### ISSUE TITLE
我乱输了个匹配不上的主机名，然后终端就卡死了

### ISSUE THREAD

**Issue by StevenSume** [jumpserver/jumpserver#1002]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0
##### 问题复现步骤
1. [步骤1]
终端上在选择连接主机的界面上乱输一个匹配不上的主机名
2. [步骤2]
回车
##### 具体表现[截图可能会更好些,最好能截全]
然后终端就卡死了，光标消失了，什么也输入不了了，只能关闭终端重新连接

##### 其他
错误发生时的日志输出如下
2018-02-06 15:49:04 [recorder DEBUG] <Session command recorder 1> queue size: 0
Exception in thread Thread-73:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/work/servers/coco/coco/sshd.py", line 96, in handle_chan
    self.dispatch(client)
  File "/work/servers/coco/coco/sshd.py", line 102, in dispatch
    InteractiveServer(self.app, client).interact()
  File "/work/servers/coco/coco/interactive.py", line 296, in interact
    rv = self.dispatch(opt)
  File "/work/servers/coco/coco/interactive.py", line 138, in dispatch
    self.search_and_proxy(opt)
  File "/work/servers/coco/coco/interactive.py", line 275, in search_and_proxy
    if len(self.search_result) == 1:
TypeError: object of type 'NoneType' has no len()

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
fixed
