### ISSUE TITLE
调用接口修改用户密码报错Invalid signature 

### ISSUE THREAD

**Issue by ok-dok** [jumpserver/jumpserver#10105]
我用了具有admin权限的账户的apiKey，通过接口/users/users/{id}/password进行patch、update修改其他用户的密码，报错返回没有权限，签名不正确。

以下是响应内容：
{"detail":"Invalid signature.","code":"authentication_failed"}

使用jumpserver版本：3.1.1

下面是我的请求日志：

> 2023-03-29 17:27:50,156 base.py[line:77] [DEBUG] send request, url=http://127.0.0.1/api/v1/users/users/bc8c5bbe-1ada-43be-b575-6897ed3b088c/password, method=PATCH, header={'user-agent': 'python-requests/2.28.2', 'accept-encoding': 'gzip, deflate', 'accept': 'application/json', 'connection': 'keep-alive', 'x-jms-org': '00000000-0000-0000-0000-000000000002', 'date': 'Wed, 29 Mar 2023 09:27:50 GMT', 'authorization': 'Signature keyId="8856ab42-7eba-42d3-81d2-0a9cbbf1157d",algorithm="hmac-sha256",signature="pyxl/xpXNIr8CnREB55hp8FmAcDG/xaFXsbU1cT3ukw=",headers="(request-target) accept date"'}, content=
2023-03-29 17:27:50,157 user.py[line:104] [WARNING] update user bc8c5bbe-1ada-43be-b575-6897ed3b088c password failed, err=HTTP 401: Unauthorized  => {"detail":"Invalid signature.","code":"authentication_failed"}

但是同样的签名方式创建用户和查询用户都没有问题。

请问是哪里不对吗？ 修改用户密码需要额外不一样的签名方式吗？还是说这是一个bug？

**Comment by BaiJiangJie** [comment]
API 调错了。

**Comment by ok-dok** [comment]
感谢解答，按照你提供的接口，我通过token方式更新用户密码成功，但是使用auth方式依然遇到同样的错误。

下面是我的日志：

> 2023-03-29 21:47:46,616 base.py[line:75] [DEBUG] send request, url=http://127.0.0.1/api/v1/users/users/, method=GET, header={'user-agent': 'python-requests/2.28.2', 'accept-encoding': 'gzip, deflate', 'accept': 'application/json', 'connection': 'keep-alive', 'x-jms-org': '00000000-0000-0000-0000-000000000002', 'content-type': 'application/json', 'date': 'Wed, 29 Mar 2023 13:47:46 GMT', 'authorization': 'Signature keyId="8856ab42-7eba-42d3-81d2-0a9cbbf1157d",algorithm="hmac-sha256",signature="+/9lZnqduEydiOH0a2f1lok26RRnzodD28Fdbw0fqhM=",headers="(request-target) accept date"'}, content=
2023-03-29 21:47:46,618 base.py[line:89] [DEBUG] recv response, header={'Server': 'nginx', 'Date': 'Wed, 29 Mar 2023 13:47:46 GMT', 'Content-Type': 'application/json', 'Content-Length': '1168', 'Connection': 'keep-alive', 'Vary': 'Accept, Accept-Language, Cookie', 'Allow': 'GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS', 'X-Frame-Options': 'DENY', 'Content-Language': 'zh-hans', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'same-origin', 'Set-Cookie': 'SESSION_COOKIE_NAME_PREFIX=jms_; Path=/'}, content=[{'id': '8a10104d-b190-4e46-b15b-a7266ef73fc2', 'name': 'test', 'username': 'dokeyhou', 'email': 'dokeyhou@xxx.com', 'wechat': '', 'phone': None, 'mfa_level': {'value': 0, 'el': '禁用'}, 'source': {'value': 'local', 'label': '数据库'}, 'wecom_id': None, 'dingtalk_id': None, 'feishu_id': None, 'created_by': 'Administrator', 'updated_by': 'Administrator', 'comment': None, 'avatar_url': '/static/img/avatar.png', 'groups': [], 'system_roles': [{'id': '00000000-0000-0000-0000-000000000003', 'display_name': '用户'}], 'org_roles': [{'id': '00000000-0000-0000-0000-000000000007', 'display_name': '组织用户', 'name': 'OrgUser'}], 'password_gy': {'value': 'email', 'label': '生成重置密码链接，通过邮件发送给用户'}, 'is_service_account': False, 'is_valid': True, 'is_expired': False, 'is_active': True, 'is_otp_secret_key_bound': False, 'can_public_key_auth': True, 'mfa_enad_update_password': True, 'mfa_force_enabled': False, 'is_first_login': True, 'login_blocked': False, 'date_expired': '2093/03/11 21:40:10 +0800', 'date_joined': '2023/03/29 21:40:32 +0800', 'last_login': None, 'date_updated': '2023/03/29 21:40:32 +0800', 'date_password_last_updated': '2023/03/29 21:40:32 +0800'}]
2023-03-29 21:47:46,697 base.py[line:75] [DEBUG] send request, url=http://127.0.0.1/api/v1/users/users/8a10104d-b190-4e46-b15b-a7266ef73fc2, method=PATCH, header={'user-agent': 'python-requests/2.28.2', 'accept-encoding': 'gzip, deflate', 'accept': 'application/json', 'connection': 'keep-alive', 'x-jms-org': '00000000-0000-0000-0000-000000000002', 'date': 'Wed, 29 Mar 2023 13:47:46 GMT', 'authorization': 'Signature keyId="8856ab42-7eba-42d3-81d2-0a9cbbf1157d",algorithm="hmac-sha256",signature="y62eLiSpdahjQfdYhcKvuQO4Vw7vcHuF1/X4KlHrjn0=",headers="(request-target) accept date"'}, content=
2023-03-29 21:47:46,697 user.py[line:81] [WARNING] update user 8a10104d-b190-4e46-b15b-a7266ef73fc2 password failed, err=HTTP 401: Unauthorized  => {"detail":"Invalid signature.","code":"authentication_failed"}
Traceback (most recent call last):
  File "/Users/dokey/Workspace/python/jumpserver-bot/api/base.py", line 94, in api_request
    response.raise_for_status()
  File "/Users/dokey/Workspace/python/jumpserver-bot/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://30.7.129.245/api/v1/users/users/8a10104d-b190-4e46-b15b-a7266ef73fc2/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dokey/Workspace/python/jumpserver-bot/api/user.py", line 78, in update_password
    res = self.client.api_patch(path, data={"password": password})
  File "/Users/dokey/Workspace/python/jumpserver-bot/api/base.py", line 108, in api_patch
    return self.api_request(path, params, data, method="patch")
  File "/Users/dokey/Workspace/python/jumpserver-bot/api/base.py", line 143, in api_request
    return super(ApiAuthClient, self).api_request(path, params, data, method, self.auth)
  File "/Users/dokey/Workspace/python/jumpserver-bot/api/base.py", line 96, in api_request
    raise ApiRequestError(response.status_code, response.reason, response.text, err=err)
api.base.ApiRequestError: HTTP 401: Unauthorized  => {"detail":"Invalid signature.","code":"authentication_failed"}
F
======================================================================
FAIL: test5_update_password (__main__.UserAuthTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dokey/Workspace/python/jumpserver-bot/test/test_password.py", line 29, in test5_update_password

**Comment by ok-dok** [comment]
我知道原因了，是url最后少了/导致的。在最后加了“/"通过了。

错误的地址：url=http://127.0.0.1/api/v1/users/users/8a10104d-b190-4e46-b15b-a7266ef73fc2
正确的地址是：url=http://127.0.0.1/api/v1/users/users/8a10104d-b190-4e46-b15b-a7266ef73fc2/

**Comment by ok-dok** [comment]
感谢，问题解决。
