### ISSUE TITLE
[Bug] 账号推送手动执行后，验证测试报错

### ISSUE THREAD

**Issue by Anorpi** [jumpserver/jumpserver#10204]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
JumpServer  v3.1.2
通过 jmsctl.sh  upgrade 命令将 v2.28 升级到  v3.1.2的

**浏览器版本**
Chrome 版本 111.0.5563.147（正式版本） （64 位）

**Bug 描述**
使用 账号管理-账号推送 手动执行后，生成的账号点击测试报错如下：

```python
Task accounts.tasks.verify_account.verify_accounts_connectivity_task[44bd5213-e063-4e03-9af4-67066e496c5c] raised unexpected: AttributeError("'NoneType' object has no attribute 'encode'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/accounts/tasks/verify_account.py", line 57, in verify_accounts_connectivity_task
    return verify_accounts_connectivity_util(accounts, task_name)
  File "/opt/jumpserver/apps/orgs/utils.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/opt/jumpserver/apps/accounts/tasks/verify_account.py", line 42, in verify_accounts_connectivity_util
    verify_connectivity_util(
  File "/opt/jumpserver/apps/accounts/tasks/verify_account.py", line 25, in verify_connectivity_util
    quickstart_automation_by_snapshot(task_name, tp, task_snapshot)
  File "/opt/jumpserver/apps/accounts/tasks/common.py", line 18, in quickstart_automation_by_snapshot
    execution.start()
  File "/opt/jumpserver/apps/accounts/models/automations/base.py", line 45, in start
    return manager.run()
  File "/opt/jumpserver/apps/accounts/automations/endpoint.py", line 26, in run
    return self._runner.run(*args, **kwargs)
  File "/opt/jumpserver/apps/assets/automations/base/manager.py", line 285, in run
    runners = self.get_runners()
  File "/opt/jumpserver/apps/assets/automations/base/manager.py", line 180, in get_runners
    self.generate_inventory(_assets, inventory_path)
  File "/opt/jumpserver/apps/assets/automations/base/manager.py", line 146, in generate_inventory
    inventory.write_to_file(inventory_path)
  File "/opt/jumpserver/apps/ops/ansible/inventory.py", line 229, in write_to_file
    data = self.generate(path_dir)
  File "/opt/jumpserver/apps/ops/ansible/inventory.py", line 199, in generate
    host = self.host_callback(
  File "/opt/jumpserver/apps/accounts/automations/verify_account/manager.py", line 58, in host_callback
    private_key_path = self.generate_private_key_path(secret, path_dir)
  File "/opt/jumpserver/apps/assets/automations/base/manager.py", line 125, in generate_private_key_path
    key_name = '.' + md5(secret.encode('utf-8')).hexdigest()
AttributeError: 'NoneType' object has no attribute 'encode'

```

**Bug 重现步骤(有截图更好)**
1.进入 “账号管理“-”账号推送“ 设置好推送后，点击推送。
2.返回 ”账号列表“ 找到推送的新账号，类型xxx-ssh_key 的格式。点击后面的”更多“-”测试“
3.发生报错

**Comment by BaiJiangJie** [comment]
好的，我们来本地复现一下。

你看查看一下账号的密码/密钥，是否有值？

**Comment by Anorpi** [comment]
> 好的，我们来本地复现一下。
> 
> 你看查看一下账号的密码/密钥，是否有值？

点击查看确实是空的，但我 “账号推送” 那里确实是输入了“私钥内容”的。
又测了下，输入密码不会有这种报错，但填入的是 “私钥” 的话，推送过去 点 “测试” 就会报错，点击查看是空白。
另外 “账号推送” 里设置“账号” 的时候，可以让从 “账号模板” 选择吗？ 不然挺麻烦的。

**Comment by BaiJiangJie** [comment]
`另外 “账号推送” 里设置“账号” 的时候，可以让从 “账号模板” 选择吗？ 不然挺麻烦的。`

暂时还不支持，不过可以考虑支持选择`账号模版`。


`点击查看确实是空的，但我 “账号推送” 那里确实是输入了“私钥内容”的。
又测了下，输入密码不会有这种报错，但填入的是 “私钥” 的话，推送过去 点 “测试” 就会报错，点击查看是空白。`

这个问题在 v3.2 中会修复。

**Comment by BaiJiangJie** [comment]
账号推送中选择模版暂时不考虑支持。
