### ISSUE TITLE
[Question] 连接VSCode问题

### ISSUE THREAD

**Issue by bacterous** [jumpserver/jumpserver#10241]
在官方配置VSCode连接的[教程](https://kb.fit2cloud.com/?p=48)中，按照**编辑配置文件法**进行配置之后，VSCode还是无法成功连接，报错信息为：
```[18:08:54.552] > ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
[18:08:55.822] "install" terminal command done
[18:08:55.822] Install terminal quit with output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
[18:08:55.822] Received install output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
[18:08:55.823] Failed to parse remote port from server output
[18:08:55.824] Resolver error: Error: 
	at m.Create (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:584145)
	at t.handleInstallOutput (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:582705)
	at t.tryInstall (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:681555)
	at async c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:643798
	at async t.withShowDetailsEvent (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:647116)
	at async t.resolve (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:644848)
	at async c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:720590
[18:08:55.830] ------
```

在终端中，利用以下命令可以直接连接：
`ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222`

另外注意到，[教程](https://kb.fit2cloud.com/?p=48)中在VSCode中登录了Jumpserver之后，直接连接成功了资产。这是不是意味着，VSCode连接时，是需要资产先在Jumpserver中托管密码之后才可以成功连接，是否支持像在终端中两次输入密码连接呢。

**Comment by wojiushixiaobai** [comment]
只支持自动登录的，输入两次密码的不支持

**Comment by Cerdore** [comment]
> 只支持自动登录的，输入两次密码的不支持



> 只支持自动登录的，输入两次密码的不支持

我司也用了jumpserver，然后只有我的vscode连接不上，报错同上...  
我的vscode只有在jumpserver网站上连一下内嵌终端才能连得上。而我其他同事都可以直接连上....

**Comment by edentliang** [comment]
> 在官方配置VSCode连接的[教程](https://kb.fit2cloud.com/?p=48)中，按照**编辑配置文件法**进行配置之后，VSCode还是无法成功连接，报错信息为：
> 
> ```
> [18:08:55.822] "install" terminal command done
> [18:08:55.822] Install terminal quit with output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
> [18:08:55.822] Received install output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
> [18:08:55.823] Failed to parse remote port from server output
> [18:08:55.824] Resolver error: Error: 
> 	at m.Create (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:584145)
> 	at t.handleInstallOutput (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:582705)
> 	at t.tryInstall (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:681555)
> 	at async c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:643798
> 	at async t.withShowDetailsEvent (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:647116)
> 	at async t.resolve (c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:644848)
> 	at async c:\Users\bacte\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:720590
> [18:08:55.830] ------
> ```
> 
> 在终端中，利用以下命令可以直接连接： `ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222`
> 
> 另外注意到，[教程](https://kb.fit2cloud.com/?p=48)中在VSCode中登录了Jumpserver之后，直接连接成功了资产。这是不是意味着，VSCode连接时，是需要资产先在Jumpserver中托管密码之后才可以成功连接，是否支持像在终端中两次输入密码连接呢。

相同的连接错误，有解决方法嘛

**Comment by wml3** [comment]
注意你的资产是否能连通外网，首次连接时，会要求下载vscode插件。如果不能连外网，可以找一台可连接的，拷贝插件。

**Comment by edentliang** [comment]
能连外网的，之前就是用vscode 直连资产
