### ISSUE TITLE
[Bug] v3.1.2的创建host的api文档platform示例字段值格式不对。

### ISSUE THREAD

**Issue by yuanhaoliang** [jumpserver/jumpserver#10277]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.1.2

**浏览器版本**
chrome

**Bug 描述**
![image](https://user-images.githubusercontent.com/2853517/233292851-30be14b8-de64-4bea-b37b-dd29486679aa.png)
![image](https://user-images.githubusercontent.com/2853517/233293016-94a09016-b715-430f-944e-9f8c8323879b.png)

platform的示例值是写一个字符串，例如"Linux“，在2.8的版本，这样写是可以的，但是在v3里是不行的。这样写会报错

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/assets/api/asset/asset.py", line 145, in create
    return super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework_bulk/drf3/mixins.py", line 29, in create
    return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 256, in is_valid
    return super().is_valid(raise_exception)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/opt/jumpserver/apps/common/serializers/mixin.py", line 81, in run_validation
    return super().run_validation(data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/opt/jumpserver/apps/common/serializers/mixin.py", line 50, in to_internal_value
    ret = super(BulkSerializerMixin, self).to_internal_value(data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 267, in validate_protocols
    protocols_required, protocols_default = self._get_protocols_required_default()
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 162, in _get_protocols_required_default
    platform = self._asset_platform
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 226, in _asset_platform
    platform = Platform.objects.filter(id=platform_id).first()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1370, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1216, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'Linux'.
```

platform字段值正确写法是：（其实get出来是这个格式的）
```
{
    "name": "test",
    "address": "10.10.1.1",
    "platform": {
      "id": 1,
      "name": "Linux"
    },
    "protocols":
    [
        {
            "name": "ssh",
            "port": 22
        }
    ],
}
```

**Comment by BaiJiangJie** [comment]
v3 版本的 platform 仅允许输入`平台ID`，比如 Linux 平台的 ID 为 “1”。

![901682070962_ pic](https://user-images.githubusercontent.com/32935519/233607169-ef5ddb21-dd7f-49a8-b86f-3b21c2fe1817.jpg)

![911682070982_ pic](https://user-images.githubusercontent.com/32935519/233607247-fa376d90-1a1b-45ab-835d-fb00611cc681.jpg)
