### ISSUE TITLE
点击管理用户报错

### ISSUE THREAD

**Issue by kaka1992** [jumpserver/jumpserver#1032]
[简述你的问题]
1. 点击管理用户报错
2. 之前的授权数据消失
##### 使用版本
0.5.0

##### 问题复现步骤
1. 点击管理用户报错
##### 具体表现[截图可能会更好些,最好能截全]
2018-03-01 11:58:05 [exception ERROR] Internal Server Error: /api/assets/v1/admin-user/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 738, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 656, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 656, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 500, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/fields.py", line 1816, in to_representation
    return method(value)
  File "/etc/jumpserver/apps/assets/serializers/admin_user.py", line 39, in get_assets_amount
    return obj.assets_amount
  File "/etc/jumpserver/apps/assets/models/user.py", line 186, in assets_amount
    return len(self.get_related_assets())
  File "/etc/jumpserver/apps/assets/models/user.py", line 180, in get_related_assets
    assets.extend(cluster.assets.all())
AttributeError: 'Cluster' object has no attribute 'assets'

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
1. fixed
2. 需要重新添加授权规则，因为现在授权规则改成以node的方式授权了
