### ISSUE TITLE
[Bug] v2.26.1升级v2.28.9报错

### ISSUE THREAD

**Issue by louishot** [jumpserver/jumpserver#10369]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**Bug 描述**

```
3. Backup database
Backing up...
[SUCCESS] Backup succeeded! The backup file has been saved to: /opt/jumpserver/db_backup/jumpserver-v2.26.1-2023-04-28_14:20:30.sql

4. Backup Configuration File
Back up to /opt/jumpserver/db_backup/config-v2.26.1-2023-04-28_14:20:37.conf

5. Apply database changes
Changing database schema may take a while, please wait patiently
Detected that the JumpServer container is running. Do you want to close the container and continue to upgrade? (y/n)  (default y): y

Stopping jms_core ... done
Stopping jms_koko ... done
Stopping jms_lion ... done
Stopping jms_magnus ... done
Stopping jms_web ... done
Stopping jms_celery ... done
Removing jms_core ... done
Removing jms_koko ... done
Removing jms_lion ... done
Removing jms_magnus ... done
Removing jms_web ... done
Removing jms_celery ... done

jms_mysql is up-to-date
jms_redis is up-to-date
Creating jms_core ... done
2023-04-28 22:23:10 Collect static files
2023-04-28 22:23:11 Collect static files done
2023-04-28 22:23:11 Check database structure change ...
2023-04-28 22:23:11 Migrate model change to database ...
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying applications.0024_alter_application_type... OK
  Applying assets.0092_commandfilter_nodes...2023-04-28 22:23:12 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1005, 'Can\'t create table `jumpserver`.`assets_commandfilter_nodes` (errno: 150 "Foreign key constraint is incorrectly formed")')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./jms", line 87, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 230, in apply_migration
    migration_recorded = True
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 118, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1005, 'Can\'t create table `jumpserver`.`assets_commandfilter_nodes` (errno: 150 "Foreign key constraint is incorrectly formed")')
[ERROR] Failed to change the table structure!
root@jumpserver-2024-04-25:/opt/jumpserver-offline-installer-v2.28.9-amd64-8# 
```

**Comment by louishot** [comment]
我删除数据库用下面这命令重建了数据库然后导入备份数据再升级就正常。

`CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_bin */`
