### ISSUE TITLE
[Question] 配置 LDAP 登陆，如果 OU 配置多个，则登陆会报错

### ISSUE THREAD

**Issue by cobolbaby** [jumpserver/jumpserver#10383]
**请描述您的问题.**

配置 LDAP 登陆，如果 OU 配置多个，则登陆会报错

![2023-05-04 12-04-22屏幕截图](https://user-images.githubusercontent.com/11460848/236161936-868a0940-9898-4160-be8f-7e840c2ca1d9.png)

查看日志 docker exec -it jms_core /bin/bash && cat logs/jumpserver.log

```log
2023-05-04 17:07:03 [ldap INFO] Authentication LDAP backend
2023-05-04 17:07:03 [config ERROR] result(3) raised OPERATIONS_ERROR({'msgtype': 101, 'msgid': 3, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A5A, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4f7c'})
2023-05-04 17:07:07 [config ERROR] search_s('CN=Zhang\, Xing-Long (張興龍 TSA/ITC),OU=Support Accounts,OU=ITC Users,DC=itc,DC=inventec', 0, '(objectClass=*)') raised OPERATIONS_ERROR({'msgtype': 101, 'msgid': 7, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A5A, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4f7c'})
2023-05-04 17:07:07 [config ERROR] search_s('CN=Zhang\, Xing-Long (張興龍 TSA/ITC),OU=Support Accounts,OU=ITC Users,DC=itc,DC=inventec', 0, '(objectClass=*)') raised OPERATIONS_ERROR({'msgtype': 101, 'msgid': 13, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A5A, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4f7c'})
2023-05-04 17:07:07 [backend WARNING] 'NoneType' object is not subscriptable while authenticating TSA180012
2023-05-04 17:07:07 [log ERROR] Internal Server Error: /core/auth/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/opt/jumpserver/apps/authentication/views/login.py", line 211, in form_valid
    self.check_user_auth(form.cleaned_data)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 436, in check_user_auth
    user = self._check_auth_user_is_valid(username, password, public_key)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 404, in _check_auth_user_is_valid
    user = authenticate(
  File "/opt/jumpserver/apps/authentication/mixins.py", line 71, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/jumpserver/apps/authentication/backends/ldap.py", line 86, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 211, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 355, in authenticate
    self._get_or_create_user()
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 606, in _get_or_create_user
    self._user, built = self.backend.get_or_build_user(username, self)
  File "/opt/jumpserver/apps/authentication/backends/ldap.py", line 40, in get_or_build_user
    query_value = ldap_user.attrs[self.settings.USER_ATTR_MAP[query_field]][0]
TypeError: 'NoneType' object is not subscriptable
2023-05-04 17:07:12 [config ERROR] search_s('CN=Zhang\, Xing-Long (張興龍 TSA/ITC),OU=Support Accounts,OU=ITC Users,DC=itc,DC=inventec', 0, '(objectClass=*)') raised OPERATIONS_ERROR({'msgtype': 101, 'msgid': 7, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A5A, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4f7c'})
2023-05-04 17:07:12 [config ERROR] search_s('CN=Zhang\, Xing-Long (張興龍 TSA/ITC),OU=Support Accounts,OU=ITC Users,DC=itc,DC=inventec', 0, '(objectClass=*)') raised OPERATIONS_ERROR({'msgtype': 101, 'msgid': 13, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A5A, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v4f7c'})
2023-05-04 17:07:12 [backend WARNING] 'NoneType' object is not subscriptable while authenticating TSA180012
2023-05-04 17:07:12 [log ERROR] Internal Server Error: /core/auth/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 490, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/opt/jumpserver/apps/authentication/views/login.py", line 211, in form_valid
    self.check_user_auth(form.cleaned_data)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 436, in check_user_auth
    user = self._check_auth_user_is_valid(username, password, public_key)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 404, in _check_auth_user_is_valid
    user = authenticate(
  File "/opt/jumpserver/apps/authentication/mixins.py", line 71, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/jumpserver/apps/authentication/backends/ldap.py", line 86, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 211, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 355, in authenticate
    self._get_or_create_user()
  File "/usr/local/lib/python3.9/site-packages/django_auth_ldap/backend.py", line 606, in _get_or_create_user
    self._user, built = self.backend.get_or_build_user(username, self)
  File "/opt/jumpserver/apps/authentication/backends/ldap.py", line 40, in get_or_build_user
    query_value = ldap_user.attrs[self.settings.USER_ATTR_MAP[query_field]][0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by cobolbaby** [comment]
官方文档 https://docs.jumpserver.org/zh/v3/guide/env/#1-core 中有提到将配置:

```
AUTH_LDAP_OPTIONS_OPT_REFERRALS=-1         # LDAP 认证时如果日志中出现以下信息将参数设置为 0
```

我在修改了 /opt/jumpserver/config/config.txt 中配置之后，执行了 `/opt/jumpserver-installer-v3.1.1 &&  ./jmsctl.sh restart`，然后再次尝试，发现报错依旧。

是配置修改方式不对造成配置没有生效？还是其他问题？

**Comment by ibuler** [comment]
截图看看你的 LDAP 配置，应该是映射字段出问题了

**Comment by cobolbaby** [comment]
如果我想单步调试一下，请问我最少需要部署哪些服务模块？有没有开发者文档之类的？

**Comment by wojiushixiaobai** [comment]
参考 - pingidentity/ldapsdk#142

**Comment by cobolbaby** [comment]
@wojiushixiaobai [django-auth-ldap](https://github.com/django-auth-ldap/django-auth-ldap) 貌似还不支持．

相关问题: [Using django-auth-ldap with Microsoft ad #305](https://github.com/django-auth-ldap/django-auth-ldap/issues/305)

**Comment by BaiJiangJie** [comment]
应该是 LDAP 返回的属性中没有 sAMAccountName 值。

**Comment by wojiushixiaobai** [comment]
@cobolbaby 那估计得等上游先解决此问题，感谢反馈。

**Comment by cobolbaby** [comment]
> 也可能是跨域的问题，图片中把 a.com 的 OU 删掉试一下呢？

@BaiJiangJie  我再解释一下上图的配置，有两个 LDAP Server，a.com / b.com，我在 JumpServer 上配置的 LDAP Server 是 b.com，为了让 a.com 下的用户也可以登录到堡垒机，我就请 LDAP 管理员在 b.com 中添加 a.com 的域信任配置。但配置之后我发现，b.com 下的用户可以正常登录，但 a.com 下的用户还是无法正常登录。

此时如果我将 JumpServer 上配置的 LDAP Server 换成 a.com，那 a.com 下的用户可以正常登录，而 b.com 下的用户就不行了。所以应该不是 `映射字段出问题` 或 `没有 sAMAccountName 值`。

> 如果我想单步调试一下，请问我最少需要部署哪些服务模块？有没有开发者文档之类的？

@wojiushixiaobai @BaiJiangJie 如果我想单步调试这块的功能，请问我需要怎么构建 Debug 环境？我看 JumpServer 子服务比较多，我希望部署一个最小集。

**Comment by BaiJiangJie** [comment]
要调试的话，你需要搭建一个开发环境，启动 core 服务 和 lina 服务即可；

然后根据报错信息 Debug 查看返回的数据信息；

**Comment by cobolbaby** [comment]
> 所以说，是后端在拿着你 a.com 的 OU，去 b.com 下获取用户信息时没获取到。

不是没有返回，是返回了一个  REF，相当于跳转连接，而 django-auth-ldap 貌似不处理这种情况:

```
# search result
search: 2
result: 10 Referral
text: 0000202B: RefErr: DSID-0310079D, data 0, 1 access points
	ref 1: 'itc.inventec'

ref: ldap://itc.inventec/OU=Support%20Accounts,OU=ITC%20Users,DC=itc,DC=inventec
```

**Comment by cobolbaby** [comment]
> 要调试的话，你需要搭建一个开发环境，启动 core 服务 和 lina 服务即可；

搭建开发环境有没有说明文档，目前我没找到。另外 MySQL 和 Redis 等服务是必须安装的吗？

**Comment by BaiJiangJie** [comment]
`另外 MySQL 和 Redis 等服务是必须安装的吗？`
是的，必须都要安装；

`搭建开发环境有没有说明文档，目前我没找到。`
相当于源码部署，可以参考下面文档的链接；
https://docs.jumpserver.org/zh/v3/installation/source_install/core_install/

**Comment by BaiJiangJie** [comment]
`不是没有返回，是返回了一个 REF，相当于跳转连接，而 django-auth-ldap 貌似不处理这种情况:`

那就得自己去 Debug 了。

**Comment by cobolbaby** [comment]
> 另外 MySQL 和 Redis 等服务是必须安装的吗？

有没有快速搭建这两个服务的办法？`jmsctl.sh` 能不能将这两个服务一键起来，并且做好数据初始化？

**Comment by saszhuqing** [comment]
> > 也可能是跨域的问题，图片中把 a.com 的 OU 删掉试一下呢？
> 
> @BaiJiangJie 我再解释一下上图的配置，有两个 LDAP Server，a.com / b.com，我在 JumpServer 上配置的 LDAP Server 是 b.com，为了让 a.com 下的用户也可以登录到堡垒机，我就请 LDAP 管理员在 b.com 中添加 a.com 的域信任配置。但配置之后我发现，b.com 下的用户可以正常登录，但 a.com 下的用户还是无法正常登录。
> 
> 此时如果我将 JumpServer 上配置的 LDAP Server 换成 a.com，那 a.com 下的用户可以正常登录，而 b.com 下的用户就不行了。所以应该不是 `映射字段出问题` 或 `没有 sAMAccountName 值`。
> 
> > 如果我想单步调试一下，请问我最少需要部署哪些服务模块？有没有开发者文档之类的？
> 
> @wojiushixiaobai @BaiJiangJie 如果我想单步调试这块的功能，请问我需要怎么构建 Debug 环境？我看 JumpServer 子服务比较多，我希望部署一个最小集。

我之前测试过同一林下的根域和子域，也是同样的报错信息。
ladp server 设置为根域 abc.com , 在认证设置里用子域 a.abc.com 的账号“测试登录”是成功的，“用户导入”也是成功的，但在登录时就会报错 Server error occur

**Comment by cobolbaby** [comment]
> 子域 a.abc.com 的账号“测试登录”是成功的，“用户导入”也是成功的

用户导入的确没障碍，不过我没做“测试登录”验证。

**Comment by BaiJiangJie** [comment]
处理逻辑上基本是相同的，`但在登录时就会报错 Server error occur` 看一下后端 core 服务的日志，jumpserver.log 文件； 

`用户导入的确没障碍，不过我没做“测试登录”验证。` 导入没问题，测试连接有问题？

@cobolbaby @saszhuqing

**Comment by saszhuqing** [comment]
我找到原因了，需要在 ldap server 中添加 3268 端口进行全局目录搜索才能找到其他域内的用户，ldap://192.168.1.1:3268
搜索了一下 jumpserver.log 中的这个关键内容 In order to perform this operation a successful bind must be completed on the connection，找了这个文章 https://stackoverflow.com/questions/3363377/cant-bind-for-successful-connection，然后找到了微软官方 https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc978012(v=technet.10)?redirectedfrom=MSDN
我这边经过测试，ldap server 设置为根域 abc.com 的域控服务器 , 可以用子域 a.abc.com 里的用户账号正常登录了。
@cobolbaby @wojiushixiaobai
