### ISSUE TITLE
终端登陆后输入命令显示有权限的主机命令后卡死

### ISSUE THREAD

**Issue by clangcn** [jumpserver/jumpserver#1060]
[简述你的问题]
通过coco登录跳板机，输入p，查询有权限的主机，结果卡死，在coco中直接输入服务器ip地址，可以连接到服务器，就是不能用p和g命令，用luna可以正常登录主机。

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
centos7.4
根据http://docs.jumpserver.org/zh/latest/step_by_step.html一步步安装
使用的是0.5.0版本
##### 问题复现步骤
1. [步骤1]
新安装没有添加任何服务器资源的时候，命令G输入后可以显示结果“无”，输入P后卡住不动。
添加服务器资源并授权，ssh登录跳板机，然后输入命令p显示有权限的主机，输入后界面卡住不动
重新连接跳板机，在命令行中直接输入要连接的服务器完整IP地址，可以登录服务器，简写ip地址同样卡死。
在有服务器资源并授权后，输入G命令同样卡死。
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
<img width="557" alt="37038569-1f0b1d04-2190-11e8-8913-4ebec0c0469e" src="https://user-images.githubusercontent.com/17767687/37141074-df658990-22ee-11e8-81cf-15d6e3f1b5ff.png">

后台显示日志：
```
127.0.0.1 - - [06/Mar/2018 22:45:25] "GET /socket.io/?EIO=3&transport=polling&t=M3znSqt&sid=1d2713d09fj64bc2a7205c016ad4e183 HTTP/1.1" 200 - 
2018-03-06 22:45:26 [recorder DEBUG] <Session command recorder 1> queue size: 0                                                             
2018-03-06 22:45:31 [recorder DEBUG] <Session command recorder 1> queue size: 0
2018-03-06 22:45:33 [interactive DEBUG] b'p'                                   
2018-03-06 22:45:33 [interactive DEBUG] b'\r'                                  
Exception in thread Thread-125:                                                
Traceback (most recent call last):                                             
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                                
    self.run()                                                                                                                              
  File "/usr/local/lib/python3.6/threading.py", line 864, in run               
    self._target(*self._args, **self._kwargs)                                  
  File "/opt/coco/coco/sshd.py", line 90, in handle_chan                       
    self.dispatch(client)                                                      
  File "/opt/coco/coco/sshd.py", line 96, in dispatch
    InteractiveServer(self.app, client).interact()
  File "/opt/coco/coco/interactive.py", line 310, in interact
    rv = self.dispatch(opt)
  File "/opt/coco/coco/interactive.py", line 137, in dispatch
    self.display_assets()
  File "/opt/coco/coco/interactive.py", line 178, in display_assets
    self.search_and_display('')
  File "/opt/coco/coco/interactive.py", line 231, in search_and_display
    self.display_search_result()
  File "/opt/coco/coco/interactive.py", line 219, in display_search_result
    comment_length = self.request.meta["width"] - len(header.format(fake_asset, id_max_length))
KeyError: 'width'

2018-03-06 22:45:36 [recorder DEBUG] <Session command recorder 1> queue size: 0
```
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
fixed

**Comment by clangcn** [comment]
刚刚重新clone了一下coco项目，还是一样的错误。
···
256 bits) (active; 1 open channel(s))>>
2018-03-08 20:47:10 [interface INFO] Check channel shell request: 0
2018-03-08 20:47:11 [interactive DEBUG] b'p'
2018-03-08 20:47:11 [interactive DEBUG] b'\r'
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/sshd.py", line 90, in handle_chan
    self.dispatch(client)
  File "/opt/coco/coco/sshd.py", line 96, in dispatch
    InteractiveServer(self.app, client).interact()
  File "/opt/coco/coco/interactive.py", line 311, in interact
    rv = self.dispatch(opt)
  File "/opt/coco/coco/interactive.py", line 138, in dispatch
    self.display_assets()
  File "/opt/coco/coco/interactive.py", line 179, in display_assets
    self.search_and_display('')
  File "/opt/coco/coco/interactive.py", line 232, in search_and_display
    self.display_search_result()
  File "/opt/coco/coco/interactive.py", line 220, in display_search_result
    comment_length = self.request.meta["width"] - len(header.format(fake_asset, id_max_length))
KeyError: 'width'

···

**Comment by clangcn** [comment]
已经发现问题了，是SecureCRT设置问题，在coco的session设置里，将ssh2的高级选项里“Enable OpenSSH agent forwarding”勾选去掉，就可以正常了
<img width="783" alt="wx20180309-223221 2x" src="https://user-images.githubusercontent.com/17767687/37212344-c4e6d4a6-23e9-11e8-80c6-6f8fa53b8ada.png">
