### ISSUE TITLE
3.3.1版本中升级怎么变成2.28.15了，然后升级报错了[Question] 

### ISSUE THREAD

**Issue by davie89** [jumpserver/jumpserver#10658]
**请描述您的问题.**
5. 进行数据库变更
表结构变更可能需要一段时间, 请耐心等待
[+] Running 3/3
 ✔ Container jms_mysql  Healthy                                                                                                                     0.5s 
 ✔ Container jms_redis  Healthy                                                                                                                     0.5s 
 ✔ Container jms_core   Started                                                                                                                     0.9s 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'applications_application.domain_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./jms", line 21, in <module>
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 15, in ready
    django_ready.send(CommonConfig)
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/jumpserver/apps/terminal/signal_handlers.py", line 22, in check_db_port_mapper
    db_port_manager.check()
  File "/opt/jumpserver/apps/terminal/utils/db_port_mapper.py", line 46, in check
    for db in dbs:
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'applications_application.domain_id' in 'field list'")
[ERROR] 表结构变更失败!

**Comment by lunzai** [comment]
安装也出现同样的问题
![image](https://github.com/jumpserver/jumpserver/assets/1671136/4be44659-51d9-4638-a469-08aa99e15062)

**Comment by wojiushixiaobai** [comment]
@lunzai 说明操作过程

**Comment by jym503558564** [comment]
升级请严格参照官方文档进行升级，如还有问题可将报错日志贴出来。
