### ISSUE TITLE
[Question] v3.4.1升级到v3.5.0失败，django.db.utils.IntegrityError: Cannot add foreign key constraint

### ISSUE THREAD

**Issue by jibill** [jumpserver/jumpserver#11047]
**请描述您的问题.**
v3.4.1升级到v3.5.0失败，django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')

```
5. Apply database changes
Changing database schema may take a while, please wait patiently
Recreating jms_redis ... done
Creating jms_core    ... done
2023-07-22 03:44:51 [db_port INFO] Check oracle ports (MAGNUS_ORACLE_PORTS)
2023-07-22 03:44:51 Collect static files
2023-07-22 03:44:51 Collect static files done
2023-07-22 03:44:51 Check database structure change ...
2023-07-22 03:44:51 Migrate model change to database ...
Operations to perform:
  Apply all migrations: accounts, acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying assets.0120_auto_20230630_1613...2023-07-22 03:44:53 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1215, 'Cannot add foreign key constraint')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 230, in apply_migration
    migration_recorded = True
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 118, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')
[ERROR] Failed to change the table structure!
```

补充
```
2023-07-22 02:44:53 0x7ff53bf1f700 Error in foreign key constraint of table jumpserver/#sql-19e6_3aa:
 FOREIGN KEY (`asset_ptr_id`) REFERENCES `assets_asset` (`id`):
Cannot find an index in the referenced table where the
referenced columns appear as the first columns, or column types
in the table and the referenced table do not match for constraint.
Note that the internal storage type of ENUM and SET changed in
tables created with >= InnoDB-4.1.12, and such columns in old tables
cannot be referenced by such columns in new tables.
Please refer to http://dev.mysql.com/doc/refman/5.7/en/innodb-foreign-key-constraints.html for correct foreign key definition.
```

**Comment by jibill** [comment]
### 字符集的问题
此次升级又包含了迁移，先从原来的库迁移过来，发现好多表的字段中指定的character set。
挺奇怪，之前升级前，都是先mysqldump复制个库做升级测试，都可行，这次升级也是Mysqldump，结果就出现了assets_gpt这表张的asset_ptr_id引用不上assets_asset` (`id`)这个表的ID，看了assets_asset的ID字段的字符集发现和库默认的字符集不一致，修改为`asset_ptr_id` char(32) CHARACTER SET utf8 NOT NULL,之后就可以了。
```sql
CREATE TABLE `jms`.`assets_gpt`  (
  `asset_ptr_id` char(32) NOT NULL,
  `proxy` varchar(128) NOT NULL,
  PRIMARY KEY (`asset_ptr_id`) USING BTREE,
  CONSTRAINT `assets_gpt_asset_ptr_id_b92bbec5_fk_assets_asset_id` FOREIGN KEY (`asset_ptr_id`) REFERENCES `jms`.`assets_asset` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB ROW_FORMAT = Dynamic;
```

### 并没有解决
但是事情还没有结束，我发现字符集不一致导致v3.5并不能正确的启动
```
Creating jms_core ... done
ERROR: for web  Container "afc2455e820f" is unhealthy.
ERROR: for magnus  Container "afc2455e820f" is unhealthy.
ERROR: for koko  Container "afc2455e820f" is unhealthy.
ERROR: for kael  Container "afc2455e820f" is unhealthy.
ERROR: for celery  Container "afc2455e820f" is unhealthy.
ERROR: for lion  Container "afc2455e820f" is unhealthy.
ERROR: for chen  Container "afc2455e820f" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

> 即使是使用jmsctl backup_db也是如此

### 表结构对比
于是用新库重新安装了v3.5，使用了工具对比表结构，修改字符集一致后。
最后附加v3.4.1 to v3.5.0表的修改
```
ALTER TABLE `jms`.`terminal_endpointrule` ADD COLUMN `is_active` tinyint(1) NOT NULL AFTER `endpoint_id`;

CREATE TABLE `jms`.`assets_gpt`  (
  `asset_ptr_id` char(32) NOT NULL,
  `proxy` varchar(128) NOT NULL,
  PRIMARY KEY (`asset_ptr_id`) USING BTREE,
  CONSTRAINT `assets_gpt_asset_ptr_id_b92bbec5_fk_assets_asset_id` FOREIGN KEY (`asset_ptr_id`) REFERENCES `jms`.`assets_asset` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB ROW_FORMAT = Dynamic;
```

### 最后
问题解决了
