### ISSUE TITLE
[Bug] 批量修改接口/api/v1/assets/assets/返回500报错

### ISSUE THREAD

**Issue by jibill** [jumpserver/jumpserver#11052]
**请描述您的问题.**
报错如下。
```
Environment:

Request Method: PATCH
Request URL: http://10.0.1.88/api/v1/assets/assets/

Django Version: 3.2.20
Python Version: 3.9.17
Installed Applications:
['orgs.apps.OrgsConfig',
 'users.apps.UsersConfig',
 'assets.apps.AssetsConfig',
 'accounts.apps.AccountsConfig',
 'perms.apps.PermsConfig',
 'ops.apps.OpsConfig',
 'settings.apps.SettingsConfig',
 'terminal.apps.TerminalConfig',
 'audits.apps.AuditsConfig',
 'authentication.apps.AuthenticationConfig',
 'applications.apps.ApplicationsConfig',
 'tickets.apps.TicketsConfig',
 'acls.apps.AclsConfig',
 'notifications.apps.NotificationsConfig',
 'rbac.apps.RBACConfig',
 'jms_oidc_rp',
 'rest_framework',
 'rest_framework_swagger',
 'drf_yasg',
 'django_cas_ng',
 'channels',
 'django_filters',
 'bootstrap3',
 'captcha',
 'private_storage',
 'django_celery_beat',
 'django.contrib.auth',
 'django.contrib.admin',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.forms',
 'common.apps.CommonConfig',
 'simple_history']
Installed Middleware:
['jumpserver.middleware.StartMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'jumpserver.middleware.TimezoneMiddleware',
 'jumpserver.middleware.DemoMiddleware',
 'jumpserver.middleware.RequestMiddleware',
 'jumpserver.middleware.RefererCheckMiddleware',
 'jumpserver.middleware.SQLCountMiddleware',
 'orgs.middleware.OrgMiddleware',
 'authentication.backends.oidc.middleware.OIDCRefreshIDTokenMiddleware',
 'authentication.backends.cas.middleware.CASMiddleware',
 'authentication.middleware.MFAMiddleware',
 'authentication.middleware.ThirdPartyLoginMiddleware',
 'authentication.middleware.SessionCookieMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware',
 'jumpserver.middleware.EndMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework_bulk/drf3/mixins.py", line 79, in partial_bulk_update
    return self.bulk_update(request, *args, **kwargs)
  File "/opt/jumpserver/apps/assets/api/asset/asset.py", line 181, in bulk_update
    response = super().bulk_update(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework_bulk/drf3/mixins.py", line 67, in bulk_update
    serializer = self.get_serializer(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 122, in __new__
    return cls.many_init(*args, **kwargs)
  File "/opt/jumpserver/apps/common/serializers/mixin.py", line 90, in many_init
    return super(BulkSerializerMixin, cls).many_init(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 149, in many_init
    child_serializer = cls(*args, **kwargs)
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 155, in __init__
    self._extract_accounts()
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 160, in _extract_accounts
    accounts = self.initial_data.pop('accounts', None)

Exception Type: TypeError at /api/v1/assets/assets/
Exception Value: pop expected at most 1 argument, got 2
```

请指教，如何排查此问题

**Comment by jibill** [comment]
这个可以确定为BUG吧，新部署的v3.5.0也是有同样的错误。

**Comment by xulinde** [comment]
v3.5.1已修复
