### ISSUE TITLE
[Bug] docker-compose 部署方式v3.4.3 升级到v3.5.3 失败

### ISSUE THREAD

**Issue by jiangxianliang007** [jumpserver/jumpserver#11233]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

**浏览器版本**

**Bug 描述**
https://github.com/jumpserver/Dockerfile  用这个方式部署的版本v3.4.3 升级到 v3.5.3 web 容器启动失败
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-init-config.sh
Starting periodic command scheduler: cron.
/docker-entrypoint.sh: Configuration complete; ready for start up
nginx: [emerg] host not found in upstream "chen" in /etc/nginx/conf.d/default.conf:87
```

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BaiJiangJie** [comment]
allinone 吗？

**Comment by BaiJiangJie** [comment]
看看 nginx 的配置，是不是没有更新。

**Comment by jiangxianliang007** [comment]
[Dockerfile](https://github.com/jumpserver/Dockerfile)  repo 里面的allinone 和 web 目录 下的 nginx.conf 是一样的，就user 一个是 nginx，一个是 root  这2个配置文件都只支持 v3.4.3, 最新的nginx.conf 在哪获取？

**Comment by BaiJiangJie** [comment]
暂时还没有提供最新的 v3.5.3 版本。

**Comment by jiangxianliang007** [comment]
docker-compose -f docker-compose-network.yml -f docker-compose-redis.yml -f docker-compose-mariadb.yml -f docker-compose.yml up -d
请问这种方式部署的，支持 3.6 了吗？

**Comment by BaiJiangJie** [comment]
直接用离线包部署吧

**Comment by jiangxianliang007** [comment]
已经在用 docker-compose 部署的环境，应该怎么切换到 离线包部署的环境，有操作文档和思路吗？

**Comment by BaiJiangJie** [comment]
数据库备份好，下载离线包，安装就行。

**Comment by BaiJiangJie** [comment]
参考文档。https://docs.jumpserver.org/zh/v3/installation/setup_linux_standalone/offline_install/

**Comment by jiangxianliang007** [comment]
把docker-compose 方式运行的保留mysql、redis、magnus 容器，离线包，redis 和 mysql 配置到 magnus 的 mysql 和 redis 信息，在部署离线包，是不是就算切换过来了？

**Comment by BaiJiangJie** [comment]
只保留 mysql 和 redis 就行，其他都用离线包的容器。

其实最好的方案是，只把数据库备份下来。离线包起来之后，单独导入一下数据库。

**Comment by jiangxianliang007** [comment]
用这个包 wget https://resource.fit2cloud.com/jumpserver/installer/releases/download/v3.6.2/jumpserver-installer-v3.6.2.tar.gz 安装后,导入数据库，可以正常登录页面，但有一些500错误，然后 ./jmsctl.sh stop ./jmsctl.sh  start ，jms_core 就启动不了了.

![image](https://github.com/jumpserver/jumpserver/assets/24754263/5054d5fc-5305-423c-8416-62d21ccc3a64)



```System check identified no issues (0 silenced).
2023-08-25 18:01:01 Database connect success
2023-08-25 18:01:01 Collect static files
2023-08-25 18:01:01 Collect static files done
2023-08-25 18:01:01 Check database structure change ...
2023-08-25 18:01:01 Migrate model change to database ...
Operations to perform:
  Apply all migrations: accounts, acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying accounts.0013_account_backup_recipients...2023-08-25 18:01:02 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1050, "Table 'accounts_accountbackupautomation_recipients_part_one' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
    schema_editor.add_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/schema.py", line 104, in add_field
    super().add_field(model, field)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 636, in add_field
    return self.create_model(field.remote_field.through)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 447, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'accounts_accountbackupautomation_recipients_part_one' already exists")```

**Comment by jiangxianliang007** [comment]
数据库，删了 jumpserver 库重新导入就正常了， 但有其他错误
```
2023-08-25 23:52:16 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2023-08-25 23:52:21 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2023-08-25 23:52:26 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2023-08-25 23:52:32 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2023-08-25 23:52:37 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2023-08-25 23:52:42 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2023-08-25 23:52:47 [ERRO] POST http://core:8080/api/v1/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}```
配置文件里面填了域名的，还有服务器上不配置证书，直接用cloudflare proxy 模式自带的证书这种可行？
![image](https://github.com/jumpserver/jumpserver/assets/24754263/6142660a-cee3-4856-8e16-74e923e09f3e)

**Comment by jiangxianliang007** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/24754263/826aa736-8b79-4c1d-9c58-e4d2d8dff365)

这5个容器启动失败，日志都有  [ERRO] Access key 已失效, 重新注册 ，然后我就把 keys/.access_key 删了，重启，发下不会重新生成了。

**Comment by wojiushixiaobai** [comment]
```
service account registration disabled
```
提示已经明确告诉你，服务账号注册被关闭了，自己从 web 页面系统设置里面打开
