### ISSUE TITLE
SecureCRT客户端交互时报错

### ISSUE THREAD

**Issue by hbgcll** [jumpserver/jumpserver#1124]
[简述你的问题]
客户端SecureCRT登录coco后，命令交互报错，xshell, iterm正常

##### 使用版本
1.0.0

##### 问题复现步骤
1. SecureCRT登录后输入 'p' 'g' '/' 直接回车等指令卡住。

##### 具体表现[截图可能会更好些,最好能截全]
SecureCRT登录后输入 'p' 'g' '/' '回车'等指令卡住。  
输入主机id，ip,可以登录主机，h指令正常

##### 其他
coco错误日志如下：
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/jumper/coco/coco/sshd.py", line 96, in handle_chan
    self.dispatch(client)
  File "/apps/jumper/coco/coco/sshd.py", line 102, in dispatch
    InteractiveServer(self.app, client).interact()
  File "/apps/jumper/coco/coco/interactive.py", line 307, in interact
    rv = self.dispatch(opt)
  File "/apps/jumper/coco/coco/interactive.py", line 137, in dispatch
    self.display_assets()
  File "/apps/jumper/coco/coco/interactive.py", line 178, in display_assets
    self.search_and_display('')
  File "/apps/jumper/coco/coco/interactive.py", line 231, in search_and_display
    self.display_search_result()
  File "/apps/jumper/coco/coco/interactive.py", line 219, in display_search_result
    comment_length = self.request.meta["width"] - len(header.format(fake_asset, id_max_length))
KeyError: 'width'

[注:] 完成后请关闭 issue

**Comment by hbgcll** [comment]
补充： 登录成功后，调整一下窗口大小，就可以正常交互

**Comment by ibuler** [comment]
修改 coco中的代码，先删除这行，这个bug已经收到了，还没有merge

https://github.com/jumpserver/coco/blob/master/coco/interface.py#L117

**Comment by ibuler** [comment]
等待merge后，直接更新coco即可

**Comment by clangcn** [comment]
https://github.com/jumpserver/jumpserver/issues/1060#issuecomment-371828771
按照我这个方法设置一下，应该可以，我自己是这样解决的 @hbgcll
