### ISSUE TITLE
[Bug]  VSCode 连接问题

### ISSUE THREAD

**Issue by Cerdore** [jumpserver/jumpserver#11256]
我的VSCode在正常情况下连接不上，而同事的都可以。

 问题堆栈如下。可以看到，vscode 的 ssh 命令会默认带 `-T`， `"-v -T -D 61755 -o ConnectTimeout=15 -o RemoteCommand=none dev"`。经过本地终端测试，就是 -T 导致的问题，而 `ssh -T` 在其他的同事电脑连接jumpserver资产时没有问题。

但我在通过Jumpserver网站启用嵌入的终端后，就可以正常使用VSCode Remote.

-T 意味着禁用伪终端，

`[17:04:37.831] Log Level: 2
[17:04:37.840] SSH Resolver called for "ssh-remote+dev", attempt 1
[17:04:37.840] "remote.SSH.useLocalServer": true
[17:04:37.840] "remote.SSH.path": undefined
[17:04:37.840] "remote.SSH.configFile": undefined
[17:04:37.840] "remote.SSH.useFlock": true
[17:04:37.840] "remote.SSH.lockfilesInTmp": false
[17:04:37.841] "remote.SSH.localServerDownload": auto
[17:04:37.841] "remote.SSH.remoteServerListenOnSocket": false
[17:04:37.841] "remote.SSH.showLoginTerminal": false
[17:04:37.841] "remote.SSH.defaultExtensions": []
[17:04:37.841] "remote.SSH.loglevel": 2
[17:04:37.841] "remote.SSH.enableDynamicForwarding": true
[17:04:37.841] "remote.SSH.enableRemoteCommand": false
[17:04:37.841] "remote.SSH.serverPickPortsFromRange": {}
[17:04:37.842] "remote.SSH.serverInstallPath": {}
[17:04:37.846] VS Code version: 1.77.3
[17:04:37.846] Remote-SSH version: remote-ssh@0.102.0
[17:04:37.846] darwin arm64
[17:04:37.847] SSH Resolver called for host: dev
[17:04:37.847] Setting up SSH remote "dev"
[17:04:37.848] Acquiring local install lock: /var/folders/4z/s3xgd_9j60dcj0_tm38tqpmw0000gp/T/vscode-remote-ssh-d55997bc-install.lock
[17:04:37.848] Looking for existing server data file at /Users/xiansen.chen/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-xxx/data.json
[17:04:37.848] Using commit id "704ed70d4fd1c6bd6342c436f1ede30d1cff4710" and quality "stable" for server
[17:04:37.850] Install and start server if needed
[17:04:37.852] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
[17:04:37.852] Checking ssh with "ssh -V"
[17:04:37.856] > OpenSSH_9.0p1, LibreSSL 3.3.6
。。。。。。
[17:04:39.579] > ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remainlocal-server-1> ssh child died, shutting down
[17:04:39.584] Local server exit: 0
[17:04:39.584] Received install output: local-server-1> Running ssh connection command: "-v -T -D 61755 -o ConnectTimeout=15 -o RemoteCommand=none dev"
local-server-1> Spawned ssh, pid=58150
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Server host key: ssh-rsa SHA256:xxxxxxxx
Authenticated to jumpserver.dev.openpie.com ([IP.IP.IP.IP]:2222) using "password".
Transferred: sent 1848, received 1520 bytes, in 0.1 seconds
Bytes per second: sent 14042.7, received 11550.2
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remainlocal-server-1> ssh child died, shutting down

[17:04:39.585] Failed to parse remote port from server output
[17:04:39.588] Resolver error: Error: 
	at m.Create (/Users/x/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/Users/x/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/Users/xx/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:623656)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/x/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:643708
	at async t.withShowDetailsEvent (/Users/xn/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:647428)
	at async /Users/x/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:622128
	at async C (/Users/x/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:618634)
	at async t.resolveWithLocalServer (/Users/x/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:621743)
	at async t.resolve (/Users/x/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:645036)
	at async /Users/x/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:720916`

**Comment by BaiJiangJie** [comment]
是不是你们 VSCode 的版本不同？

**Comment by Cerdore** [comment]
> 是不是你们 VSCode 的版本不同？

尝试过将版本改为同事使用的 1.77，还是这样...

**Comment by LeeEirc** [comment]
部署的 JumpServer 的版本？你本地 vscode 版本？使用最新的 vscode 行不行？ Koko 有没有报错日志？资产是否是自动托管密码登陆的？

**Comment by Cerdore** [comment]
JumpServer  v2.26.1; vscode 1.77.3; 之前是今年7月的vscode 1.80，降成了 vscode;  ;是自动托管密码登陆的。

Koko的报错
`2023-08-14 17:43:20 [ERRO] Get SSH Client failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain`

**Comment by LeeEirc** [comment]
我觉得你可能需要升级到 v2.28，v2.28才支持 openssh9。是不是你资产的 ssh 版本比较高？还是你本地的 openssh 版本比较高？

**Comment by Cerdore** [comment]
既然我同事的可以，那可能不是jumpserver版本的问题？我同事的资产和本机ssh版本和我也是一致的....

**我想知道网站启动内嵌终端时，ssh的命令格式是？**既然先启动内嵌终端再连ssh是可以的，那我跑个后台命令感觉也能达到目的...

资产： `ssh -V
OpenSSH_8.2p1 Ubuntu-4ubuntu0.9, OpenSSL 1.1.1f  31 Mar 2020`

本机：ssh -V
OpenSSH_9.0p1, LibreSSL 3.3.6

**Comment by Cerdore** [comment]
命令格式我知道了，/.../client ssh [一串序列号]@jumpserver.dev.openpie.com -p 2222 -P [一段字符]. 
但是 -P 后面的字符貌似每次不一样...

**Comment by Cerdore** [comment]
> 命令格式我知道了，/.../client ssh [一串序列号]@jumpserver.dev.openpie.com -p 2222 -P [一段字符]. 但是 -P 后面的字符貌似每次不一样...

我关闭之前和资产的连接，再使用上次相同的命令进入，则又会提示：

`2023/08/14 18:15:36 dial err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain`


这个报错与我直接连接vscode相同。

<img width="860" alt="image" src="https://github.com/jumpserver/jumpserver/assets/24353799/9f099b29-e322-491a-8b37-8a25370b5cd7">

**Comment by LeeEirc** [comment]
参考下这个文档 https://kb.fit2cloud.com/?p=48

**Comment by Cerdore** [comment]
> 参考下这个文档 https://kb.fit2cloud.com/?p=48

我最开始就参考了这个文档... 然后出现了这个奇怪的问题, 所以才有上面的尝试。

**Comment by LeeEirc** [comment]
可以进交流群，远程帮你看看。你贴的报错，是连接资产的时候，密码错误。按理说你如果是托管的密码，不应该有这样的问题

**Comment by Cerdore** [comment]
问题解决，IT的同事后来发现不是托管的密码..... 感谢🙏
