### ISSUE TITLE
[问题] 服务启动后一会儿自动又停了（allinone）

### ISSUE THREAD

**Issue by aishang1993** [jumpserver/jumpserver#11456]
使用docker 部署，镜像：jumpserver/jms_all:v2.24.2
外置mysql和redis,容器启动后，可以正常访问，但过几分钟就不能访问了，下面是部分日志

jumpserver.log
```
2023-08-29 17:02:08 [cache DEBUG] End init cache: cost=0.3120763301849365 key=cache.orgs.caches.OrgResourceStatisticsCache.org_00000000-0000-0000-0000-000000000002
2023-08-29 17:02:08 [lock DEBUG] Released lock: lock_id=CHrQWJGihv68kdiP2wlopSXP lock=lock:{compute:cache.orgs.caches.OrgResourceStatisticsCache.org_00000000-0000-0000-0000-000000000002} thread=140140756334336
2023-08-29 17:02:24 [permissions DEBUG] View require perms: ['terminal.view_terminalconfig'], result: True
2023-08-29 17:02:24 [permissions DEBUG] View require perms: {'terminal.add_status'}, result: True
2023-08-29 17:02:24 [permissions DEBUG] View require perms: ['terminal.view_terminalconfig'], result: True
2023-08-29 17:02:25 [permissions DEBUG] View require perms: {'terminal.add_status'}, result: True
2023-08-29 17:02:25 [permissions DEBUG] View require perms: {'terminal.add_status'}, result: True
2023-08-29 17:02:28 [signal_handler DEBUG] Worker shutdown signal recv
2023-08-29 17:02:28 [signal_handler DEBUG] Clean period tasks: [ops.tasks.clean_tasks_adhoc_period, ops.tasks.clean_celery_tasks_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session, terminal.tasks.clean_expired_session_period]

```

celery_ansible.log
```
Connected to redis://redis:6379/3
mingle: searching for neighbors
mingle: all alone
2023-08-29 16:58:24 [signal_handler DEBUG] Work ready signal recv
Work ready signal recv
2023-08-29 16:58:24 [signal_handler DEBUG] Start need start task: [ops.tasks.clean_celery_periodic_tasks, ops.tasks.create_or_update_registered_periodic_tasks, users.tasks.check_password_expired_periodic, users.tasks.check_user_expired_periodic, users.tasks.import_ldap_user_periodic, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session, terminal.tasks.clean_expired_session_period]
Start need start task: [ops.tasks.clean_celery_periodic_tasks, ops.tasks.create_or_update_registered_periodic_tasks, users.tasks.check_password_expired_periodic, users.tasks.check_user_expired_periodic, users.tasks.import_ldap_user_periodic, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session, terminal.tasks.clean_expired_session_period]
ansible@28962adc771f ready.
Events of group {task} enabled by remote.
missed heartbeat from celery@28962adc771f

worker: Warm shutdown (MainProcess)
2023-08-29 17:02:28 [signal_handler DEBUG] Worker shutdown signal recv
Worker shutdown signal recv
2023-08-29 17:02:28 [signal_handler DEBUG] Clean period tasks: [ops.tasks.clean_tasks_adhoc_period, ops.tasks.clean_celery_tasks_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session, terminal.tasks.clean_expired_session_period]
Clean period tasks: [ops.tasks.clean_tasks_adhoc_period, ops.tasks.clean_celery_tasks_period, terminal.tasks.delete_terminal_status_period, terminal.tasks.clean_orphan_session, terminal.tasks.clean_expired_session_period]
```

celery_default.log
```
Connected to redis://redis:6379/3
mingle: searching for neighbors
mingle: all alone
celery@28962adc771f ready.
Task terminal.tasks.clean_orphan_session[f67fdca0-b364-421d-8d1e-16ae210b442c] received
Task ops.tasks.clean_celery_periodic_tasks[c3468c1c-c08f-448b-866b-d076dd664f27] received
Task ops.tasks.create_or_update_registered_periodic_tasks[4964071b-1ce5-4d1d-9092-123fd49fbf87] received
Task users.tasks.check_password_expired_periodic[0b4c013e-9504-42c8-aee6-cdb155909c83] received
Task users.tasks.check_user_expired_periodic[652dabe4-28ef-485d-a575-94236ea5ef88] received
Task users.tasks.import_ldap_user_periodic[460dc4b1-661d-4f4f-9fd3-4053b39fa7ef] received
Task terminal.tasks.delete_terminal_status_period[80f36ea7-ae27-40de-b811-950fa8a9dbb6] received
Task terminal.tasks.clean_orphan_session[aba0b905-c3a7-497b-afb9-7b80e727fadb] received
Task terminal.tasks.clean_expired_session_period[ede357dd-fd7d-44fa-bd4a-d31bc3faf256] received
2023-08-29 16:58:24 [tasks INFO] Start clean celery periodic tasks: ['handle_be_interrupted_change_auth_task_periodic']
Start clean celery periodic tasks: ['handle_be_interrupted_change_auth_task_periodic']
2023-08-29 16:58:24 [tasks INFO] Start clean task: handle_be_interrupted_change_auth_task_periodic
Start clean task: handle_be_interrupted_change_auth_task_periodic
2023-08-29 16:58:24 [tasks INFO] Task does not exist: handle_be_interrupted_change_auth_task_periodic
Task does not exist: handle_be_interrupted_change_auth_task_periodic
Start clean expired session record, commands and replay
Clean session item done
Task users.tasks.import_ldap_user_periodic[460dc4b1-661d-4f4f-9fd3-4053b39fa7ef] succeeded in 0.13586957999999072s: None
Task ops.tasks.clean_celery_periodic_tasks[c3468c1c-c08f-448b-866b-d076dd664f27] succeeded in 0.16043106300000431s: None
Task terminal.tasks.delete_terminal_status_period[80f36ea7-ae27-40de-b811-950fa8a9dbb6] succeeded in 0.1588239349999867s: None
Task terminal.tasks.clean_orphan_session[f67fdca0-b364-421d-8d1e-16ae210b442c] succeeded in 0.1784510379999915s: None
Task terminal.tasks.clean_orphan_session[aba0b905-c3a7-497b-afb9-7b80e727fadb] succeeded in 0.15681562800000393s: None
Task users.tasks.check_password_expired_periodic[0b4c013e-9504-42c8-aee6-cdb155909c83] succeeded in 0.18782087799999658s: None
Task users.tasks.check_user_expired_periodic[652dabe4-28ef-485d-a575-94236ea5ef88] succeeded in 0.1857250080000199s: None
Task ops.tasks.create_or_update_registered_periodic_tasks[4964071b-1ce5-4d1d-9092-123fd49fbf87] succeeded in 0.5577269580000177s: None
Events of group {task} enabled by remote.
```

gunicorn.log
```
2023-08-29 16:58:24 [permissions DEBUG] View require perms: ['terminal.view_terminalconfig'], result: True
127.0.0.1 [29/Aug/2023:16:58:24 +0800] 0.083162s "GET /api/v1/terminal/terminals/config/ HTTP/1.1" 200 2314
2023-08-29 16:58:24 [permissions DEBUG] View require perms: {'terminal.change_session'}, result: True
2023-08-29 16:58:24 [exc_handlers ERROR] 
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
terminal.models.session.Session.DoesNotExist: Session matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/mixins.py", line 65, in update
    instance = self.get_object()
  File "/opt/py3/lib/python3.8/site-packages/rest_framework_bulk/drf3/mixins.py", line 51, in get_object
    return super(BulkUpdateModelMixin, self).get_object()
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django/shortcuts.py", line 78, in get_object_or_404
    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)
django.http.response.Http404: No Session matches the given query.
2023-08-29 16:58:24 [log WARNING] Not Found: /api/v1/terminal/sessions/b6dc7a0b-3184-42de-8658-e8214bc58387/
127.0.0.1 [29/Aug/2023:16:58:24 +0800] 0.085498s "PATCH /api/v1/terminal/sessions/b6dc7a0b-3184-42de-8658-e8214bc58387/ HTTP/1.1" 404 65
```

**Comment by wojiushixiaobai** [comment]
具体是哪个服务停？可以尝试升级到 v3.5 版本看看问题是否解决

**Comment by aishang1993** [comment]
> 具体是哪个服务停？可以尝试升级到 v3.5 版本看看问题是否解决

![image](https://github.com/jumpserver/jumpserver/assets/20903014/1f385106-9e1a-412e-af8e-6c9aa014244b)
![image](https://github.com/jumpserver/jumpserver/assets/20903014/d20861a2-5d98-4d3d-beb7-803e58afde44)

**Comment by aishang1993** [comment]
> > 具体是哪个服务停？可以尝试升级到 v3.5 版本看看问题是否解决
> 
> ![image](https://user-images.githubusercontent.com/20903014/264041294-1f385106-9e1a-412e-af8e-6c9aa014244b.png) ![image](https://user-images.githubusercontent.com/20903014/264042309-d20861a2-5d98-4d3d-beb7-803e58afde44.png)

这是容器刚启动是的进程列表
![image](https://github.com/jumpserver/jumpserver/assets/20903014/bbd0e50d-cbb6-4d5b-87a5-acff50b876c8)

**Comment by BaiJiangJie** [comment]
https://hub.docker.com/r/jumpserver/jms_all/tags

`jumpserver/jms_all:v2.24.2` 版本比较旧了，升级到最新版本看看是不是正常。

**Comment by BaiJiangJie** [comment]
最新版本已更新。
