### ISSUE TITLE
jumpserver升级3.6.4版本后，无法正常访问资产。

### ISSUE THREAD

**Issue by Sanbobo1** [jumpserver/jumpserver#11492]
环境问题导致的表字段丢失，需要修复表结构，非代码问题。
_Originally posted by @wojiushixiaobai in https://github.com/jumpserver/jumpserver/issues/8239#issuecomment-1130901210_

查看日志发现如下报错

**Comment by Sanbobo1** [comment]
{ComponentName:magnus Name:[Magnus]-iZwz9g60zr019yhug5u84cZ-jms_magnus-pVrkpsv CoreHost:http://core:8080 BootstrapToken:YmZjOTIzMDMtMWUwYS00OTcx BindHost:0.0.0.0 BindPort:9090 LogLevel:ERROR RootPath:/opt/magnus ExecuteProgram:/opt/magnus/magnus DataFolderPath:/opt/magnus/data LogFolderPath:/opt/magnus/data/logs KeyFolderPath:/opt/magnus/data/keys AccessKeyFilePath:/opt/magnus/data/keys/.access_key}
2023-09-04 16:13:54 [ERRO] Access key 已失效, 重新注册
2023-09-04 16:17:00 [ERRO] Uploader service watch config err: GET http://core:8080/api/v1/terminal/terminals/config/ failed, get code: 401, {"detail":"Invalid signature.","code":"authentication_failed"}
2023-09-04 16:18:00 [ERRO] Uploader service watch config err: GET http://core:8080/api/v1/terminal/terminals/config/ failed, get code: 401, {"detail":"Invalid signature.","code":"authentication_failed"}
2023-09-04 16:19:00 [ERRO] Uploader service watch config err: GET http://core:8080/api/v1/terminal/terminals/config/ failed, get code: 401, {"detail":"Invalid signature.","code":"authentication_failed"}
2023-09-04 16:20:00 [ERRO] Uploader service watch config err: GET http://core:8080/api/v1/terminal/terminals/config/ failed, get code: 401, {"detail":"Invalid signature.","code":"authentication_failed"}
2023-09-04 16:21:00 [ERRO] Uploader service watch config err: GET http://core:8080/api/v1/terminal/terminals/config/ failed, get code: 401, {"detail":"Invalid signature.","code":"authentication_failed"}
2023-09-04 16:22:00 [ERRO] Uploader service watch config err: GET http://core:8080/api/v1/terminal/terminals/config/ failed, get code: 401, {"detail":"Invalid signature.","code":"authentication_failed"}
2023-09-04 16:23:00 [ERRO] Uploader service watch config err: GET http://core:8080/api/v1/terminal/terminals/config/ failed, get code: 401, {"detail":"Invalid signature.","code":"authentication_failed"}
2023-09-04 16:24:00 [ERRO] Uploader service watch config err: GET http://core:8080/api/v1/terminal/terminals/config/ failed, get code: 401, {"detail":"Invalid signature.","code":"authentication_failed"}

**Comment by Sanbobo1** [comment]
按照之前issue的方法检查
root@jms_magnus:/opt/magnus# curl http://core:8080/api/v1/terminal/terminal-registrations/
{"detail":"身份认证信息未提供。","code":"not_authenticated"}root@jms_magnus:/opt/magnus#
root@jms_magnus:/opt/magnus# curl http://core:8080/api/health/
{"status":true,"db_status":true,"db_time":0.0013082027435302734,"redis_status":true,"redis_time":0.0006616115570068359,"time":1693816741}root@jms_magnus:/opt/magnus#

**Comment by Sanbobo1** [comment]
然后看到您之前回复说是 环境问题导致的表字段丢失，需要修复表结构，非代码问题。想请教下怎么解决

**Comment by Sanbobo1** [comment]
升级是从3.4.1升级到3.6.2，使用的是installer进行升级。同时请问下升级如何规避这个问题，谢谢

**Comment by Sanbobo1** [comment]
但是我现在遇到一样的问题，没办法访问资产，并且有上述的报错

**Comment by Sanbobo1** [comment]
![image](https://github.com/jumpserver/jumpserver/assets/138869963/d3845ed3-e604-4476-9865-53e4896c7cd9)
web端也无法看到主机的详细信息，也无法连接到主机

**Comment by BaiJiangJie** [comment]
你单独修改过表结构吗？

**Comment by Sanbobo1** [comment]
没有修改过，在升级的时候备份过。
if grep -q 'COLLATE=utf8_bin' /opt/jumpserver.sql; then
    cp /opt/jumpserver.sql /opt/jumpserver_bak.sql
    sed -i 's@COLLATE=utf8_bin@@g' /opt/jumpserver.sql
    sed -i 's@COLLATE utf8_bin@@g' /opt/jumpserver.sql
else
    echo "备份数据库字符集正确";
fi
执行过如上命令，但是输出是 "备份数据库字符集正确"

**Comment by BaiJiangJie** [comment]
能稳定复现吗？

**Comment by Sanbobo1** [comment]
可以 现在就是这种状态。而且使用./jmsctl.sh restart   会报错：dependency failed to start: container jms_core is unhealthy。
看日志报错如下：
Applying accounts.0013_account_backup_recipients...2023-09-04 18:34:59 Perform migrate failed, exit
jms_core   | Traceback (most recent call last):
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
jms_core   |     return self.cursor.execute(sql)
jms_core   |            ^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
jms_core   |     return self.cursor.execute(query, args)
jms_core   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
jms_core   |     res = self._query(mogrified_query)
jms_core   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
jms_core   |     db.query(q)
jms_core   |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
jms_core   |     _mysql.connection.query(self, query)
jms_core   | MySQLdb.OperationalError: (1050, "Table 'accounts_accountbackupautomation_recipients_part_one' already exists")
jms_core   |
jms_core   | The above exception was the direct cause of the following exception:
jms_core   |
jms_core   | Traceback (most recent call last):
jms_core   |   File "/opt/jumpserver/jms", line 88, in perform_db_migrate
jms_core   |     management.call_command('migrate')
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
jms_core   |     return command.execute(*args, **defaults)
jms_core   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
jms_core   |     output = self.handle(*args, **options)
jms_core   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
jms_core   |     res = handle_func(*args, **kwargs)
jms_core   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
jms_core   |     post_migrate_state = executor.migrate(
jms_core   |                          ^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
jms_core   |     state = self._migrate_all_forwards(
jms_core   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
jms_core   |     state = self.apply_migration(
jms_core   |             ^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
jms_core   |     state = migration.apply(state, schema_editor)
jms_core   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
jms_core   |     operation.database_forwards(
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
jms_core   |     schema_editor.add_field(
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/schema.py", line 104, in add_field
jms_core   |     super().add_field(model, field)
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 636, in add_field
jms_core   |     return self.create_model(field.remote_field.through)
jms_core   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 447, in create_model
jms_core   |     self.execute(sql, params or None)
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
jms_core   |     cursor.execute(sql, params)
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
jms_core   |     return self._execute_with_wrappers(
jms_core   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
jms_core   |     return executor(sql, params, many, context)
jms_core   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
jms_core   |     with self.db.wrap_database_errors:
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
jms_core   |     raise dj_exc_value.with_traceback(traceback) from exc_value
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
jms_core   |     return self.cursor.execute(sql)
jms_core   |            ^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
jms_core   |     return self.cursor.execute(query, args)
jms_core   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
jms_core   |     res = self._query(mogrified_query)
jms_core   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jms_core   |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
jms_core   |     db.query(q)
jms_core   |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
jms_core   |     _mysql.connection.query(self, query)
jms_core   | django.db.utils.OperationalError: (1050, "Table 'accounts_accountbackupautomation_recipients_part_one' already exists")
jms_core exited with code 11

必须执行
drop database jumpserver;
create database jumpserver default charset 'utf8';后
才能够正常启动jms_core 然后通过./jmsctl.sh restore_db /opt/jumpserver.sql 这个命令恢复数据库后，就会有无法访问资产的问题

**Comment by Sanbobo1** [comment]
回滚到3.4.1版本 就不会有该问题

**Comment by BaiJiangJie** [comment]
不能用 restore_db，因为之前的数据库表结构已经被损坏了。

至于为什么会损坏，还不清楚。正常情况不会出现的。

**Comment by Sanbobo1** [comment]
如果数据库表结构被损坏了，为什么我回滚到3.4.1版本后可以正常使用。
如果是数据库损坏，我能否去另一台正常的3.4版本的堡垒机执行backup_db命令，再使用其生成的备份文件来对异常的3.6版本的堡垒机进行 restore_db

**Comment by BaiJiangJie** [comment]
可能是 v3.4.1 版本没有用到那个表，有问题那个表是账号备份新增的字段。

**Comment by BaiJiangJie** [comment]
用你旧环境的表，比如另一台 v3.4 版本的数据库，重新升级到 v3.6 试一下。

**Comment by BaiJiangJie** [comment]
下载最新的 v3.6 版本，先进行 upgrade 操作。

**Comment by Sanbobo1** [comment]
使用最新的3.6.3版本，进行upgrade操作后，报如下错误
Applying accounts.0013_account_backup_recipients...2023-09-05 14:19:40 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1050, "Table 'accounts_accountbackupautomation_recipients_part_one' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
    schema_editor.add_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/schema.py", line 104, in add_field
    super().add_field(model, field)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 636, in add_field
    return self.create_model(field.remote_field.through)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 447, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'accounts_accountbackupautomation_recipients_part_one' already exists")
[ERROR] Failed to change the table structure!

**Comment by BaiJiangJie** [comment]
那说明你的 v3.4 版本的数据库表结构已经有问题了。

**Comment by BaiJiangJie** [comment]
`accounts_accountbackupautomation_recipients_part_one`
`accounts_accountbackupautomation_recipients_part_two`

找到不存在这两张表的数据库，再重新升级。
