### ISSUE TITLE
离线部署jumpserver最新版本报错

### ISSUE THREAD

**Issue by shibosen** [jumpserver/jumpserver#11660]
**版本号：V3.7.0**

*报错信息如下**
6. Init JumpServer Database
[+] Running 4/4
 ✔ Network jms_net      Created                                                                                                          0.1s 
 ✔ Container jms_redis  Started                                                                                                          1.0s 
 ✔ Container jms_core   Started                                                                                                          1.0s 
 ✔ Container jms_mysql  Started                                                                                                          1.0s 
2023-09-22 12:13:29 Collect static files
ALLOWED_HOSTS: 
  - localhost
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
ALLOWED_HOSTS: 
  - localhost
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
2023-09-22 12:13:29 Collect static files done
2023-09-22 12:13:29 Check database structure change ...
2023-09-22 12:13:29 Migrate model change to database ...
2023-09-22 12:13:30 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 114, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")
[ERROR] Failed to change the table structure!

**Comment by jym503558564** [comment]
社区版v3.7.0离线包部署吗？

**Comment by shibosen** [comment]
是的，在centos7.9和rocky8.7上面部署，都会出现这个问题，我换了V3.6.5版本以后，就能正常安装部署了

**Comment by jym503558564** [comment]
默认内置的数据库吗？

**Comment by shibosen** [comment]
是的，redis和mysql都用的默认内置的

**Comment by jym503558564** [comment]
centos7.8 离线部署社区版v3.7.0，无法复现该问题

**Comment by shibosen** [comment]
centos版本如下：
[root@jms ~]# uname -a
Linux jms 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@jms ~]# hostnamectl 
   Static hostname: jms
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 9fabc5b7b4884e7aaa72888404f923e8
           Boot ID: 0b8ea3ede95749af9e2a97104c78ecc9
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1062.el7.x86_64
      Architecture: x86-64
[root@jms ~]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

**Comment by jym503558564** [comment]
是全新安装吧？

**Comment by shibosen** [comment]
是的，都是全新安装，我现在测试一下centos7.8

**Comment by jym503558564** [comment]
mysql起来了吗？

**Comment by shibosen** [comment]
起来了，docker execl进行mysql，用show databases; 都可以看到jumpserver的数据库

**Comment by jym503558564** [comment]
测试结果如下：
![image](https://github.com/jumpserver/jumpserver/assets/40739051/db0dbc0f-81ae-4143-b07f-93e781211c26)

![image](https://github.com/jumpserver/jumpserver/assets/40739051/0d7e66b0-2a1e-4f01-9169-a4aa4b4b5c32)

![image](https://github.com/jumpserver/jumpserver/assets/40739051/8e7b6d42-3cae-4e7d-b917-ad58697e71aa)

**Comment by shibosen** [comment]
真是见鬼了，我重新安装了一个centos7.8，还是一样的问题

6. Init JumpServer Database
[+] Running 4/4
 ✔ Network jms_net      Created                                                                                                          0.9s 
 ✔ Container jms_redis  Started                                                                                                          0.2s 
 ✔ Container jms_core   Started                                                                                                          0.2s 
 ✔ Container jms_mysql  Started                                                                                                          0.2s 
2023-09-22 14:16:08 Collect static files
ALLOWED_HOSTS: 
  - localhost
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
ALLOWED_HOSTS: 
  - localhost
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
2023-09-22 14:16:08 Collect static files done
2023-09-22 14:16:08 Check database structure change ...
2023-09-22 14:16:08 Migrate model change to database ...
2023-09-22 14:16:09 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 114, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")
**[ERROR] Failed to change the table structure!**
[root@jms jumpserver-offline-installer-v3.7.0-amd64]# uname -a
Linux jms 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@jms jumpserver-offline-installer-v3.7.0-amd64]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

**Comment by wojiushixiaobai** [comment]
`Docker` 网络问题，不要在运行过程中修改 `iptables` 或者 `firewalld` 相关配置，
一般情况下可以关闭 `JumpServer` 后通过重启 `Docker` 解决。
```sh
systemctl stop docker docker.socket
systemctl restart docker
```
如果问题依旧请检测 `Docker` 使用的网段和实际网络有冲突。

**Comment by shibosen** [comment]
<img width="769" alt="image" src="https://github.com/jumpserver/jumpserver/assets/93109624/f24ec4bd-a060-4c19-acc0-607e09d45c10">

不是这个问题，我更换了docker的subnet地址，报错现象依旧存在

**Comment by shibosen** [comment]
<img width="876" alt="image" src="https://github.com/jumpserver/jumpserver/assets/93109624/be440671-1613-4773-94c0-65163d276c68">

**Comment by wojiushixiaobai** [comment]
自行检测容器网络
```sh
docker run --rm --net jms_net -it jumpserver/core:v3.7.0 bash
ping mysql
```
确定 `mysql` 容器已经正常就绪

**Comment by shibosen** [comment]
core里面没有ping命令，我运行了一个busybox测试了一下，看着是正常的
<img width="734" alt="image" src="https://github.com/jumpserver/jumpserver/assets/93109624/e2063c7b-f602-4673-b96a-deec3b26bbde">

**Comment by wojiushixiaobai** [comment]
将 `mysql` 容器状态发上来看看
```sh
docker ps
```

查看数据库配置
```sh
cat /opt/jumpserver/config/config.txt | grep ^DB_
```

测试连接
```sh
docker run --rm -it jumpserver/mariadb:10.6 bash
mysql -hmysql -uroot -p
```

**Comment by shibosen** [comment]
<img width="1003" alt="image" src="https://github.com/jumpserver/jumpserver/assets/93109624/6cd90bfe-eb0d-41cb-885d-a286bf0f891d">

**Comment by wojiushixiaobai** [comment]
```sh
docker run --rm --net jms_net -it jumpserver/mariadb:10.6 bash
mysql -hmysql -uroot -p
```
别忘记 `--net jms_net` 和 `-hmysql`

**Comment by shibosen** [comment]
是进入mysql测试还是进入那个jumpserver/core测试呀  大佬


| |
石博森
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月22日 16:43 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jumpserver/jumpserver] 离线部署jumpserver最新版本报错 (Issue #11660) |

docker run --rm --net jms_net -it jumpserver/mariadb:10.6 bash
mysql -hmysql -uroot -p

别忘记 --net jms_net 和 -hmysql

**Comment by wojiushixiaobai** [comment]
无区别，这个测试是验证是否可以连接到 mysql 容器

**Comment by shibosen** [comment]
数据可以正常连接，没有问题
<img width="887" alt="image" src="https://github.com/jumpserver/jumpserver/assets/93109624/b9031de2-03c5-4bee-ac0c-380a79f43e08">

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/installer/blob/dev/scripts/utils.sh#L568
尝试注释掉这行代码看看问题是否解决。或者改成下面的形式，逻辑不太好
```sh
# scripts/utils.sh#L554
function perform_db_migrations() {
  mysql_host=$(get_config DB_HOST)
  redis_host=$(get_config REDIS_HOST)
  create_db_ops_env
  if [[ "${mysql_host}" == "mysql" ]]; then
    while [[ "$(docker inspect -f "{{.State.Health.Status}}" jms_mysql)" != "healthy" ]]; do
      sleep 5s
    done
  fi
  if [[ "${redis_host}" == "redis" ]]; then
    while [[ "$(docker inspect -f "{{.State.Health.Status}}" jms_redis)" != "healthy" ]]; do
      sleep 5s
    done
  fi
```

**Comment by shibosen** [comment]
这样修改完以后运行正常了。什么原因导致的啊

**Comment by wojiushixiaobai** [comment]
create_db_ops_env 这个函数第二次启动的时候，没有校验健康状态，导致依赖组件未就绪就开始执行数据库初始化脚本。
