### ISSUE TITLE
[Bug] 更新通过模版所创建账号的密文时报错（QuerySet.bulk_update() got an unexpected keyword argument 'ignore_conflicts'）

### ISSUE THREAD

**Issue by smartwang** [jumpserver/jumpserver#11688]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.6.x

**浏览器版本**

Microsoft Edge
版本 117.0.2045.36 (正式版本) (64 位)

**Bug 描述**
通过“更新密文” 更新通过模版所创建账号的密文时报错

**Bug 重现步骤(有截图更好)**
"账号管理"  -->  "账号模版"  --> "账号列表" --> "更新密文" --> "提交"  报错
从core的日志中查看发现如下错误: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/usr/local/lib/python3.11/site-packages/rest_framework_bulk/drf3/mixins.py", line 82, in perform_update
    serializer.save()
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/accounts/serializers/account/template.py", line 48, in update
    self.sync_accounts_secret(instance, diff)
  File "/opt/jumpserver/apps/accounts/serializers/account/template.py", line 32, in sync_accounts_secret
    instance.bulk_sync_account_secret(accounts, self.context['request'].user.id)
  File "/opt/jumpserver/apps/accounts/models/template.py", line 85, in bulk_sync_account_secret
    self.bulk_update_accounts(accounts, {'secret': self.secret})
  File "/opt/jumpserver/apps/accounts/models/template.py", line 62, in bulk_update_accounts
    Account.objects.bulk_update(accounts, ['version', 'secret'])
  File "/opt/jumpserver/apps/accounts/models/mixins/vault.py", line 41, in bulk_update
    objs = super().bulk_update(objs, batch_size=batch_size, ignore_conflicts=ignore_conflicts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QuerySet.bulk_update() got an unexpected keyword argument 'ignore_conflicts'
```

**Comment by feng626** [comment]
3.7.1 修复

**Comment by smartwang** [comment]
从3.6.4升级到3.7.1后，现在报这个错了：
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/options.py", line 669, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'secret'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/usr/local/lib/python3.11/site-packages/rest_framework_bulk/drf3/mixins.py", line 82, in perform_update
    serializer.save()
  File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/accounts/serializers/account/template.py", line 85, in update
    self.sync_accounts_secret(instance, diff)
  File "/opt/jumpserver/apps/accounts/serializers/account/template.py", line 58, in sync_accounts_secret
    instance.bulk_sync_account_secret(accounts, self.context['request'].user.id)
  File "/opt/jumpserver/apps/accounts/models/template.py", line 91, in bulk_sync_account_secret
    self.bulk_update_accounts(accounts, {'secret': self.secret})
  File "/opt/jumpserver/apps/accounts/models/template.py", line 68, in bulk_update_accounts
    Account.objects.bulk_update(accounts, ['version', 'secret'])
  File "/opt/jumpserver/apps/accounts/models/mixins/vault.py", line 41, in bulk_update
    objs = super().bulk_update(objs, fields, batch_size=batch_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 867, in bulk_update
    fields = [self.model._meta.get_field(name) for name in fields]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 867, in <listcomp>
    fields = [self.model._meta.get_field(name) for name in fields]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/options.py", line 671, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Account has no field named 'secret'
```

应该是字段不对，我看数据库中的实际字段名是`_secret`

**Comment by BaiJiangJie** [comment]
最新版本已修复。
