### ISSUE TITLE
使用helm升级，从2.28.0升级到2.28.7 magnus报错，需要确认

### ISSUE THREAD

**Issue by l-duan** [jumpserver/jumpserver#11820]
2023-10-12 17:45:13 [common DEBUG] Start subscribe for expire orgs mapping from memory
2023-10-12 17:45:13 [node_assets_mapping DEBUG] Start subscribe for expire node assets id mapping from memory
2023-10-12 17:45:13 [signal_handlers DEBUG] Start subscribe setting change
2023-10-12 17:45:13 [signal_handlers INFO] Init db port mapper
Traceback (most recent call last):
  File "./jms", line 21, in <module>
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 15, in ready
    django_ready.send(CommonConfig)
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/jumpserver/apps/terminal/signal_handlers.py", line 22, in check_db_port_mapper
    db_port_manager.check()
  File "/opt/jumpserver/apps/terminal/utils/db_port_mapper.py", line 49, in check
    self.add(db)
  File "/opt/jumpserver/apps/terminal/utils/db_port_mapper.py", line 60, in add
    available_port = self.get_next_available_port()
  File "/opt/jumpserver/apps/terminal/utils/db_port_mapper.py", line 110, in get_next_available_port
    raise JMSException(error)
common.exceptions.JMSException: 没有端口可以使用，检查并修改配置文件中 Magnus 监听的端口数量限制。所有可用端口数量：101，已使用端口数量：101

**Comment by BaiJiangJie** [comment]
MAGNUS_PORTS 配置改大一些。

MAGNUS_PORTS=30000-31000

范围需要多大，要看你要多少数据库。

**Comment by l-duan** [comment]
调整value.yaml里magnus的service ports范围后，重新部署还是报相同的错误；
![image](https://github.com/jumpserver/jumpserver/assets/12080822/bd42eba1-4c7a-4ebf-8b3c-b4d788495ce3)
