### ISSUE TITLE
struct.error: unpack requires a bytes object of length 4

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1195]
```
(py3) ➜  jumpserver git:(master) python apps/manage.py compilemessages                                     
Traceback (most recent call last):
  File "apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/seven/workspace/jumpserver0.4/jumpserver/apps/users/models/__init__.py", line 7, in <module>
    from .user import *
  File "/home/seven/workspace/jumpserver0.4/jumpserver/apps/users/models/user.py", line 9, in <module>
    from django.contrib.auth.models import AbstractUser
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/contrib/auth/models.py", line 103, in <module>
    class Group(models.Model):
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/db/models/base.py", line 162, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/db/models/base.py", line 330, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/db/models/fields/related.py", line 1648, in contribute_to_class
    self.remote_field.through = create_many_to_many_intermediary_model(self, cls)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/db/models/fields/related.py", line 1104, in create_many_to_many_intermediary_model
    'verbose_name': _('%(from)s-%(to)s relationship') % {'from': from_, 'to': to},
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/utils/functional.py", line 162, in __mod__
    return six.text_type(self) % rhs
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/utils/functional.py", line 119, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/utils/translation/__init__.py", line 89, in ugettext
    return _trans.ugettext(message)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 338, in gettext
    return do_translate(message, 'gettext')
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 321, in do_translate
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 228, in translation
    _translations[language] = DjangoTranslation(language)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 131, in __init__
    self._add_local_translations()
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 183, in _add_local_translations
    translation = self._new_gnu_trans(localedir)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 156, in _new_gnu_trans
    fallback=use_null_fallback)
  File "/usr/local/lib/python3.6/gettext.py", line 518, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/local/lib/python3.6/gettext.py", line 254, in __init__
    self._parse(fp)
  File "/usr/local/lib/python3.6/gettext.py", line 340, in _parse
    magic = unpack('<I', buf[0:4])[0]
struct.error: unpack requires a bytes object of length 4
(py3) ➜  jumpserver git:(master) 

```
有人遇到过这个错误吗

**Comment by ibuler** [comment]
没有遇到这个问题

**Comment by gengkeye** [comment]
这个问题是由于存在一个.mo的空文件，把它删除重新compilemessages就好了

**Comment by Ashkanfarhady** [comment]
I have the exact problem, how did you guys solve it ?
