### ISSUE TITLE
版本v3.7.1  调用创建服务器api资源报错，控制台api页面创建成功。

### ISSUE THREAD

**Issue by TIGERRAN** [jumpserver/jumpserver#11953]
api控制台页面执行成功
![image](https://github.com/jumpserver/jumpserver/assets/41050950/7372aea4-a183-435b-91b3-eb49740e294e)
![image](https://github.com/jumpserver/jumpserver/assets/41050950/8caa8fd8-a451-4132-a389-2f9a5aedc640)

python调用api 参数如下
params = {
    "name": "test#10.10.10.10"
    "address": "10.10.10.10",
    "platform": "1",
    "nodes": [node_id],
    "protocols": [
         {
           "name": "ssh",
           "port": 22
         }
       ],
      "accounts": [
        {
          "name": "ops",
          "username": "ops",
          "secret_type": "ssh_key",
          "template": "9cbaa00a-ff66-4d4d-bfbd-79560b188098",
          "is_active": "true",
          "push_now": "true"
        },
        {
          "name": "dev",
          "username": "dev",
          "secret_type": "ssh_key",
          "template": "a2b9c741-8828-4a2c-ba3b-6d00eaa0340f",
          "is_active": "true",
          "push_now": "true"
        }
      ],
    "comment": "test",
    "is_active": "true"
}

corer日志报错如下：
cat /opt/jumpserver/data/logs/jumpserver.log
2023-10-24 15:34:35 [log ERROR] Internal Server Error: /api/v1/assets/hosts/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/assets/api/asset/asset.py", line 159, in create
    return super().create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework_bulk/drf3/mixins.py", line 29, in create
    return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py", line 17, in create
    serializer = self.get_serializer(data=request.data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 155, in __init__
    self._extract_accounts()
  File "/opt/jumpserver/apps/assets/serializers/asset/common.py", line 162, in _extract_accounts
    accounts = self.initial_data.pop('accounts', None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 569, in pop
    self._assert_mutable()
  File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 527, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")

这个问题测试一周了，实在不知道问题所在，麻烦给看下，是因为哪里调用的参数有问题吗

**Comment by BaiJiangJie** [comment]
用 POST 方法调用啊。

**Comment by BaiJiangJie** [comment]
<img width="794" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/673633ed-60cc-4d3e-865d-77f1afdd10db">

直接复制的这个吗？

**Comment by TIGERRAN** [comment]
> <img alt="image" width="794" src="https://user-images.githubusercontent.com/32935519/277904072-673633ed-60cc-4d3e-865d-77f1afdd10db.png">
> 直接复制的这个吗？

是的

**Comment by feng626** [comment]
requests.post(asset_url, json=params, headers=self.headers)

**Comment by taoshanghu** [comment]
v3.8.1 同样的问题， 通过页面可以正常创建，通过API 或api/docs/ 提示 {'error': 'Server internal error'}

主机数据
app_user_id = "19003f1f-a7e9-4e0d-8ce3-7ae228b45d6d"
assert_data = {"name": "k8s-1.1.1.1", "address": "1.1.1.1", "platform": "Linux",
 "protocols": [{"name": "ssh", "port": 22}], "is_active": True,
 "accounts": [
     {"template": app_user_id,
      "name": "test", "username": "test"}
 ]}


![image](https://github.com/jumpserver/jumpserver/assets/14832994/102c364a-e2f5-442c-ae60-f285d7c8e8d6)
![image](https://github.com/jumpserver/jumpserver/assets/14832994/7de8df8c-831f-4e4d-9bb3-26257b80203d)

**Comment by wnark** [comment]
> json

post调用时用json而不是data就行
