### ISSUE TITLE
[Bug] Chen 连接数据库一直转圈的问题

### ISSUE THREAD

**Issue by cdq502** [jumpserver/jumpserver#11985]
**JumpServer 版本( v2.28 之前的版本不再支持 )**

v3.8.1

**浏览器版本**
chrome(118.0.5993.89)

**Bug 描述**
相同版本下，新部署的JUMPSERVER，通过相同的NGINX反代，出现，WEBGUI链接数据库一直打圈圈。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/jumpserver/jumpserver/assets/133115516/adf7ba14-ee0a-42e5-b2db-45c631def824)
2.
组件报错信息
```
2023-10-27T06:01:19.719Z ERROR 28 --- [pool-2-thread-6] o.j.c.f.ws.ConsoleWebSocketHandler       : handle message error

java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "currentContext" is null
        at org.jumpserver.chen.framework.console.QueryConsole.onConnect(QueryConsole.java:82) ~[framework-0.0.1.jar!/:0.0.1]
        at org.jumpserver.chen.framework.console.QueryConsole.onInit(QueryConsole.java:65) ~[framework-0.0.1.jar!/:0.0.1]
        at org.jumpserver.chen.framework.ws.ConsoleWebSocketHandler.onConnectPacket(ConsoleWebSocketHandler.java:89) ~[framework-0.0.1.jar!/:0.0.1]
        at org.jumpserver.chen.framework.ws.ConsoleWebSocketHandler.lambda$handleMessage$0(ConsoleWebSocketHandler.java:49) ~[framework-0.0.1.jar!/:0.0.1]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```
3. nginx配置如下：
```
  location / {
    proxy_pass http://localhost:58080;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;

    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
  }
```

**Comment by BaiJiangJie** [comment]
所有数据库都是吗？

**Comment by cdq502** [comment]
是的

**Comment by BaiJiangJie** [comment]
每次连接必现？

**Comment by cdq502** [comment]
每次链接都必现，cli正常。我也怀疑，NGINX的配置问题，配置是一样的，只是换了主机。报错信息说获取不到，websocket转发就几条，时间也设置长了。没找到问题。只看到组件报错。

**Comment by BaiJiangJie** [comment]
你中间加的那层 Nginx 先去掉试一下。

**Comment by cdq502** [comment]
我测测看，但是其它，webgui的RDP，却一直正常，唯独这个链接数据库组件才出现此问题。

**Comment by cdq502** [comment]
直接选择库里面的表是可以正常查看的，唯独查询器，才出现一直转圈圈。

**Comment by cdq502** [comment]
已测试，去掉NGINX，直接访问jumpserver服务，也是相同错误
`jms_chen    | 2023-10-27T07:35:27.606Z ERROR 29 --- [pool-2-thread-8] o.j.c.f.ws.ConsoleWebSocketHandler       : handle message error
jms_chen    |
jms_chen    | java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "currentContext" is null
jms_chen    |   at org.jumpserver.chen.framework.console.QueryConsole.onConnect(QueryConsole.java:82) ~[framework-0.0.1.jar!/:0.0.1]
jms_chen    |   at org.jumpserver.chen.framework.console.QueryConsole.onInit(QueryConsole.java:65) ~[framework-0.0.1.jar!/:0.0.1]
jms_chen    |   at org.jumpserver.chen.framework.ws.ConsoleWebSocketHandler.onConnectPacket(ConsoleWebSocketHandler.java:89) ~[framework-0.0.1.jar!/:0.0.1]
jms_chen    |   at org.jumpserver.chen.framework.ws.ConsoleWebSocketHandler.lambda$handleMessage$0(ConsoleWebSocketHandler.java:49) ~[framework-0.0.1.jar!/:0.0.1]
jms_chen    |   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
jms_chen    |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
jms_chen    |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
jms_chen    |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
jms_chen    |   at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]`

**Comment by Aaron3S** [comment]
是不是 默认数据库为空了

**Comment by cdq502** [comment]
是的，没有选项默认数据库。我看3.8.0 的更新内容有这句

perf: 优化 MySQL、MariaDB 的默认数据库字段不再必填

**Comment by Aaron3S** [comment]
抱歉。这块忽略chen这块默认打开的console种没有默认上下文的问题。我们后续会做优化。

**Comment by cdq502** [comment]
好的，能找到问题就好，也谢谢您们，越做越好，等你们新版本修复。

**Comment by BaiJiangJie** [comment]
计划在 v3.8.2 版本中修复一下。
