### ISSUE TITLE
[Question]  3.7.1版本访问website出现core api发生错误

### ISSUE THREAD

**Issue by wangqiang1988** [jumpserver/jumpserver#11986]
core报错如下：
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/orgs/mixins/api.py", line 20, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/api/connection_token.py", line 473, in get_applet_info
    data = token.get_applet_option()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/models/connection_token.py", line 189, in get_applet_option
    host_account = applet.select_host_account(self.user, self.asset)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/terminal/models/applet/applet.py", line 261, in select_host_account
    host = self.select_host(user, asset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/terminal/models/applet/applet.py", line 188, in select_host
    host = self._select_by_load(hosts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/terminal/models/applet/applet.py", line 166, in _select_by_load
    return hosts[0]
           ~~~~~^^^
IndexError: list index out of range

**Comment by BaiJiangJie** [comment]
升级到新版本解决。

**Comment by wangqiang1988** [comment]
我试一下

**Comment by wangqiang1988** [comment]
升级完jms_web unhealthy，但是其他功能目前正常，不过website还是报core-api错误，log如下：

[log WARNING] Bad Request: /api/v1/authentication/super-connection-token/applet-option/
