### ISSUE TITLE
jumpserver1.0.0 资产导入500错误

### ISSUE THREAD

**Issue by claybbs** [jumpserver/jumpserver#1203]
[简述你的问题]

##### 使用版本
1.2.0
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
1. 资产列表->导入资产

##### 具体表现[截图可能会更好些,最好能截全]
点击确认页面没有反应，通过开发者工具查看：assets/asset/import/500 (Internal Server Error)
jumpserver代码报错如下：

2018-04-16 15:56:40 [exception ERROR] Internal Server Error: /assets/asset/import/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 116, in dispatch
    return super(UserPassesTestMixin, self).dispatch(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/opt/jumpserver/apps/assets/views/asset.py", line 254, in form_valid
    csv_data = [row for row in reader]
  File "/opt/jumpserver/apps/assets/views/asset.py", line 254, in <listcomp>
    csv_data = [row for row in reader]
_csv.Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?

##### 其他

[注:] 完成后请关闭 issue

**Comment by claybbs** [comment]
忽略,在windows下面编辑就好了。记得是csv格式。
