### ISSUE TITLE
全新离线安装初始化数据库报错

### ISSUE THREAD

**Issue by gaye746560359** [jumpserver/jumpserver#12166]
6. Init JumpServer Database
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: HTTPConnection.request() got an unexpected keyword argument 'chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'

**Comment by wojiushixiaobai** [comment]
请将 docker 和 docker-compose 升级至最新版本

**Comment by gaye746560359** [comment]
> 评论

![image](https://github.com/jumpserver/jumpserver/assets/3060035/fd2bed6a-4386-480f-802f-519d1e98fd61)
已经是最新版本

**Comment by wojiushixiaobai** [comment]
将你手动安装的 docker-compose 删除，或者参考 docker 官方文档升级至 compose v2

**Comment by gaye746560359** [comment]
> 将你手动安装的 docker-compose 删除，或者参考 docker 官方文档升级至 compose v2

升级到v2还是报错
![image](https://github.com/jumpserver/jumpserver/assets/3060035/93c53b01-3047-4a89-b1f7-4a116332d92d)

**Comment by wojiushixiaobai** [comment]
先把你的 compose v1 卸载掉
![image](https://github.com/jumpserver/jumpserver/assets/24326988/2bfb46ae-db74-41b0-87e3-c97a3bfe0284)

**Comment by gaye746560359** [comment]
> 先把你的 compose v1 卸载掉 ![image](https://user-images.githubusercontent.com/24326988/284498631-2bfb46ae-db74-41b0-87e3-c97a3bfe0284.png)

安装完后启动的容器只有两个？
![image](https://github.com/jumpserver/jumpserver/assets/3060035/e17260a6-6c3c-401c-9a2b-1ad4b4902abc)

**Comment by wojiushixiaobai** [comment]
都写在屏幕上面的字，仔细看。
安装是安装，安装完成需要你自己启动。如何启动请你看 
```
The Installation is Complete. 
```
这行字的下面。
