### ISSUE TITLE
[Question] idea gateway 通过Jumpserver直连资产时报错

### ISSUE THREAD

**Issue by littlefisher666** [jumpserver/jumpserver#12179]
通过idea gateway直连资产时有报错。但是如果使用资产的用户名密码直接连的话就没问题
<img width="832" alt="image" src="https://github.com/jumpserver/jumpserver/assets/19563352/fe70def3-21a8-4fb8-8bf1-d02188e8bf94">

```
2023-11-21 16:37:26,361 [ 104944] SEVERE - #c.j.g.w.MultistagePanelContainer - Failed to determine OS in 10000 ms
java.lang.IllegalStateException: Failed to determine OS in 10000 ms
	at com.jetbrains.gateway.ssh.deploy.ShellFacade$Companion.getDeployTargetOs(ShellFacade.kt:305)
	at com.jetbrains.gateway.ssh.deploy.ShellFacade$Companion.access$getDeployTargetOs(ShellFacade.kt:226)
	at com.jetbrains.gateway.ssh.deploy.ShellFacade$Companion$getDeployTargetOs$1.invokeSuspend(ShellFacade.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1$3.invokeSuspend(BackgroundProgressCoroutineUtil.kt:174)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:170)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$create$task$1.invoke(BackgroundProgressCoroutineUtil.kt:160)
	at com.intellij.openapi.rd.util.CoroutineProgressContext$Companion$createModal$1$1.run(BackgroundProgressCoroutineUtil.kt:205)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:512)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:87)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by LeeEirc** [comment]
目前仅支持 VSCode 的 remote-ssh 插件。暂且未对 IDEA 的 ssh gateway 优化和支持。

**Comment by littlefisher666** [comment]
> 目前仅支持 VSCode 的 remote-ssh 插件。暂且未对 IDEA 的 ssh gateway 优化和支持。

1. 有计划对Jetbrains的gateway做支持呢？除了idea之外，pycharm也挺需要的，只不过都是Jetbrains gateway罢了
2. 我理解咱们的直连资产的方式应该已经成功了，只不过可能是部分权限控制等等逻辑导致失败了，这块应该稍微改造下即可。毕竟VSCode都已经支持了的

**Comment by LeeEirc** [comment]
1、暂无计划，需要支持 ssh tunnel 等功能，但此方式则无录像审计。
2、与权限控制无关。

**Comment by littlefisher666** [comment]
收到

**Comment by zengjie617789** [comment]
请问下，jumpserver 对Pycharm还没有支持么。

**Comment by ljaa-lu** [comment]
gateway 通过Jumpserver直连资产现在还是不支持吗

**Comment by LeeEirc** [comment]
v4 已经支持，添加以下参数

```
ENABLE_LOCAL_PORT_FORWARD=true
ENABLE_VSCODE_SUPPORT=true
ENABLE_REVERSE_PORT_FORWARD=true

```
