### ISSUE TITLE
Edge浏览器在资产树中点某个节点下面的第一个资产时前端报错，无法打开。

### ISSUE THREAD

**Issue by wzqiang1332** [jumpserver/jumpserver#12171]
**JumpServer 版本3.7.1**

**浏览器版本Microsoft Edge(Chromium)版本-112到119期间都发现报错，无法打开资产**
在default树下面第二级树第三级资源节点，点击层级下资源节点第一个时发现报错，不是所有三级资源节点的第一个都报错，部分是正常的。
在chrome浏览器是可以正常打开的。
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'appletConnectMethod')
TypeError: Cannot read properties of undefined (reading 'appletConnectMethod')
    at t.<anonymous> (main.624da886161826515104.js:2:1303105)
    at polyfills.8daa380586add02896b4.js:2:69669
    at Object.next (polyfills.8daa380586add02896b4.js:2:69774)
    at a (polyfills.8daa380586add02896b4.js:2:68492)
    at e.invoke (polyfills.8daa380586add02896b4.js:2:7400)
    at Object.onInvoke (main.624da886161826515104.js:2:536565)
    at e.invoke (polyfills.8daa380586add02896b4.js:2:7340)
    at t.run (polyfills.8daa380586add02896b4.js:2:2603)
    at polyfills.8daa380586add02896b4.js:2:14364
    at e.invokeTask (polyfills.8daa380586add02896b4.js:2:8084)
    at w (polyfills.8daa380586add02896b4.js:2:13598)
    at w (polyfills.8daa380586add02896b4.js:2:13136)
    at polyfills.8daa380586add02896b4.js:2:14401
    at e.invokeTask (polyfills.8daa380586add02896b4.js:2:8084)
    at Object.onInvokeTask (main.624da886161826515104.js:2:536477)
    at e.invokeTask (polyfills.8daa380586add02896b4.js:2:8005)
    at t.runTask (polyfills.8daa380586add02896b4.js:2:3266)
    at y (polyfills.8daa380586add02896b4.js:2:10351)
    at t.invokeTask [as invoke] (polyfills.8daa380586add02896b4.js:2:9196)
    at f (polyfills.8daa380586add02896b4.js:2:21755)
```

**Bug 描述**

![image](https://github.com/jumpserver/jumpserver/assets/20432873/0350d6b4-4026-4cce-b677-679ac952af88)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by jym503558564** [comment]
截图资产树的节点情况，点击哪级节点下的资产

**Comment by wzqiang1332** [comment]
> 截图资产树的节点情况，点击哪级节点下的资产

![image](https://github.com/jumpserver/jumpserver/assets/20432873/4cc05826-077a-4e6d-bc61-95441b4be715)
第三级资产节点，点击第一个会报这个错，并且不会弹出登录窗，都是该层级只有3个资源。
其他第三级的资产点击第一个节点不会报错。

**Comment by wzqiang1332** [comment]
> 截图资产树的节点情况，点击哪级节点下的资产

![image](https://github.com/jumpserver/jumpserver/assets/20432873/82a3780d-a61c-460b-818e-d145f9383cb6)

点击第三级的第一个节点会报这个错，不会弹出登录窗口。但是第三级有部分的第一个节点点击是正常的。从3.4版本就出现了这个问题，中间陆续升级了几个版本都还存在。edge也是一直跟着升级。在chrome上没有这个问题。

**Comment by jym503558564** [comment]
好的，感谢反馈，我们验证一下。

**Comment by jym503558564** [comment]
无法复现
![image](https://github.com/jumpserver/jumpserver/assets/40739051/9c53f7e1-b0bd-4ca7-a1a1-20c0109bc579)

**Comment by wzqiang1332** [comment]
> v3.9.2无法复现，请升级进行测试 ![image](https://user-images.githubusercontent.com/40739051/284219158-9c53f7e1-b0bd-4ca7-a1a1-20c0109bc579.png)

我怀疑是之前某个版本升级时数据损坏导致的，我删除了其中一个报错的节点，然后重建节点发现是可以正常打开的。

**Comment by wzqiang1332** [comment]
更新到3.9.1了，现在前端不会报错了，但是点击资产会报没有权限，但是实际是有权限的，在chrome可以正常到登录窗口

edge点击
![image](https://github.com/jumpserver/jumpserver/assets/20432873/9ae0a77c-4c81-4ba6-b900-cae6da0a737d)
chrome点击
![image](https://github.com/jumpserver/jumpserver/assets/20432873/8d66276d-1627-4cdf-ab74-f14f9a0c643a)

**Comment by jym503558564** [comment]
暂时先用chrome浏览器，我们测试一下，排查一下是什么原因引起的。

**Comment by wzqiang1332** [comment]
从3.7.1升级到3.8.2，可以正常打开了
