### ISSUE TITLE
测试网关连接性时报错

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1218]
错误信息如下：
```
127.0.0.1 [19/Apr/2018:17:06:28 +0800] "GET /api/assets/v1/gateway/dfb287e0-05bd-4c6c-8c59-34ed02e6f502/test-connective/ HTTP/1.0" 404 5812
Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/data/workspace/py3/lib/python3.6/site-packages/paramiko/transport.py", line 2003, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/data/workspace/py3/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
    buf += self._read_timeout(timeout)
  File "/data/workspace/py3/lib/python3.6/site-packages/paramiko/packet.py", line 552, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/workspace/py3/lib/python3.6/site-packages/paramiko/transport.py", line 1856, in run
    self._check_banner()
  File "/data/workspace/py3/lib/python3.6/site-packages/paramiko/transport.py", line 2008, in _check_banner
    'Error reading SSH protocol banner' + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

```

**Comment by ibuler** [comment]
这就是网关连接异常

**Comment by gengkeye** [comment]
我添加了两个网关，一个是与JP处于同一网段的网关，可以链接；一个是与JP处于不同网段的网关，不可链接。不知道您那边有没有这个情况？
