### ISSUE TITLE
[Question] 配置文件有问题，无法登录，请联系管理员或查看最新文档 如果你是管理员，可以更新配置文件解决，设置配置项 DOMAINS

### ISSUE THREAD

**Issue by zwb0619** [jumpserver/jumpserver#12336]
docker 安装jumpserver3.9.3
能正常到登录界面，但是登录界面报错：
配置文件有问题，无法登录，请联系管理员或查看最新文档
如果你是管理员，可以更新配置文件解决，设置配置项
DOMAINS=192.168.66.123:12380

根据查找官方文档，以及issues的记录记录，解决办法是/opt/jumpserver/config/config.txt，配置DOMAINS="192.168.66.123:12380"
但是进入docker里面，/opt/jumpserver/目录下没有config文件夹。
尝试用了一下方法：
1、在/opt/jumpserver/目录下建立config文件，再建立config.txt文件，写入DOMAINS="192.168.66.123:12380"，保存，重启docker
2、将config.txt文件复制到/opt/jumpserver目录下，重启docker
这两个方法都无法登录

在/opt/jumpserver目录下发现一个config.yml文件，里面内容为空，尝试DOMAINS="192.168.66.123:12380"写入到config.yml，保存，重启docker，docker无法启动，日志报错：
[ ok ] Starting periodic command scheduler: cron.
Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 21, in <module>
    django.setup()
  File "/opt/py3/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/opt/py3/lib/python3.11/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/jumpserver/apps/jumpserver/settings/__init__.py", line 3, in <module>
    from .base import *
  File "/opt/jumpserver/apps/jumpserver/settings/base.py", line 15, in <module>
    from .. import const
  File "/opt/jumpserver/apps/jumpserver/const.py", line 12, in <module>
    CONFIG = ConfigManager.load_user_config()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/jumpserver/conf.py", line 922, in load_user_config
    elif manager.load_from_yml():
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/jumpserver/conf.py", line 907, in load_from_yml
    loaded = self.from_yaml(i)
             ^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/jumpserver/conf.py", line 865, in from_yaml
    return self.from_mapping(obj)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/jumpserver/conf.py", line 886, in from_mapping
    for (key, value) in mapping:
        ^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
 Failed to change the table structure. 

到底该怎么才能登录？？？？

**Comment by zwb0619** [comment]
用的这个docker镜像：jumpserver/jms_all:v3.9.3

**Comment by BaiJiangJie** [comment]
不用创建 config.txt 文件，直接设置环境变量 DOMAINS 试试。

**Comment by BaiJiangJie** [comment]
类似于下面这样的方式。

<img width="1100" alt="image" src="https://github.com/jumpserver/jumpserver/assets/32935519/b19d3f8d-9e99-4cdd-aef6-7a394e6446bd">

**Comment by zwb0619** [comment]
谢谢，加了-e DOMAINS问题解决

**Comment by lxm065** [comment]
docker-compose的在.env加

**Comment by 2063113624** [comment]
@BaiJiangJie 通过quick_start.sh脚本安装，起了多个容器的，这个DOMAINS应该变量 应该加在哪个容器上。

![Image](https://github.com/user-attachments/assets/e3473f1f-ddb5-4538-b214-6d26d446a983)
