### ISSUE TITLE
[Bug] 配置CAS单点登录，CAS携带ticket给到jumpserver，出现错误。

### ISSUE THREAD

**Issue by leshalv** [jumpserver/jumpserver#12349]
**JumpServer 版本( v3.9.3 )**

**浏览器版本**

版本 120.0.6099.109（正式版本） (arm64)

**Bug 描述**

配置CAS单点登录，使用CAS 3 协议版本，登录跳转到CAS服务器，CAS服务器携带ticket给到jumpserver，页面出现错误。
我在日志中进行寻找，并没有找到相关错误日志。

<img width="960" alt="image" src="https://github.com/jumpserver/jumpserver/assets/30397655/464c71c4-a77a-49cd-9c09-3ea1fdd77e8d">

**Bug 重现步骤(有截图更好)**
1. 配置CAS协议
2. 使用CAS协议登录

**Comment by BaiJiangJie** [comment]
看 jumpserver.log 日志。

**Comment by leshalv** [comment]
```
2023-12-17 15:25:03 [log ERROR] Internal Server Error: /core/auth/cas/login/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/views.py", line 72, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/backends/cas/views.py", line 11, in get
    return super().get(request)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/views.py", line 128, in get
    user = authenticate(ticket=ticket,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/mixins.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/backends.py", line 129, in authenticate
    user.__dict__.update(attributes)
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by BaiJiangJie** [comment]
应该还是 CAS 的配置项配置的不对。

**Comment by leshalv** [comment]
> 应该还是 CAS 的配置项配置的不对。

我通过控制台配置的，已经携带ticket给到jumpserver了

**Comment by BaiJiangJie** [comment]
看日志是使用 ticket 认证完成后，创建 user 用户时失败了。
但是认证是不是成功，从日志里看不出来。

**Comment by leshalv** [comment]
> 看日志是使用 ticket 认证完成后，创建 user 用户时失败了。 但是认证是不是成功，从日志里看不出来。

方便加个wechat吗？一起看下。

**Comment by BaiJiangJie** [comment]
嗯，我拉个腾讯会议先看一下。

**Comment by BaiJiangJie** [comment]
白江杰 邀请您参加腾讯会议
会议主题：白江杰的快速会议
会议时间：2023/12/18 16:29-17:29 (GMT+08:00) 中国标准时间 - 北京

点击链接直接加入会议：
https://meeting.tencent.com/dm/JIJzNep9UEnZ

#腾讯会议：307-252-621

复制该信息，打开手机腾讯会议即可参与

**Comment by ywd1988** [comment]
请教一下，具体是cas server   配置啥问题？

**Comment by wellsyu** [comment]
我也遇到这个问题，请教下楼主最后怎么解决的？
