### ISSUE TITLE
[Bug] 集群部署报错，Failed to change the table structure!

### ISSUE THREAD

**Issue by snakewqq** [jumpserver/jumpserver#12414]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
V3.9.3

**浏览器版本**
chrome

**Bug 描述**
集群式部署，mysql和redis都是本机，服务都没有问题，安装jumpserver时始终报错，查看了数据库，表应该没有初始化成功，不知道问题出在哪里，请大神分析一下

**Bug 重现步骤(有截图更好)**
1.   ./jmsctl.sh install

3. 

6. Init JumpServer Database
[+] Running 1/1
 ⠿ Container jms_core  Started                                                                                          0.5s
ALLOWED_HOSTS: 
  - localhost
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 21, in <module>
    django.setup()
  File "/opt/py3/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/py3/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/jumpserver/apps/assets/models/__init__.py", line 10, in <module>
    from .automations import *
  File "/opt/jumpserver/apps/assets/models/automations/__init__.py", line 1, in <module>
    from .base import *
  File "/opt/jumpserver/apps/assets/models/automations/base.py", line 9, in <module>
    from assets.tasks import execute_asset_automation_task
  File "/opt/jumpserver/apps/assets/tasks/__init__.py", line 8, in <module>
    from .nodes_amount import *
  File "/opt/jumpserver/apps/assets/tasks/nodes_amount.py", line 7, in <module>
    from assets.utils import check_node_assets_amount
  File "/opt/jumpserver/apps/assets/utils/__init__.py", line 2, in <module>
    from .node import *
  File "/opt/jumpserver/apps/assets/utils/node.py", line 16, in <module>
    @NodeTreeUpdateLock()
     ^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/assets/locks.py", line 21, in __init__
    super().__init__(name=name, release_on_transaction_commit=True, reentrant=True)
  File "/opt/jumpserver/apps/common/utils/lock.py", line 48, in __init__
    redis = get_redis_client()
            ^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/common/utils/connection.py", line 16, in get_redis_client
    client = cache.client.get_client()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_redis/client/default.py", line 105, in get_client
    self._clients[index] = self.connect(index)
                           ^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_redis/client/default.py", line 118, in connect
    return self.connection_factory.connect(self._server[index])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_redis/pool.py", line 71, in connect
    connection = self.get_connection(params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_redis/pool.py", line 90, in get_connection
    pool = self.get_or_create_connection_pool(params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_redis/pool.py", line 111, in get_or_create_connection_pool
    self._pools[key] = self.get_connection_pool(params)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_redis/pool.py", line 124, in get_connection_pool
    pool = self.pool_cls.from_url(**cp_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 1349, in from_url
    url_options = parse_url(url)
                  ^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 1277, in parse_url
    if url.port:
       ^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as 'b3'
[ERROR] Failed to change the table structure!

**Comment by BaiJiangJie** [comment]
ValueError: Port could not be cast to integer value as 'b3'

配置文件 redis 的端口写的有问题。

**Comment by wojiushixiaobai** [comment]
密码不要使用 `特殊字符串`，或者使用 `''` 单引号将特殊字符串引起来

**Comment by snakewqq** [comment]
> ValueError: Port could not be cast to integer value as 'b3'
> 
> 配置文件 redis 的端口写的有问题。

端口修正后还是一样

**Comment by snakewqq** [comment]
> 密码不要使用 `特殊字符串`，或者使用 `''` 单引号将特殊字符串引起来

找到问题，redis密码不要使用 特殊字符串，我的密码里有 # 和 @ ，貌似不支持

**Comment by snakewqq** [comment]
thanks.
