### ISSUE TITLE
jumpserver v3.10.0版本，访问/api/docs/时报错：Failed to load API definition. Internal Server Error 

### ISSUE THREAD

**Issue by hnzhuzi** [jumpserver/jumpserver#12456]
部署新版本v3.10.0时，访问api接口文档报错：
![企业微信截图_17038222665821](https://github.com/jumpserver/jumpserver/assets/49380375/0c73532d-46ef-45f7-9311-99e2202d1bdc)

同时core的日志如下：
File "/opt/py3/lib/python3.11/site-packages/drf_yasg/inspectors/field.py", line 137, in field_to_swagger_object
    raise SwaggerGenerationError(
drf_yasg.errors.SwaggerGenerationError: Schema for <class 'rbac.serializers.content_type.ContentTypeSerializer'> would override distinct serializer <class 'rbac.serializers.permission.ContentTypeSerializer'> because they implicitly share the same ref_name; explicitly set the ref_name attribute on both serializers' Meta classes
2023-12-29 11:41:57 [permissions ERROR] Action not allowed: su_from_accounts, only `list,retrieve,create,update,partial_update,destroy,bulk_update,partial_bulk_update,bulk_destroy,render_to_json,metadata,GET,OPTIONS,HEAD,POST,PUT,PATCH,DELETE` supported
2023-12-29 11:41:57 [permissions ERROR] Action not allowed: su_from_account_templates, only `list,retrieve,create,update,partial_update,destroy,bulk_update,partial_bulk_update,bulk_destroy,render_to_json,metadata,GET,OPTIONS,HEAD,POST,PUT,PATCH,DELETE` supported
2023-12-29 11:42:00 [permissions ERROR] Action not allowed: exchange, only `create,renewal,get_secret_detail,get_applet_info,release_applet_account,get_virtual_app_info,list,retrieve,update,partial_update,destroy,bulk_update,partial_bulk_update,bulk_destroy,render_to_json,metadata,GET,OPTIONS,HEAD,POST,PUT,PATCH,DELETE` supported
2023-12-29 11:42:00 [permissions ERROR] Action not allowed: get_client_protocol_url, only `create,renewal,get_secret_detail,get_applet_info,release_applet_account,get_virtual_app_info,list,retrieve,update,partial_update,destroy,bulk_update,partial_bulk_update,bulk_destroy,render_to_json,metadata,GET,OPTIONS,HEAD,POST,PUT,PATCH,DELETE` supported
2023-12-29 11:42:00 [permissions ERROR] Action not allowed: get_client_protocol_url, only `create,renewal,get_secret_detail,get_applet_info,release_applet_account,get_virtual_app_info,list,retrieve,update,partial_update,destroy,bulk_update,partial_bulk_update,bulk_destroy,render_to_json,metadata,GET,OPTIONS,HEAD,POST,PUT,PATCH,DELETE` supported
2023-12-29 11:42:00 [permissions ERROR] Action not allowed: expire, only `create,renewal,get_secret_detail,get_applet_info,release_applet_account,get_virtual_app_info,list,retrieve,update,partial_update,destroy,bulk_update,partial_bulk_update,bulk_destroy,render_to_json,metadata,GET,OPTIONS,HEAD,POST,PUT,PATCH,DELETE` supported
2023-12-29 11:42:00 [permissions ERROR] Action not allowed: get_rdp_file, only `create,renewal,get_secret_detail,get_applet_info,release_applet_account,get_virtual_app_info,list,retrieve,update,partial_update,destroy,bulk_update,partial_bulk_update,bulk_destroy,render_to_json,metadata,GET,OPTIONS,HEAD,POST,PUT,PATCH,DELETE` supported
2023-12-29 11:42:00 [permissions ERROR] Action not allowed: get_rdp_file, only `create,renewal,get_secret_detail,get_applet_info,release_applet_account,get_virtual_app_info,list,retrieve,update,partial_update,destroy,bulk_update,partial_bulk_update,bulk_destroy,render_to_json,metadata,GET,OPTIONS,HEAD,POST,PUT,PATCH,DELETE` supported
2023-12-29 11:42:00 [permissions ERROR] Action not allowed: reuse, only `create,renewal,get_secret_detail,get_applet_info,release_applet_account,get_virtual_app_info,list,retrieve,update,partial_update,destroy,bulk_update,partial_bulk_update,bulk_destroy,render_to_json,metadata,GET,OPTIONS,HEAD,POST,PUT,PATCH,DELETE` supported
2023-12-29 11:42:00 [permissions ERROR] Action not allowed: GET, only `get` supported
2023-12-29 11:42:01 [log ERROR] Internal Server Error: /api/docs/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner

**Comment by wojiushixiaobai** [comment]
等待修复

**Comment by hnzhuzi** [comment]
> 等待修复

这个大概什么时候可以修复完？还有，这个api文档打不开会不会影响其它功能使用，比如接口调用啥的。

**Comment by hnzhuzi** [comment]
> 等待修复
除了api文档打不开，也遇到调用接口使用上的问题，麻烦也看一下：
https://github.com/jumpserver/jumpserver/issues/12453

**Comment by wojiushixiaobai** [comment]
文档打不开不影响其他功能。

接口调用问题请检查你的参数是否正确，可以自行通过 开发者工具栏 在 Web 页面创建资产比对。

**Comment by linkdao** [comment]
您好，我是https://github.com/jumpserver/jumpserver/issues/12453问题的提问者，在3.0.4使用没有问题，但是在3.10就有问题

**Comment by linkdao** [comment]
我在创建资产的时候将"template": False，注释id就能创建，但是使用"template": True就提示{"detail":"AccountTemplate对象不存在","code":"object_does_not_exist"}，账号模板无法使用
