### ISSUE TITLE
[Bug] docker jms_all 3.10.0升级3.10.1无法启动

### ISSUE THREAD

**Issue by 37491** [jumpserver/jumpserver#12475]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.1 jms_all
```
$ docker images | grep jms
jumpserver/jms_all   v3.10.1         6bff28e21dad   3 days ago      3.49GB
jumpserver/jms_all   v3.10.0         21365e63346e   11 days ago     3.7GB
```

**浏览器版本**

**Bug 描述**
3.10.0能正常启动,升级到3.10.1后,服务无法启动
```
$ docker logs jms -f

Starting periodic command scheduler: cron.
ALLOWED_HOSTS: 
  - test-jms.local.com
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 21, in <module>
    django.setup()
  File "/opt/py3/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/opt/py3/lib/python3.11/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/jumpserver/apps/jumpserver/settings/__init__.py", line 6, in <module>
    from .auth import *
  File "/opt/jumpserver/apps/jumpserver/settings/auth.py", line 5, in <module>
    import ldap
  File "/opt/py3/lib/python3.11/site-packages/ldap/__init__.py", line 34, in <module>
    import _ldap
ImportError: libldap-2.5.so.0: cannot open shared object file: No such file or directory
 Failed to change the table structure. 
```
**Bug 重现步骤(有截图更好)**
1.jms_all docker从`3.10.0` 升级到`3.10.1`

**Comment by hhhguany** [comment]
我也遇到了同样的问题
