### ISSUE TITLE
[Bug] 上传阿里云应用报错

### ISSUE THREAD

**Issue by kzcPo** [jumpserver/jumpserver#12522]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
v3.10.1

**浏览器版本**
版本 120.0.6099.71（正式版本） (arm64)

**Bug 描述**
从应用商城下载阿里云https://apps.fit2cloud.com/jumpserver/alibaba-cloud 上传文件报错

**Bug 重现步骤(有截图更好)**
![image](https://github.com/jumpserver/jumpserver/assets/16077203/f112f6c0-8ccc-41d7-9e3c-bdd5944e071f)

``` log
==> jumpserver.log <==
2024-01-11 16:10:30 [log ERROR] Internal Server Error: /api/v1/terminal/applets/upload/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/py3/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/terminal/api/applet/applet.py", line 78, in upload
    applet, serializer = Applet.install_from_dir(tmp_dir, builtin=False)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/terminal/models/applet/applet.py", line 144, in install_from_dir
    instance.load_platform_if_need(path)
  File "/opt/jumpserver/apps/terminal/models/applet/applet.py", line 128, in load_platform_if_need
    s.add_type_choices(tp, tp)
  File "/opt/jumpserver/apps/assets/serializers/platform.py", line 194, in add_type_choices
    tp.choice_mapper[name] = label
    ^^^^^^^^^^^^^^^^
AttributeError: 'LabeledChoiceField' object has no attribute 'choice_mapper'

==> unexpected_exception.log <==

2024-01-11 16:10:30 [ERROR]
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/terminal/api/applet/applet.py", line 78, in upload
    applet, serializer = Applet.install_from_dir(tmp_dir, builtin=False)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/terminal/models/applet/applet.py", line 144, in install_from_dir
    instance.load_platform_if_need(path)
  File "/opt/jumpserver/apps/terminal/models/applet/applet.py", line 128, in load_platform_if_need
    s.add_type_choices(tp, tp)
  File "/opt/jumpserver/apps/assets/serializers/platform.py", line 194, in add_type_choices
    tp.choice_mapper[name] = label
    ^^^^^^^^^^^^^^^^
AttributeError: 'LabeledChoiceField' object has no attribute 'choice_mapper'
```

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/pull/12525

**Comment by jym503558564** [comment]
v3.10.2已发布，请升级至最新版本，进行测试。
