### ISSUE TITLE
[Bug] helm更新到3.10.2后 jms-celery 服务起不来

### ISSUE THREAD

**Issue by kzcPo** [jumpserver/jumpserver#12587]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.10.2

**Bug 描述**
helm 更新jms 3.10.1 -> 3.10.2后 jms-celery 服务起不来

<img width="767" alt="image" src="https://github.com/jumpserver/jumpserver/assets/16077203/bf3451e3-22ec-4207-a8f7-ee2c27ed4cf2">
<img width="1185" alt="image" src="https://github.com/jumpserver/jumpserver/assets/16077203/1375574e-7748-4b94-818f-8097925ecc91">

报错日志如下：
```
==> beat.log <==
 self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 1461, in get_connection
    connection.connect()
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 719, in connect
    self.on_connect()
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 763, in on_connect
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 372, in _read_response
    raise error
redis.exceptions.AuthenticationError: invalid username-password pair
```
```
==> beat.log <==
start_celery_beat.py", line 78, in main
    with redis_lock.Lock(redis_client, name="beat-distribute-start-lock", expire=60, auto_renewal=True):
  File "/opt/py3/lib/python3.11/site-packages/redis_lock/__init__.py", line 321, in __enter__
    acquired = self.acquire(blocking=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis_lock/__init__.py", line 208, in acquire
    if self._held:
       ^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis_lock/__init__.py", line 181, in _held
    return self.id == self.get_owner_id()
                      ^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis_lock/__init__.py", line 194, in get_owner_id
    owner_id = self._client.get(self._name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/commands/core.py", line 1816, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 1461, in get_connection
    connection.connect()
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 719, in connect
    self.on_connect()
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 763, in on_connect
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 372, in _read_response
    raise error
redis.exceptions.AuthenticationError: invalid username-password pair
Scheduler: Sending due task users.signal_handlers.clean_audits_log_period (users.signal_handlers.clean_audits_log_period)
Scheduler: Sending due task check_user_expired_periodic (users.tasks.check_user_expired)
Scheduler: Sending due task users.tasks.check_unused_users (users.tasks.check_unused_users)

==> celery_default.log <==
Task users.signal_handlers.clean_audits_log_period[92e30125-a5a8-408f-9a26-138a59b45d11] received
>> Set language to zh
>> Set org to 00000000-0000-0000-0000-000000000000
Task users.tasks.check_user_expired[0d6957ef-10a2-4945-9bc0-e4258de41fac] received
>> Set language to zh
>> Set org to 00000000-0000-0000-0000-000000000000
Task users.tasks.check_unused_users[8e8ac704-edbc-47d7-8890-0253dd0c9098] received
Task users.signal_handlers.clean_audits_log_period[92e30125-a5a8-408f-9a26-138a59b45d11] succeeded in 0.04906945303082466s: None
>> Set language to zh
>> Set org to 00000000-0000-0000-0000-000000000000
Task users.tasks.check_user_expired[0d6957ef-10a2-4945-9bc0-e4258de41fac] succeeded in 0.04240427725017071s: None
Task users.tasks.check_unused_users[8e8ac704-edbc-47d7-8890-0253dd0c9098] raised unexpected: AttributeError("'int' object has no attribute 'isdigit'")
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/ops/celery/decorator.py", line 73, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/users/tasks.py", line 89, in check_unused_users
    if not uncommon_users_ttl or not uncommon_users_ttl.isdigit():
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'isdigit'
```

**Comment by BaiJiangJie** [comment]
应该是你的 Redis 密码中包含特殊字符了，v3.10.2 有 Bug。

v3.10.3 会修复。

**Comment by BaiJiangJie** [comment]
临时解决方案：

进入 core 容器替换这个文件：https://github.com/jumpserver/jumpserver/blob/v3.10/utils/start_celery_beat.py

退出容器，commit 镜像，然后重启服务。

**Comment by kzcPo** [comment]
> 应该是你的 Redis 密码中包含特殊字符了，v3.10.2 有 Bug。
> 
> v3.10.3 会修复。

redis密码未包含特殊字符，只有大小写字符+数字。

**Comment by kzcPo** [comment]
@BaiJiangJie

**Comment by kzcPo** [comment]
@BaiJiangJie 按你说的替换文件后，还是报错
```
==> beat.log <==
     ^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 372, in _read_response
    raise error
redis.exceptions.AuthenticationError: invalid username-password pair
ALLOWED_HOSTS:
  - localhost
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Traceback (most recent call last):
  File "/opt/jumpserver/utils/start_celery_beat.py", line 86, in <module>
    main()
  File "/opt/jumpserver/utils/start_celery_beat.py", line 78, in main
    with redis_lock.Lock(redis_client, name="beat-distribute-start-lock", expire=60, auto_renewal=True):
  File "/opt/py3/lib/python3.11/site-packages/redis_lock/__init__.py", line 321, in __enter__
    acquired = self.acquire(blocking=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis_lock/__init__.py", line 208, in acquire
    if self._held:
       ^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis_lock/__init__.py", line 181, in _held
    return self.id == self.get_owner_id()
                      ^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis_lock/__init__.py", line 194, in get_owner_id
    owner_id = self._client.get(self._name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/commands/core.py", line 1816, in get
    return self.execute_command("GET", name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 1461, in get_connection
    connection.connect()
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 719, in connect
    self.on_connect()
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 763, in on_connect
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/redis/connection.py", line 372, in _read_response
    raise error
redis.exceptions.AuthenticationError: invalid username-password pair
```

**Comment by kzcPo** [comment]
> 前面 redis.exceptions.AuthenticationError: invalid username-password pair 的问题，只大小写 + 数字应该不会报错啊。
> 
> 后面 isdigit 是个 bug。

噢噢，我知道了，我这边redis的验证，是通过用户名+密码，用户名有包含下划线。
```
externalRedis:
  host: xxxxx.redis.zhangbei.xxxxx.com
  port: 6379
  password: "op_jumpserver_w:xxxxxxx"
```

**Comment by BaiJiangJie** [comment]
用户名包含下划线应该也没问题啊。

**Comment by BaiJiangJie** [comment]
我知道，是因为包含 `:` 了，`_` 不影响。
