### ISSUE TITLE
编译安装jumpserverv3.10.3处理国际化时报错：TypeError: unsupported operand type(s) for |: 'ModelBase' and 'type'[Question] 

### ISSUE THREAD

**Issue by fanmaoyang** [jumpserver/jumpserver#12669]
(py3) root@monitor:/opt/jumpserver-v3.10.3# python apps/manage.py compilemessages
ALLOWED_HOSTS: 
  - localhost
  - 127.0.0.1:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Traceback (most recent call last):
  File "/opt/jumpserver-v3.10.3/apps/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/py3/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/jumpserver-v3.10.3/apps/accounts/apps.py", line 9, in ready
    from . import signal_handlers  # noqa
  File "/opt/jumpserver-v3.10.3/apps/accounts/signal_handlers.py", line 10, in <module>
    from audits.signal_handlers import create_activities
  File "/opt/jumpserver-v3.10.3/apps/audits/signal_handlers/__init__.py", line 2, in <module>
    from .login_log import *
  File "/opt/jumpserver-v3.10.3/apps/audits/signal_handlers/login_log.py", line 105, in <module>
    def send_login_info_to_reviewers(instance: UserLoginLog | str, auth_acl_id):
TypeError: unsupported operand type(s) for |: 'ModelBase' and 'type'

**Comment by BaiJiangJie** [comment]
python 版本升级到 v3.11.4。

**Comment by fanmaoyang** [comment]
> python 版本升级到 v3.11.4。

好的，我试一下，谢谢。

**Comment by fanmaoyang** [comment]
> python 版本升级到 v3.11.4。
又报了新的q错误，帮看一下
![image](https://github.com/jumpserver/jumpserver/assets/46638118/22ab42e0-85a5-4dcb-a1ee-b4b06439e313)

**Comment by fanmaoyang** [comment]
(py4) root@monitor:/opt/jumpserver-v3.10.3# python apps/manage.py compilemessages
ALLOWED_HOSTS: 
  - localhost
  - 127.0.0.1:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Traceback (most recent call last):
  File "/opt/jumpserver-v3.10.3/apps/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py4/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/py4/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/py4/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py4/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/py4/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/jumpserver-v3.10.3/apps/orgs/models.py", line 7, in <module>
    from common.utils import lazyproperty, settings, get_logger
  File "/opt/jumpserver-v3.10.3/apps/common/utils/__init__.py", line 7, in <module>
    from .encode import *
  File "/opt/jumpserver-v3.10.3/apps/common/utils/encode.py", line 16, in <module>
    from itsdangerous import (
ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (/opt/py4/lib/python3.11/site-packages/itsdangerous/__init__.py)

**Comment by fanmaoyang** [comment]
> python 版本升级到 v3.11.4。

(py4) root@monitor:/opt/jumpserver-v3.10.3# python apps/manage.py compilemessages
ALLOWED_HOSTS: 
  - localhost
  - 127.0.0.1:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Traceback (most recent call last):
  File "/opt/jumpserver-v3.10.3/apps/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py4/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/py4/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/py4/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py4/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/py4/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/jumpserver-v3.10.3/apps/orgs/models.py", line 7, in <module>
    from common.utils import lazyproperty, settings, get_logger
  File "/opt/jumpserver-v3.10.3/apps/common/utils/__init__.py", line 7, in <module>
    from .encode import *
  File "/opt/jumpserver-v3.10.3/apps/common/utils/encode.py", line 16, in <module>
    from itsdangerous import (
ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (/opt/py4/lib/python3.11/site-packages/itsdangerous/__init__.py)
