### ISSUE TITLE
[Question]  /opt/jumpserver-v3.10.3：python apps/manage.py compilemessages 报错

### ISSUE THREAD

**Issue by fanmaoyang** [jumpserver/jumpserver#12670]
**请描述您的问题.**
(py4) root@monitor:/opt/jumpserver-v3.10.3# python apps/manage.py compilemessages
ALLOWED_HOSTS: 
  - localhost
  - 127.0.0.1:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Traceback (most recent call last):
  File "/opt/jumpserver-v3.10.3/apps/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py4/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/py4/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/py4/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py4/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/py4/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/jumpserver-v3.10.3/apps/orgs/models.py", line 7, in <module>
    from common.utils import lazyproperty, settings, get_logger
  File "/opt/jumpserver-v3.10.3/apps/common/utils/__init__.py", line 7, in <module>
    from .encode import *
  File "/opt/jumpserver-v3.10.3/apps/common/utils/encode.py", line 16, in <module>
    from itsdangerous import (
ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (/opt/py4/lib/python3.11/site-packages/itsdangerous/__init__.py)

**Comment by BaiJiangJie** [comment]
依赖问题。

**Comment by fanmaoyang** [comment]
> 依赖问题。

pip install itsdangerous==2.0.1
