### ISSUE TITLE
[Question] 版本升级时，出现 Duplicate column name 'backup_type' 错误

### ISSUE THREAD

**Issue by k4nzdroid** [jumpserver/jumpserver#12672]
**请描述您的问题.**

版本升级：JumpServer 3.8.2 升级 3.10.3 版本
部署及升级方式：Helm 
Kubernetes 集群版本：v1.25.5-r20-25.2.34.5

通过 helm upgrade 进行升级时，Pod jumpserver-jms-init-db 出现 Error 状态，其日志如下：

```
# kubectl logs jumpserver-jms-init-db-2mtb8
2024-02-20 17:34:00 [DEBU] Start subscribe for expire orgs mapping from memory
2024-02-20T17:34:00.748672440+08:00 2024-02-20 17:34:00 [DEBU] Start subscribe for expire node assets id mapping from memory
2024-02-20T17:34:00.776015140+08:00 2024-02-20 17:34:00 [DEBU] Start subscribe setting change
2024-02-20T17:34:00.782242740+08:00 2024-02-20 17:34:00 [DEBU] Start subscribe for expire node assets id mapping from memory
2024-02-20T17:34:00.787684323+08:00 2024-02-20 17:34:00 [INFO] Check oracle ports (MAGNUS_ORACLE_PORTS)
2024-02-20T17:34:00.802668721+08:00 2024-02-20 17:34:00 Collect static files
2024-02-20T17:34:00.898508282+08:00 ALLOWED_HOSTS: 
2024-02-20T17:34:00.898528078+08:00   - localhost
2024-02-20T17:34:00.898530997+08:00   - 127.0.0.1
2024-02-20T17:34:00.898534170+08:00   - 127.0.0.1:8080
2024-02-20T17:34:00.898536635+08:00   - 127.0.0.1:80
2024-02-20T17:34:00.898539061+08:00   - localhost:8080
2024-02-20T17:34:00.898541382+08:00   - localhost:80
2024-02-20T17:34:00.898543708+08:00   - core:8080
2024-02-20T17:34:00.898546410+08:00   - core:80
2024-02-20T17:34:00.898548684+08:00 ALLOWED_HOSTS: 
2024-02-20T17:34:00.898550978+08:00   - localhost
2024-02-20T17:34:00.898553209+08:00   - 127.0.0.1
2024-02-20T17:34:00.898555427+08:00   - 127.0.0.1:8080
2024-02-20T17:34:00.898557774+08:00   - 127.0.0.1:80
2024-02-20T17:34:00.898559973+08:00   - localhost:8080
2024-02-20T17:34:00.898562243+08:00   - localhost:80
2024-02-20T17:34:00.898564450+08:00   - core:8080
2024-02-20T17:34:00.898566722+08:00   - core:80
2024-02-20T17:34:00.898585960+08:00 2024-02-20 17:34:00 Collect static files done
2024-02-20T17:34:00.898609333+08:00 2024-02-20 17:34:00 Check database structure change ...
2024-02-20T17:34:00.898634706+08:00 2024-02-20 17:34:00 Migrate model change to database ...
2024-02-20T17:34:01.744135202+08:00 Operations to perform:
2024-02-20T17:34:01.744161684+08:00   Apply all migrations: accounts, acls, admin, applications, assets, audits, auth, authentication, captcha, common
, contenttypes, django_cas_ng, django_celery_beat, labels, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
2024-02-20T17:34:01.744166313+08:00 Running migrations:
2024-02-20T17:34:01.795825156+08:00 2024-02-20 17:34:01 Perform migrate failed, exit
2024-02-20T17:34:01.795847265+08:00 Traceback (most recent call last):
2024-02-20T17:34:01.795850768+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-02-20T17:34:01.795853322+08:00     return self.cursor.execute(sql, params)
2024-02-20T17:34:01.795855603+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795858301+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
2024-02-20T17:34:01.795860658+08:00     return self.cursor.execute(query, args)
2024-02-20T17:34:01.795862845+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795865058+08:00   File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
2024-02-20T17:34:01.795867436+08:00     res = self._query(mogrified_query)
2024-02-20T17:34:01.795869637+08:00           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795871836+08:00   File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
2024-02-20T17:34:01.795874101+08:00     db.query(q)
2024-02-20T17:34:01.795876334+08:00   File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
2024-02-20T17:34:01.795878975+08:00     _mysql.connection.query(self, query)
2024-02-20T17:34:01.795881491+08:00 MySQLdb.OperationalError: (1060, "Duplicate column name 'backup_type'")
2024-02-20T17:34:01.795892273+08:00 
2024-02-20T17:34:01.795894833+08:00 The above exception was the direct cause of the following exception:
2024-02-20T17:34:01.795896918+08:00 
2024-02-20T17:34:01.795902109+08:00 Traceback (most recent call last):
2024-02-20T17:34:01.795904723+08:00   File "/opt/jumpserver/./jms", line 88, in perform_db_mi
grate
2024-02-20T17:34:01.795906915+08:00     management.call_command('migrate')
2024-02-20T17:34:01.795909189+08:00   File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
2024-02-20T17:34:01.795911393+08:00     return command.execute(*args, **defaults)
2024-02-20T17:34:01.795913605+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795915849+08:00   File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
2024-02-20T17:34:01.795918115+08:00     output = self.handle(*args, **options)
2024-02-20T17:34:01.795920323+08:00              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795922514+08:00   File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
2024-02-20T17:34:01.795924746+08:00     res = handle_func(*args, **kwargs)
2024-02-20T17:34:01.795927020+08:00           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795929319+08:00   File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
2024-02-20T17:34:01.795931491+08:00     post_migrate_state = executor.migrate(
2024-02-20T17:34:01.795933689+08:00                          ^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795935960+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
2024-02-20T17:34:01.795938170+08:00     state = self._migrate_all_forwards(
2024-02-20T17:34:01.795940349+08:00             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795942842+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
2024-02-20T17:34:01.795945146+08:00     state = self.apply_migration(
2024-02-20T17:34:01.795947303+08:00             ^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795949473+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
2024-02-20T17:34:01.795951835+08:00     state 
= migration.apply(state, schema_editor)
2024-02-20T17:34:01.795954443+08:00             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795956676+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
2024-02-20T17:34:01.795959080+08:00     operation.database_forwards(
2024-02-20T17:34:01.795961323+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
2024-02-20T17:34:01.795963693+08:00     schema_editor.add_field(
2024-02-20T17:34:01.795966016+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/schema.py", line 104, in add_field
2024-02-20T17:34:01.795968181+08:00     super().add_field(model, field)
2024-02-20T17:34:01.795970424+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 682, in add_field
2024-02-20T17:34:01.795972704+08:00     self.execute(sql, params)
2024-02-20T17:34:01.795974976+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
2024-02-20T17:34:01.795977190+08:00     cursor.execute(sql, params)
2024-02-20T17:34:01.795979419+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
2024-02-20T17:34:01.795984293+08:00     return self._execute_with_wrappers(
2024-02-20T17:34:01.795986579+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795988877+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2024-02-20T17:34:01.795991109+08:00     return executor(sql, params, many, context)
2024-02-20T17:34:01.795993240+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.795995517+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
2024-02-20T17:34:01.795997675+08:00     with self.db.wrap_database_errors:
2024-02-20T17:34:01.796000364+08:00   File "/opt/py3/lib/py
thon3.11/site-packages/django/db/utils.py", line 91, in __exit__
2024-02-20T17:34:01.796002559+08:00     raise dj_exc_value.with_traceback(traceback) from exc_value
2024-02-20T17:34:01.796004745+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
2024-02-20T17:34:01.796006991+08:00     return self.cursor.execute(sql, params)
2024-02-20T17:34:01.796009210+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.796022984+08:00   File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
2024-02-20T17:34:01.796025550+08:00     return self.cursor.execute(query, args)
2024-02-20T17:34:01.796027788+08:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.796030066+08:00   File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
2024-02-20T17:34:01.796032259+08:00     res = self._query(mogrified_query)
2024-02-20T17:34:01.796061348+08:00           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-20T17:34:01.796063718+08:00   File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
2024-02-20T17:34:01.796065956+08:00     db.query(q)
2024-02-20T17:34:01.796068668+08:00   File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
2024-02-20T17:34:01.796070912+08:00     _mysql.connection.query(self, query)
2024-02-20T17:34:01.796073458+08:00 django.db.utils.OperationalError: (1060, "Duplicate column name 'backup_type'")
2024-02-20T17:34:02.609379622+08:00   Applying accounts.0018_accountbackupautomation_backup_type_and_more...

# kubectl get pods
NAME                                     READY   STATUS    RESTARTS         AGE
jumpserver-jms-celery-76bc8695f-22hnn    1/1     Running   10 (9m59s ago)   31h
jumpserver-jms-chen-789f56ff7c-7hrsl     1/1     Running   0                31h
jumpserver-jms-core-99664b76c-8bzrx      1/1     Running   0                31h
jumpserver-jms-init-db-2mtb8             0/1     Error     0                6m44s
jumpserver-jms-init-db-7dn9d             0/1     Error     0                4m15s
jumpserver-jms-init-db-lxffm             0/1     Error     0                5m50s
jumpserver-jms-init-db-nvntv             0/1     Error     0                7m18s
jumpserver-jms-init-db-rww72             0/1     Error     0                7m42s
jumpserver-jms-init-db-vfrwk             0/1     Error     0                7m57s
jumpserver-jms-init-db-w5622             0/1     Error     0                81s
jumpserver-jms-kael-58446877d7-wq5rb     1/1     Running   0                31h
jumpserver-jms-koko-8d769c996-6699h      1/1     Running   0                31h
jumpserver-jms-lion-54fd74649d-dpxd9     1/1     Running   0                31h
jumpserver-jms-magnus-5885679d65-mzqfm   1/1     Running   0                31h
jumpserver-jms-web-d5858f967-xxhjx       1/1     Running   0                39m

# helm list 
NAME      	NAMESPACE 	REVISION	UPDATED                                	STATUS	CHART            	APP VERSION
jumpserver	jumpserver	11      	2024-02-20 17:33:34.968506314 +0800 CST	failed	jumpserver-3.10.3	v3.10.3  
```

**Comment by BaiJiangJie** [comment]
升级过程中是不是中断过一次？

**Comment by k4nzdroid** [comment]
> 升级过程中是不是中断过一次？

针对这次的操作，印象中是没有中断过的。但是以往就不清楚了。最早是通过 jumpserver-installer 部署，jmsctl.sh 来管理，数据库是内置的数据库。后来迁移到 Kubernetes 集群中，数据库使用了云数据库 RDS。

请问有补救的方法么？数据库备份，然后重新部署 JumpServer 服务，再导入数据可以么？

**Comment by k4nzdroid** [comment]
> 需要还原到以前没有重复字段的数据库备份，重新部署升级。
> 
> 也就是 `accounts_accountbackupautomation` 表，不包含 `backup_type` 字段的时候。

按照您说的，数据库恢复到之前没有 backup_type 字段的时候，然后部署 3.10.3 版本，现在能成功运行了。

谢谢
