### ISSUE TITLE
v3.1.2 版本升级数据库报错

### ISSUE THREAD

**Issue by linzehai0801** [jumpserver/jumpserver#12816]
v3.1.2升级到v3.10.4数据库报错报错如下
请问该如何解决？
![jumpserver-1](https://github.com/jumpserver/jumpserver/assets/88591254/8a96fa83-74df-4473-a9d6-9680c4b2dbe0)
``Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (3780, "Referencing column 'asset_ptr_id' and referenced column 'id' in foreign key constraint 'assets_custom_asset_ptr_id_c9ab0d9d_fk_assets_asset_id' are incompatible.")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 249, in apply_migration
    with self.connection.schema_editor(
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 164, in __exit__
    self.execute(sql)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/py3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (3780, "Referencing column 'asset_ptr_id' and referenced column 'id' in foreign key constraint 'assets_custom_asset_ptr_id_c9ab0d9d_fk_assets_asset_id' are incompatible.")

**Comment by BaiJiangJie** [comment]
回滚数据库，重新升级，升级过程中不要中断。（因为进行数据表结构迁移是一个完整的操作，不能断开）。

**Comment by linzehai0801** [comment]
试过回滚数据库，重新升级，结果还是一样的哦，过程没有中断过

**Comment by linzehai0801** [comment]
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 87                                                 , in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", li                                                 ne 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in exe                                                 cute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _qu                                                 ery
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in                                                  query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1050, "Table 'assets_custom' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py",                                                  line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line                                                  448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line                                                  96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migra                                                 te.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", li                                                 ne 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", li                                                 ne 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", li                                                 ne 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/migration.py", l                                                 ine 130, in apply
    operation.database_forwards(
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/operations/model                                                 s.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", l                                                 ine 447, in create_model
    self.execute(sql, params or None)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", l                                                 ine 199, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67                                                 , in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80                                                 , in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84                                                 , in _execute
    with self.db.wrap_database_errors:
  File "/opt/py3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __ex                                                 it__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 87                                                 , in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", li                                                 ne 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in exe                                                 cute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _qu                                                 ery
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in                                                  query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'assets_custom' already exists")
这个步骤是我再一次尝试的结果

**Comment by BaiJiangJie** [comment]
我看和第一次执行的报错不一样了。
多尝试几次，创建数据库时编码要保持一致。

**Comment by linzehai0801** [comment]
抱歉忘记说了，最开始是报错Table 'assets_custom' already exists"，然后我手动把这个表删除了，接着就有了第一个报错(3780, "Referencing column 'asset_ptr_id' and referenced column 'id' in foreign key constraint 'assets_custom_asset_ptr_id_c9ab0d9d_fk_assets_asset_id' are incompatible.")，现在无论怎么尝试都是这两个报错

**Comment by BaiJiangJie** [comment]
https://github.com/jumpserver/jumpserver/issues/11047#issuecomment-1646524721

看下这个回复。主要是字符集问题。
