### ISSUE TITLE
客户端批量执行SQL 错误： [S1000]: Cannot invoke "Object.getClass()" because "currentProtocolEntity" is null[Bug] Bug 标题

### ISSUE THREAD

**Issue by Linkjie-11** [jumpserver/jumpserver#12853]
## 注意
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

## 当前使用的 JumpServer 版本 (必填)
[在这里输入当前使用的 JumpServer 的版本号]
3.10.5
## 使用的版本类型 (必填)
- [√ ] 社区版
- [√] 企业版
- [ ] 企业试用版

## 版本安装方式 (必填)
- [ √] 离线安装 (下载离线包)

## Bug 描述 (详细)
[在这里描述 Bug 的详细情况，包括其影响和出现的具体情况]
mangus客户端批量执行SQL报错
![图片](https://github.com/jumpserver/jumpserver/assets/52249559/063e5321-8953-468c-b7ab-adbc24811567)
web端没有问题
![图片](https://github.com/jumpserver/jumpserver/assets/52249559/eecc16fd-a2e3-4770-adee-b7c90ad7465b)
数据库版本8.0.29/8.0.26均出现此问题
## 复现步骤
1. 创建两张表，随机生成数据
3. 使用uodate更新两张表的数据，同时执行两条SQL
3. 调用SQL客户端（DBeaver）新建SQL查询，批量执行两条SQL报错 [S1000]: Cannot invoke "Object.getClass()" because "currentProtocolEntity" is null
4. 尝试替换驱动后重新执行，依旧报错

## 期望行为
类似WEB端可批量执行SQL

## 实际行为
无法执行

## 系统环境
- 操作系统：Windows 10, 
- 浏览器/应用版本 DBeaver23.dbeaver24

**Comment by BaiJiangJie** [comment]
客户端报的错，DBeaver 不通过 JumpServer 连一下数据库试试。

**Comment by Linkjie-11** [comment]
> 客户端报的错，DBeaver 不通过 JumpServer 连一下数据库试试。

测试过了 直接没问题

**Comment by BaiJiangJie** [comment]
那执行一下别的语句呢？
比如两条 select 。

**Comment by Linkjie-11** [comment]
> 那执行一下别的语句呢？ 比如两条 select 。
白哥，我都测试过了。

**Comment by BaiJiangJie** [comment]
@jym503558564 看看能否复现一下。

**Comment by jym503558564** [comment]
无法复现。DBeaver中执行单条SQL和多条SQL时，选择不同的按钮。
![image](https://github.com/jumpserver/jumpserver/assets/40739051/1c31ceb1-d8d0-4402-8faa-2a030d38c106)

**Comment by maganto1** [comment]
``` java
org.springframework.dao.TransientDataAccessResourceException: 
### Error updating database.  Cause: java.sql.SQLException: Cannot invoke "Object.getClass()" because "currentProtocolEntity" is null
### The error may exist in com/wunding/learn/membership/service/mapper/material/SupplyMaterialMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: update                 supply_material             set                                       total_num = ?,                                                         prepare_reduce_num = ?,                                   update_time = now()             where update_time = ? and id = ?          ;              update                 supply_material             set                                       total_num = ?,                                                         prepare_reduce_num = ?,                                   update_time = now()             where update_time = ? and id = ?          ;              update                 supply_material             set                                       total_num = ?,                                                         prepare_reduce_num = ?,                                   update_time = now()             where update_time = ? and id = ?          ;              update                 supply_material             set                                       total_num = ?,                                                         prepare_reduce_num = ?,                                   update_time = now()             where update_time = ? and id = ?
### Cause: java.sql.SQLException: Cannot invoke "Object.getClass()" because "currentProtocolEntity" is null
; Cannot invoke "Object.getClass()" because "currentProtocolEntity" is null; nested exception is java.sql.SQLException: Cannot invoke "Object.getClass()" because "currentProtocolEntity" is null
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:110)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at jdk.proxy2/jdk.proxy2.$Proxy172.update(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy175.updateBatchXml(Unknown Source)
```
问题是不是还存在，代码中
```xml
<foreach collection="supplyMaterials" separator=";" item="item">
            update
                test
            set
                <if test="item.totalNum != null">
                    total_num = #{item.totalNum},
                </if>
                <if test="item.prepareReduceNum != null and item.prepareReduceNum != 0">
                    prepare_reduce_num = #{item.prepareReduceNum},
                </if>
                update_time = now()
            where update_time = #{item.updateTime} and id = #{item.id}
        </foreach>
```
JumpServer 版本
![image](https://github.com/user-attachments/assets/b47b92ff-132a-4979-95af-7dcd600271f3)
