### ISSUE TITLE
coco启动失败

### ISSUE THREAD

**Issue by 113998274** [jumpserver/jumpserver#1313]
##### 使用版本
jumpserver 1.3.0
centos7 手动安装

##### 问题复现步骤
jms start -d已经显示启动成功，web能登录设置，但是cocod start -d启动cocod失败

cocod日志：
2018-05-11 13:31:16 [terminal ERROR] Response code is 500: MultipleObjectsReturned at /api/terminal/v1/terminal/
get() returned more than one Terminal -- it returned 2!

Request Method: POST
Request URL: http://127.0.0.1:8080/api/terminal/v1/terminal/
Django Version: 1.11
Python Executable: /root/.pyenv/versions/3.6.5/envs/jumpserverpy3/bin/python
Python Version: 3.6.5

jumpserver日志
127.0.0.1 [11/May/2018:15:26:46 +0800] "POST /api/terminal/v1/terminal/ HTTP/1.1" 500 18318

2018-05-11 15:30:25 [exception ERROR] Internal Server Error: /api/terminal/v1/terminal/
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/terminal/api.py", line 45, in create
    terminal = get_object_or_none(Terminal, name=name, is_deleted=False)
  File "/opt/jumpserver/apps/common/utils.py", line 44, in get_object_or_none
    obj = model.objects.get(**kwargs)
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.pyenv/versions/3.6.5/envs/jumpserverpy3/lib/python3.6/site-packages/django/db/models/query.py", line 383, in get
    (self.model._meta.object_name, num)
terminal.models.MultipleObjectsReturned: get() returned more than one Terminal -- it returned 2!

[注:] 完成后请关闭 issue

**Comment by 113998274** [comment]
Python Version: 3.6.5  
请问Python版本有硬性要求吗？

**Comment by jokimina** [comment]
看报错coco重复注册了吧  在web上 会话管理->终端管理 看看名称是否有重复的. 

还不行的话 可以清除掉 terminal 表(慎重！) , 然后重新启动coco注册  @113998274

**Comment by BaiJiangJie** [comment]
请使用最新版本，如果有问题请重新打开Issues
