### ISSUE TITLE
新加的服务器无法推送系统用户，无法连接，请问是有限制吗？

### ISSUE THREAD

**Issue by qianghong000** [jumpserver/jumpserver#1317]
[简述你的问题]
新加几台服务器发现无法连接，报错：('Bad authentication type', ['publickey']) (allowed_types=['publickey'])。公钥已添加，通过堡垒机管理机可以直接连过去。
目标机器发现没有创建系统用户。手动推送系统用户后，看日志有报错。

##### 使用版本
[Version 1.3.0-2 GPLv2.]

##### 问题复现步骤

2018-05-14 20:59:03 [signals_handler INFO] System user RD(rd) update signal received
2018-05-14 21:23:01 [signals_handler DEBUG] Receive django ready signal
2018-05-14 21:23:01 [signals_handler DEBUG] - fresh all settings
2018-05-14 21:23:01 [signals_handler DEBUG] Receive django ready signal
2018-05-14 21:23:01 [signals_handler DEBUG] - fresh all settings
2018-05-14 21:23:01 [signals_handler DEBUG] Receive django ready signal
2018-05-14 21:23:01 [signals_handler DEBUG] Receive django ready signal
2018-05-14 21:23:01 [signals_handler DEBUG] - fresh all settings
2018-05-14 21:23:01 [signals_handler DEBUG] - fresh all settings
2018-05-14 21:23:05 [exception ERROR] Internal Server Error: /api/terminal/v1/terminal/status/
Traceback (most recent call last):
File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/opt/py3/lib/python3.6/site-packages/django/utils/deprecation.py", line 138, in call
response = self.process_request(request)
File "/opt/py3/lib/python3.6/site-packages/django/middleware/locale.py", line 24, in process_request
i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
File "/opt/py3/lib/python3.6/site-packages/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
for url_pattern in get_resolver(urlconf).url_patterns:
File "/opt/py3/lib/python3.6/site-packages/django/utils/functional.py", line 35, in get
res = instance.dict[self.name] = self.func(instance)
File "/opt/py3/lib/python3.6/site-packages/django/urls/resolvers.py", line 405, in url_patterns
patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/opt/py3/lib/python3.6/site-packages/django/utils/functional.py", line 35, in get
res = instance.dict[self.name] = self.func(instance)
File "/opt/py3/lib/python3.6/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
return import_module(self.urlconf_name)
File "/usr/local/python3.6/lib/python3.6/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "", line 678, in exec_module
File "", line 219, in _call_with_frames_removed
File "/opt/jumpserver/apps/jumpserver/urls.py", line 30, in 
url(r'^api/terminal/', include('terminal.urls.api_urls', namespace='api-terminal')),
File "/opt/py3/lib/python3.6/site-packages/django/conf/urls/init.py", line 50, in include
urlconf_module = import_module(urlconf_module)
File "/usr/local/python3.6/lib/python3.6/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "", line 678, in exec_module
File "", line 219, in _call_with_frames_removed
File "/opt/jumpserver/apps/terminal/urls/api_urls.py", line 8, in 
from .. import api
File "/opt/jumpserver/apps/terminal/api.py", line 15, in 
import jms_storage
File "/opt/py3/lib/python3.6/site-packages/jms_storage/init.py", line 10, in 
from .aws import aws
File "/opt/py3/lib/python3.6/site-packages/jms_storage/aws.py", line 3, in 
import boto3
File "/opt/py3/lib/python3.6/site-packages/boto3/init.py", line 16, in 
from boto3.session import Session
File "/opt/py3/lib/python3.6/site-packages/boto3/session.py", line 17, in 
import botocore.session
ModuleNotFoundError: No module named 'botocore.session'

**Comment by qianghong000** [comment]
2018-05-14 20:59:03 [signals_handler INFO] System user `RD(rd)` update signal received
2018-05-14 21:23:01 [signals_handler DEBUG] Receive django ready signal
2018-05-14 21:23:01 [signals_handler DEBUG]   - fresh all settings
2018-05-14 21:23:01 [signals_handler DEBUG] Receive django ready signal
2018-05-14 21:23:01 [signals_handler DEBUG]   - fresh all settings
2018-05-14 21:23:01 [signals_handler DEBUG] Receive django ready signal
2018-05-14 21:23:01 [signals_handler DEBUG] Receive django ready signal
2018-05-14 21:23:01 [signals_handler DEBUG]   - fresh all settings
2018-05-14 21:23:01 [signals_handler DEBUG]   - fresh all settings
2018-05-14 21:23:05 [exception ERROR] Internal Server Error: /api/terminal/v1/terminal/status/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/py3/lib/python3.6/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/opt/py3/lib/python3.6/site-packages/django/middleware/locale.py", line 24, in process_request
    i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
  File "/opt/py3/lib/python3.6/site-packages/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
    for url_pattern in get_resolver(urlconf).url_patterns:
  File "/opt/py3/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/py3/lib/python3.6/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/py3/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/py3/lib/python3.6/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/jumpserver/urls.py", line 30, in <module>
    url(r'^api/terminal/', include('terminal.urls.api_urls', namespace='api-terminal')),
  File "/opt/py3/lib/python3.6/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/terminal/urls/api_urls.py", line 8, in <module>
    from .. import api
  File "/opt/jumpserver/apps/terminal/api.py", line 15, in <module>
    import jms_storage
  File "/opt/py3/lib/python3.6/site-packages/jms_storage/__init__.py", line 10, in <module>
    from .aws import aws
  File "/opt/py3/lib/python3.6/site-packages/jms_storage/aws.py", line 3, in <module>
    import boto3
  File "/opt/py3/lib/python3.6/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/opt/py3/lib/python3.6/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
ModuleNotFoundError: No module named 'botocore.session'

**Comment by wojiushixiaobai** [comment]
看资产详情，确定测试可连接性和更新硬件信息正常，如果资产只支持key登录，请在系统设置-终端设置里面去的密码认证。保存并重启jumpserver

**Comment by iwasnobody** [comment]
@qianghong000 你好，你的问题解决了吗

**Comment by chenylon** [comment]
我遇到过和你一样的情况 主机是AWS EC2 ubuntu的系统 显示
('Bad authentication type', ['publickey']) (allowed_types=['publickey'])

fatal: [test]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 54.238.212.212 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "rc": 0}

从上面的debug信息里我发现是因为 ec2系统里没有python ........
于是 sudo apt install python 
就OK了
