### ISSUE TITLE
[Question] 由3.9.3 升級上 3.10.10 出問題

### ISSUE THREAD

**Issue by alextsang30** [jumpserver/jumpserver#13257]
## 注意
**请描述您的问题.** <br>
**JumpServer 版本( v2.28 之前的版本不再支持 )** <br>
_针对过于简单的 Bug 描述不予考虑。请确保提供足够的细节和信息以支持 Bug 的复现和修复。_

在v3.9.3 升級上 3.10.10時候, 出現了
MySQLdb.OperationalError: (1005, 'Can\'t create table `jumpserver`.`terminal_appprovider` (errno: 150 "Foreign key constraint is incorrectly formed")') 這個錯誤. 

## 当前使用的 JumpServer 版本 (必填)
3.9.3

## 使用的版本类型 (必填)
社区版

## 版本安装方式 (必填)
在线安装 (一键命令)

## 问题描述 (详细)
[在这里描述你遇到的问题]

在v3.9.3 升級上 3.10.10時候, 出現了
MySQLdb.OperationalError: (1005, 'Can\'t create table `jumpserver`.`terminal_appprovider` (errno: 150 "Foreign key constraint is incorrectly formed")') 這個錯誤. 

Error log 如下:
2024-05-20 16:40:56 Migrate model change to database ...
Operations to perform:
  Apply all migrations: accounts, acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, labels, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying labels.0001_initial... OK
  Applying labels.0002_auto_20231103_1659... OK
  Applying assets.0126_remove_asset_labels... OK
  Applying assets.0127_automation_remove_account... OK
  Applying labels.0003_alter_labeledresource_options_and_more... OK
  Applying ops.0028_celerytaskexecution_creator... OK
  Applying rbac.0014_auto_20231208_1548... OK
  Applying users.0049_alter_user_unique_together_user_slack_id_and_more... OK
  Applying users.0050_user_lark_id_alter_user_source... OK
  Applying settings.0011_chatprompt... OK
  Applying settings.0012_alter_setting_options... OK
  Applying settings.0013_auto_20240326_1531... OK
  Applying terminal.0068_virtualapp...2024-05-20 16:40:58 Perform migrate failed, exit
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1005, 'Can\'t create table `jumpserver`.`terminal_appprovider` (errno: 150 "Foreign key constraint is incorrectly formed")')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
    schema_editor.add_field(
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/schema.py", line 104, in add_field
    super().add_field(model, field)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 682, in add_field
    self.execute(sql, params)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/py3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1005, 'Can\'t create table `jumpserver`.`terminal_appprovider` (errno: 150 "Foreign key constraint is incorrectly formed")')
[ERROR] Failed to change the table structure!

## 尝试过的解决方法

1. 嘗試新安裝v3.9.3之後導出表結構和現有的v3.9.3數據, 之後創建新數據庫導入後升級失敗.
2. 嘗試在升級失敗後刪除terminal_appprovider之後升級, 會出現terminal_virtualapp和terminal_virtualapppublication兩個表已經存在錯誤, 當刪除了terminal_appprovider,terminal_virtualapp和terminal_virtualapppublication之後,會重覆這個MySQLdb.OperationalError: (1005, 'Can\'t create table `jumpserver`.`terminal_appprovider` (errno: 150 "Foreign key constraint is incorrectly formed")') 錯誤.
檢查了新安裝的v3.9.3的表結構, 這三個表terminal_appprovider,terminal_virtualapp和terminal_virtualapppublication不存在.

**Comment by wojiushixiaobai** [comment]
`数据库字符集` 和 `排序规则` 不一致导致，自行修改后重新升级即可。

**Comment by alextsang30** [comment]
> `数据库字符集` 和 `排序规则` 不一致导致，自行修改后重新升级即可。

檢查了數據庫字符集是一樣的, 但排序規則要怎樣排查和解決呢? 謝謝

**Comment by wojiushixiaobai** [comment]
- https://docs.jumpserver.org/zh/master/faq/upgrade/#2

**Comment by alextsang30** [comment]
@wojiushixiaobai 感謝你的幫忙. 檢查了表和數據庫的排序規則不一致導致. 修改後升級正常了.

檢查和修改步驟: 
1. 檢查數據庫的字符集和排序規則
show create database jumpserver;
+------------+--------------------------------------------------------------------------------------------+
| Database   | Create Database                                                                            |
+------------+--------------------------------------------------------------------------------------------+
| jumpserver | CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci */ |
+------------+--------------------------------------------------------------------------------------------+
2. 檢查其中一個表的字符集和排序規則
SHOW CREATE TABLE users_user_groups;
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| users_user_groups | CREATE TABLE `users_user_groups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` char(32) NOT NULL,
  `usergroup_id` char(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_user_groups_user_id_usergroup_id_ac1e3824_uniq` (`user_id`,`usergroup_id`),
  KEY `users_user_groups_usergroup_id_90818973_fk_users_usergroup_id` (`usergroup_id`),
  CONSTRAINT `users_user_groups_user_id_5f6f5a90_fk_users_user_id` FOREIGN KEY (`user_id`) REFERENCES `users_user` (`id`),
  CONSTRAINT `users_user_groups_usergroup_id_90818973_fk_users_usergroup_id` FOREIGN KEY (`usergroup_id`) REFERENCES `users_usergroup` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=89 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
3. 調整數據庫的排序規則
ALTER DATABASE jumpserver CHARACTER SET utf8mb3 COLLATE utf8mb3_bin;
4. 重新升級.
