### ISSUE TITLE
[Question] vscode连接跳板机会出现无规律断开连接的现象

### ISSUE THREAD

**Issue by zdf0221** [jumpserver/jumpserver#13371]
### 产品版本

v3.10.9

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

ubuntu 20.04.6 LTS

### 🤔 问题描述

![image](https://github.com/jumpserver/jumpserver/assets/9160607/786cf910-b917-47e6-a47b-ec6bd7043083)

我们使用token方式配置vscode经跳板机连接资产，配置成功之后实际使用中发现，vscode server会有不规律的断开连接情况（大致5-15min不等），尝试重连后一般能够成功重连，少数情况下会提示SSH: connection refused

想了解这个问题应该如何排查？谢谢

related issue: #13278

### 期望结果

提供一个排查问题的SOP流程，或者一些相关的资料支持
如果能实现自动重连的feature就更好了

### 补充信息

我们已经将token expire time调整为30天，且可以重连应该不是该问题。

**Comment by zdf0221** [comment]
VSCODE这边重新连接失败时候的log

```
[15:55:27.036] Log Level: 2
[15:55:27.052] SSH Resolver called for "ssh-remote+rs7-token", attempt 1
[15:55:27.052] "remote.SSH.useLocalServer": true
[15:55:27.052] "remote.SSH.useExecServer": true
[15:55:27.053] "remote.SSH.path": undefined
[15:55:27.053] "remote.SSH.configFile": undefined
[15:55:27.053] "remote.SSH.useFlock": true
[15:55:27.053] "remote.SSH.lockfilesInTmp": false
[15:55:27.053] "remote.SSH.localServerDownload": auto
[15:55:27.053] "remote.SSH.remoteServerListenOnSocket": false
[15:55:27.053] "remote.SSH.showLoginTerminal": false
[15:55:27.053] "remote.SSH.defaultExtensions": []
[15:55:27.053] "remote.SSH.loglevel": 2
[15:55:27.053] "remote.SSH.enableDynamicForwarding": true
[15:55:27.054] "remote.SSH.enableRemoteCommand": false
[15:55:27.054] "remote.SSH.serverPickPortsFromRange": {}
[15:55:27.054] "remote.SSH.serverInstallPath": {}
[15:55:27.058] VS Code version: 1.89.1
[15:55:27.058] Remote-SSH version: remote-ssh@0.112.2024053015
[15:55:27.058] linux x64
[15:55:27.060] SSH Resolver called for host: rs7-token
[15:55:27.060] Setting up SSH remote "rs7-token"
[15:55:27.063] Acquiring local install lock: /tmp/vscode-remote-ssh-6f7344a3-install.lock
[15:55:27.065] Looking for existing server data file at /home/z000020/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6f7344a3-dc96b837cf6bb4af9cd736aa3af08cf8279f7685-0.112.2024053015-es/data.json
[15:55:27.066] Using commit id "dc96b837cf6bb4af9cd736aa3af08cf8279f7685" and quality "stable" for server
[15:55:27.068] Install and start server if needed
[15:55:27.070] PATH: /home/z000020/miniconda3/bin:/home/z000020/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
[15:55:27.070] Checking ssh with "ssh -V"
[15:55:27.076] > OpenSSH_8.9p1 Ubuntu-3ubuntu0.7, OpenSSL 3.0.2 15 Mar 2022

[15:55:27.078] askpass server listening on /run/user/1000026/vscode-ssh-askpass-6af8a071cad7a48d7470ac3412647aa0a851f206.sock
[15:55:27.079] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000026/vscode-ssh-askpass-e2b86cb8124cbc21a073cd85ad2542ea7e8ea115.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","36241","-o","ConnectTimeout=15","rs7-token"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/z000020/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6f7344a3-dc96b837cf6bb4af9cd736aa3af08cf8279f7685-0.112.2024053015-es/data.json"}
[15:55:27.079] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000026/keyring/ssh","SHELL":"/bin/sh","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000026/vscode-ssh-askpass-6af8a071cad7a48d7470ac3412647aa0a851f206.sock"}
[15:55:27.082] Spawned 26522
[15:55:27.149] > local-server-1> Running ssh connection command: ssh -v -T -D 36241 -o ConnectTimeout=15 rs7-token
[15:55:27.151] > local-server-1> Spawned ssh, pid=26530
[15:55:27.154] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.7, OpenSSL 3.0.2 15 Mar 2022
[15:55:27.165] stderr> kex_exchange_identification: read: Connection reset by peer
[15:55:27.165] stderr> Connection reset by 192.168.1.165 port 27108
[15:55:27.166] > local-server-1> ssh child died, shutting down
[15:55:27.169] Local server exit: 0
[15:55:27.169] Received install output: local-server-1> Running ssh connection command: ssh -v -T -D 36241 -o ConnectTimeout=15 rs7-token
local-server-1> Spawned ssh, pid=26530
OpenSSH_8.9p1 Ubuntu-3ubuntu0.7, OpenSSL 3.0.2 15 Mar 2022
kex_exchange_identification: read: Connection reset by peer
Connection reset by 192.168.1.165 port 27108
local-server-1> ssh child died, shutting down

[15:55:27.169] Failed to parse remote port from server output
[15:55:27.171] Resolver error: Error: 
	at g.Create (/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:499918)
	at t.handleInstallOutput (/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:497240)
	at e (/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:558422)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:580377
	at async t.withShowDetailsEvent (/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:584036)
	at async /home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:555127
	at async T (/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:553178)
	at async t.resolveWithLocalServer (/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:554667)
	at async k (/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:577548)
	at async t.resolve (/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:581407)
	at async /home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/extension.js:2:847860
[15:55:27.176] ------




[15:55:27.354] Opening exec server for ssh-remote+rs7-token
[15:55:27.359] Acquiring local install lock: /tmp/vscode-remote-ssh-6f7344a3-install.lock
[15:55:27.359] Initizing new exec server for ssh-remote+rs7-token
[15:55:27.372] Looking for existing server data file at /home/z000020/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6f7344a3-dc96b837cf6bb4af9cd736aa3af08cf8279f7685-0.112.2024053015-es/data.json
[15:55:27.374] Using commit id "dc96b837cf6bb4af9cd736aa3af08cf8279f7685" and quality "stable" for server
[15:55:27.376] Install and start server if needed
[15:55:27.381] askpass server listening on /run/user/1000026/vscode-ssh-askpass-e12e43ffab05169e8335bf22698dfee7d4ce5444.sock
[15:55:27.381] Spawning local server with {"serverId":2,"ipcHandlePath":"/run/user/1000026/vscode-ssh-askpass-c6dbfb74a12a7bd2ece7b59642a92837cf175ba8.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","36241","-o","ConnectTimeout=15","rs7-token"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/z000020/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6f7344a3-dc96b837cf6bb4af9cd736aa3af08cf8279f7685-0.112.2024053015-es/data.json"}
[15:55:27.381] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000026/keyring/ssh","SHELL":"/bin/sh","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/home/z000020/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.2024053015/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000026/vscode-ssh-askpass-e12e43ffab05169e8335bf22698dfee7d4ce5444.sock"}
[15:55:27.385] Spawned 26531
[15:55:27.454] > local-server-2> Running ssh connection command: ssh -v -T -D 36241 -o ConnectTimeout=15 rs7-token
[15:55:27.457] > local-server-2> Spawned ssh, pid=26540
[15:55:27.459] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.7, OpenSSL 3.0.2 15 Mar 2022
[15:55:27.459] stderr> ssh: connect to host 192.168.1.165 port 27108: Connection refused
[15:55:27.460] > local-server-2> ssh child died, shutting down
[15:55:27.464] Local server exit: 0
[15:55:27.464] Received install output: local-server-2> Running ssh connection command: ssh -v -T -D 36241 -o ConnectTimeout=15 rs7-token
local-server-2> Spawned ssh, pid=26540
OpenSSH_8.9p1 Ubuntu-3ubuntu0.7, OpenSSL 3.0.2 15 Mar 2022
ssh: connect to host 192.168.1.165 port 27108: Connection refused
local-server-2> ssh child died, shutting down

[15:55:27.465] Failed to parse remote port from server output
[15:55:27.465] Exec server for ssh-remote+rs7-token failed: Error
[15:55:27.465] Error opening exec server for ssh-remote+rs7-token: Error
```

**Comment by BaiJiangJie** [comment]
检查一下 VS Code 断开连接时 KoKo 组件的日志。

**Comment by BaiJiangJie** [comment]
由于长时间未回复，暂时关闭当前 issue，如果有任何问题请重新打开。
