### ISSUE TITLE
Error reading SSH protocol bannerfiledescriptor out of range in select()

### ISSUE THREAD

**Issue by opstrip** [jumpserver/jumpserver#1350]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本  1.3.0-2 ]

##### 问题复现步骤
1. [步骤1] jumpserver持续运行一到两天以上
2. [步骤2] 使用人数比较多时

##### 具体表现[截图可能会更好些,最好能截全]
Xshell等终端连接跳板机会提示“Error reading SSH protocol bannerfiledescriptor out of range in select()
”错误导致无法连接。图形界面Web终端直接卡死。直连进入跳板机所在主机，查看ssh进程总数在80+，并没有达到1024。

##### 其他

[注:] 完成后请关闭 issue

**Comment by opstrip** [comment]
现在临时解决方案是每天凌晨3点定时任务重启jumpserver，更改跳板机所在主机的TMOUT设置5分钟自动断开，ssh进程数一般在40左右。还是几乎每2周出现异常这个报错，导致无法登入其他机器，只能通过手动重启解决。不知道1.3.2有没有彻底解决这个问题，改天升级试试。

**Comment by ibuler** [comment]
使用网关了吗？

**Comment by jokimina** [comment]
`2018-07-06 11:30:13 INFO - Connect to xxxxx-vpc02 (proxy:64) [7119-Thread-35960]
2018-07-06 11:30:14 DEBUG - Get system user xxxxx password: cash*** key: MIIEpAIBAAKCAQEAm93S8jKR2nGLlUpRaRWh+tJEOWnvTRdpNuEqp3J/+MpQSRDh*** (assets:80) [7119-Thread-35960]
2018-07-06 11:30:14 DEBUG - starting thread (client mode): 0x5835e518 (transport:1687) [7119-Thread-36001]
2018-07-06 11:30:14 DEBUG - Local version/idstring: SSH-2.0-paramiko_2.4.0 (transport:1687) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR - Exception: Error reading SSH protocol bannerfiledescriptor out of range in select() (transport:1687) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR - Traceback (most recent call last): (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -   File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 2003, in _check_banner (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -     buf = self.packetizer.readline(timeout) (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -   File "/opt/py3/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -     buf += self._read_timeout(timeout) (transport:1685) [7119-Thread-36001]2018-07-06 11:30:14 ERROR -   File "/opt/py3/lib/python3.6/site-packages/paramiko/packet.py", line 540, in _read_timeout (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -     x = self.__socket.recv(128) (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -   File "/opt/py3/lib/python3.6/site-packages/paramiko/proxy.py", line 95, in recv (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -     [self.process.stdout], [], [], select_timeout) (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR - ValueError: filedescriptor out of range in select() (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -  (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR - During handling of the above exception, another exception occurred: (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -  (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR - Traceback (most recent call last): (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -   File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 1856, in run (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -     self._check_banner() (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -   File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 2008, in _check_banner (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -     'Error reading SSH protocol banner' + str(e) (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol bannerfiledescriptor out of range in select() (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR -  (transport:1685) [7119-Thread-36001]
2018-07-06 11:30:14 ERROR - Connect xxxxx@172.16.0.7:22 auth failed, password:                                  cashb**********, key: b'fb:52:10:21:fb:87:50:b3:32:da:0e:41:ec:9f:28:68' (connection:63) [7119-Thread-35960]`

我这里也出现了  使用了网关

**Comment by jokimina** [comment]
```
Jul  6 14:28:14 xxxxx sshd[11820]: debug1: Forked child 11837.
Jul  6 14:28:14 xxxxx sshd[11837]: Set /proc/self/oom_score_adj to 0
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: inetd sockets after dupping: 3, 3
Jul  6 14:28:14 xxxxx sshd[11837]: Connection from xx.xx.173.169 port 58362 on 172.16.0.3 port 22
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: Client protocol version 2.0; client software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.2 pat OpenSSH* compat 0x04000000
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: Enabling compatibility mode for protocol 2.0
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: permanently_set_uid: 104/65534 [preauth]
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: list_hostkey_types: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Jul  6 14:28:14 xxxxx sshd[11837]: Connection closed by xx.xx.173.169 [preauth]
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: do_cleanup [preauth]
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: monitor_read_log: child log fd closed
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: do_cleanup
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: Killing privsep child 11838
Jul  6 14:28:14 xxxxx sshd[11837]: debug1: audit_event: unhandled event 12
```


网关的ssh日志

**Comment by jokimina** [comment]
https://www.jianshu.com/p/a74a48a54fce
参考这个博文, 受限于内核 select传入1024以上的fd就会出现这个错误.

https://github.com/paramiko/paramiko/blob/master/paramiko/proxy.py#L97
proxyCommand->recv使用了select, 不太好处理...除非重新编译内核改掉__FD_SETSIZE 

https://github.com/jumpserver/coco/commit/fcb5074941d8fd8c7cc7ee7f3fcf09eb6859096a
不过看已经默默在coco上用paramiko channel, 代替ProxyCommand了... 我更新下试试

**Comment by opstrip** [comment]
@ibuler 嗯，是使用了网关，大概10个以上。今天升级到1.3.2版本了，我先小规模测试下吧。

**Comment by ibuler** [comment]
已修复，有问题重新打开issue
