### ISSUE TITLE
[Bug] 使用dbeaver转储数据库失败了

### ISSUE THREAD

**Issue by maasengit** [jumpserver/jumpserver#13516]
### Product Version

v3.10.9

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

CentOS-7

### 🐛 Bug Description

采用数据库客户端方式使用dbeaver打开mysql数据库，查询、删除、增加记录都没问题
转储数据库失败了。

转储数据库

`C:\Users\Administrator\AppData\Roaming\DBeaverData\drivers\clients\mysql_8\win\mysqldump.exe --skip-lock-tables --routines --add-drop-table --disable-keys --extended-insert --comments -u 5d588fed-a2f1-4262-b41b-0845e609ed38 --host=jms.ddcir.com --port=3306 test
任务  'MySQL 转储' 开始于 Wed Jun 26 17:15:28 CST 2024
mysqldump: Got error: 1045: password not match when trying to connect

任务  'MySQL 转储' 结束于 Wed Jun 26 17:15:28 CST 2024
2024-06-26 17:15:28.463 - IO error: Process failed (exit code = 2). See error log.
2024-06-26 17:15:28.463 - java.io.IOException: Process failed (exit code = 2). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:263)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:241)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:283)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:87)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
`

### Recurrence Steps

dbeaver里选择数据库，右键，工具 > 转储数据库，下一步，开始

**Comment by Aaron3S** [comment]
我们先确认一下。

**Comment by Aaron3S** [comment]
大概了解了原因。
