### ISSUE TITLE
[Question] 无法对接casdoor平台

### ISSUE THREAD

**Issue by ERroooooR** [jumpserver/jumpserver#13545]
### 产品版本

3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [X] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

jumpserver:1panel  docker
casdoor:docker

### 🤔 问题描述

按照casdoor文档对接后
网页报错： Server error occur, contact administrator
jumpserver.log
```
2024-06-22 17:08:35 [ERRO] Internal Server Error: /core/auth/cas/login/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/views.py", line 72, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/backends/cas/views.py", line 11, in get
    return super().get(request)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/views.py", line 128, in get
    user = authenticate(ticket=ticket,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/mixins.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/backends.py", line 29, in authenticate
    username, attributes, pgtiou = client.verify_ticket(ticket)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/cas.py", line 202, in verify_ticket
    return self.verify_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/cas.py", line 296, in verify_response
    return cls.parse_response_xml(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/cas.py", line 259, in parse_response_xml
    tree = ElementTree.fromstring(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1350, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 36, column 159`
```

casdoor似乎没有cas可配置的选项，在设置应用后在casdoor网页能成功登陆，但跳转后jumpserver报错

```
{
  "cas:user": "username"
}
```

**Comment by BaiJiangJie** [comment]
初步判断是 `Casdoor` 服务返回的 `Response` 和你配置的`用户属性映射`字段没有匹配上。

配置文件 `LOG_LEVEL`  开启 `DEBUG`，看一下认证时 `Casdoor` 返回的响应。

日志中搜索下面的关键字：
```python
logger.debug('%s response - %s', cls.__name__, response)
```

**Comment by ERroooooR** [comment]
在配置文件中修改了LOG_LEVEL为DEBUG
但是在日志中并没有显示response -相关关键字，不清楚是否这个debug有其他的输出地方
并且检查了对应源码，日志输出语句确实存在
jumpserver.log
`2024-07-04 00:45:58 [INFO] Try using auth backend: <rbac.backends.RBACBackend object at 0x7f627c0f73d0>
2024-07-04 00:45:58 [INFO] Try using auth backend: <authentication.backends.base.JMSModelBackend object at 0x7f627c119450>
2024-07-04 00:45:58 [INFO] Try using auth backend: <authentication.backends.pubkey.PublicKeyAuthBackend object at 0x7f627c118fd0>
2024-07-04 00:45:58 [INFO] Try using auth backend: <authentication.backends.cas.backends.CASBackend object at 0x7f627c11b810>
2024-07-04 00:45:59 [DEBU] pid 91 executor submit run update_user_last_used
2024-07-04 00:45:59 [DEBU] pid 91 executor submit run update_token_last_used
2024-07-04 00:45:59 [DEBU] Api require perms: ['terminal.view_terminalconfig'], result: True
2024-07-04 00:45:59 [DEBU] Api require perms: ['terminal.view_terminalconfig'], result: True
2024-07-04 00:45:59 [ERRO] Internal Server Error: /core/auth/cas/login/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/views.py", line 72, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/backends/cas/views.py", line 11, in get
    return super().get(request)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/views.py", line 128, in get
    user = authenticate(ticket=ticket,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/mixins.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/backends.py", line 29, in authenticate
    username, attributes, pgtiou = client.verify_ticket(ticket)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/cas.py", line 202, in verify_ticket
    return self.verify_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/cas.py", line 296, in verify_response
    return cls.parse_response_xml(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/cas.py", line 259, in parse_response_xml
    tree = ElementTree.fromstring(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1350, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 11, column 159
2024-07-04 00:45:59 [DEBU] Api require perms: ['terminal.view_terminalconfig'], result: True`

然后我重新部署一个纯净的casdoor,在默认配置情况下，并没有复现相关错误
但出现了新的问题，jumpserver陷入了无限的登陆循环
jumpserver.log
`2024-07-04 00:59:45 [INFO] Try using auth backend: <rbac.backends.RBACBackend object at 0x7f627c0cc110>
2024-07-04 00:59:45 [INFO] Try using auth backend: <authentication.backends.base.JMSModelBackend object at 0x7f626a16eed0>
2024-07-04 00:59:52 [INFO] Try using auth backend: <rbac.backends.RBACBackend object at 0x7f626a1a2410>
2024-07-04 00:59:52 [INFO] Try using auth backend: <authentication.backends.base.JMSModelBackend object at 0x7f626a1b8190>
2024-07-04 00:59:52 [INFO] Try using auth backend: <authentication.backends.pubkey.PublicKeyAuthBackend object at 0x7f626a1b81d0>
2024-07-04 00:59:52 [INFO] Try using auth backend: <authentication.backends.cas.backends.CASBackend object at 0x7f626a1b8290>
2024-07-04 00:59:52 [INFO] Try using auth backend: <authentication.backends.sso.AuthorizationTokenAuthentication object at 0x7f626abcd490>
2024-07-04 00:59:58 [WARN] Unauthorized: /api/v1/users/profile/
2024-07-04 00:59:59 [DEBU] Api require perms: ['terminal.view_terminalconfig'], result: True
2024-07-04 00:59:59 [DEBU] pid 88 executor submit run update_user_last_used
2024-07-04 00:59:59 [DEBU] pid 88 executor submit run update_token_last_used
2024-07-04 00:59:59 [DEBU] Api require perms: ['terminal.view_terminalconfig'], result: True
2024-07-04 01:00:00 [DEBU] Api require perms: ['terminal.view_terminalconfig'], result: True
`

**Comment by ERroooooR** [comment]
https://github.com/jumpserver/jumpserver/issues/11451
根据此issues已经解决
之前可能是错误的casdoor配置导致数据污染，出现了特殊字符
此问题确认解决，抱歉打扰了
