### ISSUE TITLE
[Question] v3.10.11升级至v4.0版本，更改admin用户后表结构报错，jms_kael和jms_magnus容器缺失，导致部分功能异常

### ISSUE THREAD

**Issue by flacce** [jumpserver/jumpserver#13615]
### 产品版本

3.10.11

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Debian12

### v3.10升级至v4.0版本，表结构报错
```
Operations to perform:
  Apply all migrations: accounts, acls, admin, assets, audits, auth, authentication, captcha, contenttypes, django_cas_ng, django_celery_beat, labels, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying notifications.0003_initial_admin_msg...2024-07-05 15:42:42 Perform migrate failed, exit
Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/migration.py", line 125, in apply
    operation.database_forwards(
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/jumpserver/apps/notifications/migrations/0003_initial_admin_msg.py", line 11, in init_user_msg_subscription
    user = User.objects.get(username='admin')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
__fake__.User.DoesNotExist: User matching query does not exist.
[ERROR] 表结构变更失败!
```

猜测可能是之前还可以更改默认的admin账号名的时候将admin改成了useradmin 是否是这个影响的
想到的解决方法，将数据库里面的useradmin全部替换成admin，还是在用户列表新增一个admin用户
或者是否还有其它更好的方法能够解决数据库表结构变更失败呢？

### 期望结果

v3.10正常升级至v4.0版本

**Comment by renziyou** [comment]
先升级到v3.10.11再升级到v4.0.0已验证通过

**Comment by ibuler** [comment]
@flacce admin 用户是不能删除和更改的

**Comment by flacce** [comment]
> 先升级到v3.10.11再升级到v4.0.0已验证通过

就是3.10.11升级4.0.0，表结构报错

**Comment by flacce** [comment]
> @flacce admin 用户是不能删除和更改的

在去年早些版本的时候是还能修改

**Comment by flacce** [comment]
现在也能改呀，改回去后升级成功了，这个如果是之前改了admin用户名的话，不改回去应该都升级失败（虽然好像记得哪一个版本后说不能修改admin账号）
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/8e6c9c8f-8c43-4187-a593-7537e660378e)
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/3719087d-ddb3-4acf-80e3-381fc87f29e4)
![图片](https://github.com/jumpserver/jumpserver/assets/64127000/52867bdd-9629-4801-9695-2a9b09981a95)

**Comment by flacce** [comment]
@ibuler 请问4.0是没有使用jms_magnus容器了吗？

> https://hub.docker.com/r/jumpserver/jms_magnus/tags 
也没有更新4.0的镜像

![图片](https://github.com/jumpserver/jumpserver/assets/64127000/4d4a2ef6-8544-48bf-b5c2-0f9b324262a2)
也没有其它容器映射33061端口
导致数据库客户端使用DB连接向导根本连不上


![图片](https://github.com/jumpserver/jumpserver/assets/64127000/f8a2c630-37fd-42f6-a1ab-74b9f7f47972)
4.0比3.10.11少了jms_maguns和jms_kael 是不会对原有功能造成影响吗？

**Comment by BaiJiangJie** [comment]
是的，v4.0 移除了 jms_magnus 容器，不支持使用本地客户端方式连接 MySQL 了。但是 Web 方式将 PostgreSQL 数据库开放了出来。

jms_kael 的功能移动到 jms_koko 中了，Kael 的功能不受影响。

**Comment by mattholy** [comment]
同样的错误，总结下就是降级到3.10.11，把管理员用户名改回admin，然后再升级？

**Comment by fengdwx** [comment]
> 是的，v4.0 移除了 jms_magnus 容器，不支持使用本地客户端方式连接 MySQL 了。但是 Web 方式将 PostgreSQL 数据库开放了出来。
> 
> jms_kael 的功能移动到 jms_koko 中了，Kael 的功能不受影响。

数据库web gui 是否会支持json字段展示
