### ISSUE TITLE
coco报错

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1384]
版本1.3.1
```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/sshd.py", line 104, in handle_chan
    self.dispatch(client)
  File "/opt/coco/coco/sshd.py", line 111, in dispatch
    InteractiveServer(client).interact()
  File "/opt/coco/coco/interactive.py", line 271, in interact
    rv = self.dispatch(opt)
  File "/opt/coco/coco/interactive.py", line 86, in dispatch
    self.search_and_proxy(opt)
  File "/opt/coco/coco/interactive.py", line 254, in search_and_proxy
    self.proxy(asset)
  File "/opt/coco/coco/interactive.py", line 264, in proxy
    forwarder.proxy(asset, system_user)
  File "/opt/coco/coco/proxy.py", line 58, in proxy
    session.bridge()
  File "/opt/coco/coco/session.py", line 134, in bridge
    self.close()
  File "/opt/coco/coco/session.py", line 167, in close
    self.post_bridge()
  File "/opt/coco/coco/session.py", line 105, in post_bridge
    self._replay_recorder.session_end(self.id)
  File "/opt/coco/coco/recorder.py", line 58, in session_end
    self.upload_replay(session_id)
  File "/opt/coco/coco/recorder.py", line 77, in upload_replay
    self.upload_replay(session_id, times-1)
  File "/opt/coco/coco/recorder.py", line 77, in upload_replay
    self.upload_replay(session_id, times-1)
  File "/opt/coco/coco/recorder.py", line 77, in upload_replay
    self.upload_replay(session_id, times-1)
  File "/opt/coco/coco/recorder.py", line 70, in upload_replay
    self.storage = jms_storage.JMSReplayStorage(app_service)
  File "/opt/py3/lib/python3.6/site-packages/jms_storage/jms.py", line 9, in __init__
    self.client = config.get("SERVICE")
  File "/opt/py3/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AppService' object has no attribute 'get'

2018-05-31 15:05:26 [recorder DEBUG] Send 2 commands to server
2018-05-31 15:05:26 [app INFO] Remove session: 4cce39fa-91e3-43af-8681-098d99c91b74
```
使用AWS保存录像的时候报的一个错误：
```
Wed May 30 10:17:36 2018
Coco version 1.3.1, more see https://www.jumpserver.org
Quit the server with CONTROL-C.
Starting ssh server at 0.0.0.0:2222
Starting websocket server at 0.0.0.0:5000
2018-05-30 10:17:36 [recorder WARNING] Failed push replay file: None, try again 1
2018-05-30 10:17:49 [httpd DEBUG] On connect event trigger
2018-05-30 10:17:50 [httpd ERROR] 'AppService' object has no attribute 'check_user_with_token'
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/flask_socketio/__init__.py", line 624, in _handle_event
    ret = handler()
  File "/opt/coco/coco/httpd.py", line 116, in on_connect
    super().on_connect()
  File "/opt/coco/coco/httpd.py", line 23, in on_connect
    self.current_user = self.get_current_user()
  File "/opt/coco/coco/httpd.py", line 36, in get_current_user
    user = app_service.check_user_with_token(token)
  File "/opt/py3/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AppService' object has no attribute 'check_user_with_token'
```

**Comment by gengkeye** [comment]
1.3.2已发布，不知道有么有修复这个问题？
