### ISSUE TITLE
[Bug] 在升级v4.0.1中如果用户修改了默认admin用户可能导致升级失败

### ISSUE THREAD

**Issue by Boc-chi-no** [jumpserver/jumpserver#13860]
### Product Version

v4.0.1

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

使用一键脚本安装
由于安全因素修改了admin用户名

### 🐛 Bug Description

在迁移数据库时获取管理员用户的过程不够严谨

### Recurrence Steps

在升级v4.0.1修改默认用户名,然后进行一键在线升级

### Additional Information

2024-08-01 13:44:26 Migrate model change to database ...
Operations to perform:
  Apply all migrations: accounts, acls, admin, assets, audits, auth, authentication, captcha, contenttypes, django_cas_ng, django_celery_beat, labels, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying notifications.0003_initial_admin_msg...2024-08-01 13:44:27 Perform migrate failed, exit
Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 88, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/migration.py", line 125, in apply
    operation.database_forwards(
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/jumpserver/apps/notifications/migrations/0003_initial_admin_msg.py", line 11, in init_user_msg_subscription
    user = User.objects.get(username='admin')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
__fake__.User.DoesNotExist: User matching query does not exist.
[ERROR] Failed to change the table structure!

### Attempted Solutions

在升级之前将用户名修改回admin

**Comment by BaiJiangJie** [comment]
嗯，已知问题，v4.1.0 中会修复。

**Comment by FengLing02** [comment]
> 嗯，已知问题，v4.1.0 中会修复。

如何回退呢，更新4.0.1失败了，现在Redis无法启动
