### ISSUE TITLE
[Bug] 升级V4.1.0版本报错

### ISSUE THREAD

**Issue by leim** [jumpserver/jumpserver#14047]
### Product Version

v4.1.0

### Product Edition

- [ ] Community Edition
- [X] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [X] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

centos 7.9
docker 24.02

### 🐛 Bug Description

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 203, in <module>
    upgrade_db()
  File "/opt/jumpserver/./jms", line 137, in upgrade_db
    perform_db_migrate()
  File "/opt/jumpserver/./jms", line 92, in perform_db_migrate
    raise e
  File "/opt/jumpserver/./jms", line 89, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/migration.py", line 125, in apply
    operation.database_forwards(
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/jumpserver/apps/tickets/migrations/0003_initial_ticket_flow_data.py", line 13, in create_ticket_flow_and_approval_rule
    super_user = User.objects.get(username='admin')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
__fake__.User.DoesNotExist: User matching query does not exist.

### Recurrence Steps

原版本 v3.10.12，
升级 v4.0.0 ，失败
升级 v4.0.1，失败
升级 v4.0.2，失败
升级 v4.1.0，失败

### Expected Behavior

不说啥了

**Comment by Nickyang00** [comment]
是否修改过默认管理员admin名称

**Comment by BaiJiangJie** [comment]
应该是，升级前，必须包含 admin 用户。
@leim 

> 是否修改过默认管理员admin名称

**Comment by everLeek** [comment]
同样遇到问题，同样修改过 admin 名称。

**Comment by everLeek** [comment]
请问这个问题有进展吗？或者有没有一个临时解决方案？

**Comment by BaiJiangJie** [comment]
临时解决方案是升级前保证有 username 为 admin 的用户，升级过程中必须包含。

**Comment by leim** [comment]
把admin用户的用户名改为admin，然后就升级成功了
