### ISSUE TITLE
[Question] vscode remote-ssh 连接不了资产

### ISSUE THREAD

**Issue by edentliang** [jumpserver/jumpserver#14053]
### 产品版本

3

### 版本类型

- [ ] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

ubuntu22

### 🤔 问题描述

https://github.com/jumpserver/jumpserver/issues/10241

已经按照教程配置jumpserver 的配置文件，和在资产服务器添加 `AllowTcpForwarding yes`

问题跟上面issue 一样， 使用 `ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222` 可以在终端连接，但是用vscode连接时，返回

> 10:52:11.846] Showing password prompt
[10:52:16.637] Got password response
[10:52:16.637] "install" wrote data to terminal: "************"
[10:52:16.672] > 
[10:52:17.301] > ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
[10:52:18.626] "install" terminal command done
[10:52:18.627] Install terminal quit with output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
[10:52:18.627] Received install output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
[10:52:18.627] Failed to parse remote port from server output
[10:52:18.629] Resolver error: Error: 
	at g.Create (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:679699)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:642502
	at async t.withShowDetailsEvent (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:645820)
	at async t.resolve (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:643552)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:722230
[10:52:18.635] ------
>
使用教程的第二种方法时，返回：

> [15:40:35.341] Got password response
[15:40:35.342] "install" wrote data to terminal: "************"
[15:40:35.369] > 
[15:40:35.768] > channel 0: open failed: administratively prohibited: port forwarding is disabled
> stdio forwarding failed
> kex_exchange_identification: Connection closed by remote host
[15:40:35.769] ERROR: TCP port forwarding appears to be disabled on the remote host. Ensure that the sshd_config has `AllowTcpForwarding yes`. Contact your system administrator if needed.
[15:40:35.798] > 过程试图写入的管
[15:40:37.093] "install" terminal command done
[15:40:37.094] Install terminal quit with output: 过程试图写入的管
[15:40:37.094] Received install output: 过程试图写入的管
[15:40:37.096] Failed to parse remote port from server output
[15:40:37.101] Resolver error: Error: 
	at m.Create (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:501230)
	at t.handleInstallOutput (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:498552)
	at t.tryInstall (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:623316)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:582788
	at async t.withShowDetailsEvent (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:586054)
	at async k (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:579675)
	at async t.resolve (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:583465)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:851126
[15:40:37.161] ------

### 期望结果

是否能提供其他可能导致此问题的原因，配置文件时运维配置的，可能会存在其他疏漏嘛

**Comment by BaiJiangJie** [comment]
https://kb.fit2cloud.com/?p=48
```
ENABLE_LOCAL_PORT_FORWARD=true
ENABLE_VSCODE_SUPPORT=true
```

这两个参数都配置上，并重启服务了吗？

**Comment by edentliang** [comment]
是的，另外我发现remote-ssh 有些配置需要更改，例如` Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 58881 "AssetIp" bash`， 是否能提供remote-ssh 的配置作为参考

**Comment by BaiJiangJie** [comment]
如果资产 IP 有重复，AssetIp 改成 AssetID。

**Comment by LeeEirc** [comment]
可以提供下 VSCode 的版本，插件 remote-ssh 的版本，另外都升级到最新版本的测试下？
```[18:08:55.822] Install terminal quit with output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
[18:08:55.822] Received install output: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain```
如果有这样的报错，可能是资产账号密码不是托管方式，连不上资产。

**Comment by edentliang** [comment]
VScode： 1.92.2， remote-ssh: v0.113.1

**Comment by LeeEirc** [comment]
koko 开启 DEBUG 日志，查看下日志

```
LOG_LEVEL=DEBUG
```

**Comment by edentliang** [comment]
> 024-08-30 09:27:40 [ERRO] SSH conn[edd19d2198ab45da51a48daff483477b92893c4315a9e6082057306fb5c0f12b] auth method none failed: ssh: no auth passed yet
2024-08-30 09:27:40 [INFO] SSH conn[edd19d2198ab45da51a48daff483477b92893c4315a9e6082057306fb5c0f12b] authenticating user XXXXXX publickey
2024-08-30 09:27:40 [ERRO] User XXXXXXAuthenticate err: POST http://core:8080/api/v1/authentication/tokens/ failed, get code: 400, {"error":"password_failed","msg":"您输入的用户名或密码不正确，请重新输入。 您还可以尝试 7 次 (账号将被临时 锁定 30 分钟)"}
2024-08-30 09:27:40 [INFO] SSH conn[edd19d2198ab45da51a48daff483477b92893c4315a9e6082057306fb5c0f12b] Failed publickey for XXXXX from XXXXXXX
2024-08-30 09:27:40 [ERRO] SSH conn[edd19d2198ab45da51a48daff483477b92893c4315a9e6082057306fb5c0f12b] auth method publickey failed: permission denied
2024/08/30 09:27:40 Screen不支持解析l
2024/08/30 09:27:40 Screen不支持解析h
2024/08/30 09:27:40 Screen不支持解析l
2024/08/30 09:27:40 Screen不支持解析h
2024/08/30 09:27:40 Screen不支持解析l
2024/08/30 09:27:40 Screen不支持解析h
2024/08/30 09:27:40 Screen不支持解析l
2024/08/30 09:27:40 Screen不支持解析h
[GIN] 2024/08/30 - 09:27:41 | 200 |      67.911µs |             ::1 | GET      "/koko/health/"
2024-08-30 09:27:42 [INFO] SSH conn[edd19d2198ab45da51a48daff483477b92893c4315a9e6082057306fb5c0f12b] authenticating user XXXXXXXX password
2024-08-30 09:27:43 [INFO] SSH conn[edd19d2198ab45da51a48daff483477b92893c4315a9e6082057306fb5c0f12b] Accepted password for XXXXXX from XXXXXXXX
2024-08-30 09:27:43 [ERRO] SSH conn[edd19d2198ab45da51a48daff483477b92893c4315a9e6082057306fb5c0f12b] auth method password success
2024-08-30 09:27:43 [ERRO] Get SSH Client failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

**Comment by LeeEirc** [comment]
这个是托管的账号密码吗？不是托管的账号密码，无法连接到资产。

**Comment by edentliang** [comment]
是的，我用一样的账号密码，用过terminal 使用` ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222`， 能连接，但是用vscode 就不行

**Comment by LeeEirc** [comment]
你具体使用那个版本的JumpServer，能测试下最新的吗？交流群里帮你远程看下环境

**Comment by SpecterHi** [comment]
我的是通过1panel安装的jumpserver 4.6.0，然后这台机器本身还在内网，是通过frp把http和ssh的端口转发至公网。
同样遇到类似的vscode无法打开动态端口转发不能用的情况，一开始还怀疑是因为本来就是转发导致，之后冷静思考本来就是用ssh啊，问题肯定在别处。

排查思路：用各种方式，只要定位到是
`open failed: administratively prohibited: port forwarding is disabled`

就应该可以用类似方法排除。

首先修改.env，增加
```
ENABLE_LOCAL_PORT_FORWARD="true"  
ENABLE_VSCODE_SUPPORT="true"
```
这个处理方式其实也可以在网上搜到，但是重建后问题依旧，查看容器日志发现
`EnableLocalPortForward:false EnableVscodeSupport:false`
信息，说明没有生效。

最后的解决：
在上述基础上，修改
`docker-compose.yml`

在
```
services:
    jumpserver:
        environment:
```
段中，已有的多个变量后添加
```
ENABLE_LOCAL_PORT_FORWARD: ${ENABLE_LOCAL_PORT_FORWARD}
ENABLE_VSCODE_SUPPORT: ${ENABLE_VSCODE_SUPPORT}
```

重建容器实例，搞定！

**Comment by ZYWNB666** [comment]
我来的太晚了，我也遇到这个问题了。
v4.10.13 企业版，使用vscode  token认证方式连接服务器报错，已经将.vscode-server 放到服务器上了。

```txt

[20:35:27.687] Expecting scp to be next to ssh at C:\WINDOWS\System32\OpenSSH\scp.exe
[20:35:27.687] Testing scp with "C:\WINDOWS\System32\OpenSSH\scp.exe"
[20:35:27.750] scp exited with code: 1
[20:35:27.750] Got stderr from scp: usage: scp [-346ABCOpqRrsTv] [-c cipher] [-D sftp_server_path] [-F ssh_config]
           [-i identity_file] [-J destination] [-l limit] [-o ssh_option]
           [-P port] [-S program] [-X sftp_option] source ... target
[20:35:27.750] Copying file to remote with "C:\WINDOWS\System32\OpenSSH\scp.exe" "vscode-cli-994fd12f8d3a5aa16f17d42c041e5809167e845a.tar.gz" "vscode-cli-994fd12f8d3a5aa16f17d42c041e5809167e845a.tar.gz.done" "vssh.*.cn":"/root/.vscode-server"
[20:35:27.751] Using cwd: file:///c%3A/Users/ZYW/AppData/Local/Temp/vscode_server_1766061327617
[20:35:27.751] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[20:35:27.989] > 
[20:35:28.005] > 
[20:35:29.174] > JMS-808d46f8-8f5f-4229-83fe-4058680624e5@vssh.*.cn's password: 
[20:35:29.174] Showing password prompt
[20:35:31.127] Got password response
[20:35:31.127] "Copy server to host" wrote data to terminal: "****************"
[20:35:31.158] > 
[20:35:31.332] > Permission denied, please try again.
[20:35:31.345] > JMS-808d46f8-8f5f-4229-83fe-4058680624e5@vssh.*.cn's password: 
[20:35:31.345] Showing password prompt
[20:35:32.349] Got password response
[20:35:32.349] "Copy server to host" wrote data to terminal: "****************"
[20:35:32.375] > 
[20:35:32.532] > Permission denied, please try again.
[20:35:32.551] > JMS-808d46f8-8f5f-4229-83fe-4058680624e5@vssh.*.cn's password: 
[20:35:32.552] Showing password prompt
[20:35:33.848] Got password response
[20:35:33.848] "Copy server to host" wrote data to terminal: "****************"
[20:35:33.895] > 
[20:35:34.052] > JMS-808d46f8-8f5f-4229-83fe-4058680624e5@vssh.*.cn: Permission denied (
> password,publickey).
> C:\WINDOWS\System32\OpenSSH\scp.exe: Connection closed
[20:35:35.377] "Copy server to host" terminal command done

```


虽然我看到Permission denied了，但是我不理解，目的服务器是root权限，并且我用ssh token认证没问题，可以登录，上面说的变量也加过了，容器内验证变量存在。

实在搞不定了，请教大佬们
