### ISSUE TITLE
Jumpserver访问windows7报安全协议协商失败

### ISSUE THREAD

**Issue by mago960806** [jumpserver/jumpserver#1421]
jumpserver搭建完毕后,访问windows server操作系统的远程桌面服务正常.但是访问windows7,windows10这类系统的远程桌面服务,都会在报连接错误[Error: protocol security negotiation or connection failure]
查了下原因可能是因为windows7之后的rdp会话默认都是SSL加密的,证书是自签导致证书有安全问题.

##### 使用版本

jumpserver 1.3.1
windows7,10(虚拟机)

##### 问题复现步骤

1.开启windows7远程协助功能并设置"允许运行任意版本远程桌面的计算机连接",然后添加当前用户到远程桌面用户列表中.
2.在jumpserver里访问该主机

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/18606660/41273243-4aacf33a-6e4b-11e8-975a-3df2df10a7a4.png)

##### 报错LOG

connected to 118.25.4.169:3389
06:14:35.627 [http-apr-8080-exec-1] INFO  o.a.g.a.j.s.JumpserverSessionService - {code:201,result:{"id":"3fff46a1-b080-479b-b78f-93e2135f0562","command_amount":0,"user":"admin","asset":"windows_server_2008","system_user":"jumpserver","login_from":"ST","remote_addr":"192.168.86.1","is_finished":false,"has_replay":false,"has_command":false,"protocol":"rdp","date_last_active":"2018-06-12 06:14:35 +0000","date_start":"2018-06-12 14:14:35 +0800","date_end":null,"terminal":"656cba2e-f827-4acb-9e9d-3c47e95fe1b0"}}
06:14:35.627 [http-apr-8080-exec-1] INFO  o.a.g.a.j.s.JumpserverSessionService - 注册Session成功
creating directory /root/.config/freerdp
creating directory /root/.config/freerdp/certs
creating directory /root/.config/freerdp/server
certificate_store_open: error opening [/root/.config/freerdp/known_hosts] for writing
**SSL_read: Failure in SSL library (protocol error?)**
**SSL_read: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied**
**credssp_recv() error: -1**
**Authentication failure, check credentials.**
If credentials are valid, the NTLMSSP implementation may be to blame.
**Error: protocol security negotiation or connection failure**
guacd[301]: ERROR:	Error connecting to RDP server
guacd[301]: INFO:	User "@64053635-6608-402d-9718-dde08dfdfae9" disconnected (0 users remain)
guacd[301]: INFO:	Last user of connection "$0772574a-741d-439d-a4e9-1d37eb164d09" disconnected
Exception in thread "Thread-12" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:387)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.startMessage(WsRemoteEndpointImplBase.java:344)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$TextMessageSendHandler.write(WsRemoteEndpointImplBase.java:788)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:252)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:195)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:190)
guacd[217]: INFO:	Connection "$0772574a-741d-439d-a4e9-1d37eb164d09" removed.

**Comment by mago960806** [comment]
可以确定目标主机是能够通过mstsc正常登录的.

**Comment by wojiushixiaobai** [comment]
@mago960806 经过测试没有发现你说的问题（直连，可以提供视频录像），如果是通过rdp网关进行跳转的资产，可能会出现这个问题。

**Comment by allen5460** [comment]
你这个是怎么解决的?，我windows server2016也是报同样的错误

**Comment by mago960806** [comment]
@allen5460 还是有这个问题，没有解决。但是官方那边无法复现，所以也没什么办法。

**Comment by ibuler** [comment]
@allen5460 windows 2016时，选择资产操作系统系统为 windows(2016)
