### ISSUE TITLE
[Bug] jumpserver配置casdoor的 XML 解析问题

### ISSUE THREAD

**Issue by ssrsec** [jumpserver/jumpserver#14360]
### 产品版本

v3x、v4x

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [X] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

社区版v3.10.14和v4.3.0均存在
casdoor：v1.738.0

在后台配置cas，对接casdoor，通过飞书统一登录

### 🐛 缺陷描述

casdoor配置飞书统一登录，获取到的头像，在数据库中体现的url如下：
https://s3-imfile.feishucdn.com/static-resource/v1/v3_008s_6e731fc0-da8c-4482-82b5-7aa26415d8ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp

此时跳转回jumpserver就会报错，但是手动在数据库中去掉头像url中后面的参数后，就正常了，如下：
https://s3-imfile.feishucdn.com/static-resource/v1/v3_008s_6e731fc0-da8c-4482-82b5-7aa26415d8ag

感觉是jumpserver解析的问题

### 复现步骤

1.正常安装jumpserver和casdoor，在casdoor中配置好飞书统一登录，在jumpserver后台配置cas对接casdoor
2.尝试登录，报错如下图：
<img width="736" alt="image" src="https://github.com/user-attachments/assets/b2ff312b-825d-488e-a876-9e174ea26d0a">

3.经过排查，casdoor数据库中获取飞书用户的头像在数据库中体现的url如下：
https://s3-imfile.feishucdn.com/static-resource/v1/v3_008s_6e731fc0-da8c-4482-82b5-7aa26415d8ag~?image_size=72x72&cut_type=&quality=&format=image&sticker_format=.webp

此时跳转回jumpserver就会报错，但是手动在数据库中去掉头像url中后面的参数后，就正常了，如下：
https://s3-imfile.feishucdn.com/static-resource/v1/v3_008s_6e731fc0-da8c-4482-82b5-7aa26415d8ag

感觉是jumpserver解析的问题

### 期望结果

fix

### 尝试过的解决方案

手动进入casdoor数据库，去掉头像url后面的参数，避免jumpserver解析报错

**Comment by ssrsec** [comment]
相关日志：
```
2024-10-24 20:43:42 [ERRO] Internal Server Error: /core/auth/cas/login/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/opt/py3/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/views.py", line 72, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/backends/cas/views.py", line 11, in get
    return super().get(request)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/views.py", line 128, in get
    user = authenticate(ticket=ticket,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/jumpserver/apps/authentication/mixins.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django_cas_ng/backends.py", line 29, in authenticate
    username, attributes, pgtiou = client.verify_ticket(ticket)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/cas.py", line 202, in verify_ticket
    return self.verify_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/cas.py", line 296, in verify_response
    return cls.parse_response_xml(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/cas.py", line 259, in parse_response_xml
    tree = ElementTree.fromstring(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1350, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 612
root@jumpserver:/data/jumpserver/core/data/logs# 
```

**Comment by BaiJiangJie** [comment]
原因是这个。
https://github.com/jumpserver/jumpserver/issues/14044#issuecomment-2342849508

**Comment by ssrsec** [comment]
> 原因是这个。 [#14044 (comment)](https://github.com/jumpserver/jumpserver/issues/14044#issuecomment-2342849508)

我看之前的解决方案是需要手动在casdoor中更新头像来解决，能否在jumpserver层面自动进行转义？

**Comment by BaiJiangJie** [comment]
JumpServer 端无法处理。

**Comment by ssrsec** [comment]
> JumpServer 端无法处理。

应该替换下可能污染xml的字符就可以了。这种一般都是在参数位置，可以放心大胆处理

**Comment by BaiJiangJie** [comment]
解析逻辑都在 sdk 库中，不太好干预，欢迎你贡献 PR。
