### ISSUE TITLE
[Bug] jumpserver4.0.1社区版升级到4.3.0，报错

### ISSUE THREAD

**Issue by xiao-yuluo** [jumpserver/jumpserver#14363]
### Product Version

jumpserver4.0.1社区版升级到4.3.0，报错

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [X] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

jumpserver4.0.1社区版，升级到4.3.0版本，使用的外部数据库mysql，

### 🐛 Bug Description

升级的时候报更改数据库错误，
2024-10-25 10:03:15 Migrate model change to database ...
Operations to perform:
  Apply all migrations: accounts, acls, admin, assets, audits, auth, authentication, captcha, contenttypes, django_cas_ng, django_celery_beat, labels, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying assets.0005_myasset...2024-10-25 10:03:16 Perform migrate failed
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1050, "Table 'assets_myasset' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 203, in <module>
    upgrade_db()
  File "/opt/jumpserver/./jms", line 137, in upgrade_db
    perform_db_migrate()
  File "/opt/jumpserver/./jms", line 92, in perform_db_migrate
    raise e
  File "/opt/jumpserver/./jms", line 89, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 447, in create_model
    self.execute(sql, params or None)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/py3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'assets_myasset' already exists")
[ERROR] Failed to change the table structure!

### Recurrence Steps

![新建 BMP 图像](https://github.com/user-attachments/assets/42f90dc0-5372-46c9-893a-a9189de132e8)

**Comment by BaiJiangJie** [comment]
```
django.db.utils.OperationalError: (1050, "Table 'assets_myasset' already exists")
```
报错前是不是执行过升级操作？


删除 assets_myasset 表，重新升级试试。备份好 v4.0.1 版本的数据库。

**Comment by xiao-yuluo** [comment]
删除了 assets_myasset 表，现在报

5. Apply database changes
Changing database schema may take a while, please wait patiently
[+] Running 2/2
 ✔ Container jms_core   Started                                                                     0.4s
 ✔ Container jms_redis  Running                                                                     0.0s
2024-10-25 15:17:57 Collect static files
2024-10-25 15:17:57 Collect static files done
2024-10-25 15:17:57 Check database structure change ...
2024-10-25 15:17:57 Migrate model change to database ...
Operations to perform:
  Apply all migrations: accounts, acls, admin, assets, audits, auth, authentication, captcha, contenttypes, django_cas_ng, django_celery_beat, labels, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying assets.0005_myasset...2024-10-25 15:17:58 Perform migrate failed
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (3780, "Referencing column 'asset_id' and referenced column 'id' in foreign key constraint 'assets_myasset_asset_id_eff8cabd_fk_assets_asset_id' are incompatible.")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 203, in <module>
    upgrade_db()
  File "/opt/jumpserver/./jms", line 137, in upgrade_db
    perform_db_migrate()
  File "/opt/jumpserver/./jms", line 92, in perform_db_migrate
    raise e
  File "/opt/jumpserver/./jms", line 89, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 249, in apply_migration
    with self.connection.schema_editor(
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 164, in __exit__
    self.execute(sql)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/py3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/opt/py3/lib/python3.11/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (3780, "Referencing column 'asset_id' and referenced column 'id' in foreign key constraint 'assets_myasset_asset_id_eff8cabd_fk_assets_asset_id' are incompatible.")
[ERROR] Failed to change the table structure!

我这个是3.X版本升级到4版本的，数据库不是本地，我可以重新部署jumpserver么，如果重新部署连接数据库会有其他什么问题么

**Comment by BaiJiangJie** [comment]
确认一下，你是从哪个版本升级到哪个版本的？

**Comment by xiao-yuluo** [comment]
在升级之前，我先进入4.0.1版本路径下执行./jmsctl.sh stop ,然后执行在线升级操作，中途有提示是否更改数据库什么的，忘了，我现在是4.0.1版本，我要升级到4.3.0版本
![Uploading 新建 BMP 图像.jpeg…]()

**Comment by BaiJiangJie** [comment]
现在重新恢复一下 v4.0.1 版本的数据库，然后再执行升级操作，恢复的时候注意 collate 和 charset 字符集跟之前一致。

**Comment by xiao-yuluo** [comment]
5. Apply database changes
Changing database schema may take a while, please wait patiently
Detected that the JumpServer container is running. Do you want to close the container and continue to upgrade? (y/n)  (default y):
我恢复到之前的状态，现在升级提示这个  我要选择是还是否

**Comment by BaiJiangJie** [comment]
y

**Comment by BaiJiangJie** [comment]
恢复到之前的 v4.0.1 数据库，查一下 django_migrations 表数据。

**Comment by xiao-yuluo** [comment]
[django_migrations.txt](https://github.com/user-attachments/files/17518244/django_migrations.txt)

**Comment by xiao-yuluo** [comment]
[1025django_migrations.txt](https://github.com/user-attachments/files/17518265/1025django_migrations.txt)
[0803django_migrations.txt](https://github.com/user-attachments/files/17518267/0803django_migrations.txt)

**Comment by BaiJiangJie** [comment]
看着没问题，就用这个库升级不可能报这个错：

```django.db.utils.OperationalError: (1050, "Table 'assets_myasset' already exists")
```

**Comment by xiao-yuluo** [comment]
4.3升级是不是要改变表的内容，我可不可以重新安装4.3 然后关联到数据库中

**Comment by BaiJiangJie** [comment]
重新安装 v4.3，那你 v4.0.1 的数据就没有了。

我猜测，你是不是恢复了数据库之后，没有修改配置文件中的 DB_NAME 值。

**Comment by xiao-yuluo** [comment]
我是直接恢复本数据库的数据，应该不影响吧
![111](https://github.com/user-attachments/assets/9e511a42-5a11-48d4-b6e5-60e7b933fa09)

**Comment by BaiJiangJie** [comment]
不行，重新创建一个全新的数据库，再导入数据和表结构。

**Comment by xiao-yuluo** [comment]
那我试试
