### ISSUE TITLE
jumpserver更新升级问题

### ISSUE THREAD

**Issue by yuanguoping** [jumpserver/jumpserver#1442]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.3.1]

##### 问题复现步骤
jumpserver更新升级 1.3.1到 1.3.2
执行sh make_migrations.sh报错：
Operations to perform:
  Apply all migrations: assets, audits, auth, captcha, common, contenttypes, django_celery_beat, ops, perms, sessions, terminal, users
Running migrations:
  Applying assets.0002_auto_20180615_1244...Traceback (most recent call last):
  File "/data/py3_jumpserver/lib/python3.6/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
  File "/data/py3_jumpserver/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/data/py3_jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/data/py3_jumpserver/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/data/py3_jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/data/py3_jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/data/py3_jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/data/py3_jumpserver/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1050, "Table 'assets_domain' already exists")

**Comment by wojiushixiaobai** [comment]
如果有备份请还原后重新升级，也可以参考FAQ文档的13条处理
(13). 升级提示 Table 'xxx' already exists（可用以下命令检查，如果显示内容不一致则无法升级）
    \# cd /opt/jumpserver/apps
    \# python manage.py makemigrations
    \# python manage.py migrate --fake
    \# find . | grep migrations | grep apps | grep -v 'pyc' | grep -v '__init__'
    \# 把这里的内容和下面数据库查询的内容对比

    \# mysql -uroot
    \> use jumpserver;
    \> select * from django_migrations;
    \# 如果对比结果不一样则无法升级
    \> quit;

**Comment by ibuler** [comment]
切记 migrations不能丢失，不能更改，否则升级会出现这个问题
