### ISSUE TITLE
[Question] 使用 vscode 连接资产服务器失败

### ISSUE THREAD

**Issue by steven22tom** [jumpserver/jumpserver#14572]
### 产品版本

v4.4.1

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [X] 离线包安装
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

ubuntu-22.04.5 server
有互联网

### 🤔 问题描述

config.txt中添加了配置，但使用vscode 连接资产服务器失败。
资产服务器账号密码托管在平台上，JumpServer登录日志中显示JumpServer用户登录成功。但无法与资产服务器建立连接，并报错
[17:17:34.170] > Welcome to JumpServer SSH Server
[17:17:34.187] > admin@root@10.168.1.5@202.115.11.78's password: 
[17:17:34.187] Showing password prompt
[17:17:39.735] Got password response
[17:17:39.735] "install" wrote data to terminal: "*********"
[17:17:39.751] > 
[17:17:40.240] > match asset failed: No found asset
[17:17:41.507] "install" terminal command done
[17:17:41.507] Install terminal quit with output: match asset failed: No found asset
[17:17:41.507] Received install output: match asset failed: No found asset
[17:17:41.507] Failed to parse remote port from server output
[17:17:41.509] Resolver error: Error: 
	at v.Create (c:\Users\btcz7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:493431)
	at t.handleInstallOutput (c:\Users\btcz7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:490753)
	at t.tryInstall (c:\Users\btcz7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:608797)
	at async c:\Users\btcz7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:568008
	at async t.withShowDetailsEvent (c:\Users\btcz7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:571256)
	at async P (c:\Users\btcz7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:564794)
	at async t.resolve (c:\Users\btcz7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:568667)
	at async c:\Users\btcz7\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:839059
[17:17:41.513] ------

### 期望结果

问题解决，可连接

**Comment by inlmouse** [comment]
Same problem!

**Comment by steven22tom** [comment]
Resolved
