### ISSUE TITLE
[Bug] All-in-One 升级显示数据库连接失败（v4.0.2升级v4.2.0报错）

### ISSUE THREAD

**Issue by 37491** [jumpserver/jumpserver#14652]
### 产品版本

v4

### 版本类型

- [X] 社区版
- [ ] 企业版
- [ ] 企业试用版

### 安装方式

- [ ] 在线安装 (一键命令安装)
- [ ] 离线包安装
- [X] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] 源码安装

### 环境信息

docker: jumpserver/jms_all
docker: mariadb  10.8

### 🐛 缺陷描述

直接从v3.10.12升级v4.4.1也是类似的报错, 尝试逐步升级

1. 升级v3到v4.0.2成功 (升级后系统是正常可用的)
2. 从v4.0.2升级到v4.2.0报错如下
```
$ docker run --name jms --network jms --ip 10.1.0.2 -p 80:80 -p 2222:2222 \
-e SECRET_KEY=xxx \
-e BOOTSTRAP_TOKEN=xxx \
-v /opt/jumpserver/data:/opt/jumpserver/data \
  -v /opt/jumpserver/koko/data:/opt/koko/data \
  -v /opt/jumpserver/lion/data:/opt/lion/data \
  -v /opt/jumpserver/kael/data:/opt/kael/data \
  -v /opt/jumpserver/chen/data:/opt/chen/data \
    --privileged=true \
-v /opt/jumpserver/nginx/logs:/var/log/nginx/ \
-e DB_HOST="10.1.0.100" -e DB_PORT=3306 -e DB_USER=jumpserver -e DB_PASSWORD=xxx -e DB_NAME=jumpserver \
-e REDIS_HOST=10.1.0.101 -e REDIS_PORT=6379 -e REDIS_PASSWORD=xxx -e DOMAINS=172.16.2.77 jumpserver/jms_all:v4.2.0

rm: cannot remove '/opt/jumpserver/data': Device or resource busy
rm: cannot remove '/opt/koko/data': Device or resource busy
rm: cannot remove '/opt/lion/data': Device or resource busy
rm: cannot remove '/opt/chen/data': Device or resource busy
rm: cannot remove '/var/log/nginx': Device or resource busy
>> Init database
External database skip start, 10.1.0.100
>> Init nginx
External redis server skip start, 10.1.0.101
Starting periodic command scheduler: cron.
>> Update database structure
2024-12-12 16:12:08 [INFO] Start subscribe for stop job execution
2024-12-12 16:12:08 [INFO] Check oracle ports (MAGNUS_ORACLE_PORTS)
2024-12-12 16:12:08 [WARN] (Ignore) connection to server at "10.1.0.100", port 3306 failed: received invalid response to SSL negotiation: o

2024-12-12 16:12:08 Collect static files
2024-12-12 16:12:08 Collect static files done
2024-12-12 16:12:08 Check database structure change ...
2024-12-12 16:12:08 Migrate model change to database ...
2024-12-12 16:12:08 Perform migrate failed
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/opt/py3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "10.1.0.100", port 3306 failed: received invalid response to SSL negotiation: o


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 203, in <module>
    upgrade_db()
  File "/opt/jumpserver/./jms", line 137, in upgrade_db
    perform_db_migrate()
  File "/opt/jumpserver/./jms", line 92, in perform_db_migrate
    raise e
  File "/opt/jumpserver/./jms", line 89, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 114, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
       ^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/opt/py3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "/opt/py3/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/opt/py3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: connection to server at "10.1.0.100", port 3306 failed: received invalid response to SSL negotiation: o

 Failed to change the table structure. 
```
谢谢.

### 复现步骤

db: mariadb 10.8
1) docker: jumpserver/jms_all 升级路径: v3.10.12->v4.0.2->v4.2.0
2)  docker: jumpserver/jms_all 升级路径: v3.10.12->v4.4.1

### 补充信息

提示`received invalid response to SSL negotiation` ,但是没有配置过db ssl. 参数也没有指定.

### 尝试过的解决方案

逐个小版本升级

**Comment by BaiJiangJie** [comment]
启动命令再加一个参数：`-e DB_ENGINE=mysql`
