### ISSUE TITLE
[ERROR] Failed to change the table structure!

### ISSUE THREAD

**Issue by viniciusgruske** [jumpserver/jumpserver#14702]
### Product Version

4.5.0

### Product Edition

- [X] Community Edition
- [ ] Enterprise Edition
- [ ] Enterprise Trial Edition

### Installation Method

- [ ] Online Installation (One-click command installation)
- [ ] Offline Package Installation
- [ ] All-in-One
- [ ] 1Panel
- [ ] Kubernetes
- [ ] Source Code

### Environment Information

- External PostgreSQL
- Internal Redis
- Internal NGINX with SSL
- IPv6 enable

### 🐛 Bug Description

Run the `jms_ctl.sh upgrade` command returns the error `[ERROR] Failed to change the table structure!`

### Recurrence Steps

```
# cd /opt
# wget https://github.com/jumpserver/installer/releases/download/v4.5.0/jumpserver-installer-v4.5.0.tar.gz
# tar -zxf jumpserver-installer-v4.5.0.tar.gz
# jumpserver-installer-v4.5.0/jmsctl.sh upgrade
```

### Expected Behavior

Sucessfull update for the 4.5.0 version

### Additional Information

```
jumpserver:/opt# jumpserver-installer-v4.5.0/jmsctl.sh upgrade
Are you sure you want to update the current version to dev ? (y/n)  (default y):

1. Check Configuration File
Path to Configuration file: /opt/jumpserver/config
/opt/jumpserver/config/config.txt        [ √ ]
/opt/jumpserver/config/loki/loki.yaml    [ √ ]
/opt/jumpserver/config/loki/promtail.yml         [ √ ]
/opt/jumpserver/config/mariadb/mariadb.cnf       [ √ ]
/opt/jumpserver/config/mysql/my.cnf      [ √ ]
/opt/jumpserver/config/nginx/lb_http_server.conf         [ √ ]
/opt/jumpserver/config/redis/redis.conf          [ √ ]
/opt/jumpserver/config/nginx/cert/server.crt     [ √ ]
/opt/jumpserver/config/nginx/cert/server.key     [ √ ]

complete

2. Loading Docker Image
[jumpserver/lion:dev] exist, pass
[redis:7.0-bullseye] exist, pass
[postgres:16.3-bullseye] exist, pass
[jumpserver/web:dev] exist, pass
[jumpserver/koko:dev] exist, pass
[jumpserver/chen:dev] exist, pass
[jumpserver/core:dev] exist, pass
complete

3. Backup database
Backing up...
[SUCCESS] Backup succeeded! The backup file has been saved to: /data/jumpserver/db_backup/jumpserver-v4.4.1-ce-2024-12-19_10:19:55.dump

4. Backup Configuration File
Back up to /data/jumpserver/db_backup/config-v4.4.1-ce-2024-12-19_10:19:56.conf

5. Apply database changes
Changing database schema may take a while, please wait patiently
Detected that the JumpServer container is running. Do you want to close the container and continue to upgrade? (y/n)  (default y):

[+] Running 3/3
 ✔ Container jms_redis  Removed                                                                                                                                                                                     0.4s
 ✔ Container jms_core   Removed                                                                                                                                                                                     0.4s
 ✔ Network jms_net      Removed                                                                                                                                                                                     0.4s

[+] Running 3/3
 ✔ Network jms_net      Created                                                                                                                                                                                     0.1s
 ✔ Container jms_core   Started                                                                                                                                                                                     0.6s
 ✔ Container jms_redis  Started                                                                                                                                                                                     0.6s
ALLOWED_HOSTS:
  - localhost
  - jump.wsinternet.com.br
  - core:8080
  - 127.0.0.1
  - 127.0.0.1:8080
  - 127.0.0.1:80
  - localhost:8080
  - localhost:80
  - core:8080
  - core:80
Traceback (most recent call last):
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 24, in <module>
    import psycopg2 as Database
  File "/opt/py3/lib/python3.11/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq.so.5: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jumpserver/./jms", line 21, in <module>
    django.setup()
  File "/opt/py3/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/py3/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/jumpserver/apps/orgs/models.py", line 5, in <module>
    from common.db.models import JMSBaseModel
  File "/opt/jumpserver/apps/common/db/models.py", line 31, in <module>
    class BaseCreateUpdateModel(models.Model):
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/base.py", line 141, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/base.py", line 369, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/py3/lib/python3.11/site-packages/django/db/models/options.py", line 231, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
                   ^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/py3/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 28, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: libpq.so.5: cannot open shared object file: No such file or directory
[ERROR] Failed to change the table structure!
```

**Comment by BaiJiangJie** [comment]
Before the upgrade, were you using MySQL or PostgreSQL as the database?

**Comment by viniciusgruske** [comment]
1. PostgreSQL
2. External
3. Community Edition v4.4.1

**Comment by ibuler** [comment]
Pelease check version first, if not pelease change manually
```
# cat static.env
export VERSION=v4.5.0-ce
```

**Comment by BaiJiangJie** [comment]
```
# cd /opt
# wget https://github.com/jumpserver/installer/releases/download/v4.5.0/jumpserver-installer-v4.5.0.tar.gz
# tar -zxf jumpserver-installer-v4.5.0.tar.gz
# jumpserver-installer-v4.5.0/jmsctl.sh upgrade
```

Please run the upgrade command again, and it will succeed as the installation package has been updated.

**Comment by viniciusgruske** [comment]
The version in static.env was correct.

```
# cat static.env
export VERSION=v4.5.0-ce
```

I re-did the steps to update, and this time everything worked out fine.

Thank you.

PS.: The translation to pt_BR seems to be very good, congratulations.
