### ISSUE TITLE
关于coco卡死的问题

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1482]
VERSION：1.3.2
目前遇到的会导致COCO卡死的情况有以下几种: 

1.tailf 日志时，按ctrl+c会卡死
2.空闲状态超过一定时间会卡死
3.连接资产超时时会卡死
4.执行脚本，有用户交互的情况

PS：设计上，任何情况下都不应该卡死，非常影响用户体验。
下面是第一种情况下的日志：
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/seven/workspace/jumpserver/coco/coco/sshd.py", line 104, in handle_chan
    self.dispatch(client)
  File "/home/seven/workspace/jumpserver/coco/coco/sshd.py", line 111, in dispatch
    InteractiveServer(client).interact()
  File "/home/seven/workspace/jumpserver/coco/coco/interactive.py", line 271, in interact
    rv = self.dispatch(opt)
  File "/home/seven/workspace/jumpserver/coco/coco/interactive.py", line 86, in dispatch
    self.search_and_proxy(opt)
  File "/home/seven/workspace/jumpserver/coco/coco/interactive.py", line 254, in search_and_proxy
    self.proxy(asset)
  File "/home/seven/workspace/jumpserver/coco/coco/interactive.py", line 264, in proxy
    forwarder.proxy(asset, system_user)
  File "/home/seven/workspace/jumpserver/coco/coco/proxy.py", line 58, in proxy
    session.bridge()
  File "/home/seven/workspace/jumpserver/coco/coco/session.py", line 148, in bridge
    self.server.send(data)
  File "/home/seven/workspace/jumpserver/coco/coco/models.py", line 153, in send
    self.parse(b)
  File "/home/seven/workspace/jumpserver/coco/coco/models.py", line 140, in parse
    self._output = self._parse_output()
  File "/home/seven/workspace/jumpserver/coco/coco/models.py", line 186, in _parse_output
    return parser.parse_output(self.output_data)
  File "/home/seven/workspace/jumpserver/coco/coco/utils.py", line 115, in parse_output
    self.stream.feed(d)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/pyte/streams.py", line 378, in feed
    return super(ByteStream, self).feed(chars)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/pyte/streams.py", line 166, in feed
    send(char)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/pyte/streams.py", line 318, in _parser_fsm
    dispatch("draw", char)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/pyte/streams.py", line 215, in dispatch
    handler(*args, **kwargs)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/pyte/screens.py", line 448, in draw
    line[self.cursor.x + 1] = self.cursor.attrs._replace(data=" ")
IndexError: list assignment index out of range

```

**Comment by wojiushixiaobai** [comment]
第一个问题，请说明下环境及文件的大小，我这边自己测试了一下，tail -f xxx.log  可以正常ctrl + c
第二个问题，一般是由于网络造成的（这方面可能需要等项目继续优化）
第三个问题能否提供下详细的截图。我这边测试都是超时后提示timed out然后可以重新选择资产
第四个问题，我这边测试后发现可以正常交互和退出

**Comment by gengkeye** [comment]
@wojiushixiaobai 感谢回复。
第一个问题，已解决。
第二个问题，是由于ssh连接空闲超时造成，现在空闲时间改成半个小时好像也没问题了。
第三个问题，仍然存在。
```
Opt> X.X.X.X

选择一个登录: 
0 运维
ID> 0

Connecting to maintenanceuser@X.X.X.X 9.9
```
第四个问题，是有的同事向我反应的，下次遇到会截图出来。

**Comment by wojiushixiaobai** [comment]
@gengkeye 老哥，你的coco版本是啥，我记得1.3.2版本超时后会直接显示timed out，而不会继续卡在那，有没有coco的报错log

**Comment by ibuler** [comment]
最后截图那个异常是由于一个库导致的，升级后就没问题了

**Comment by danieldai** [comment]
@gengkeye 请问怎么修改空闲时间？

**Comment by Helloyanxuan** [comment]
> @wojiushixiaobai 感谢回复。
> 第一个问题，已解决。
> 第二个问题，是由于ssh连接空闲超时造成，现在空闲时间改成半个小时好像也没问题了。
> 第三个问题，仍然存在。超时的原因可能是防火墙挡住了或端口根本就不通等。
> 
> ```
> Opt> X.X.X.X
> 
> 选择一个登录: 
> 0 运维
> 1 管理员
> ID> 0
> 
> Connecting to om_user@X.X.X.X 9.9
> ```
> 第四个问题，是有的同事向我反应的，下次遇到会截图出来。

第二个问题修改超时时间是掩盖了问题，我们公司场景下超时时间太短了DB会骂，改长了没到时间就卡死了，日志报错[transport ERROR] Socket exception: Connection timed out (110)，尴尬得很
