### ISSUE TITLE
按照一步步安装(ubuntu) coco不能启动。

### ISSUE THREAD

**Issue by jdkcn** [jumpserver/jumpserver#1485]
[简述你的问题]
按照一步步安装(ubuntu) coco不能启动。

```bash
(py3) docker@jumpserver:/opt/coco$ ./cocod start
Traceback (most recent call last):
  File "./cocod", line 11, in <module>
    from coco import Coco
  File "/opt/coco/coco/__init__.py", line 5, in <module>
    from .app import Coco
  File "/opt/coco/coco/app.py", line 15, in <module>
    from jms.service import AppService
ModuleNotFoundError: No module named 'jms'
```
##### 使用版本
coco 版本 a518b9a799ee9e4dfd6ef2ca277dbcac93b35824
jumpserver 版本 e7a731fae9f6f27e96045ea34d93999c3b1b6641

##### 问题复现步骤
1. 按照手册操作到coco步骤不能启动。

##### 其他

[注:] 完成后请关闭 issue

**Comment by jokimina** [comment]
包没装诶  pip install -r requirements.txt  

你这个是少了jumpserver-python-sdk

**Comment by jdkcn** [comment]
感谢。
