### ISSUE TITLE
退出服务器之后，卡死在logout页面

### ISSUE THREAD

**Issue by qiqizjl** [jumpserver/jumpserver#1518]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.3.2-2
##### 问题复现步骤
1;通过跳板机登录服务器
2:服务器中执行exit
3:卡死在logout

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/7540584/42517301-f78f988a-8491-11e8-8825-4bae3ce511bd.png)

##### 其他
开启了LDAP
强制二步验证

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
是否可以把  coco的日志发出来

**Comment by qiqizjl** [comment]
~~~
Jul 16 11:37:49 dev-op-1 python[7930]: 2018-07-16 11:37:49 [recorder WARNING] Failed push replay file 5047bd01-8a13-4bb6-955e-d602c21813db: maximum recursion depth exceeded, try again 3
Jul 16 11:37:49 dev-op-1 python[7930]: 2018-07-16 11:37:49 [recorder WARNING] Failed push replay file 5047bd01-8a13-4bb6-955e-d602c21813db: maximum recursion depth exceeded while calling a Python object, try again 2
Jul 16 11:37:49 dev-op-1 python[7930]: 2018-07-16 11:37:49 [recorder WARNING] Failed push replay file 5047bd01-8a13-4bb6-955e-d602c21813db: maximum recursion depth exceeded while calling a Python object, try again 1
Jul 16 11:37:52 dev-op-1 python[7930]: Exception in thread Thread-80915:
Jul 16 11:37:52 dev-op-1 python[7930]: Traceback (most recent call last):
Jul 16 11:37:52 dev-op-1 python[7930]: File "/root/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Jul 16 11:37:52 dev-op-1 python[7930]: self.run()
Jul 16 11:37:52 dev-op-1 python[7930]: File "/root/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864, in run
Jul 16 11:37:52 dev-op-1 python[7930]: self._target(*self._args, **self._kwargs)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/sshd.py", line 104, in handle_chan
Jul 16 11:37:52 dev-op-1 python[7930]: self.dispatch(client)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/sshd.py", line 111, in dispatch
Jul 16 11:37:52 dev-op-1 python[7930]: InteractiveServer(client).interact()
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/interactive.py", line 271, in interact
Jul 16 11:37:52 dev-op-1 python[7930]: rv = self.dispatch(opt)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/interactive.py", line 86, in dispatch
Jul 16 11:37:52 dev-op-1 python[7930]: self.search_and_proxy(opt)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/interactive.py", line 254, in search_and_proxy
Jul 16 11:37:52 dev-op-1 python[7930]: self.proxy(asset)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/interactive.py", line 264, in proxy
Jul 16 11:37:52 dev-op-1 python[7930]: forwarder.proxy(asset, system_user)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/proxy.py", line 58, in proxy
Jul 16 11:37:52 dev-op-1 python[7930]: session.bridge()
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/session.py", line 134, in bridge
Jul 16 11:37:52 dev-op-1 python[7930]: self.close()
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/session.py", line 167, in close
Jul 16 11:37:52 dev-op-1 python[7930]: self.post_bridge()
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/session.py", line 105, in post_bridge
Jul 16 11:37:52 dev-op-1 python[7930]: self._replay_recorder.session_end(self.id)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/recorder.py", line 58, in session_end
Jul 16 11:37:52 dev-op-1 python[7930]: self.upload_replay(session_id)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/recorder.py", line 79, in upload_replay
Jul 16 11:37:52 dev-op-1 python[7930]: self.upload_replay(session_id, times-1)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/recorder.py", line 79, in upload_replay
Jul 16 11:37:52 dev-op-1 python[7930]: self.upload_replay(session_id, times-1)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/recorder.py", line 79, in upload_replay
Jul 16 11:37:52 dev-op-1 python[7930]: self.upload_replay(session_id, times-1)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/opt/coco/coco/recorder.py", line 70, in upload_replay
Jul 16 11:37:52 dev-op-1 python[7930]: self.storage = jms_storage.JMSReplayStorage(app_service)
Jul 16 11:37:52 dev-op-1 python[7930]: File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/jms_storage/jms.py", line 9, in __init__
Jul 16 11:37:52 dev-op-1 python[7930]: self.client = config.get("SERVICE")
Jul 16 11:37:52 dev-op-1 python[7930]: File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
Jul 16 11:37:52 dev-op-1 python[7930]: return getattr(self._get_current_object(), name)
Jul 16 11:37:52 dev-op-1 python[7930]: AttributeError: 'AppService' object has no attribute 'get'
Jul 16 11:37:52 dev-op-1 python[7930]: 2018-07-16 11:37:52 [app INFO] Remove session: 5047bd01-8a13-4bb6-955e-d602c21813db
~~~

**Comment by qiqizjl** [comment]
~~~
Jul 16 11:37:52 dev-op-1 python[7930]: AttributeError: 'AppService' object has no attribute 'get'
Jul 16 11:37:52 dev-op-1 python[7930]: 2018-07-16 11:37:52 [app INFO] Remove session: 5047bd01-8a13-4bb6-955e-d602c21813db
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [sshd INFO] Get ssh request from 100.116.246.3: 28720
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport DEBUG] starting thread (server mode): 0x8e2b6898
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport DEBUG] Local version/idstring: SSH-2.0-paramiko_2.4.0
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR] Exception: Error reading SSH protocol banner
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR] Traceback (most recent call last):
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/transport.py", line 2003, in _check_banner
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]     buf = self.packetizer.readline(timeout)
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]     buf += self._read_timeout(timeout)
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/packet.py", line 542, in _read_timeout
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]     raise EOFError()
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR] EOFError
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR] During handling of the above exception, another exception occurred:
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR] Traceback (most recent call last):
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/transport.py", line 1856, in run
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]     self._check_banner()
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/transport.py", line 2008, in _check_banner
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]     'Error reading SSH protocol banner' + str(e)
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR] paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [transport ERROR]
Jul 16 11:38:19 dev-op-1 python[7930]: 2018-07-16 11:38:19 [sshd WARNING] SSH negotiation failed
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [sshd INFO] Get ssh request from 100.97.192.1: 30256
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport DEBUG] starting thread (server mode): 0x8e74ba20
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport DEBUG] Local version/idstring: SSH-2.0-paramiko_2.4.0
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR] Exception: Error reading SSH protocol banner
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR] Traceback (most recent call last):
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/transport.py", line 2003, in _check_banner
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]     buf = self.packetizer.readline(timeout)
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]     buf += self._read_timeout(timeout)
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/packet.py", line 542, in _read_timeout
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]     raise EOFError()
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR] EOFError
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR] During handling of the above exception, another exception occurred:
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR] Traceback (most recent call last):
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/transport.py", line 1856, in run
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]     self._check_banner()
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]   File "/root/.pyenv/versions/coco/lib/python3.6/site-packages/paramiko/transport.py", line 2008, in _check_banner
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]     'Error reading SSH protocol banner' + str(e)
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR] paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [transport ERROR]
Jul 16 11:38:26 dev-op-1 python[7930]: 2018-07-16 11:38:26 [sshd WARNING] SSH negotiation failed
Jul 16 11:38:28 dev-op-1 python[7930]: 2018-07-16 11:38:28 [channel DEBUG] [chan 0] Unhandled channel request "keepalive@openssh.com"
Jul 16 11:38:28 dev-op-1 python[7930]: 2018-07-16 11:38:28 [channel DEBUG] [chan 0] Unhandled channel request "keepalive@openssh.com"
~~~

**Comment by qiqizjl** [comment]
后面一个应该是SLB的检测。。

**Comment by qiqizjl** [comment]
OSS配置的问题。。改了key就好了。。这个如果上传OSS失败 不应该回落到默认么。。不应该卡着呀

**Comment by rhinoceros** [comment]
> 后面一个应该是SLB的检测。。

如果是SLB的话， 怎么避免？我也遇到这个问题了。
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

**Comment by qiqizjl** [comment]
> > 后面一个应该是SLB的检测。。
> 
> 如果是SLB的话， 怎么避免？我也遇到这个问题了。
> paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

卡顿和SLB无关。我们在SLB里把检测port改成80了。检测nginx服务是否正常。。。。
