### ISSUE TITLE
【重要】1.3.3 录像设置为存储在亚马逊时coco报错

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#1548]
错误信息如下：
```
Start coco process
2018-07-18 14:35:46 [service DEBUG] Initial app service
2018-07-18 14:35:46 [service DEBUG] Load access key
2018-07-18 14:35:46 [service DEBUG] Set app service auth: dd975096-5015-42f3-a442-0d167ecf6b96
2018-07-18 14:35:46 [service DEBUG] Service http auth: <jms.auth.AccessKeyAuth object at 0x7fc3dddae518>
2018-07-18 14:35:46 [app DEBUG] Loading config from server: {"ASSET_LIST_SORT_BY": "hostname", "COMMAND_STORAGE": {"TYPE": "server"}, "HEARTBEAT_INTERVAL": 5, "PASSWORD_AUTH": false, "PUBLIC_KEY_AUTH": true, "REPLAY_STORAGE": {"TYPE": "s3", "BUCKET": "jumpserver", "ACCESS_KEY": "XXXXXXXXXXXXXXXX", "SECRET_KEY": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "REGION": "ap-northeast-7"}}
Wed Jul 18 14:35:46 2018
Coco version 1.3.3, more see https://www.jumpserver.org
Quit the server with CONTROL-C.
Starting ssh server at 0.0.0.0:2222
Starting websocket server at 0.0.0.0:5000
2018-07-18 14:35:47 [recorder WARNING] Failed push replay file 7797d351-c682-479f-ba48-5cf0ba08b49c: maximum recursion depth exceeded while calling a Python object, try again 1
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/seven/workspace/jumpserver/coco/coco/app.py", line 184, in func
    ok = recorder.upload_replay(session_id, 1)
  File "/home/seven/workspace/jumpserver/coco/coco/recorder.py", line 79, in upload_replay
    self.upload_replay(session_id, times-1)
  File "/home/seven/workspace/jumpserver/coco/coco/recorder.py", line 70, in upload_replay
    self.storage = jms_storage.JMSReplayStorage(app_service)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/jms_storage/jms.py", line 9, in __init__
    self.client = config.get("SERVICE")
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AppService' object has no attribute 'get'
```
存储到阿里云时，启动coco不报错，但是当在终端里输入exit时，报错，且终端卡死。错误信息：
```
2018-07-18 15:05:21 [transport DEBUG] Kex agreed: ecdh-sha2-nistp256
2018-07-18 15:05:21 [transport DEBUG] HostKey agreed: ssh-ed25519
2018-07-18 15:05:21 [transport DEBUG] Cipher agreed: aes128-ctr
2018-07-18 15:05:21 [transport DEBUG] MAC agreed: hmac-sha2-256
2018-07-18 15:05:21 [transport DEBUG] Compression agreed: zlib@openssh.com
2018-07-18 15:05:21 [transport DEBUG] kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2018-07-18 15:05:21 [transport DEBUG] Switch to new keys ...
2018-07-18 15:05:21 [transport DEBUG] Adding ssh-ed25519 host key for [18.179.72.143]:6263: b'be220defb5851c75059ff03d533dd291'
2018-07-18 15:05:21 [transport DEBUG] Trying SSH key b'ca8365c83e0d629efe32d344abe500b7'
2018-07-18 15:05:21 [transport DEBUG] userauth is OK
2018-07-18 15:05:21 [transport INFO] Authentication (publickey) successful!
2018-07-18 15:05:21 [transport DEBUG] Switching on outbound compression ...
2018-07-18 15:05:21 [transport DEBUG] Switching on inbound compression ...
2018-07-18 15:05:21 [channel DEBUG] [chan 0] Max packet in: 32768 bytes
2018-07-18 15:05:21 [transport DEBUG] Received global request "hostkeys-00@openssh.com"
2018-07-18 15:05:21 [transport DEBUG] Rejecting "hostkeys-00@openssh.com" global request from server.
2018-07-18 15:05:21 [channel DEBUG] [chan 0] Max packet out: 32768 bytes
2018-07-18 15:05:21 [transport DEBUG] Secsh channel 0 opened.
2018-07-18 15:05:21 [channel DEBUG] [chan 0] Sesch channel 0 request ok
2018-07-18 15:05:21 [channel DEBUG] [chan 0] Sesch channel 0 request ok
2018-07-18 15:05:22 [session INFO] Start bridge session: 5e0a75cd-b8be-4ccd-8135-c0f89c994337
Session start: 5e0a75cd-b8be-4ccd-8135-c0f89c994337
2018-07-18 15:05:24 [models DEBUG] 
############################## Command ##############################
Input: None
Output: [maintenanceuser@ip-172-31-5-202 ~]$
############################## End ##############################
2018-07-18 15:05:28 [models DEBUG] 
############################## Command ##############################
Input: hello ann
Output: -bash: hello: command not found
############################## End ##############################
2018-07-18 15:05:32 [models DEBUG] 
############################## Command ##############################
Input: I love you ann
Output: -bash: I: command not found
############################## End ##############################
2018-07-18 15:05:33 [channel DEBUG] [chan 0] EOF received (0)
2018-07-18 15:05:33 [channel DEBUG] [chan 0] EOF sent (0)
2018-07-18 15:05:33 [session INFO] Server close the connection
2018-07-18 15:05:33 [session INFO] Close the session: 5e0a75cd-b8be-4ccd-8135-c0f89c994337 
2018-07-18 15:05:33 [recorder WARNING] Failed push replay file 5e0a75cd-b8be-4ccd-8135-c0f89c994337: {'status': 403, 'request-id': '5B4EE6BD3723C98CA855EA61', 'details': {'Code': 'AccessDenied', 'Message': 'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.', 'RequestId': '5B4EE6BD3723C98CA855EA61', 'HostId': 'jumpserver.oss-ap-southeast-1.aliyuncs.com', 'Bucket': 'jumpserver', 'Endpoint': 'oss-cn-hangzhou.aliyuncs.com'}}, try again 3
2018-07-18 15:05:33 [recorder WARNING] Failed push replay file 5e0a75cd-b8be-4ccd-8135-c0f89c994337: {'status': 403, 'request-id': '5B4EE6BD3723C98CA855EA83', 'details': {'Code': 'AccessDenied', 'Message': 'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.', 'RequestId': '5B4EE6BD3723C98CA855EA83', 'HostId': 'jumpserver.oss-ap-southeast-1.aliyuncs.com', 'Bucket': 'jumpserver', 'Endpoint': 'oss-cn-hangzhou.aliyuncs.com'}}, try again 2
2018-07-18 15:05:33 [recorder WARNING] Failed push replay file 5e0a75cd-b8be-4ccd-8135-c0f89c994337: {'status': 403, 'request-id': '5B4EE6BD3723C98CA855EA8A', 'details': {'Code': 'AccessDenied', 'Message': 'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.', 'RequestId': '5B4EE6BD3723C98CA855EA8A', 'HostId': 'jumpserver.oss-ap-southeast-1.aliyuncs.com', 'Bucket': 'jumpserver', 'Endpoint': 'oss-cn-hangzhou.aliyuncs.com'}}, try again 1
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/seven/workspace/jumpserver/coco/coco/sshd.py", line 104, in handle_chan
    self.dispatch(client)
  File "/home/seven/workspace/jumpserver/coco/coco/sshd.py", line 111, in dispatch
    InteractiveServer(client).interact()
  File "/home/seven/workspace/jumpserver/coco/coco/interactive.py", line 271, in interact
    rv = self.dispatch(opt)
  File "/home/seven/workspace/jumpserver/coco/coco/interactive.py", line 86, in dispatch
    self.search_and_proxy(opt)
  File "/home/seven/workspace/jumpserver/coco/coco/interactive.py", line 254, in search_and_proxy
    self.proxy(asset)
  File "/home/seven/workspace/jumpserver/coco/coco/interactive.py", line 264, in proxy
    forwarder.proxy(asset, system_user)
  File "/home/seven/workspace/jumpserver/coco/coco/proxy.py", line 73, in proxy
    session.bridge()
  File "/home/seven/workspace/jumpserver/coco/coco/session.py", line 135, in bridge
    self.close()
  File "/home/seven/workspace/jumpserver/coco/coco/session.py", line 168, in close
    self.post_bridge()
  File "/home/seven/workspace/jumpserver/coco/coco/session.py", line 106, in post_bridge
    self._replay_recorder.session_end(self.id)
  File "/home/seven/workspace/jumpserver/coco/coco/recorder.py", line 58, in session_end
    self.upload_replay(session_id)
  File "/home/seven/workspace/jumpserver/coco/coco/recorder.py", line 79, in upload_replay
    self.upload_replay(session_id, times-1)
  File "/home/seven/workspace/jumpserver/coco/coco/recorder.py", line 79, in upload_replay
    self.upload_replay(session_id, times-1)
  File "/home/seven/workspace/jumpserver/coco/coco/recorder.py", line 79, in upload_replay
    self.upload_replay(session_id, times-1)
  File "/home/seven/workspace/jumpserver/coco/coco/recorder.py", line 70, in upload_replay
    self.storage = jms_storage.JMSReplayStorage(app_service)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/jms_storage/jms.py", line 9, in __init__
    self.client = config.get("SERVICE")
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AppService' object has no attribute 'get'

2018-07-18 15:05:36 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:05:37 [app INFO] Remove session: 5e0a75cd-b8be-4ccd-8135-c0f89c994337
2018-07-18 15:05:37 [recorder DEBUG] Send 2 commands to server
2018-07-18 15:05:39 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:05:42 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:05:44 [recorder WARNING] Failed push replay file 5e0a75cd-b8be-4ccd-8135-c0f89c994337: {'status': 403, 'request-id': '5B4EE6C89A4636974D564C7F', 'details': {'Code': 'AccessDenied', 'Message': 'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.', 'RequestId': '5B4EE6C89A4636974D564C7F', 'HostId': 'jumpserver.oss-ap-southeast-1.aliyuncs.com', 'Bucket': 'jumpserver', 'Endpoint': 'oss-cn-hangzhou.aliyuncs.com'}}, try again 1
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/seven/workspace/jumpserver/coco/coco/app.py", line 184, in func
    ok = recorder.upload_replay(session_id, 1)
  File "/home/seven/workspace/jumpserver/coco/coco/recorder.py", line 79, in upload_replay
    self.upload_replay(session_id, times-1)
  File "/home/seven/workspace/jumpserver/coco/coco/recorder.py", line 70, in upload_replay
    self.storage = jms_storage.JMSReplayStorage(app_service)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/jms_storage/jms.py", line 9, in __init__
    self.client = config.get("SERVICE")
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AppService' object has no attribute 'get'
2018-07-18 15:05:45 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:05:48 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:05:51 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:05:54 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:05:57 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:00 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:03 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:06 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:09 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:12 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:15 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:18 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:21 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:24 [transport DEBUG] Received global request "keepalive@openssh.com"
2018-07-18 15:06:27 [transport DEBUG] Received global request "keepalive@openssh.com"
.
.
.
.

```

**Comment by ibuler** [comment]
找到原因了，修改一下

```
    def upload_replay(self, session_id, times=3):
        if times < 1:
            if self.storage.type == 'jms':
                return False
            else:
                self.storage = jms_storage.JMSReplayStorage(
                    {"SERVICE": app_service}
                )
                self.upload_replay(session_id, times=3)
```

**Comment by gengkeye** [comment]
@ibuler  改了之后出现了新的错误，部分日志如下：
```
############################## End ##############################
2018-08-02 14:22:44 [channel DEBUG] [chan 0] EOF received (0)
2018-08-02 14:22:44 [channel DEBUG] [chan 0] EOF sent (0)
2018-08-02 14:22:44 [session INFO] Server close the connection
2018-08-02 14:22:44 [session INFO] Close the session: aea0793e-8317-4de0-8065-8752c1667f7f 
2018-08-02 14:22:44 [recorder WARNING] Failed push replay file aea0793e-8317-4de0-8065-8752c1667f7f: maximum recursion depth exceeded while calling a Python object, try again 3
2018-08-02 14:22:44 [app INFO] Remove session: aea0793e-8317-4de0-8065-8752c1667f7f
2018-08-02 14:22:44 [recorder WARNING] Failed push replay file aea0793e-8317-4de0-8065-8752c1667f7f: maximum recursion depth exceeded while calling a Python object, try again 2
2018-08-02 14:22:44 [recorder WARNING] Failed push replay file aea0793e-8317-4de0-8065-8752c1667f7f: maximum recursion depth exceeded while calling a Python object, try again 1
2018-08-02 14:22:44 [recorder INFO] Success push replay file: aea0793e-8317-4de0-8065-8752c1667f7f
2018-08-02 14:22:44 [recorder INFO] Success finish session aea0793e-8317-4de0-8065-8752c1667f7f's replay 
2018-08-02 14:22:44 [app INFO] Client <oldseven from 127.0.0.1:59868> leave, total 0 now
2018-08-02 14:22:44 [models INFO] Client <oldseven from 127.0.0.1:59868> close
```

**Comment by ibuler** [comment]
3次后没有成功推送到aws，最后推送到jumpserver本地存储了

**Comment by gengkeye** [comment]
是的，不知道哪里出了问题
