### ISSUE TITLE
AttributeError: 'Asset' object has no attribute 'protocol'

### ISSUE THREAD

**Issue by lizhisen** [jumpserver/jumpserver#1610]
2018-07-25 15:49:16 [models DEBUG] Proxy <coco.models.WSProxy object at 0x7f49b0c5cdd8> closed
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/opt/coco/coco/proxy.py", line 47, in proxy
if asset.protocol != system_user.protocol:
AttributeError: 'Asset' object has no attribute 'protocol'

1.开始以为是没升级sdk，因为环境不支持连外网，我手工更新了jumpserver-python-sdk-0.0.44.tar.gz，通过python setup.py install。后续对比了requirement，把jms-storage==0.0.18 jumpserver-python-sdk==0.0.44 paramiko==2.4.1 jms-storage==0.0.18 都已经手工升级，问题照旧。

2.jumpserver coco lua都升级1.3.3了

重新安装卸载过几次，回退到1.3.2就没问题了。

**Comment by wojiushixiaobai** [comment]
@lizhisen 确定组件版本一致。不要直接restart组件，用stop后，确定进程已经结束，然后重新start
