### ISSUE TITLE
1.0.0升级到1.3.3失败

### ISSUE THREAD

**Issue by lazyops** [jumpserver/jumpserver#1652]
[简述你的问题]

##### 使用版本
当前使用版本：1.0.0-2
计划升级到：1.3.3-2
##### 问题复现步骤
按离线升级文档操作，至执行迁移脚本步骤失败

##### 具体表现[截图可能会更好些,最好能截全]
\# sh 2018_04_11_migrate_permissions.sh
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/opt/py3/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/opt/jumpserver/apps/assets/models/__init__.py", line 8, in <module>
    from .domain import *
  File "/opt/jumpserver/apps/assets/models/domain.py", line 36, in <module>
    class Gateway(AssetUser):
  File "/opt/jumpserver/apps/assets/models/domain.py", line 46, in Gateway
    domain = models.ForeignKey(Domain, verbose_name=_("Domain"))
TypeError: __init__() missing 1 required positional argument: 'on_delete'

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@lazyops 先把数据库表结构还原

**Comment by ibuler** [comment]
django 版本 1.11 不要升级2.0
