### ISSUE TITLE
celery提示找不到ops模块

### ISSUE THREAD

**Issue by BackFire** [jumpserver/jumpserver#1689]
[简述你的问题]
ops_celerytask表里面有72个任务在waiting，想清理一下。用celery -A ops purge -f报错

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.4.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
(py3) [root@jump opt]# celery -A ops purge -f
Traceback (most recent call last):
  File "/opt/py3/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/opt/py3/lib64/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/opt/py3/lib64/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/opt/py3/lib64/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/py3/lib64/python3.6/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/opt/py3/lib64/python3.6/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/opt/py3/lib64/python3.6/site-packages/celery/bin/base.py", line 503, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/opt/py3/lib64/python3.6/site-packages/celery/app/utils.py", line 355, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/opt/py3/lib64/python3.6/site-packages/celery/bin/base.py", line 506, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/opt/py3/lib64/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ops'

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
```
$ cd /opt/jumpserver/apps
$ celery -A ops purge -f
```

有问题请重新打开issue
