### ISSUE TITLE
提示 AttributeError: 'AppService' object has no attribute 'check_user_with_token'

### ISSUE THREAD

**Issue by awklinux** [jumpserver/jumpserver#1708]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

##### 问题复现步骤
web 访问终端，没有反应，提示错误，这个问题经常出现

##### 具体表现[截图可能会更好些,最好能截全]
2018-08-18 10:31:20 [httpd ERROR] 'AppService' object has no attribute 'check_user_with_token'
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/flask_socketio/__init__.py", line 626, in _handle_event
    ret = handler(*args)
  File "/opt/coco/coco/httpd.py", line 108, in on_host
    current_user = self.get_current_user()
  File "/opt/coco/coco/httpd.py", line 34, in get_current_user
    user = app_service.check_user_with_token(token)
  File "/opt/py3/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AppService' object has no attribute 'check_user_with_token'

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
sdk版本不对，参考升级coco的说明

[升级文档](http://docs.jumpserver.org/zh/docs/upgrade.html)

**Comment by ibuler** [comment]
有问题重新打开
