### ISSUE TITLE
BUG 当网域网关通过 PNAT 进行跳转后测试网关连通性失败

### ISSUE THREAD

**Issue by kys1230** [jumpserver/jumpserver#1732]
背景环境:
2个数据中心分别为 A B, Jumpserver 在 A 中心, 两个数据中心的网络直接走公网质量不好. 购买了单独两台主机, 分别在两个数据中心的所在地域, 这两台主机之间通过专线互通, 两个数据中心访问通过在这两台机器 iptables NAT 方式进行. 
在B中心的网关实际监听SSH端口为22, 经过 iptables NAT 后 A 数据中心应该通过 2222 进行访问, 在网关配置的时候端口写的是 2222, 点击测试连通性后报错链接失败. 

看了下测试连通性的相关代码应该通过网关去链接本机的2222端口, 而实际上本地并未监听2222端口从而报错. 不知道这算不算 BUG . 对于跨墙的中心这种方式应该比较常见. 

##### 使用版本
1.4.0 版本

##### 问题复现步骤
1. 点击网关的测试连通性
2. 提示连接失败

##### 具体表现
Traceback (most recent call last):
  File "/data/venv/jumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/data/venv/jumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/venv/jumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/data/venv/jumpserver/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/venv/jumpserver/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/venv/jumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/data/venv/jumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/data/venv/jumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/jumpserver/apps/assets/api/domain.py", line 50, in get
    ok, e = test_gateway_connectability(self.object)
  File "/data/jumpserver/apps/assets/utils.py", line 67, in test_gateway_connectability
    'direct-tcpip', ('127.0.0.1', gateway.port), ('127.0.0.1', 0)
  File "/data/venv/jumpserver/lib/python3.6/site-packages/paramiko/transport.py", line 902, in open_channel
    raise e
paramiko.ssh_exception.ChannelException: (2, 'Connect failed')

##### 其他

[注:] 完成后请关闭 issue

**Comment by kys1230** [comment]
目前我的临时解决办法是将端口写死成22, 因为我的机器默认都是22..
diff --git a/apps/assets/utils.py b/apps/assets/utils.py
index f841e4a..8808725 100644
--- a/apps/assets/utils.py
+++ b/apps/assets/utils.py
@@ -64,11 +64,13 @@ def test_gateway_connectability(gateway):
         return False, str(e)
 
     sock = proxy.get_transport().open_channel(
-        'direct-tcpip', ('127.0.0.1', gateway.port), ('127.0.0.1', 0)
+        # 'direct-tcpip', ('127.0.0.1', gateway.port), ('127.0.0.1', 0)
+        'direct-tcpip', ('127.0.0.1', 22), ('127.0.0.1', 0)
     )
 
     try:
-        client.connect("127.0.0.1", port=gateway.port,
+        # client.connect("127.0.0.1", port=gateway.port,
+        client.connect("127.0.0.1", port=22,
                        username=gateway.username,
                        password=gateway.password,
                        key_filename=gateway.private_key_file,

**Comment by wojiushixiaobai** [comment]
@BaiJiangJie 老哥，貌似是不能正确传值，你要不要瞄下。之前我记得这个问题是处理过的

**Comment by ibuler** [comment]
这里确实可能存在该问题，不过测试无法通过，不影响使用

测试的逻辑是通过网关连自己这台机器

$ ssh ${GATEWAY.USER}@${GATEWAY.IP}:${GATEWAY.PORT} -p 
成功后
$ ssh ${GATEWAY.USER}@127.0.0.1:${GATEWAY.PORT}  

如果不做DNAT应该没问题，但如果做了DNAT, port则对不上了，以为我们取不到真实的127.0.0.1 监听的端口
