### ISSUE TITLE
数据库更新失败

### ISSUE THREAD

**Issue by qiqizjl** [jumpserver/jumpserver#1741]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
1.3.2 to 1.4.0(Master)
##### 问题复现步骤
执行 cd utils && sh make_migrations.sh
报错

##### 具体表现[截图可能会更好些,最好能截全]
~~~
Operations to perform:
  Apply all migrations: assets, audits, auth, captcha, common, contenttypes, django_celery_beat, ops, orgs, perms, sessions, terminal, users
Running migrations:
  Applying assets.0004_auto_20180824_1639... OK
  Applying audits.0002_ftplog_org_id... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying orgs.0001_initial...Traceback (most recent call last):
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1215, 'Cannot add foreign key constraint')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 106, in __exit__
    self.execute(sql)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/root/.pyenv/versions/jumpserver/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')
2018-08-24 17:25:09 [signals_handler DEBUG] Receive django ready signal
2018-08-24 17:25:09 [signals_handler DEBUG]   - fresh all settings
No conflicts detected to merge.
~~~

##### 其他

[注:] 完成后请关闭 issue

**Comment by qiqizjl** [comment]
已解决 数据表编码不一致

**Comment by stephen8339** [comment]
我也遇到了这个问题，请问您是这么解决的？

**Comment by qiqizjl** [comment]
将数据库编码和字段编码保持一致
