### ISSUE TITLE
jumpserver记录命令无法入库问题

### ISSUE THREAD

**Issue by qq77moon** [jumpserver/jumpserver#1773]
[简述你的问题]
jumpserver后台日志疯狂打下面的日志内容， 目前半天日志大概能涨1G空间，之前觉得可能是mysql数据库的字符集问题，修改了mysql字符集为utf8，后删除了数据库重建，现在还是出现这个问题。还望各位前辈能帮忙解决，谢谢。

2018-09-04 16:07:18 [log ERROR] Internal Server Error: /api/terminal/v1/command/
Traceback (most recent call last):
  File "/home/deploy/.virtualenvs/jumpserver/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/deploy/.virtualenvs/jumpserver/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/deploy/.virtualenvs/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/deploy/.virtualenvs/jumpserver/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/deploy/.virtualenvs/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/deploy/.virtualenvs/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/deploy/.virtualenvs/jumpserver/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/deploy/.virtualenvs/jumpserver/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x99\\x8C  ...' for column 'output' at row 4")

mysql字符集如下：
mysql> show variables like '%chara%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | utf8                       |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.01 sec)

[注:] 完成后请关闭 issue

**Comment by qq77moon** [comment]
![image](https://user-images.githubusercontent.com/23115053/45029783-58f9cf80-b07c-11e8-9174-0b7ec9aa9c52.png)

**Comment by qq77moon** [comment]
![image](https://user-images.githubusercontent.com/23115053/45029845-8d6d8b80-b07c-11e8-98ba-4ebe3b30a2bb.png)

**Comment by qq77moon** [comment]
![image](https://user-images.githubusercontent.com/23115053/45029870-a6763c80-b07c-11e8-88d1-e68f10bcc00a.png)

mysql的字符集已经修改为utf8mb4

**Comment by qq77moon** [comment]
但后台程序仍然插库失败

**Comment by ibuler** [comment]
手动插入报错吗

**Comment by qq77moon** [comment]
手动插入不报错，能正常插入
![image](https://user-images.githubusercontent.com/23115053/45030059-3b793580-b07d-11e8-91a1-0f152fa5c34a.png)

**Comment by ibuler** [comment]
感谢反馈，记录到 docs
