### ISSUE TITLE
1.4.1版本不支持ftp 上传和下载文件到具体机器上吗

### ISSUE THREAD

**Issue by yakexi07** [jumpserver/jumpserver#1802]
[简述你的问题]

jumpserver版本为1.4.1
无法看到 ftp 上传和下载的按钮

**Comment by wojiushixiaobai** [comment]
@yakexi07 支持，web文件上传功能还在制作中，可以使用sftp客户端或者命令进行上传
官网的文档中有介绍

**Comment by yakexi07** [comment]
当时使用sshpass
/usr/local/bin/sshpass -p xxxxxx  ssh  xxxx@xx.xx.xx.xx -p2222
Permission denied, please try again. 配置都是正确的，而且允许了 用密码进行验证，请问是什么问题呢
jumpserver 会报类似的错误，
2018-09-11 10:57:39 [log ERROR] Internal Server Error: /api/users/v1/auth/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/users/api/auth.py", line 68, in post
    'user': self.serializer_class(user).data
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/serializers.py", line 560, in data
    ret = super(Serializer, self).data
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/serializers.py", line 527, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/fields.py", line 1855, in to_representation
    return method(value)
  File "/opt/jumpserver/apps/users/serializers.py", line 38, in get_groups_display
    return " ".join([group.name for group in obj.groups.all()])
  File "/opt/py3/lib/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/opt/py3/lib/python3.6/site-packages/django/db/models/query.py", line 1183, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/py3/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/py3/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1061, in execute_sql
    cursor.execute(sql, params)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
    self.db.validate_no_broken_transaction()
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 437, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
2018-09-11 10:57:40 [signal_handler WARNING] Not get the task: 2600bf0d-1854-4ffa-849f-eebcc8dc2587
2018-09-11 10:57:40 [signal_handler WARNING] Not get the task: 2600bf0d-1854-4ffa-849f-eebcc8dc2587

**Comment by ThirteenPo** [comment]
借楼问一下，如何查看jumpserver的版本，见笑了。

**Comment by wojiushixiaobai** [comment]
@yakexi07 
sftp走的ssh的端口，先确定ssh能登录资产，不是直接连到资产，通过跳板机登录
