### ISSUE TITLE
创建资产后资产无法连接，同时celery.log报错

### ISSUE THREAD

**Issue by zhujianfeng** [jumpserver/jumpserver#1848]
[简述你的问题]
创建资产后资产无法连接，同时celery.log报错

##### 使用版本
1.4.1-2 

##### 问题复现步骤
1. 进入jumpserver安装目录下的logs目录，执行tail -f celery.log
2. 填写创建资产的表单，其中节点名称和标签为中文
3. 点击表单提交按钮
4. 控制台输出celery.log的错误内容

##### 具体表现（报错内容，已经删除主机名、用户名等敏感信息）
![1](https://user-images.githubusercontent.com/2062804/45876793-48608d80-bdce-11e8-9a07-7ff2268f7e65.png)
![image](https://user-images.githubusercontent.com/2062804/45876804-5e6e4e00-bdce-11e8-86f8-1ca0dd3ea3e3.png)

Received task: assets.tasks.update_assets_hardware_info_util[feeea0f0-9ab2-4d9a-8c68-2ba399bbfc0a]
TaskPool: Apply <function _fast_trace_task at 0x7fc68a9cabf8> (args:('assets.tasks.update_assets_hardware_info_util', 'feeea0f0-9ab2-4d9a-8c68-2ba399bbfc0a', {'lang': 'py', 'task': 'assets.tasks.update_assets_hardware_info_util', 'id': 'feeea0f0-9ab2-4d9a-8c68-2ba399bbfc0a', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'feeea0f0-9ab2-4d9a-8c68-2ba399bbfc0a', 'parent_id': None, 'argsrepr': '([<Asset: backend02.xx.xxxxxx.com(10.10.100.26)>],)', 'kwargsrepr': '{}', 'origin': 'gen37520@jumpserver00.xx.xxxxxx.com', 'reply_to': '4c95f144-3a59-30d1-b386-b83641a79cd6', 'correlation_id': 'feeea0f0-9ab2-4d9a-8c68-2ba399bbfc0a', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}},... kwargs:{})
Received task: assets.tasks.test_asset_connectability_util[2a4c30fd-0ec8-424e-aac2-4e6b7d0051f6]
TaskPool: Apply <function _fast_trace_task at 0x7fc68a9cabf8> (args:('assets.tasks.test_asset_connectability_util', '2a4c30fd-0ec8-424e-aac2-4e6b7d0051f6', {'lang': 'py', 'task': 'assets.tasks.test_asset_connectability_util', 'id': '2a4c30fd-0ec8-424e-aac2-4e6b7d0051f6', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '2a4c30fd-0ec8-424e-aac2-4e6b7d0051f6', 'parent_id': None, 'argsrepr': '([<Asset: backend02.xx.xxxxxx.com(10.10.100.26)>],)', 'kwargsrepr': '{}', 'origin': 'gen37520@jumpserver00.xx.xxxxxx.com', 'reply_to': '4c95f144-3a59-30d1-b386-b83641a79cd6', 'correlation_id': '2a4c30fd-0ec8-424e-aac2-4e6b7d0051f6', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': None}},... kwargs:{})
Task accepted: assets.tasks.update_assets_hardware_info_util[feeea0f0-9ab2-4d9a-8c68-2ba399bbfc0a] pid:37568
Task accepted: assets.tasks.test_asset_connectability_util[2a4c30fd-0ec8-424e-aac2-4e6b7d0051f6] pid:37569
Received task: assets.tasks.push_system_user_util[f2e962a0-904f-44fd-89fc-1776d93e461d]
--- Logging error ---
Traceback (most recent call last):
File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 438-441: ordinal not in range(128)
Call stack:
File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/__main__.py", line 18, in <module>
    main()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/worker.py", line 256, in run
    worker.start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
File "/home/jumper/py3/lib/python3.6/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
File "/home/jumper/py3/lib/python3.6/site-packages/kombu/transport/redis.py", line 1039, in on_readable
    self.cycle.on_readable(fileno)
File "/home/jumper/py3/lib/python3.6/site-packages/kombu/transport/redis.py", line 337, in on_readable
    chan.handlers[type]()
File "/home/jumper/py3/lib/python3.6/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
    self.connection._deliver(loads(bytes_to_str(item)), dest)
File "/home/jumper/py3/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 981, in _deliver
    callback(message)
File "/home/jumper/py3/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 633, in _callback
    return callback(message)
File "/home/jumper/py3/lib/python3.6/site-packages/kombu/messaging.py", line 623, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 570, in on_task_received
    callbacks,
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/strategy.py", line 145, in task_message_handler
    handle(req)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/worker.py", line 221, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
File "/home/jumper/py3/lib/python3.6/site-packages/kombu/async/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/request.py", line 531, in execute_using_pool
    correlation_id=task_id,
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/base.py", line 150, in apply_async
    truncate(safe_repr(kwargs), 1024))
Task accepted: assets.tasks.push_system_user_util[f2e962a0-904f-44fd-89fc-1776d93e461d] pid:37570
--- Logging error ---
Traceback (most recent call last):
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
File "/home/jumper/jumpserver/apps/assets/tasks.py", line 239, in test_asset_connectability_util
    options=const.TASK_OPTIONS, run_as_admin=True, created_by='System',
File "/home/jumper/jumpserver/apps/ops/utils.py", line 46, in update_or_create_ansible_task
    print("Task create new adhoc: {}".format(task_name))
File "/home/jumper/jumpserver/apps/common/utils.py", line 398, in write
    self.file_obj.write(msg.replace('*', ''))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 23-30: ordinal not in range(128)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 158-165: ordinal not in range(128)
Call stack:
File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/__main__.py", line 18, in <module>
    main()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/worker.py", line 256, in run
    worker.start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/base.py", line 131, in start
    self.on_start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 112, in on_start
    **self.options)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 422, in __init__
    super(AsynPool, self).__init__(processes, *args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 1007, in __init__
    self._create_worker_process(i)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 439, in _create_worker_process
    return super(AsynPool, self)._create_worker_process(i)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 1116, in _create_worker_process
    w.start()
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 289, in __call__
    sys.exit(self.workloop(pid=pid))
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 537, in _fast_trace_task
    uuid, args, kwargs, request,
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 388, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 330, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 164, in handle_error_state
    call_errbacks=call_errbacks)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 218, in handle_failure
    self._log_error(task, req, einfo)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 248, in _log_error
    extra={'data': context})
--- Logging error ---
Traceback (most recent call last):
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
File "/home/jumper/jumpserver/apps/assets/tasks.py", line 105, in update_assets_hardware_info_util
    options=const.TASK_OPTIONS, run_as_admin=True, created_by='System',
File "/home/jumper/jumpserver/apps/ops/utils.py", line 46, in update_or_create_ansible_task
    print("Task create new adhoc: {}".format(task_name))
File "/home/jumper/jumpserver/apps/common/utils.py", line 398, in write
    self.file_obj.write(msg.replace('*', ''))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 23-30: ordinal not in range(128)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 160-167: ordinal not in range(128)
Call stack:
File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/__main__.py", line 18, in <module>
    main()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/worker.py", line 256, in run
    worker.start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/base.py", line 131, in start
    self.on_start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 112, in on_start
    **self.options)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 422, in __init__
    super(AsynPool, self).__init__(processes, *args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 1007, in __init__
    self._create_worker_process(i)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 439, in _create_worker_process
    return super(AsynPool, self)._create_worker_process(i)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 1116, in _create_worker_process
    w.start()
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 289, in __call__
    sys.exit(self.workloop(pid=pid))
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 537, in _fast_trace_task
    uuid, args, kwargs, request,
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 388, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 330, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 164, in handle_error_state
    call_errbacks=call_errbacks)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 218, in handle_failure
    self._log_error(task, req, einfo)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 248, in _log_error
    extra={'data': context})
--- Logging error ---
Traceback (most recent call last):
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
File "/home/jumper/jumpserver/apps/assets/tasks.py", line 398, in push_system_user_util
    options=const.TASK_OPTIONS, run_as_admin=True, created_by='System'
File "/home/jumper/jumpserver/apps/ops/utils.py", line 46, in update_or_create_ansible_task
    print("Task create new adhoc: {}".format(task_name))
File "/home/jumper/jumpserver/apps/common/utils.py", line 398, in write
    self.file_obj.write(msg.replace('*', ''))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 23-32: ordinal not in range(128)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 149-158: ordinal not in range(128)
Call stack:
File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/__main__.py", line 18, in <module>
    main()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bin/worker.py", line 256, in run
    worker.start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/base.py", line 131, in start
    self.on_start()
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/prefork.py", line 112, in on_start
    **self.options)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 422, in __init__
    super(AsynPool, self).__init__(processes, *args, **kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 1007, in __init__
    self._create_worker_process(i)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/concurrency/asynpool.py", line 439, in _create_worker_process
    return super(AsynPool, self)._create_worker_process(i)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 1116, in _create_worker_process
    w.start()
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 289, in __call__
    sys.exit(self.workloop(pid=pid))
File "/home/jumper/py3/lib/python3.6/site-packages/billiard/pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 537, in _fast_trace_task
    uuid, args, kwargs, request,
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 388, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 330, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 164, in handle_error_state
    call_errbacks=call_errbacks)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 218, in handle_failure
    self._log_error(task, req, einfo)
File "/home/jumper/py3/lib/python3.6/site-packages/celery/app/trace.py", line 248, in _log_error
    extra={'data': context})

**Comment by zhujianfeng** [comment]
问题已经解决，原因是安装跳板机的操作系统设置有问题，将语言正确设置为zh_CN.utf-8之后，重启jumpserver，问题解决
