### ISSUE TITLE
任务列表内的任务，点击后提示错误500

### ISSUE THREAD

**Issue by veryrich** [jumpserver/jumpserver#1861]
[简述你的问题]
使用docker搭建，运行命令是
docker run --name jms_server -d -p 80:80 -p 2222:2222 -e DB_ENGINE=mysql -e DB_HOST=172.16.0.251 -e DB_PORT=3306 -e DB_USER=jumpserver -e DB_PASSWORD='www.123.com' -e DB_NAME=jumpserver  wojiushixiaobai/jumpserver:1.4.1

作业中心中的任务，全部执行失败，并且，推送系统用户的那一条任务，点击后弹出提示500错误。截图如下
![image](https://user-images.githubusercontent.com/12951051/46142981-3cbc0d80-c28b-11e8-8f47-2c5ce3fce972.png)

错误如下：
![image](https://user-images.githubusercontent.com/12951051/46143040-6412da80-c28b-11e8-92db-0df28aaeb04d.png)

其它的任务可以点击，并看到详情例如，第二个任务：
![image](https://user-images.githubusercontent.com/12951051/46143076-75f47d80-c28b-11e8-86f1-266eaa797f05.png)

##### 使用版本
Jumpserver版本 1.4.1##### 问题复现步骤

**Comment by veryrich** [comment]
当我出现 500错误的时候，jumpserver的错误日志如下：
（使用命令 docker exec -ti ID /bin/bash  进入docker 内,在/opt/jumpserver/logs/jumpserver.log日志中使用tail -f 追中日志，然后点击任务并出现500报错后，截取的日志）

==> ./jumpserver.log <==
2018-09-27 19:34:35 [log ERROR] Internal Server Error: /ops/task/a100c197-9770-45ca-8f8f-a4e8c12b2110/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/opt/py3/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/opt/py3/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/opt/py3/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/py3/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/opt/py3/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/opt/py3/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'celery-task-log' with keyword arguments '{'pk': ''}' not found. 1 pattern(s) tried: ['ops\\/celery\\/task\\/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\\/log\\/$']

**Comment by wojiushixiaobai** [comment]
@veryrich 已收到，目前存在这个问题，请等待修复

**Comment by ibuler** [comment]
已修复
