### ISSUE TITLE
Jumpserver 接受coco注册后报错  No such file or directory: '/opt/coco/keys/.access_key'

### ISSUE THREAD

**Issue by vincent927** [jumpserver/jumpserver#1881]
[简述你的问题]

##### 使用版本
Jumpserver 1.4.2

##### 问题复现步骤
1. 按照教程安装到coco启动
2. 执行```./cocod start``` 
3. 在web页面接受注册
4. coco报错
```
(py3) [root@jump coco]# ./cocod start
Traceback (most recent call last):
  File "./cocod", line 11, in <module>
    from coco import Coco
  File "/opt/coco/coco/__init__.py", line 5, in <module>
    from .app import Coco
  File "/opt/coco/coco/app.py", line 18, in <module>
    from .sshd import SSHServer
  File "/opt/coco/coco/sshd.py", line 12, in <module>
    from coco.interface import SSHInterface
  File "/opt/coco/coco/interface.py", line 11, in <module>
    from .ctx import app_service
  File "/opt/coco/coco/ctx.py", line 22, in <module>
    app_service.initial()
  File "/opt/py3/lib/python3.6/site-packages/jms/service.py", line 56, in initial
    self.load_access_key()
  File "/opt/py3/lib/python3.6/site-packages/jms/service.py", line 67, in load_access_key
    self.register_and_save()
  File "/opt/py3/lib/python3.6/site-packages/jms/service.py", line 116, in register_and_save
    self.save_access_key()
  File "/opt/py3/lib/python3.6/site-packages/jms/service.py", line 119, in save_access_key
    self.access_key.save_to_file()
  File "/opt/py3/lib/python3.6/site-packages/jms/auth.py", line 157, in save_to_file
    return super().save_to_f(self._key_file)
  File "/opt/py3/lib/python3.6/site-packages/jms/auth.py", line 105, in save_to_f
    f = open(f, 'wt')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/coco/keys/.access_key'
```

#### 其他
![image](https://user-images.githubusercontent.com/10399425/46650130-0d33cc00-cbce-11e8-9904-ae219621e101.png)

**Comment by wojiushixiaobai** [comment]
@vincent927 mkdir -p /opt/coco/keys/
然后重新注册

**Comment by vincent927** [comment]
@wojiushixiaobai 谢谢，这算不算个小bug
