### ISSUE TITLE
网关无法连接

### ISSUE THREAD

**Issue by zxing0214** [jumpserver/jumpserver#1923]
网关无法连接

##### 使用版本
Version 1.4.3-2 GPLv2.

##### 问题复现步骤
1. 添加网关，ssh 协议
2. 点击测试，总是提示连接错误
3. 在 jumpserver 上直接通过 ssh 连接网关服务器，正常。

##### 具体表现[截图可能会更好些,最好能截全]

错误日志：
![image](https://user-images.githubusercontent.com/1646806/47060122-dded1280-d1fe-11e8-93e6-1f789784239c.png)

错误日志

`2018-10-17 11:12:06 [log ERROR] Internal Server Error: /api/assets/v1/gateway/ed24ba0e-a45d-4c56-b195-8aa0280015a6/test-connective/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/assets/api/domain.py", line 50, in get
    ok, e = test_gateway_connectability(self.object)
  File "/opt/jumpserver/apps/assets/utils.py", line 67, in test_gateway_connectability
  File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 902, in open_channel
    raise e
paramiko.ssh_exception.ChannelException: (2, 'Connect failed')`

![image](https://user-images.githubusercontent.com/1646806/47060137-eba29800-d1fe-11e8-8830-35fcc4653171.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@zxing0214 可能你是通过映射端口的方式来进行连接的，端口映射前后不一致时会出现测试失败（实际是成功的），你可以直接测试资产看看
