### ISSUE TITLE
ubuntu 16.04 启动报错ldap相关错误

### ISSUE THREAD

**Issue by zsdevX** [jumpserver/jumpserver#1964]
版本为为最为 git clone https://github.com/jumserver/jumpserver.git
首次启动 报ldap auth相关模块缺失 pip 安装后启动报新错：

Jumpserver version 1.4.3, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
Check database structure change ...
Traceback (most recent call last):
File "manage.py", line 28, in <module>
  execute_from_command_line(sys.argv)
File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
  utility.execute()
File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 224, in fetch_command
  klass = load_command_class(app_name, subcommand)
File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
  module = import_module('%s.management.commands.%s' % (app_name, name))
File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 978, in _gcd_import
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
File "/opt/py3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 14, in <module>
  from django.db.migrations.autodetector import MigrationAutodetector
File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 11, in <module>
  from django.db.migrations.questioner import MigrationQuestioner
File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/questioner.py", line 9, in <module>
  from .loader import MigrationLoader
File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/loader.py", line 8, in <module>
  from django.db.migrations.recorder import MigrationRecorder
File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 9, in <module>
  class MigrationRecorder:
File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 22, in MigrationRecorder
  class Migration(models.Model):
File "/opt/py3/lib/python3.6/site-packages/django/db/models/base.py", line 87, in __new__
  app_config = apps.get_containing_app_config(module)
File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 249, in get_containing_app_config
  self.check_apps_ready()
File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 131, in check_apps_ready
  settings.INSTALLED_APPS
File "/opt/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
  self._setup(name)
File "/opt/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
  self._wrapped = Settings(settings_module)
File "/opt/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
  mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
File "/opt/jumpserver/apps/jumpserver/settings.py", line 17, in <module>
  from django_auth_ldap.config import LDAPSearch, LDAPSearchUnion
File "/opt/py3/lib/python3.6/site-packages/django_auth_ldap/config.py", line 38, in <module>
  import ldap.filter
File "/opt/py3/lib/python3.6/site-packages/ldap/filter.py", line 12, in <module>
  from ldap.functions import strf_secs
File "/opt/py3/lib/python3.6/site-packages/ldap/functions.py", line 20, in <module>
  from ldap import LDAPError
ImportError: cannot import name 'LDAPError'
Collect static files
Traceback (most recent call last):
File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 204, in fetch_command
  app_name = commands[subcommand]
KeyError: 'collectstatic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "manage.py", line 28, in <module>
  execute_from_command_line(sys.argv)
File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
  utility.execute()
File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 211, in fetch_command
  settings.INSTALLED_APPS
File "/opt/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
  self._setup(name)
File "/opt/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
  self._wrapped = Settings(settings_module)
File "/opt/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
  mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 978, in _gcd_import
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
File "/opt/jumpserver/apps/jumpserver/settings.py", line 17, in <module>
  from django_auth_ldap.config import LDAPSearch, LDAPSearchUnion
File "/opt/py3/lib/python3.6/site-packages/django_auth_ldap/config.py", line 38, in <module>
  import ldap.filter
File "/opt/py3/lib/python3.6/site-packages/ldap/filter.py", line 12, in <module>
  from ldap.functions import strf_secs
File "/opt/py3/lib/python3.6/site-packages/ldap/functions.py", line 20, in <module>
  from ldap import LDAPError
ImportError: cannot import name 'LDAPError'

**Comment by wojiushixiaobai** [comment]
@zsdevX 无法复现，请检查一下系统环境，如果需要的话可以提供远程技术支持。
