### ISSUE TITLE
主机名称过长BUG,导致webterminal,ssh无法登陆目标主机

### ISSUE THREAD

**Issue by igoryang** [jumpserver/jumpserver#199]
主机名称过长BUG  登陆日志上也没有报错   会影响到 webterminal 和 ssh的登陆  程序上可以修改吗？还是说程序上只支持到32字符这个长度, 如主机名称：pbs_10-80-20-25_lin_logistics.service.activity.service算长吗？没超过表上的128 ,webterminal ssh 不能登陆 ，把主机名称修改成 pbs_10-80-20-25_lin_lsas ,webterminal  ssh 正常

**Comment by ibuler** [comment]
tty连接正常吗？还是只是webterminal ?

**Comment by yumaojun03** [comment]
我这边客户端 使用centos7， 测试terminal并没出现bug，你能贴出具体环境吗？
我的测试结果：
[new_user1@pbs_10-80-20-25_lin_logistics ~]$ hostname
pbs_10-80-20-25_lin_logistics.service.activity.service
[new_user1@pbs_10-80-20-25_lin_logistics ~

**Comment by igoryang** [comment]
主机名称如上 tty 和 webterminal 2个都不可以，把主机名称修改短后正常。

**Comment by igoryang** [comment]
CentOS release 6.6 (Final)  jumpserver 3.0

主机名称：pbs_10-80-20-25_lin_logistics.service.activity.service  --》webterminal 一直connecting，回车后  CONNECTION RESET BY PEER 


后台日志：2016-04-12 22:00:58,068 - views.py - DEBUG - 获取授权系统用户: baolei
2016-04-12 22:00:58,585 - run_websocket.py - DEBUG - Websocket: session_key: xxkki3bi2qfh3o37hfvidcoj7dsd5wi1
2016-04-12 22:00:58,590 - run_websocket.py - DEBUG - Websocket: session: Session object
2016-04-12 22:00:58,593 - run_websocket.py - DEBUG - Websocket: user [ gang.yang ] request websocket
2016-04-12 22:00:58,593 - run_websocket.py - DEBUG - Websocket: Open request
2016-04-12 22:00:58,640 - run_websocket.py - DEBUG - set([<PermRole: baolei>])
2016-04-12 22:00:58,640 - run_websocket.py - DEBUG - 系统用户: baolei
2016-04-12 22:00:58,641 - run_websocket.py - DEBUG - Websocket: request web terminal Host: pbs_10-80-20-25_lin_logistics.service.activity.service User: gang.yang Role: baolei
2016-04-12 22:00:58,642 - connect.py - DEBUG - {'ip': u'10.80.20.25', 'role_name': u'baolei', 'role_key': u'/opt/jumpserver/keys/user/gang.yang_baolei.pem', 'user': <User: gang.yang>, 'role_pass': 'JEsGmQa2hyqXV7xhVAnX', 'port': 22, 'asset': <Asset: 10.80.20.25>}

2016-04-12 22:02:15,210 - run_websocket.py - DEBUG - Websocket: Close request

==============================================================

2，tty
[9  ] pbs_10-80-20-25_lin_logistics.service.activity.service 10.80.20.25      22     ['baolei']  

Opt or ID>: 9
Traceback (most recent call last):
  File "/opt/jumpserver/connect.py", line 818, in <module>
    main()
  File "/opt/jumpserver/connect.py", line 807, in main
    ssh_tty.connect()
  File "/opt/jumpserver/connect.py", line 458, in connect
    ssh = self.get_connection()
  File "/opt/jumpserver/connect.py", line 308, in get_connection
    look_for_keys=False)
  File "/usr/lib/python2.6/site-packages/paramiko/client.py", line 367, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.6/site-packages/paramiko/client.py", line 505, in _auth
    key = pkey_class.from_private_key_file(key_filename, password)
  File "/usr/lib/python2.6/site-packages/paramiko/pkey.py", line 184, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/lib/python2.6/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python2.6/site-packages/paramiko/rsakey.py", line 165, in _from_private_key_file
    data = self._read_private_key_file('RSA', filename, password)
  File "/usr/lib/python2.6/site-packages/paramiko/pkey.py", line 255, in _read_private_key_file
    with open(filename, 'r') as f:
IOError: [Errno 13] Permission denied: u'/opt/jumpserver/keys/user/gang.yang_baolei.pem'
================================================================

我所主机名称修改为 ：pbs_10-80-20-25_lin_lsas====》webterminal ，tty 可以登陆

**Comment by liuzheng712** [comment]
> IOError: [Errno 13] Permission denied: u'/opt/jumpserver/keys/user/gang.yang_baolei.pem'

权限问题？

**Comment by yumaojun03** [comment]
暂时限制了主机名的长度。
