### ISSUE TITLE
Windows Server 2012R2 x64 RDP CONNECTION ERROR

### ISSUE THREAD

**Issue by purevita** [jumpserver/jumpserver#2062]
[简述你的问题]
Windows Server 2012R2 x64 RDP CONNECTION ERROR

##### 使用版本
1.4.4

##### 具体表现[截图可能会更好些,最好能截全]
tomcat8 log catalina.out
```
07:18:40.788 [Thread-189] ERROR o.a.g.a.j.s.JumpserverSessionService - 更新Session失败
java.lang.NullPointerException: null
	at org.apache.guacamole.auth.jumpserver.utils.ForwardPortUtil.stop(ForwardPortUtil.java:70) ~[guacamole-auth-jumpserver-0.9.14.jar:na]
	at org.apache.guacamole.auth.jumpserver.session.JumpserverSessionService.finishSession(JumpserverSessionService.java:109) ~[guacamole-auth-jumpserver-0.9.14.jar:na]
	at org.apache.guacamole.auth.jumpserver.event.JumpserverListener.handleEvent(JumpserverListener.java:34) [guacamole-auth-jumpserver-0.9.14.jar:na]
	at org.apache.guacamole.rest.event.ListenerService.handleEvent(ListenerService.java:53) [classes/:na]
	at org.apache.guacamole.tunnel.TunnelRequestService.fireTunnelClosedEvent(TunnelRequestService.java:115) [classes/:na]
	at org.apache.guacamole.tunnel.TunnelRequestService.access$000(TunnelRequestService.java:52) [classes/:na]
	at org.apache.guacamole.tunnel.TunnelRequestService$1.close(TunnelRequestService.java:307) [classes/:na]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.onClose(GuacamoleWebSocketTunnelEndpoint.java:265) [guacamole-common-0.9.14.jar:na]
	at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:535) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.WsSession.doClose(WsSession.java:481) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.WsSession.close(WsSession.java:445) [tomcat-websocket.jar:8.5.35]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.closeConnection(GuacamoleWebSocketTunnelEndpoint.java:87) [guacamole-common-0.9.14.jar:na]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.closeConnection(GuacamoleWebSocketTunnelEndpoint.java:106) [guacamole-common-0.9.14.jar:na]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$100(GuacamoleWebSocketTunnelEndpoint.java:50) [guacamole-common-0.9.14.jar:na]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:197) [guacamole-common-0.9.14.jar:na]

```
##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@purevita 在 '系统用户' 里面选择 '更新' ，修改 '自动登陆' 为 '手动登陆' ，然后重新通过web连接资产，看提示什么

建议参考[FAQ文档](http://docs.jumpserver.org/zh/docs/faq_rdp.html)

**Comment by tnndlbmu** [comment]
这个问题我也碰到了，使用手动登陆windows资产正常，自动登陆就会抛出一楼的异常。抛出的tomcat catalina 日志是一样的。同时，我在log/message下发现如下报错：
Nov 20 20:04:47 mb guacd[6171]: Loading keymap "base"
Nov 20 20:04:47 mb guacd[6171]: Loading keymap "en-us-qwerty"
Nov 20 20:04:47 mb guacd[6171]: Failed to load cliprdr plugin. Clipboard will not work.
Nov 20 20:04:47 mb guacd[6171]: Failed to load guacdr plugin. Drive redirection and printing will not work. Sound MAY not work.
Nov 20 20:04:47 mb guacd[6171]: Failed to load guacsnd alongside guacdr plugin. Sound will not work. Drive redirection and printing MAY not work.
Nov 20 20:04:47 mb guacd[6171]: Error connecting to RDP server
Nov 20 20:04:47 mb guacd[6171]: User "@efa7e9bf-8bac-47e0-8d8f-f9f8f34d9068" disconnected (0 users remain)
Nov 20 20:04:47 mb guacd[6171]: Last user of connection "$2a15857d-ac39-408b-94d1-656ffc9376da" disconnected
Nov 20 20:04:47 mb guacd[2705]: Connection "$2a15857d-ac39-408b-94d1-656ffc9376da" removed.

**Comment by tnndlbmu** [comment]
这是我的堡垒机操作系统环境：
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core) 
Release:        7.3.1611
Codename:       Core

需要远程windows的环境是windows 2008 r2 ent sp1
经过我的排查在装guacd之前还需要yum一个组件:
yum -y install freerdp-plugins

同样windows 组策略要确保这项是“允许所有”或者是"没有定义"：
![image](https://user-images.githubusercontent.com/8831381/48834808-a2270900-edb9-11e8-8e81-fb37bdf79780.png)

通过以上操作，堡垒机就可以自动登陆并远程windows的资产了。

**Comment by purevita** [comment]
根据 @tnndlbmu 的方法
在一台系统为CentOS Linux release 7.3.1611 (Core)的主机上部署
自动RDP远程Windows Server 2012R2 Standard成功
自动手动RDP远程Windows Server 2016 Standard失败（资产的系统平台有选择为Windows 2016）

```
07:02:30.451 [http-nio-8081-exec-7] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
07:02:30.504 [http-nio-8081-exec-7] INFO  o.a.g.tunnel.TunnelRequestService - User "018a6ad2-302d-4d63-982c-91b43e08a7d8" connected to connection "862d332b-dffe-4abc-953a-a736b2ea0729".
07:02:30.504 [http-nio-8081-exec-7] INFO  o.a.g.a.j.s.JumpserverSessionService - 注册Session{remote_addr=192.168.143.58, protocol=rdp, date_start=2018-11-22 07:02:30 +0000, org_id=, id=40c5ac73-bf85-4d12-8808-a35aaef342b9, system_user=218a48cd-69e3-4692-a963-24110e73b2d7, asset=win2, user=admin, is_finished=false, login_from=WT}
07:02:30.539 [http-nio-8081-exec-7] INFO  o.a.g.a.j.s.JumpserverSessionService - {code:201,result:{"id":"40c5ac73-bf85-4d12-8808-a35aaef342b9","command_amount":0,"org_id":"","user":"admin","asset":"win2","system_user":"win_admin","login_from":"WT","remote_addr":"192.168.143.58","is_finished":false,"has_replay":false,"has_command":false,"protocol":"rdp","date_last_active":"2018-11-22 15:02:30 +0800","date_start":"2018-11-22 15:02:30 +0800","date_end":null,"terminal":"23a79f74-debd-453a-b765-a931534f786c"}}
07:02:30.539 [http-nio-8081-exec-7] INFO  o.a.g.a.j.s.JumpserverSessionService - 注册Session成功
07:02:30.551 [Thread-63] INFO  o.a.g.a.j.s.JumpserverSessionService - 更新Session{date_end=2018-11-22 07:02:30 +0000, is_finished=true}
07:02:30.558 [Thread-65] INFO  o.a.g.a.j.s.JumpserverSessionService - path:/config/guacamole/record/018a6ad2-302d-4d63-982c-91b43e08a7d8
07:02:30.558 [Thread-65] INFO  o.a.g.a.j.s.JumpserverSessionService - recordName:win2-b9b1dc20-2434-48d7-bb32-daa2c36c53ee
07:02:30.558 [Thread-65] INFO  o.a.g.a.j.s.JumpserverSessionService - index:win2-b9b1dc20-2434-48d7-bb32-daa2c36c53ee
07:02:30.610 [Thread-65] INFO  o.a.g.a.j.s.JumpserverSessionService - {code:201,result:{"url":"/media/replay/2018-11-22/40c5ac73-bf85-4d12-8808-a35aaef342b9.replay.gz"}}
07:02:30.610 [Thread-65] INFO  o.a.g.a.j.s.JumpserverSessionService - 上传录像成功
07:02:30.625 [Thread-63] INFO  o.a.g.a.j.s.JumpserverSessionService - {code:200,result:{"id":"40c5ac73-bf85-4d12-8808-a35aaef342b9","command_amount":0,"org_id":"","user":"admin","asset":"win2","system_user":"win_admin","login_from":"WT","remote_addr":"192.168.143.58","is_finished":true,"has_replay":false,"has_command":false,"protocol":"rdp","date_last_active":"2018-11-22 15:02:30 +0800","date_start":"2018-11-22 15:02:30 +0800","date_end":"2018-11-22 15:02:30 +0800","terminal":"23a79f74-debd-453a-b765-a931534f786c"}}
07:02:30.626 [Thread-63] ERROR o.a.g.a.j.s.JumpserverSessionService - 更新Session失败
java.lang.NullPointerException: null
	at org.apache.guacamole.auth.jumpserver.utils.ForwardPortUtil.stop(ForwardPortUtil.java:70) ~[guacamole-auth-jumpserver-0.9.14.jar:na]
	at org.apache.guacamole.auth.jumpserver.session.JumpserverSessionService.finishSession(JumpserverSessionService.java:109) ~[guacamole-auth-jumpserver-0.9.14.jar:na]
	at org.apache.guacamole.auth.jumpserver.event.JumpserverListener.handleEvent(JumpserverListener.java:34) [guacamole-auth-jumpserver-0.9.14.jar:na]
	at org.apache.guacamole.rest.event.ListenerService.handleEvent(ListenerService.java:53) [classes/:na]
	at org.apache.guacamole.tunnel.TunnelRequestService.fireTunnelClosedEvent(TunnelRequestService.java:115) [classes/:na]
	at org.apache.guacamole.tunnel.TunnelRequestService.access$000(TunnelRequestService.java:52) [classes/:na]
	at org.apache.guacamole.tunnel.TunnelRequestService$1.close(TunnelRequestService.java:307) [classes/:na]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.onClose(GuacamoleWebSocketTunnelEndpoint.java:265) [guacamole-common-0.9.14.jar:na]
	at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:535) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.WsSession.doClose(WsSession.java:481) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.WsSession.close(WsSession.java:445) [tomcat-websocket.jar:8.5.35]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.closeConnection(GuacamoleWebSocketTunnelEndpoint.java:87) [guacamole-common-0.9.14.jar:na]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.closeConnection(GuacamoleWebSocketTunnelEndpoint.java:106) [guacamole-common-0.9.14.jar:na]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$100(GuacamoleWebSocketTunnelEndpoint.java:50) [guacamole-common-0.9.14.jar:na]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:197) [guacamole-common-0.9.14.jar:na]
07:02:30.626 [Thread-63] INFO  o.a.g.tunnel.TunnelRequestService - User "018a6ad2-302d-4d63-982c-91b43e08a7d8" disconnected from connection "862d332b-dffe-4abc-953a-a736b2ea0729". Duration: 87 milliseconds
07:02:30.634 [http-nio-8081-exec-4] INFO  o.a.g.a.j.p.JumpserverPermissionService - getUser:018a6ad2-302d-4d63-982c-91b43e08a7d8
```
先前部署的1.3.1版本（系统为CentOS Linux release 7.3.1611 (Core)）RDP远程确定上述两台主机可以连接


今日看到安装文档已经更新过，包含了freerdp-plugins的安装
重新安装过后，手动RDP远程Windows Server 2012R2 Standard已成功
但自动依然会有错误
主机系统为CentOS Linux release 7.5.1804 (Core)
```
06:49:13.866 [http-nio-8081-exec-2] INFO  o.a.g.a.j.p.JumpserverPermissionService - getUser:10469882-02d2-4968-ab99-01b23b1a4bfa
06:49:13.867 [http-nio-8081-exec-2] INFO  o.a.g.r.auth.AuthenticationService - User "10469882-02d2-4968-ab99-01b23b1a4bfa" successfully authenticated from [192.168.143.58, 127.0.0.1].
22-Nov-2018 06:49:13.894 WARNING [http-nio-8081-exec-10] com.sun.jersey.spi.container.servlet.WebComponent.filterFormParameters A servlet request, to the URI http://10.3.3.57/api/session/ext/jumpserver/asset/add?user_id=10469882-02d2-4968-ab99-01b23b1a4bfa&asset_id=c87b395c-0db9-46ca-8247-d68b294f8b50&system_user_id=35072659-25a5-42b7-aa74-a4f2b1997196&token=3E477AEEF7E1EFD61ADEC1FDA384000639BD9B74F1D461BCD41A7EECD86860D5, contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.
06:49:13.959 [http-nio-8081-exec-10] INFO  o.a.g.a.j.p.JumpserverPermissionService - validatePermission:{code:200,result:{"msg":true}}
06:49:13.994 [http-nio-8081-exec-10] INFO  o.a.g.a.j.p.JumpserverPermissionService - getAsset:{code:200,result:{"id":"c87b395c-0db9-46ca-8247-d68b294f8b50","org_id":"","ip":"10.3.3.61","hostname":"web1","protocol":"rdp","port":3389,"platform":"Windows","is_active":true,"public_ip":null,"number":null,"vendor":null,"model":null,"sn":null,"cpu_model":null,"cpu_count":null,"cpu_cores":null,"cpu_vcpus":null,"memory":null,"disk_total":null,"disk_info":null,"os":null,"os_version":null,"os_arch":null,"hostname_raw":null,"created_by":"Administrator","date_created":"2018-11-22 14:46:02 +0800","comment":"","domain":null,"admin_user":"c0f65e5b-8ac3-420c-a2d9-ebdda652e76e","nodes":["38ac510f-ad75-4045-9b44-85b8ad6af34a"],"labels":[],"hardware_info":"","is_connective":true,"org_name":"DEFAULT"}}
06:49:14.017 [http-nio-8081-exec-10] INFO  o.a.g.a.j.p.JumpserverPermissionService - getSystemUser:{code:200,result:{"id":"35072659-25a5-42b7-aa74-a4f2b1997196","name":"win_admin","username":"administrator","protocol":"rdp","login_mode":"auto","password":"tj0 z/","private_key":null}}
06:49:14.017 [http-nio-8081-exec-10] INFO  o.a.g.a.j.JumpserverAuthenticationService - configuration: {drive-path=/config/guacamole/drive/10469882-02d2-4968-ab99-01b23b1a4bfa, systemUserId=35072659-25a5-42b7-aa74-a4f2b1997196, userId=10469882-02d2-4968-ab99-01b23b1a4bfa, create-drive-path=true, orgId=, hostname=10.3.3.61, password=tj0 z/, security=any, ignore-cert=true, port=3389, enable-drive=true, create-recording-path=true, asset=web1, recording-name=web1-e609e275-6378-454f-8a8d-3317aa3ff9fc, recording-path=/config/guacamole/record/10469882-02d2-4968-ab99-01b23b1a4bfa, username=administrator}
06:49:14.017 [http-nio-8081-exec-10] INFO  o.a.g.a.j.JumpserverAuthenticationService - 添加资产成功,userId: 10469882-02d2-4968-ab99-01b23b1a4bfa, assetId: c87b395c-0db9-46ca-8247-d68b294f8b50, systemUserId: 35072659-25a5-42b7-aa74-a4f2b1997196
06:49:14.847 [http-nio-8081-exec-5] INFO  o.a.g.a.j.p.JumpserverPermissionService - getUser:10469882-02d2-4968-ab99-01b23b1a4bfa
06:49:15.075 [http-nio-8081-exec-5] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
06:49:15.130 [http-nio-8081-exec-5] INFO  o.a.g.tunnel.TunnelRequestService - User "10469882-02d2-4968-ab99-01b23b1a4bfa" connected to connection "c87b395c-0db9-46ca-8247-d68b294f8b50".
06:49:15.131 [http-nio-8081-exec-5] INFO  o.a.g.a.j.s.JumpserverSessionService - 注册Session{remote_addr=192.168.143.58, protocol=rdp, date_start=2018-11-22 06:49:15 +0000, org_id=, id=38cf2ce0-0ef4-4f4f-a7b8-fc2db1fd033b, system_user=administrator, asset=web1, user=admin, is_finished=false, login_from=WT}
06:49:15.178 [http-nio-8081-exec-5] INFO  o.a.g.a.j.s.JumpserverSessionService - {code:201,result:{"id":"38cf2ce0-0ef4-4f4f-a7b8-fc2db1fd033b","command_amount":0,"org_id":"","user":"admin","asset":"web1","system_user":"administrator","login_from":"WT","remote_addr":"192.168.143.58","is_finished":false,"has_replay":false,"has_command":false,"protocol":"rdp","date_last_active":"2018-11-22 14:49:15 +0800","date_start":"2018-11-22 14:49:15 +0800","date_end":null,"terminal":"08ec5ae2-c34e-4fb4-9cab-e0612b3bd794"}}
06:49:15.178 [http-nio-8081-exec-5] INFO  o.a.g.a.j.s.JumpserverSessionService - 注册Session成功
Exception in thread "Thread-20" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:424)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:191)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:190)
06:49:16.167 [http-nio-8081-exec-4] INFO  o.a.g.a.j.s.JumpserverSessionService - 更新Session{date_end=2018-11-22 06:49:16 +0000, is_finished=true}
06:49:16.168 [Thread-22] INFO  o.a.g.a.j.s.JumpserverSessionService - path:/config/guacamole/record/10469882-02d2-4968-ab99-01b23b1a4bfa
06:49:16.168 [Thread-22] INFO  o.a.g.a.j.s.JumpserverSessionService - recordName:web1-e609e275-6378-454f-8a8d-3317aa3ff9fc
06:49:16.168 [Thread-22] INFO  o.a.g.a.j.s.JumpserverSessionService - index:web1-e609e275-6378-454f-8a8d-3317aa3ff9fc
06:49:16.187 [Thread-22] INFO  o.a.g.a.j.s.JumpserverSessionService - {code:201,result:{"url":"/media/replay/2018-11-22/38cf2ce0-0ef4-4f4f-a7b8-fc2db1fd033b.replay.gz"}}
06:49:16.188 [Thread-22] INFO  o.a.g.a.j.s.JumpserverSessionService - 上传录像成功
06:49:16.197 [http-nio-8081-exec-4] INFO  o.a.g.a.j.s.JumpserverSessionService - {code:200,result:{"id":"38cf2ce0-0ef4-4f4f-a7b8-fc2db1fd033b","command_amount":0,"org_id":"","user":"admin","asset":"web1","system_user":"administrator","login_from":"WT","remote_addr":"192.168.143.58","is_finished":true,"has_replay":false,"has_command":false,"protocol":"rdp","date_last_active":"2018-11-22 14:49:15 +0800","date_start":"2018-11-22 14:49:15 +0800","date_end":"2018-11-22 14:49:16 +0800","terminal":"08ec5ae2-c34e-4fb4-9cab-e0612b3bd794"}}
06:49:16.198 [http-nio-8081-exec-4] ERROR o.a.g.a.j.s.JumpserverSessionService - 更新Session失败
java.lang.NullPointerException: null
	at org.apache.guacamole.auth.jumpserver.utils.ForwardPortUtil.stop(ForwardPortUtil.java:70) ~[guacamole-auth-jumpserver-0.9.14.jar:na]
	at org.apache.guacamole.auth.jumpserver.session.JumpserverSessionService.finishSession(JumpserverSessionService.java:109) ~[guacamole-auth-jumpserver-0.9.14.jar:na]
	at org.apache.guacamole.auth.jumpserver.event.JumpserverListener.handleEvent(JumpserverListener.java:34) [guacamole-auth-jumpserver-0.9.14.jar:na]
	at org.apache.guacamole.rest.event.ListenerService.handleEvent(ListenerService.java:53) [classes/:na]
	at org.apache.guacamole.tunnel.TunnelRequestService.fireTunnelClosedEvent(TunnelRequestService.java:115) [classes/:na]
	at org.apache.guacamole.tunnel.TunnelRequestService.access$000(TunnelRequestService.java:52) [classes/:na]
	at org.apache.guacamole.tunnel.TunnelRequestService$1.close(TunnelRequestService.java:307) [classes/:na]
	at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.onClose(GuacamoleWebSocketTunnelEndpoint.java:265) [guacamole-common-0.9.14.jar:na]
	at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:535) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:513) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.WsFrameBase.processDataControl(WsFrameBase.java:347) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:289) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) [tomcat-websocket.jar:8.5.35]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) [tomcat-websocket.jar:8.5.35]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-coyote.jar:8.5.35]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) [tomcat-coyote.jar:8.5.35]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-coyote.jar:8.5.35]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.35]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.35]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.35]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
06:49:16.199 [http-nio-8081-exec-4] INFO  o.a.g.tunnel.TunnelRequestService - User "10469882-02d2-4968-ab99-01b23b1a4bfa" disconnected from connection "c87b395c-0db9-46ca-8247-d68b294f8b50". Duration: 1021 milliseconds
06:49:16.210 [http-nio-8081-exec-1] INFO  o.a.g.a.j.p.JumpserverPermissionService - getUser:10469882-02d2-4968-ab99-01b23b1a4bfa
06:49:18.621 [Thread-6] INFO  o.a.g.a.j.r.JumpserverRegisterService - 心跳成功{code:201,result:[]}
```

**Comment by wojiushixiaobai** [comment]
@purevita 自动报错表示系统用户的用户或者密码不正确

**Comment by purevita** [comment]
@wojiushixiaobai 
谢谢你的提醒
我原本用户密码有用到空白键，刚试了一下似乎不能使用空白键？
密码改为没有使用空白键自动RDP就成功了
