### ISSUE TITLE
安装时候忘记修改 SECRET_KEY, 使用之后 怎么修改 SECRET_KEY呢？

### ISSUE THREAD

**Issue by xiao-fan** [jumpserver/jumpserver#2085]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
系统用户，管理用户密码等都是由SECRET_KEY加密生成，如果更改，请更新他们的密码

**Comment by xiao-fan** [comment]
现在 配置中  我已经修改了 SECRET_KEY   
  执行  ./jms start all -d

- Start Gunicorn WSGI HTTP Server
Check database structure change ...
2018-11-23 18:19:53 [signals_handler DEBUG] Receive django ready signal
2018-11-23 18:19:53 [signals_handler DEBUG]   - fresh all settings
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 12, in ready
    django_ready.send(self.__class__)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/jumpserver/apps/common/signals_handler.py", line 29, in refresh_all_settings_on_django_ready
    Setting.refresh_all_settings()
  File "/opt/jumpserver/apps/common/models.py", line 75, in refresh_all_settings
    setting.refresh_setting()
  File "/opt/jumpserver/apps/common/models.py", line 80, in refresh_setting
    setattr(settings, self.name, self.cleaned_value)
  File "/opt/jumpserver/apps/common/models.py", line 55, in cleaned_value
    value = json.loads(value)
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'

**Comment by ibuler** [comment]
把 setting表清空

**Comment by xiao-fan** [comment]
> 把 setting表清空

非常感谢
