### ISSUE TITLE
SSH negotiation failed

### ISSUE THREAD

**Issue by Coyote5** [jumpserver/jumpserver#2138]
[简述你的问题]
coco中有报错，但功能可以正常使用。
```
coco_1        | 2018-12-10 17:45:55 [sshd WARNING] SSH negotiation failed
coco_1        | 2018-12-10 17:46:00 [sshd INFO] Get ssh request from 127.0.0.1: 56252
coco_1        | 2018-12-10 17:46:00 [transport ERROR] Exception: Error reading SSH protocol banner
coco_1        | 2018-12-10 17:46:00 [transport ERROR] Traceback (most recent call last):
coco_1        | 2018-12-10 17:46:00 [transport ERROR]   File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 2044, in _check_banner
coco_1        | 2018-12-10 17:46:00 [transport ERROR]     buf = self.packetizer.readline(timeout)
coco_1        | 2018-12-10 17:46:00 [transport ERROR]   File "/opt/py3/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
coco_1        | 2018-12-10 17:46:00 [transport ERROR]     buf += self._read_timeout(timeout)
coco_1        | 2018-12-10 17:46:00 [transport ERROR]   File "/opt/py3/lib/python3.6/site-packages/paramiko/packet.py", line 542, in _read_timeout
coco_1        | 2018-12-10 17:46:00 [transport ERROR]     raise EOFError()
coco_1        | 2018-12-10 17:46:00 [transport ERROR] EOFError
coco_1        | 2018-12-10 17:46:00 [transport ERROR]
coco_1        | 2018-12-10 17:46:00 [transport ERROR] During handling of the above exception, another exception occurred:
coco_1        | 2018-12-10 17:46:00 [transport ERROR]
coco_1        | 2018-12-10 17:46:00 [transport ERROR] Traceback (most recent call last):
coco_1        | 2018-12-10 17:46:00 [transport ERROR]   File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 1893, in run
coco_1        | 2018-12-10 17:46:00 [transport ERROR]     self._check_banner()
coco_1        | 2018-12-10 17:46:00 [transport ERROR]   File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 2049, in _check_banner
coco_1        | 2018-12-10 17:46:00 [transport ERROR]     'Error reading SSH protocol banner' + str(e)
coco_1        | 2018-12-10 17:46:00 [transport ERROR] paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
coco_1        | 2018-12-10 17:46:00 [transport ERROR]
```

##### 使用版本
[Jumpserver版本 1.4.0]

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
正常连接资产了吗？

**Comment by Coyote5** [comment]
资产可以正常连接，使用也没问题。

**Comment by ibuler** [comment]
可能是nginx心跳

**Comment by Coyote5** [comment]
问题的原因找到了，是jumpserver前面LB的心跳包引起的。 @ibuler 请问除了关闭心跳，还有其他方法解决这个问题吗？
