### ISSUE TITLE
Ldap第二次登陆失败，提示重复的username

### ISSUE THREAD

**Issue by xiaojin525** [jumpserver/jumpserver#2163]
[简述你的问题]
Ldap第二次登陆失败，提示重复的username

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.5

##### 问题复现步骤
Ldap第一次可以正常登陆，第二次登陆失败，提示重复的username

##### 具体表现[截图可能会更好些,最好能截全]
日志：
2018-12-13 11:22:57 [backend WARNING] (1062, "Duplicate entry '**' for key 'username'") while authenticating **
2018-12-13 11:22:57 [log ERROR] Internal Server Error: /users/login/
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry '**' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/users/views/login.py", line 65, in post
    return super().post(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/forms.py", line 195, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/jumpserver/apps/authentication/ldap/backends.py", line 21, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 210, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 350, in authenticate
    self._get_or_create_user()
  File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 609, in _get_or_create_user
    populate_user.send(self.backend.__class__, user=self._user, ldap_user=self)
  File "/opt/py3/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/jumpserver/apps/authentication/signals_handlers.py", line 40, in on_ldap_create_user
    user.save()
  File "/opt/jumpserver/apps/users/models/user.py", line 262, in save
    super().save(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 717, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 747, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 830, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 868, in _do_insert
    using=using, raw=raw)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 1133, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '**' for key 'username'")

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@xiaojin525 删除或者修改掉对应的用户，确定username和email唯一，然后继续操作
确定ldap设置无误

**Comment by jym503558564** [comment]
升级至最新版本，看是否问题还存在。

**Comment by ChinaNanSen** [comment]
同样的错误，提示重复的username

**Comment by ChinaNanSen** [comment]
怎么解决的

**Comment by peter1123** [comment]
我也出现同样错误，按如下截图配置即可正常。
http://i2.51cto.com/images/blog/201807/22/1954da4558201ec23c6451e8c1b5008b.png?x-oss-process=image/watermark,size_16,text_QDUxQ1RP5Y2a5a6i,color_FFFFFF,t_100,g_se,x_10,y_10,shadow_90,type_ZmFuZ3poZW5naGVpdGk=

**Comment by peter1123** [comment]
> 
> 
> > @xiaojin525 删除或者修改掉对应的用户，确定username和email唯一，然后继续操作
> > 确定ldap设置无误
> 
> 同样的错误。LDAP连接测试正常，按错误提示应该是LDAP用户登录后会在系统
> 
> > [简述你的问题]
> > Ldap第二次登陆失败，提示重复的username
> > ##### 使用版本
> > [请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
> > 1.4.5
> > ##### 问题复现步骤
> > Ldap第一次可以正常登陆，第二次登陆失败，提示重复的username
> > ##### 具体表现[截图可能会更好些,最好能截全]
> > 日志：
> > 2018-12-13 11:22:57 [backend WARNING] (1062, "Duplicate entry '**' for key 'username'") while authenticating ** 2018-12-13 11:22:57 [log ERROR] Internal Server Error: /users/login/ Traceback (most recent call last): File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute return self.cursor.execute(sql, params) File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute return self.cursor.execute(query, args) File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute self.errorhandler(self, exc, value) File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler raise errorvalue File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute res = self._query(query) File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query db.query(q) File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query _mysql.connection.query(self, query) _mysql_exceptions.IntegrityError: (1062, "Duplicate entry '**' for key 'username'")
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> > response = get_response(request)
> > File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
> > response = self.process_exception_by_middleware(e, request)
> > File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
> > response = wrapped_callback(request, *callback_args, **callback_kwargs)
> > File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
> > return func(*args, **kwds)
> > File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
> > return self.dispatch(request, *args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
> > return bound_method(*args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
> > return view(request, *args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
> > return bound_method(*args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
> > response = view_func(request, *args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
> > return bound_method(*args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
> > response = view_func(request, *args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
> > return handler(request, *args, **kwargs)
> > File "/opt/jumpserver/apps/users/views/login.py", line 65, in post
> > return super().post(request, *args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
> > if form.is_valid():
> > File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
> > return self.is_bound and not self.errors
> > File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 180, in errors
> > self.full_clean()
> > File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
> > self._clean_form()
> > File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
> > cleaned_data = self.clean()
> > File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/forms.py", line 195, in clean
> > self.user_cache = authenticate(self.request, username=username, password=password)
> > File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/**init**.py", line 73, in authenticate
> > user = backend.authenticate(request, **credentials)
> > File "/opt/jumpserver/apps/authentication/ldap/backends.py", line 21, in authenticate
> > user = self.authenticate_ldap_user(ldap_user, password)
> > File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 210, in authenticate_ldap_user
> > return ldap_user.authenticate(password)
> > File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 350, in authenticate
> > self._get_or_create_user()
> > File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 609, in _get_or_create_user
> > populate_user.send(self.backend.**class**, user=self._user, ldap_user=self)
> > File "/opt/py3/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
> > for receiver in self._live_receivers(sender)
> > File "/opt/py3/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in
> > for receiver in self._live_receivers(sender)
> > File "/opt/jumpserver/apps/authentication/signals_handlers.py", line 40, in on_ldap_create_user
> > user.save()
> > File "/opt/jumpserver/apps/users/models/user.py", line 262, in save
> > super().save(*args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
> > super().save(*args, **kwargs)
> > File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 717, in save
> > force_update=force_update, update_fields=update_fields)
> > File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 747, in save_base
> > updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
> > File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 830, in _save_table
> > result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
> > File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 868, in _do_insert
> > using=using, raw=raw)
> > File "/opt/py3/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
> > return getattr(self.get_queryset(), name)(*args, **kwargs) File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 1133, in _insert return query.get_compiler(using=using).execute_sql(return_id) File "/opt/py3/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql cursor.execute(sql, params) File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers return executor(sql, params, many, context) File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute return self.cursor.execute(sql, params) File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in **exit** raise dj_exc_value.with_traceback(traceback) from exc_value File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute return self.cursor.execute(sql, params) File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute return self.cursor.execute(query, args) File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute self.errorhandler(self, exc, value) File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler raise errorvalue File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute res = self._query(query) File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query db.query(q) File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query _mysql.connection.query(self, query) django.db.utils.IntegrityError: (1062, "Duplicate entry '**' for key 'username'")
> > ##### 其他
> > [注:] 完成后请关闭 issue
> 
> 我也出现同样错误，按如下截图配置即可正常。
> http://i2.51cto.com/images/blog/201807/22/1954da4558201ec23c6451e8c1b5008b.png?x-oss-process=image/watermark,size_16,text_QDUxQ1RP5Y2a5a6i,color_FFFFFF,t_100,g_se,x_10,y_10,shadow_90,type_ZmFuZ3poZW5naGVpdGk=

亲测有效！
