### ISSUE TITLE
1.4.4 升级到1.4.5失败

### ISSUE THREAD

**Issue by dishuihengxin** [jumpserver/jumpserver#2166]
[简述你的问题]
1.4.4 升级到1.4.5失败

##### 使用版本
[1.4.4] 升级前的版本

##### 问题复现步骤
1. [步骤1]
按照文档从1.4.0成功升级至1.4.4后，升级到1.4.5过程中`sh make_migrations.sh`报错
```
 sh make_migrations.sh 

2018-12-13 17:18:22 [signals_handler DEBUG] Receive django ready signal
2018-12-13 17:18:22 [signals_handler DEBUG]   - fresh all settings
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 12, in ready
    django_ready.send(self.__class__)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/jumpserver/apps/common/signals_handler.py", line 61, in refresh_all_settings_on_django_ready
    Setting.refresh_all_settings()
  File "/opt/jumpserver/apps/common/models.py", line 106, in refresh_all_settings
    setting.refresh_setting()
  File "/opt/jumpserver/apps/common/models.py", line 111, in refresh_setting
    setattr(settings, self.name, self.cleaned_value)
  File "/opt/jumpserver/apps/common/models.py", line 50, in cleaned_value
    value = json.loads(value)
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
2018-12-13 17:18:24 [signals_handler DEBUG] Receive django ready signal
2018-12-13 17:18:24 [signals_handler DEBUG]   - fresh all settings
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 12, in ready
    django_ready.send(self.__class__)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/jumpserver/apps/common/signals_handler.py", line 61, in refresh_all_settings_on_django_ready
    Setting.refresh_all_settings()
  File "/opt/jumpserver/apps/common/models.py", line 106, in refresh_all_settings
    setting.refresh_setting()
  File "/opt/jumpserver/apps/common/models.py", line 111, in refresh_setting
    setattr(settings, self.name, self.cleaned_value)
  File "/opt/jumpserver/apps/common/models.py", line 50, in cleaned_value
    value = json.loads(value)
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
2018-12-13 17:18:25 [signals_handler DEBUG] Receive django ready signal
2018-12-13 17:18:25 [signals_handler DEBUG]   - fresh all settings
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 12, in ready
    django_ready.send(self.__class__)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/jumpserver/apps/common/signals_handler.py", line 61, in refresh_all_settings_on_django_ready
    Setting.refresh_all_settings()
  File "/opt/jumpserver/apps/common/models.py", line 106, in refresh_all_settings
    setting.refresh_setting()
  File "/opt/jumpserver/apps/common/models.py", line 111, in refresh_setting
    setattr(settings, self.name, self.cleaned_value)
  File "/opt/jumpserver/apps/common/models.py", line 50, in cleaned_value
    value = json.loads(value)
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'

```
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@dishuihengxin 请严格按照文档进行升级，再不清楚相关的设置之前，请按照说明进行修改

**Comment by devops007** [comment]
按照以前的方法就可以：
1. 执行clean_migrations.sh 清空迁移文件
2. 拷贝1.4.4的migrations文件到1.4.5
3. 执行 make_migrations.sh

1.4.6也是同样的办法，从1.4.5目录升级。
