### ISSUE TITLE
运行make_migrations.sh报错导致无法升级Jumpserver

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#2167]
[简述你的问题]

Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/data0/jumpserver/jumpserver/apps/common/apps.py", line 12, in ready
    django_ready.send(self.__class__)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/data0/jumpserver/jumpserver/apps/common/signals_handler.py", line 61, in refresh_all_settings_on_django_ready
    Setting.refresh_all_settings()
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 106, in refresh_all_settings
    setting.refresh_setting()
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 111, in refresh_setting
    setattr(settings, self.name, self.cleaned_value)
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 50, in cleaned_value
    value = json.loads(value)
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/data0/jumpserver/jumpserver/apps/common/apps.py", line 12, in ready
    django_ready.send(self.__class__)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/data0/jumpserver/jumpserver/apps/common/signals_handler.py", line 61, in refresh_all_settings_on_django_ready
    Setting.refresh_all_settings()
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 106, in refresh_all_settings
    setting.refresh_setting()
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 111, in refresh_setting
    setattr(settings, self.name, self.cleaned_value)
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 50, in cleaned_value
    value = json.loads(value)
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/data0/jumpserver/jumpserver/apps/common/apps.py", line 12, in ready
    django_ready.send(self.__class__)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/data0/jumpserver/jumpserver/apps/common/signals_handler.py", line 61, in refresh_all_settings_on_django_ready
    Setting.refresh_all_settings()
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 106, in refresh_all_settings
    setting.refresh_setting()
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 111, in refresh_setting
    setattr(settings, self.name, self.cleaned_value)
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 50, in cleaned_value
    value = json.loads(value)
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.5
##### 问题复现步骤
1. 按照文档进行操作时就会报错

##### 其他

[注:] 完成后请关闭 issue

**Comment by bigbird1985** [comment]
# SECURITY WARNING: keep the secret key used in production secret!
    # 加密秘钥 生产环境中请修改为随机字符串，请勿外泄
    SECRET_KEY = '2vym+ky!997d5kkcc64mnz06y1mmui3lut#(^wd=%s_qj$1%x'

    # Django security setting, if your disable debug model, you should setting that
    **### ALLOWED_HOSTS = ['*']**

    # SECURITY WARNING: keep the bootstrap token used in production secret!
    # 预共享Token coco和guacamole用来注册服务账号，不在使用原来的注册接受机制
    BOOTSTRAP_TOKEN = 'nwv4RdXpM82LtSvmV'

**Comment by RaynorAZ** [comment]
秘钥和token添加以后启动的时候报错
Check database connection ...
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/commands/showmigrations.py", line 45, in handle
    return self.show_list(connection, options['app_label'])
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/commands/showmigrations.py", line 61, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/loader.py", line 270, in build_graph
    raise exc
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/loader.py", line 244, in build_graph
    self.graph.validate_consistency()
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/graph.py", line 243, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/graph.py", line 243, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/graph.py", line 96, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration users.0003_auto_20180101_0046 dependencies reference nonexistent parent node ('users', '0002_auto_20171225_1157')

**Comment by wojiushixiaobai** [comment]
@bigbird1985  严格按照文档进行安装。

@RaynorAZ  升级失败看请升级失败的faq文档

**Comment by RaynorAZ** [comment]
> @bigbird1985 严格按照文档进行安装。
> 
> @RaynorAZ 升级失败看请升级失败的faq文档

Check database connection ...
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/data0/jumpserver/jumpserver/apps/common/apps.py", line 12, in ready
    django_ready.send(self.__class__)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/data0/jumpserver/jumpserver/apps/common/signals_handler.py", line 61, in refresh_all_settings_on_django_ready
    Setting.refresh_all_settings()
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 106, in refresh_all_settings
    setting.refresh_setting()
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 111, in refresh_setting
    setattr(settings, self.name, self.cleaned_value)
  File "/data0/jumpserver/jumpserver/apps/common/models.py", line 50, in cleaned_value
    value = json.loads(value)
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'dict'


按照FAQ操作，导入数据后依然出现报错

**Comment by wojiushixiaobai** [comment]
@RaynorAZ 执行命令的记录记录发一下，注意脱敏

**Comment by RaynorAZ** [comment]
795  mysqldump -uroot -p jumpserver --ignore-table=jumpserver.django_migrations > jumpserver.sql
  796  cd ..
  797  ls
  798  mv jumpserver jumpserver.bak
  799  git clone https://github.com/jumpserver/jumpserver.git
  800  yum install -y $(cat requirements/rpm_requirements.txt)
  801  yum -y install $(cat /data0/jumpserver/jumpserver/requirements/rpm_requirements.txt)
  802  pip install --upgrade pip setuptools
  803  cd jumpserver
  804  ls
  805  pip install -r requirements/requirements.txt 
  806  mysql
  807  ls
  808  cp ../jumpserver.bak/config.py ./
  809  vim config.py 
  810  cd utils/
  811  ls
  812  sh make_migrations.sh 
  813  扯淡..
  814  cd ..
  815  ls
  816  cd ..
  817  ls
  818  cd jumpserver.bak/
  819  ls
  820  cd apps/
  821  ls
  822  cd ..
  823  ls
  824  pwd
  825  mysql
  826  ls
  827  cd ..
  828  ls
  829  cd jumpserver
  830  ls
  831  ./jms start all -d

**Comment by RaynorAZ** [comment]
mysql中的操作就是按照FAQ里的进行的。
> create database jumpserver01 default charset 'utf8';
> grant all on jumpserver01.* to 'jumpserver01'@'127.0.0.1' identified by 'weakPassword';
> flush privileges;
> quit

> use jumpserver01;
> source /opt/jumpserver.sql

**Comment by wojiushixiaobai** [comment]
@RaynorAZ 
# 一定要知道自己升级之前的版本, 在升级之前可以通过如下代码进行查询, 记住是升级之前, 也可以通过 web 页面的右下角来查看当前版本信息
$ cat /opt/jumpserver/apps/__init__.py | grep version
$ cat /opt/jumpserver/apps/templates/_footer.html | grep Version

    # 备份当前版本数据库, 忽略 django_migrations 表
$ mysqldump -uroot -p jumpserver --ignore-table=jumpserver.django_migrations > /opt/jumpserver.sql

    # 重命名 Jumpserver 目录
$ mv /opt/jumpserver /opt/jumpserver_bak

    # 重新 clone 代码
$ cd /opt
$ git clone https://github.com/jumpserver/jumpserver.git
$ cd jumpserver

# 检出你之前的版本, 比如之前的版本是1.4.0
$ git checkout 1.4.0  # 1.4.0 表示版本号, 自己手动更换成你当前的版本, 如 1.3.1 则输入 git checkout 1.3.1

    # 依赖安装
$ source /opt/py3/bin/activate
$ yum -y install $(cat /opt/jumpserver/requirements/rpm_requirements.txt)
$ pip install --upgrade pip setuptools
$ pip install -r /opt/jumpserver/requirements/requirements.txt

# 重新创建一个数据库
$ mysql -uroot
> create database jumpserver01 default charset 'utf8';
> grant all on jumpserver01.* to 'jumpserver01'@'127.0.0.1' identified by 'weakPassword';
> flush privileges;
> quit

# 修改配置文件
$ cp /opt/jumpserver_bak/config.py /opt/jumpserver/
$ vim /opt/jumpserver/config.py
DB_ENGINE = 'mysql'
DB_HOST = '127.0.0.1'
DB_PORT = 3306
DB_USER = 'jumpserver01'
DB_PASSWORD = 'weakPassword'
DB_NAME = 'jumpserver01'

# 初始化数据库
$ cd /opt/jumpserver/utils
$ sh make_migrations.sh

# 确定初始化没有错误, 把旧的数据库导入
$ mysql -uroot
> use jumpserver01;
> source /opt/jumpserver.sql

# 启动 jumpserver, 确定没有错误
$ cd /opt/jumpserver
$ ./jms start all

# 打开 web 页面检查是否都正常

$ 参考升级文档继续升级到最新版本即可

    # 删除原数据库命令
$ mysql -uroot
> drop database jumpserver;
> quit

**Comment by RaynorAZ** [comment]
升级之前的版本就是1.4.5的
__version__ = "1.4.5"

**Comment by wojiushixiaobai** [comment]
@RaynorAZ 如何升级到1.4.5的，升级流程说一下

**Comment by RaynorAZ** [comment]
升级之前的版本是1.4.4的。我测试环境和线上环境是一致的。

**Comment by wojiushixiaobai** [comment]
@RaynorAZ 升级过程执行的命令截图

**Comment by RaynorAZ** [comment]
![image](https://user-images.githubusercontent.com/42203736/49988312-38adab00-ffb1-11e8-99c1-2e1257cb5805.png)

**Comment by wojiushixiaobai** [comment]
@RaynorAZ 升级过程不正确，你执行sh make_migrations.sh 会出现警告才对

**Comment by RaynorAZ** [comment]
执行 make_migrations.sh的报错就是之前我贴的最上层的内容了。
![image](https://user-images.githubusercontent.com/42203736/49988492-dbfec000-ffb1-11e8-997d-8213ff153b36.png)

**Comment by wojiushixiaobai** [comment]
@RaynorAZ 看我上面的回复，你的升级有问题

**Comment by bigbird1985** [comment]
@RaynorAZ  我的意思是: 记得加上这个参数, config_example里默认没有这个. 加上就可以了.
#记得设置这个参数
ALLOWED_HOSTS = ['*']

**Comment by RaynorAZ** [comment]
users_user.date_password_last_updated

**Comment by huangzx** [comment]
我也碰到这个问题，1.4.4 升级到 1.4.5

(1054, "Unknown column 'users_user.date_password_last_updated' in 'field list'")

**Comment by BackFire** [comment]
我这边从1.4.4升级到1.4.5也遇到问题
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration audits.0004_operatelog_passwordchangelo
g_userloginlog is applied before its dependency users.0014_auto_20180816_1652 on database 'default'.

**Comment by RaynorAZ** [comment]
@wojiushixiaobai @ibuler 是否可以通过在users_user表里增加date_password_last_updated 来实现升级？

**Comment by RaynorAZ** [comment]
我目前1.4.4的版本通过users_user表里增加date_password_last_updated这个字段，然后默认给这个字段一个赋值之后可以正常运行1.4.5和1.4.6了。麻烦确认下这样的可行性吧

**Comment by devops007** [comment]
按照以前的方法就可以，我试验后是可行的：

执行clean_migrations.sh 清空迁移文件
拷贝1.4.4的migrations文件到1.4.5
执行 make_migrations.sh
1.4.6也是同样的办法，从1.4.5目录升级。
