### ISSUE TITLE
pip install -r requirements.txt 报错

### ISSUE THREAD

**Issue by yuynagforhacker** [jumpserver/jumpserver#2171]
你好
      我在安装py依赖的时候报错
```
Using cached https://files.pythonhosted.org/packages/a4/9e/648b4e85235097edcee561c986f7075cb1606be24c514cfcdd2930e35c5e/python-gssapi-0.6.4.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no previously-included files found matching 'setup.pyc'
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'

No package 'gss' found
gssapi/bindings/__pycache__/_cffi__x8e012de6x6c820412.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__xf223bac3xa79bfeef.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__xb3bc6629xdba4f2a1.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__xeb514d6x5d98e1c3.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__x67999e0x2a0d7c22.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__x680d8754xa883e720.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__x3116e390xdc4bc63b.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__x605c8c53xc4f5555d.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__xeb98ca96x39d25428.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__x9da3f28cxf7292814.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__x71c8306cx52487aa4.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__xcb5bccdbx18251cfe.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    gssapi/bindings/__pycache__/_cffi__xaa59ba48xdb9bd1d2.c:212:27: 致命错误：gssapi/gssapi.h：没有那个文件或目录
     #include <gssapi/gssapi.h>
                               ^
    编译中断。
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
        extra_postargs)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-yyv83nw_/python-gssapi/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 51, in _build
        dist.run_command('build_ext')
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yyv83nw_/python-gssapi/setup.py", line 74, in <module>
        url="https://github.com/sigmaris/python-gssapi",
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib64/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/build_py.py", line 34, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/lib64/python3.6/distutils/command/build_py.py", line 45, in finalize_options
        ('force', 'force'))
      File "/usr/lib64/python3.6/distutils/cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/lib64/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-yyv83nw_/python-gssapi/setup.py", line 22, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "/tmp/pip-install-yyv83nw_/python-gssapi/setup.py", line 15, in get_ext_modules
        from gssapi.bindings import ffi
      File "/tmp/pip-install-yyv83nw_/python-gssapi/gssapi/__init__.py", line 4, in <module>
        from . import bindings
      File "/tmp/pip-install-yyv83nw_/python-gssapi/gssapi/bindings/__init__.py", line 233, in <module>
        C = ffi.verify(_source, **_kwargs)
      File "/tmp/pip-install-yyv83nw_/python-gssapi/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/api.py", line 451, in verify
        lib = self.verifier.load_library()
      File "/tmp/pip-install-yyv83nw_/python-gssapi/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/verifier.py", line 104, in load_library
        self._compile_module()
      File "/tmp/pip-install-yyv83nw_/python-gssapi/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/verifier.py", line 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/tmp/pip-install-yyv83nw_/python-gssapi/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 22, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "/tmp/pip-install-yyv83nw_/python-gssapi/.eggs/cffi-1.11.5-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 58, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yyv83nw_/python-gssapi/
```
系统环境centos7.4   python3.6.6
以上为参考手册安装

**Comment by wojiushixiaobai** [comment]
@yuynagforhacker 请完整的参考文档进行测试。

**Comment by guoxu3** [comment]
@yuynagforhacker  yum install -y krb5-devel

**Comment by cw4t** [comment]
我也遇到这个问题，pip 安装 requirements里的python-gssapi==0.6.4 的时候卡住了。。装了好几遍了。希望能帮忙解答下，感激不尽！！！

**Comment by wuennan** [comment]
> 我也遇到这个问题，pip 安装 requirements里的python-gssapi==0.6.4 的时候卡住了。。装了好几遍了。希望能帮忙解答下，感激不尽！！！

遇到了相同的问题，请问您是否已经解决

**Comment by cw4t** [comment]
yiji

> > 我也遇到这个问题，pip 安装 requirements里的python-gssapi==0.6.4 的时候卡住了。。装了好几遍了。希望能帮忙解答下，感激不尽！！！
> 
> 遇到了相同的问题，请问您是否已经解决

已经解决了，豆瓣源可以装
