### ISSUE TITLE
安装出现了问题

### ISSUE THREAD

**Issue by HeiZheJun** [jumpserver/jumpserver#2396]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.4.7
##### 问题复现步骤
1. [步骤1]
按着安装步骤一步一步来的，没有错误
2. [步骤2]
在运行jumpserver的时候出现了报错
##### 具体表现[截图可能会更好些,最好能截全]
截图上传不上来，我直接贴报错代码了
Thu Feb 14 20:29:40 2019
Jumpserver version 1.4.7, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
Check database connection ...
users
 [ ] 0001_initial
 [ ] 0002_auto_20171225_1157
 [ ] 0003_auto_20180101_0046
 [ ] 0004_auto_20180125_1218
 [ ] 0005_auto_20180306_1804
 [ ] 0006_auto_20180411_1135
 [ ] 0007_auto_20180419_1036
 [ ] 0008_auto_20180425_1516
 [ ] 0009_auto_20180517_1537
 [ ] 0010_auto_20180606_1505
 [ ] 0011_user_source
 [ ] 0012_auto_20180710_1641
 [ ] 0013_auto_20180807_1116
 [ ] 0014_auto_20180816_1652
 [ ] 0015_auto_20181105_1112
 [ ] 0016_auto_20181109_1505
 [ ] 0017_auto_20181123_1113
 [ ] 0018_auto_20190107_1912
Database connect success
Check database structure change ...
Migrate model change to database ...
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/2.1/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: admin, assets, audits, auth, captcha, common, contenttypes, django_celery_beat, ops, orgs, perms, sessions, terminal, users
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1050, "Table 'django_content_type' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/operations/models.py", line 91, in database_forwards
    schema_editor.create_model(model)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 312, in create_model
    self.execute(sql, params or None)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'django_content_type' already exists")
Collect static files

0 static files copied to '/opt/jumpserver/data/static', 550 unmodified.

- Start Celery as Distributed Task Queue

- Start Beat as Periodic Task Scheduler
Error: beat start error
Stop service: gunicorn
Stop service: celery
beat is stopped

##### 其他

[注:] 完成后请关闭 issue

**Comment by HeiZheJun** [comment]
![qq 20190215142201](https://user-images.githubusercontent.com/40173996/52838289-19580900-312d-11e9-88b6-117351ddf12f.png)

**Comment by HeiZheJun** [comment]
![qq 20190215140545](https://user-images.githubusercontent.com/40173996/52838297-1fe68080-312d-11e9-8956-c5b9824272d0.png)

**Comment by HeiZheJun** [comment]
![qq 20190215140731](https://user-images.githubusercontent.com/40173996/52838309-27a62500-312d-11e9-8236-898ce09f8ac0.png)

**Comment by ibuler** [comment]
删掉 django_content_type表试试

**Comment by HeiZheJun** [comment]
删掉django_content_type表没有任何作用

**Comment by HeiZheJun** [comment]
删掉django_content_type表没有任何作用

**Comment by 17634369935** [comment]
解决了吗
