### ISSUE TITLE
JumpServer 插入数据至mysql错误

### ISSUE THREAD

**Issue by vipsql** [jumpserver/jumpserver#2698]
[简述你的问题]

##### 使用版本
1.5.4-2

##### 问题复现步骤
后台抛错日志:
Traceback (most recent call last):
  File "/mnt/data1/bigdata/jumpserver/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/mnt/data1/bigdata/jumpserver/env/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/mnt/data1/bigdata/jumpserver/env/lib64/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/mnt/data1/bigdata/jumpserver/env/lib64/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/mnt/data1/bigdata/jumpserver/env/lib64/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/mnt/data1/bigdata/jumpserver/env/lib64/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/mnt/data1/bigdata/jumpserver/env/lib64/python3.6/site-packages/mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1366, "Incorrect string value: '\\xF2\\xA7\\x83\\xAC\\xEF\\xBF...' for column 'output' at row 1")

The above exception was the direct cause of the following exception:

**Comment by jym503558564** [comment]
1.mysql版本？
2.修改数据库表格的字符编码为utf-8

**Comment by vipsql** [comment]
mysql版本为: 5.7
数据编码默认为为utf-8

**Comment by jym503558564** [comment]
在插入什么数据的时候报这个错，能否复现，截图一下？

**Comment by jym503558564** [comment]
问题是否已解决？如果还存在，请详细说明在插入什么数据报错，以及完整的错误信息

**Comment by ibuler** [comment]
已处理
