### ISSUE TITLE
1.4.10-2 LDAP 配置成功，LDAP 用户无法登录

### ISSUE THREAD

**Issue by ontherd** [jumpserver/jumpserver#2712]
[简述你的问题]
JumpServer 里配置公司的 AD 域，在配置测试能成功获取域账户，使用域账户初次登录 jumpserver 时，会成功登录并完善用户属性引导。
然后，
退出再次使用已注册过的 AD 域账户登录JumpServer，报错如下：

Exception Value: | (1062, "Duplicate entry 'xxx' for key 'username'")

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
Version 1.4.10-2 GPLv2.

##### 问题复现步骤
1. [使用admin 管理账户登录 jumpserver 并配置AD域控]
![image](https://user-images.githubusercontent.com/21536855/58078767-182df080-7be2-11e9-8e95-cd91e29e7b16.png)

2. [使用域账户初次登录JumpServer]
![image](https://user-images.githubusercontent.com/21536855/58078866-4e6b7000-7be2-11e9-94d7-649d2158567c.png)
##### 用户信息补充完成后
![image](https://user-images.githubusercontent.com/21536855/58078955-84a8ef80-7be2-11e9-81ff-a57b4911b723.png)

3. [使用已完成的域账号再次登录jumpserver]
![image](https://user-images.githubusercontent.com/21536855/58078998-9e4a3700-7be2-11e9-85bb-183adf012ac0.png)

##### 其他
这套域配置信息，我在版本 1.4.1 中是正常的。

[注:] 完成后请关闭 issue

**Comment by ontherd** [comment]
后台日志报错：
jms             | 2019-05-21 16:11:52 [ldap INFO] Authentication LDAP backend
jms             | 2019-05-21 16:11:53 [backend WARNING] (1062, "Duplicate entry 'xxxx' for key 'username'") while authenticating xxxx
jms             | 2019-05-21 16:11:53 [log ERROR] Internal Server Error: /auth/login/
jms             | Traceback (most recent call last):
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
jms             |     return self.cursor.execute(sql, params)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
jms             |     return self.cursor.execute(query, args)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
jms             |     self.errorhandler(self, exc, value)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
jms             |     raise errorvalue
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
jms             |     res = self._query(query)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
jms             |     db.query(q)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
jms             |     _mysql.connection.query(self, query)
jms             | _mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'xxxx' for key 'username'")
jms             | 
jms             | The above exception was the direct cause of the following exception:
jms             | 
jms             | Traceback (most recent call last):
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
jms             |     response = get_response(request)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
jms             |     response = self.process_exception_by_middleware(e, request)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
jms             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
jms             |   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
jms             |     return func(*args, **kwds)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
jms             |     return self.dispatch(request, *args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
jms             |     return bound_method(*args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
jms             |     return view(request, *args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
jms             |     return bound_method(*args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
jms             |     response = view_func(request, *args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
jms             |     return bound_method(*args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
jms             |     response = view_func(request, *args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
jms             |     return handler(request, *args, **kwargs)
jms             |   File "/opt/jumpserver/apps/authentication/views/login.py", line 76, in post
jms             |     return super().post(request, *args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
jms             |     if form.is_valid():
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
jms             |     return self.is_bound and not self.errors
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 180, in errors
jms             |     self.full_clean()
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
jms             |     self._clean_form()
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
jms             |     cleaned_data = self.clean()
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/forms.py", line 196, in clean
jms             |     self.user_cache = authenticate(self.request, username=username, password=password)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
jms             |     user = backend.authenticate(request, **credentials)
jms             |   File "/opt/jumpserver/apps/authentication/backends/ldap.py", line 24, in authenticate
jms             |     user = self.authenticate_ldap_user(ldap_user, password)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 210, in authenticate_ldap_user
jms             |     return ldap_user.authenticate(password)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 350, in authenticate
jms             |     self._get_or_create_user()
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 609, in _get_or_create_user
jms             |     populate_user.send(self.backend.__class__, user=self._user, ldap_user=self)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
jms             |     for receiver in self._live_receivers(sender)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
jms             |     for receiver in self._live_receivers(sender)
jms             |   File "/opt/jumpserver/apps/authentication/signals_handlers.py", line 53, in on_ldap_create_user
jms             |     user.save()
jms             |   File "/opt/jumpserver/apps/users/models/user.py", line 291, in save
jms             |     super().save(*args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
jms             |     super().save(*args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 718, in save
jms             |     force_update=force_update, update_fields=update_fields)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
jms             |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
jms             |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
jms             |     using=using, raw=raw)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
jms             |     return getattr(self.get_queryset(), name)(*args, **kwargs)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
jms             |     return query.get_compiler(using=using).execute_sql(return_id)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
jms             |     cursor.execute(sql, params)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
jms             |     return super().execute(sql, params)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
jms             |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
jms             |     return executor(sql, params, many, context)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
jms             |     return self.cursor.execute(sql, params)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
jms             |     raise dj_exc_value.with_traceback(traceback) from exc_value
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
jms             |     return self.cursor.execute(sql, params)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
jms             |     return self.cursor.execute(query, args)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
jms             |     self.errorhandler(self, exc, value)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
jms             |     raise errorvalue
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
jms             |     res = self._query(query)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
jms             |     db.query(q)
jms             |   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
jms             |     _mysql.connection.query(self, query)
jms             | django.db.utils.IntegrityError: (1062, "Duplicate entry 'xxxx' for key 'username'")
jms             | 172.19.0.1 [21/May/2019:16:12:04 +0800] "POST /api/terminal/v1/terminal/status/ HTTP/1.1" 201 2
