### ISSUE TITLE
资产分组备注中有中文时，在 ssh 后输入 g 出现报错并退出

### ISSUE THREAD

**Issue by zxing0214** [jumpserver/jumpserver#275]
报错内容：

```
Traceback (most recent call last):
  File "/opt/jumpserver/connect.py", line 813, in <module>
    main()
  File "/opt/jumpserver/connect.py", line 787, in main
    nav.print_asset_group()
  File "/opt/jumpserver/connect.py", line 569, in print_asset_group
    print '[%-3s] %-15s %s' % (asset_group.id, asset_group.name, asset_group.comment)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-24: ordinal not in range(128)
```

经过测试，资产组的备注中出现中文会出现这个问题，英文备注没有问题。

**Comment by jiaxiangkong** [comment]
我这边测试不会报错
![Uploading 1.png…]()

**Comment by zxing0214** [comment]
我这里修改了下 /opt/jumpserver/init.sh 文件中的 LANG 为 en_US.UTF-8。测试中文也不会报错了。
