### ISSUE TITLE
连接Window资产失败，日志提示上传录像失败

### ISSUE THREAD

**Issue by yanzhang78** [jumpserver/jumpserver#2750]
[简述你的问题]
连接windows资产失败，guacamole应用日志：
2019-05-29 16:21:07.071 [Thread-305] ERROR o.a.g.a.j.s.JumpserverSessionService - 上传录像失败
java.lang.RuntimeException: 上传录像失败: {code:404,result:{"detail":"未找到。"}}
        at org.apache.guacamole.auth.jumpserver.session.JumpserverSessionService.uploadServer(JumpserverSessionService.java:230) [guacamole-auth-jumpserver-0.9.14.jar:na]
        at org.apache.guacamole.auth.jumpserver.session.JumpserverSessionService.uploadSessionRecord(JumpserverSessionService.java:373) [guacamole-auth-jumpserver-0.9.14.jar:na]
        at org.apache.guacamole.auth.jumpserver.session.JumpserverSessionService.lambda$null$0(JumpserverSessionService.java:59) [guacamole-auth-jumpserver-0.9.14.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
2019-05-29 16:21:07.072 [Thread-306] ERROR o.a.g.a.j.s.JumpserverSessionService - 更新Session失败: {code:404,result:{"detail":"未找到。"}}

##### 使用版本
[1.4.9]

**Comment by wojiushixiaobai** [comment]
@yanzhang78 等待修复
