### ISSUE TITLE
Docker启动Mysql环境报错 argument 3 must be str, not int

### ISSUE THREAD

**Issue by bobt2018** [jumpserver/jumpserver#2811]
[简述你的问题]

##### 使用版本
Jumpserver ALL 1.4.8

##### 问题复现步骤
1. 生成随机加密秘钥, 勿外泄
$ if [ "$SECRET_KEY" = "" ]; then SECRET_KEY=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 50`; echo "SECRET_KEY=$SECRET_KEY" >> ~/.bashrc; echo $SECRET_KEY; else echo $SECRET_KEY; fi
$ if [ "$BOOTSTRAP_TOKEN" = "" ]; then BOOTSTRAP_TOKEN=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 16`; echo "BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN" >> ~/.bashrc; echo $BOOTSTRAP_TOKEN; else echo $BOOTSTRAP_TOKEN; fi

2.外置数据库
docker run --name jms_all -d \
    -v /opt/mysql:/var/lib/mysql \
    -v /opt/jumpserver:/opt/jumpserver/data/media \
    -p 80:80 \
    -p 2222:2222 \
    -e SECRET_KEY=$SECRET_KEY \
    -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN \
    -e DB_HOST=192.168.69.12 \
    -e DB_PORT=3306 \
    -e DB_USER=root \
    -e DB_PASSWORD=123456789 \
    -e DB_NAME=jumpserver \
    jumpserver/jms_all:1.4.8

##### 其他
1.报错日志
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib64/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 12, in ready
    django_ready.send(self.__class__)
  File "/opt/py3/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/opt/py3/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/opt/jumpserver/apps/common/signals_handler.py", line 64, in monkey_patch_settings
    Setting.refresh_all_settings()
  File "/opt/jumpserver/apps/common/models.py", line 107, in refresh_all_settings
    for setting in settings_list:
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    cursor = self.connection.cursor()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: connect() argument 3 must be str, not int

2.内存足够
3.DB_PASSWORD改为字符串没用

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@bobt2018 数据库密码不要使用纯数字，使用外置数据库使用下面shell
````
$ docker run --name jms_all -d -p 80:80 -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e DB_HOST=192.168.69.12 -e DB_PORT=3306 -e DB_USER=root -e DB_PASSWORD=数据库密码 -e DB_NAME=jumpserver jumpserver/jms_all:1.4.8

**Comment by bobt2018** [comment]
> @bobt2018 数据库密码不要使用纯数字，使用外置数据库使用下面shell
> 
> ```
> $ docker run --name jms_all -d -p 80:80 -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e DB_HOST=192.168.69.12 -e DB_PORT=3306 -e DB_USER=root -e DB_PASSWORD=数据库密码 -e DB_NAME=jumpserver jumpserver/jms_all:1.4.8
> ```

问题已解决，数据库改为字母+数字就可以了，thx
