### ISSUE TITLE
推送系统用户 定期更新资产硬件信息时会报错

### ISSUE THREAD

**Issue by onchiao** [jumpserver/jumpserver#2844]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.0

##### 具体表现[截图可能会更好些,最好能截全]

2019-06-24 16:55:00 [adhoc WARNING] Failed run adhoc 定期更新资产硬件信息, Inventory is empty.
2019-06-24 16:55:00 [adhoc ERROR] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/data/jumpserver/apps/ops/models/adhoc.py", line 224, in _run_and_record
    raw, summary = self._run_only()
TypeError: 'NoneType' object is not iterable
2019-06-25 10:49:08 [log WARNING] Unauthorized: /api/users/v1/auth/
2019-06-25 16:55:00 [adhoc WARNING] Failed run adhoc 定期更新资产硬件信息, Inventory is empty.
2019-06-25 16:55:00 [adhoc ERROR] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/data/jumpserver/apps/ops/models/adhoc.py", line 224, in _run_and_record
    raw, summary = self._run_only()
TypeError: 'NoneType' object is not iterable
2019-06-26 14:38:14 [tasks ERROR] 获取资产信息失败：xxxxxx
2019-06-26 14:39:50 [log WARNING] Not Found: /favicon.ico
2019-06-26 15:11:03 [log WARNING] Not Found: /favicon.ico
2019-06-26 15:39:31 [adhoc WARNING] Failed run adhoc 推送系统用户到入资产: xxx SoftTimeLimitExceeded()
2019-06-26 15:39:31 [adhoc ERROR] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/data/jumpserver/apps/ops/models/adhoc.py", line 224, in _run_and_record
    raw, summary = self._run_only()
TypeError: 'NoneType' object is not iterable
2019-06-26 15:45:34 [log WARNING] Unauthorized: /api/users/v1/auth/
2019-06-26 15:45:47 [adhoc WARNING] Failed run adhoc 推送系统用户到入资产: xxxxx, SoftTimeLimitExceeded()
2019-06-26 15:45:47 [adhoc ERROR] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/data/jumpserver/apps/ops/models/adhoc.py", line 224, in _run_and_record
    raw, summary = self._run_only()
TypeError: 'NoneType' object is not iterable

[注:] 完成后请关闭 issue

**Comment by linux-luzhihang** [comment]
我也遇到额这个问题。求大神解答。
