### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by wangjunking** [jumpserver/jumpserver#2868]
[简述你的问题]

##### 使用版本
1.3.3

##### 问题复现步骤
1. 网页登录提示Server Error (500)

报错：[exception ERROR] Internal Server Error: /users/login/
Traceback (most recent call last):
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/jumpserver/jumpserver/apps/users/views/login.py", line 73, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/usr/local/jumpserver/jumpserver/apps/users/views/login.py", line 80, in form_valid
    return redirect(self.get_success_url())
  File "/usr/local/jumpserver/jumpserver/apps/users/views/login.py", line 121, in get_success_url
    self.write_login_log()
TypeError: write_login_log() missing 1 required positional argument: 'data'

但是添加data参数后，报错提示为：
[exception ERROR] Internal Server Error: /users/login/
Traceback (most recent call last):
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/jumpserver/jumpserver/apps/users/views/login.py", line 73, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/usr/local/jumpserver/jumpserver/apps/users/views/login.py", line 80, in form_valid
    return redirect(self.get_success_url())
  File "/usr/local/jumpserver/jumpserver/apps/users/views/login.py", line 121, in get_success_url
    self.write_login_log(data)
UnboundLocalError: local variable 'data' referenced before assignment

请问这是什么问题，请大神帮忙分析下什么问题，感谢！

[注:] 完成后请关闭 issue

**Comment by zhimin-fit2cloud** [comment]
请升级到最新版本。

**Comment by jym503558564** [comment]
问题是否已得到解决，如有其它问题，请重新打开issues
