### ISSUE TITLE
1.5.1 coco 通过网关连接机器失败

### ISSUE THREAD

**Issue by huangzx** [jumpserver/jumpserver#2897]
[简述你的问题]
因为 jumpserver 部署在内网中（无外网 IP），连接其它机房的机器，在网关之上还加了 nginx 的 tcp 代理。
现在的问题是：coco 通过网关连接其它机房的机器失败。
1.5.0 正常，1.5.1 不正常。

##### 使用版本
1.5.1

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/3265516/60782464-f4fad880-a170-11e9-9546-4a938bd902f3.png)

coco 日志：

2019-07-08 11:46:28 [connection ERROR] required argument is not an integer
Traceback (most recent call last):
  File "/data/jumpserver/coco/coco/connection.py", line 233, in get_proxy_sock_v2
    'direct-tcpip', (asset.ip, asset.ssh_port), ('127.0.0.1', 0)
  File "/data/jumpserver/py3/lib/python3.6/site-packages/paramiko/transport.py", line 911, in open_channel
    m.add_int(dest_addr[1])
  File "/data/jumpserver/py3/lib/python3.6/site-packages/paramiko/message.py", line 232, in add_int
    self.packet.write(struct.pack(">I", n))
struct.error: required argument is not an integer
2019-07-08 11:46:28 [connection ERROR] Connect gateway failed.

**Comment by 932340583** [comment]
表示遇到了同样的问题，同时问一下，之前guacamole编译安装的文档为什么没有了，改成了完全由docker运行服务？这次更新我还需要这个文档啊！！！

**Comment by 932340583** [comment]
我的情况也是通过网关连接的机器失败，但提示报错是timeout.

**Comment by ibuler** [comment]
已修复 1.5.2
