### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by 7cristiano** [jumpserver/jumpserver#2949]
[简述你的问题]
从1.4.9升级到1.5.1后，有一个用户组下面的所有用户都看不到已授权的资产（其他用户组下账号正常）。查看日志有报错

##### 使用版本
1.5.1

##### 问题复现步骤
1. 从1.4.9升级到1.5.1，有一个用户组下面的所有用户都看不到已授权的资产。
2.看有问题用户的授权的资产有Unknown error occur的报错，同时jumpserver.log也有报错打印

##### 具体表现[截图可能会更好些,最好能截全]
看有问题用户的授权的资产有Unknown error occur的报错
![image](https://user-images.githubusercontent.com/33511216/61200618-a327f480-a714-11e9-8836-4e1d951d7d81.png)
日志报错
![image](https://user-images.githubusercontent.com/33511216/61200783-28aba480-a715-11e9-8b8f-feccfddacafb.png)
2019-07-15 10:46:43 [log ERROR] Internal Server Error: /api/perms/v1/users/2af5729c-4217-46c8-9396-c0f4d5f34221/assets/
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/perms/api/user_permission.py", line 128, in get
    resp = super().get(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/opt/jumpserver/apps/perms/api/user_permission.py", line 153, in get_queryset
    assets = util.get_assets()
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 319, in get_assets
    return self.get_resource("assets")
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 303, in get_resource
    return self.get_resource_from_cache(resource)
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 297, in get_resource_from_cache
    self.update_cache()
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 343, in update_cache
    assets = self.get_resource_without_cache("assets")
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 313, in get_resource_without_cache
    return getattr(self, attr)()
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 489, in get_assets_without_cache
    self.get_assets_direct()
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 478, in get_assets_direct
    self.tree.add_assets(assets)
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 127, in add_assets
    self.add_asset(asset, system_users)
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 156, in add_asset
    self.nodes[self.ungrouped_node]["assets"].add(system_users)
TypeError: unhashable type: 'dict'
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
git pull 升级一下

**Comment by 7cristiano** [comment]
git pull升级后好了，但是授权规则变了，有些规则不见了，还多出来一个未分组的目录
![image](https://user-images.githubusercontent.com/33511216/61207986-f9069780-a728-11e9-8f42-433364d16c56.png)

**Comment by BaiJiangJie** [comment]
未分组目录：用来存放单独授权的资产（该资产没有在被授权的任何节点或子节点中）

**Comment by zhxjdwh** [comment]
我试了 1.5.2版本还是有这个问题！！！ @BaiJiangJie

**Comment by zhxjdwh** [comment]
`Traceback:

File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/lib/python3.6/contextlib.py" in inner
  52.                 return func(*args, **kwds)

File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)

File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  495.             response = self.handle_exception(exc)

File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py" in handle_exception
  455.             self.raise_uncaught_exception(exc)

File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py" in dispatch
  492.             response = handler(request, *args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py" in _wrapper
  45.         return bound_method(*args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/http.py" in inner
  99.                 response = func(request, *args, **kwargs)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/mixin.py" in get
  129.             return super().get(request, *args, **kwargs)

File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/generics.py" in get
  201.         return self.list(request, *args, **kwargs)

File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/mixins.py" in list
  40.         queryset = self.filter_queryset(self.get_queryset())

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/user_permission.py" in get_queryset
  286.         nodes_items = self.util.get_nodes_with_assets()

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/utils/asset_permission.py" in get_nodes_with_assets
  368.         return self.get_resource("nodes_with_assets")

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/utils/asset_permission.py" in get_resource
  361.             return self.get_resource_without_cache(resource)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/utils/asset_permission.py" in get_resource_without_cache
  365.         return getattr(self, attr)()

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/common/utils/common.py" in wrapper
  192.         result = func(*args, **kwargs)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/utils/asset_permission.py" in get_nodes_with_assets_without_cache
  570.         self.get_assets_without_cache()

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/common/utils/common.py" in wrapper
  192.         result = func(*args, **kwargs)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/utils/asset_permission.py" in get_assets_without_cache
  562.         self.get_nodes_direct()

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/common/utils/common.py" in wrapper
  192.         result = func(*args, **kwargs)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/utils/asset_permission.py" in get_nodes_direct
  509.         self.tree.add_nodes(nodes_keys)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/common/utils/common.py" in wrapper
  192.         result = func(*args, **kwargs)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/utils/asset_permission.py" in add_nodes
  167.         family = util.get_nodes_family_and_system_users(nodes_keys_with_system_users_ids)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/common/utils/common.py" in wrapper
  192.         result = func(*args, **kwargs)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/utils/stack.py" in get_nodes_family_and_system_users
  47.         family_keys = node_util.get_some_nodes_family_keys_by_keys(_nodes_keys)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/assets/utils.py" in get_some_nodes_family_keys_by_keys
  186.         family = self.get_some_nodes_family_by_keys(keys)

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/assets/utils.py" in get_some_nodes_family_by_keys
  182.             family.update(self.get_family_by_key(key))

File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/assets/utils.py" in get_family_by_key
  165.         tree_nodes.add(node)

Exception Type: TypeError at /api/perms/v1/users/nodes-assets/tree/
Exception Value: unhashable type: 'Node'`

**Comment by zhxjdwh** [comment]
![image](https://user-images.githubusercontent.com/9401765/63636087-05bdca00-c69d-11e9-873b-98cb6335a219.png)

**Comment by zhxjdwh** [comment]
`2019-08-24 18:30:31 [log ERROR] Internal Server Error: /api/perms/v1/asset-permissions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/asset_permission.py", line 162, in filter_queryset
    queryset = self.filter_asset(queryset)
  File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/asset_permission.py", line 111, in filter_asset
    inherit_nodes.update(set(node.get_ancestor(with_self=True)))
TypeError: unhashable type: 'Node'
2019-08-24 18:30:32 [log ERROR] Internal Server Error: /api/perms/v1/asset-permissions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/asset_permission.py", line 162, in filter_queryset
    queryset = self.filter_asset(queryset)
  File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/asset_permission.py", line 111, in filter_asset
    inherit_nodes.update(set(node.get_ancestor(with_self=True)))
TypeError: unhashable type: 'Node'1`

**Comment by zhxjdwh** [comment]
`2019-08-24 18:30:31 [log ERROR] Internal Server Error: /api/perms/v1/asset-permissions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/asset_permission.py", line 162, in filter_queryset
    queryset = self.filter_asset(queryset)
  File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/asset_permission.py", line 111, in filter_asset
    inherit_nodes.update(set(node.get_ancestor(with_self=True)))
TypeError: unhashable type: 'Node'
2019-08-24 18:30:32 [log ERROR] Internal Server Error: /api/perms/v1/asset-permissions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jumpserver/python/env1/env1/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/asset_permission.py", line 162, in filter_queryset
    queryset = self.filter_asset(queryset)
  File "/home/jumpserver/jumpserver2/jumpserver-1.5.2/apps/perms/api/asset_permission.py", line 111, in filter_asset
    inherit_nodes.update(set(node.get_ancestor(with_self=True)))
TypeError: unhashable type: 'Node'1`
