### ISSUE TITLE
创建命令过滤器规则--正则表达式--Server error occur, contact administrator

### ISSUE THREAD

**Issue by wanghkkk** [jumpserver/jumpserver#2950]
[简述你的问题]
配置创建命令过滤器规则，正则表达式，
过滤器：denyCmds
类型：正则表达式
内容：rm.*
优先级：50
动作：拒绝

点击提交提示错误：Server error occur, contact administrator

日志错误提示：
2019-07-15 16:20:02 [log ERROR] Internal Server Error: /assets/cmd-filter/d052d070-71df-4eed-81d5-c2a7e25a730a/rule/create/
Traceback (most recent call last):
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/microoak/python-3.6.8/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/microoak/jumpserver/jumpserver-1.5.1/apps/assets/views/cmd_filter.py", line 132, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/opt/microoak/jumpserver/lib/python3.6/site-packages/django/forms/forms.py", line 402, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "/opt/microoak/jumpserver/jumpserver-1.5.1/apps/assets/forms/cmd_filter.py", line 37, in clean_content
    msg = _("Content should not be contain: {}").format(invalid_char)
NameError: name '_' is not defined

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.1

##### 问题复现步骤
1. 资产管理--命令过滤--创建命令过滤器--名称为denyCmds
2. 资产管理--命令过滤--创建命令过滤器--denyCmds--规则--创建规则---如下：
配置创建命令过滤器规则，正则表达式，
过滤器：denyCmds
类型：正则表达式
内容：rm.*
优先级：50
动作：拒绝

##### 其他

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
新版本已修复,可更新到最新版本

**Comment by BaiJiangJie** [comment]
Fixed.
