### ISSUE TITLE
同一组的某个用户 登录突然不能登录指定主机 同组其他用户正常

### ISSUE THREAD

**Issue by npcomet** [jumpserver/jumpserver#3067]
[简述你的问题]
同一组的某个用户 登录突然不能登录指定主机 同组其他用户正常

##### 使用版本
Jumpserver版本 1.5.2

##### 问题复现步骤
1. web 终端不能登录
2. 文件管理器提示  (2, 'Connect failed')
##### 具体表现[截图可能会更好些,最好能截全]

```bash
2019-08-01 10:45:30 [ws ERROR] Unexpected error occur: (2, 'Connect failed')
2019-08-01 10:45:30 [ws ERROR] (2, 'Connect failed')
Traceback (most recent call last):
  File "/opt/coco/coco/httpd/ws.py", line 87, in proxy
    forwarder.proxy()
  File "/opt/coco/coco/proxy.py", line 68, in proxy
    self.server = self.get_server_conn_from_cache()
  File "/opt/coco/coco/proxy.py", line 110, in get_server_conn_from_cache
    server = self.get_ssh_server_conn(cache=True)
  File "/opt/coco/coco/proxy.py", line 162, in get_ssh_server_conn
    chan = conn.get_channel(term=term, width=width, height=height)
  File "/opt/coco/coco/connection.py", line 168, in get_channel
    chan = self.client.invoke_shell(term, width=width, height=height)
  File "/opt/py3/lib/python3.6/site-packages/paramiko/client.py", line 530, in invoke_shell
    chan = self._transport.open_session()
  File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 806, in open_session
    timeout=timeout,
  File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 944, in open_channel
    raise e
paramiko.ssh_exception.ChannelException: (2, 'Connect failed')
2019-08-01 10:45:51 [ws ERROR] Unexpected error occur: (2, 'Connect failed')
2019-08-01 10:45:51 [ws ERROR] (2, 'Connect failed')
Traceback (most recent call last):
  File "/opt/coco/coco/httpd/ws.py", line 87, in proxy
    forwarder.proxy()
  File "/opt/coco/coco/proxy.py", line 68, in proxy
    self.server = self.get_server_conn_from_cache()
  File "/opt/coco/coco/proxy.py", line 110, in get_server_conn_from_cache
    server = self.get_ssh_server_conn(cache=True)
  File "/opt/coco/coco/proxy.py", line 162, in get_ssh_server_conn
    chan = conn.get_channel(term=term, width=width, height=height)
  File "/opt/coco/coco/connection.py", line 168, in get_channel
    chan = self.client.invoke_shell(term, width=width, height=height)
  File "/opt/py3/lib/python3.6/site-packages/paramiko/client.py", line 530, in invoke_shell
    chan = self._transport.open_session()
  File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 806, in open_session
    timeout=timeout,
  File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 944, in open_channel
    raise e
paramiko.ssh_exception.ChannelException: (2, 'Connect failed')
```

##### 其他

最后重启 coco 故障消失

应该算一个隐藏 bug 吧 如果还需要查询哪里的日志，我可以提供一下

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
应该是链接过多导致

**Comment by npcomet** [comment]
> 应该是链接过多导致

资产不 200 用户 10人左右
连接数可以调整吗？

**Comment by shyp88** [comment]
我遇到的问题和楼主有些类似，同组的某一个用户他授权的一个资产突然无法访问，同组的另外用户正常，而且这人他访问其他授权资产也正常。
我尝试了各种方法，删除用户所有权限，重新添加也没用，最后将用户删除，再重建，重新设置权限，才恢复正常，现象无法复现，希望也不要复现。删用户再重新授权很麻烦

**Comment by ibuler** [comment]
应该是连接复用导致的，一个人是不是连接这个资产过多了
