### ISSUE TITLE
AUTH_USER_MODEL refers to model 'users.User' that has not been installed

### ISSUE THREAD

**Issue by gengkeye** [jumpserver/jumpserver#3119]
升级至版本1.5.2，执行makemigrations时报错： 

```
Traceback (most recent call last):
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/apps/config.py", line 165, in get_model
    return self.models[model_name.lower()]
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 165, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/apps/registry.py", line 207, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/apps/config.py", line 168, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'users' doesn't have a 'User' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/seven/workspace/jumpserver/jumpserver/apps/users/models/__init__.py", line 6, in <module>
    from .group import *
  File "/home/seven/workspace/jumpserver/jumpserver/apps/users/models/group.py", line 7, in <module>
    from orgs.mixins import OrgModelMixin
  File "/home/seven/workspace/jumpserver/jumpserver/apps/orgs/mixins/__init__.py", line 7, in <module>
    from .api import *
  File "/home/seven/workspace/jumpserver/jumpserver/apps/orgs/mixins/api.py", line 4, in <module>
    from rest_framework.viewsets import ModelViewSet
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/rest_framework/viewsets.py", line 29, in <module>
    from rest_framework import generics, mixins, views
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/rest_framework/generics.py", line 11, in <module>
    from rest_framework import mixins, views
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/rest_framework/views.py", line 19, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/rest_framework/schemas/__init__.py", line 32, in <module>
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/rest_framework/settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/rest_framework/settings.py", line 172, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/rest_framework/settings.py", line 172, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/rest_framework/settings.py", line 183, in import_from_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/seven/workspace/jumpserver/jumpserver/apps/authentication/backends/api.py", line 109, in <module>
    class AccessTokenAuthentication(authentication.BaseAuthentication):
  File "/home/seven/workspace/jumpserver/jumpserver/apps/authentication/backends/api.py", line 111, in AccessTokenAuthentication
    model = get_user_model()
  File "/home/seven/workspace/py3/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 170, in get_user_model
    "AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.User' that has not been installed
```

apps/jumpserver/settings.py 文件中的配置是：

```
AUTH_USER_MODEL = "users.User"
```

**Comment by gengkeye** [comment]
在线等，挺急的

**Comment by gengkeye** [comment]
当把配置改为：
```
AUTH_USER_MODEL = "auth.User"
```
后，会有如下问题：
```
(py3) ➜   ✗ python apps/manage.py makemigrations
SystemCheckError: System check identified some issues:

ERRORS:
auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
users.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
(py3) ➜  ✗ 


```

**Comment by wojiushixiaobai** [comment]
@gengkeye 确定下升级过程，可以参考升级问题第三条
