### ISSUE TITLE
1.5.2安装报错

### ISSUE THREAD

**Issue by CaoZhenggg** [jumpserver/jumpserver#3176]
[简述你的问题]

##### 使用版本
1.5.2

##### 问题复现步骤
1. 安装python依赖包报错

##### 具体表现[截图可能会更好些,最好能截全]
Collecting python-gssapi==0.6.4 (from -r requirements.txt (line 57))
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/a4/9e/648b4e85235097edcee561c986f7075cb1606be24c514cfcdd2930e35c5e/python-gssapi-0.6.4.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no previously-included files found matching 'setup.pyc'
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.__pycache__.lex.cpython-36: module references __file__
    pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
    pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
    pycparser.ply.__pycache__.ygen.cpython-36: module references __file__
    
    Installed /tmp/pip-install-wbpud_ea/python-gssapi/.eggs/pycparser-2.19-py3.6.egg
    running egg_info
    creating pip-egg-info/python_gssapi.egg-info
    writing pip-egg-info/python_gssapi.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/python_gssapi.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/python_gssapi.egg-info/requires.txt
    writing top-level names to pip-egg-info/python_gssapi.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/python_gssapi.egg-info/SOURCES.txt'
    gssapi/bindings/__pycache__/_cffi__xa7d82a3cx47db505c.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xb6db7234xa2d82a13.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x4043bc38x4bfb7d35.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x91c0b203x91526966.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x4d60bb6fxf6f90d7e.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xfeda9684x2ac7d8ee.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xaca9cfeaxf572031a.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x9c11ac12x52753e5f.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x83153404xfc2f8cba.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x1e24ce42x6b064b6b.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x7d445f8dx8333c101.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x1c5a925axc95ea75b.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x84e8e962x962c4589.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
        extra_postargs)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-wbpud_ea/python-gssapi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 51, in _build
        dist.run_command('build_ext')
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wbpud_ea/python-gssapi/setup.py", line 74, in <module>
        url="https://github.com/sigmaris/python-gssapi",
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib64/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/opt/python-venv/jumpserver/lib64/python3.6/site-packages/setuptools/command/build_py.py", line 34, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/lib64/python3.6/distutils/command/build_py.py", line 45, in finalize_options
        ('force', 'force'))
      File "/usr/lib64/python3.6/distutils/cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/lib64/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-wbpud_ea/python-gssapi/setup.py", line 22, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "/tmp/pip-install-wbpud_ea/python-gssapi/setup.py", line 15, in get_ext_modules
        from gssapi.bindings import ffi
      File "/tmp/pip-install-wbpud_ea/python-gssapi/gssapi/__init__.py", line 4, in <module>
        from . import bindings
      File "/tmp/pip-install-wbpud_ea/python-gssapi/gssapi/bindings/__init__.py", line 233, in <module>
        C = ffi.verify(_source, **_kwargs)
      File "/tmp/pip-install-wbpud_ea/python-gssapi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/api.py", line 464, in verify
        lib = self.verifier.load_library()
      File "/tmp/pip-install-wbpud_ea/python-gssapi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/verifier.py", line 104, in load_library
        self._compile_module()
      File "/tmp/pip-install-wbpud_ea/python-gssapi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/verifier.py", line 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/tmp/pip-install-wbpud_ea/python-gssapi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 22, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "/tmp/pip-install-wbpud_ea/python-gssapi/.eggs/cffi-1.12.3-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 58, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wbpud_ea/python-gssapi/

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@CaoZhenggg 关键错误 Python.h: No such file or directory
原因: Python3.6 的 devel 库未安装。

请自行解决即可。如果任有问题建议使用极速安装文档进行安装
