### ISSUE TITLE
1.5.3 获取资产失败

### ISSUE THREAD

**Issue by NeilyoSH** [jumpserver/jumpserver#3287]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.3-2] (从1.5.2 升级)

##### 问题复现步骤
1. 资产列表获取资产状态一直是 “Loading”
2. 后台报错信息输出“[log ERROR] Internal Server Error: /api/v1/assets/nodes/children/tree/”

##### 具体表现[截图可能会更好些,最好能截全]

报错日志如下:
127.0.0.1 [26/Sep/2019:15:44:52 +0800] "POST /api/v1/terminal/terminals/status/ HTTP/1.1" 201 2
127.0.0.1 [26/Sep/2019:15:44:52 +0800] "POST /api/v1/terminal/terminals/status/?from_guacamole=1 HTTP/1.1" 201 2
127.0.0.1 [26/Sep/2019:15:44:59 +0800] "GET /assets/asset/ HTTP/1.0" 200 59744
127.0.0.1 [26/Sep/2019:15:44:59 +0800] "GET /en/jsi18n/ HTTP/1.0" 200 3185
2019-09-26 15:44:59 [log ERROR] Internal Server Error: /api/v1/assets/nodes/children/tree/
Traceback (most recent call last):
  File "/data/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/data/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/py3/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/data/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/data/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/py3/lib64/python3.6/site-packages/rest_framework/generics.py", line 241, in get
    return self.list(request, *args, **kwargs)
  File "/data/py3/lib64/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/data/jumpserver/apps/assets/api/node.py", line 163, in get_queryset
    queryset = [node.as_tree_node() for node in queryset]
  File "/data/jumpserver/apps/assets/api/node.py", line 163, in <listcomp>
    queryset = [node.as_tree_node() for node in queryset]
  File "/data/jumpserver/apps/assets/models/node.py", line 451, in as_tree_node
    name = '{} ({})'.format(self.value, self.assets_amount)
  File "/data/jumpserver/apps/common/utils/common.py", line 226, in __get__
    value = self.func(instance)
  File "/data/jumpserver/apps/assets/models/node.py", line 260, in assets_amount
    amount = self.tree().assets_amount(self.key)
  File "/data/jumpserver/apps/assets/models/node.py", line 45, in tree
    tree = TreeService.new()
  File "/data/jumpserver/apps/common/utils/common.py", line 195, in wrapper
    result = func(*args, **kwargs)
  File "/data/jumpserver/apps/assets/utils.py", line 52, in new
    parent=parent_key,
  File "/data/py3/lib64/python3.6/site-packages/treelib/tree.py", line 291, in create_node
    self.add_node(node, parent)
  File "/data/py3/lib64/python3.6/site-packages/treelib/tree.py", line 260, in add_node
    "is not in the tree" % pid)
treelib.exceptions.NodeIDAbsentError: Parent node '1:24:24' is not in the tree
127.0.0.1 [26/Sep/2019:15:44:59 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0 HTTP/1.0" 500 180
127.0.0.1 [26/Sep/2019:15:44:59 +0800] "GET /api/v1/assets/assets/?draw=1&search=&limit=15&offset=0&_=1569483899171 HTTP/1.0" 200 11335

##### 其他

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
通过日志，初步判断是在构造资产树时，节点之间的依赖关系有存在一些问题，您最好可以把节点的信息（通过调用 API 获取，主要是 Key 字段的信息）截图发一下，以便于 Jumpserver 团队能够更快的在本地复现，修复出现的问题。
备注：您也可以尝试着做一次升级，master 分支最后一次更新日期是在 2019.09.27 16:26 分左右。

**Comment by NeilyoSH** [comment]
> 通过日志，初步判断是在构造资产树时，节点之间的依赖关系有存在一些问题，您最好可以把节点的信息（通过调用 API 获取，主要是 Key 字段的信息）截图发一下，以便于 Jumpserver 团队能够更快的在本地复现，修复出现的问题。
> 备注：您也可以尝试着做一次升级，master 分支最后一次更新日期是在 2019.09.27 16:26 分左右。


升级搞定.
