### ISSUE TITLE
1.5.2升级到1.5.3 jms启动遇到错误

### ISSUE THREAD

**Issue by glkappe** [jumpserver/jumpserver#3343]
(jumpserver_py3) [root@ser4-44 jumpserver]# ./jms start -d
2019-10-15 17:18:50 Tue Oct 15 17:18:50 2019
2019-10-15 17:18:50 Jumpserver version 1.5.3, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
2019-10-15 17:18:50 Check database connection ...
Traceback (most recent call last):
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/rest_framework/settings.py", line 183, in import_from_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/authentication/backends/api.py", line 14, in <module>
    from common.auth import signature
  File "/opt/jumpserver/apps/common/auth/signature.py", line 4, in <module>
    from httpsig import HeaderVerifier, utils
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/httpsig/__init__.py", line 3, in <module>
    from .sign import Signer, HeaderSigner
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/httpsig/sign.py", line 5, in <module>
    from Crypto.PublicKey import RSA
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/Crypto/PublicKey/__init__.py", line 21, in <module>
    from Crypto.Util.asn1 import (DerSequence, DerInteger, DerBitString,
ImportError: cannot import name 'DerBitString'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/jumpserver/urls.py", line 11, in <module>
    from . import views
  File "/opt/jumpserver/apps/jumpserver/views.py", line 12, in <module>
    from rest_framework.views import APIView
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/rest_framework/views.py", line 19, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/rest_framework/schemas/__init__.py", line 32, in <module>
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/rest_framework/settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/rest_framework/settings.py", line 172, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/rest_framework/settings.py", line 172, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/opt/jumpserver_py3/lib/python3.6/site-packages/rest_framework/settings.py", line 187, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'authentication.backends.api.AccessKeyAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ImportError: cannot import name 'DerBitString'.
^CTraceback (most recent call last):
  File "./jms", line 514, in <module>
    start_services_and_watch(srv)
  File "./jms", line 399, in start_services_and_watch
    p = start_service(i)
  File "./jms", line 370, in start_service
    kwargs = services_kwargs.get(s)()
  File "./jms", line 186, in get_start_gunicorn_kwargs
    prepare()
  File "./jms", line 107, in prepare
    check_database_connection()
  File "./jms", line 86, in check_database_connection
    time.sleep(1)
KeyboardInterrupt

**Comment by glkappe** [comment]
在这种情况下，我是否可以删除config.yml这个目录 重新git pull

**Comment by glkappe** [comment]
重新clone还是出现这错误。。。

**Comment by glkappe** [comment]
(jumpserver_py3) [root@ser4-44 jumpserver]# pip list
Package                   Version  
------------------------- ---------
aioredis                  1.3.0    
aliyun-python-sdk-core-v3 2.9.1    
aliyun-python-sdk-ecs     4.10.1   
amqp                      2.1.4    
ansible                   2.8.0    
asgiref                   3.2.2    
asn1crypto                0.24.0   
async-timeout             3.0.1    
attrs                     19.3.0   
autobahn                  19.10.1  
Automat                   0.7.0    
azure-common              1.1.22   
azure-nspkg               3.0.2    
azure-storage-blob        1.3.1    
azure-storage-common      1.4.2    
azure-storage-nspkg       3.1.0    
Babel                     2.7.0    
bcrypt                    3.1.4    
billiard                  3.5.0.3  
boto                      2.49.0   
boto3                     1.6.5    
botocore                  1.9.5    
cachetools                2.0.1    
celery                    4.1.0    
certifi                   2018.1.18
cffi                      1.11.5   
channels                  2.3.0    
channels-redis            2.4.0    
chardet                   3.0.4    
click                     6.7      
configparser              3.5.0    
constantly                15.1.0   
coreapi                   2.3.3    
coreschema                0.0.4    
crcmod                    1.7      
cryptography              2.7      
daphne                    2.3.0    
decorator                 4.1.2    
Django                    2.1.7    
django-auth-ldap          1.7.0    
django-bootstrap3         9.1.0    
django-celery-beat        1.4.0    
django-filter             2.0.0    
django-formtools          2.1      
django-proxy              1.2.1    
django-radius             1.3.3    
django-ranged-response    0.2.0    
django-redis-cache        1.7.1    
django-redis-sessions     0.6.1    
django-rest-swagger       2.1.2    
django-simple-captcha     0.5.6    
django-timezone-field     3.0      
djangorestframework       3.9.4    
djangorestframework-bulk  0.2.1    
dnspython                 1.16.0   
docutils                  0.14     
dotmap                    1.2.20   
drf-nested-routers        0.91     
drf-yasg                  1.9.1    
ecdsa                     0.13     
elasticsearch             6.4.0    
enum-compat               0.0.2    
ephem                     3.7.6.0  
eventlet                  0.24.1   
Flask                     1.0.2    
Flask-SocketIO            2.9.2    
flower                    0.9.3    
ForgeryPy                 0.1      
future                    0.17.1   
greenlet                  0.4.14   
gunicorn                  19.9.0   
hiredis                   1.0.0    
httpsig                   1.3.0    
hyperlink                 19.0.0   
idna                      2.6      
incremental               17.5.0   
inflection                0.3.1    
ipip-ipdb                 1.2.1    
itsdangerous              0.24     
itypes                    1.1.0    
Jinja2                    2.10.1   
jmespath                  0.9.3    
jms-storage               0.0.25   
jumpserver-python-sdk     0.0.63   
kombu                     4.0.2    
ldap3                     2.4      
lockfile                  0.12.2   
MarkupSafe                1.0      
monotonic                 1.5      
msgpack                   0.6.2    
mysqlclient               1.3.14   
netaddr                   0.7.19   
olefile                   0.44     
openapi-codec             1.3.2    
oss2                      2.4.0    
paramiko                  2.4.2    
passlib                   1.7.1    
Pillow                    4.3.0    
pip                       19.3     
psutil                    5.4.1    
pyasn1                    0.4.2    
pyasn1-modules            0.2.5    
pycparser                 2.19     
pycrypto                  2.6.1    
pycryptodome              3.8.2    
PyHamcrest                1.9.0    
PyNaCl                    1.2.1    
pyotp                     2.2.6    
pyrad                     2.1      
pyte                      0.8.0    
python-crontab            2.3.6    
python-daemon             2.2.3    
python-dateutil           2.6.1    
python-engineio           2.1.0    
python-gssapi             0.6.4    
python-jose               3.0.1    
python-keycloak           0.13.3   
python-keycloak-client    0.1.3    
python-ldap               3.1.0    
python-socketio           1.8.3    
pytz                      2018.3   
PyYAML                    5.1      
redis                     2.10.6   
requests                  2.22.0   
rest-condition            1.0.3    
rsa                       4.0      
ruamel.yaml               0.15.97  
s3transfer                0.1.13   
setuptools                41.0.1   
simplejson                3.13.2   
six                       1.11.0   
sqlparse                  0.3.0    
sshpubkeys                3.1.0    
tencentcloud-sdk-python   3.0.40   
tornado                   4.5.2    
treelib                   1.5.3    
Twisted                   19.7.0   
txaio                     18.8.1   
unicodecsv                0.14.1   
uritemplate               3.0.0    
urllib3                   1.25.2   
vine                      1.1.4    
wcwidth                   0.1.7    
Werkzeug                  0.14.1   
zope.interface            4.6.0

**Comment by glkappe** [comment]
autobahn有版本需求吗

**Comment by bingws** [comment]
pip uninstall PyCrypto
pip uninstall PyCryptodome
pip install PyCryptodome
