### ISSUE TITLE
1.5.3登录问题

### ISSUE THREAD

**Issue by justinmjc** [jumpserver/jumpserver#3354]
[简述你的问题]

我是用docker-comppse起的，中间有把各个组件重建过，数据库和redis 没变过，
然后现在所有机器都链接不上，点击测更新硬件或者 测试可连接性都报一样的错，如下

2019-10-17 20:50:36 任务开始: 更新资产硬件信息: ALISH59
[Errno 2] No such file or directory: '/opt/jumpserver/tmp/.df2dfc9fdfccb5e6d844eed1848f49c4'
Traceback (most recent call last):
  File "/opt/jumpserver/apps/ops/models/adhoc.py", line 252, in _run_and_record
    raw, summary = self._run_only()
  File "/opt/jumpserver/apps/ops/models/adhoc.py", line 275, in _run_only
    runner = AdHocRunner(self.inventory, options=self.options)
  File "/opt/jumpserver/apps/ops/models/adhoc.py", line 221, in inventory
    run_as=self.run_as, become_info=become_info
  File "/opt/jumpserver/apps/ops/inventory.py", line 94, in __init__
    host = self.convert_to_ansible(asset, run_as_admin=run_as_admin)
  File "/opt/jumpserver/apps/ops/inventory.py", line 32, in convert_to_ansible
    info.update(asset.get_auth_info())
  File "/opt/jumpserver/apps/assets/models/asset.py", line 250, in get_auth_info
    'private_key': self.admin_user.private_key_file,
  File "/opt/jumpserver/apps/assets/models/base.py", line 61, in private_key_file
    self.private_key_obj.write_private_key_file(key_path)
  File "/opt/py3/lib64/python3.6/site-packages/paramiko/rsakey.py", line 146, in write_private_key_file
    password=password,
  File "/opt/py3/lib64/python3.6/site-packages/paramiko/pkey.py", line 355, in _write_private_key_file
    with open(filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/jumpserver/tmp/.df2dfc9fdfccb5e6d844eed1848f49c4'
2019-10-17 12:50:36 任务结束
.

.
获取资产信息失败：ALISH59

no such file or directory: '/opt/jumpserver/tmp/.df2dfc9fdfccb5e6d844eed1848f49c4'
core 容器里 /opt/jumpserver/下没有tmp 这个文件夹，
想问下这个tmp 的文件夹作用

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by justinmjc** [comment]
应该是我自己改了core 源码编译出的问题，我返回之前没改过代码的core 正常了
