### ISSUE TITLE
Centos 6.5 全新安装jumpserver之后，不能使用Terminal登录目标机，其他功能正常。

### ISSUE THREAD

**Issue by baiyubao** [jumpserver/jumpserver#341]
Centos 6.5 全新安装jumpserver之后，不能使用Terminal登录目标机，其他功能正常。
页面截图：
![1](https://cloud.githubusercontent.com/assets/19277618/21877417/f1031f2e-d8c5-11e6-855a-920ceae48029.png)
![Uploading 2.png…]()

日志报错如下：
2017-01-12 12:50:23,209 - views.py - DEBUG - 获取授权系统用户: admin
2017-01-12 12:50:24,383 - run_server.py - DEBUG - Websocket: session_key: is6ta44cz9xxuosxnebtrrgdi4mwmfba
2017-01-12 12:50:24,388 - run_server.py - DEBUG - Websocket: session: Session object
2017-01-12 12:50:24,393 - run_server.py - DEBUG - Websocket: user [ baiyubao ] request websocket
2017-01-12 12:50:24,394 - run_server.py - DEBUG - Websocket: Open request
2017-01-12 12:50:24,428 - run_server.py - DEBUG - set([<PermRole: admin>])
2017-01-12 12:50:24,428 - run_server.py - DEBUG - 系统用户: admin
2017-01-12 12:50:24,428 - run_server.py - DEBUG - Websocket: request web terminal Host: client1 User: baiyubao Role: admin
2017-01-12 12:50:24,431 - connect.py - DEBUG - {'ip': u'192.168.1.231', 'role_name': u'admin', 'role_key': u'/opt/jumpserver-0.3.2/keys/user/baiyubao_admin.pem', 'user': <User: baiyubao>, 'role_pass': 'admin123456', 'port': 123, 'asset': <Asset: 192.168.1.231>}
2017-01-12 12:50:25,116 - run_server.py - DEBUG - Websocket: Close request

这个问题困扰了我好久，一直没有解决，还请帮忙看下是哪里的问题，谢谢！

ps：论坛，wiki我都转遍了，都没解决。。

**Comment by xiaooloong** [comment]
`jumpserver.conf` 里配置的端口是多少？直接用端口访问试试

**Comment by baiyubao** [comment]
配置如下：
#cat jumpserver.conf 
[base]
url = http://192.168.1.230
key = jl68y05lwmo679z4
ip = 0.0.0.0
port = 8000
log = debug

[db]
host = 127.0.0.1
port = 3306
user = jumpserver
password = 5Lov@wife
database = jumpserver

[mail]
mail_enable = 1
email_host = smtp.exmail.qq.com
email_port = 25
email_host_user = xxxx@com
email_host_password = xxx
email_use_tls = True
email_use_ssl = False


我访问的就是带端口号的，并没有使用nginx做代理访问呢
http://192.168.1.230:8000/login/

![qq 20170112153957](https://cloud.githubusercontent.com/assets/19277618/21881181/d0a1c682-d8dd-11e6-9044-5f032881525a.png)

**Comment by CloudZheng** [comment]
请问问题解决了吗 我也遇到这个问题了

**Comment by sifksky** [comment]
我也是这个问题,后台报
DEBUG:jumpserver:系统用户: developer
DEBUG:jumpserver:Websocket: request web terminal Host: 10.130.160.8 User: admin Role: developer
DEBUG:jumpserver:{'ip': u'10.130.160.8', 'role_name': u'developer', 'role_key': u'/opt/jumpserver/keys/user/admin_developer.pem', 'user': <User: admin>, 'role_pass': 'test', 'port': 22, 'asset': <Asset: 10.130.160.8>}
ERROR:tornado.application:Uncaught exception in /ws/terminal
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 417, in _run_callback
    callback(*args, **kwargs)
  File "./run_server.py", line 367, in on_message
    self.termlog.write(jsondata)
  File "/opt/jumpserver/jlog/views.py", line 267, in write
    self.log[str(time.time() - self.recoderStartTime)] = msg.decode('utf-8', 'replace')
AttributeError: 'dict' object has no attribute 'decode'
DEBUG:jumpserver:Websocket: Close request
{}

**Comment by liuhetongzi** [comment]
请问问题解决了吗  分享一下
