### ISSUE TITLE
coco - and - koko - Restart issue

### ISSUE THREAD

**Issue by mousazade** [jumpserver/jumpserver#3424]
jumpserver/jms_coco:1.4.5
jumpserver Last Version + koko Service -- "Docker and source Install"

There have been problems with the jump server service
You will be notified:
1. The problem of not loading the coco service after restart, which is as follows:
This problem occurs in both old and new versions

Traceback (most recent call last):
  File "./cocod", line 20, in <module>
    from coco import Coco
  File "/opt/coco/coco/__init__.py", line 6, in <module>
    from .app import Coco
  File "/opt/coco/coco/app.py", line 13, in <module>
    from .sshd import SSHServer
  File "/opt/coco/coco/sshd.py", line 12, in <module>
    from coco.interface import SSHInterface
  File "/opt/coco/coco/interface.py", line 11, in <module>
    from .service import app_service
  File "/opt/coco/coco/service.py", line 13, in <module>
    app_service.initial ()
  File "/opt/py3/lib64/python3.6/site-packages/jms/service.py", line 55, in initial
    self.load_access_key ()
  File "/opt/py3/lib64/python3.6/site-packages/jms/service.py", line 66, in load_access_key
    self.register_and_save ()
  File "/opt/py3/lib64/python3.6/site-packages/jms/service.py", line 93, in register_and_save
    self.config ['NAME'], self.config ['BOOTSTRAP_TOKEN']
  File "/opt/py3/lib64/python3.6/site-packages/jms/terminal.py", line 62, in register_terminal_v2
    headers = headers
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 118, in post
    return self.do (* args, ** kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 106, in do
    resp = req.do ()
  File "/opt/py3/lib64/python3.6/site-packages/jms/request.py", line 51, in do
    ** self.kwargs
  File "/opt/py3/lib64/python3.6/site-packages/requests/api.py", line 112, in post
    return request ('post', url, data = data, json = json, ** kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request (method = method, url = url, ** kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request (req)
  File "/opt/py3/lib64/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks = merge_hooks (request.hooks, self.hooks),
  File "/opt/py3/lib64/python3.6/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url (url, params)
  File "/opt/py3/lib64/python3.6/site-packages/requests/models.py", line 382, ​​in prepare_url
    raise InvalidURL ("Invalid URL% r: No host supplied"% url)
requests.exceptions.InvalidURL: Invalid URL 'http: //: 8080 / api / terminal / v2 / terminal-registrations /': No host supplied

2-Difficulty setting sudoers through the panel :
Values ​​that are allowed in sudo are added in tandem or below, but the user still cannot use the command added with sudo.
Only the "Whoami" command works

Please guide me to these problems so I can use this service

Thanks

![Screenshot from 2019-11-10 12-31-46](https://user-images.githubusercontent.com/33278412/68541577-7e881480-03b6-11ea-9dbb-7dd45bcc8789.png)

**Comment by wojiushixiaobai** [comment]
@mousazade 
Your URL is wrong, please fix it
TIP：
```
$ cat /opt/coco/conf.py
...

CORE_HOST = os.environ.get("CORE_HOST") or 'http://<your jumpserver url>'
```

**Comment by mousazade** [comment]
> @mousazade
> Your URL is wrong, please fix it
> TIP：
> 
> ```
> $ cat /opt/coco/conf.py
> ...
> 
> CORE_HOST = os.environ.get("CORE_HOST") or 'http://<your jumpserver url>'
> ```
its worked !

please help for issue number 2

2-Difficulty setting sudoers through the panel :
Values ​​that are allowed in sudo are added in tandem or below, but the user still cannot use the command added with sudo.
Only the "Whoami" command works

thanks
