### ISSUE TITLE
执行批量命令的时候报错

### ISSUE THREAD

**Issue by reY2ox** [jumpserver/jumpserver#3478]
[简述你的问题]
执行批量命令的时候报错
![QQ截图20191202134122](https://user-images.githubusercontent.com/49467163/69933381-7597e800-1509-11ea-81b4-c44781cda493.png)

`
---------- 任务开始 ----------
Task ops.tasks.run_command_execution[b631b08d-7543-4fc2-b01c-5febfceaaf96] raised unexpected: error('multiple repeat at position 13',)
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/ops/tasks.py", line 48, in run_command_execution
    execution.run()
  File "/opt/jumpserver/apps/ops/models/command.py", line 61, in run
    ok, msg = self.run_as.is_command_can_run(self.command)
  File "/opt/jumpserver/apps/assets/models/user.py", line 143, in is_command_can_run
    action, matched_cmd = rule.match(command)
  File "/opt/jumpserver/apps/assets/models/cmd_filter.py", line 81, in match
    found = self._pattern.search(data)
  File "/opt/jumpserver/apps/assets/models/cmd_filter.py", line 75, in _pattern
    self.__pattern = re.compile(r'{}'.format('|'.join(regex)))
  File "/usr/lib64/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib64/python3.6/sre_parse.py", line 619, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 13`

##### 使用版本
我的版本是根据快速部署阿里云的教程部署的1.5.2-2

##### 问题复现步骤
执行批量命令就报错。

##### 具体表现[截图可能会更好些,最好能截全]

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@reY2ox 更新到1.5.4后再试试看
