### ISSUE TITLE
COCO1.46 经常挂掉或死掉

### ISSUE THREAD

**Issue by seadog0331** [jumpserver/jumpserver#3549]
报错日志如下：
2019-12-18 16:55:16 [models ERROR] 
Traceback (most recent call last):
  File "/data0/jumpserver/coco/coco/models.py", line 326, in send
    self.s_parse_input_output_filter(data)
  File "/data0/jumpserver/coco/coco/models.py", line 234, in s_parse_input_output_filter
    self._output = self._parse_output()
  File "/data0/jumpserver/coco/coco/models.py", line 351, in _parse_output
    return self._cmd_parser.parse_output(self.output_data)
  File "/data0/jumpserver/coco/coco/utils.py", line 121, in parse_output
    self.stream.feed(d)
  File "/opt/py3/lib/python3.6/site-packages/pyte/streams.py", line 395, in feed
    super(ByteStream, self).feed(data)
  File "/opt/py3/lib/python3.6/site-packages/pyte/streams.py", line 196, in feed
    taking_plain_text = send(data[offset:offset + 1])
StopIteration

**Comment by wojiushixiaobai** [comment]
@seadog0331 旧版本问题请更新到新版本后看问题是否复现
