### ISSUE TITLE
删除koko和gua之后，无法重新注册

### ISSUE THREAD

**Issue by gm12367** [jumpserver/jumpserver#3622]
[简述你的问题]
删除koko和gua之后，无法重新注册

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.4
##### 问题复现步骤
1. docker rm -f jms_koko 
2. docker rm -f jms_guacamole

##### 具体表现[截图可能会更好些,最好能截全]
```
2020/01/10 17:31:55 Not found file: config.yml
2020/01/10 17:31:55 Load from env
2020-01-10 17:31:55 [ERRO] POST http://10.100.39.1:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-10 17:31:55 [ERRO] register access key failed
2020/01/10 17:31:56 Not found file: config.yml
2020/01/10 17:31:56 Load from env
2020-01-10 17:31:56 [ERRO] POST http://10.100.39.1:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-10 17:31:56 [ERRO] register access key failed
2020/01/10 17:31:56 Not found file: config.yml
2020/01/10 17:31:56 Load from env
2020-01-10 17:31:56 [ERRO] POST http://10.100.39.1:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-10 17:31:56 [ERRO] register access key failed
2020/01/10 17:31:57 Not found file: config.yml
2020/01/10 17:31:57 Load from env
2020-01-10 17:31:57 [ERRO] POST http://10.100.39.1:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-10 17:31:57 [ERRO] register access key failed
2020/01/10 17:31:58 Not found file: config.yml
2020/01/10 17:31:58 Load from env
2020-01-10 17:31:58 [ERRO] POST http://10.100.39.1:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-10 17:31:58 [ERRO] register access key failed
2020/01/10 17:32:00 Not found file: config.yml
2020/01/10 17:32:00 Load from env
2020-01-10 17:32:00 [ERRO] POST http://10.100.39.1:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-10 17:32:00 [ERRO] register access key failed
```

##### 其他
尝试了清除terminal表中的数据，依然不行

[注:] 完成后请关闭 issue

**Comment by BaiJiangJie** [comment]
删除 koko 和 gua 生成的 key 文件。路径在 log 里面有显示

**Comment by gm12367** [comment]
我的koko和gua都是docker部署的，/opt下没有相关key文件，docker log里面我贴出来了，并未找到相关路径

**Comment by gm12367** [comment]
@BaiJiangJie 我试了一下1.5.6，按照卸载文档卸载之后，重装也会出现同样的问题，docker部署方式我只有在成功注册之后，容器里面才会正常生成access key文件
这个是gua的docker log：
```
guacd[20]: INFO:	Guacamole proxy daemon (guacd) version 1.0.0 started
2020-01-11 09:38:11,794 [Thread-5] ERROR o.a.g.a.j.r.JumpserverRegisterService 123 - 注册终端失败
org.apache.guacamole.GuacamoleClientException: 注册失败，可能已经注册过，请检查终端名称: [Gua]b9e1b149ce35
	at org.apache.guacamole.auth.jumpserver.api.JumpserverService.getRegisterTerminal(JumpserverService.java:49) ~[na:na]
	at org.apache.guacamole.auth.jumpserver.register.JumpserverRegisterService.lambda$getAccessKey$0(JumpserverRegisterService.java:109) ~[na:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]

```

这个是koko的log：
```
2020-01-11 09:42:58 [ERRO] register access key failed
2020-01-11 09:44:03 [ERRO] POST http://192.168.56.132:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-11 09:44:03 [ERRO] register access key failed
2020-01-11 09:45:08 [ERRO] POST http://192.168.56.132:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-11 09:45:08 [ERRO] register access key failed
2020-01-11 09:46:14 [ERRO] POST http://192.168.56.132:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-11 09:46:14 [ERRO] register access key failed
2020-01-11 09:47:19 [ERRO] POST http://192.168.56.132:8080/api/v2/terminal/terminal-registrations/ failed, get code: 400, {"error":"service account registration disabled"}
2020-01-11 09:47:19 [ERRO] register access key failed
```
authentication_accesskey 表和terminal表都是空的，但是就是注册失败

**Comment by LeeEirc** [comment]
@gm12367 
![image](https://user-images.githubusercontent.com/32626707/72199803-dd800d80-347b-11ea-9f06-e72232d58a0d.png)
这个允许终端注册是否选中？

**Comment by gm12367** [comment]
@LeeEirc 开启终端注册后，问题解决，十分感谢

**Comment by ykfq** [comment]
致后来人：
需要将表 settings_setting 中的 SECURITY_SERVICE_ACCOUNT_REGISTRATION 改为 true

**Comment by ykfq** [comment]
> @gm12367 ![image](https://user-images.githubusercontent.com/32626707/72199803-dd800d80-347b-11ea-9f06-e72232d58a0d.png) 这个允许终端注册是否选中？

致后来人：
由于界面上已经找不到上面截图的配置了，需要将表 settings_setting 中的 SECURITY_SERVICE_ACCOUNT_REGISTRATION 改为 true

**Comment by hcql** [comment]
v3.8.1  
![Untitled](https://github.com/jumpserver/jumpserver/assets/45474027/9ad844c1-5925-4239-b11f-f032d1abf7f7)
