### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by nineaiyu** [jumpserver/jumpserver#365]
Traceback (most recent call last):
  File "/jumpserver/connect.py", line 821, in <module>
    main()
  File "/jumpserver/connect.py", line 801, in main
    nav.upload()
  File "/jumpserver/connect.py", line 697, in upload
    color_print(msg, 'green')
  File "/jumpserver/connect.py", line 69, in color_print
    print msg
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-10: ordinal not in range(128)

Connection closed by foreign host.

推送文件时出错，基于docker centos:latest 环境，这个该怎么解决？

**Comment by jiaxiangkong** [comment]
字符集的问题

**Comment by nineaiyu** [comment]
这个应该怎么重新设置字符集，我试过了，好像一直没有成功，重新安装glibc-common也没有用
