### ISSUE TITLE
部分RDP录像丢失

### ISSUE THREAD

**Issue by bigbird1985** [jumpserver/jumpserver#3652]
[简述你的问题]
部分RDP录像丢失

##### 使用版本
1.5.6

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 具体表现[截图可能会更好些,最好能截全]
![图片](https://user-images.githubusercontent.com/4084548/72578112-10a91d80-3910-11ea-8887-4019bac6c333.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by xeooon** [comment]
我这边也有类似的问题，只是windows资产，linux资产没有问题，版本是1.5.6

**Comment by xeooon** [comment]
2020-02-05 08:20:46.754 [http-nio-8080-exec-4] INFO  o.a.g.a.j.api.JumpserverService - 注册Session成功
2020-02-05 08:20:46.755 [http-nio-8080-exec-4] INFO  o.a.g.a.j.session.RecordService - 录像Session关联文件创建成���: /run/s6/services/guacamole/nullnull-to-eaa0f26b-705f-4084-a5e9-076c4becb77c.map
creating directory /root/.config/freerdp
creating directory /root/.config/freerdp/certs
creating directory /root/.config/freerdp/server
certificate_store_open: error opening [/root/.config/freerdp/known_hosts] for writing
Unable to find a match for unix timezone: Etc/UTC
guacd[380]: INFO:       guacdr connected.
guacd[380]: INFO:       guacsnd connected.
guacd[380]: INFO:       Connected to RDPDR 1.12 as client 0x000e
guacd[380]: INFO:       Ignoring server capability set type=0x0001, length=44
guacd[380]: INFO:       Ignoring server capability set type=0x0002, length=8
guacd[380]: INFO:       Ignoring server capability set type=0x0003, length=8
guacd[380]: INFO:       Ignoring server capability set type=0x0004, length=8
guacd[380]: INFO:       Ignoring server capability set type=0x0005, length=8
guacd[380]: INFO:       Sending capabilities...
guacd[380]: INFO:       Capabilities sent.
guacd[380]: INFO:       Client ID confirmed
guacd[380]: INFO:       Connected to RDPDR 1.12 as client 0x0007
guacd[380]: INFO:       Ignoring server capability set type=0x0001, length=44
guacd[380]: INFO:       Ignoring server capability set type=0x0002, length=8
guacd[380]: INFO:       Ignoring server capability set type=0x0003, length=8
guacd[380]: INFO:       Ignoring server capability set type=0x0004, length=8
guacd[380]: INFO:       Ignoring server capability set type=0x0005, length=8
guacd[380]: INFO:       Sending capabilities...
guacd[380]: INFO:       Capabilities sent.
guacd[380]: INFO:       Client ID confirmed
guacd[380]: INFO:       User logged on
guacd[380]: INFO:       All supported devices sent.
guacd[380]: INFO:       User "@c59b0626-4bb2-45e3-9d86-5e378488eb7b" disconnected (0 users remain)
guacd[380]: INFO:       Last user of connection "$dc7ca19a-c6dc-437c-98ff-289dfe3823e4" disconnected
Exception in thread "Thread-25" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:425)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:191)
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
2020-02-05 08:20:53.668 [http-nio-8080-exec-8] INFO  o.a.g.tunnel.TunnelRequestService - User "5a7ce30f-671d-48f0-918f-6ef555397868" disconnected from connection "33ad73cb-3476-45ce-82fe-9bb90800f14e". Duration: 6913 milliseconds
guacd[380]: INFO:       Internal RDP client disconnected
guacd[214]: INFO:       Connection "$dc7ca19a-c6dc-437c-98ff-289dfe3823e4" removed.

**Comment by bigbird1985** [comment]
我找到问题了, /run/s6/services/guacamole/nullnull-to-eaa0f26b-705f-4084-a5e9-076c4becb77c.map 这段里的nullnull提示了我. 正常的情况下是这样/run/s6/services/guacamole/10.1.12.52-a24b11a9-1cd6-4c97-9a68-9e8e5ecb11c5-to-790a8b7b-7cd1-4648-aee8-1d93a53e3b00.map.

解决方法:
docker stop jms_guacamole
docker start jms_guacamole

**Comment by xeooon** [comment]
> 我找到问题了, /run/s6/services/guacamole/nullnull-to-eaa0f26b-705f-4084-a5e9-076c4becb77c.map 这段里的nullnull提示了我. 正常的情况下是这样/run/s6/services/guacamole/10.1.12.52-a24b11a9-1cd6-4c97-9a68-9e8e5ecb11c5-to-790a8b7b-7cd1-4648-aee8-1d93a53e3b00.map.
> 
> 解决方法:
> docker stop jms_guacamole
> docker start jms_guacamole

谢谢，目前我吧jumpserver升级到了最新版本1.5.6 20200203 后，目前没有发现问题。当然docker的组件也重启了。
