### ISSUE TITLE
1.3.3升级至1.4.4时报错"Unknown column 'settings.encrypted' in 'field list'"

### ISSUE THREAD

**Issue by wangjunking** [jumpserver/jumpserver#3655]
[简述你的问题]

##### 使用版本
1.3.3

##### 问题复现步骤
1.3.3升级至1.4.4

##### 具体表现[截图可能会更好些,最好能截全]
报错提示如下：
2020-01-17 16:58:16 [log ERROR] Internal Server Error: /users/login/
Traceback (most recent call last):
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1054, "Unknown column 'settings.encrypted' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/jumpserver/jumpserver/apps/users/views/login.py", line 64, in post
    if is_block_login(username, ip):
  File "/usr/local/jumpserver/jumpserver/apps/users/utils.py", line 360, in is_block_login
    limit_count = common_settings.SECURITY_LOGIN_LIMIT_COUNT or \
  File "/usr/local/jumpserver/jumpserver/apps/common/models.py", line 44, in __getattr__
    if len(instances) == 1:
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/models/query.py", line 1183, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1061, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/python-3.6.4/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'settings.encrypted' in 'field list'")

##### 其他

请问下是什么原因呢？

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
cd apps;
python manage.py migrate 试试

**Comment by fat8701** [comment]
请问后面如何解决的？

**Comment by wangjunking** [comment]
&nbsp;
 问题解决了，升级到最新版本就行了。
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"FAT__________"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月14日(星期四) 下午2:10
 收件人:&nbsp;"jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;;
 抄送:&nbsp;"王骏"<946324237@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [jumpserver/jumpserver] 1.3.3升级至1.4.4时报错"Unknown column 'settings.encrypted' in 'field list'" (#3655)

 

 

 
请问后面如何解决的？

**Comment by fat8701** [comment]
> &nbsp; 问题解决了，升级到最新版本就行了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"FAT__________"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月14日(星期四) 下午2:10 收件人:&nbsp;"jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;; 抄送:&nbsp;"王骏"<946324237@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [jumpserver/jumpserver] 1.3.3升级至1.4.4时报错"Unknown column 'settings.encrypted' in 'field list'" (#3655) 请问后面如何解决的？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我升级1.4.4 ok，但是升级到最新时报错：
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0003_auto_20200515_1023, 0023_auto_20181016_1650 in assets; 0013_auto_20181123_1113, 0003_auto_20200515_1023 in terminal; 0002_auto_20180903_1132, 0002_auto_20200515_1023 in orgs; 0009_auto_20180903_1132, 0003_auto_20200515_1023 in perms; 0017_auto_20181123_1113, 0004_auto_20200515_1023 in users; 0004_setting_encrypted, 0002_setting_encrypted in common; 0004_operatelog_passwordchangelog_userloginlog, 0002_auto_20200515_1023 in audits).
To fix them run 'python manage.py makemigrations --merge'
请问有遇到吗？
