### ISSUE TITLE
运行 ./ make_migrations.sh 报错信息：raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")

### ISSUE THREAD

**Issue by bigblue0** [jumpserver/jumpserver#3725]
运行 ./ make_migrations.sh 报错信息：raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")

Jumpserver版本 1.5.6

运行环境：
Centos7.4  Python3.6.9

报错操作：
运行完 pip install -r requirements.txt 后
切换到 utils 下面，执行 
./ make_migrations.sh 后，会一直出现下面的内容：

2020-02-27 01:38:11 Check database connection ...
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 36, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/commands/showmigrations.py", line 3, in <module>
    from django.db.migrations.loader import MigrationLoader
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/loader.py", line 8, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 9, in <module>
    class MigrationRecorder:
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 22, in MigrationRecorder
    class Migration(models.Model):
  File "/opt/py3/lib/python3.6/site-packages/django/db/models/base.py", line 87, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 249, in get_containing_app_config
    self.check_apps_ready()
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 131, in check_apps_ready
    settings.INSTALLED_APPS
  File "/opt/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/opt/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 126, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

以上，谢谢！

**Comment by wojiushixiaobai** [comment]
参考官方安装文档进行安装 https://docs.jumpserver.org/zh/master/step_by_step.html
