### ISSUE TITLE
创建资产时有时候会推送成功，有时候推送失败

### ISSUE THREAD

**Issue by WangZhiLoong** [jumpserver/jumpserver#3736]
[简述你的问题]
前提：使用的是sqlite3存储数据（不知道是否和这个有关系）
问题：创建资产推送管理用户到目标服务器，有时会成功，有时推送任务触发不了，追踪jumpserver/logs/celery_ansible.log中记录，发现有错误信息。

##### 使用版本
1.5.6

##### 问题复现步骤
1. [步骤1] 添加资产，信息填写完成保存
2. [步骤2]查看作业中心--任务列表，只有“更新资产硬件信息的任务”，并没有“推送系统用户到入资产: jumpserver”的任务记录。
3.查看celery_ansible.log，记录如下：
Task assets.tasks.asset_connectivity.test_asset_connectivity_manual[445f5aa4-46d0-48eb-b222-edf6338b6aed] succeeded in 0.7162
513980001677s: (True, '')
Received task: assets.tasks.push_system_user.push_system_user_to_assets[79570e78-2777-4940-81ee-e34c127eb2c7]
Received task: assets.tasks.asset_connectivity.test_asset_connectivity_util[101f1221-02e0-445b-97f0-5b4a6532e804]
Task assets.tasks.asset_connectivity.test_asset_connectivity_util[101f1221-02e0-445b-97f0-5b4a6532e804] raised unexpected: Op
erationalError('database is locked',)
Traceback (most recent call last):
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/jumpserver/jumpserver/apps/assets/tasks/asset_connectivity.py", line 52, in test_asset_connectivity_util
    created_by=created_by,
  File "/data/jumpserver/jumpserver/apps/ops/utils.py", line 36, in update_or_create_ansible_task
    defaults=defaults, name=task_name, created_by=created_by
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 564, in update_or_create
    obj.save(using=self.db)
  File "/data/jumpserver/jumpserver/apps/ops/models/adhoc.py", line 142, in save
    instance = super().save(**kwargs)
File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1426, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
    cursor.execute(sql, params)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
Task assets.tasks.push_system_user.push_system_user_to_assets[79570e78-2777-4940-81ee-e34c127eb2c7] raised unexpected: OperationalError('database is locked',)
Traceback (most recent call last):
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/jumpserver/jumpserver/apps/assets/tasks/push_system_user.py", line 192, in push_system_user_to_assets
    return push_system_user_util(system_user, assets, task_name)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/celery/app/trace.py", line 630, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/data/jumpserver/jumpserver/apps/assets/tasks/push_system_user.py", line 169, in push_system_user_util
    created_by=system_user.org_id,
  File "/data/jumpserver/jumpserver/apps/ops/utils.py", line 36, in update_or_create_ansible_task
    defaults=defaults, name=task_name, created_by=created_by
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 564, in update_or_create
    obj.save(using=self.db)
  File "/data/jumpserver/jumpserver/apps/ops/models/adhoc.py", line 142, in save
      instance = super().save(**kwargs)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1426, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
    cursor.execute(sql, params)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/jumpserver/py3_venv/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
Received task: assets.tasks.admin_user_connectivity.test_admin_user_connectivity_period[05d64239-d40a-417d-b7da-cfd52accd014]
Task assets.tasks.admin_user_connectivity.test_admin_user_connectivity_period[05d64239-d40a-417d-b7da-cfd52accd014] succeeded in 0.0010728210036177188s: None

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@WangZhiLoong 推荐使用mysql数据库
