### ISSUE TITLE
检测配置或连接性测试出错

### ISSUE THREAD

**Issue by drscrewdriver** [jumpserver/jumpserver#3750]
检测配置或连接性测试出错无法正常显示结果

##### 使用版本
1.5.6

##### 问题复现步骤
1点击后弹窗报错
'ascii' codec can't encode characters in position 20-23: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/jumpserver-1.5.6/apps/ops/models/adhoc.py", line 323, in start
    print(_("{} Start task: {}").format(date_start_s, self.task.name))
  File "/opt/py3/lib64/python3.6/site-packages/celery/utils/log.py", line 235, in write
    self.logger.log(self.loglevel, safe_str(data))
  File "/usr/lib64/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/opt/jumpserver-1.5.6/apps/ops/celery/logger.py", line 148, in emit
    self.f.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 20-23: ordinal not in range(128)

**Comment by wojiushixiaobai** [comment]
@drscrewdriver 数据库字符集检查下
