### ISSUE TITLE
pip install requirements.txt抛出异常

### ISSUE THREAD

**Issue by marksugar** [jumpserver/jumpserver#3760]
[简述你的问题]

无法正常安装jumpserver

使用yum安装 python36 python36-devel
系统环境:
```
(py3) [root@********* /opt/jumpserver]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
(py3) [root@********* /opt/jumpserver]# python -V
Python 3.6.8
```
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

克隆最新的版本
```
(py3) [root@********* /opt/jumpserver]# git log -1
commit 775f8f2ffd89419f1af7213c796f98021b9e3b92
Author: 老广 <ibuler@qq.com>
Date:   Wed Feb 26 16:18:24 2020 +0800

    Merge pull request #3722 from jumpserver/settings_bug
    
    Settings bug
```

##### 问题复现步骤
1. [步骤1]
```
(py3) [root@********* /opt]# pip install -r /opt/jumpserver/requirements/requirements.txt
Collecting amqp==2.1.4
  Using cached amqp-2.1.4-py2.py3-none-any.whl (49 kB)
Collecting ansible==2.8.2
  Using cached ansible-2.8.2.tar.gz (14.3 MB)
Collecting asn1crypto==0.24.0
  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl (101 kB)
Collecting bcrypt==3.1.4
  Using cached bcrypt-3.1.4-cp36-cp36m-manylinux1_x86_64.whl (54 kB)
Collecting billiard==3.5.0.3
  Using cached billiard-3.5.0.3-py3-none-any.whl (89 kB)
Collecting boto3==1.6.5
  Using cached boto3-1.6.5-py2.py3-none-any.whl (128 kB)
Collecting botocore==1.9.5
  Using cached botocore-1.9.5-py2.py3-none-any.whl (4.1 MB)
Collecting celery==4.1.0
  Using cached celery-4.1.0-py2.py3-none-any.whl (400 kB)
Collecting certifi==2018.1.18
  Using cached certifi-2018.1.18-py2.py3-none-any.whl (151 kB)
Collecting cffi==1.11.5
  Using cached cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl (421 kB)
Requirement already satisfied: chardet==3.0.4 in ./py3/lib/python3.6/site-packages (from -r /opt/jumpserver/requirements/requirements.txt (line 11)) (3.0.4)
Collecting configparser==3.5.0
  Using cached configparser-3.5.0.tar.gz (39 kB)
Collecting coreapi==2.3.3
  Using cached coreapi-2.3.3-py2.py3-none-any.whl (25 kB)
Collecting coreschema==0.0.4
  Using cached coreschema-0.0.4.tar.gz (10 kB)
Collecting cryptography==2.3.1
  Using cached cryptography-2.3.1-cp34-abi3-manylinux1_x86_64.whl (2.1 MB)
Collecting decorator==4.1.2
  Using cached decorator-4.1.2-py2.py3-none-any.whl (9.1 kB)
Collecting Django==2.1.11
  Using cached Django-2.1.11-py3-none-any.whl (7.3 MB)
Collecting django-auth-ldap==1.7.0
  Using cached django_auth_ldap-1.7.0-py2.py3-none-any.whl (23 kB)
Collecting django-bootstrap3==9.1.0
  Using cached django-bootstrap3-9.1.0.tar.gz (39 kB)
Collecting django-celery-beat==1.4.0
  Using cached django_celery_beat-1.4.0-py2.py3-none-any.whl (30 kB)
Collecting django-filter==2.0.0
  Using cached django_filter-2.0.0-py3-none-any.whl (69 kB)
Collecting django-formtools==2.1
  Using cached django_formtools-2.1-py2.py3-none-any.whl (132 kB)
Collecting django-ranged-response==0.2.0
  Using cached django-ranged-response-0.2.0.tar.gz (3.0 kB)
Collecting django-redis-cache==1.7.1
  Using cached django-redis-cache-1.7.1.tar.gz (13 kB)
Collecting django-rest-swagger==2.1.2
  Using cached django_rest_swagger-2.1.2-py2.py3-none-any.whl (747 kB)
Collecting django-simple-captcha==0.5.6
  Using cached django-simple-captcha-0.5.6.zip (226 kB)
Collecting djangorestframework==3.9.4
  Using cached djangorestframework-3.9.4-py2.py3-none-any.whl (911 kB)
Collecting djangorestframework-bulk==0.2.1
  Using cached djangorestframework-bulk-0.2.1.tar.gz (13 kB)
Collecting docutils==0.14
  Using cached docutils-0.14-py3-none-any.whl (543 kB)
Collecting ecdsa==0.13.3
  Using cached ecdsa-0.13.3-py2.py3-none-any.whl (52 kB)
Collecting enum-compat==0.0.2
  Using cached enum-compat-0.0.2.tar.gz (1.3 kB)
Collecting ephem==3.7.6.0
  Using cached ephem-3.7.6.0.tar.gz (739 kB)
Collecting eventlet==0.24.1
  Using cached eventlet-0.24.1-py2.py3-none-any.whl (219 kB)
Collecting ForgeryPy==0.1
  Using cached ForgeryPy-0.1.tar.gz (27 kB)
Collecting greenlet==0.4.14
  Using cached greenlet-0.4.14-cp36-cp36m-manylinux1_x86_64.whl (41 kB)
Collecting gunicorn==19.9.0
  Using cached gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)
Collecting idna==2.6
  Using cached idna-2.6-py2.py3-none-any.whl (56 kB)
Collecting itsdangerous==0.24
  Using cached itsdangerous-0.24.tar.gz (46 kB)
Collecting itypes==1.1.0
  Using cached itypes-1.1.0.tar.gz (2.2 kB)
Collecting Jinja2==2.10.1
  Using cached Jinja2-2.10.1-py2.py3-none-any.whl (124 kB)
Collecting jmespath==0.9.3
  Using cached jmespath-0.9.3-py2.py3-none-any.whl (23 kB)
Collecting kombu==4.0.2
  Using cached kombu-4.0.2-py2.py3-none-any.whl (178 kB)
Collecting ldap3==2.4
  Using cached ldap3-2.4-py2.py3-none-any.whl (373 kB)
Collecting MarkupSafe==1.0
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/py3/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3ks9fpcg/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3ks9fpcg/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3ks9fpcg/MarkupSafe/pip-egg-info
         cwd: /tmp/pip-install-3ks9fpcg/MarkupSafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3ks9fpcg/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
尝试`pip install -r /opt/jumpserver/requirements/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/`也抛出同样的错误

thanks

**Comment by marksugar** [comment]
这个问题在https://github.com/pallets/markupsafe/issues/57复现

**Comment by marksugar** [comment]
当我在`requirements.txt`将`MarkupSafe=1.0`修改为`MarkupSafe=1.1`解决了这个问题。
但最后抛出了新的异常。
请注意
thanks

**Comment by bailiang27** [comment]
2020-03-10 centos 7 升级到最新补丁。
requirements.txt 中
MarkupSafe==1.0.0 更改为 1.1.1
PyNaCl==1.2.1  更改为 1.3.0
pyasn1==0.4.2  更改为 0.4.8
drf-yasg==1.9.1 更改为 1.17.1
aliyun-python-sdk-core-v3==2.9.1  更改为 2.13.11
安装通过。但是还不知道对使用有什么影响。毕竟不是搞开发的，对基础库的更新没怎么关注。


--------------------------------------------------------------------------------------------------------------
requirements.txt
--------------------------------------------------------------------------------------------------------------


amqp==2.1.4
ansible==2.8.2
asn1crypto==0.24.0
bcrypt==3.1.4
billiard==3.5.0.3
boto3==1.6.5
botocore==1.9.5
celery==4.1.0
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
configparser==3.5.0
coreapi==2.3.3
coreschema==0.0.4
cryptography==2.3.1
decorator==4.1.2
Django==2.1.11
django-auth-ldap==1.7.0
django-bootstrap3==9.1.0
django-celery-beat==1.4.0
django-filter==2.0.0
django-formtools==2.1
django-ranged-response==0.2.0
django-redis-cache==1.7.1
django-rest-swagger==2.1.2
django-simple-captcha==0.5.6
djangorestframework==3.9.4
djangorestframework-bulk==0.2.1
docutils==0.14
ecdsa==0.13.3
enum-compat==0.0.2
ephem==3.7.6.0
eventlet==0.24.1
ForgeryPy==0.1
greenlet==0.4.14
gunicorn==19.9.0
idna==2.6
itsdangerous==0.24
itypes==1.1.0
Jinja2==2.10.1
jmespath==0.9.3
kombu==4.0.2
ldap3==2.4
MarkupSafe==1.1.1
mysqlclient==1.3.14
olefile==0.44
openapi-codec==1.3.2
paramiko==2.4.2
passlib==1.7.1
Pillow==6.2.0
pyasn1==0.4.8
pycparser==2.19
pycrypto==2.6.1
pyotp==2.2.6
PyNaCl==1.3.0
python-dateutil==2.6.1
python-gssapi==0.6.4
pytz==2018.3
PyYAML==5.1
redis==2.10.6
requests==2.22.0
jms-storage==0.0.26
s3transfer==0.1.13
simplejson==3.13.2
six==1.11.0
sshpubkeys==3.1.0
uritemplate==3.0.0
urllib3==1.25.2
vine==1.1.4
drf-yasg==1.17.1
Werkzeug==0.15.3
drf-nested-routers==0.91
aliyun-python-sdk-core-v3==2.13.11
aliyun-python-sdk-ecs==4.10.1
python-keycloak==0.13.3
python-keycloak-client==0.1.3
rest_condition==1.0.3
python-ldap==3.1.0
tencentcloud-sdk-python==3.0.40
django-radius==1.3.3
ipip-ipdb==1.2.1
django-redis-sessions==0.6.1
unicodecsv==0.14.1
python-daemon==2.2.3
httpsig==1.3.0
treelib==1.5.3
django-proxy==1.2.1
flower==0.9.3
channels-redis==2.4.0
channels==2.3.0
daphne==2.3.0
psutil==5.6.5

**Comment by marksugar** [comment]
如果在centos安装抛出`” ERROR: Failed building wheel for mysqlclient“`，请执行`yum install -y openssl-devel`

**Comment by ibuler** [comment]
https://github.com/jumpserver/jumpserver/blob/dev/requirements/requirements.txt#L46 
dev已更改，等待新版本发布
