### ISSUE TITLE
File "./jms", line 26, in <module>     from apps.jumpserver import const

### ISSUE THREAD

**Issue by kwz1993** [jumpserver/jumpserver#3825]
[简述你的问题]
安装过程中，启动 ./jms start 报错
Traceback (most recent call last):
  File "./jms", line 26, in <module>
    from apps.jumpserver import const
  File "/opt/jumpserver/apps/jumpserver/const.py", line 11, in <module>
    CONFIG = ConfigManager.load_user_config()
  File "/opt/jumpserver/apps/jumpserver/conf.py", line 482, in load_user_config
    elif manager.load_from_yml():
  File "/opt/jumpserver/apps/jumpserver/conf.py", line 467, in load_from_yml
    loaded = self.from_yaml(i)
  File "/opt/jumpserver/apps/jumpserver/conf.py", line 420, in from_yaml
    obj = yaml.safe_load(f)
  File "/opt/py3/lib64/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/opt/py3/lib64/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/py3/lib64/python3.6/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/opt/py3/lib64/python3.6/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/opt/py3/lib64/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/opt/py3/lib64/python3.6/site-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "/opt/jumpserver/config.yml", line 8, column 1
##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
config.yml 设置有误，注意格式。faq文档有相应说明
```
- config.yml 设置说明
# 常见的错误就是字段为空和: 后面少一个空格, 参考下面, 请勿照抄
# SECRET_KEY: 5RLbBjm8AkMSvnft...  # 不要忽略: 后面的空格, 不支持纯数字
# BOOTSTRAP_TOKEN: ihR4WG4gRShCnpQL...  # 不要忽略: 后面的空格, 不支持纯数字
# DB_PASSWORD: '123456'  # 密码纯数字用单引号括起来
# DB_PASSWORD: cPzxaiUAtA5IkdT2...  # 非纯数字可以不用单引号
# REDIS_PASSWORD: '888888'  # 密码纯数字用单引号括起来
# REDIS_PASSWORD: Ma5bzA3gVK5oY17l...  # 非纯数字可以不用单引号
```

**Comment by kwz1993** [comment]
已解决，感谢。
