### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by ChaosYin0912** [jumpserver/jumpserver#3831]
[简述你的问题]
在启动时报错

##### 使用版本
[请提供你使用的Jumpserver版本 1.x.x 注: 0.3.x不再提供支持]
1.5.7
##### 问题复现步骤
在jumpserver根目录下运行./jms start all

##### 具体表现[截图可能会更好些,最好能截全]
![image](https://user-images.githubusercontent.com/52448641/77624191-63402f00-6f7c-11ea-94cb-0b7e0ce6065d.png)
![image](https://user-images.githubusercontent.com/52448641/77624073-3a1f9e80-6f7c-11ea-8358-664269a26a4a.png)
![image](https://user-images.githubusercontent.com/52448641/77624086-3ee45280-6f7c-11ea-8e07-1437f1749127.png)

##### 其他
2020-03-26 01:05:06 Thu Mar 26 01:05:06 2020
2020-03-26 01:05:06 Jumpserver version 1.5.7, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
2020-03-26 01:05:06 Check database connection ...
users
 [X] 0001_initial
 [X] 0002_auto_20171225_1157_squashed_0019_auto_20190304_1459 (18 squashed migrations)
 [X] 0020_auto_20190612_1825
 [X] 0021_auto_20190625_1104
 [X] 0022_auto_20190625_1105
 [X] 0023_auto_20190724_1525
 [X] 0024_auto_20191118_1612
 [X] 0025_auto_20200206_1216
2020-03-26 01:05:11 Database connect success
2020-03-26 01:05:11 Check database structure change ...
2020-03-26 01:05:11 Migrate model change to database ...
Operations to perform:
  Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  No migrations to apply.
2020-03-26 01:05:16 Collect static files
2020-03-26 01:05:20 Collect static files done

- Start Celery as Distributed Task Queue: Ansible

- Start Celery as Distributed Task Queue: Celery

- Start Beat as Periodic Task Scheduler

- Start Flower as Task Monitor

- Start Daphne ASGI WS Server
2020-03-26 01:05:32 Check service status: gunicorn -> running at 11946
2020-03-26 01:05:32 Check service status: celery_ansible -> stopped with code: 1(12055)
2020-03-26 01:05:32 Check service status: celery_default -> stopped with code: 1(12110)
2020-03-26 01:05:32 Check service status: beat -> stopped with code: 1(12247)
2020-03-26 01:05:32 Check service status: flower -> stopped with code: 1(12509)
2020-03-26 01:05:32 Check service status: daphne -> running at 12551

- Start Celery as Distributed Task Queue: Ansible
2020-03-26 01:05:34 > Find celery_ansible stopped, retry 1, 12847

- Start Celery as Distributed Task Queue: Celery
2020-03-26 01:05:34 > Find celery_default stopped, retry 1, 12849

- Start Beat as Periodic Task Scheduler
2020-03-26 01:05:34 > Find beat stopped, retry 1, 12850

- Start Flower as Task Monitor
2020-03-26 01:05:34 > Find flower stopped, retry 1, 12851
2020-03-26 01:06:04 Check service status: gunicorn -> running at 11946
2020-03-26 01:06:04 Check service status: celery_ansible -> stopped with code: 1(12847)
2020-03-26 01:06:04 Check service status: celery_default -> stopped with code: 1(12849)
2020-03-26 01:06:04 Check service status: beat -> stopped with code: 1(12850)
2020-03-26 01:06:04 Check service status: flower -> stopped with code: 1(12851)
2020-03-26 01:06:04 Check service status: daphne -> running at 12551

- Start Celery as Distributed Task Queue: Ansible
2020-03-26 01:06:06 > Find celery_ansible stopped, retry 2, 14419

- Start Celery as Distributed Task Queue: Celery
2020-03-26 01:06:06 > Find celery_default stopped, retry 2, 14420

- Start Beat as Periodic Task Scheduler
2020-03-26 01:06:06 > Find beat stopped, retry 2, 14421

- Start Flower as Task Monitor
2020-03-26 01:06:06 > Find flower stopped, retry 2, 14422
2020-03-26 01:06:36 Check service status: gunicorn -> running at 11946
2020-03-26 01:06:36 Check service status: celery_ansible -> stopped with code: 1(14419)
2020-03-26 01:06:36 Check service status: celery_default -> stopped with code: 1(14420)
2020-03-26 01:06:36 Check service status: beat -> stopped with code: 1(14421)
2020-03-26 01:06:36 Check service status: flower -> stopped with code: 1(14422)
2020-03-26 01:06:36 Check service status: daphne -> running at 12551

- Start Celery as Distributed Task Queue: Ansible
2020-03-26 01:06:38 > Find celery_ansible stopped, retry 3, 15950

- Start Celery as Distributed Task Queue: Celery
2020-03-26 01:06:38 > Find celery_default stopped, retry 3, 15951

- Start Beat as Periodic Task Scheduler
2020-03-26 01:06:38 > Find beat stopped, retry 3, 15953

- Start Flower as Task Monitor
2020-03-26 01:06:38 > Find flower stopped, retry 3, 15954
2020-03-26 01:07:08 Check service status: gunicorn -> running at 11946
2020-03-26 01:07:08 Check service status: celery_ansible -> stopped with code: 1(15950)
2020-03-26 01:07:08 Check service status: celery_default -> stopped with code: 1(15951)
2020-03-26 01:07:08 Check service status: beat -> stopped with code: 1(15953)
2020-03-26 01:07:08 Check service status: flower -> stopped with code: 1(15954)
2020-03-26 01:07:08 Check service status: daphne -> running at 12551

- Start Celery as Distributed Task Queue: Ansible
2020-03-26 01:07:10 > Find celery_ansible stopped, retry 4, 17478

- Start Celery as Distributed Task Queue: Celery
2020-03-26 01:07:10 > Find celery_default stopped, retry 4, 17479

- Start Beat as Periodic Task Scheduler
2020-03-26 01:07:10 > Find beat stopped, retry 4, 17480

- Start Flower as Task Monitor
2020-03-26 01:07:10 > Find flower stopped, retry 4, 17481
2020-03-26 01:07:40 Check service status: gunicorn -> running at 11946
2020-03-26 01:07:40 Check service status: celery_ansible -> stopped with code: 1(17478)
2020-03-26 01:07:40 Check service status: celery_default -> stopped with code: 1(17479)
2020-03-26 01:07:40 Check service status: beat -> stopped with code: 1(17480)
2020-03-26 01:07:40 Check service status: flower -> stopped with code: 1(17481)
2020-03-26 01:07:40 Check service status: daphne -> running at 12551
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./jms", line 536, in <module>
    start_services_and_watch(srv)
  File "./jms", line 405, in start_services_and_watch
    watch_services()
  File "./jms", line 351, in watch_services
    retry_start_stopped_services()
  File "./jms", line 307, in retry_start_stopped_services
    logging.info("Service start failed, exit: ", s)
Message: 'Service start failed, exit: '
Arguments: ('celery_ansible',)
Stop service: gunicorn Ok
celery_ansible is stopped
celery_default is stopped
beat is stopped
flower is stopped
Stop service: daphne Ok

[注:] 完成后请关闭 issue

**Comment by jianlinz** [comment]
请教一下 问题是怎么解决的 我也出现了同样问题

**Comment by jianlinz** [comment]
可否给个思路

**Comment by yuanchao-sh** [comment]
这是啥问题啊，升级升出来这个事

**Comment by gitgzz** [comment]
个人观点flower文件有问题。/存储位置/core/data/flower，
若主机上找不到文件的重启后立马进入容器位置在/opt/jumpserver/data/flower
建议查验flower文件权限，权限无误，将此文件备份，之后rm删除，重启会自行创建恢复。
