### ISSUE TITLE
安装完jumpserver后每次启动完jms服务后过一会就自动stop服务了，是为什么

### ISSUE THREAD

**Issue by whr845736938** [jumpserver/jumpserver#3838]
通过一站式安装完jumpserver后，启动jumpserver就会过几分钟服务自动stop，这是为什么。
`- Start Celery as Distributed Task Queue: Ansible
2020-03-27 08:08:47 > Find celery_ansible stopped, retry 2, 17960
- Start Celery as Distributed Task Queue: Ansible
2020-03-27 08:09:21 > Find celery_ansible stopped, retry 3, 17980
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./jumpserver/jms", line 536, in <module>
  File "./jumpserver/jms", line 405, in start_services_and_watch
  File "./jumpserver/jms", line 351, in watch_services
  File "./jumpserver/jms", line 307, in retry_start_stopped_services
Message: 'Service start failed, exit: '
Arguments: ('celery_ansible',)
Stop service: gunicorn Error
celery_ansible is stopped
celery_default is stopped
Stop service: beat Ok
Stop service: flower Ok
Stop service: daphne Ok

`

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
