### ISSUE TITLE
1.5.2版本升级到1.5.3和1.5.8版本报错Table 'perms_remoteapppermission_system_users' already exists

### ISSUE THREAD

**Issue by feiyu563** [jumpserver/jumpserver#3911]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 1.5.2 注: 0.3.x不再提供支持]

##### 问题复现步骤
1. [按照（https://docs.jumpserver.org/zh/docs/upgrade.html）该文档中（1.5.0 及之后版本升级到最新版本）进行升级后无法登录管理后台]

2.[尝试按照(https://docs.jumpserver.org/zh/docs/faq_upgrade.html) 升级常见问题中的（数据库表结构不完整导致升级失败的, 按如下内容进行处理）中的版本操作，错误依旧]

##### 具体表现[截图可能会更好些,最好能截全]

页面错误提示：

Server error occur, contact administrator

升级后启动 jms 错误信息如下：

```
2020-04-17 05:20:12 Fri Apr 17 05:20:12 2020
2020-04-17 05:20:12 Jumpserver version 1.5.8, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
2020-04-17 05:20:12 Check database connection ...
users
 [X] 0001_initial
 [X] 0002_auto_20171225_1157_squashed_0019_auto_20190304_1459 (18 squashed migrations)
 [X] 0020_auto_20190612_1825
 [X] 0021_auto_20190625_1104
 [X] 0022_auto_20190625_1105
 [ ] 0023_auto_20190724_1525
 [ ] 0024_auto_20191118_1612
 [ ] 0025_auto_20200206_1216
2020-04-17 05:20:14 Database connect success
2020-04-17 05:20:14 Check database structure change ...
2020-04-17 05:20:14 Migrate model change to database ...
Operations to perform:
  Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  Applying perms.0008_auto_20190911_1907... OK
  Applying assets.0037_auto_20190724_2002... OK
  Applying assets.0038_auto_20190911_1634... OK
  Applying perms.0009_remoteapppermission_system_users...Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1050, "Table 'perms_remoteapppermission_system_users' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/operations/fields.py", line 112, in database_forwards
    field,
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/schema.py", line 44, in add_field
    super().add_field(model, field)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 431, in add_field
    return self.create_model(field.remote_field.through)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1050, "Table 'perms_remoteapppermission_system_users' already exists")
2020-04-17 05:20:17 Collect static files
2020-04-17 05:20:19 Collect static files done

- Start Celery as Distributed Task Queue: Ansible

- Start Celery as Distributed Task Queue: Celery

- Start Beat as Periodic Task Scheduler

- Start Flower as Task Monitor

- Start Daphne ASGI WS Server
```

登录jumpserver日志中报错：

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/generics.py", line 192, in post
    return self.create(request, *args, **kwargs)
  File "/opt/jumpserver/apps/terminal/api_v2/terminal.py", line 39, in create
    serializer.is_valid(raise_exception=True)
  File "/opt/jumpserver/apps/terminal/serializers_v2/terminal.py", line 36, in is_valid
    valid = self.sa_serializer.is_valid(raise_exception=True)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/serializers.py", line 434, in run_validation
    value = self.to_internal_value(data)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/serializers.py", line 493, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/opt/jumpserver/apps/users/serializers_v2/user.py", line 34, in validate_name
    if users.filter(email=email) or \
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 278, in __bool__
    self._fetch_all()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'users_user.mfa_level' in 'field list'")
```

**Comment by feiyu563** [comment]
尝试升级到1.5.3也是同样的情况，参考官方的文档直接升级也是上面的

```Table 'perms_remoteapppermission_system_users' already exists")```

尝试按照 

```数据库表结构不完整导致升级失败的, 按如下内容进行处理```

里面记录的方法先还原原本的版本，再次升级，情况依旧。

**Comment by feiyu563** [comment]
同时有尝试 删除掉 ```perms_remoteapppermission_system_users```表，再次执行升级，该表会自动创建，并且会产生新的报错

**Comment by feiyu563** [comment]
请问有人能帮忙看下吗

**Comment by wojiushixiaobai** [comment]
@feiyu563 23333. 
备份后，啥报错删啥，直到升级完成，然后看根据数据重要性手动进行数据还原

**Comment by feiyu563** [comment]
手动还原是指还原那些表是吗

**Comment by feiyu563** [comment]
删除掉 perms_remoteapppermission_system_users表后，再次启动./jms start -d 就开始报下面的错误了
```
2020-04-20 05:46:55 Mon Apr 20 05:46:55 2020
2020-04-20 05:46:55 Jumpserver version 1.5.8, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
2020-04-20 05:46:55 Check database connection ...
users
 [X] 0001_initial
 [X] 0002_auto_20171225_1157_squashed_0019_auto_20190304_1459 (18 squashed migrations)
 [X] 0020_auto_20190612_1825
 [X] 0021_auto_20190625_1104
 [X] 0022_auto_20190625_1105
 [ ] 0023_auto_20190724_1525
 [ ] 0024_auto_20191118_1612
 [ ] 0025_auto_20200206_1216
2020-04-20 05:46:58 Database connect success
2020-04-20 05:46:58 Check database structure change ...
2020-04-20 05:46:58 Migrate model change to database ...
Operations to perform:
  Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  Applying perms.0009_remoteapppermission_system_users...Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1005, "Can't create table 'jumpserver.#sql-643_c2c' (errno: 150)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 247, in apply_migration
    migration_recorded = True
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 110, in __exit__
    self.execute(sql)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1005, "Can't create table 'jumpserver.#sql-643_c2c' (errno: 150)")
2020-04-20 05:47:00 Collect static files
2020-04-20 05:47:03 Collect static files done

- Start Celery as Distributed Task Queue: Ansible

- Start Celery as Distributed Task Queue: Celery

- Start Beat as Periodic Task Scheduler

- Start Flower as Task Monitor

- Start Daphne ASGI WS Server
gunicorn is running: 8236
celery_ansible is running: 8247
celery_default is running: 8251
beat is running: 8256
flower is running: 8274
daphne is running: 8324

```

**Comment by feiyu563** [comment]
@wojiushixiaobai 可否帮忙分析或者远程协助下，我们这边两套jumpserver都是一样的情况

**Comment by feiyu563** [comment]
版本都是1.5.2，升级都是同样的报错

**Comment by yxiaoy6** [comment]
> 删除掉 perms_remoteapppermission_system_users表后，再次启动./jms start -d 就开始报下面的错误了
> 
> ```
> 2020-04-20 05:46:55 Mon Apr 20 05:46:55 2020
> 2020-04-20 05:46:55 Jumpserver version 1.5.8, more see https://www.jumpserver.org
> 
> - Start Gunicorn WSGI HTTP Server
> 2020-04-20 05:46:55 Check database connection ...
> users
>  [X] 0001_initial
>  [X] 0002_auto_20171225_1157_squashed_0019_auto_20190304_1459 (18 squashed migrations)
>  [X] 0020_auto_20190612_1825
>  [X] 0021_auto_20190625_1104
>  [X] 0022_auto_20190625_1105
>  [ ] 0023_auto_20190724_1525
>  [ ] 0024_auto_20191118_1612
>  [ ] 0025_auto_20200206_1216
> 2020-04-20 05:46:58 Database connect success
> 2020-04-20 05:46:58 Check database structure change ...
> 2020-04-20 05:46:58 Migrate model change to database ...
> Operations to perform:
>   Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, ops, orgs, perms, sessions, settings, terminal, tickets, users
> Running migrations:
>   Applying perms.0009_remoteapppermission_system_users...Traceback (most recent call last):
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
>     return self.cursor.execute(query, args)
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
>     self.errorhandler(self, exc, value)
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
>     raise errorvalue
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
>     res = self._query(query)
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
>     db.query(q)
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
>     _mysql.connection.query(self, query)
> _mysql_exceptions.OperationalError: (1005, "Can't create table 'jumpserver.#sql-643_c2c' (errno: 150)")
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "manage.py", line 28, in <module>
>     execute_from_command_line(sys.argv)
>   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
>     output = self.handle(*args, **options)
>   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
>     fake_initial=fake_initial,
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 247, in apply_migration
>     migration_recorded = True
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 110, in __exit__
>     self.execute(sql)
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
>     cursor.execute(sql, params)
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
>     return self.cursor.execute(query, args)
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
>     self.errorhandler(self, exc, value)
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
>     raise errorvalue
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
>     res = self._query(query)
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
>     db.query(q)
>   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
>     _mysql.connection.query(self, query)
> django.db.utils.OperationalError: (1005, "Can't create table 'jumpserver.#sql-643_c2c' (errno: 150)")
> 2020-04-20 05:47:00 Collect static files
> 2020-04-20 05:47:03 Collect static files done
> 
> - Start Celery as Distributed Task Queue: Ansible
> 
> - Start Celery as Distributed Task Queue: Celery
> 
> - Start Beat as Periodic Task Scheduler
> 
> - Start Flower as Task Monitor
> 
> - Start Daphne ASGI WS Server
> gunicorn is running: 8236
> celery_ansible is running: 8247
> celery_default is running: 8251
> beat is running: 8256
> flower is running: 8274
> daphne is running: 8324
> ```

你好，这个问题解决了吗，我升级后启动也报这种错

**Comment by feiyu563** [comment]
没有解决



---原始邮件---
发件人: "yxiaoy6"<notifications@github.com&gt;
发送时间: 2020年6月16日(周二) 中午12:24
收件人: "jumpserver/jumpserver"<jumpserver@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"feiyu563"<244217140@qq.com&gt;;
主题: Re: [jumpserver/jumpserver] 1.5.2版本升级到1.5.3和1.5.8版本报错Table 'perms_remoteapppermission_system_users' already exists (#3911)




  
删除掉 perms_remoteapppermission_system_users表后，再次启动./jms start -d 就开始报下面的错误了
 2020-04-20 05:46:55 Mon Apr 20 05:46:55 2020 2020-04-20 05:46:55 Jumpserver version 1.5.8, more see https://www.jumpserver.org - Start Gunicorn WSGI HTTP Server 2020-04-20 05:46:55 Check database connection ... users  [X] 0001_initial  [X] 0002_auto_20171225_1157_squashed_0019_auto_20190304_1459 (18 squashed migrations)  [X] 0020_auto_20190612_1825  [X] 0021_auto_20190625_1104  [X] 0022_auto_20190625_1105  [ ] 0023_auto_20190724_1525  [ ] 0024_auto_20191118_1612  [ ] 0025_auto_20200206_1216 2020-04-20 05:46:58 Database connect success 2020-04-20 05:46:58 Check database structure change ... 2020-04-20 05:46:58 Migrate model change to database ... Operations to perform:   Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, ops, orgs, perms, sessions, settings, terminal, tickets, users Running migrations:   Applying perms.0009_remoteapppermission_system_users...Traceback (most recent call last):   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute     return self.cursor.execute(sql, params)   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute     return self.cursor.execute(query, args)   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute     self.errorhandler(self, exc, value)   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler     raise errorvalue   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute     res = self._query(query)   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query     db.query(q)   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query     _mysql.connection.query(self, query) _mysql_exceptions.OperationalError: (1005, "Can't create table 'jumpserver.#sql-643_c2c' (errno: 150)") The above exception was the direct cause of the following exception: Traceback (most recent call last):   File "manage.py", line 28, in <module&gt;     execute_from_command_line(sys.argv)   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line     utility.execute()   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute     self.fetch_command(subcommand).run_from_argv(self.argv)   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv     self.execute(*args, **cmd_options)   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute     output = self.handle(*args, **options)   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped     res = handle_func(*args, **kwargs)   File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle     fake_initial=fake_initial,   File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)   File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)   File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 247, in apply_migration     migration_recorded = True   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 110, in __exit__     self.execute(sql)   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute     cursor.execute(sql, params)   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers     return executor(sql, params, many, context)   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute     return self.cursor.execute(sql, params)   File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__     raise dj_exc_value.with_traceback(traceback) from exc_value   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute     return self.cursor.execute(sql, params)   File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute     return self.cursor.execute(query, args)   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute     self.errorhandler(self, exc, value)   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler     raise errorvalue   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute     res = self._query(query)   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query     db.query(q)   File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query     _mysql.connection.query(self, query) django.db.utils.OperationalError: (1005, "Can't create table 'jumpserver.#sql-643_c2c' (errno: 150)") 2020-04-20 05:47:00 Collect static files 2020-04-20 05:47:03 Collect static files done - Start Celery as Distributed Task Queue: Ansible - Start Celery as Distributed Task Queue: Celery - Start Beat as Periodic Task Scheduler - Start Flower as Task Monitor - Start Daphne ASGI WS Server gunicorn is running: 8236 celery_ansible is running: 8247 celery_default is running: 8251 beat is running: 8256 flower is running: 8274 daphne is running: 8324   
你好，这个问题解决了吗，我升级后启动也报这种错

**Comment by wojiushixiaobai** [comment]
暂时无法验证问题，手动测试是没有问题的。可以尝试手动修复表结构看看
