### ISSUE TITLE
1.5.8 jumpserver 程序自动挂掉

### ISSUE THREAD

**Issue by kaibinyuan** [jumpserver/jumpserver#3920]
[简述你的问题]

启动jumpserver后，过段时间程序自动挂掉
##### 使用版本
1.5.8

##### 问题复现步骤
1. ./jms start
2. 过几分钟

##### 具体表现[截图可能会更好些,最好能截全]
2020-04-18 19:47:16 Check service status: daphne -> running at 6143
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./jms", line 536, in <module>
    start_services_and_watch(srv)
  File "./jms", line 405, in start_services_and_watch
    watch_services()
  File "./jms", line 351, in watch_services
    retry_start_stopped_services()
  File "./jms", line 307, in retry_start_stopped_services
    logging.info("Service start failed, exit: ", s)
Message: 'Service start failed, exit: '
Arguments: ('celery_ansible',)
Stop service: gunicorn Error
celery_ansible is stopped
celery_default is stopped
Stop service: beat Ok
Stop service: flower Ok
Stop service: daphne Ok

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
@kaibinyuan 环境请一定要严格按照文档要求来。以下建议供参考：

python==3.6.x

请确认python依赖已经完整安装，并在启动jms_core前无遗留历史进程。
启动先可用
```
ps aux | grep py3

```

**Comment by kaibinyuan** [comment]
多谢解答，经常挂掉的原因应该是因为koko和guacamole未启动成功，导致心跳检测异常，jumpserver主程序自动挂掉。
