### ISSUE TITLE
ldap 用户第一次成功登陆， 注销后再次登陆 就报错 重复插入用户

### ISSUE THREAD

**Issue by tonyfud** [jumpserver/jumpserver#3964]
v1.5.8  

 ldap 用户第一次成功登陆， 注销后再次登陆 就报错 重复插入用户。。。

`2020-05-07 00:31:24 [ldap INFO] Authentication LDAP backend
2020-05-07 00:31:24 [ldap INFO] Authenticate user: None
2020-05-07 00:31:34 [ldap INFO] Authentication LDAP backend
2020-05-07 00:31:34 [ldap INFO] Authenticate user: 测试01( test01)
2020-05-07 00:32:18 [ldap INFO] Authentication LDAP backend
2020-05-07 00:32:18 [ldap INFO] Authenticate user: None
2020-05-07 00:32:27 [ldap INFO] Authentication LDAP backend
2020-05-07 00:32:27 [backend WARNING] (1062, "Duplicate entry ' test01' for key 'username'") while authenticating test01
2020-05-07 00:32:27 [log ERROR] Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry ' test01' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/opt/jumpserver/apps/authentication/views/login.py", line 85, in form_valid
    self.check_user_auth()
  File "/opt/jumpserver/apps/authentication/mixins.py", line 66, in check_user_auth
    public_key=public_key
  File "/opt/jumpserver/apps/authentication/utils.py", line 15, in check_user_valid
    password=password, public_key=public_key)
  File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/jumpserver/apps/authentication/backends/ldap.py", line 55, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 210, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 350, in authenticate
    self._get_or_create_user()
  File "/opt/py3/lib64/python3.6/site-packages/django_auth_ldap/backend.py", line 612, in _get_or_create_user
    self._user.save()
  File "/opt/jumpserver/apps/users/models/user.py", line 551, in save
    super().save(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
    cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry ' test01' for key 'username'")
^C`

**Comment by wojiushixiaobai** [comment]
@tonyfud 确定创建数据库的命令为：
```
create database jumpserver default charset 'utf8' collate 'utf8_bin';
```

**Comment by epoll-j** [comment]
同样的问题

**Comment by epoll-j** [comment]
> @tonyfud 确定创建数据库的命令为：
> 
> ```
> create database jumpserver default charset 'utf8' collate 'utf8_bin';
> ```

```
| users_user | CREATE TABLE `users_user` (
  `password` varchar(128) COLLATE utf8_bin NOT NULL,
  `last_login` datetime(6) DEFAULT NULL,
  `first_name` varchar(30) COLLATE utf8_bin NOT NULL,
  `last_name` varchar(150) COLLATE utf8_bin NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `date_joined` datetime(6) NOT NULL,
  `id` char(32) COLLATE utf8_bin NOT NULL,
  `username` varchar(128) COLLATE utf8_bin NOT NULL,
  `name` varchar(128) COLLATE utf8_bin NOT NULL,
  `email` varchar(128) COLLATE utf8_bin NOT NULL,
  `role` varchar(10) COLLATE utf8_bin NOT NULL,
  `avatar` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `wechat` varchar(128) COLLATE utf8_bin NOT NULL,
  `phone` varchar(20) COLLATE utf8_bin DEFAULT NULL,
  `private_key` longtext COLLATE utf8_bin,
  `public_key` longtext COLLATE utf8_bin,
  `comment` longtext COLLATE utf8_bin,
  `is_first_login` tinyint(1) NOT NULL,
  `date_expired` datetime(6) DEFAULT NULL,
  `created_by` varchar(30) COLLATE utf8_bin NOT NULL,
  `mfa_level` smallint(6) NOT NULL,
  `otp_secret_key` varchar(256) COLLATE utf8_bin DEFAULT NULL,
  `source` varchar(30) COLLATE utf8_bin NOT NULL,
  `date_password_last_updated` datetime(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `users_user_date_expired_2e2eb0b3` (`date_expired`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
```
数据库是正确的

**Comment by wang509020** [comment]
此问题是否有解决，我也遇到此问题，急待结果。

**Comment by wojiushixiaobai** [comment]
尚未复现，请更新新版本验证看看。
