### ISSUE TITLE
按照教程在Ubuntu部署，启动的时候出现的问题

### ISSUE THREAD

**Issue by yuanqi-pythoner** [jumpserver/jumpserver#4050]
按照官方部署（https://jumpserver.readthedocs.io/zh/latest/setup_by_ubuntu18.html）
使用jumpserver最新版
在执行到：./jms start all -d 的时候
出现错误如下：
Start Gunicorn WSGI HTTP Server
2020-05-29 14:10:30 Check database connection ...
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/opt/py3/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/py3/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/opt/py3/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/py3/lib/python3.7/site-packages/django/core/checks/model_checks.py", line 16, in check_all_models
    models = apps.get_models()
  File "/opt/py3/lib/python3.7/site-packages/django/apps/registry.py", line 178, in get_models
    self.check_models_ready()
  File "/opt/py3/lib/python3.7/site-packages/django/apps/registry.py", line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by wojiushixiaobai** [comment]
@yuanqi-pythoner 不支持python3.7 请仔细看文档，并严格按照文档执行
