### ISSUE TITLE
在ssh终端刷新机器列表时候出现：没有资产 的问题。

### ISSUE THREAD

**Issue by xupeng9** [jumpserver/jumpserver#4071]
[简述你的问题]
在secureCRT终端列出机器列表的时候出现：没有资产
过一会儿再 p又会正常。

##### 使用版本
Jumpserver版本 1.5.9 刚搭好的环境。

##### 问题复现步骤
1. 在secureCRT终端直接回车或输入命令P，直接返回：没有资产

##### 具体表现[截图可能会更好些,最好能截全]
![Foxmail20200603173742](https://user-images.githubusercontent.com/39824703/83621318-18b4e180-a5c1-11ea-82ea-d328e642a099.png)

##### 其他
jumpserver.log 和gunicorn.log 里报一样的错。

2020-06-03 17:19:08 [log ERROR] Internal Server Error: /api/v1/perms/users/a2cf4460-8117-4fbf-aebb-eac55e3018c8/assets/
Traceback (most recent call last):
  File "/opt/cdn-jms/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/cdn-jms/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/cdn-jms/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/cdn-jms/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/cdn-jms/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/cdn-jms/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/cdn-jms/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/cdn-jms/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/cdn-jms/lib/python3.6/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/opt/cdn-jms/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/opt/jumpserver/apps/perms/api/user_permission/user_permission_assets.py", line 49, in get_queryset
    queryset = self.util.get_assets().only(*self.only_fields).order_by(
  File "/opt/jumpserver/apps/common/utils/common.py", line 208, in wrapper
    result = func(*args, **kwargs)
  File "/opt/jumpserver/apps/perms/utils/asset_permission.py", line 403, in get_assets
    nodes_keys, extra_assets_ids=assets_ids
  File "/opt/jumpserver/apps/assets/models/node.py", line 359, in get_nodes_all_assets
    assets_ids = cls.get_nodes_all_assets_ids(nodes_keys)
  File "/opt/jumpserver/apps/assets/models/node.py", line 351, in get_nodes_all_assets_ids
    node_assets_ids = cls.tree().all_assets(key)
  File "/opt/jumpserver/apps/assets/utils.py", line 135, in all_assets
    if node.data is None:
AttributeError: 'NoneType' object has no attribute 'data'

koko.log 报错：

2020-06-03 17:50:04 [ERRO] Get user assets error: GET http://127.0.0.1:8080/api/v1/perms/users/a2cf4460-8117-4fbf-aebb-eac55e3018c8/assets/?limit=50&offset=0 failed, get code: 500, {"error": "Server internal error"}

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
请验证新版本是否仍然出现此问题，感谢反馈
