### ISSUE TITLE
docker 迁移jumpserver容器内mysql 无法启动

### ISSUE THREAD

**Issue by jingtiangihub** [jumpserver/jumpserver#4084]
[简述你的问题]
忘记备份数据到宿主机，导出数据后重启创建数据卷后报错
##### 使用版本
1.5.9

##### 问题复现步骤
1. 使用 
`docker run --name jms_all -d-p 8000:80 -p 2222:22 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_all:1.5.9`
启动
2. 运行一段时间，有运维数据
3.导出数据
`mkdir /opt/jumpserver
docker cp jms_all:/opt/jumpserver/data /opt/jumpserver/data
docker cp jms_all:/var/lib/mysql /opt/jumpserver/mysql`
4.docker run --name jms_all -d \
  -v /opt/jumpserver/data:/opt/jumpserver/data \
  -v /opt/jumpserver/mysql:/var/lib/mysql \
  -p 80:80 \
  -p 2222:22 \
  -e SECRET_KEY=$SECRET_KEY \
  -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN \
  jumpserver/jms_all:1.5.9

##### 具体表现[截图可能会更好些,最好能截全]
`200606 16:22:45 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
2020-06-06 16:22:45 Sat Jun  6 16:22:45 2020
2020-06-06 16:22:45 Jumpserver version 1.5.9, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
2020-06-06 16:22:45 Check database connection ...
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2006, "Can't connect to MySQL server on '127.0.0.1' (111)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/showmigrations.py", line 48, in handle
    return self.show_list(connection, options['app_label'])
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/showmigrations.py", line 67, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2006, "Can't connect to MySQL server on '127.0.0.1' (111)")`

##### 其他

完成后请关闭 issue

**Comment by jingtiangihub** [comment]
已确定为/var/lib/权限问题 改变mysql 用拥有便可解决
