### ISSUE TITLE
users.models.user.User.terminal.RelatedObjectDoesNotExist: User has no terminal.

### ISSUE THREAD

**Issue by zmleasy** [jumpserver/jumpserver#4186]
[简述你的问题]

##### 使用版本
Version 2.0.0 GPLv2

##### 问题复现步骤
日志报错如下：
tail -f jumpserver.log
2020-06-28 17:28:34 [log ERROR] Internal Server Error: /api/v1/terminal/terminals/config/
Traceback (most recent call last):
  File "/data/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/data/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/python3.6/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/data/py3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/py3/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/py3/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/data/py3/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/data/py3/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/jump/jumpserver-2.0.0/apps/terminal/api/terminal.py", line 144, in get
    terminal = user.terminal
  File "/data/py3/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 415, in __get__
    self.related.get_accessor_name()
users.models.user.User.terminal.RelatedObjectDoesNotExist: User has no terminal.

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
删掉终端，重新注册

**Comment by zmleasy** [comment]
依然报同样的错误
