### ISSUE TITLE
jms 不兼容 MariaDB 10.5.x 吗？

### ISSUE THREAD

**Issue by opsarno** [jumpserver/jumpserver#4224]
[简述你的问题]
```
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
```

##### 使用版本
系统：
```
CentOS Linux release 7.8.2003 (Core)
```

数据库：
```
MariaDB-common-10.5.4-1.el7.centos.x86_64
MariaDB-devel-10.5.4-1.el7.centos.x86_64
MariaDB-server-10.5.4-1.el7.centos.x86_64
MariaDB-compat-10.5.4-1.el7.centos.x86_64
MariaDB-client-10.5.4-1.el7.centos.x86_64
```

Jumpserver: 2.0.1

##### 问题复现步骤
1. pip install -r requirements.txt 遇到 mysqlcliient 编译安装失败问题，经过研究，增加软链解决。
```
# ll /usr/lib64/libmariadb*
lrwxrwxrwx 1 root root       24 Jul  1 16:32 /usr/lib64/libmariadb.a -> /usr/lib64/libmariadbd.a   # 新增的软链
-rw-r--r-- 1 root root   500740 Jun 24 00:10 /usr/lib64/libmariadbclient.a
-rw-r--r-- 1 root root 50528932 Jun 24 00:10 /usr/lib64/libmariadbd.a
lrwxrwxrwx 1 root root       17 Jun 30 18:21 /usr/lib64/libmariadbd.so -> libmariadbd.so.19
-rwxr-xr-x 1 root root 23742280 Jun 24 00:14 /usr/lib64/libmariadbd.so.19
```

2. 基于教程正常安装，启动时报错。

##### 具体表现[截图可能会更好些,最好能截全]
```
# ./jms start
2020-07-01 17:18:05 Wed Jul  1 17:18:05 2020
2020-07-01 17:18:05 Jumpserver version 2.0.0, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
2020-07-01 17:18:05 Check database connection ...
Traceback (most recent call last):
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: /data/service/jumpserver/venv/lib64/python3.6/site-packages/MySQLdb/_mysql.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/service/jumpserver/jumpserver/apps/orgs/models.py", line 10, in <module>
    class Organization(models.Model):
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 20, in <module>
    ) from err
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
2020-07-01 17:18:08 Check database connection ...
Traceback (most recent call last):
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: /data/service/jumpserver/venv/lib64/python3.6/site-packages/MySQLdb/_mysql.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/service/jumpserver/jumpserver/apps/orgs/models.py", line 10, in <module>
    class Organization(models.Model):
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/service/jumpserver/venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 20, in <module>
    ) from err
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
```

##### 其他

[注:] 完成后请关闭 issue

**Comment by opsarno** [comment]
切换到 MySQL 8.X 可以正常启动。

```
mysql-community-client-8.0.20-1.el7.x86_64
mysql-community-common-8.0.20-1.el7.x86_64
mysql-community-libs-8.0.20-1.el7.x86_64
mysql-community-server-8.0.20-1.el7.x86_64
mysql-community-devel-8.0.20-1.el7.x86_64

**Comment by opsarno** [comment]
建议大家还是用 MySQL 作为数据库，可以自动的解决依赖安装，也不会有任何奇葩问题，MariaDB 我放弃了。
