### ISSUE TITLE
docker 启动日志报错数据库连接错误, TypeError: connect() argument 3 must be str, not int

### ISSUE THREAD

**Issue by zhangge3992513** [jumpserver/jumpserver#4266]
[简述你的问题]
docker 启动时, 启动日志报错
TypeError: connect() argument 3 must be str, not int
##### 使用版本
docker镜像: 2.0.0, 以及latest

##### 问题复现步骤
```bash
docker run --name jumpserver_all -d -p 10080:80 -p 12222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN -e DB_HOST=172.17.0.5 -e DB_PORT=3306 -e DB_USER=jumpserver -e DB_PASSWORD=123456 -e DB_NAME=jumpserver -e REDIS_HOST=172.17.0.8 -e REDIS_PORT=6379 -e REDIS_PASSWORD=123456 jumpserver/jms_all:latest
```

##### 具体表现

```bash
2020-07-08 11:20:05 Check database connection ...
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/showmigrations.py", line 48, in handle
    return self.show_list(connection, options['app_label'])
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/showmigrations.py", line 67, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: connect() argument 3 must be str, not int
2020-07-08 11:20:09 Check database connection ...
```

**Comment by zhangge3992513** [comment]
谁能救救我

**Comment by zhangge3992513** [comment]
问题解决
将`DB_PASSWORD=123456` 改为 `DB_PASSWORD="'123456'"`
