### ISSUE TITLE
jumpserver 2.0.2 批量执行命令出错

### ISSUE THREAD

**Issue by todevops** [jumpserver/jumpserver#4382]
[简述你的问题]

##### 使用版本
JumpServer 2.0.2

##### 问题复现步骤
1. 执行批量任务
![image](https://user-images.githubusercontent.com/57765353/88077383-cb5ef480-cbad-11ea-8771-98f61df211ff.png)

2. 报错日志
选择左侧资产, 选择运行的系统用户，批量执行命令已选择资产:172.28.1.31, 172.28.209.42
总共：2 
等待
---------- 任务开始 ----------
Task ops.tasks.run_command_execution[cd26f596-6161-4823-941f-565bfee460b3] raised unexpected: AttributeError("'str' object has no attribute 'search'",)
Traceback (most recent call last):
  File "/opt/virtualenv/lib64/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/virtualenv/lib64/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver-v2.0.2/apps/ops/tasks.py", line 61, in run_command_execution
    execution.run()
  File "/opt/jumpserver-v2.0.2/apps/ops/models/command.py", line 76, in run
    ok, msg = self.run_as.is_command_can_run(self.command)
  File "/opt/jumpserver-v2.0.2/apps/assets/models/user.py", line 176, in is_command_can_run
    action, matched_cmd = rule.match(command)
  File "/opt/jumpserver-v2.0.2/apps/assets/models/cmd_filter.py", line 87, in match
    found = self._pattern.search(data)
AttributeError: 'str' object has no attribute 'search'

##### 其他

[注:] 完成后请关闭 issue

**Comment by orangemio** [comment]
升级到2.1.0应该可以解决这个问题

**Comment by todevops** [comment]
> 升级到2.1.0应该可以解决这个问题

2.1.0才rc，不敢上这么新的版本啊
