### ISSUE TITLE
从2.0.2升级至2.1.0登录提示解密失败

### ISSUE THREAD

**Issue by r6c** [jumpserver/jumpserver#4406]
[简述你的问题]
docker 部署，从2.0.2升级至2.1.0登录提示解密失败
##### 使用版本
2.1.0
##### 问题复现步骤
1. [步骤1]
docker 已做持久化，启动参数一致，换成2.1.0、v2.1.0及latest都会出现登陆时解密失败
2. [步骤2]
降级回2.0.2，功能正常
##### 具体表现[截图可能会更好些,最好能截全]
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./jms", line 536, in <module>
    start_services_and_watch(srv)
  File "./jms", line 405, in start_services_and_watch
    watch_services()
  File "./jms", line 351, in watch_services
    retry_start_stopped_services()
  File "./jms", line 307, in retry_start_stopped_services
    logging.info("Service start failed, exit: ", s)
Message: 'Service start failed, exit: '
```

**Comment by wojiushixiaobai** [comment]
升级及迁移请保持 SECRET_KEY 与旧版本一致, 否则会导致数据库加密数据无法解密

**Comment by ibuler** [comment]
提供信息较少

**Comment by r6c** [comment]
SECRET_KEY 与旧版本一致,我是分开部署的，jms_core koko等分开，其中jms_core启动时会报错
```
2020-07-24 15:50:12 Fri Jul 24 15:50:12 2020
2020-07-24 15:50:12 Jumpserver version v2.1.0, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
2020-07-24 15:50:12 Check database connection ...
users
 [X] 0001_initial
 [X] 0002_auto_20171225_1157_squashed_0019_auto_20190304_1459 (18 squashed migrations)
 [X] 0020_auto_20190612_1825
 [X] 0021_auto_20190625_1104
 [X] 0022_auto_20190625_1105
 [X] 0023_auto_20190724_1525
 [X] 0024_auto_20191118_1612
 [X] 0025_auto_20200206_1216
 [X] 0026_auto_20200508_2105
 [X] 0027_auto_20200616_1503
2020-07-24 15:50:16 Database connect success
2020-07-24 15:50:16 Check database structure change ...
2020-07-24 15:50:16 Migrate model change to database ...
Operations to perform:
  Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
2020-07-24 15:50:20 Collect static files
2020-07-24 15:50:22 Collect static files done
```

**Comment by r6c** [comment]
根据提示 ` Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.` 运行后还是无法登录，提示解密失败。

**Comment by r6c** [comment]
降级回2.0.2，运行正常
```
2020-07-24 15:53:26 Fri Jul 24 15:53:26 2020
2020-07-24 15:53:26 Jumpserver version v2.0.2, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
2020-07-24 15:53:26 Check database connection ...
users
 [X] 0001_initial
 [X] 0002_auto_20171225_1157_squashed_0019_auto_20190304_1459 (18 squashed migrations)
 [X] 0020_auto_20190612_1825
 [X] 0021_auto_20190625_1104
 [X] 0022_auto_20190625_1105
 [X] 0023_auto_20190724_1525
 [X] 0024_auto_20191118_1612
 [X] 0025_auto_20200206_1216
 [X] 0026_auto_20200508_2105
 [X] 0027_auto_20200616_1503
2020-07-24 15:53:31 Database connect success
2020-07-24 15:53:31 Check database structure change ...
2020-07-24 15:53:31 Migrate model change to database ...
Operations to perform:
  Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  No migrations to apply.
2020-07-24 15:53:35 Collect static files
2020-07-24 15:53:37 Collect static files done
```

**Comment by r6c** [comment]
前端显示与 #4408 情况一致

**Comment by wojiushixiaobai** [comment]
无法复现
