### ISSUE TITLE
1.4.10 升级到 v2.1.0 报错

### ISSUE THREAD

**Issue by dmanbu** [jumpserver/jumpserver#4447]
[简述你的问题]
1.4.10 升级到 v2.1.0 报错，提示 Unknown column 'users_user.mfa_level' in 'field list'

##### 使用版本
v2.1.0

##### 问题复现步骤
1. 安装文档 https://docs.jumpserver.org/zh/master/admin-guide/upgrade/1.4.5-1.4.10/ 进行升级

##### 具体表现[截图可能会更好些,最好能截全]
```
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/generics.py", line 192, in post
    return self.create(request, *args, **kwargs)
  File "/opt/jumpserver/apps/terminal/api_v2/terminal.py", line 39, in create
    serializer.is_valid(raise_exception=True)
  File "/opt/jumpserver/apps/terminal/serializers_v2/terminal.py", line 36, in is_valid
    valid = self.sa_serializer.is_valid(raise_exception=True)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/serializers.py", line 434, in run_validation
    value = self.to_internal_value(data)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/serializers.py", line 493, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/opt/jumpserver/apps/users/serializers_v2/user.py", line 34, in validate_name
    if users.filter(email=email) or \
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 278, in __bool__
    self._fetch_all()
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'users_user.mfa_level' in 'field list'")
```

##### 其他

[注:] 完成后请关闭 issue

**Comment by dmanbu** [comment]
数据库缺了20多张表

**Comment by ibuler** [comment]
手动执行以下试试：

```
$ cd apps
$ python manage.py migrate 
```

**Comment by dmanbu** [comment]
> 手动执行以下试试：
> 
> ```
> $ cd apps
> $ python manage.py migrate 
> ```

试过了，又报了
```
django.db.utils.OperationalError: (1050, "Table 'applications_remoteapp' already exists")
```

**Comment by dmanbu** [comment]
我把 applications_remoteapp 表删了，运行 ```python manage.py migrate ```
又报了:
```
django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')
```

我尝试手动更改表结构，并且成功启动了，但通过SSH连接的时候，core服务却在报 
```
2020-08-06 11:34:03 [log ERROR] Internal Server Error: /api/v1/terminal/sessions/
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1364, "Field 'date_last_active' doesn't have a default value")
```
我该怎么解决这个问题？

**Comment by dmanbu** [comment]
目前，我通过自己整理SQL，实现了升级，自带的 manage.py migrate 没法用
整理SQL的时候，我发现了几个问题
比如，拿IP字段来说，涨到了 varchar(128) 明显是为了兼容 ipv6， 但还要不少表还是 char(39)，为什么不一次性改完？
还有，在不同表中，代表同一个意思的字段，如 asset.id 和 terminal_session.asset_id ，这两个字段的UUID应该是关联关系，但UUID的值却是两种形式，有些表加了横杠，有些表没有横杠，为什么不统一一下？

**Comment by yxiaoy6** [comment]
我升级时遇到类似无法创建表问题，最后解决是将库的character_set_database先改为其他类型，再改回utf8，再升级就可以了

![image](https://user-images.githubusercontent.com/43592152/90708152-b8823180-e2cb-11ea-8f15-418324d58ea5.png)

alter database databasename character set latin1;
alter database databasename character set utf8;

**Comment by dmanbu** [comment]
> 我升级时遇到类似无法创建表问题，最后解决是将库的character_set_database先改为其他类型，再改回utf8，再升级就可以了
> 
> ![image](https://user-images.githubusercontent.com/43592152/90708152-b8823180-e2cb-11ea-8f15-418324d58ea5.png)
> 
> alter database databasename character set latin1;
> alter database databasename character set utf8;

跟创建表没关系，我运行 python manage.py migrate 报了一堆错
比如：
表 applications_remoteapp 已经存在 ，这是旧表，不是多余，但没有跳过；
还有外键问题 “Cannot add foreign key constraint” ，migrate 没有进行处理
还有旧表有多余的字段，没有删除 Field 'date_last_active' doesn't have a default value

**Comment by yxiaoy6** [comment]
> > 我升级时遇到类似无法创建表问题，最后解决是将库的character_set_database先改为其他类型，再改回utf8，再升级就可以了
> > ![image](https://user-images.githubusercontent.com/43592152/90708152-b8823180-e2cb-11ea-8f15-418324d58ea5.png)
> > alter database databasename character set latin1;
> > alter database databasename character set utf8;
> 
> 跟创建表没关系，我运行 python manage.py migrate 报了一堆错
> 比如：
> 表 applications_remoteapp 已经存在 ，这是旧表，不是多余，但没有跳过；
> 还有外键问题 “Cannot add foreign key constraint” ，migrate 没有进行处理
> 还有旧表有多余的字段，没有删除 Field 'date_last_active' doesn't have a default value

这种情况我测试时也有遇到过，你可以尝试下我的方法，记得这个也执行一下set collation_database = utf8_general_ci;

**Comment by wojiushixiaobai** [comment]
Cannot add foreign key constraint 问题官方帮助文档里面写了处理方法

**Comment by WilliamGuozi** [comment]
> 我升级时遇到类似无法创建表问题，最后解决是将库的character_set_database先改为其他类型，再改回utf8，再升级就可以了
> 
> ![image](https://user-images.githubusercontent.com/43592152/90708152-b8823180-e2cb-11ea-8f15-418324d58ea5.png)
> 
> alter database databasename character set latin1;
> alter database databasename character set utf8;

亲测有效

**Comment by swq-github** [comment]
遇到了jumpserver 版本从1.5.7升级的2.2.2版本之后web页面打开提示internal server error错误
求解决

服务升级没有报错，start启动程序报正常
