### ISSUE TITLE
系统用户添加节点无法显示

### ISSUE THREAD

**Issue by kame000** [jumpserver/jumpserver#4500]
[简述你的问题]

![image](https://user-images.githubusercontent.com/20923887/90502182-04c05b00-e180-11ea-81a7-5b66c8f5e820.png)

##### 使用版本
[请提供你使用的JumpServer版本 如 2.0.1 注: 1.4及以下版本不再提供支持]
2.0

#### 日志

==> logs/celery_default.log <==
Received task: assets.tasks.common.add_nodes_assets_to_system_users[3b720b52-5728-4c3b-a79a-06ac3f91c89a]
Task assets.tasks.common.add_nodes_assets_to_system_users[3b720b52-5728-4c3b-a79a-06ac3f91c89a] raised unexpected: AttributeError("'NoneType' object has no attribute 'data'",)
Traceback (most recent call last):
  File "/data/py3/lib64/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data/py3/lib64/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/jumpserver/apps/assets/tasks/common.py", line 12, in add_nodes_assets_to_system_users
    assets = Node.get_nodes_all_assets(nodes_keys).values_list('id', flat=True)
  File "/data/jumpserver/apps/assets/models/node.py", line 373, in get_nodes_all_assets
    assets_ids = cls.get_nodes_all_assets_ids(nodes_keys)
  File "/data/jumpserver/apps/assets/models/node.py", line 365, in get_nodes_all_assets_ids
    node_assets_ids = cls.tree().all_assets(key)
  File "/data/jumpserver/apps/assets/utils.py", line 135, in all_assets
    if node.data is None:
AttributeError: 'NoneType' object has no attribute 'data'

![image](https://user-images.githubusercontent.com/20923887/90502575-a647ac80-e180-11ea-83de-f592d39b3ad2.png)

[注:] 完成后请关闭 issue

**Comment by jym503558564** [comment]
2.7.1版本未复现。系统用户添加某节点，刷新页面，资产列表即可显示刚添加节点下的所有资产。
升级至2.7.1版本
![image](https://user-images.githubusercontent.com/40739051/109279521-cef9de80-7854-11eb-82c0-7264ffb7f374.png)
