### ISSUE TITLE
在 windows10电脑上克隆代码后 pip 安装依赖一直报错

### ISSUE THREAD

**Issue by shenmou98** [jumpserver/jumpserver#4554]
[简述你的问题]
在 windows10电脑上克隆代码后（最新master分支代码 - 56fdf36e）， 使用 pip install -r requirements/requirements.txt安装依赖一直报错，已经安装了 Microsoft Visual  Studio 14.0 也不行； python版本 3.6；系统 windows10 （）;
所以想请问下，在windows10上开发,还有什么特别需要安装的依赖么；

```
cffi.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual
 Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for f
ull command output.
```

##### 使用版本
[最新master分支代码 - 56fdf36e]

##### 使用浏览器版本
[不涉及 ]

##### 问题复现步骤
1. [windows 10 电脑上， pip install -r requirements/requirements.txt]， 总之就是安装依赖各种报错，也百度google了很久，都找不出能完全解决的方法。
2. []

##### 具体表现[截图可能会更好些,最好能截全]
![微信截图_20200828190404](https://user-images.githubusercontent.com/10502050/91554333-8161ef00-e961-11ea-932a-b0a039c78550.png)

##### 其他

[注:] 完成后请关闭 issue

**Comment by shenmou98** [comment]
报错内容:
```
(Python36-venv-jumpserver) D:\admin-desktop\files\repository\github\jumpserver>pip install -
r requirements/requirements.txt
Requirement already satisfied: amqp==2.5.2 in d:\python\venv\python36-venv-jumpserver\lib\si
te-packages (from -r requirements/requirements.txt (line 1)) (2.5.2)
Collecting ansible==2.8.8
  Using cached ansible-2.8.8.tar.gz (12.7 MB)
Requirement already satisfied: asn1crypto==0.24.0 in d:\python\venv\python36-venv-jumpserver
\lib\site-packages (from -r requirements/requirements.txt (line 3)) (0.24.0)
Requirement already satisfied: bcrypt==3.1.4 in d:\python\venv\python36-venv-jumpserver\lib\
site-packages (from -r requirements/requirements.txt (line 4)) (3.1.4)
Requirement already satisfied: billiard==3.6.3.0 in d:\python\venv\python36-venv-jumpserver\
lib\site-packages (from -r requirements/requirements.txt (line 5)) (3.6.3.0)
Requirement already satisfied: boto3==1.12.14 in d:\python\venv\python36-venv-jumpserver\lib
\site-packages (from -r requirements/requirements.txt (line 6)) (1.12.14)
Requirement already satisfied: botocore==1.15.26 in d:\python\venv\python36-venv-jumpserver\
lib\site-packages (from -r requirements/requirements.txt (line 7)) (1.15.26)
Requirement already satisfied: celery==4.4.2 in d:\python\venv\python36-venv-jumpserver\lib\
site-packages (from -r requirements/requirements.txt (line 8)) (4.4.2)
Requirement already satisfied: certifi==2018.1.18 in d:\python\venv\python36-venv-jumpserver
\lib\site-packages (from -r requirements/requirements.txt (line 9)) (2018.1.18)
Requirement already satisfied: cffi==1.13.2 in d:\python\venv\python36-venv-jumpserver\lib\s
ite-packages (from -r requirements/requirements.txt (line 10)) (1.13.2)
Requirement already satisfied: chardet==3.0.4 in d:\python\venv\python36-venv-jumpserver\lib
\site-packages (from -r requirements/requirements.txt (line 11)) (3.0.4)
Requirement already satisfied: configparser==3.5.0 in d:\python\venv\python36-venv-jumpserve
r\lib\site-packages (from -r requirements/requirements.txt (line 12)) (3.5.0)
Requirement already satisfied: coreapi==2.3.3 in d:\python\venv\python36-venv-jumpserver\lib
\site-packages (from -r requirements/requirements.txt (line 13)) (2.3.3)
Requirement already satisfied: coreschema==0.0.4 in d:\python\venv\python36-venv-jumpserver\
lib\site-packages (from -r requirements/requirements.txt (line 14)) (0.0.4)
Requirement already satisfied: cryptography==2.8 in d:\python\venv\python36-venv-jumpserver\
lib\site-packages (from -r requirements/requirements.txt (line 15)) (2.8)
Requirement already satisfied: decorator==4.1.2 in d:\python\venv\python36-venv-jumpserver\l
ib\site-packages (from -r requirements/requirements.txt (line 16)) (4.1.2)
Requirement already satisfied: Django==2.2.13 in d:\python\venv\python36-venv-jumpserver\lib
\site-packages (from -r requirements/requirements.txt (line 17)) (2.2.13)
Collecting django-auth-ldap==1.7.0
  Using cached django_auth_ldap-1.7.0-py2.py3-none-any.whl (23 kB)
Collecting django-bootstrap3==14.1.0
  Using cached django_bootstrap3-14.1.0-py3-none-any.whl (23 kB)
Collecting django-celery-beat==1.4.0
  Using cached django_celery_beat-1.4.0-py2.py3-none-any.whl (30 kB)
Collecting django-filter==2.0.0
  Using cached django_filter-2.0.0-py3-none-any.whl (69 kB)
Collecting django-formtools==2.1
  Using cached django_formtools-2.1-py2.py3-none-any.whl (132 kB)
Collecting django-ranged-response==0.2.0
  Using cached django-ranged-response-0.2.0.tar.gz (3.0 kB)
Collecting django-redis-cache==2.1.1
  Using cached django_redis_cache-2.1.1-py3-none-any.whl (15 kB)
Collecting django-rest-swagger==2.1.2
  Using cached django_rest_swagger-2.1.2-py2.py3-none-any.whl (747 kB)
Collecting django-simple-captcha==0.5.6
  Using cached django-simple-captcha-0.5.6.zip (226 kB)
Collecting django-timezone-field==3.1
  Using cached django_timezone_field-3.1-py2.py3-none-any.whl (7.6 kB)
Collecting djangorestframework==3.9.4
  Using cached djangorestframework-3.9.4-py2.py3-none-any.whl (911 kB)
Collecting djangorestframework-bulk==0.2.1
  Using cached djangorestframework-bulk-0.2.1.tar.gz (13 kB)
Requirement already satisfied: docutils==0.14 in d:\python\venv\python36-venv-jumpserver\lib
\site-packages (from -r requirements/requirements.txt (line 30)) (0.14)
Collecting ecdsa==0.13.3
  Using cached ecdsa-0.13.3-py2.py3-none-any.whl (52 kB)
Collecting enum-compat==0.0.2
  Using cached enum-compat-0.0.2.tar.gz (1.3 kB)
Collecting ephem==3.7.6.0
  Using cached ephem-3.7.6.0.tar.gz (739 kB)
Collecting eventlet==0.24.1
  Using cached eventlet-0.24.1-py2.py3-none-any.whl (219 kB)
Collecting future==0.16.0
  Using cached future-0.16.0.tar.gz (824 kB)
Collecting ForgeryPy==0.1
  Using cached ForgeryPy-0.1.tar.gz (27 kB)
Collecting greenlet==0.4.14
  Using cached greenlet-0.4.14-cp36-cp36m-win_amd64.whl (16 kB)
Collecting gunicorn==19.9.0
  Using cached gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: idna==2.6 in d:\python\venv\python36-venv-jumpserver\lib\site
-packages (from -r requirements/requirements.txt (line 39)) (2.6)
Collecting itsdangerous==0.24
  Using cached itsdangerous-0.24.tar.gz (46 kB)
Requirement already satisfied: itypes==1.1.0 in d:\python\venv\python36-venv-jumpserver\lib\
site-packages (from -r requirements/requirements.txt (line 41)) (1.1.0)
Requirement already satisfied: Jinja2==2.10.1 in d:\python\venv\python36-venv-jumpserver\lib
\site-packages (from -r requirements/requirements.txt (line 42)) (2.10.1)
Requirement already satisfied: jmespath==0.9.3 in d:\python\venv\python36-venv-jumpserver\li
b\site-packages (from -r requirements/requirements.txt (line 43)) (0.9.3)
Requirement already satisfied: kombu==4.6.8 in d:\python\venv\python36-venv-jumpserver\lib\s
ite-packages (from -r requirements/requirements.txt (line 44)) (4.6.8)
Collecting ldap3==2.4
  Using cached ldap3-2.4-py2.py3-none-any.whl (373 kB)
Requirement already satisfied: MarkupSafe==1.1.1 in d:\python\venv\python36-venv-jumpserver\
lib\site-packages (from -r requirements/requirements.txt (line 46)) (1.1.1)
Collecting mysqlclient==1.3.14
  Using cached mysqlclient-1.3.14-cp36-cp36m-win_amd64.whl (266 kB)
Collecting olefile==0.44
  Using cached olefile-0.44.zip (74 kB)
Collecting openapi-codec==1.3.2
  Using cached openapi-codec-1.3.2.tar.gz (6.3 kB)
Collecting paramiko==2.4.2
  Using cached paramiko-2.4.2-py2.py3-none-any.whl (193 kB)
Collecting passlib==1.7.1
  Using cached passlib-1.7.1-py2.py3-none-any.whl (498 kB)
Collecting Pillow==6.2.2
  Using cached Pillow-6.2.2-cp36-cp36m-win_amd64.whl (2.0 MB)
Requirement already satisfied: pyasn1==0.4.8 in d:\python\venv\python36-venv-jumpserver\lib\
site-packages (from -r requirements/requirements.txt (line 53)) (0.4.8)
Requirement already satisfied: pycparser==2.19 in d:\python\venv\python36-venv-jumpserver\li
b\site-packages (from -r requirements/requirements.txt (line 54)) (2.19)
Collecting pycrypto==2.6.1
  Using cached pycrypto-2.6.1.tar.gz (446 kB)
Collecting pyotp==2.2.6
  Using cached pyotp-2.2.6-py2.py3-none-any.whl (11 kB)
Collecting PyNaCl==1.2.1
  Using cached PyNaCl-1.2.1-cp36-cp36m-win_amd64.whl (165 kB)
Requirement already satisfied: python-dateutil==2.6.1 in d:\python\venv\python36-venv-jumpse
rver\lib\site-packages (from -r requirements/requirements.txt (line 58)) (2.6.1)
Collecting python-gssapi==0.6.4
  Using cached python-gssapi-0.6.4.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\venv\python36-venv-jumpserver\scripts\python.exe' -c 'import sys, s
etuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-
93y_n4r_\\python-gssapi\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp
\\pip-install-93y_n4r_\\python-gssapi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', ope
n)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code
, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\admin\AppData\Local\Temp\pip-pip
-egg-info-w28cg549'
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-93y_n4r_\python-gssapi\
    Complete output (126 lines):
    running egg_info
    creating C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-w28cg549\python_gssapi.egg-i
nfo
    writing C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-w28cg549\python_gssapi.egg-in
fo\PKG-INFO
    writing dependency_links to C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-w28cg549\
python_gssapi.egg-info\dependency_links.txt
    writing requirements to C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-w28cg549\pyth
on_gssapi.egg-info\requires.txt
    writing top-level names to C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-w28cg549\p
ython_gssapi.egg-info\top_level.txt
    writing manifest file 'C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-w28cg549\pytho
n_gssapi.egg-info\SOURCES.txt'
    _cffi__x8e012de6x6c820412.c
    gssapi\bindings\__pycache__\_cffi__x8e012de6x6c820412.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__xf223bac3xa79bfeef.c
    gssapi\bindings\__pycache__\_cffi__xf223bac3xa79bfeef.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__xb3bc6629xdba4f2a1.c
    gssapi\bindings\__pycache__\_cffi__xb3bc6629xdba4f2a1.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__xeb514d6x5d98e1c3.c
    gssapi\bindings\__pycache__\_cffi__xeb514d6x5d98e1c3.c(212): fatal error C1083: Cannot o
pen include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__x67999e0x2a0d7c22.c
    gssapi\bindings\__pycache__\_cffi__x67999e0x2a0d7c22.c(212): fatal error C1083: Cannot o
pen include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__x680d8754xa883e720.c
    gssapi\bindings\__pycache__\_cffi__x680d8754xa883e720.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__x3116e390xdc4bc63b.c
    gssapi\bindings\__pycache__\_cffi__x3116e390xdc4bc63b.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__x605c8c53xc4f5555d.c
    gssapi\bindings\__pycache__\_cffi__x605c8c53xc4f5555d.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__xeb98ca96x39d25428.c
    gssapi\bindings\__pycache__\_cffi__xeb98ca96x39d25428.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__x9da3f28cxf7292814.c
    gssapi\bindings\__pycache__\_cffi__x9da3f28cxf7292814.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__x71c8306cx52487aa4.c
    gssapi\bindings\__pycache__\_cffi__x71c8306cx52487aa4.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__xcb5bccdbx18251cfe.c
    gssapi\bindings\__pycache__\_cffi__xcb5bccdbx18251cfe.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    _cffi__xaa59ba48xdb9bd1d2.c
    gssapi\bindings\__pycache__\_cffi__xaa59ba48xdb9bd1d2.c(212): fatal error C1083: Cannot
open include file: 'gssapi/gssapi.h': No such file or directory
    Traceback (most recent call last):
      File "D:\Python\Python36\lib\distutils\_msvccompiler.py", line 423, in compile
        self.spawn(args)
      File "D:\Python\Python36\lib\distutils\_msvccompiler.py", line 542, in spawn
        return super().spawn(cmd)
      File "D:\Python\Python36\lib\distutils\ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "D:\Python\Python36\lib\distutils\spawn.py", line 38, in spawn
        _spawn_nt(cmd, search_path, dry_run=dry_run)
      File "D:\Python\Python36\lib\distutils\spawn.py", line 81, in _spawn_nt
        "command %r failed with exit status %d" % (cmd, rc))
    distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual
Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\cffi\ffiplatform.py",
line 51, in _build
        dist.run_command('build_ext')
      File "D:\Python\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\command\bui
ld_ext.py", line 87, in run
        _build_ext.run(self)
      File "D:\Python\Python36\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "D:\Python\Python36\lib\distutils\command\build_ext.py", line 448, in build_exten
sions
        self._build_extensions_serial()
      File "D:\Python\Python36\lib\distutils\command\build_ext.py", line 473, in _build_exte
nsions_serial
        self.build_extension(ext)
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\command\bui
ld_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "D:\Python\Python36\lib\distutils\command\build_ext.py", line 533, in build_exten
sion
        depends=ext.depends)
      File "D:\Python\Python36\lib\distutils\_msvccompiler.py", line 425, in compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio
 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-install-93y_n4r_\python-gssapi\setup.py",
line 74, in <module>
        url="https://github.com/sigmaris/python-gssapi",
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\__init__.py
", line 163, in setup
        return distutils.core.setup(**attrs)
      File "D:\Python\Python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "D:\Python\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\command\egg
_info.py", line 297, in run
        self.find_sources()
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\command\egg
_info.py", line 304, in find_sources
        mm.run()
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\command\egg
_info.py", line 535, in run
        self.add_defaults()
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\command\egg
_info.py", line 571, in add_defaults
        sdist.add_defaults(self)
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\command\py3
6compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\command\sdi
st.py", line 135, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "D:\Python\Python36\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "D:\Python\Python36\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\setuptools\command\bui
ld_py.py", line 39, in finalize_options
        orig.build_py.finalize_options(self)
      File "D:\Python\Python36\lib\distutils\command\build_py.py", line 45, in finalize_opti
ons
        ('force', 'force'))
      File "D:\Python\Python36\lib\distutils\cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "D:\Python\Python36\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "C:\Users\admin\AppData\Local\Temp\pip-install-93y_n4r_\python-gssapi\setup.py",
line 22, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "C:\Users\admin\AppData\Local\Temp\pip-install-93y_n4r_\python-gssapi\setup.py",
line 15, in get_ext_modules
        from gssapi.bindings import ffi
      File "C:\Users\admin\AppData\Local\Temp\pip-install-93y_n4r_\python-gssapi\gssapi\__in
it__.py", line 4, in <module>
        from . import bindings
      File "C:\Users\admin\AppData\Local\Temp\pip-install-93y_n4r_\python-gssapi\gssapi\bind
ings\__init__.py", line 233, in <module>
        C = ffi.verify(_source, **_kwargs)
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\cffi\api.py", line 464
, in verify
        lib = self.verifier.load_library()
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\cffi\verifier.py", lin
e 104, in load_library
        self._compile_module()
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\cffi\verifier.py", lin
e 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\cffi\ffiplatform.py",
line 22, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "d:\python\venv\python36-venv-jumpserver\lib\site-packages\cffi\ffiplatform.py",
line 58, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual
 Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for f
ull command output.

(Python36-venv-jumpserver) D:\admin-desktop\files\repository\github\jumpserver>

```

**Comment by wojiushixiaobai** [comment]
不支持windows下开发

**Comment by zhangyx23** [comment]
那应该怎么配置开发环境，支持什么环境下开发
