### ISSUE TITLE
安装依赖python-gssapi失败

### ISSUE THREAD

**Issue by jxb1027** [jumpserver/jumpserver#4694]
Collecting python-gssapi==0.6.4
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a4/9e/648b4e85235097edcee561c986f7075cb1606be24c514cfcdd2930e35c5e/python-gssapi-0.6.4.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/py3/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pwcmvz6s/python-gssapi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pwcmvz6s/python-gssapi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5vx5rc3b
         cwd: /tmp/pip-install-pwcmvz6s/python-gssapi/
    Complete output (152 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-5vx5rc3b/python_gssapi.egg-info
    writing /tmp/pip-pip-egg-info-5vx5rc3b/python_gssapi.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-5vx5rc3b/python_gssapi.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-5vx5rc3b/python_gssapi.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-5vx5rc3b/python_gssapi.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-5vx5rc3b/python_gssapi.egg-info/SOURCES.txt'
    gssapi/bindings/__pycache__/_cffi__xa7d82a3cx47db505c.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xb6db7234xa2d82a13.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x4043bc38x4bfb7d35.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x91c0b203x91526966.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x4d60bb6fxf6f90d7e.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xfeda9684x2ac7d8ee.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__xaca9cfeaxf572031a.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x9c11ac12x52753e5f.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x83153404xfc2f8cba.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x1e24ce42x6b064b6b.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x7d445f8dx8333c101.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x1c5a925axc95ea75b.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    gssapi/bindings/__pycache__/_cffi__x84e8e962x962c4589.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
        extra_postargs)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/.eggs/cffi-1.14.3-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 51, in _build
        dist.run_command('build_ext')
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/setup.py", line 74, in <module>
        url="https://github.com/sigmaris/python-gssapi",
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 293, in run
        self.find_sources()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 300, in find_sources
        mm.run()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 531, in run
        self.add_defaults()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/egg_info.py", line 567, in add_defaults
        sdist.add_defaults(self)
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/py36compat.py", line 32, in add_defaults
        self._add_defaults_python()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/sdist.py", line 109, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib64/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/command/build_py.py", line 36, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/lib64/python3.6/distutils/command/build_py.py", line 45, in finalize_options
        ('force', 'force'))
      File "/usr/lib64/python3.6/distutils/cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/usr/lib64/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/setup.py", line 22, in finalize_options
        self.distribution.ext_modules = get_ext_modules()
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/setup.py", line 15, in get_ext_modules
        from gssapi.bindings import ffi
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/gssapi/__init__.py", line 4, in <module>
        from . import bindings
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/gssapi/bindings/__init__.py", line 233, in <module>
        C = ffi.verify(_source, **_kwargs)
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/.eggs/cffi-1.14.3-py3.6-linux-x86_64.egg/cffi/api.py", line 468, in verify
        lib = self.verifier.load_library()
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/.eggs/cffi-1.14.3-py3.6-linux-x86_64.egg/cffi/verifier.py", line 104, in load_library
        self._compile_module()
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/.eggs/cffi-1.14.3-py3.6-linux-x86_64.egg/cffi/verifier.py", line 201, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/.eggs/cffi-1.14.3-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 22, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
      File "/tmp/pip-install-pwcmvz6s/python-gssapi/.eggs/cffi-1.14.3-py3.6-linux-x86_64.egg/cffi/ffiplatform.py", line 58, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jxb1027** [comment]
yum install python3-devel
