### ISSUE TITLE
在资产管理里添加删除系统用户出错

### ISSUE THREAD

**Issue by xieyuanpeng** [jumpserver/jumpserver#471]
在资产管理里，进资产详情页面的右下角，无论是增加或者删除系统用户，都会出错， server端的日志：

2017-06-01 10:19:24 [exception ERROR] Internal Server Error: /api/assets/v1/assets/1/system-users/
Traceback (most recent call last):
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/utils/json.py", line 72, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/python-3.6.1/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/python-3.6.1/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/python-3.6.1/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/python-3.6.1/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Asset' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/monitor/jumpserver-toolkit/jumpserver/apps/assets/api.py", line 109, in patch
    push_users.delay([asset], system_users)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/celery/app/task.py", line 412, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/celery/app/base.py", line 737, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/celery/app/amqp.py", line 558, in send_task_message
    **properties
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/python-3.6.1/lib/python3.6/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/vine/five.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/utils/json.py", line 72, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/python-3.6.1/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/python-3.6.1/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/python-3.6.1/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/monitor/jumpserver-toolkit/py-env/lib/python3.6/site-packages/kombu/utils/json.py", line 62, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/python-3.6.1/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
kombu.exceptions.EncodeError: Object of type 'Asset' is not JSON serializable
2017-06-01 10:19:24 [basehttp ERROR] "PATCH /api/assets/v1/assets/1/system-users/ HTTP/1.1" 500 24651

**Comment by ibuler** [comment]
收到

**Comment by marksugar** [comment]
@ibuler so,这个问题解决了吗？

我在删除资产中的管理用户似乎又遇到了这个错误
```
2019-04-25 21:56:04 [log ERROR] Internal Server Error: /api/assets/v1/admin-user/844cc6b7-436f-4cd9-8e52-c0f479521c4c/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/mixins.py", line 93, in destroy
    self.perform_destroy(instance)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework_bulk/drf3/mixins.py", line 114, in perform_destroy
    instance.delete()
  File "/opt/py3/lib/python3.6/site-packages/django/db/models/base.py", line 879, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/opt/py3/lib/python3.6/site-packages/django/db/models/deletion.py", line 221, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/opt/py3/lib/python3.6/site-packages/django/db/models/deletion.py", line 27, in PROTECT
    sub_objs
```
