### ISSUE TITLE
资产树加载中...，页面报错500[Question] 

### ISSUE THREAD

**Issue by BigbigY** [jumpserver/jumpserver#4711]
版本2.2.2

![image](https://user-images.githubusercontent.com/16998173/94385915-de2b1200-0178-11eb-90af-00a75f2f27f0.png)

日志:
```
2020-09-28 10:49:26 [log ERROR] Internal Server Error: /api/v1/assets/nodes/children/tree/
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/generics.py", line 241, in get
    return self.list(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/opt/jumpserver/apps/assets/api/node.py", line 158, in get_queryset
    queryset = [node.as_tree_node() for node in queryset]
  File "/opt/jumpserver/apps/assets/api/node.py", line 158, in <listcomp>
    queryset = [node.as_tree_node() for node in queryset]
  File "/opt/jumpserver/apps/assets/models/node.py", line 553, in as_tree_node
    name = '{} ({})'.format(self.value, self.assets_amount)
  File "/opt/jumpserver/apps/common/utils/common.py", line 241, in __get__
    value = self.func(instance)
  File "/opt/jumpserver/apps/assets/models/node.py", line 320, in assets_amount
    amount = self.tree().assets_amount(self.key)
  File "/opt/jumpserver/apps/assets/utils.py", line 154, in assets_amount
    return len(self.all_assets(nid))
  File "/opt/jumpserver/apps/assets/utils.py", line 135, in all_assets
    if node.data is None:
AttributeError: 'NoneType' object has no attribute 'data'
172.27.143.174 [28/Sep/2020:10:49:26 +0800] "GET /api/v1/assets/nodes/children/tree/?assets=0 HTTP/1.0" 500 28585
```

**Comment by ibuler** [comment]
刷新一下缓存吧，按道理来讲不会出现这个问题

```
$ cd apps
$ python manage.py shell
$ from assets.models import Node
[1] Node.refresh_nodes()
```

**Comment by BigbigY** [comment]
![image](https://user-images.githubusercontent.com/16998173/94392228-3ddde900-018a-11eb-9acf-33750b568c0a.png)
在容器中刷新不好使啊

**Comment by BigbigY** [comment]
我有3000多台主机，是否会是数量多的问题导致

**Comment by ibuler** [comment]
方便时添加一下我的 qq：446465001
