### ISSUE TITLE
从1.5.5的数据导致2.4.0里会存在登录不了的问题，怎么解决

### ISSUE THREAD

**Issue by moyuanbo** [jumpserver/jumpserver#4853]
数据导完时，启动时
jms 启动报错问题
```
2020-10-23 17:30:04 Fri Oct 23 17:30:04 2020
2020-10-23 17:30:04 JumpServer version v2.4.0, more see https://www.jumpserver.org

- Start Gunicorn WSGI HTTP Server
2020-10-23 17:30:04 Check database connection ...
users
 [X] 0001_initial
 [X] 0002_auto_20171225_1157_squashed_0019_auto_20190304_1459 (18 squashed migrations)
 [X] 0020_auto_20190612_1825
 [X] 0021_auto_20190625_1104
 [X] 0022_auto_20190625_1105
 [X] 0023_auto_20190724_1525
 [X] 0024_auto_20191118_1612
 [ ] 0025_auto_20200206_1216
 [ ] 0026_auto_20200508_2105
 [ ] 0027_auto_20200616_1503
 [ ] 0028_auto_20200728_1805
 [ ] 0029_auto_20200814_1650
 [ ] 0030_auto_20200819_2041
2020-10-23 17:30:16 Database connect success
2020-10-23 17:30:16 Check database structure change ...
2020-10-23 17:30:16 Migrate model change to database ...
Operations to perform:
  Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  Applying assets.0049_systemuser_sftp_root... OK
  Applying assets.0050_auto_20200711_1740... OK
  Applying assets.0051_auto_20200713_1143... OK
  Applying assets.0052_auto_20200715_1535... OK
  Applying assets.0053_auto_20200723_1232... OK
  Applying assets.0054_auto_20200807_1032... OK
  Applying assets.0055_auto_20200811_1845... OK
  Applying assets.0056_auto_20200904_1751... OK
  Applying assets.0057_fill_node_value_assets_amount_and_parent_key...

	01/27 compute node[-10]`s assets_amount ...
	02/27 compute node[-11]`s assets_amount ...
	03/27 compute node[-12]`s assets_amount ...
	04/27 compute node[1]`s assets_amount ...
	05/27 compute node[1:10]`s assets_amount ...
	06/27 compute node[1:11]`s assets_amount ...
	07/27 compute node[1:11:1]`s assets_amount ...
	08/27 compute node[1:11:2]`s assets_amount ...
	09/27 compute node[1:11:3]`s assets_amount ...
	10/27 compute node[1:11:4]`s assets_amount ...
	11/27 compute node[1:27]`s assets_amount ...
	12/27 compute node[1:28]`s assets_amount ...
	13/27 compute node[1:30]`s assets_amount ...
	14/27 compute node[1:31]`s assets_amount ...
	15/27 compute node[1:35]`s assets_amount ...
	16/27 compute node[1:36]`s assets_amount ...
	17/27 compute node[1:9]`s assets_amount ...
	18/27 compute node[1:9:0]`s assets_amount ...
	19/27 compute node[1:9:1]`s assets_amount ...
	20/27 compute node[1:9:12]`s assets_amount ...
	21/27 compute node[1:9:14]`s assets_amount ...
	22/27 compute node[1:9:15]`s assets_amount ...
	23/27 compute node[1:9:2]`s assets_amount ...
	24/27 compute node[1:9:4]`s assets_amount ...
	25/27 compute node[1:9:5]`s assets_amount ...
	26/27 compute node[1:9:6]`s assets_amount ...
	27/27 compute node[1:9:7]`s assets_amount ...
  ................................................................. OK
  Applying audits.0007_auto_20191202_1010... OK
  Applying audits.0008_auto_20200508_2105... OK
  Applying audits.0009_auto_20200624_1654... OK
  Applying audits.0010_auto_20200811_1122... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying authentication.0004_ssotoken... OK
  Applying django_cas_ng.0001_initial...Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1005, "Can't create table 'jumpserver.#sql-430a_422' (errno: 150)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 247, in apply_migration
    migration_recorded = True
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 110, in __exit__
    self.execute(sql)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/opt/py3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1005, "Can't create table 'jumpserver.#sql-430a_422' (errno: 150)")
2020-10-23 17:30:28 Collect static files
2020-10-23 17:30:38 Collect static files done

- Start Flower as Task Monitor

- Start Daphne ASGI WS Server

- Start Celery as Distributed Task Queue: Ansible

- Start Celery as Distributed Task Queue: Celery

- Start Celery as Distributed Task Queue: NodeTree

- Start Celery as Distributed Task Queue: CheckAseetPermissionExpired

- Start Beat as Periodic Task Scheduler
gunicorn is running: 5611
flower is running: 5623
daphne is running: 5628
celery_ansible is running: 5642
celery_default is running: 5655
celery_node_tree is running: 5669
check_asset_perm_expired is running: 5682
beat is running: 5693


访问网页时报错：
Request failed with status code 500




过一段时间，程序会全部停掉：
(py3) [root@jms 17:38:00/opt/jumpserver]# ./jms status
gunicorn is stopped
flower is stopped
daphne is stopped
celery_ansible is stopped
celery_default is stopped
celery_node_tree is stopped
check_asset_perm_expired is stopped
beat is stopped
(py3) 
```

**Comment by wojiushixiaobai** [comment]
@moyuanbo 手动处理下数据库表结构问题
