### ISSUE TITLE
修改资产信息的时候有报错

### ISSUE THREAD

**Issue by jiangchao2016** [jumpserver/jumpserver#487]
env use  v4.0,django v1.11 python v3.6

jumpserver    | 2017-06-07 10:37:24 [exception ERROR] Internal Server Error: /api/assets/v1/assets/5/refresh/
jumpserver    | Traceback (most recent call last):
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
jumpserver    |     response = get_response(request)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
jumpserver    |     response = self.process_exception_by_middleware(e, request)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
jumpserver    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
jumpserver    |     return view_func(*args, **kwargs)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
jumpserver    |     return self.dispatch(request, *args, **kwargs)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
jumpserver    |     response = self.handle_exception(exc)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
jumpserver    |     self.raise_uncaught_exception(exc)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
jumpserver    |     response = handler(request, *args, **kwargs)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/rest_framework/generics.py", line 210, in get
jumpserver    |     return self.retrieve(request, *args, **kwargs)
jumpserver    |   File "/opt/jumpserver/apps/assets/api.py", line 156, in retrieve
jumpserver    |     summary = update_assets_hardware_info([asset])
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
jumpserver    |     return self._get_current_object()(*a, **kw)
jumpserver    |   File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 379, in __call__
jumpserver    |     return self.run(*args, **kwargs)
jumpserver    |   File "/opt/jumpserver/apps/assets/tasks.py", line 17, in update_assets_hardware_info
jumpserver    |     summary, result = run_AdHoc(task_tuple, assets, record=False)
jumpserver    |   File "/opt/jumpserver/apps/ops/utils.py", line 38, in run_AdHoc
jumpserver    |     assets = [asset._to_secret_json() for asset in assets]
jumpserver    |   File "/opt/jumpserver/apps/ops/utils.py", line 38, in <listcomp>
jumpserver    |     assets = [asset._to_secret_json() for asset in assets]
jumpserver    |   File "/opt/jumpserver/apps/assets/models/asset.py", line 123, in _to_secret_json
jumpserver    |     'private_key': self.admin_user.private_key_file if self.admin_user else None,

**Comment by jiangchao2016** [comment]
给用户加上sudo all权限，没有这个报错了，资产管理里有机器了，可是Connected host 为0，这个问题怎么解决
