### ISSUE TITLE
./jms start 后一直报错Find gunicorn stopped, retry 2, 3231066直至完全关闭

### ISSUE THREAD

**Issue by LHB6540** [jumpserver/jumpserver#4917]
./jms start后一直报错，重试  
`Find gunicorn stopped, retry 2, 3231066`  

6次重试失败后显示错误日志如下并自动关闭所有服务  
`Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./jms", line 540, in <module>
    start_services_and_watch(srv)
  File "./jms", line 409, in start_services_and_watch
    watch_services()
  File "./jms", line 353, in watch_services
    retry_start_stopped_services()
  File "./jms", line 309, in retry_start_stopped_services
    logging.info("Service start failed, exit: ", s)
Message: 'Service start failed, exit: '
Arguments: ('gunicorn',)
gunicorn is stopped
Stop service: flower Ok
Stop service: daphne Ok
Stop service: celery_ansible Error
Stop service: celery_default Error
Stop service: celery_node_tree Error
Stop service: check_asset_perm_expired Error
Stop service: beat Ok
`

环境：
python 3.6
redis 3.2.12
mysql  5.7.32

**Comment by umena337** [comment]
(py3) [root@localhost jumpserver]# ./jms status
gunicorn is stopped
celery_ansible is running: 7518
celery_default is running: 7519
beat is running: 7571
flower is running: 7576
daphne is running: 7582
