### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LHB6540** [jumpserver/jumpserver#4918]
JumpServer2.4.3

./jms start后一直报错如下
Find gunicorn stopped, retry 2, 3231066

6次重试失败后显示错误日志如下并自动关闭所有服务
--- Logging error ---
Traceback (most recent call last): File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit msg = self.format(record) File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format return fmt.format(record) File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format record.message = record.getMessage() File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage msg = msg % self.args TypeError: not all arguments converted during string formatting Call stack: File "./jms", line 540, in <module> start_services_and_watch(srv) File "./jms", line 409, in start_services_and_watch watch_services() File "./jms", line 353, in watch_services retry_start_stopped_services() File "./jms", line 309, in retry_start_stopped_services logging.info("Service start failed, exit: ", s) Message: 'Service start failed, exit: ' Arguments: ('gunicorn',) gunicorn is stopped Stop service: flower Ok Stop service: daphne Ok Stop service: celery_ansible Error Stop service: celery_default Error Stop service: celery_node_tree Error Stop service: check_asset_perm_expired Error Stop service: beat Ok

环境：
python 3.6
redis 3.2.12
mysql 5.7.32

![image](https://user-images.githubusercontent.com/41095303/97857071-27eab780-1d38-11eb-84f2-890514d98a90.png)

**Comment by wojiushixiaobai** [comment]
@LHB6540 
```
source /opt/py3/bin/activate
cd /opt/jumpserver
./jms stop
ps aux | grep py3 | awk '{print $2}' | xargs kill -9
rm -f tmp/*.pid
./jms start
```

**Comment by LHB6540** [comment]
谢谢解答，问题已解决
