### ISSUE TITLE
[Question] 按文档装，centos上装出现的问题。python版本是 Python 3.6.3

### ISSUE THREAD

**Issue by webangeld** [jumpserver/jumpserver#4948]
**请描述您的问题.**
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/data/jumpserver/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/data/jumpserver/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/jumpserver/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/jumpserver/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/data/jumpserver/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/data/jumpserver/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/data/jumpserver/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/data/jumpserver/lib/python3.6/site-packages/django/core/checks/model_checks.py", line 16, in check_all_models
    models = apps.get_models()
  File "/data/jumpserver/lib/python3.6/site-packages/django/apps/registry.py", line 178, in get_models
    self.check_models_ready()
  File "/data/jumpserver/lib/python3.6/site-packages/django/apps/registry.py", line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")

**Comment by wojiushixiaobai** [comment]
已远程处理，用户未仔细参考文档，config.yml 填写有误导致
```
SECRET_KEY: 
BOOTSTRAP_TOKEN: 
```
不能为空
