### ISSUE TITLE
批量命令报错

### ISSUE THREAD

**Issue by tms-c** [jumpserver/jumpserver#4956]
**JumpServer 版本(v1.5.9以下不再支持)**
2.4.0

**浏览器版本**
chrome 86.0

**Bug 描述**
---------- 任务开始 ----------
Should return 1 record, but get 2
Traceback (most recent call last):
  File "/opt/jumpserver/apps/ops/inventory.py", line 113, in get_run_user_info
    run_user = manager.get_latest(username=self.run_as, asset=asset)
  File "/opt/jumpserver/apps/assets/backends/manager.py", line 98, in get_latest
    return self.get(latest=True, **kwargs)
  File "/opt/jumpserver/apps/assets/backends/manager.py", line 92, in get
    raise MultipleObjectsReturned(msg)
django.core.exceptions.MultipleObjectsReturned: Should return 1 record, but get 2
Should return 1 record, but get 2
Traceback (most recent call last):
  File "/opt/jumpserver/apps/ops/inventory.py", line 113, in get_run_user_info
    run_user = manager.get_latest(username=self.run_as, asset=asset)
  File "/opt/jumpserver/apps/assets/backends/manager.py", line 98, in get_latest
    return self.get(latest=True, **kwargs)
  File "/opt/jumpserver/apps/assets/backends/manager.py", line 92, in get
    raise MultipleObjectsReturned(msg)

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/57564739/98507061-d1313080-2297-11eb-8c35-70035e47dc2b.png)

2. 
3.

**Comment by tms-c** [comment]
docker部署

**Comment by wojiushixiaobai** [comment]
请使用最新版本

**Comment by tms-c** [comment]
> 请使用最新版本

已经升级至2.4.3，错误依旧

**Comment by ibuler** [comment]
具体问题已了解，等待修复
