### ISSUE TITLE
CAS 认证失败

### ISSUE THREAD

**Issue by wolfguoliang** [jumpserver/jumpserver#4971]
2020-11-10 15:40:43 [exc_handlers ERROR] 
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 401, in initial
    self.check_permissions(request)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 336, in check_permissions
    request, message=getattr(permission, 'message', None)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 176, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

**Comment by ibuler** [comment]
那应该是配置有问题

**Comment by wolfguoliang** [comment]
感谢，能具体说是哪块配置的问题吗？
另外cas 认证会有跨域的问题吗？
CAS_SERVER_URL:   这个是域名
CAS_ROOT_PROXIED_AS:  这个是内网ip 地址
如上配置会有问题吗？

2020-11-11 10:23:17 [log ERROR] Internal Server Error: /core/auth/cas/login/
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django_cas_ng/views.py", line 70, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django_cas_ng/views.py", line 124, in get
    request=request)
  File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/py3/lib64/python3.6/site-packages/django_cas_ng/backends.py", line 20, in authenticate
    username, attributes, pgtiou = client.verify_ticket(ticket)
  File "/opt/py3/lib64/python3.6/site-packages/cas.py", line 166, in verify_ticket
    return self.verify_response(response)
  File "/opt/py3/lib64/python3.6/site-packages/cas.py", line 259, in verify_response
    return cls.parse_response_xml(response)
  File "/opt/py3/lib64/python3.6/site-packages/cas.py", line 223, in parse_response_xml
    tree = ElementTree.fromstring(response)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by Gourds** [comment]
> 感谢，能具体说是哪块配置的问题吗？
> 另外cas 认证会有跨域的问题吗？
> CAS_SERVER_URL: 这个是域名
> CAS_ROOT_PROXIED_AS: 这个是内网ip 地址
> 如上配置会有问题吗？
> 
> 2020-11-11 10:23:17 [log ERROR] Internal Server Error: /core/auth/cas/login/
> Traceback (most recent call last):
> File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> response = get_response(request)
> File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
> response = self.process_exception_by_middleware(e, request)
> File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
> response = wrapped_callback(request, *callback_args, **callback_kwargs)
> File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
> return func(*args, **kwds)
> File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
> return self.dispatch(request, *args, **kwargs)
> File "/opt/py3/lib64/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
> return bound_method(*args, **kwargs)
> File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
> return view_func(*args, **kwargs)
> File "/opt/py3/lib64/python3.6/site-packages/django_cas_ng/views.py", line 70, in dispatch
> return super().dispatch(request, *args, **kwargs)
> File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
> return handler(request, *args, **kwargs)
> File "/opt/py3/lib64/python3.6/site-packages/django_cas_ng/views.py", line 124, in get
> request=request)
> File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/**init**.py", line 73, in authenticate
> user = backend.authenticate(request, **credentials)
> File "/opt/py3/lib64/python3.6/site-packages/django_cas_ng/backends.py", line 20, in authenticate
> username, attributes, pgtiou = client.verify_ticket(ticket)
> File "/opt/py3/lib64/python3.6/site-packages/cas.py", line 166, in verify_ticket
> return self.verify_response(response)
> File "/opt/py3/lib64/python3.6/site-packages/cas.py", line 259, in verify_response
> return cls.parse_response_xml(response)
> File "/opt/py3/lib64/python3.6/site-packages/cas.py", line 223, in parse_response_xml
> tree = ElementTree.fromstring(response)
> File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1314, in XML
> parser.feed(text)
> File "", line None
> xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

请问解决了么，遇到相似的问题

**Comment by Gourds** [comment]
### 问题描述：
使用cas2.0，可以正常登录，无法退出
配置如下
```
#cas
AUTH_CAS: True
CAS_SERVER_URL: https://xxx.login.aliyunidaas.com/enduser/api/application/plugin_cas_apereo/idaas-cas_apereo/
CAS_ROOT_PROXIED_AS: http://1.1.2.3
#CAS_VERIFY_SSL_CERTIFICATE: True
CAS_LOGOUT_COMPLETELY: False
CAS_VERSION: 2
```

### 问题log：
```
==> jumpserver/logs/drf_exception.log <==

2020-12-02 16:34:57 [ERROR]
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 401, in initial
    self.check_permissions(request)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 336, in check_permissions
    request, message=getattr(permission, 'message', None)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 176, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

==> jumpserver/logs/gunicorn.log <==
/opt/py3/lib64/python3.6/site-packages/django_cas_ng/utils.py:78: UserWarning: `CAS_VERIFY_SSL_CERTIFICATE` is disabled, meaning that SSL certificates are not being verified by a certificate authority. This can expose your system to various attacks and should _never_ be disabled in a production environment.
  "`CAS_VERIFY_SSL_CERTIFICATE` is disabled, meaning that SSL certificates "
/opt/py3/lib64/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/opt/py3/lib64/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2020-12-02 16:34:57 [exc_handlers ERROR]
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 401, in initial
    self.check_permissions(request)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 336, in check_permissions
    request, message=getattr(permission, 'message', None)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 176, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。
```

**Comment by Gourds** [comment]
@wolfguoliang 能看下我这个问题么
