### ISSUE TITLE
从另外的jumpserver导入过来的sql,会丢失掉资产授权数据--注释

### ISSUE THREAD

**Issue by hnhn22** [jumpserver/jumpserver#509]
2017-06-23 19:16:15 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
2017-06-23 19:16:19 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
2017-06-23 19:16:19 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
2017-06-23 19:14:59 [basehttp INFO] "GET /api/users/v1/users/?token=1vFg609oFHX4DIbZnKEBkoTXh73EOl HTTP/1.1" 200 8920
2017-06-23 19:14:59 [oauth DEBUG] verify token: 200 b'{"username": "admin", "id": 1, "groups": [], "email": "clouddev2@vsettan.com.cn"}'
2017-06-23 19:14:59 [basehttp INFO] "GET /api/assets/v1/system-user/?token=1vFg609oFHX4DIbZnKEBkoTXh73EOl HTTP/1.1" 200 3203
2017-06-23 19:14:59 [oauth DEBUG] verify token: 200 b'{"username": "admin", "id": 1, "groups": [], "email": "clouddev2@vsettan.com.cn"}'
2017-06-23 19:14:59 [exception ERROR] Internal Server Error: /api/perms/v1/asset-permissions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 86, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/opt/jumpserver/apps/perms/api.py", line 58, in perform_create
    self.associate_system_users_and_assets(serializer)
  File "/opt/jumpserver/apps/perms/api.py", line 54, in associate_system_users_and_assets
    print('Run')
OSError: [Errno 5] Input/output error
2017-06-23 19:14:59 [basehttp ERROR] "POST /api/perms/v1/asset-permissions/?token=1vFg609oFHX4DIbZnKEBkoTXh73EOl HTTP/1.1" 500 18117
2017-06-23 19:15:00 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
2017-06-23 19:15:03 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28
2017-06-23 19:15:03 [basehttp INFO] "POST /api/applications/v1/terminal/heatbeat/ HTTP/1.1" 201 28

jumpserver/apps/perms/api.py
54行
#print('Run')      注释该行, 解决数据导入时界面上资产授权数据不能显示;

**Comment by ibuler** [comment]
另外jumpserver是指 jumpserver 0.3.2 ?
