### ISSUE TITLE
每次启动完jms服务后过一会就自动stop服务了，是为什么 #3838

### ISSUE THREAD

**Issue by tinyWa** [jumpserver/jumpserver#5097]
Check service status: beat -> stopped with code: 73(6663)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./jms", line 540, in <module>
    start_services_and_watch(srv)
  File "./jms", line 414, in start_services_and_watch
    watch_services()
  File "./jms", line 353, in watch_services
    retry_start_stopped_services()
  File "./jms", line 309, in retry_start_stopped_services
    logging.info("Service start failed, exit: ", s)
Message: 'Service start failed, exit: '
Arguments: ('beat',)
Stop service: gunicorn Ok
Stop service: flower Ok
Stop service: daphne Ok
Stop service: celery_ansible Ok
Stop service: celery_default Ok
Stop service: celery_node_tree Ok
Stop service: check_asset_perm_expired Ok
beat is stopped

**Comment by wojiushixiaobai** [comment]
#4918
参考此问题
```
source /opt/py3/bin/activate
cd /opt/jumpserver
./jms stop
ps aux | grep py3 | awk '{print $2}' | xargs kill -9
rm -f tmp/*.pid
./jms start
```
