### ISSUE TITLE
[v3.0 beta] vim编辑录像监控录像回放卡死

### ISSUE THREAD

**Issue by ibuler** [jumpserver/jumpserver#52]
bug现象： 录像监控卡顿或卡死
bug描述： 实时监控和录屏功能也会卡死。录像无法正常播放，操作记录都无法查看
环境： centos6.5 python2.6 django1.6 jumpserver3.0

**Comment by ibuler** [comment]
vim 没有权限的文件也会卡死

**Comment by liuzheng712** [comment]
该bug我暂时没有思路修复，原因如下：
1.经过一系列排查，认定不是前端bug，而是后端paramiko对读取gbk字节流产生的bug，暂时还没有实现jumpserver实现的精简重现代码，有如下测试代码说明问题：

```
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('localhost', port=22, username="liuzheng", key_filename='/Users/liuzheng/.ssh/id_rsa')
stdin, stdout, stderr = ssh.exec_command("cat /Users/liuzheng/Downloads/44.txt")
print stdout.readlines()
```

其中`44.txt`是gbk编码的。

```
Traceback (most recent call last):
  File "bug52show.py", line 7, in <module>
    print stdout.readlines()
  File "/usr/local/lib/python2.7/site-packages/paramiko/file.py", line 285, in readlines
    line = self.readline()
  File "/usr/local/lib/python2.7/site-packages/paramiko/file.py", line 270, in readline
    return line if self._flags & self.FLAG_BINARY else u(line)
  File "/usr/local/lib/python2.7/site-packages/paramiko/py3compat.py", line 53, in u
    return s.decode(encoding)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbf in position 0: invalid start byte
```

2. 我自己在webterminal上有异于jumpserver的一套完整的实现方式，无bug，但是由于是使用os.system 和 os.execv ，利用ssh命令进行连接，在Windows会不兼容，不能套用。


故而对此的建议是希望运维人员统一字符编码，猜测如果正常使用下，通过sql 的select语句打印出gbk编码的也会出现死的情况

**Comment by lanxing** [comment]
paramiko对gbk读取的bug楼主怎么解决的？
