### ISSUE TITLE
[Question] 我用k8s部署jumpserver的时候，镜像替换后，报“Internal Server Error”错误！

### ISSUE THREAD

**Issue by bingws** [jumpserver/jumpserver#5209]
查看日志，错误如下。Google下，不应该出现下面的错误，不懂。
版本：
我用我的v2.5.1，替换官方v2.5.2
```
2020-12-10 05:00:14 [log ERROR] Internal Server Error: /api/v1/terminal/terminals/config/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/terminal/api/terminal.py", line 148, in get
    configs = terminal.config
  File "/opt/jumpserver/apps/terminal/models.py", line 110, in config
    configs.update(self.get_command_storage_setting())
  File "/opt/jumpserver/apps/terminal/models.py", line 76, in get_command_storage_setting
    config = self.get_command_storage_config()
  File "/opt/jumpserver/apps/terminal/models.py", line 68, in get_command_storage_config
    s = self.get_command_storage()
  File "/opt/jumpserver/apps/terminal/models.py", line 64, in get_command_storage
    storage = CommandStorage.objects.filter(name=self.command_storage).first()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 653, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 72, in __iter__
    for row in compiler.results_iter(results):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1084, in apply_converters
    value = converter(value, expression, connection)
  File "/opt/jumpserver/apps/common/fields/model.py", line 124, in from_db_value
    plain_value = crypto.decrypt(value)
  File "/opt/jumpserver/apps/common/utils/crypto.py", line 188, in decrypt
    origin_text = decryptor.decrypt(text)
  File "/opt/jumpserver/apps/common/utils/crypto.py", line 133, in decrypt
    cipher = AES.new(self.key, AES.MODE_GCM, nonce=nonce)
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_GCM'
```
按照 #4830 的方法，我进入jumpserver的core组件的POD里面，卸载重装了pycryptodome，解决了，但是再替换镜像时，还是同样的错误。官方的解决方法是？

**Comment by bingws** [comment]
[我的解决方法](https://community.developers.refinitiv.com/questions/57674/error-module-cryptocipheraes-has-no-attribute-mode.html)

**Comment by wojiushixiaobai** [comment]
@bingws 用v2.5.3镜像即可
此问题是 pip 最新版本导致
- [fix: 修复 pip 升级引起的问题](https://github.com/jumpserver/Dockerfile/commit/1d18f2e396ebaddadbd35416c5b497e2a330aa28)

**Comment by bingws** [comment]
不用改这个，用 “from Cryptodome.Cipher import AES” (rather than from Crypto.Cipher import AES )

**Comment by seaurching** [comment]
我在k8s集群里面部署了之后，打开web终端后，不操作，会话就自动关闭了。我看了一下有这个报错，不知道怎么解决。我用istio做的ingress
![image](https://user-images.githubusercontent.com/7349963/113375950-27b41e00-93a3-11eb-9fd1-20b9f2e491e3.png)
