### ISSUE TITLE
centos install jumpserver  sh make_migrations.sh  error

### ISSUE THREAD

**Issue by chendianhui** [jumpserver/jumpserver#532]
jumpserver 4.0  python是后来更新3.6版本，另虚拟环境怎么安装，谢谢
![_20170710162520](https://user-images.githubusercontent.com/30037886/28009030-7ea246f4-658c-11e7-9e6a-d068c641e117.png)

**Comment by hellorocky** [comment]
看看配置文件中SECRET_KEY这一项是不是没有配置,  另外下一次提问的时候最好把自己的版本说清楚, 安装0.4版本是用python3不是python2

**Comment by xubinxinant** [comment]
我也遇到了相同的问题，SECRET_KEY在config.py里已经有，信息如下：
class Config:
    # Use it to encrypt or decrypt data
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = os.environ.get('SECRET_KEY') or '2vym+ky!997d5kkcc64mnz06y1mmui3lut#(^wd=%s_qj$1%x'

**Comment by chendianhui** [comment]
@xubinxinant 换成Python3 试试

**Comment by chendianhui** [comment]
@hellorocky  有时间帮忙看看新问题，谢谢 第一次搞jumpserver，4.0版本虚拟环境安装哪一步没有，不清楚安装什么

**Comment by xubinxinant** [comment]
@chendianhui 正在尝试了，目前遇到了和楼主一样的报错，现在的思路是在升级完python3后重新安装requerments，一会过来反馈结果

**Comment by chendianhui** [comment]
@xubinxinant   https://github.com/jumpserver/jumpserver/blob/dev/docs/install.md   你是按照这个步骤进行的吗

**Comment by ibuler** [comment]
我认为你们可以写出一篇好的文章来描述一步一步手动安装，关于安装 请参考 

- Dockerfile-py3
- Dockerfile 

这两个文件描述了我们的docker是怎么构建的，期待你们的消息

**Comment by xubinxinant** [comment]
@chendianhui 是的，我就是按照这个步骤在安装，centos7安装完python3（http://blog.csdn.net/hobohero/article/details/54381475）后，我重新运行了
sh sh make_migrations.sh 
报错如楼主的截图，应该是python3.6下没有django造成的
我又继续按照官网步骤执行
$ cd requirements 
$ sudo yum -y install `cat rpm_requirements.txt`
$ pip install -r requirements.txt -i https://pypi.doubanio.com/simple
根据信息提示，意思是rpm包已经安装，且django已经安装在python2.7下。
我尝试手动在python3.6下安装了Django
cd /usr/local/lib/python3.6/site-packages
python easy_install.py django
安装成功
再次执行
sh sh make_migrations.sh 
报错如下：
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv[1])
  File "/usr/local/lib/python3.6/site-packages/Django-1.11.3-py3.6.egg/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/Django-1.11.3-py3.6.egg/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/Django-1.11.3-py3.6.egg/django/core/management/__init__.py", line 193, in fetch_command
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.6/site-packages/Django-1.11.3-py3.6.egg/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/site-packages/Django-1.11.3-py3.6.egg/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/Django-1.11.3-py3.6.egg/django/conf/__init__.py", line 129, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
我简单的追溯了一下
/usr/local/lib/python3.6/site-packages/Django-1.11.3-py3.6.egg/django/conf/__init__.py的相关行数
代码里用到了操作系统变量ENVIRONMENT_VARIABLE，但是我在系统下echo为空。
暂时只追溯这里，我认为本次安装失败为源码问题，系统作者重新调试源码，安装文档里也写清楚各种需求

**Comment by ibuler** [comment]
你这个问题其实很明显，python -V 查看一下版本，然后确认一下你的 pip是哪个python下的pip，最好使用 pip3来安装

**Comment by hekan321** [comment]
@xubinxinant 同样的问题 ，我还试了docker-compose方式 也是报一堆的错

**Comment by xubinxinant** [comment]
@ibuler 感谢，正在按照你的方法尝试

**Comment by ibuler** [comment]
@hekan321 docker-compose的不是报错，是提示，需要去admin后台接受注册

**Comment by 727023460** [comment]
centos安装jumpserver的教程在这里，作者都说了python2和3都是可以的
https://www.hyahm.com/article/163.html

**Comment by ibuler** [comment]
看这个吧   https://github.com/jumpserver/jumpserver/wiki/v0.4.0-%E5%9F%BA%E4%BA%8E-RedHat-%E7%9A%84%E7%B3%BB%E7%BB%9F

**Comment by ibuler** [comment]
看这个吧，我也推送过微信了

https://github.com/jumpserver/jumpserver/wiki/v0.4.0-%E5%9F%BA%E4%BA%8E-CenOS7-%E7%9A%84%E7%B3%BB%E7%BB%9F

**Comment by 727023460** [comment]
那个是我自己写的，部署出来的

在 2017-07-19 15:18:23，"老广" <notifications@github.com> 写道：


看这个吧，我也推送过微信了

https://github.com/jumpserver/jumpserver/wiki/v0.4.0-%E5%9F%BA%E4%BA%8E-CenOS7-%E7%9A%84%E7%B3%BB%E7%BB%9F

**Comment by chendianhui** [comment]
@ibuler 按照步骤走，在执行表结构sh报错
  Applying assets.0001_initial... OK
  Applying audits.0001_initial...Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/py3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 93, in __exit__
    self.execute(sql)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/py3/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/py3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/py3/lib/python3.6/site-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

**Comment by chendianhui** [comment]
@727023460   pip install -r requirements.txt    centos7 minimal版本
按照你的步骤也试一次 到这报错
Collecting passlib>=1.7.1 (from -r requirements.txt (line 19))
  Using cached passlib-1.7.1-py2.py3-none-any.whl
Collecting gssapi (from -r requirements.txt (line 20))
  Using cached gssapi-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    In distributed package, building from C files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BlPOkN/gssapi/setup.py", line 93, in <module>
        raise Exception("Could not find main GSSAPI shared library.  Please "
    Exception: Could not find main GSSAPI shared library.  Please try setting GSSAPI_MAIN_LIB yourself or setting ENABLE_SUPPORT_DETECTION to 'false'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BlPOkN/gssapi/
[root@localhost requirements]#

**Comment by chendianhui** [comment]
@xubinxinant   我测试了下，4.0 centos安装教程有了，暂时先用sqlite试试，mysql我安装初始化结构报错

**Comment by ibuler** [comment]
已修复 Specified key was too long; max key length is 767 bytes

**Comment by xionghui** [comment]
如何修复的？Specified key was too long; max key length is 767 bytes  哪个commit?

**Comment by opsarno** [comment]
```bash
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 91, in database_forwards
    schema_editor.create_model(model)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 312, in create_model
    self.execute(sql, params or None)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/soft/jumpserver/venv-1.4.3/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
2018-10-15 16:48:37 [signals_handler DEBUG] Receive django ready signal
2018-10-15 16:48:37 [signals_handler DEBUG]   - fresh all settings
No conflicts detected to merge.

```
@ibuler   Python 3.6.6 & jumpserver-1.4.3  目前也报这个错
