### ISSUE TITLE
Socket error processing request.报错 ， jumpserver版本：Version 1.5.0-2 GPLv2.

### ISSUE THREAD

**Issue by jincheng-xiaosu** [jumpserver/jumpserver#5384]
**请描述您的问题.**
有普通用户使用crt建立多个会话，某一时间，该用户的crt会话全部掉线了，而其他用户却没有问题。经过查看日志，
在gunicorn.log日志里面发现以下报错（很多），请问这个报错和我的问题有关系吗，如果有关系，请问如何解决？
OSError: [Errno 107] Transport endpoint is not connected
Socket error processing request.
Traceback (most recent call last):
  File "/data/py3/lib64/python3.6/site-packages/gunicorn/workers/gthread.py", line 274, in handle
    req = six.next(conn.parser)
  File "/data/py3/lib64/python3.6/site-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/data/py3/lib64/python3.6/site-packages/gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/data/py3/lib64/python3.6/site-packages/gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "/data/py3/lib64/python3.6/site-packages/gunicorn/http/message.py", line 230, in parse
    self.headers = self.parse_headers(data[:idx])
  File "/data/py3/lib64/python3.6/site-packages/gunicorn/http/message.py", line 74, in parse_headers
    remote_addr = self.unreader.sock.getpeername()

**Comment by ibuler** [comment]
这个不太清楚，按道理来讲，不应该只有一个用户出现问题的
