### ISSUE TITLE
v0.40安装报错

### ISSUE THREAD

**Issue by sakufo** [jumpserver/jumpserver#540]
在安装步骤的2.4步初始化数据库时报以下错误 
$ sh make_migrations.sh
$ sh init_db.sh

[11:09:54 root@mq utils]#./make_migrations.sh 
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/jumpserver/apps/jumpserver/settings.py", line 26, in <module>
    from config import config as env_config, env
  File "/data/jumpserver/config.py", line 96
    USER_GUIDE_URL = '
                     ^
SyntaxError: EOL while scanning string literal
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/jumpserver/apps/jumpserver/settings.py", line 26, in <module>
    from config import config as env_config, env
  File "/data/jumpserver/config.py", line 96
    USER_GUIDE_URL = '
                     ^
SyntaxError: EOL while scanning string literal
[11:09:57 root@mq utils]#
[11:09:57 root@mq utils]#
[11:09:58 root@mq utils]#
[11:09:58 root@mq utils]#./init_db.sh 
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/jumpserver/apps/jumpserver/settings.py", line 26, in <module>
    from config import config as env_config, env
  File "/data/jumpserver/config.py", line 96
    USER_GUIDE_URL = '
                     ^
SyntaxError: EOL while scanning string literal

**Comment by hellorocky** [comment]
修改一下脚本里的python路径, 改成python3

**Comment by ibuler** [comment]
/usr/lib64/python2.7 需要py3
