### ISSUE TITLE
[Question] 升级数据库时 Foreign key constraint is incorrectly formed

### ISSUE THREAD

**Issue by hugeng1979** [jumpserver/jumpserver#5429]
**请描述您的问题.**
执行./jmsctl.sh upgrade 升级数据库时，出现错误：

472 static files copied to '/opt/jumpserver/data/static'.
Operations to perform:
  Apply all migrations: admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  Applying users.0031_auto_20201118_1801...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1025, "Error on rename of './jumpserver/#sql-1_3080' to './jumpserver/users_user' (errno: 150 - Foreign key constraint is incorrectly formed)")

应该是在给表users_user设置外键时有问题，从哪里可以找到相应的sql脚本？ 可以看看到底是哪里有问题。
对了，原jumpserver版本是2.0.2

**Comment by hugeng1979** [comment]
在这个错误下面，还同时有这个错误提示：
 File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1025, "Error on rename of './jumpserver/#sql-1_3717' to './jumpserver/users_user' (errno: 150 - Foreign key constraint is incorrectly formed)")

**Comment by hugeng1979** [comment]
升级成功了。
我是到mysql中先禁用外键约束
SET FOREIGN_KEY_CHECKS=0;
然后执行升级
升级后，再启用外键约束
SET FOREIGN_KEY_CHECKS=1;

**Comment by linsir** [comment]
@ibuler @wojiushixiaobai 
> 升级时 先禁用外键约束
SET FOREIGN_KEY_CHECKS=0;
然后执行升级
升级后，再启用外键约束

请问，这样操作对系统有没有影响?
