### ISSUE TITLE
登录的时候验证码图片出不来,报下面的错误

### ISSUE THREAD

**Issue by 727023460** [jumpserver/jumpserver#547]
2017-07-19 10:46:15 [exception ERROR] Internal Server Error: /captcha/image/67b367bdcbc02397d664b7a60130c26848e6f2aa/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/captcha/views.py", line 95, in captcha_image
    chardraw.text((0, 0), ' %s ' % char, font=font, fill='#ffffff')
  File "/usr/lib64/python2.7/site-packages/PIL/ImageDraw.py", line 272, in text
    self.draw.draw_bitmap(xy, mask, ink)
KeyError: 'setting text direction or font features is not supported without libraqm'

**Comment by hellorocky** [comment]
请使用python3启动服务试试
