### ISSUE TITLE
coco 运行一段时间之后会有如下报错 并且会卡住 重启docker 可以恢复

### ISSUE THREAD

**Issue by zsjohny** [jumpserver/jumpserver#549]
```
2017-07-19 18:13:06 [interface INFO] Accepted public key for johny from 125.33.26.222
2017-07-19 18:13:06 [transport DEBUG] Auth request (type=publickey) service=ssh-connection, username=johny
2017-07-19 18:13:06 [interface DEBUG] Start check auth
2017-07-19 18:13:06 [connectionpool DEBUG] Starting new HTTP connection (1): bastion.kuick.cn
2017-07-19 18:13:06 [connectionpool DEBUG] http://bastion.kuick.cn:80 "POST /api/users/v1/auth/ HTTP/1.1" 200 287
2017-07-19 18:13:06 [interface DEBUG] Finish check auth
2017-07-19 18:13:06 [interface INFO] Accepted public key for johny from 125.33.26.222
2017-07-19 18:13:06 [transport INFO] Auth granted (publickey).
2017-07-19 18:13:06 [channel DEBUG] [chan 0] Max packet in: 32768 bytes
2017-07-19 18:13:06 [channel DEBUG] [chan 0] Max packet out: 16384 bytes
2017-07-19 18:13:06 [transport DEBUG] Secsh channel 0 (session) opened.
2017-07-19 18:13:06 [app INFO] Client asked for a shell.
2017-07-19 18:13:06 [interactive DEBUG] Start get my assets
Exception in thread Thread-224:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/app.py", line 133, in process_request
    InteractiveServer(self).run()
  File "/opt/coco/coco/interactive.py", line 42, in __init__
    self.assets = self.get_my_assets()
  File "/opt/coco/coco/interactive.py", line 173, in get_my_assets
    assets = g.user_service.get_my_assets()
  File "/usr/local/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 471, in get_my_assets
    r, content = self.get('my-assets', use_auth=True)
  File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 130, in get
    return self.request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 116, in request
    raise RequestError('Authentication required')
jms.exceptions.RequestError: Authentication required
```

**Comment by ibuler** [comment]
想起来了，用户的token有个有效期，长时间不操作有效期过了

**Comment by zsjohny** [comment]
@ibuler  能贴一下啊代码的 链接吗

**Comment by hellorocky** [comment]
@zsjohny 
https://github.com/jumpserver/coco/blob/7bc135ac773cae7f28908ec0198a8ac1a57329fe/coco/interface.py#L63
https://github.com/jumpserver/jumpserver-python-sdk/blob/master/jms/service.py#L434
https://github.com/jumpserver/jumpserver/blob/dev/apps/users/api.py#L145
https://github.com/jumpserver/jumpserver/blob/dev/apps/users/utils.py#L161

**Comment by wutongjie23hao** [comment]
@zsjohny @ibuler 
出现了同样问题，错误日志：
Exception in thread Thread-66:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/app.py", line 137, in process_request
    InteractiveServer(self).run()
  File "/opt/coco/coco/interactive.py", line 303, in run
    self.dispatch()
  File "/opt/coco/coco/interactive.py", line 118, in dispatch
    self.assets = self.get_my_assets()
  File "/opt/coco/coco/interactive.py", line 181, in get_my_assets
    assets = g.user_service.get_my_assets()
  File "/usr/local/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 479, in get_my_assets
    r, content = self.get('my-assets', use_auth=True)
  File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 131, in get
    return self.request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 116, in request
    raise RequestError('Authentication required')
jms.exceptions.RequestError: Authentication required
在获取资产的时候，会到cache里面去取user_service，和这个有没有关系呢？

**Comment by ibuler** [comment]
#569
