### ISSUE TITLE
TypeError at /users/password/forgot  

### ISSUE THREAD

**Issue by sadlar** [jumpserver/jumpserver#551]
自定义安装的jumpserver 重置密码的时候遇到。 
**str() takes at most 1 argument (2 given)**

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/jumpserver/apps/users/views/login.py", line 95, in post
    send_reset_password_mail(user)
  File "/root/jumpserver/apps/users/utils.py", line 92, in send_reset_password_mail
    'rest_password_token': user.generate_reset_token(),
  File "/root/jumpserver/apps/users/models/user.py", line 192, in generate_reset_token
    return signer.sign_t({'reset': self.id, 'email': self.email}, expires_in=3600)
  File "/root/jumpserver/apps/common/utils.py", line 71, in sign_t
    return str(s.dumps(value), encoding="utf8")
TypeError: str() takes at most 1 argument (2 given)

**Comment by ibuler** [comment]
不支持python2,谢谢
