### ISSUE TITLE
[Question] 升级后 koko容器无法启动 报500  http://core:8080/api/v2/terminal/terminal-registrations/ failed, get code: 500, {"error": "Server internal error"}

### ISSUE THREAD

**Issue by scottyungit** [jumpserver/jumpserver#5511]
**请描述您的问题.**
升级后 koko容器无法启动 报500 
2021-01-22 11:12:07 [ERRO] POST http://core:8080/api/v2/terminal/terminal-registrations/ failed, get code: 500, {"error": "Server internal error"}
2021-01-22 11:12:07 [ERRO] register access key failed

**Comment by LeeEirc** [comment]
报500，请看core的日志，

**Comment by scottyungit** [comment]
> 报500，请看core的日志，

2021-01-22 13:50:31 [log ERROR] Internal Server Error: /api/v2/terminal/terminal-registrations/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'users_user.mfa_level' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/opt/jumpserver/apps/terminal/api_v2/terminal.py", line 39, in create
    serializer.is_valid(raise_exception=True)
  File "/opt/jumpserver/apps/terminal/serializers_v2/terminal.py", line 36, in is_valid
    valid = self.sa_serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 478, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/opt/jumpserver/apps/users/serializers_v2/user.py", line 34, in validate_name
    if users.filter(email=email) or \
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 291, in __bool__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'users_user.mfa_level' in 'field list'")

**Comment by LeeEirc** [comment]
数据库迁移可能存在问题，重新迁移吧。

**Comment by haitang5445** [comment]
![W2IV4P)7ZB1QX~G7L$1~`HA](https://user-images.githubusercontent.com/59681546/105822457-0e839f80-5ff7-11eb-8b5a-00672b1c0c95.png)
V2.6.2 一直有这个报错，WEB端的终端管理中koko一会儿不在线，一会儿又在线了

**Comment by jym503558564** [comment]
升级可参考文档 https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/

**Comment by jym503558564** [comment]
@haitang5445 该问题现在还存在吗？

**Comment by jym503558564** [comment]
@haitang5445 如果问题还未解决，可再次打开Issues

**Comment by smallhorsegg** [comment]
django.db.utils.IntegrityError: (1215, 'Cannot add foreign key constraint')    导完数据库，core启动报这个异常。
