### ISSUE TITLE
[Question] 第一次登录修改admin密码后再登录报错

### ISSUE THREAD

**Issue by yangfan0421** [jumpserver/jumpserver#5535]
Server error occur, contact administrator
后台日志
 Internal Server Error: /api/v1/terminal/components/state/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/opt/jumpserver/apps/terminal/serializers/components.py", line 25, in save
    terminal.state = self.validated_data
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 93, in state
    self._add_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 79, in _add_status
    status = self._compute_component_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 49, in _compute_component_status
    system_status = self._compute_system_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 43, in _compute_system_status
    state_value = state[system_status_key]
KeyError: 'system_cpu_load_1'

大佬帮忙看看什么问题导致的

**Comment by yangfan0421** [comment]
问题解决了，还有这样的日志，最后定位问题为外部的mysql数据库的字符集不是utf8。
create database jumpserver CHARACTER SET utf8 COLLATE utf8_general_ci;

附log
[log ERROR] Internal Server Error: /core/auth/login/guard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xE5\\xB1\\x80\\xE5\\x9F\\x9F...' for column 'city' at row 1")

The above exception was the direct cause of the following exception:
