### ISSUE TITLE
[Question] 2.7.0一直报Internal Server Error: /api/v1/terminal/components/state/

### ISSUE THREAD

**Issue by WeiqiuLiu** [jumpserver/jumpserver#5567]
**请描述您的问题.**
每30秒就报错：
 [log ERROR] Internal Server Error: /api/v1/terminal/components/state/
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/opt/py3/lib64/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/opt/jumpserver/apps/terminal/serializers/components.py", line 25, in save
    terminal.state = self.validated_data
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 93, in state
    self._add_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 79, in _add_status
    status = self._compute_component_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 49, in _compute_component_status
    system_status = self._compute_system_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 43, in _compute_system_status
    state_value = state[system_status_key]
KeyError: 'system_cpu_load_1'

我是使用setuptools安装的2.7.0

后台界面打开正常。请问这是什么原因导致的呢？

**Comment by WeiqiuLiu** [comment]
居然没人理啊！！QAQ

我自己加了几个print试了下，好像原因ComponentsStateSerializer这个类里的data里就没有system_cpu_load_1这个key

呐
ComponentsStateSerializer(context={'request': <rest_framework.request.Request: POST '/api/v1/terminal/components/state/'>, 'format': None, 'view': <terminal.api.component.ComponentsStateAPIView object>}, data={'system_memory_used_percent': 16.3, 'system_cpu_load_1': 0.01, 'session_active_count': 0, 'system_disk_used_percent': 15.6}):
    system_cpu_load_1 = FloatField(label='系统CPU负载 (1分钟)', required=False)
    system_memory_used_percent = FloatField(label='系统内存使用百分比', required=False)
    system_disk_used_percent = FloatField(label='系统磁盘使用百分比', required=False)
    session_active_count = IntegerField(label='活跃会话数量', required=False)
这个是正常的

ComponentsStateSerializer(context={'request': <rest_framework.request.Request: POST '/api/v1/terminal/components/state/'>, 'format': None, 'view': <terminal.api.component.ComponentsStateAPIView object>}, data={'session_active_count': 0, 'system_disk_used_percent': 15.6, 'system_memory_used_percent': 14.07}):
    system_cpu_load_1 = FloatField(label='系统CPU负载 (1分钟)', required=False)
    system_memory_used_percent = FloatField(label='系统内存使用百分比', required=False)
    system_disk_used_percent = FloatField(label='系统磁盘使用百分比', required=False)
    session_active_count = IntegerField(label='活跃会话数量', required=False)
这个是抛错的，data里没有system_cpu_load_1

应该是koko那边传来的，服务是正常的，但一直报这个错我不敢上线啊！！

也不知道是什么原因导致的-。-  怎么就我有这个问题呢...

**Comment by ibuler** [comment]
不好意思，忘记回复了，等我确认一下修复情况
