### ISSUE TITLE
[Question] 2.7 docker安装，数据库连接不上

### ISSUE THREAD

**Issue by RaynorAZ** [jumpserver/jumpserver#5572]
**请描述您的问题.**
Creating jms_core ... done

ERROR: for luna  Container "2fd2b6e0a598" is unhealthy.

ERROR: for koko  Container "2fd2b6e0a598" is unhealthy.

ERROR: for guacamole  Container "2fd2b6e0a598" is unhealthy.

ERROR: for celery  Container "2fd2b6e0a598" is unhealthy.

ERROR: for lina  Container "2fd2b6e0a598" is unhealthy.
ERROR: Encountered errors while bringing up the project.

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/showmigrations.py", line 52, in handle
    return self.show_list(connection, options['app_label'])
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/showmigrations.py", line 71, in show_list
    loader = MigrationLoader(connection, ignore_no_migrations=True)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 216, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '10.0.110.2' (115)")

jms容器中看了，config.yml文件是空的
用的是外部安装方式进行安装的，始终无法正常启动。

**Comment by RaynorAZ** [comment]
使用的是外部数据库安装方式

**Comment by RaynorAZ** [comment]
本地机器可以正常连接到数据库

**Comment by wojiushixiaobai** [comment]
1. 请勿在启动 docker 后修改 firewalld 或者 iptables 设置
2. 如果违背第一条请重新启动 docker
3. 如果不存在 1-2 条问题，请开启对应 ipv4/ipv6 转发

    ```sh
    # ipv4 查询
    sysctl net.ipv4.ip_forward
    # 返回结果为 1 表示正常
    ```
4. 如果不存在 1-3 条问题，请开启地址转发

    ```sh
    firewall-cmd --add-masquerade --permanent
    firewall-cmd --reload
    ```

5. 以上任意步骤操作后，请重启 docker 确认问题是否已经解决

**Comment by jym503558564** [comment]
@RaynorAZ 该问题是否已得到解决？

**Comment by Wes000** [comment]
@wojiushixiaobai 根据你的操作步骤还是没有解决这个问题

**Comment by zhouzhenhua** [comment]
我今天也试着部署jumpserver2.7.1，发现部署过程中，选择外置Mysql数据库，install过程中，jumpserver 库内未生成初始脚本（空库状态），这步怎么操作，或者去哪找到初始SQL语句

**Comment by wojiushixiaobai** [comment]
@zhouzhenhua 启动时通过另外一个终端查看 jms_core 容器的状态
```bash
docker logs -f jms_core
```

**Comment by swq-github** [comment]
没有人解决这个问题吗？
我的是跨大版本升级，从1.5.4---》2.8.3出现的问题。
感觉是不是python  和djiango没有更新的问题？
