### ISSUE TITLE
coco登录堡垒机输入密码后卡死问题

### ISSUE THREAD

**Issue by hellorocky** [jumpserver/jumpserver#558]
在测试Coco的过程中经常会遇到输入完密码后终端直接卡死的情况, Ctrl+C也不行, 除非把这个终端关闭才可以, 服务端也没有出现什么错误日志, 使用的是iterm2.
![qq20170721-165338](https://user-images.githubusercontent.com/7486508/28456531-3bf4ef6c-6e35-11e7-8de7-d98506a07671.png)

**Comment by ibuler** [comment]
出现频率高吗

**Comment by hellorocky** [comment]
@ibuler 每天总会有一次, 而且是在长时间未登录后第一次登陆的时候, 比如早上刚来上班打开终端登录就会卡死, 然后把这个终端关闭后这一天就不会出现了, 现在已经在生产环境使用, 倒不是很影响工作, 就是感觉不太爽....

**Comment by ibuler** [comment]
最好能有一些debug日志，logs里应该有一个详细的日志，paramiko打的，可以关注一下。

另外：生产环境有问题可以交流，修复的bug可以提交一下

**Comment by hellorocky** [comment]
```
INFO|2017-08-03 14:51:08|9819|app.py:112|Get ssh request from 60.205.224.12
ERROR|2017-08-03 14:51:24|9819|transport.py:1636|Exception: Error reading SSH protocol banner
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|Traceback (most recent call last):
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/transport.py", line 1952, in _check_banner
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|    buf = self.packetizer.readline(timeout)
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|    buf += self._read_timeout(timeout)
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/packet.py", line 546, in _read_timeout
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|    raise socket.timeout()
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|socket.timeout
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|During handling of the above exception, another exception occurred:
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|Traceback (most recent call last):
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/transport.py", line 1805, in run
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|    self._check_banner()
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/transport.py", line 1957, in _check_banner
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|    'Error reading SSH protocol banner' + str(e)
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR|2017-08-03 14:51:24|9819|transport.py:1634|
WARNING|2017-08-03 14:51:24|9819|app.py:127|SSH negotiation failed.
WARNING|2017-08-03 14:51:44|9819|app.py:132|No ssh channel get.

```

**Comment by vki** [comment]
我也经常遇到

**Comment by ibuler** [comment]
conflict with #698
