### ISSUE TITLE
[Question] 当我远程连接windows机器的时候浏览网页里面带动画的时候会整个卡死，查看日志没有发现报错

### ISSUE THREAD

**Issue by clcvi123** [jumpserver/jumpserver#5586]
**请描述您的问题.**
我是用jumpserver 连接远程桌面的时候（windwos） 浏览的一个需要局域网访问的网页的时候，因为那个网页有个动画效果，所以导致整个远程连接就卡死了，尝试关闭那个动画就可以了，想知道是什么问题。
jumpserver版本：v2.7.0
浏览器：chrome
windows版本：win10
![1612751254(1)](https://user-images.githubusercontent.com/40661627/107169230-555e9580-69f8-11eb-8719-1899f6a98b9c.jpg)

**Comment by ibuler** [comment]
没有遇到过，尝试看优酷视频，也没有出现这个问题

**Comment by clcvi123** [comment]
现在log里面也会出现这种错误，不知道怎么重现，可以帮忙看下吗？

2021-02-08 12:36:46 [log ERROR] Internal Server Error: /api/v1/terminal/components/state/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/opt/jumpserver/apps/terminal/serializers/components.py", line 25, in save
    terminal.state = self.validated_data
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 93, in state
    self._add_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 79, in _add_status
    status = self._compute_component_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 49, in _compute_component_status
    system_status = self._compute_system_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 43, in _compute_system_status
    state_value = state[system_status_key]
KeyError: 'system_cpu_load_1'
