### ISSUE TITLE
4.0 beta 1 连接coco失败-token过期问题

### ISSUE THREAD

**Issue by btkinghome** [jumpserver/jumpserver#569]
INFO:/opt/coco/coco/interface.py:Accepted password for admin from 172.19.0.1
2017-07-24 07:18:07 [interface INFO] Accepted password for admin from 172.19.0.1
INFO:paramiko.transport:Auth granted (password).
2017-07-24 07:18:07 [transport INFO] Auth granted (password).
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
2017-07-24 07:18:07 [channel DEBUG] [chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 16384 bytes
2017-07-24 07:18:07 [channel DEBUG] [chan 0] Max packet out: 16384 bytes
DEBUG:paramiko.transport:Secsh channel 0 (session) opened.
2017-07-24 07:18:07 [transport DEBUG] Secsh channel 0 (session) opened.
INFO:/opt/coco/coco/app.py:Client asked for a shell.
2017-07-24 07:18:07 [app INFO] Client asked for a shell.
DEBUG:/opt/coco/coco/interactive.py:Start get my assets
2017-07-24 07:18:07 [interactive DEBUG] Start get my assets
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/app.py", line 133, in process_request
    InteractiveServer(self).run()
  File "/opt/coco/coco/interactive.py", line 42, in __init__
    self.assets = self.get_my_assets()
  File "/opt/coco/coco/interactive.py", line 173, in get_my_assets
    assets = g.user_service.get_my_assets()
  File "/usr/local/lib/python3.6/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 471, in get_my_assets
    r, content = self.get('my-assets', use_auth=True)
  File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 130, in get
    return self.request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jms/service.py", line 116, in request
    raise RequestError('Authentication required')
jms.exceptions.RequestError: Authentication required

**Comment by btkinghome** [comment]
看起来像是token过期，要如何fix

**Comment by ibuler** [comment]
是的，token过期了。

我的思路是延长token有效期到2个小时，用户每次操作都会刷新token有效期的，如果过期，就断开连接

**Comment by hellorocky** [comment]
@ibuler 如果token过期就断开连接的话, 是不是在服务端还得有一个cron或者一个线程不断地监控过期的token, 另外还有一个问题, 断开client_channel和断开backend_channel有关系吗?如何能彻底断开一个用户的链接, 包括用户链接 coco和coco链接的所有资产, 看代码这一部分有点乱, 希望能解答一下

**Comment by ibuler** [comment]
jumpserver是一个proxy，和用户端连接的是 client_channel，和服务器端连接的是backend_channel，如果断开client_channel的话，用户就掉线了，如果断开backend_channel的话，用户理论应该回到 开始的导航页面。

每一个token是有有消息的，过期了api就认证不通过了

**Comment by ibuler** [comment]
这个可能不是token过期引起的

**Comment by lllwan** [comment]
同样遇到了这个问题，clone最新代码仍然存在这个问题，有临时fix方案吗？

**Comment by ibuler** [comment]
新版本已重构，不再使用用户token
