### ISSUE TITLE
[0.4.0]使用mysql时，makemigrations报错

### ISSUE THREAD

**Issue by iwannarock** [jumpserver/jumpserver#572]
在执行makemigrations同步数据库时，报错。错误信息如下：
Traceback (most recent call last):
  File "/home/cloud/jumpserver4/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/cloud/jumpserver4/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/cloud/jumpserver4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/cloud/jumpserver4/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/cloud/jumpserver4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/cloud/jumpserver4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/cloud/jumpserver4/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/cloud/jumpserver4/lib/python3.6/site-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'jumpserver.users_user' doesn't exist")

mysql 版本5.5，python库为mysqlclient
python版本为3.6.2
数据库里只有一个空的库jumpserver，没有任何表。
所有app目录下的migrations文件夹都已经删除。

**Comment by iwannarock** [comment]
找到问题了，之前测试的时候，为了使批量导入用户功能的form表单能够初始化User的输入框，我将users/forms.py 第126行（# choices=[(user.id, user.name) for user in User.objects.all()]）的注释给取消掉了。
在执行makemigrations时，该语句尝试查询User表，产生错误
