### ISSUE TITLE
[Bug] 重新连接按钮没用

### ISSUE THREAD

**Issue by mynameisshiy** [jumpserver/jumpserver#5731]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.7.1
**浏览器版本**
chrome 89
**Bug 描述**
通过网域访问远程桌面超时断开后，点击重新连接后没用，只能关掉后重新打开远程桌面窗口连接

**Bug 重现步骤(有截图更好)**
1.点击重新连接
![image](https://user-images.githubusercontent.com/8981574/110881758-d7095200-831b-11eb-9e8c-fee560c91c25.png)
2. 后台错误日志
guacd[485]: DEBUG:      Requesting termination of client...
Exception in thread "Thread-30" guacd[485]: DEBUG:      Client terminated successfully.
java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:439)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:311)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:251)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:192)
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
2021-03-12 02:07:11.630 [http-nio-8080-exec-6] INFO  o.a.g.a.j.s.JumpserverSessionService - uploadSessionRecord: ccf3aa2d-d77b-487a-9751-bd9943dbeb91
2021-03-12 02:07:11.631 [http-nio-8080-exec-6] INFO  o.a.g.a.j.s.JumpserverSessionService - 插入队列: {"error":0,"type":"UPLOAD","uuid":"ccf3aa2d-d77b-487a-9751-bd9943dbeb91"}
2021-03-12 02:07:11.631 [http-nio-8080-exec-6] INFO  o.a.g.tunnel.TunnelRequestService - User "5db1a5fc-cc78-4d9b-9f0b-3a0fc3559910" disconnected from connection "60117229-5d7d-4d5f-afef-dbcf50a167c9". Duration: 330 milliseconds
guacd[198]: INFO:       Connection "$c9147214-8e13-4158-9348-eedb2a0ab385" removed.

**Comment by LeeEirc** [comment]
受网域功能的实现限制，此类连接不支持重连。

**Comment by mynameisshiy** [comment]
> 受网域功能的实现限制，此类连接不支持重连。

这个在今后的版本会解决么？还是说永久都会这样了，没办法
