### ISSUE TITLE
jumpserver 2.7.1 审计-命令无法记录

### ISSUE THREAD

**Issue by vicenkaka** [jumpserver/jumpserver#5740]
操作命令无法记录。koko log 如下：
2021-03-13 09:26:36 [ERRO] Conn[09df58d6-b130-4c99-afea-df3d0d966b04] did not found cache ssh client(fjs@mysql)
2021-03-13 09:26:36 [ERRO] parse private key with passphrase error: ssh: not an encrypted key
2021-03-13 09:26:54 [ERRO] Session[f6708012-a45a-42fb-909e-f5b2d6a69943] srv read err: EOF
2021-03-13 09:26:54 [ERRO] Session[f6708012-a45a-42fb-909e-f5b2d6a69943] user read err: io: read/write on closed pipe
2021-03-13 09:28:06 [ERRO] Report stat err: POST http://127.0.0.1:8080/api/v1/terminal/components/state/ failed, get code: 500, {"error": "Server internal error"}
2021-03-13 09:28:36 [ERRO] Report stat err: POST http://127.0.0.1:8080/api/v1/terminal/components/state/ failed, get code: 500, {"error": "Server internal error"}

jumpserver.log
2021-03-13 09:50:37 [log ERROR] Internal Server Error: /api/v1/terminal/components/state/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/opt/jumpserver/apps/terminal/serializers/components.py", line 25, in save
    terminal.state = self.validated_data
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 93, in state
    self._add_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 79, in _add_status
    status = self._compute_component_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 49, in _compute_component_status
    system_status = self._compute_system_status(state)
  File "/opt/jumpserver/apps/terminal/models/terminal.py", line 43, in _compute_system_status
    state_value = state[system_status_key]
KeyError: 'system_cpu_load_1'

**Comment by ibuler** [comment]
收到，马上发版本解决

**Comment by ibuler** [comment]
升级新版本 v2.8 即可
