### ISSUE TITLE
[Bug] CAS配置报错

### ISSUE THREAD

**Issue by 78778443** [jumpserver/jumpserver#5775]
**JumpServer 版本(v1.5.9以下不再支持)**
使用最新版的2.7.1版本

**浏览器版本**

**Bug 描述**
我需要把jumpserver接入到统一的CAS服务里面去，安装官方文档配置后报错

**Bug 重现步骤(有截图更好)**
1.  添加配置到 `/opt/jumpserver/config/config.txt` 文件中去,并重启了服务
```
AUTH_CAS=True
CAS_SERVER_URL=https://idaas.xxxx.cn/enduser/api/application/plugin_cas1/xxxxgin_cas13/login
CAS_ROOT_PROXIED_AS=https://10.x.x3.2:8443/
CAS_LOGOUT_COMPLETELY=False
CAS_VERSION=2
```
2. 在登陆界面点击了CAS登陆
![image](https://user-images.githubusercontent.com/8509054/111426076-09a5b700-872f-11eb-9688-32d9e8192573.png)

出现报错 `Server error occur, contact administrator`
![image](https://user-images.githubusercontent.com/8509054/111426147-2641ef00-872f-11eb-90b4-329238ce5812.png)

3. 查看错误日志显示
```
==> /opt/jumpserver/core/logs/jumpserver.log <==
2021-03-17 14:45:55 [log ERROR] Internal Server Error: /core/auth/cas/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_cas_ng/views.py", line 70, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_cas_ng/views.py", line 105, in get
    client = get_cas_client(service_url=service_url, request=request)
  File "/usr/local/lib/python3.8/site-packages/django_cas_ng/utils.py", line 84, in get_cas_client
    return CASClient(
  File "/usr/local/lib/python3.8/site-packages/cas.py", line 48, in __new__
    return CASClientV1(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'proxy_callback'

```

**Comment by ibuler** [comment]
确实是 v2 版本的 cas 吗？

**Comment by 78778443** [comment]
是的，用的是阿里云idaas，里面有一个cas 服务



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月19日(周五) 下午3:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jumpserver/jumpserver] [Bug] CAS配置报错 (#5775)




 
确实是 v2 版本的 cas 吗？

**Comment by 78778443** [comment]
2.8.1版本不报这个错误了，可以正常调整到cas的登录页面，但是跳回来的时候会报错。
