### ISSUE TITLE
python run_server.py 报错 找不到runner

### ISSUE THREAD

**Issue by calistochen** [jumpserver/jumpserver#580]
Traceback (most recent call last):
  File "run_server.py", line 28, in <module>
    from connect import Tty, User, Asset, PermRole, logger, get_object, gen_resource
  File "/data/svr/jumpserver/connect.py", line 33, in <module>
    from jperm.ansible_api import MyRunner
  File "/data/svr/jumpserver/jperm/ansible_api.py", line 10, in <module>
    from ansible.runner import Runner
ImportError: No module named runner

**Comment by hellorocky** [comment]
是不是ansible升级了?要用1.9.4版本的, 你试试`ansible --version`看看版本

**Comment by calistochen** [comment]
明白
