### ISSUE TITLE
[Bug] 添加用户报错 Server internal error

### ISSUE THREAD

**Issue by wu-kui** [jumpserver/jumpserver#5812]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.8.0
操作系统为全新安装的 CentOS Linux release 7.9.2009 (Core)

**浏览器版本**
chrome 版本 89.0.4389.90（正式版本） (x86_64)

**Bug 描述**
创建不了用户，页面报 Server internal error

**Bug 重现步骤(有截图更好)**
1.  用户管理 -->  用户例表 -->   创建用户 ， 填写好用户信息后点 "提交"
![image](https://user-images.githubusercontent.com/15603499/111764020-b9b92280-88dd-11eb-9b76-3ee850651c3e.png)

日志如下:
2021-03-19 17:30:38 [log ERROR] Internal Server Error: /api/v1/users/users/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework_bulk/drf3/mixins.py", line 29, in create
    return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/opt/jumpserver/apps/users/api/user.py", line 83, in perform_create
    users = serializer.save()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 964, in create
    field.set(value)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1015, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 950, in add
    self._add_items(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1159, in _add_items
    signals.m2m_changed.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/jumpserver/apps/perms/signals_handler/refresh_perms.py", line 31, in on_user_groups_change
    group = UserGroup.objects.get(id=group_ids[0])
TypeError: 'set' object is not subscriptable

**Comment by hugoren** [comment]
我也遇到同样的问题

**Comment by luweijun1992** [comment]
v2.8.1 更新说明中包含：
fix: 修复创建用户失败的问题

**Comment by jym503558564** [comment]
@wu-kui v2.8.1已修复，请更新至最新版本进行测试

**Comment by wu-kui** [comment]
@jym503558564  已安装到 v2.8.1 问题修复了。

**Comment by emc2jumpser** [comment]
v2.13.0 重复出现此问题
