### ISSUE TITLE
给用户授权了，提示没权限登录，还需要设置什么

### ISSUE THREAD

**Issue by 727023460** [jumpserver/jumpserver#585]
Opt> p

[ID  ] IP               Port  Hostname Username Comment                                                                                                     
[0   ] 192.168.2.77     22    test     [test]                                                                                                             

Opt> 0

Connecting test@192.168.2.77:22 ... 

Connect backend server 192.168.2.77 failed: Auth failed

**Comment by krisbai** [comment]
遇到了同样的问题

**Comment by hellorocky** [comment]
看看jumpserver.log日志有没有什么异常

**Comment by krisbai** [comment]
用docker-compose 直接启动的 
错误报错：
Connect backend server XXX failed: Auth failed
版本：jumpserver:v0.4.0-beta1
日志信息：
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/viewsets.py", line 86, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/applications/api.py", line 78, in create
    TerminalHeatbeat.objects.create(terminal=terminal)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked

**Comment by 727023460** [comment]
0.4.0版本

**Comment by 727023460** [comment]
我问了下，说是后台创建系统用户的时候，服务器没有生成系统用户

**Comment by krisbai** [comment]
@727023460 你解决了么？

**Comment by 727023460** [comment]
我没办法，自己在服务器操作了

**Comment by 727023460** [comment]
自己新建了个用户，然后ssh-key远程认证，为了使用root用户，在远程机器用root新加了sudo su切换到root账户的权限

**Comment by 727023460** [comment]
2017-08-01 23:35:18 [basehttp WARNING] "GET /static/js/plugins/dataTables/dataTables.min.js HTTP/1.1" 404 1734
2017-08-01 23:35:18 [basehttp WARNING] "GET /static/js/plugins/dataTables/dataTables.min.js HTTP/1.1" 404 1734
2017-08-01 23:35:18 [basehttp WARNING] "GET /static/js/plugins/dataTables/pdfmake.min.js.map HTTP/1.1" 404 1737
看到错误日志了

**Comment by vki** [comment]
系统用户没办法推送

**Comment by ibuler** [comment]
应该是sqlite自己锁住了，等一会儿继续尝试，或者换mysql
