### ISSUE TITLE
[Question] 我jumpserver无法使用root批量执行命令，普通账号是正常的

### ISSUE THREAD

**Issue by zhangbin804** [jumpserver/jumpserver#5911]
---------- 任务开始 ----------

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/ops/tasks.py", line 64, in run_command_execution
    execution.run()
  File "/opt/jumpserver/apps/ops/models/command.py", line 82, in run
    ok, msg = self.run_as.is_command_can_run(self.command)
  File "/opt/jumpserver/apps/assets/models/user.py", line 198, in is_command_can_run
    action, matched_cmd = rule.match(command)
  File "/opt/jumpserver/apps/assets/models/cmd_filter.py", line 88, in match
    found = self._pattern.search(data)
  File "/opt/jumpserver/apps/common/utils/common.py", line 240, in __get__
    value = self.func(instance)
  File "/opt/jumpserver/apps/assets/models/cmd_filter.py", line 74, in _pattern
    if cmd[-1].isalpha():
IndexError: string index out of range

**Comment by zhangbin804** [comment]
之前安装的是2.2.2版本的，刚开始是好好的，突然间root就无法执行批量命令了。现在我升级到2.8.2版本发现还是有这个问题
