### ISSUE TITLE
生产数据bash make_migrations.sh 失败

### ISSUE THREAD

**Issue by aolens** [jumpserver/jumpserver#594]
Applying audits.0001_initial...Traceback (most recent call last):
  File "/home/jumpserver/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/jumpserver/py3/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/jumpserver/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/jumpserver/py3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/jumpserver/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/jumpserver/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/jumpserver/py3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/jumpserver/py3/lib/python3.6/site-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

**Comment by hellorocky** [comment]
把jumpserver数据库中audits_commandlog表的command字段长度加长一点试试

**Comment by ibuler** [comment]
fixed
