### ISSUE TITLE
[Bug] 推送成功以后无法登录 v2.9.0

### ISSUE THREAD

**Issue by zlylong** [jumpserver/jumpserver#5973]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.9.0

**浏览器版本**
Microsoft Edge
版本 90.0.818.39 (官方内部版本) (64 位)

**Bug 描述**
推送成功以后无法登录：
 发生错误：ssh: handshake failed: EOF
Connection closed

**Bug 重现步骤(有截图更好)**
1.  分配权限
2. 推送完成
3. web终端或者ssh登录

2021-04-16 16:36:45 任务开始: 测试系统用户可连接性: admin(admin)
q must be exactly 160, 224, or 256 bits long
Traceback (most recent call last):
  File "/opt/jumpserver/apps/ops/inventory.py", line 123, in get_run_user_info
    return run_user._to_secret_json()
  File "/opt/jumpserver/apps/assets/models/base.py", line 292, in _to_secret_json
    'private_key': self.private_key_file,
  File "/opt/jumpserver/apps/assets/models/base.py", line 141, in private_key_file
    self.private_key_obj.write_private_key_file(key_path)
  File "/usr/local/lib/python3.8/site-packages/paramiko/dsskey.py", line 162, in write_private_key_file
    key = dsa.DSAPrivateNumbers(
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 250, in private_key
    return backend.load_dsa_private_numbers(self)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 853, in load_dsa_private_numbers
    dsa._check_dsa_private_numbers(numbers)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 147, in _check_dsa_private_numbers
    _check_dsa_parameters(parameters)
  File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 139, in _check_dsa_parameters
    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ValueError: q must be exactly 160, 224, or 256 bits long
PLAY [测试系统用户可连接性: admin(admin)] ************************************************
TASK [ping] ********************************************************************
fatal: [seafile]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '172.16.105.81' (ECDSA) to the list of known hosts.\r\nroot@172.16.105.81: Permission denied (publickey).", "unreachable": true}
PLAY RECAP *********************************************************************
seafile                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
2021-04-16 16:36:45 任务结束
.

**Comment by k8scat** [comment]
I also met this problem, how to solve it?

**Comment by zlylong** [comment]
> I also met this problem, how to solve it?

chage -E '2099-12-30' XXXX

**Comment by k8scat** [comment]
> > I also met this problem, how to solve it?
> 
> `chage -E '2099-12-30' XXXX` XXXX is username

where to execute?

**Comment by ahvy** [comment]
When use windows openssh ssh-keygen.exe -t rsa command,is error. the id_rsa file length is 2609
But use centos ssh-keygen command make id_rsa is ok. thd id_rsa file length is 1674
