### ISSUE TITLE
[Bug] v2.9.0安装成功后启动报错

### ISSUE THREAD

**Issue by peteyan** [jumpserver/jumpserver#5974]
**JumpServer 版本(v1.5.9以下不再支持)**
version 2.9.0

**浏览器版本**
NaN

**Bug 描述**
os: centos 7.6.1810
jumpserver version: 2.9.0
------------
使用官网推荐安装：

> curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.9.0/quick_start.sh | bash

安装成功后，执行:
```
$ cd /opt/jumpserver-installer-v2.9.0
$ ./jmsctl.sh start
jms_redis is up-to-date
jms_mysql is up-to-date
jms_core is up-to-date

ERROR: for guacamole  Container "daa7ee068f06" is unhealthy.

ERROR: for koko  Container "daa7ee068f06" is unhealthy.

ERROR: for celery  Container "daa7ee068f06" is unhealthy.

ERROR: for luna  Container "daa7ee068f06" is unhealthy.

ERROR: for lina  Container "daa7ee068f06" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
参照官网查看docker日志 ``` docker logs -f jms_core --tail 200 ```
```
2021-04-16 15:20:18 Database connect success
 [ ] 0007_auto_20201119_1110
 [ ] 0008_auto_20210104_0435
 [ ] 0060_node_full_value
 [ ] 0061_auto_20201116_1757
 [ ] 0062_auto_20201117_1938
 [ ] 0063_migrate_default_node_key
 [ ] 0064_auto_20201203_1100
 [ ] 0065_auto_20210121_1549
 [ ] 0066_auto_20210208_1802
 [ ] 0067_auto_20210311_1113
 [ ] 0068_auto_20210312_1455
 [ ] 0069_change_node_key0_to_key1
 [ ] 0001_initial
 [ ] 0002_ftplog_org_id
 [ ] 0003_auto_20180816_1652
 [ ] 0004_operatelog_passwordchangelog_userloginlog
 [ ] 0005_auto_20190228_1715
 [ ] 0006_auto_20190726_1753
 [ ] 0007_auto_20191202_1010
 [ ] 0008_auto_20200508_2105
 [ ] 0009_auto_20200624_1654
 [ ] 0010_auto_20200811_1122
 [ ] 0011_userloginlog_backend
 [ ] 0012_auto_20210414_1443
 [ ] 0009_alter_user_last_name_max_length
 [ ] 0010_alter_group_name_max_length
 [ ] 0011_update_proxy_permissions
 [ ] 0012_alter_user_first_name_max_length
 [ ] 0001_initial
 [ ] 0002_auto_20190729_1423
 [ ] 0003_loginconfirmsetting
 [ ] 0004_ssotoken
 [ ] 0001_initial
 [ ] 0001_initial
 [ ] 0002_auto_20180111_1407
 [ ] 0003_setting_category
 [ ] 0004_setting_encrypted
 [ ] 0005_auto_20190221_1902
 [ ] 0006_auto_20190304_1515
 [ ] 0001_initial
 [ ] 0001_initial
 [ ] 0002_auto_20161118_0346
 [ ] 0003_auto_20161209_0049
 [ ] 0004_auto_20170221_0000
 [ ] 0005_add_solarschedule_events_choices
 [ ] 0006_auto_20180322_0932
 [ ] 0007_auto_20180521_0826
 [ ] 0008_auto_20180914_1922
 [ ] 0006_auto_20180210_1226
 [ ] 0006_periodictask_priority
 [ ] 0009_periodictask_headers
 [ ] 0010_auto_20190429_0326
 [ ] 0011_auto_20190508_0153
 [ ] 0012_periodictask_expire_seconds
 [ ] 0001_initial
 [ ] 0001_initial
 [ ] 0002_celerytask
 [ ] 0003_auto_20181207_1744
 [ ] 0004_adhoc_run_as
 [ ] 0005_auto_20181219_1807
 [ ] 0006_auto_20190318_1023
 [ ] 0007_auto_20190724_2002
 [ ] 0008_auto_20190919_2100
 [ ] 0009_auto_20191217_1713
 [ ] 0010_auto_20191217_1758
 [ ] 0011_auto_20200106_1534
 [ ] 0012_auto_20200108_1659
 [ ] 0013_auto_20200108_1706
 [ ] 0014_auto_20200108_1749
 [ ] 0015_auto_20200108_1809
 [ ] 0016_commandexecution_org_id
 [ ] 0017_auto_20200306_1747
 [ ] 0018_auto_20200509_1434
 [ ] 0019_adhocexecution_celery_task_id
 [ ] 0001_initial
 [ ] 0002_auto_20180903_1132
 [ ] 0003_auto_20190916_1057
 [ ] 0004_organizationmember
 [ ] 0005_auto_20200721_1937
 [ ] 0006_auto_20200721_1937
 [ ] 0007_auto_20200728_1805
 [ ] 0008_auto_20200819_2041
 [ ] 0009_auto_20201023_1628
 [ ] 0010_auto_20210219_1241
 [ ] 0017_auto_20210104_0435
 [ ] 0018_auto_20210208_1515
 [ ] 0001_initial
 [ ] 0001_initial
 [ ] 0001_initial
 [ ] 0002_auto_20171228_0025_squashed_0009_auto_20180326_0957 (8 squashed migrations)
 [ ] 0010_auto_20180423_1140
 [ ] 0011_auto_20180807_1116
 [ ] 0012_auto_20180816_1652
 [ ] 0013_auto_20181123_1113
 [ ] 0014_auto_20181226_1441
 [ ] 0015_auto_20190923_1529
 [ ] 0016_commandstorage_replaystorage
 [ ] 0017_auto_20191125_0931
 [ ] 0018_auto_20191202_1010
 [ ] 0019_auto_20191206_1000
 [ ] 0020_auto_20191218_1721
 [ ] 0021_auto_20200213_1316
 [ ] 0022_session_is_success
 [ ] 0023_command_risk_level
 [ ] 0024_auto_20200715_1713
 [ ] 0025_auto_20200810_1735
 [ ] 0026_auto_20201027_1905
 [ ] 0027_auto_20201102_1651
 [ ] 0028_auto_20201110_1918
 [ ] 0029_auto_20201116_1757
 [ ] 0030_terminal_type
 [ ] 0031_auto_20210113_1356
 [ ] 0032_auto_20210302_1853
 [ ] 0033_auto_20210324_1008
 [ ] 0034_auto_20210406_1434
 [ ] 0001_initial
 [ ] 0002_auto_20200728_1146
 [ ] 0003_auto_20200804_1551
 [ ] 0004_ticket_comment
 [ ] 0005_ticket_meta_confirmed_system_users
 [ ] 0006_auto_20201023_1628
 [ ] 0007_auto_20201224_1821
 [ ] 0008_auto_20210311_1113
 [ ] 0031_auto_20201118_1801
2021-04-16 15:20:28 Collect static files
2021-04-16 15:20:28 Collect static files done
2021-04-16 15:20:28 Check database structure change ...
2021-04-16 15:20:28 Migrate model change to database ...
Deleting 'css/animate.css'
Deleting 'css/bootstrap-style.css'
Deleting 'css/bootstrap.min.css'
Deleting 'css/colorbox.css'
Deleting 'css/font-awesome.min.css'
Deleting 'css/jumpserver.css'
Deleting 'css/login-style.css'
Deleting 'css/otp.css'
Deleting 'css/style.css'
Deleting 'css/images/jbox-button1.png'
Deleting 'css/images/jbox-close.gif'
Deleting 'css/images/jbox-icons.png'
Deleting 'css/patterns/congruent_pentagon.png'
Deleting 'css/patterns/header-profile-skin-1.png'
Deleting 'css/patterns/header-profile-skin-2.png'
Deleting 'css/patterns/header-profile-skin-3.png'
Deleting 'css/patterns/header-profile.png'
Deleting 'css/patterns/otis_redding.png'
Deleting 'css/patterns/shattered.png'
Deleting 'css/patterns/triangular.png'
Deleting 'css/plugins/bootstrap.min.css'
Deleting 'css/plugins/inputTags.css'
Deleting 'css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css'
Deleting 'css/plugins/codemirror/ambiance.css'
Deleting 'css/plugins/codemirror/codemirror.css'
Deleting 'css/plugins/cropper/cropper.min.css'
Deleting 'css/plugins/datatables/datatables.min.css'
Deleting 'css/plugins/datatables/datatables.min.css.bak'
Deleting 'css/plugins/datepicker/datepicker3.css'
Deleting 'css/plugins/daterangepicker/daterangepicker.css'
Deleting 'css/plugins/dropzone/basic.css'
Deleting 'css/plugins/dropzone/dropzone.css'
Deleting 'css/plugins/footable/footable.core.css'
Deleting 'css/plugins/footable/fonts/footable.eot'
Deleting 'css/plugins/footable/fonts/footable.svg'
Deleting 'css/plugins/footable/fonts/footable.ttf'
Deleting 'css/plugins/footable/fonts/footable.woff'
Deleting 'css/plugins/fullcalendar/fullcalendar.css'
Deleting 'css/plugins/fullcalendar/fullcalendar.print.css'
Deleting 'css/plugins/iCheck/custom.css'
Deleting 'css/plugins/iCheck/green.png'
Deleting 'css/plugins/iCheck/green@2x.png'
Deleting 'css/plugins/images/sort.png'
Deleting 'css/plugins/images/sort_asc.png'
Deleting 'css/plugins/images/sort_desc.png'
...
Deleting 'admin/js/vendor/select2/i18n/zh-TW.js'
Deleting 'admin/js/vendor/xregexp/LICENSE.txt'
Deleting 'admin/js/vendor/xregexp/xregexp.js'
Deleting 'admin/js/vendor/xregexp/xregexp.min.js'

473 static files copied to '/opt/jumpserver/data/static'.
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  Applying perms.0017_auto_20210104_0435...Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 508, in database_forwards
    alter_together(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 380, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/schema.py", line 129, in _delete_composed_index
    return super()._delete_composed_index(model, fields, *args)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 416, in _delete_composed_index
    raise ValueError("Found wrong number (%s) of constraints for %s(%s)" % (
ValueError: Found wrong number (0) of constraints for perms_k8sapppermission(org_id, name)

- Start Flower as Task Monitor

- Start Daphne ASGI WS Server
2021-04-16 15:20:42 Check service status: gunicorn -> running at 826
2021-04-16 15:20:42 Check service status: flower -> running at 839
2021-04-16 15:20:42 Check service status: daphne -> running at 1201
```

如上日志，出现初始化table时的报错，造成core后面服务启动不起来，请问如何解决，谢谢！

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/9857264/114990157-d0e23480-9eca-11eb-9671-49f081d04323.png)

![image](https://user-images.githubusercontent.com/9857264/114990233-e5bec800-9eca-11eb-8a38-cfaddc5ee3d1.png)

**Comment by peteyan** [comment]
Hi 问题已解决，可能因为在第一次start时，没有等到core跑完表，我执行了docker container的其他操作中断了导表，再次执行core时可能因为表外键约束关系导表不成功所以core容器跑不起来，现在重新走了安装操作，全部运行成功了。
