### ISSUE TITLE
任务列表或者批量命令 执行失败

### ISSUE THREAD

**Issue by k8scat** [jumpserver/jumpserver#5976]
作业中心 -> 任务列表或者批量命令，执行的时候提示 `q must be exactly 160, 224, or 256 bits long`

完整的错误信息如下：

```
Traceback (most recent call last):
  File "/opt/py3/lib64/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/py3/lib64/python3.6/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/ops/tasks.py", line 64, in run_command_execution
    execution.run()
  File "/opt/jumpserver/apps/ops/models/command.py", line 84, in run
    runner = CommandRunner(self.inventory)
  File "/opt/jumpserver/apps/ops/models/command.py", line 46, in inventory
    inv = JMSInventory(self.hosts.all(), run_as=username, system_user=self.run_as)
  File "/opt/jumpserver/apps/ops/inventory.py", line 97, in __init__
    run_user_info = self.get_run_user_info(host)
  File "/opt/jumpserver/apps/ops/inventory.py", line 118, in get_run_user_info
    return self.system_user._to_secret_json()
  File "/opt/jumpserver/apps/assets/models/base.py", line 292, in _to_secret_json
    'private_key': self.private_key_file,
  File "/opt/jumpserver/apps/assets/models/base.py", line 141, in private_key_file
    self.private_key_obj.write_private_key_file(key_path)
  File "/opt/py3/lib64/python3.6/site-packages/paramiko/dsskey.py", line 170, in write_private_key_file
    ).private_key(backend=default_backend())
  File "/opt/py3/lib64/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 250, in private_key
    return backend.load_dsa_private_numbers(self)
  File "/opt/py3/lib64/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 852, in load_dsa_private_numbers
    dsa._check_dsa_private_numbers(numbers)
  File "/opt/py3/lib64/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 147, in _check_dsa_private_numbers
    _check_dsa_parameters(parameters)
  File "/opt/py3/lib64/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 139, in _check_dsa_parameters
    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ValueError: q must be exactly 160, 224, or 256 bits long
```

**Comment by jym503558564** [comment]
@k8scat 哪个版本

**Comment by jym503558564** [comment]
@k8scat 可升级至最新版本进行测试，如还有问题可再次打开Issues
