### ISSUE TITLE
LDAP用户无法远程windows

### ISSUE THREAD

**Issue by JohnHan-cn** [jumpserver/jumpserver#6002]
用户从AD同步过来后中间有空格
Caused by: java.lang.IllegalArgumentException: Illegal character in query at index 149: http://core:8080/api/v1/assets/system-users/d3fbcc16-b561-4845-8606-3a57e9225de4/assets/1bfa8e5c-edbd-4599-a451-93e2c260160a/auth-info/?username=John Han&user_id=ebdbf9d7-6e24-4594-8aa7-7ecf1f469091

2021-04-20 09:25:16,904 [http-nio-8080-exec-4] INFO  o.a.g.a.j.api.JumpserverService 200 - getPermission:{code:200,result:{"actions":["all","connect","upload_file","download_file","updownload","clipboard_copy","clipboard_paste","clipboard_copy_paste"]}}
2021-04-20 09:25:16,906 [http-nio-8080-exec-4] ERROR o.a.g.a.j.utils.HttpClientUtil 111 - HttpClient查询失败
java.lang.IllegalArgumentException: Illegal character in query at index 149: http://core:8080/api/v1/assets/system-users/d3fbcc16-b561-4845-8606-3a57e9225de4/assets/1bfa8e5c-edbd-4599-a451-93e2c260160a/auth-info/?username=John Han&user_id=ebdbf9d7-6e24-4594-8aa7-7ecf1f469091
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
	at org.apache.guacamole.auth.jumpserver.utils.HttpClientUtil.get(HttpClientUtil.java:100)
	at org.apache.guacamole.auth.jumpserver.api.JumpserverService.getSystemUser(JumpserverService.java:279)
	at org.apache.guacamole.auth.jumpserver.configuration.JumpserverConfigurationService.registerAsset(JumpserverConfigurationService.java:156)
	at org.apache.guacamole.auth.jumpserver.configuration.JumpserverConfigurationService.addAsset(JumpserverConfigurationService.java:144)
	at org.apache.guacamole.auth.jumpserver.rest.RESTService.add(RESTService.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ObjectOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:258)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:137)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:137)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in query at index 149: http://core:8080/api/v1/assets/system-users/d3fbcc16-b561-4845-8606-3a57e9225de4/assets/1bfa8e5c-edbd-4599-a451-93e2c260160a/auth-info/?username=John Han&user_id=ebdbf9d7-6e24-4594-8aa7-7ecf1f469091
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 55 common frames omitted
2021-04-20 09:25:16,907 [http-nio-8080-exec-4] ERROR o.a.g.a.jumpserver.rest.RESTService 65 - [/asset/add]添加资产出现异常
org.apache.guacamole.auth.jumpserver.utils.HttpClientException: HttpClient查询失败
	at org.apache.guacamole.auth.jumpserver.utils.HttpClientUtil.get(HttpClientUtil.java:112)
	at org.apache.guacamole.auth.jumpserver.api.JumpserverService.getSystemUser(JumpserverService.java:279)
	at org.apache.guacamole.auth.jumpserver.configuration.JumpserverConfigurationService.registerAsset(JumpserverConfigurationService.java:156)
	at org.apache.guacamole.auth.jumpserver.configuration.JumpserverConfigurationService.addAsset(JumpserverConfigurationService.java:144)
	at org.apache.guacamole.auth.jumpserver.rest.RESTService.add(RESTService.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ObjectOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:258)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:137)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:137)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Illegal character in query at index 149: http://core:8080/api/v1/assets/system-users/d3fbcc16-b561-4845-8606-3a57e9225de4/assets/1bfa8e5c-edbd-4599-a451-93e2c260160a/auth-info/?username=John Han&user_id=ebdbf9d7-6e24-4594-8aa7-7ecf1f469091
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
	at org.apache.guacamole.auth.jumpserver.utils.HttpClientUtil.get(HttpClientUtil.java:100)
	... 53 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in query at index 149: http://core:8080/api/v1/assets/system-users/d3fbcc16-b561-4845-8606-3a57e9225de4/assets/1bfa8e5c-edbd-4599-a451-93e2c260160a/auth-info/?username=John Han&user_id=ebdbf9d7-6e24-4594-8aa7-7ecf1f469091
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 55 common frames omitted
2021-04-20 09:25:17,470 [http-nio-8080-exec-5] INFO  o.a.g.a.j.api.JumpserverService 137 - getUser by cookie: ebdbf9d7-6e24-4594-8aa7-7ecf1f469091
2021-04-20 09:25:17,937 [http-nio-8080-exec-2] ERROR o.a.g.w.GuacamoleWebSocketTunnelEndpoint 208 - Creation of WebSocket tunnel to guacd failed: Requested tunnel destination does not exist.
2021-04-20 09:25:18,021 [http-nio-8080-exec-1] WARN  o.a.g.s.GuacamoleHTTPTunnelServlet 263 - HTTP tunnel request rejected: Requested tunnel destination does not exist.

**Comment by JohnHan-cn** [comment]
Version v2.9.0-101 GPLv2.

**Comment by jym503558564** [comment]
@JohnHan-cn 经测试，跟是不是ldap用户没关系。
- 关于 【用户从AD同步过来后中间有空格】 这个问题，是ldap，创建用户填写firstname, lastname，然后Common Name是根据firstname以及lastname组合成的，自动中间加了空格。您如果不想空格，可以Common Name 自己去掉空格。

![image](https://user-images.githubusercontent.com/40739051/115506418-673c9e80-a2ad-11eb-97d8-9860201aa887.png)

**Comment by jym503558564** [comment]
@JohnHan-cn 

关于 【用户从AD同步过来后中间有空格】 这个问题，您可以先手动更新一下ldap的Common Name。ldap中创建用户填写firstname, lastname，然后Common Name是根据firstname以及lastname组合成的，自动中间加了空格。 您可以将Common Name 中的空格去掉。

**Comment by jym503558564** [comment]
![image](https://user-images.githubusercontent.com/40739051/115507495-cc44c400-a2ae-11eb-87ee-9c10811cb14b.png)

**Comment by JohnHan-cn** [comment]
@jym503558564 好的，感谢支持。后续的版本希望可以修复此问题，再次感谢。

**Comment by JohnHan-cn** [comment]
关闭
