### ISSUE TITLE
v2.10.1 update fail

### ISSUE THREAD

**Issue by stefen-jms** [jumpserver/jumpserver#6179]
[jumpserver/guacamole:v2.10.1]
Error response from daemon: manifest for swr.cn-south-1.myhuaweicloud.com/jumpserver/guacamole:v2.10.1 not found
Error response from daemon: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/guacamole:v2.10.1
Error: No such image: swr.cn-south-1.myhuaweicloud.com/jumpserver/guacamole:v2.10.1

**Comment by stefen-jms** [comment]
Guacamole update failed during version update

**Comment by stefen-jms** [comment]
manifest for jumpserver/guacamole:v2.10.1 not found

**Comment by LeeEirc** [comment]
The Guacamole component has decrepted from v2.10.0, and will be replaced by Lion. You should download v2.10.1 Installer to update.

**Comment by stefen-jms** [comment]
> The Guacamole component has decrepted from v2.10.0, and will be replaced by Lion. You should download v2.10.1 Installer to update.
that means i need to have a fully installed jumpserver, right?

**Comment by stefen-jms** [comment]
> The Guacamole component has decrepted from v2.10.0, and will be replaced by Lion. You should download v2.10.1 Installer to update.

that means i need to have a fully installed jumpserver, right?

**Comment by stefen-jms** [comment]
my previous configuration will be lost, right

**Comment by LeeEirc** [comment]
It is up to your deployment. We recommand you install JumpServer by our Installer which based on docker.
If you install components by manual , You need replace Guacamole imgae to Lion image, and modify nginx conf accordingly.

**Comment by stefen-jms** [comment]
i see, many thanks

**Comment by stefen-jms** [comment]
2021-05-24 14:27:28 [ldap INFO] Authentication LDAP backend
2021-05-24 14:27:29 [config ERROR] result(2) raised OPERATIONS_ERROR({'msgtype': 101, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C0907E9, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580'})
2021-05-24 14:27:29 [config ERROR] result(3) raised OPERATIONS_ERROR({'msgtype': 101, 'msgid': 3, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C0907E9, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580'})
2021-05-24 14:27:29 [backend WARNING] password is mandatory in simple bind while authenticating admin
2021-05-24 14:27:29 [log ERROR] Internal Server Error: /core/auth/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/opt/jumpserver/apps/authentication/views/login.py", line 89, in form_valid
    self.check_user_auth(decrypt_passwd=True)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 217, in check_user_auth
    user = self._check_auth_user_is_valid(username, password, public_key)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 180, in _check_auth_user_is_valid
    user = authenticate(self.request, username=username, password=password, public_key=public_key)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 58, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/jumpserver/apps/authentication/backends/ldap.py", line 88, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/usr/local/lib/python3.8/site-packages/django_auth_ldap/backend.py", line 211, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/usr/local/lib/python3.8/site-packages/django_auth_ldap/backend.py", line 353, in authenticate
    self._authenticate_user_dn(password)
  File "/usr/local/lib/python3.8/site-packages/django_auth_ldap/backend.py", line 481, in _authenticate_user_dn
    if self.dn is None:
  File "/usr/local/lib/python3.8/site-packages/django_auth_ldap/backend.py", line 446, in dn
    self._load_user_dn()
  File "/usr/local/lib/python3.8/site-packages/django_auth_ldap/backend.py", line 517, in _load_user_dn
    self._user_dn = cache.get_or_set(
  File "/usr/local/lib/python3.8/site-packages/django/core/cache/backends/base.py", line 171, in get_or_set
    default = default()
  File "/opt/jumpserver/apps/authentication/backends/ldap.py", line 150, in _search_for_user_dn
    user_dn = self._search_for_user_dn_from_ldap_util()
  File "/opt/jumpserver/apps/authentication/backends/ldap.py", line 121, in _search_for_user_dn_from_ldap_util
    user_dn = util.search_for_user_dn(self._username)
  File "/opt/jumpserver/apps/settings/utils/ldap.py", line 197, in search_for_user_dn
    user_entries = self.search_user_entries(search_users=[username])
  File "/opt/jumpserver/apps/common/utils/common.py", line 209, in wrapper
    result = func(*args, **kwargs)
  File "/opt/jumpserver/apps/settings/utils/ldap.py", line 168, in search_user_entries
    self.search_user_entries_ou(search_ou)
  File "/opt/jumpserver/apps/settings/utils/ldap.py", line 142, in search_user_entries_ou
    self.connection.search(
  File "/opt/jumpserver/apps/settings/utils/ldap.py", line 98, in connection
    conn.bind()
  File "/usr/local/lib/python3.8/site-packages/ldap3/core/connection.py", line 527, in bind
    request = bind_operation(self.version, self.authentication, self.user, self.password)
  File "/usr/local/lib/python3.8/site-packages/ldap3/operation/bind.py", line 59, in bind_operation
    raise LDAPPasswordIsMandatoryError('password is mandatory in simple bind')
ldap3.core.exceptions.LDAPPasswordIsMandatoryError: password is mandatory in simple bind

**Comment by stefen-jms** [comment]
Server error occur, contact administrator
can't login when upgrade from v2.9.2 to v2.10.1

**Comment by wojiushixiaobai** [comment]
need reset LDAP
```bash
mysql -uroot -p
```
```mysql
use jumpserver;
update settings_setting set value='false' where name='AUTH_LDAP';
```
```bash
redis-cli -a $REDIS_PASSWORD
```
```redis
select 4
keys *LDAP*
del :1:_SETTING_AUTH_LDAP
```
