### ISSUE TITLE
4.0 migrations 时报错。

### ISSUE THREAD

**Issue by vslinux** [jumpserver/jumpserver#624]
Traceback (most recent call last):
  File "/Data/apps/ENV3/lib/python3.6/site-packages/django/core/management/__init__.py", line 186, in fetch_command
    app_name = commands[subcommand]
KeyError: 'migrations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/Data/apps/ENV3/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Data/apps/ENV3/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Data/apps/ENV3/lib/python3.6/site-packages/django/core/management/__init__.py", line 193, in fetch_command
    settings.INSTALLED_APPS
  File "/Data/apps/ENV3/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Data/apps/ENV3/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Data/apps/ENV3/lib/python3.6/site-packages/django/conf/__init__.py", line 129, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by ibuler** [comment]
或许 你没有copy配置文件
