### ISSUE TITLE
4.0 安装失败，没有启动8080端口

### ISSUE THREAD

**Issue by xieyabo1993** [jumpserver/jumpserver#630]
小弟我是按着这个文章安装的。http://www.cnblogs.com/Csir/p/7352902.html

环境包括centos7.2 ； python3.6；mysql5.6   防火墙，selinux已关

下面是启动信息，看到一个明显的错误：TypeError: 'NoneType' object is not callable

然后lsof-i:8080   查看，发现8080端口并没有启动

# python3 run_server.py 
start celery
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/python36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "run_server.py", line 22, in start_django
    http_host = CONFIG.HTTP_BIND_HOST or '127.0.0.1'
TypeError: 'NoneType' object is not callable

/usr/lib/python2.7/site-packages/celery/platforms.py:795: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2017-08-19 20:12:17,699: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2017-08-19 20:12:17,702: DEBUG/MainProcess] | Worker: Building graph...
[2017-08-19 20:12:17,703: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Timer, Hub, Pool, Autoscaler, Beat, Consumer}
[2017-08-19 20:12:17,724: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2017-08-19 20:12:17,725: DEBUG/MainProcess] | Consumer: Building graph...
[2017-08-19 20:12:17,744: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Gossip, Heart, Agent, Tasks, Control, event loop}
 
 -------------- celery@bogon v4.1.0 (latentcall)
---- **** ----- 
--- * ***  * -- Linux-3.10.0-327.el7.x86_64-x86_64-with-centos-7.2.1511-Core 2017-08-19 20:12:17
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         jumpserver:0x2a88250
- ** ---------- .> transport:   redis://127.0.0.1:6379/3
- ** ---------- .> results:     redis://127.0.0.1:6379/3
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . assets.tasks.test_admin_user_connective_period
  . assets.tasks.update_assets_hardware_info
  . assets.tasks.update_assets_hardware_period
  . audits.tasks.write_login_log_async
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . common.tasks.send_mail_async
  . ops.tasks.rerun_task
  . perms.tasks.push_users

[2017-08-19 20:12:17,758: DEBUG/MainProcess] | Worker: Starting Hub
[2017-08-19 20:12:17,759: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:17,759: DEBUG/MainProcess] | Worker: Starting Pool
[2017-08-19 20:12:18,052: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:18,053: DEBUG/MainProcess] | Worker: Starting Beat
[2017-08-19 20:12:18,058: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:18,059: DEBUG/MainProcess] | Worker: Starting Consumer
[2017-08-19 20:12:18,060: DEBUG/MainProcess] | Consumer: Starting Connection
[2017-08-19 20:12:18,087: INFO/MainProcess] Connected to redis://127.0.0.1:6379/3
[2017-08-19 20:12:18,087: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:18,087: DEBUG/MainProcess] | Consumer: Starting Events
[2017-08-19 20:12:18,099: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:18,099: DEBUG/MainProcess] | Consumer: Starting Mingle
[2017-08-19 20:12:18,100: INFO/MainProcess] mingle: searching for neighbors
[2017-08-19 20:12:18,292: INFO/Beat] beat: Starting...
[2017-08-19 20:12:18,318: DEBUG/Beat] Current schedule:
<ScheduleEntry: test-admin-user-connective assets.tasks.test_admin_user_connective_period() <freq: 2.50 days>
<ScheduleEntry: refresh-asset-hardware-info assets.tasks.update_assets_hardware_period() <freq: 60.00 days>
[2017-08-19 20:12:18,318: DEBUG/Beat] beat: Ticking with max interval->5.00 minutes
[2017-08-19 20:12:18,320: DEBUG/Beat] beat: Waking up in 5.00 minutes.
[2017-08-19 20:12:19,129: INFO/MainProcess] mingle: all alone
[2017-08-19 20:12:19,129: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:19,130: DEBUG/MainProcess] | Consumer: Starting Gossip
[2017-08-19 20:12:19,141: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:19,141: DEBUG/MainProcess] | Consumer: Starting Heart
[2017-08-19 20:12:19,146: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:19,146: DEBUG/MainProcess] | Consumer: Starting Tasks
[2017-08-19 20:12:19,161: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:19,161: DEBUG/MainProcess] | Consumer: Starting Control
[2017-08-19 20:12:19,167: DEBUG/MainProcess] ^-- substep ok
[2017-08-19 20:12:19,168: DEBUG/MainProcess] | Consumer: Starting event loop
[2017-08-19 20:12:19,169: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2017-08-19 20:12:19,171: WARNING/MainProcess] /usr/lib/python2.7/site-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2017-08-19 20:12:19,172: INFO/MainProcess] celery@bogon ready.
[2017-08-19 20:12:19,172: DEBUG/MainProcess] basic.qos: prefetch_count->16
[2017-08-19 20:17:18,377: DEBUG/Beat] beat: Synchronizing schedule...
[2017-08-19 20:17:18,385: DEBUG/Beat] beat: Waking up in 5.00 minutes.
[2017-08-19 20:22:18,398: DEBUG/Beat] beat: Synchronizing schedule...
[2017-08-19 20:22:18,407: DEBUG/Beat] beat: Waking up in 5.00 minutes.
[2017-08-19 20:27:18,459: DEBUG/Beat] beat: Synchronizing schedule...
[2017-08-19 20:27:18,467: DEBUG/Beat] beat: Waking up in 5.00 minutes.

下面是我的config.py 配置文件

class DevelopmentConfig(Config):
    DEBUG = True
    DISPLAY_PER_PAGE = 20
    DB_ENGINE = 'sqlite'
    DB_NAME = os.path.join(BASE_DIR, 'data', 'db.sqlite3')
    EMAIL_HOST = 'smtp.exmail.qq.com'
    EMAIL_PORT = 465
    EMAIL_HOST_USER = 'a@jumpserver.org'
    EMAIL_HOST_PASSWORD = 'somepasswrd'
    EMAIL_USE_SSL = True
    EMAIL_USE_TLS = False
    EMAIL_SUBJECT_PREFIX = '[Jumpserver] '
    SITE_URL = 'http://192.168.43.11:8080'

class ProductionConfig(Config):
    DEBUG = False
    DB_ENGINE = 'mysql'
    DB_HOST = '127.0.0.1'
    DB_PORT = 3306
    DB_USER = 'jumpserver'
    DB_PASSWORD = '123123'
    DB_NAME = 'jumpserver'

哪个大哥哥能帮我想想办法，小弟先在这里谢过了。

**Comment by hellorocky** [comment]
有报错, 你没看到吗? 看看run_server.py文件, 简单的脚本, 看错误信息是启动的监听地址端口没有配好
