### ISSUE TITLE
[Question] 自动部署，手动部署，mysql容器启动出错！

### ISSUE THREAD

**Issue by nchair** [jumpserver/jumpserver#6324]
实体机centos7.9，无论是自动部署还是手动部署，mysql容器都启动不了！

django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

Creating network "jms_net" with driver "bridge"
Creating jms_redis ... done
Creating jms_mysql ... done

ERROR: for core  Container "beb400d2ea57" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by nchair** [comment]
使用外置mysql部署后，服务全部能启动，第一次登录修改密码之后，再次登录显示：Server error occur, contact administrator

**Comment by xiaohui1997** [comment]
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                          PORTS                 NAMES
f86212cbee6d        jumpserver/mysql:5          "docker-entrypoint.s…"   10 minutes ago      Up About a minute (unhealthy)   3306/tcp, 33060/tcp   jms_mysql


v2.11.1版本   centos 7.6   容器起不来

**Comment by nchair** [comment]
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> f86212cbee6d jumpserver/mysql:5 "docker-entrypoint.s…" 10 minutes ago Up About a minute (unhealthy) 3306/tcp, 33060/tcp jms_mysql
> 
> v2.11.1版本 centos 7.6 容器起不来

和你的一样，centos7.9，搞了4次mysql都起不来，外置mysql服务能起来，不能登录！

**Comment by nchair** [comment]
更换Ubuntu 20.04后问题依旧！

**Comment by itfans520** [comment]
我的也是这样的问题，搞了4天了，ubuntu 18.04、20.04，Centos 7，都是这个问题。
jumpserver 与 jumpserver-2.12.1的目录都给了777的权限，也是不行。
部署到“7. Init JumpServer Database”的时候就报错。
docker logs jms_mysql也是正常的，没有异常报错信息，但就是 unhealthy状态。

### **哪位大神帮忙给看一眼吧！谢谢了！**

7. Init JumpServer Database
Creating network "jms_net" with driver "bridge"
Creating jms_redis ... done
Creating jms_mysql ... done
2021-06-26 14:54:41 Collect static files
2021-06-26 14:54:41 Collect static files done
2021-06-26 14:54:41 Check database structure change ...
2021-06-26 14:54:41 Migrate model change to database ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/ops/models/__init__.py", line 6, in <module>
    from .command import *
  File "/opt/jumpserver/apps/ops/models/command.py", line 12, in <module>
    from terminal.notifications import CommandExecutionAlert
  File "/opt/jumpserver/apps/terminal/notifications.py", line 47, in <module>
    class CommandAlertMessage(CommandAlertMixin, SystemMessage):
  File "/opt/jumpserver/apps/notifications/notifications.py", line 36, in __new__
    if not SystemMsgSubscription.objects.filter(message_type=message_type).exists():
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 809, in exists
    return self.query.has_results(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 535, in has_results
    return compiler.has_results()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1126, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/ops/models/__init__.py", line 6, in <module>
    from .command import *
  File "/opt/jumpserver/apps/ops/models/command.py", line 12, in <module>
    from terminal.notifications import CommandExecutionAlert
  File "/opt/jumpserver/apps/terminal/notifications.py", line 47, in <module>
    class CommandAlertMessage(CommandAlertMixin, SystemMessage):
  File "/opt/jumpserver/apps/notifications/notifications.py", line 36, in __new__
    if not SystemMsgSubscription.objects.filter(message_type=message_type).exists():
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 809, in exists
    return self.query.has_results(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 535, in has_results
    return compiler.has_results()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1126, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

Stopping jms_redis ... done
Stopping jms_mysql ... done
Removing jms_redis ... done
Removing jms_mysql ... done
Removing network jms_net

complete

**Comment by wojiushixiaobai** [comment]
删掉mysql的持久化数据，默认是/opt/jumpserver/mysql
```bash
rm -rf /opt/jumpserver/mysql
./jmsctl.sh start
```
等待即可

**Comment by CatGamesGa0** [comment]
> 有掉mysql的持久化数据，默认是/opt/jumpserver/mysql
> 
> ```shell
> rm -rf /opt/jumpserver/mysql 
> ./jmsctl.sh 开始
> ```
> 
> 等待时间

试过了，没用，同样也是CentOs7

**Comment by KU4NG** [comment]
今天试了下，我这边解决了，存在两个问题：
一是默认配置中数据库和 redis 的连接是错的，容器名称是 jms_mysql/ jms_redis，需要改一下。
二是即使改了也不一定成功，MySQL 刚刚创建完成启动直接同步数据还是可能会报错，需要修改 scripts 目录下的 1_config_jumpserver.sh 脚本，在 function init_db() 函数中 ${cmd} up -d 启动命令之后加上一个 sleep 20 让他等一会再同步。

**Comment by nchair** [comment]
> 今天试了下，我这边解决了，存在两个问题：
> 一是默认配置中数据库和 redis 的连接是错的，容器名称是 jms_mysql/ jms_redis，需要改一下。
> 二是即使改了也不一定成功，MySQL 刚刚创建完成启动直接同步数据还是可能会报错，需要修改 scripts 目录下的 1_config_jumpserver.sh 脚本，在 function init_db() 函数中 ${cmd} up -d 启动命令之后加上一个 sleep 20 让他等一会再同步。

实测，mysql容器还是unhealthy。

**Comment by KU4NG** [comment]
报错信息：
`7. 初始化数据库
Creating network "jms_net" with driver "bridge"
Creating jms_redis ... done
Creating jms_mysql ... done
2021-06-29 16:10:49 Collect static files
2021-06-29 16:10:49 Collect static files done
2021-06-29 16:10:49 Check database structure change ...
2021-06-29 16:10:49 Migrate model change to database ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")
`

**Comment by KU4NG** [comment]
报错信息：
7. 初始化数据库
Creating network "jms_net" with driver "bridge"
Creating jms_redis ... done
Creating jms_mysql ... done
2021-06-29 16:10:49 Collect static files
2021-06-29 16:10:49 Collect static files done
2021-06-29 16:10:49 Check database structure change ...
2021-06-29 16:10:49 Migrate model change to database ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

**Comment by KU4NG** [comment]
问了下老广，他说容器内部是做了映射的，就不需要修改配置文件，刚刚试了也是，但是脚本那个必须修改，刚刚我重新下载最新版本试了，也可以，系统是 Centos 7.5.
function init_db() {
  echo_yellow "\n7. $(gettext 'Init JumpServer Database')"
  use_external_mysql=$(get_config USE_EXTERNAL_MYSQL)
  use_ipv6=$(get_config USE_IPV6)
  cmd="docker-compose -f ./compose/docker-compose-redis.yml"
  if [[ "${use_external_mysql}" == "0" ]]; then
    cmd="${cmd} -f ./compose/docker-compose-mysql.yml"
  fi
  if [[ "${use_ipv6}" != "1" ]]; then
    cmd="${cmd} -f compose/docker-compose-network.yml"
  else
    cmd="${cmd} -f compose/docker-compose-network_ipv6.yml"
  fi
  ${cmd} up -d
  sleep 20
  if ! perform_db_migrations; then
    re_code="1"
  fi
  echo
  ${cmd} down
  echo
  if [[ "${re_code}" ]]; then
    log_error "$(gettext 'Failed to change the table structure')!"
    exit 1
  else
    echo_done
  fi
}
