### ISSUE TITLE
windows vscode ssh remote连接不上[Bug] 

### ISSUE THREAD

**Issue by gamestart** [jumpserver/jumpserver#6334]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.11.0

**浏览器版本**
chrome

**Bug 描述**
windows 使用ssh remote 连接不上，但是mac可以

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/9861979/123363440-1c891c80-d5a5-11eb-8f7f-dd5cbcea9899.png)

**Comment by rty813** [comment]
我也连不上，报错信息如下：
![image](https://user-images.githubusercontent.com/22488813/123407095-2a0ec880-d5de-11eb-8c19-f6f572168c96.png)

```
[17:52:20.656] Log Level: 2
[17:52:20.659] remote-ssh@0.65.7
[17:52:20.659] win32 x64
[17:52:20.660] SSH Resolver called for "ssh-remote+68test", attempt 1
[17:52:20.660] "remote.SSH.useLocalServer": false
[17:52:20.660] "remote.SSH.showLoginTerminal": false
[17:52:20.661] "remote.SSH.remotePlatform": {"68":"linux","71":"linux","73":"linux","1070":"linux","30053":"linux","30104":"linux","30166":"linux","60022":"linux","nuc":"linux","192.168.3.100":"linux","nuc_frp":"linux","192.168.3.11":"linux","192.168.3.127":"linux","一楼服务器":"linux","一楼服务器(www-data)":"linux","一楼服务器(Root)":"linux","172.28.112.101":"linux","192.168.3.181":"linux"}
[17:52:20.661] "remote.SSH.path": undefined
[17:52:20.661] "remote.SSH.configFile": undefined
[17:52:20.661] "remote.SSH.useFlock": true
[17:52:20.661] "remote.SSH.lockfilesInTmp": false
[17:52:20.661] "remote.SSH.localServerDownload": auto
[17:52:20.662] "remote.SSH.remoteServerListenOnSocket": false
[17:52:20.662] "remote.SSH.showLoginTerminal": false
[17:52:20.662] "remote.SSH.defaultExtensions": []
[17:52:20.662] "remote.SSH.loglevel": 2
[17:52:20.662] SSH Resolver called for host: 68test
[17:52:20.663] Setting up SSH remote "68test"
[17:52:20.685] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server
[17:52:20.688] Install and start server if needed
[17:52:21.960] Checking ssh with "ssh -V"
[17:52:21.994] > OpenSSH_for_Windows_8.1p1, 
[17:52:21.995] > LibreSSL 3.0.2

[17:52:21.999] Running script with connection command: ssh -T -D 2932 68test bash
[17:52:22.001] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[17:52:22.234] > ]0;C:\WINDOWS\System32\cmd.exe
[17:52:22.234] Got some output, clearing connection timeout
[17:52:22.604] > admin@orca@10.0.1.68@192.168.3.100's password: 
[17:52:22.604] Showing password prompt
[17:52:27.985] Got password response
[17:52:27.985] "install" wrote data to terminal: "******"
[17:52:28.003] > 
[17:52:28.385] > No PTY requested.
[17:52:29.658] "install" terminal command done
[17:52:29.658] Install terminal quit with output: No PTY requested.
[17:52:29.659] Received install output: No PTY requested.
[17:52:29.659] Failed to parse remote port from server output
[17:52:29.660] Resolver error: Error: 
	at Function.Create (c:\Users\doufu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64659)
	at Object.t.handleInstallOutput (c:\Users\doufu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63302)
	at Object.t.tryInstall (c:\Users\doufu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\doufu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\doufu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\doufu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\doufu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[17:52:29.665] ------
```

他能弹出密码输入框，并且密码验证也是正确的。

**Comment by pan3793** [comment]
macOS 下类似的情况。
ssh 可以直连成功，但 scp 以及 ssh 端口转发命令报 No PTY requested.

**Comment by jym503558564** [comment]
windows vscode remote-ssh 我们研发人员已修复，请持续关注我们后续版本发布情况，及时更新。

**Comment by pan3793** [comment]
@jym503558564 有修复 link 吗？以及 scp 问题是否也一并修复了？

**Comment by rty813** [comment]
> @jym503558564 有修复 link 吗？以及 scp 问题是否也一并修复了？

应该还没发布

**Comment by jym503558564** [comment]
快发布了哈，在准备包了，请耐心等待

**Comment by gamestart** [comment]
那等发布了加个链接啊，直接就给closed了。。。

**Comment by sgyy** [comment]
在 v2.16.3 里遇到同样的问题
