### ISSUE TITLE
[Bug] 初始化JumpServer数据库报错（7.Init JumpServer Database：ERROR）

### ISSUE THREAD

**Issue by itfans520** [jumpserver/jumpserver#6338]
**请描述您的问题：** 安装JumpServer时，MySQL初始化异常

**操作系统**
Ubuntu 18.04
Ubuntu 20.04
CentOS 7.9
注：
上述3个操作系统均出现相同报错信息，且
1）已经关闭防火墙，CentOS调整了selinux；
2）更新了Ubuntu的apt源 与CentOS的 yum源；
3）均采用“非external”形式；
4）尝试指定JumpServer 2.10.2 & 2.11.2  均出现同样的报错信息；
5）反复 ./jmsctl start、restart、reconfig 亦出现相同问题；
6）执行 ./jmsctl uninstall 并删除镜像重新安装后，也是同样的报错信息。

**安装步骤**
**1、**
export DOCKER_IMAGE_PREFIX=swr.cn-north-1.myhuaweicloud.com
**2、**
curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.11.2/quick_start.sh | bash
**3、**
cp /opt/jumpserver/config/config.txt /opt/jumpserver-installer-v2.11.2/
**4、**
chmod -R 777 /opt/jumpserver/mysql
**5、**
cd /opt/jumpserver-installer-v2.11.2
./jmsctl.sh start

**Bug 描述**

**7. Init JumpServer Database**
Creating network "jms_net" with driver "bridge"
Creating jms_redis ... done
Creating jms_mysql ... done
2021-06-26 23:23:56 Collect static files
2021-06-26 23:23:56 Collect static files done
2021-06-26 23:23:56 Check database structure change ...
2021-06-26 23:23:56 Migrate model change to database ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/ops/models/__init__.py", line 6, in <module>
    from .command import *
  File "/opt/jumpserver/apps/ops/models/command.py", line 12, in <module>
    from terminal.notifications import CommandExecutionAlert
  File "/opt/jumpserver/apps/terminal/notifications.py", line 47, in <module>
    class CommandAlertMessage(CommandAlertMixin, SystemMessage):
  File "/opt/jumpserver/apps/notifications/notifications.py", line 36, in __new__
    if not SystemMsgSubscription.objects.filter(message_type=message_type).exists():
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 809, in exists
    return self.query.has_results(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 535, in has_results
    return compiler.has_results()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1126, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/ops/models/__init__.py", line 6, in <module>
    from .command import *
  File "/opt/jumpserver/apps/ops/models/command.py", line 12, in <module>
    from terminal.notifications import CommandExecutionAlert
  File "/opt/jumpserver/apps/terminal/notifications.py", line 47, in <module>
    class CommandAlertMessage(CommandAlertMixin, SystemMessage):
  File "/opt/jumpserver/apps/notifications/notifications.py", line 36, in __new__
    if not SystemMsgSubscription.objects.filter(message_type=message_type).exists():
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 809, in exists
    return self.query.has_results(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 535, in has_results
    return compiler.has_results()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1126, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")

Stopping jms_mysql ... done
Stopping jms_redis ... done
Removing jms_mysql ... done
Removing jms_redis ... done
Removing network jms_net

complete

>>> The Installation is Complete
1. You can use the following command to start, and then visit
./jmsctl.sh start

2. Other management commands
./jmsctl.sh stop
./jmsctl.sh restart
./jmsctl.sh backup
./jmsctl.sh upgrade
For more commands, you can enter ./jmsctl.sh --help to understand

3. Web access
http://10.2.9.200:80
https://10.2.9.200:443
Default username: admin  Default password: admin

4. SSH/SFTP access
ssh -p2222 admin@10.2.9.200
sftp -P2222 admin@10.2.9.200

5. More information
Offical Website: https://www.jumpserver.org/
Documentation: https://docs.jumpserver.org/

**启动JumpServer**

root@hfhly:/opt/jumpserver-installer-v2.11.2# ./jmsctl.sh start
WARNING: The HOSTNAME variable is not set. Defaulting to a blank string.
Creating network "jms_net" with driver "bridge"
Creating jms_redis ... done
Creating jms_mysql ... done

ERROR: for core  Container "6759015f452e" is unhealthy.
ERROR: Encountered errors while bringing up the project.
root@hfhly:/opt/jumpserver-installer-v2.11.2# 

**查看报错镜像日志**

root@hfhly:/opt/jumpserver-installer-v2.11.2# docker logs 67
2021-06-26 15:25:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.32-1debian10 started.
2021-06-26 15:25:18+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-06-26 15:25:18+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.32-1debian10 started.

**jms_mysql镜像中mysql的报错信息（/var/log/mysql/error.log）**
root@0c98dd6de06b:/# cd /var/log/
root@0c98dd6de06b:/var/log# ls
alternatives.log  apt  btmp  dpkg.log  faillog	lastlog  mysql	wtmp
root@0c98dd6de06b:/var/log# cd mysql/
root@0c98dd6de06b:/var/log/mysql# ls
error.log
root@0c98dd6de06b:/var/log/mysql# vim error.log 
bash: vim: command not found
root@0c98dd6de06b:/var/log/mysql# more error.log 
2020-12-11T17:05:43.652666Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timest
amp server option (see documentation for more details).
2020-12-11T17:05:43.914014Z 0 [Warning] InnoDB: New log files created, LSN=45790
2020-12-11T17:05:44.076412Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2020-12-11T17:05:44.134482Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has
 been started. Generating a new UUID: 1af528ca-3bd3-11eb-92a5-0242ac120002.
2020-12-11T17:05:44.136505Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2020-12-11T17:05:45.035737Z 0 [Warning] CA certificate ca.pem is self signed.
2020-12-11T17:05:45.657169Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initial
ize-insecure option.
2020-12-11T17:05:48.753623Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timest
amp server option (see documentation for more details).
2020-12-11T17:05:48.755427Z 0 [Note] mysqld (mysqld 5.7.32) starting as process 594 ...
2020-12-11T17:05:48.758615Z 0 [Note] InnoDB: PUNCH HOLE support available
2020-12-11T17:05:48.758633Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-12-11T17:05:48.758640Z 0 [Note] InnoDB: Uses event mutexes
2020-12-11T17:05:48.758645Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2020-12-11T17:05:48.758651Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-12-11T17:05:48.758657Z 0 [Note] InnoDB: Using Linux native AIO
2020-12-11T17:05:48.758931Z 0 [Note] InnoDB: Number of pools: 1
2020-12-11T17:05:48.759057Z 0 [Note] InnoDB: Using CPU crc32 instructions
2020-12-11T17:05:48.761012Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2020-12-11T17:05:48.769432Z 0 [Note] InnoDB: Completed initialization of buffer pool
2020-12-11T17:05:48.771806Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. 
See the man page of setpriority().
2020-12-11T17:05:48.783705Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2020-12-11T17:05:48.792931Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-12-11T17:05:48.792989Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-12-11T17:05:48.812149Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-12-11T17:05:48.812912Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2020-12-11T17:05:48.812927Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2020-12-11T17:05:48.813523Z 0 [Note] InnoDB: 5.7.32 started; log sequence number 2747371
2020-12-11T17:05:48.813705Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-12-11T17:05:48.813874Z 0 [Note] Plugin 'FEDERATED' is disabled.
2020-12-11T17:05:48.815419Z 0 [Note] InnoDB: Buffer pool(s) load completed at 201211 17:05:48
2020-12-11T17:05:48.820165Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support 
using them.
2020-12-11T17:05:48.820181Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2020-12-11T17:05:48.820746Z 0 [Warning] CA certificate ca.pem is self signed.
2020-12-11T17:05:48.820786Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2020-12-11T17:05:48.821088Z 0 [Note] Server hostname (bind-address): '127.0.0.1'; port: 3306
2020-12-11T17:05:48.821111Z 0 [Note]   - '127.0.0.1' resolves to '127.0.0.1';
2020-12-11T17:05:48.821135Z 0 [Note] Server socket created on IP: '127.0.0.1'.
2020-12-11T17:05:48.823259Z 0 [Warning] Insecure configuration for --pid-file: Location '/tmp' in the path is accessible to all OS use
rs. Consider choosing a different directory.
2020-12-11T17:05:48.832715Z 0 [Note] Event Scheduler: Loaded 0 events
2020-12-11T17:05:48.832877Z 0 [Note] Execution of init_file '/var/lib/mysql-files/PGiiHwsuPG' started.
2020-12-11T17:05:48.836175Z 0 [Note] Execution of init_file '/var/lib/mysql-files/PGiiHwsuPG' ended.
2020-12-11T17:05:48.836260Z 0 [Note] mysqld: ready for connections.
Version: '5.7.32'  socket: '/tmp/tmp.c4DNhRcwuH/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2020-12-11T17:05:48.836580Z 0 [Note] Giving 0 client threads a chance to die gracefully
2020-12-11T17:05:48.836600Z 0 [Note] Shutting down slave threads
2020-12-11T17:05:48.836606Z 0 [Note] Forcefully disconnecting 0 remaining clients
2020-12-11T17:05:48.836613Z 0 [Note] Event Scheduler: Purging the queue. 0 events
2020-12-11T17:05:48.836664Z 0 [Note] Binlog end
2020-12-11T17:05:48.836987Z 0 [Note] Shutting down plugin 'auth_socket'
2020-12-11T17:05:48.836997Z 0 [Note] Shutting down plugin 'ngram'
2020-12-11T17:05:48.837002Z 0 [Note] Shutting down plugin 'partition'
2020-12-11T17:05:48.837007Z 0 [Note] Shutting down plugin 'BLACKHOLE'
2020-12-11T17:05:48.837013Z 0 [Note] Shutting down plugin 'ARCHIVE'
2020-12-11T17:05:48.837018Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
2020-12-11T17:05:48.837035Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
2020-12-11T17:05:48.837041Z 0 [Note] Shutting down plugin 'MyISAM'
2020-12-11T17:05:48.837049Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
2020-12-11T17:05:48.837055Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
2020-12-11T17:05:48.837060Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
2020-12-11T17:05:48.837064Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
2020-12-11T17:05:48.837069Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
2020-12-11T17:05:48.837074Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
2020-12-11T17:05:48.837079Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
2020-12-11T17:05:48.837083Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
2020-12-11T17:05:48.837088Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
2020-12-11T17:05:48.837093Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
2020-12-11T17:05:48.837098Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
2020-12-11T17:05:48.837103Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
2020-12-11T17:05:48.837107Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
2020-12-11T17:05:48.837112Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
2020-12-11T17:05:48.837117Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
2020-12-11T17:05:48.837122Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
2020-12-11T17:05:48.837126Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
2020-12-11T17:05:48.837131Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
2020-12-11T17:05:48.837136Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
2020-12-11T17:05:48.837141Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
2020-12-11T17:05:48.837146Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
2020-12-11T17:05:48.837150Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
2020-12-11T17:05:48.837155Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
2020-12-11T17:05:48.837160Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
2020-12-11T17:05:48.837165Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
2020-12-11T17:05:48.837169Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
2020-12-11T17:05:48.837174Z 0 [Note] Shutting down plugin 'INNODB_CMP'
2020-12-11T17:05:48.837179Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
2020-12-11T17:05:48.837184Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
2020-12-11T17:05:48.837189Z 0 [Note] Shutting down plugin 'INNODB_TRX'
2020-12-11T17:05:48.837193Z 0 [Note] Shutting down plugin 'InnoDB'
2020-12-11T17:05:48.837240Z 0 [Note] InnoDB: FTS optimize thread exiting.
2020-12-11T17:05:48.837347Z 0 [Note] InnoDB: Starting shutdown...
2020-12-11T17:05:48.937556Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2020-12-11T17:05:48.937816Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 201211 17:05:48
2020-12-11T17:05:50.974239Z 0 [Note] InnoDB: Shutdown completed; log sequence number 2747592
2020-12-11T17:05:50.976155Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2020-12-11T17:05:50.976173Z 0 [Note] Shutting down plugin 'MEMORY'
2020-12-11T17:05:50.976181Z 0 [Note] Shutting down plugin 'CSV'
2020-12-11T17:05:50.976188Z 0 [Note] Shutting down plugin 'sha256_password'
2020-12-11T17:05:50.976193Z 0 [Note] Shutting down plugin 'mysql_native_password'
2020-12-11T17:05:50.976367Z 0 [Note] Shutting down plugin 'binlog'
2020-12-11T17:05:50.977501Z 0 [Note] mysqld: Shutdown complete

**Comment by wojiushixiaobai** [comment]
删掉mysql的持久化数据，默认是/opt/jumpserver/mysql
```bash
rm -rf /opt/jumpserver/mysql
./jmsctl.sh start
```
等待即可

**Comment by itfans520** [comment]
###**wojiushixiaobai** ： 老师您好！

非常感谢您的帮助，谢谢！
按照您的方法执行后，非常牛的执行成功了，真心感觉“谢谢”两个字很苍白、很敷衍，只等借用星爷一句台词表达我对您的感激之情——我对您的感谢如滔滔江水连绵不绝。

**依照您的建议，我是按照如下操作流程完整的操作执行成功的，以此分享、反馈，希望对其他出现类似问题的同学们有所帮助**
**1、**
在/opt/jumpserver-installer-2.11.2目录执行卸载命令
./jmsctl uninstall
1）选择（Y）清除；
2）选择（Y）清除。
**2、**
删除残留在opt目录下的jumpserver-installer-2.11.2目录
rm -rf /opt/jumpserver-installer-2.11.2
**3、**
在opt目录下（或者任意目录均可）执行 “下载并安装”命令
curl -sSL https://github.com/jumpserver/jumpserver/releases/download/v2.11.2/quick_start.sh | bash
（如果失败，可以尝试更新操作系统的“源”（我用的是ubuntu的阿里源，但我最近发现ubuntu自带的源也是可以的，很好使，下载速度也很快）；即便提示报错，尝试多执行几次也会出现奇迹的）
**4、**
现在不用cp /opt/jumpserver/config/config.txt 文件到 /opt/jumpserver-installer-2.11.2目录了，我记得以前是需要的（也有可能是我以前就搞错了——其实一直都是不需要的，whatever啦，反正这句话现在其实已经变成“废话”啦，哈哈哈！）
直接到/opt/jumpserver-installer-2.11.2目录执行“启动”命令
./jmsctl start

###**5、重点来啦**
因为刚刚是 重新清除了 jumpserver上一次的所有文件，所以之前按照“woshixiaobai”老师的方法“删除mysql支持就花数据”的操作就已经不存在了，所以这时依然会报我上面提到的错误，what小erver啦！到/opt/jumpserver目录再删一次嘛！
rm -rf /opt/jumpserver/mysql

**6、**
返回到/opt/jumpserver-installer-2.11.2目录，继续执行 jumpserver的“启动”命令
./jmsctl.sh start

Creating network "jms_net" with driver "bridge"
Creating jms_mysql ... done
Creating jms_redis ... done
Creating jms_core  ... done
ERROR: for celery  Container "76b2e315f69d" is unhealthy.
ERROR: for lina  Container "76b2e315f69d" is unhealthy.
ERROR: for luna  Container "76b2e315f69d" is unhealthy.
ERROR: for lion  Container "76b2e315f69d" is unhealthy.
ERROR: for koko  Container "76b2e315f69d" is unhealthy.
ERROR: Encountered errors while bringing up the project.

# 如果出现上面的错误, 执行下面的命令, 直到出现 Check service status 为止
docker logs -f jms_core --tail 200  # 如果没有报错就等表结构合并完毕后然后重新 start 即可
