### ISSUE TITLE
coco  运行一段时间会有如下报错 导致 登录不上 重启coco 就好了

### ISSUE THREAD

**Issue by zsjohny** [jumpserver/jumpserver#636]
```
2017-08-22 05:34:01 [transport DEBUG] Auth request (type=none) service=ssh-connection, username=johny
2017-08-22 05:34:01 [transport INFO] Auth rejected (none).
2017-08-22 05:34:01 [transport DEBUG] Auth request (type=publickey) service=ssh-connection, username=johny
2017-08-22 05:34:01 [interface DEBUG] Start check auth
2017-08-22 05:34:01 [transport ERROR] Unknown exception: '_AppCtxGlobals' object has no attribute 'user_service'
2017-08-22 05:34:01 [transport ERROR] Traceback (most recent call last):
2017-08-22 05:34:01 [transport ERROR]   File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 1860, in run
2017-08-22 05:34:01 [transport ERROR]     handler(self.auth_handler, m)
2017-08-22 05:34:01 [transport ERROR]   File "/usr/local/lib/python3.6/site-packages/paramiko/auth_handler.py", line 461, in _parse_userauth_request
2017-08-22 05:34:01 [transport ERROR]     username, key)
2017-08-22 05:34:01 [transport ERROR]   File "/opt/coco/coco/interface.py", line 92, in check_auth_publickey
2017-08-22 05:34:01 [transport ERROR]     if self.check_auth(username, public_key=public_key_s):
2017-08-22 05:34:01 [transport ERROR]   File "/opt/coco/coco/interface.py", line 63, in check_auth
2017-08-22 05:34:01 [transport ERROR]     user, token = g.user_service.login(data)
2017-08-22 05:34:01 [transport ERROR]   File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
2017-08-22 05:34:01 [transport ERROR]     return getattr(self._get_current_object(), name)
2017-08-22 05:34:01 [transport ERROR] AttributeError: '_AppCtxGlobals' object has no attribute 'user_service'
2017-08-22 05:34:01 [transport ERROR]
2017-08-22 05:34:01 [app WARNING] No ssh channel get.
```

@ibuler 
https://github.com/jumpserver/coco/blob/master/coco/interface.py#L62-L70

**Comment by zsjohny** [comment]
@ibuler

**Comment by ibuler** [comment]
问题 同 #698
