### ISSUE TITLE
[Bug]  升级2.12.0后 资产列表 Request failed with status code 500

### ISSUE THREAD

**Issue by Changego** [jumpserver/jumpserver#6472]
**JumpServer 版本(v1.5.9以下不再支持)**
2.12.0

**浏览器版本**
火狐89.0 X64

**Bug 描述**
1.资产列表 Request failed with status code 500
2.web终端,左侧树 菜单点击无反应,无法操作
**Bug 重现步骤(有截图更好)**
1.  必现

**Comment by jym503558564** [comment]
升级的报错日志贴出来

**Comment by Changego** [comment]
升级过程.经过重试,镜像加速,倒不算有问题.
这个是点资产列表的jumpserver.log报错.  
  
2021-07-16 15:43:52 [log ERROR] Internal Server Error: /api/v1/perms/users/nodes/children-with-assets/tree/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'assets_asset.admin_user_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/perms/api/asset/user_permission/mixin.py", line 33, in get
    return super().get(request, *args, **kwargs)
  File "/opt/jumpserver/apps/perms/api/asset/user_permission/mixin.py", line 21, in get
    return super().get(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "/opt/jumpserver/apps/perms/api/asset/user_permission/user_permission_nodes_with_assets.py", line 145, in list
    tree_assets = self.serialize_assets(assets, key)
  File "/opt/jumpserver/apps/common/utils/common.py", line 209, in wrapper
    result = func(*args, **kwargs)
  File "/opt/jumpserver/apps/assets/api/mixin.py", line 56, in serialize_assets
    data = [
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'assets_asset.admin_user_id' in 'field list'")

**Comment by szlyunnan** [comment]
我遇到的是这种
![image](https://user-images.githubusercontent.com/12928768/125914123-03c2ec2e-a53e-42b0-82c2-769a06c2cb02.png)

**Comment by jym503558564** [comment]
升级错了吧，我们最新版本里已经去掉了assets_asset.admin_user_id。您现在版本是？

**Comment by Changego** [comment]
2.12.0啊
没毛病啊.
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                       PORTS                                            NAMES
a3530144b18e        jumpserver/koko:v2.12.0     "./entrypoint.sh"        About an hour ago   Up About an hour (healthy)   2222/tcp, 5000/tcp                               jms_koko
1dfc08aef1d1        jumpserver/nginx:v2.12.0    "/docker-entrypoin..."   About an hour ago   Up About an hour (healthy)   0.0.0.0:60080->80/tcp, 0.0.0.0:60022->2222/tcp   jms_nginx
d567dd55f445        jumpserver/lion:v2.12.0     "/usr/bin/supervisord"   About an hour ago   Up About an hour (healthy)   4822/tcp                                         jms_lion
e27f4bb5433d        jumpserver/core:v2.12.0     "./entrypoint.sh s..."   About an hour ago   Up About an hour (healthy)   8070/tcp, 8080/tcp                               jms_celery
7ecf606c74ab        jumpserver/core:v2.12.0     "./entrypoint.sh s..."   About an hour ago   Up About an hour (healthy)   8070/tcp, 8080/tcp                               jms_core
d934e7d278dd        jumpserver/redis:6-alpine   "docker-entrypoint..."   21 hours ago        Up 2 hours (healthy)         6379/tcp                                         jms_redis
dcd9e33cf8b0        jumpserver/mysql:5          "docker-entrypoint..."   21 hours ago        Up 2 hours (healthy)         3306/tcp, 33060/tcp                              jms_mysql

**Comment by jym503558564** [comment]
installer 也是最新版本吗？
还原数据库，重新升级吧。
社区版升级参考：https://docs.jumpserver.org/zh/master/install/upgrade/upgrade/

**Comment by Changego** [comment]
installer 也是最新版本是最新的.
感谢,我试试吧.

**Comment by jym503558564** [comment]
@Changego 升级成功了吗？

**Comment by Changego** [comment]
没有，重建了。连续重建3次了。

**Comment by Changego** [comment]
多谢，请帮关闭吧。我的问题，重建后的确没问题了。

**Comment by jym503558564** [comment]
社区群联系一下小白，远程帮你看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chang ***@***.***&gt;
发送时间: 2021年7月16日 19:19
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: 八千流 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[jumpserver/jumpserver] [Bug]  升级2.12.0后 资产列表 Request failed with status code 500 (#6472)





 
没有，重建了。连续重建3次了。

**Comment by jym503558564** [comment]
好的，如还有其他疑问，可再次提Issues



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chang ***@***.***&gt;
发送时间: 2021年7月16日 19:22
收件人: jumpserver/jumpserver ***@***.***&gt;
抄送: 八千流 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[jumpserver/jumpserver] [Bug]  升级2.12.0后 资产列表 Request failed with status code 500 (#6472)





 
多谢，请帮关闭吧。我的问题，重建后的确没问题了。

**Comment by wojiushixiaobai** [comment]
升级过程有错误，仔细检查，把原始的错误发出来。你的错误是第二次或者更后续的错误了，需要第一次的错误
