### ISSUE TITLE
使用web连接主机错误，

### ISSUE THREAD

**Issue by fxqmifi** [jumpserver/jumpserver#657]
正常新建了用户，添加了主机资源，添加了系统用户，和sudo，并成功的推送了系统用户；
也对用户进行主机授权；
但是用用户登录后，点击连接主机之后，报错
错误提示：Connecting...Connection Reset By Peer

**Comment by hellorocky** [comment]
最好说明更多背景, 比如使用的哪个版本, 使用的终端还是web终端, 有没有相关错误日志等等

**Comment by fxqmifi** [comment]
版本是0.3.2，使用的是web终端，日志错误提示
ERROR:tornado.application:Uncaught exception in /ws/terminal
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/websocket.py", line 417, in _run_callback
    callback(*args, **kwargs)
  File "run_server.py", line 367, in on_message
    self.termlog.write(jsondata)
  File "/data/jumpserver/jlog/views.py", line 267, in write
    self.log[str(time.time() - self.recoderStartTime)] = msg.decode('utf-8', 'replace')
AttributeError: 'dict' object has no attribute 'decode'
DEBUG:jumpserver:Websocket: Close request
{}
