### ISSUE TITLE
0.4.0批量导入报错

### ISSUE THREAD

**Issue by liushuai168** [jumpserver/jumpserver#665]
2017-08-31 16:49:26 [exception ERROR] Internal Server Error: /assets/asset/import/
Traceback (most recent call last):
  File "/usr/local/python36/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/python36/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python36/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/python36/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/usr/local/python36/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/python36/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 116, in dispatch
    return super(UserPassesTestMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/python36/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/python36/lib/python3.6/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/opt/jumpserver/apps/assets/views/asset.py", line 246, in form_valid
    data = file.read().decode('utf-8').strip(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 16: invalid start byte
2017-08-31 16:49:26 [basehttp ERROR] "POST /assets/asset/import/ HTTP/1.1" 500 18858

**Comment by liushuai168** [comment]
这个bug何时修复呢，谢谢各位大神

**Comment by ibuler** [comment]
已修复
