### ISSUE TITLE
添加阿里云的cas认证，后台服务报错

### ISSUE THREAD

**Issue by caoxiaojin** [jumpserver/jumpserver#6681]
部署方式才有官方手动方式部署的
cas配置如下
# CAS 配置
AUTH_CAS=True
CAS_SERVER_URL=https://*******iplugin_cas_apereo1/
CAS_ROOT_PROXIED_AS=http://jumpserver.work
CAS_LOGOUT_COMPLETELY=True
CAS_VERSION=3

CAS_USERNAME_ATTRIBUTE=uid
CAS_APPLY_ATTRIBUTES_TO_USER=Flase
CAS_CREATE_USER=True
后台报错日志如下：
2021-08-18 18:10:38 [log ERROR] Internal Server Error: /core/auth/cas/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_cas_ng/views.py", line 70, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_cas_ng/views.py", line 122, in get
    user = authenticate(ticket=ticket,
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.8/site-packages/django_cas_ng/backends.py", line 20, in authenticate
    username, attributes, pgtiou = client.verify_ticket(ticket)
  File "/usr/local/lib/python3.8/site-packages/cas.py", line 166, in verify_ticket
    return self.verify_response(response)
  File "/usr/local/lib/python3.8/site-packages/cas.py", line 259, in verify_response
    return cls.parse_response_xml(response)
  File "/usr/local/lib/python3.8/site-packages/cas.py", line 223, in parse_response_xml
    tree = ElementTree.fromstring(response)
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by caoxiaojin** [comment]
CAS_VERSION=2   使用这个配置是正常的，3就报错
