### ISSUE TITLE
[Question] 添加资产限制500错误，日志显示redis报错

### ISSUE THREAD

**Issue by miahwk** [jumpserver/jumpserver#6746]
> 添加资产报错，显示500错误信息

> 日志如下

> 2021-08-31 14:44:25 [log ERROR] Internal Server Error: /api/v1/assets/nodes/c355eec4-f75a-4521-8193-9116816e9621/children/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/db/transaction.py", line 276, in __exit__
    connection.set_autocommit(True)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 420, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 651, in run_and_clear_commit_hooks
    func()
  File "/opt/jumpserver/apps/common/utils/lock.py", line 160, in _release
    self._release_redis_lock()
  File "/opt/jumpserver/apps/common/utils/lock.py", line 156, in _release_redis_lock
    super().release()
  File "/usr/local/lib/python3.8/site-packages/redis_lock/__init__.py", line 353, in release
    error = _eval_script(self._client, UNLOCK_SCRIPT, self._name, self._signal, self._signal_expire, args=(self._id,))
  File "/usr/local/lib/python3.8/site-packages/redis_lock/__init__.py", line 126, in _eval_script
    return redis.evalsha(SCRIPTS[script_id], len(keys), *keys + args)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3143, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: 'EVALSHA' command keys must in same slot

> redis用的阿里云的，不知道怎么解决

**Comment by wojiushixiaobai** [comment]
Redis 版本需要大于等于 > 5.0
