### ISSUE TITLE
4.0 邮箱设置发邮件报错

### ISSUE THREAD

**Issue by lanbing222** [jumpserver/jumpserver#686]
咨询下，邮箱设置如下
![image](https://user-images.githubusercontent.com/25219658/30239027-0f6c23d4-9586-11e7-9f1e-fab1a6b5297f.png)

发邮件报错如下，请问各位兄弟是不是我那里设置错了

[2017-09-09 17:24:33,217: INFO/MainProcess] Received task: common.tasks.send_mail_async[0b280396-c54c-4ff0-b543-2470cdd6e894]
[2017-09-09 17:24:33,218: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x3d60d70> (args:('common.tasks.send_mail_async', '0b280396-c54c-4ff0-b543-2470cdd6e894', {'lang': 'py', 'retries': 0, 'origin': 'gen30378@server.3', 'task': 'common.tasks.send_mail_async', 'group': None, 'root_id': '0b280396-c54c-4ff0-b543-2470cdd6e894', u'delivery_info': {u'priority': 0, u'redelivered': None, u'routing_key': 'celery', u'exchange': u''}, 'expires': None, u'correlation_id': '0b280396-c54c-4ff0-b543-2470cdd6e894', 'timelimit': [None, None], 'argsrepr': u'(\'\u521b\u5efa\u8d26\u6237\u6210\u529f\', \'\n    \u4f60\u597d \u6731\u8363\u4f73:\n    </br>\n    \u606d\u559c\u60a8\uff0c\u60a8\u7684\u8d26\u53f7\u5df2\u7ecf\u521b\u5efa\u6210\u529f    </br>\n     <a href="http://10.8.75.85:8080/users/password/reset?token=eyJhbGciOiJIUzI1NiIsImlhdCI6MTUwNDk0OTA3MywiZXhwIjoxNTA0OTUyNjczfQ.eyJyZXNldCI6MTUsImVtYWlsIjoiemh1cm9uZ2ppYUBkcy5jbiJ9.mQkhPZqncbR1AttwgkNU92G8khrLkZ1P4BgMU2vMljA">\u8bf7\u70b9\u51fb\u8fd9\u91cc\u8bbe\u7f6e\u5bc6\u7801</a>    </br>\n    \u8fd9\u4e2a\u94fe\u63a5\u6709\u6548\u671f1\u5c0f\u65f6,... kwargs:{})
[2017-09-09 17:24:33,251: DEBUG/MainProcess] Task accepted: common.tasks.send_mail_async[0b280396-c54c-4ff0-b543-2470cdd6e894] pid:30542
2017-09-09 17:24:33 [basehttp INFO] "POST /users/user/create HTTP/1.1" 302 0
2017-09-09 17:24:33 [basehttp INFO] "GET /users/user HTTP/1.1" 200 21395
[2017-09-09 17:24:33,395: ERROR/ForkPoolWorker-4] Task common.tasks.send_mail_async[0b280396-c54c-4ff0-b543-2470cdd6e894] raised unexpected: SMTPAuthenticationError(535, 'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/common/tasks.py", line 29, in send_mail_async
    send_mail(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/usr/lib64/python2.7/site-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/lib64/python2.7/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "/usr/lib64/python2.7/site-packages/django/core/mail/backends/smtp.py", line 71, in open
    self.connection.login(force_str(self.username), force_str(self.password))
  File "/usr/lib64/python2.7/smtplib.py", line 621, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, 'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')

**Comment by jiaxiangkong** [comment]
邮箱认证失败

**Comment by lanbing222** [comment]
能否帮忙发下这个邮箱的配置说明，测试了很多次，都是不发邮件 @jiaxiangkong  多谢

**Comment by hfq-haochenxiao** [comment]
ssl 协议没开启

**Comment by majun9129** [comment]
把EMAIL_USER_SSL 设置成False
