### ISSUE TITLE
jumpserver v2.13.2 升级 v 2.14.2 失败[Bug] 

### ISSUE THREAD

**Issue by wuweilin99** [jumpserver/jumpserver#6999]
# JumpServer 版本：v2.13.2

**Bug 描述**
MariaDB数据库，版本为10.5.12，数据库字符集为utf-8，在使用在线升级脚本升级至v2.14.2时报错，
476 static files copied to '/opt/jumpserver/data/static'.
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  Applying applications.0010_appaccount_historicalappaccount...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1005, 'Can\'t create table `jumpserver`.`applications_historicalaccount` (errno: 150 "Foreign key constraint is incorrectly formed")')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 229, in apply_migration
    migration_recorded = True
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 115, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1005, 'Can\'t create table `jumpserver`.`applications_historicalaccount` (errno: 150 "Foreign key constraint is incorrectly formed")')
2021-10-11 20:39:57 Perform migrate failed, exit
[ERROR] Failed to change the table structure!

**Comment by xmskf** [comment]
一样遇上相同的问题，从JumpServer 版本：v2.13.2 升级  v2.14.0 也会失败，提示错误

**Comment by xmskf** [comment]
。。。。没人搭理吗？

**Comment by ibuler** [comment]
应该是字符校对集发生了变更

**Comment by ibuler** [comment]
参考这个文章：

https://github.com/jumpserver/jumpserver/issues/6918

**Comment by xmskf** [comment]
> 参考这个文章：
> 
> #6918

经过测试并没有用，
我先    更换为 utf8_bin 校对集
再   还原为 utf8_general_ci 校对集



依旧报了如下错误：

django.db.utils.OperationalError: (1050, "Table 'tickets_approvalrule_assignees' already exists")
2022-01-20 10:43:56 Perform migrate failed, exit
[ERROR] Failed to change the table structure!

django.db.utils.OperationalError: (1050, "Table 'tickets_approvalrule' already exists")
2022-01-20 10:38:57 Perform migrate failed, exit
[ERROR] Failed to change the table structure!

django.db.utils.ProgrammingError: (1146, "Table 'jumpserver.tickets_ticket' doesn't exist")
2022-01-20 10:54:15 Perform migrate failed, exit
[ERROR] Failed to change the table structure!

后参考官方文档，删除数据库重建，然后在restore_db.结果还是不行……

有尝试提示的表，并执行   ./jmsctl.sh start    也是报一样的错误。

目前测试过jumpserver 

v2.14.0
v2.14.1
v2.16.2
v2.17.3

最终问题：
有办法导出数据库（只保留必要的表或内容）。然后重新搭建一套新的jumpserver 导入数据吗?

**Comment by wojiushixiaobai** [comment]
已经错误的数据库升级就会出现此错误。
必须使用正常的数据库备份出现导入后重新升级

**Comment by xmskf** [comment]
> django.db.utils.OperationalError: (1050, "Table '*' already exists") 已经错误的数据库升级就会出现此错误。 必须使用正常的数据库备份出现导入后重新升级

大佬，如果没有正确的数据库备份怎么处理？ @ @wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
emmm。这个比较难搞。可以参考 django 文档 合并数据库 失败的方法

**Comment by xmskf** [comment]
@ibuler @wojiushixiaobai @wuweilin99  
 各位大佬，我通过下面办法处理完成，终于升级成功，感谢各位的支持！
1、备份旧的数据库。导出纯数据（不含表结构）
2、创建一个空白的jumpserver v2.13.2
3、通过导出的数据和新的空白库对比表（删除多余的表）
4、导入数据
5、重启jumpserver
6、查看数据恢复情况。
7、后面就正常升级即可。

**Comment by wojiushixiaobai** [comment]
这个除了比较麻烦之外，可行。
