### ISSUE TITLE
无法创建用户：TypeError at /users/user/create

### ISSUE THREAD

**Issue by IamEricqi** [jumpserver/jumpserver#708]
环境：centos 7.2
Python：2.7 与后安装3.6.2
安装wiki里的教程，一步一步安装没有错误，但是在创建用户的时候提示，如下错误：
1、浏览器显示：
TypeError at /users/user/create
str() takes at most 1 argument (2 given)
Request Method:	POST
Request URL:	http://192.168.1.100:8080/users/user/create
Django Version:	1.11.5
Exception Type:	TypeError
Exception Value:	
str() takes at most 1 argument (2 given)
Exception Location:	/home/soft/jumpserver/apps/common/utils.py in sign_t, line 71
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	
['/home/soft/jumpserver/apps',
 '/usr/lib64/python27.zip',
 '/usr/lib64/python2.7',
 '/usr/lib64/python2.7/plat-linux2',
 '/usr/lib64/python2.7/lib-tk',
 '/usr/lib64/python2.7/lib-old',
 '/usr/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7/site-packages',
 '/usr/lib/python2.7/site-packages',
 '/home/soft/jumpserver',
 '/home/soft/jumpserver/apps']
Server time:	星期日, 10 九月 2017 06:21:46 +0800
Traceback Switch to copy-and-paste view
.......
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

2、日志显示：
2017-09-10 07:12:33 [basehttp INFO] "GET /static/img/facio.ico HTTP/1.1" 200 1744
2017-09-10 07:12:45 [exception ERROR] Internal Server Error: /users/user/create
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/contrib/auth/mixins.py", line 116, in dispatch
    return super(UserPassesTestMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/edit.py", line 217, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/home/soft/jumpserver/apps/users/views/user.py", line 77, in form_valid
    user_add_success_next(user)
  File "/home/soft/jumpserver/apps/users/utils.py", line 61, in user_add_success_next
    'rest_password_token': user.generate_reset_token(),
  File "/home/soft/jumpserver/apps/users/models/user.py", line 192, in generate_reset_token
    return signer.sign_t({'reset': self.id, 'email': self.email}, expires_in=3600)
  File "/home/soft/jumpserver/apps/common/utils.py", line 71, in sign_t
    return str(s.dumps(value), encoding="utf8")
TypeError: str() takes at most 1 argument (2 given)

**Comment by IamEricqi** [comment]
以下是Python3 run_server.py启动的结果：
start celery
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "run_server.py", line 22, in start_django
    http_host = CONFIG.HTTP_BIND_HOST or '127.0.0.1'
TypeError: 'NoneType' object is not callable

/usr/lib/python2.7/site-packages/celery/platforms.py:795: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
[2017-09-10 07:37:56,475: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2017-09-10 07:37:56,497: DEBUG/MainProcess] | Worker: Building graph...
[2017-09-10 07:37:56,497: DEBUG/MainProcess] | Worker: New boot order: {StateDB, Timer, Hub, Pool, Autoscaler, Beat, Consumer}
[2017-09-10 07:37:56,512: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2017-09-10 07:37:56,513: DEBUG/MainProcess] | Consumer: Building graph...
[2017-09-10 07:37:56,531: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Tasks, Control, Heart, Gossip, Agent, event loop}
 
 -------------- celery@localhost.localdomain v4.1.0 (latentcall)
---- **** ----- 
--- * ***  * -- Linux-3.10.0-327.el7.x86_64-x86_64-with-centos-7.2.1511-Core 2017-09-10 07:37:56
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         jumpserver:0x1dfa590
- ** ---------- .> transport:   redis://127.0.0.1:6379/3
- ** ---------- .> results:     redis://127.0.0.1:6379/3
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . assets.tasks.test_admin_user_connective_period
  . assets.tasks.update_assets_hardware_info
  . assets.tasks.update_assets_hardware_period
  . audits.tasks.write_login_log_async
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . common.tasks.send_mail_async
  . ops.tasks.rerun_task
  . perms.tasks.push_users

[2017-09-10 07:37:56,542: DEBUG/MainProcess] | Worker: Starting Hub
[2017-09-10 07:37:56,542: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:56,542: DEBUG/MainProcess] | Worker: Starting Pool
[2017-09-10 07:37:56,837: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:56,838: DEBUG/MainProcess] | Worker: Starting Beat
[2017-09-10 07:37:56,849: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:56,850: DEBUG/MainProcess] | Worker: Starting Consumer
[2017-09-10 07:37:56,850: DEBUG/MainProcess] | Consumer: Starting Connection
[2017-09-10 07:37:56,879: INFO/Beat] beat: Starting...
[2017-09-10 07:37:56,880: INFO/MainProcess] Connected to redis://127.0.0.1:6379/3
[2017-09-10 07:37:56,880: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:56,880: DEBUG/MainProcess] | Consumer: Starting Events
[2017-09-10 07:37:56,892: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:56,892: DEBUG/MainProcess] | Consumer: Starting Mingle
[2017-09-10 07:37:56,892: INFO/MainProcess] mingle: searching for neighbors
[2017-09-10 07:37:56,899: DEBUG/Beat] Current schedule:
<ScheduleEntry: test-admin-user-connective assets.tasks.test_admin_user_connective_period() <freq: 2.50 days>
<ScheduleEntry: refresh-asset-hardware-info assets.tasks.update_assets_hardware_period() <freq: 60.00 days>
[2017-09-10 07:37:56,899: DEBUG/Beat] beat: Ticking with max interval->5.00 minutes
[2017-09-10 07:37:56,900: DEBUG/Beat] beat: Waking up in 5.00 minutes.
[2017-09-10 07:37:57,926: INFO/MainProcess] mingle: all alone
[2017-09-10 07:37:57,926: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:57,927: DEBUG/MainProcess] | Consumer: Starting Tasks
[2017-09-10 07:37:57,953: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:57,954: DEBUG/MainProcess] | Consumer: Starting Control
[2017-09-10 07:37:57,966: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:57,967: DEBUG/MainProcess] | Consumer: Starting Heart
[2017-09-10 07:37:57,970: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:57,970: DEBUG/MainProcess] | Consumer: Starting Gossip
[2017-09-10 07:37:57,977: DEBUG/MainProcess] ^-- substep ok
[2017-09-10 07:37:57,978: DEBUG/MainProcess] | Consumer: Starting event loop
[2017-09-10 07:37:57,978: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2017-09-10 07:37:57,981: WARNING/MainProcess] /usr/lib/python2.7/site-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2017-09-10 07:37:57,981: INFO/MainProcess] celery@localhost.localdomain ready.
[2017-09-10 07:37:57,982: DEBUG/MainProcess] basic.qos: prefetch_count->16
到这里就卡主不动，jumpserver也没启动起来

**Comment by IamEricqi** [comment]
已经搞定！！原因是启动服务时用的是系统的python2，应该是在py3环境下（并非python3 run_server.py），如下！！
$ cd /opt
$ python3 -m venv py3
$ source /opt/py3/bin/activate
# 看到下面的提示符代表成功
(py3) [root@localhost py3]#

**Comment by hellorocky** [comment]
可以关闭issue了
