### ISSUE TITLE
[Question] 使用外置redis和mysql，报redis的错误

### ISSUE THREAD

**Issue by Songfeiyu1** [jumpserver/jumpserver#7137]
使用外置redis和mysql，报redis的错误
redis 6.2.6

2021-11-03 17:03:10 [log ERROR] Internal Server Error: /api/v1/perms/users/nodes/children/tree/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis_lock/__init__.py", line 126, in _eval_script
    return redis.evalsha(SCRIPTS[script_id], len(keys), *keys + args)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3143, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.NoScriptError: No matching script. Please use EVAL.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/db/transaction.py", line 276, in __exit__
    connection.set_autocommit(True)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 420, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 651, in run_and_clear_commit_hooks
    func()
  File "/opt/jumpserver/apps/common/utils/lock.py", line 160, in _release
    self._release_redis_lock()
  File "/opt/jumpserver/apps/common/utils/lock.py", line 156, in _release_redis_lock
    super().release()
  File "/usr/local/lib/python3.8/site-packages/redis_lock/__init__.py", line 353, in release
    error = _eval_script(self._client, UNLOCK_SCRIPT, self._name, self._signal, self._signal_expire, args=(self._id,))
  File "/usr/local/lib/python3.8/site-packages/redis_lock/__init__.py", line 129, in _eval_script
    return redis.eval(SCRIPTS[script_id + 1], len(keys), *keys + args)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 3131, in eval
    return self.execute_command('EVAL', script, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `EVAL`, with args beginning with: `     if redis.call("get", KEYS[1]) ~= ARGV[1] then         return 1     else         redis.call("del", KEYS[2])         redis.ca`,

**Comment by wojiushixiaobai** [comment]
确定外置应用符合版本要求
- [ ] Redis >= 5.0
- [ ] MySQL >= 5.7

**Comment by omyhub** [comment]
也遇到了，好像是stop,down 之后，celery之类的组件就对识别配置有问题，怀疑是读不到端口。
现在我web和终端用着没啥问题，偶尔会报，但是celery，批量任务测了下全都失败。日志显示连不到数据库。可能原因，授权时限制网段，后面重启，容器实例ip变了，检查了下，网段没变。

**Comment by zhaolinyu** [comment]
遇到同样的问题，外置Redis模式，报端口解析异常，Redis版本>6.0。楼主有解决办法了么
2022-03-24 10:31:16 [log ERROR] Internal Server Error: /api/v1/terminal/terminal-registrations/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/opt/jumpserver/apps/terminal/api/terminal.py", line 105, in create
    return super().create(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/opt/jumpserver/apps/terminal/serializers/terminal.py", line 137, in create
    sa.set_component_role()
  File "/opt/jumpserver/apps/users/models/user.py", line 344, in set_component_role
    self.system_roles.add(role)
  File "/opt/jumpserver/apps/users/models/user.py", line 228, in add
    self.user.expire_users_rbac_perms_cache()
  File "/opt/jumpserver/apps/users/models/user.py", line 293, in expire_users_rbac_perms_cache
    cache.delete_pattern(key)
  File "/usr/local/lib/python3.8/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_redis/cache.py", line 96, in delete_pattern
    return self.client.delete_pattern(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_redis/client/default.py", line 254, in delete_pattern
    client = self.get_client(write=True)
  File "/usr/local/lib/python3.8/site-packages/django_redis/client/default.py", line 90, in get_client
    self._clients[index] = self.connect(index)
  File "/usr/local/lib/python3.8/site-packages/django_redis/client/default.py", line 103, in connect
    return self.connection_factory.connect(self._server[index])
  File "/usr/local/lib/python3.8/site-packages/django_redis/pool.py", line 64, in connect
    connection = self.get_connection(params)
  File "/usr/local/lib/python3.8/site-packages/django_redis/pool.py", line 75, in get_connection
    pool = self.get_or_create_connection_pool(params)
  File "/usr/local/lib/python3.8/site-packages/django_redis/pool.py", line 94, in get_or_create_connection_pool
    self._pools[key] = self.get_connection_pool(params)
  File "/usr/local/lib/python3.8/site-packages/django_redis/pool.py", line 107, in get_connection_pool
    pool = self.pool_cls.from_url(**cp_params)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1034, in from_url
    'port': int(url.port or 6379),
  File "/usr/local/lib/python3.8/urllib/parse.py", line 177, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'QmK+hqjbm'

**Comment by wojiushixiaobai** [comment]
@zhaolinyu 哨兵或者集群模式的 redis，先改为单节点的 redis 试试

**Comment by zhaolinyu** [comment]
> 

Redis只有一个节点，不是哨兵、集群模式

**Comment by zhaolinyu** [comment]
> 
密码中确实包含特殊字符，我先去掉试一下

**Comment by zhaolinyu** [comment]
> 配置文件填写的 redis 相关内容发出来看看，如果密码字段包含特殊字符串可以先临时去掉试试

解决了，确实是特殊字符的原因，密码直接使用数字+字母组合就可以了。非常感谢
