### ISSUE TITLE
[Bug] goauthentik and OpenID integration

### ISSUE THREAD

**Issue by senolcolak** [jumpserver/jumpserver#7215]
**JumpServer 版本**
v2.15.4

**浏览器版本**
Chrome, Edge, Brave

**Bug 描述**
OpenID Auth is not working.
Keycloak OpenID Auth is working in our environment, but we need to use another tool called goAuthentik (https://goauthentik.io/). When we change the configuration to the following.
![image](https://user-images.githubusercontent.com/11789157/142244314-4468d049-5fc5-46aa-a0b2-82e9662bb543.png)

if I try to login with oauth, I get
"Server error occur, contact administrator"
the return url is:
https://jumpserver.example.com/core/auth/openid/callback/?code=c123d3692b9c43b3a43sa393a6240019&state=IIdjeFBO28kafv3naabbHawqpchzrADv

I get the following exception inside gunicorn.log
```
2021-11-18 01:01:26 [log ERROR] Internal Server Error: /core/auth/openid/callback/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jms_oidc_rp/backends.py", line 143, in authenticate
    token_response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://id.example.com/application/o/token/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jms_oidc_rp/views.py", line 142, in get
    user = auth.authenticate(nonce=nonce, request=request)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 60, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.8/site-packages/jms_oidc_rp/decorator.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jms_oidc_rp/backends.py", line 149, in authenticate
    raise ParseError(error)
rest_framework.exceptions.ParseError: Json token response error, token response content is: b'', error is: 405 Client Error: Method Not Allowed for url: https://id.example.com/application/o/token/
172.16.240.5 [18/Nov/2021:01:01:26 +0800] 0.067794s "GET /core/auth/openid/callback/?code=c123d3692b9c43b3a43sa393a6240019&state=IIdjeFBO28kafv3naabbHawqpchzrADv HTTP/1.0" 500 180
```

**Comment by senolcolak** [comment]
I solved the problem, the problem was relaed to the keyword null was missing in the line "Provider Sign Key". 
after some plenty of time digging around..

**Comment by ibuler** [comment]
Need fix something ?

**Comment by ParinLL** [comment]
> I solved the problem, the problem was relaed to the keyword null was missing in the line "Provider Sign Key". after some plenty of time digging around.. You can close the ticket.

Could you please provide the field format? I use the Google OIDC and encounter the same problem...

**Comment by senolcolak** [comment]
![screen-oauth-jumpserver](https://user-images.githubusercontent.com/11789157/153559908-c0611108-6023-4c25-97e8-0885c64d9d26.png)
I provided the working config
