### ISSUE TITLE
[Question] 您好，我配置mysql、redis已经各种依赖后，启动jump的时候，报db check 失败。

### ISSUE THREAD

**Issue by xinsir88** [jumpserver/jumpserver#7218]
```
2021-11-18 02:01:22 Check database connection ...
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/fields/related.py", line 1099, in create_many_to_many_intermediary_model
    'verbose_name': _('%(from)s-%(to)s relationship') % {'from': from_, 'to': to},
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/functional.py", line 176, in __mod__
    return str(self) % rhs
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/__init__.py", line 94, in gettext
    return _trans.gettext(message)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 355, in gettext
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 268, in translation
    _translations[language] = DjangoTranslation(language)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 157, in __init__
    self._add_local_translations()
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 209, in _add_local_translations
    translation = self._new_gnu_trans(localedir)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 181, in _new_gnu_trans
    fallback=use_null_fallback,
  File "/usr/lib64/python3.6/gettext.py", line 523, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/lib64/python3.6/gettext.py", line 254, in __init__
    self._parse(fp)
  File "/usr/lib64/python3.6/gettext.py", line 353, in _parse
    raise OSError(0, 'Bad magic number', filename)
OSError: [Errno 0] Bad magic number: '/opt/jumpserver/apps/locale/zh/LC_MESSAGES/django.mo'
^CTraceback (most recent call last):
  File "./jms", line 161, in <module>
    prepare()
  File "./jms", line 121, in prepare
    check_database_connection()
  File "./jms", line 54, in check_database_connection
    _code = subprocess.call("python manage.py showmigrations users ", shell=True)
  File "/usr/lib64/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib64/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

帮我看一下呗。

**Comment by wojiushixiaobai** [comment]
- 参考 [编译文档](https://docs.jumpserver.org/zh/master/dev/build/#core)

**Comment by xinsir88** [comment]
感谢大神的几十回复，但是我下载了mmdb文件，然后执行python apps/manage.py compilemessages依旧报上面的错

**Comment by xinsir88** [comment]
(py3) [root@Fortress-server jumpserver]# python apps/manage.py compilemessages
Traceback (most recent call last):
  File "apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib64/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/py3/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/py3/lib64/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/users/models/__init__.py", line 5, in <module>
    from .user import *
  File "/opt/jumpserver/apps/users/models/user.py", line 11, in <module>
    from django.contrib.auth.models import AbstractUser
  File "/opt/py3/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 90, in <module>
    class Group(models.Model):
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 161, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/fields/related.py", line 1637, in contribute_to_class
    self.remote_field.through = create_many_to_many_intermediary_model(self, cls)
  File "/opt/py3/lib64/python3.6/site-packages/django/db/models/fields/related.py", line 1099, in create_many_to_many_intermediary_model
    'verbose_name': _('%(from)s-%(to)s relationship') % {'from': from_, 'to': to},
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/functional.py", line 176, in __mod__
    return str(self) % rhs
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/__init__.py", line 94, in gettext
    return _trans.gettext(message)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 355, in gettext
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 268, in translation
    _translations[language] = DjangoTranslation(language)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 157, in __init__
    self._add_local_translations()
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 209, in _add_local_translations
    translation = self._new_gnu_trans(localedir)
  File "/opt/py3/lib64/python3.6/site-packages/django/utils/translation/trans_real.py", line 181, in _new_gnu_trans
    fallback=use_null_fallback,
  File "/usr/lib64/python3.6/gettext.py", line 523, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/lib64/python3.6/gettext.py", line 254, in __init__
    self._parse(fp)
  File "/usr/lib64/python3.6/gettext.py", line 353, in _parse
    raise OSError(0, 'Bad magic number', filename)
OSError: [Errno 0] Bad magic number: '/opt/jumpserver/apps/locale/zh/LC_MESSAGES/django.mo'

**Comment by xinsir88** [comment]
我的操作系统是 CentOS Linux release 8.3.2011不知道跟这个有没有关系

**Comment by xinsir88** [comment]
我把这个文件删掉了，start通过了！！
/opt/jumpserver/apps/locale/zh/LC_MESSAGES/django.mo

**Comment by wojiushixiaobai** [comment]
```
rm -f apps/locale/zh/LC_MESSAGES/django.mo
python apps/manage.py makemessages -a
python apps/manage.py compilemessages
```

**Comment by wojiushixiaobai** [comment]
- Link: jumpserver/docs#b784ac52dd2722cfd169bc2175da5d8662b4481d
