### ISSUE TITLE
生成数据库表结构和初始化数据的时候出错了

### ISSUE THREAD

**Issue by guoshengye** [jumpserver/jumpserver#725]
生成数据库表结构和初始化数据的时候出错了，不知道怎么解决，，，

(py3) [root@host opt]# cd /opt/jumpserver/utils
(py3) [root@host utils]# bash make_migrations.sh
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/opt/py3/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/opt/jumpserver/apps/users/models/__init__.py", line 5, in <module>
    from .group import *
  File "/opt/jumpserver/apps/users/models/group.py", line 11, in <module>
    from common.utils import signer, date_expired_default
  File "/opt/jumpserver/apps/common/utils.py", line 19, in <module>
    import paramiko
  File "/opt/py3/lib/python3.6/site-packages/paramiko/__init__.py", line 31, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/opt/py3/lib/python3.6/site-packages/paramiko/auth_handler.py", line 48, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/opt/py3/lib/python3.6/site-packages/paramiko/ssh_gss.py", line 54, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: module 'gssapi' has no attribute 'GSSException'
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/opt/py3/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/opt/jumpserver/apps/users/models/__init__.py", line 5, in <module>
    from .group import *
  File "/opt/jumpserver/apps/users/models/group.py", line 11, in <module>
    from common.utils import signer, date_expired_default
  File "/opt/jumpserver/apps/common/utils.py", line 19, in <module>
    import paramiko
  File "/opt/py3/lib/python3.6/site-packages/paramiko/__init__.py", line 31, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/opt/py3/lib/python3.6/site-packages/paramiko/transport.py", line 38, in <module>
    from paramiko.auth_handler import AuthHandler
  File "/opt/py3/lib/python3.6/site-packages/paramiko/auth_handler.py", line 48, in <module>
    from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
  File "/opt/py3/lib/python3.6/site-packages/paramiko/ssh_gss.py", line 54, in <module>
    GSS_EXCEPTIONS = (gssapi.GSSException,)
AttributeError: module 'gssapi' has no attribute 'GSSException'
(py3) [root@host utils]#

**Comment by ibuler** [comment]
paramiko版本问题？

**Comment by guoshengye** [comment]
这个我也不他清楚，不知道是哪出错了，就是按照步骤来的，
还有一个疑问，我用mysql5.6的话，还需要加载很多模块吗？我昨天也用mysql5.6试了下，到后面安装的时候提示缺很多东西

**Comment by ibuler** [comment]
和mysql没有关系，请卸载 ansible 和 paramiko染然后重新安装

`$ pip uninstall ansible paramiko`
`$ pip install -r requirements.txt`

**Comment by guoshengye** [comment]
已经好了，多谢

**Comment by chenbaoding2818** [comment]
@guoshengye 请问您是怎么解决的？
