### ISSUE TITLE
[Bug] 使用 RDS 作为数据库，启动失败

### ISSUE THREAD

**Issue by qq516249940** [jumpserver/jumpserver#7365]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.16.3

**浏览器版本**

**Bug 描述**
K8S v1.20.4
阿里云 RDS 5.7   database UTF8MB4
K8S部署失败，初始化msyql数据容器报错，jms-init-db  ，镜像:docker.io/jumpserver/core:v2.16.3

**Bug 重现步骤(有截图更好)**
```bash
Applying auth.0009_alter_user_last_name_max_length... OK

Applying auth.0010_alter_group_name_max_length... OK

Applying auth.0011_update_proxy_permissions... OK

Applying auth.0012_alter_user_first_name_max_length... OK

Applying authentication.0005_delete_loginconfirmsetting... OK

Applying captcha.0001_initial... OK
Traceback (most recent call last):

File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute

return self.cursor.execute(query, args)

File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute

res = self._query(query)

File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query

db.query(q)

File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query

_mysql.connection.query(self, query)

MySQLdb._exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "manage.py", line 28, in <module>

execute_from_command_line(sys.argv)

File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line

utility.execute()

File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute

self.fetch_command(subcommand).run_from_argv(self.argv)

File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv

self.execute(*args, **cmd_options)

File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute

output = self.handle(*args, **options)

File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped

res = handle_func(*args, **kwargs)

File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle

post_migrate_state = executor.migrate(

File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate

state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)

File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards

state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)

File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration

state = migration.apply(state, schema_editor)

File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply

operation.database_forwards(self.app_label, schema_editor, old_state, project_state)

File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 508, in database_forwards

alter_together(

File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 384, in alter_unique_together

self.execute(self._create_unique_sql(model, columns))

File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute

cursor.execute(sql, params)

File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute

return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers

return executor(sql, params, many, context)

File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__

raise dj_exc_value.with_traceback(traceback) from exc_value

File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

return self.cursor.execute(sql, params)

File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute

return self.cursor.execute(query, args)

File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute

res = self._query(query)

File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query

db.query(q)

File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query

_mysql.connection.query(self, query)

django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

2021-12-12 16:17:31 Perform migrate failed, exit

Applying django_cas_ng.0001_initial...
```

**Comment by ibuler** [comment]
不支持 utf8mb4

**Comment by qq516249940** [comment]
> 不支持 utf8mb4

参数设置，将innodb_large_prefix值修改为ON ，解决了，使用的是utf8mb4

**Comment by ibuler** [comment]
我记得我们是不支持 utf8mb4 的

**Comment by ibuler** [comment]
使用后，记得反馈
