### ISSUE TITLE
[Bug]  kubernetes 部署方式下，数据初始化失败

### ISSUE THREAD

**Issue by gotoworld** [jumpserver/jumpserver#7377]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**
chrome 最新版

**Bug 描述**
helm install 时失败，使用外部数据库和redis，网络连接正常，但是提示下图这样的错误

**Bug 重现步骤(有截图更好)**

![image](https://user-images.githubusercontent.com/8605471/145954957-1ee4b29c-3c23-4c21-96a1-a96d6b15bc17.png)

**Comment by gotoworld** [comment]
```
 File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 189, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 82, in wrapped
    saved_locale = translation.get_language()
  File "/usr/local/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 254, in get_language
    return _trans.get_language()
  File "/usr/local/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.8/site-packages/django/conf/__init__.py", line 189, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
2021-12-14 15:38:26 Perform migrate failed, exit
```

**Comment by gotoworld** [comment]
环境信息：

kubernetes v1.19

mysql 5.7

redis 5+

**Comment by ibuler** [comment]
很显然，没有提供配置文件

**Comment by gotoworld** [comment]
helm install 有指定value.yaml 还需要啥配置文件

网上反馈不一定是配置文件的原因，从日志上看是配置的问题，实际应该不是

**Comment by gotoworld** [comment]
> helm install 有指定value.yaml 还需要啥配置文件
> 
> 网上反馈不一定是配置文件的原因，从日志上看是配置的问题，实际应该不是

helm 下的配置，我理解就是values.yaml 文件啊，我有指定特定的value 配置

**Comment by wojiushixiaobai** [comment]
![image](https://user-images.githubusercontent.com/24326988/145975420-93ad4c11-3d8a-439b-ba45-c98c94ac8fd9.png)

**Comment by gotoworld** [comment]
> ![image](https://user-images.githubusercontent.com/24326988/145975420-93ad4c11-3d8a-439b-ba45-c98c94ac8fd9.png)

fixed, Thanks a lot
