### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by honghh2018** [jumpserver/jumpserver#7431]
**JumpServer 版本(v1.5.9以下不再支持)**
2.16.3

**浏览器版本**
google chrome 
版本 96.0.4664.45（正式版本） （64 位）

**Bug 描述**
下载jumpserver, 并创建python的虚拟环境，在虚拟环境中安装了 requirements.txt中的所有模块。
配置好mysql和redis后。
进入虚拟环境中运行：python3 /root/jumpserver/apps/manage.py makemigrations 报错：
OSError: [Errno 0] Bad magic number: /root/jumpserver-2.16.3/apps/locale/zh/LC_MESSAGES/django.mo'
#尝试删除.pyc处理也未能成功

**Bug 重现步骤(有截图更好)**
1. 进入apps
![image](https://user-images.githubusercontent.com/41668708/147240450-057addf0-e213-4990-b364-5497dc175e2d.png)

2.执行 python3 /data/jumpserver/apps/manage.py makemigrations
(jump_virtualenv) [root@localhost apps]# python3 /root/jumpserver/apps/manage.py makemigrations
Traceback (most recent call last):
  File "/root/jumpserver/apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/jumpserver-2.16.3/apps/users/models/__init__.py", line 5, in <module>
    from .user import *
  File "/root/jumpserver-2.16.3/apps/users/models/user.py", line 11, in <module>
    from django.contrib.auth.models import AbstractUser
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 90, in <module>
    class Group(models.Model):
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/db/models/base.py", line 161, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/db/models/fields/related.py", line 1637, in contribute_to_class
    self.remote_field.through = create_many_to_many_intermediary_model(self, cls)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/db/models/fields/related.py", line 1099, in create_many_to_many_intermediary_model
    'verbose_name': _('%(from)s-%(to)s relationship') % {'from': from_, 'to': to},
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/utils/functional.py", line 176, in __mod__
    return str(self) % rhs
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/utils/translation/__init__.py", line 94, in gettext
    return _trans.gettext(message)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 355, in gettext
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 268, in translation
    _translations[language] = DjangoTranslation(language)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 157, in __init__
    self._add_local_translations()
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 209, in _add_local_translations
    translation = self._new_gnu_trans(localedir)
  File "/root/jumpserver_virtualenv/jump_virtualenv/lib/python3.6/site-packages/django/utils/translation/trans_real.py", line 181, in _new_gnu_trans
    fallback=use_null_fallback,
  File "/usr/lib64/python3.6/gettext.py", line 523, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/lib64/python3.6/gettext.py", line 254, in __init__
    self._parse(fp)
  File "/usr/lib64/python3.6/gettext.py", line 353, in _parse
    raise OSError(0, 'Bad magic number', filename)
OSError: [Errno 0] Bad magic number: '/root/jumpserver-2.16.3/apps/locale/zh/LC_MESSAGES/django.mo'
# python版本为3.6

祝好

**Comment by wojiushixiaobai** [comment]
[Core 编译文档](https://docs.jumpserver.org/zh/master/dev/build/#core)

**Comment by seaurching** [comment]
> [Core 编译文档](https://docs.jumpserver.org/zh/master/dev/build/#core)

我按照提供的文档，启动起来也是这个错误。

**Comment by ktrimisu** [comment]
后面解决了么，怎么解决的呢

**Comment by seaurching** [comment]
> 后面解决了么，怎么解决的呢
删除这个文件重新编译
apps/locale/zh/LC_MESSAGES/django.mo
