### ISSUE TITLE
V0.4 跳板机一段时间无操作会卡死

### ISSUE THREAD

**Issue by cnflyne** [jumpserver/jumpserver#744]
[简述你的问题]

##### 使用版本
0.4.0

##### 问题复现步骤
1. 登陆跳板机
2. 去做其他事【中间无交互】
3. 回来再看看，跳板机卡死

##### 具体表现[截图可能会更好些,最好能截全]
客户端卡死后，过一会儿会自动断开，控制台输出如下
```
Opt> packet_write_wait: Connection to 182.61.38.179 port 2222: Broken pipe
```

服务端coco控制台输出如下【日志级别为WARN】：
```log
2017-10-01 00:19:42 [app WARNING] No ssh channel get.
2017-10-01 00:19:58 [app WARNING] No ssh channel get.  ## 注：这儿输出两次是因为我开了两个控制台
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/py3/lib/python3.6/site-packages/jms/tasks.py", line 38, in handler
    self.action(data)
  File "/opt/py3/lib/python3.6/site-packages/jms/service.py", line 353, in send_command_log
    d['output'] = base64.b64encode(d['output']).decode("utf-8")
  File "/usr/local/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/py3/lib/python3.6/site-packages/jms/tasks.py", line 38, in handler
    self.action(data)
  File "/opt/py3/lib/python3.6/site-packages/jms/service.py", line 353, in send_command_log
    d['output'] = base64.b64encode(d['output']).decode("utf-8")
  File "/usr/local/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
```

##### 其他
如上所示

**Comment by cnflyne** [comment]
之前类似问题的issue我也看了，但个人觉得问题并没有真正解决。

**Comment by cnflyne** [comment]
此外，卡死后异常断开，COCO信息中的在线session数不会变少！如下图（当前无ssh连接）：

![image](https://user-images.githubusercontent.com/6804021/31051624-412c03c8-a632-11e7-9034-79ca42972e35.png)

**Comment by cnflyne** [comment]
@ibuler 另外感觉jumpserver有一个问题没解决：

使用sshd登陆服务器时可以配置 sshd_config文件： ClientAliveInterval 60，使sshd服务端每60秒和客户端通信一次，从而保证长时间没操作也能一直保持连接。jumpserver有这样的配置么？

**Comment by hellorocky** [comment]
@cnflyne @ibuler http://docs.paramiko.org/en/2.3/api/transport.html#paramiko.transport.Transport.set_keepalive

**Comment by cnflyne** [comment]
@hellorocky 

Paramiko: A Python implementation of SSHv2.

jumpserver底层是用这玩意儿实现的？还有那个  set_keepalive  是在哪配置哟？

**Comment by hellorocky** [comment]
https://github.com/jumpserver/coco/blob/2bfb25ef3096ab8e29d52fb13fc22a5f387101d5/coco/app.py#L109

**Comment by cnflyne** [comment]
@hellorocky

我把 coco/app.py 那一行改成  gss_kex=True 之后，ssh客户端就连不上coco了（一直卡在那）。。coco的日志也没报错。

希望后面这个参数能做成coco的配置。就像sshd_config那样

**Comment by hellorocky** [comment]
@cnflyne 不知道你想干嘛, 该说的我已经说了

**Comment by cnflyne** [comment]
辛苦，可能你回复的有点多忘记上下文了。

我只是想实现 sshd_config 中  ClientAliveInterval 60 这样的功能，但是按照你给的链接，把 coco/app.py 那一行改成 gss_kex=True 之后，ssh客户端就连不上coco了（一直卡在那）。coco的日志也没报错。

所以希望后面COCO后面也能把这个功能放在 config.py 中配置。而不是像现在这样修改app.py的代码。

**Comment by hellorocky** [comment]
我没有说改成`True`啊
![8c9a3aa9-f2b9-48eb-a31e-f28441a1fd77](https://user-images.githubusercontent.com/7486508/31369848-e3fcedd0-ad4c-11e7-97bf-aa80cb659cf6.png)

**Comment by cnflyne** [comment]
好吧，已经设置了，期待OK。 👍

**Comment by ibuler** [comment]
期间更新过一次 报异常的bug，升级一下 sdk

`pip install --upgrade jumpserver-python-sdk`

#738

**Comment by cnflyne** [comment]
@ibuler 好的，已更新。

**Comment by cnflyne** [comment]
@ibuler 

上面那个命令修复了啥？为啥执行之后，jumpserver coco 挂掉了，而且重启不了了？线上，非常紧急

**Comment by cnflyne** [comment]
好奇心害死猫，大家不要随便升级，特别是线上！！！

**Comment by cnflyne** [comment]
把v0.4安装wiki上的那些命令重新跑了一遍，终于可以启动了。。。吓尿了

**Comment by ibuler** [comment]
fixed
