### ISSUE TITLE
[Question] jumpserver-core v2.17.3 tag直接docker build后启动容器失败

### ISSUE THREAD

**Issue by WeiqiuLiu** [jumpserver/jumpserver#7506]
**请描述您的问题.**
Traceback (most recent call last):
  File "jms", line 20, in <module>
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/users/models/__init__.py", line 5, in <module>
    from .user import *
  File "/opt/jumpserver/apps/users/models/user.py", line 11, in <module>
    from django.contrib.auth.models import AbstractUser
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/models.py", line 90, in <module>
    class Group(models.Model):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 161, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related.py", line 1637, in contribute_to_class
    self.remote_field.through = create_many_to_many_intermediary_model(self, cls)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related.py", line 1099, in create_many_to_many_intermediary_model
    'verbose_name': _('%(from)s-%(to)s relationship') % {'from': from_, 'to': to},
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 176, in __mod__
    return str(self) % rhs
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/usr/local/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 94, in gettext
    return _trans.gettext(message)
  File "/usr/local/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 355, in gettext
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/usr/local/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 268, in translation
    _translations[language] = DjangoTranslation(language)
  File "/usr/local/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 157, in __init__
    self._add_local_translations()
  File "/usr/local/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 209, in _add_local_translations
    translation = self._new_gnu_trans(localedir)
  File "/usr/local/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 177, in _new_gnu_trans
    return gettext_module.translation(
  File "/usr/local/lib/python3.8/gettext.py", line 598, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/local/lib/python3.8/gettext.py", line 261, in __init__
    self._parse(fp)
  File "/usr/local/lib/python3.8/gettext.py", line 393, in _parse
    raise OSError(0, 'Bad magic number', filename)
OSError: [Errno 0] Bad magic number: '/opt/jumpserver/apps/locale/zh/LC_MESSAGES/django.mo'

查到有说需要
`rm -f apps/locale/zh/LC_MESSAGES/django.mo`
`python apps/manage.py compilemessages`

但把这个加到entrypoint.sh里之后，用jmsctl.sh start启动容器报错：
- Start Gunicorn WSGI HTTP Server No such file or directory: '/opt/jumpserver/tmp/gunicorn.pid'

**Comment by ibuler** [comment]
执行一下这个脚本

https://github.com/jumpserver/jumpserver/blob/dev/requirements/lfs_requirements.sh

看看是不是由于ip库导致的，
项目使用 lfs git 插件，有些需要从 lfs 上下载

**Comment by wojiushixiaobai** [comment]
构建可以参考 
https://github.com/jumpserver/Dockerfile/blob/master/core/Dockerfile
https://github.com/jumpserver/jumpserver/blob/master/core/Dockerfile

**Comment by WeiqiuLiu** [comment]
> 执行一下这个脚本
> 
> https://github.com/jumpserver/jumpserver/blob/dev/requirements/lfs_requirements.sh
> 
> 看看是不是由于ip库导致的， 项目使用 lfs git 插件，有些需要从 lfs 上下载

@ibuler 的这个试了一下不行...



> 构建可以参考 https://github.com/jumpserver/Dockerfile/blob/master/core/Dockerfile https://github.com/jumpserver/jumpserver/blob/master/core/Dockerfile

@wojiushixiaobai 的这个看了一下修改了下dockerfile，就可以了。
```
RUN apt -y install redis-server gettext
```

```
RUN cd /opt/jumpserver/apps \
    && sed -i "561i maxmemory-policy allkeys-lru" /etc/redis/redis.conf \
    && /etc/init.d/redis-server start \
    && echo "SECRET_KEY: $(cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 49)" > /opt/jumpserver/config.yml \
    && rm -f /opt/jumpserver/apps/locale/zh/LC_MESSAGES/django.mo \
    && python manage.py compilemessages \
    && rm -f /opt/jumpserver/config.yml \
    && /etc/init.d/redis-server stop
```
