### ISSUE TITLE
[Bug] 使用脚本安装提示[ERROR] 表结构变更失败!

### ISSUE THREAD

**Issue by SANEBEN** [jumpserver/jumpserver#7524]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver-offline-installer-v2.17.3-amd64-85

**浏览器版本**
不涉及浏览器

**Bug 描述**
使用./jmsctl.sh install安装jumpserver报错，MySQL和redis都是使用的外部配置，docker为之前安装好的。运行脚本后提示：
Creating jms_core ... done
2022-01-18 15:04:59 Collect static files
2022-01-18 15:05:00 Collect static files done
2022-01-18 15:05:00 Check database structure change ...
2022-01-18 15:05:00 Migrate model change to database ...
2022-01-18 15:05:03 Perform migrate failed, exit
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, sessions, settings, terminal, tickets, users, xpack
Running migrations:
  Applying assets.0036_auto_20190716_1535...[ERROR] 表结构变更失败!

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/36869748/149889238-196cfdf0-da18-4038-9e0e-064254248b1d.png)
2. 
![image](https://user-images.githubusercontent.com/36869748/149889459-c28e92a5-3036-48f7-a152-d10adc4f71b1.png)

3.

**Comment by ibuler** [comment]
全新安装的吗？ 2.17 版本的报错 debug 信息不太明显了，这个是在变更 命令过滤器时 出错了

**Comment by zyxlcr** [comment]
全新安装 同样的问题

**Comment by lf-zhang** [comment]
同样出现 **表结构变更失败** 问题

错误日志：
```
Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'secret_key_otp' in 'users_user'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./jms", line 84, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 338, in database_forwards
    schema_editor.alter_field(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 571, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 668, in _alter_field
    self.execute(self._rename_field_sql(model._meta.db_table, old_field, new_field, new_type))
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
# 以下设置如果为空系统会自动生成随机字符串填入
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'secret_key_otp' in 'users_user'")
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  Applying users.0002_auto_20171225_1157_squashed_0019_auto_20190304_1459...[ERROR] 表结构变更失败!
```
查看创建出来的 `users_user` 表，没有报错信息中的 `secret_key_otp` 列
@wojiushixiaobai
