### ISSUE TITLE
新注册的用户不能登录其中两台服务器，老用户可以正常登录，同一权限和资产组

### ISSUE THREAD

**Issue by chuengraise** [jumpserver/jumpserver#757]
[简述你的问题]
新创建多个用户，添加到同一组资产组，但是有两台不能登录，其余服务器登录成功。但是这两台新用户不能登录的服务器。老用户在同一权限和资产里登录成功。
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
 0.3.2
##### 问题复现步骤
新注册用户登录报错：
Opt or ID>: 3
Only match Host:  Suser-Auser-Saction-Aaction-Scalculator-Acalculator-2 
Connecting Suser-Auser-Saction-Aaction-Scalculator-Acalculator-2 ...
Traceback (most recent call last):
  File "/opt/jumpserver/connect.py", line 817, in <module>
    main()
  File "/opt/jumpserver/connect.py", line 808, in main
    nav.try_connect()
  File "/opt/jumpserver/connect.py", line 560, in try_connect
    ssh_tty.connect()
  File "/opt/jumpserver/connect.py", line 415, in connect
    self.posix_shell()
  File "/opt/jumpserver/connect.py", line 297, in posix_shell
    log_file_f, log_time_f, log = self.get_log()
  File "/opt/jumpserver/connect.py", line 199, in get_log
    log.save()
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 898, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
_mysql_exceptions.Warning: Data truncated for column 'log_path' at row 1

**Comment by ibuler** [comment]
问题已解决，hostname + username 超过了100个字符，导致log_path在数据库中报错
