### ISSUE TITLE
[Bug] 上传ed25519 SSH密钥失败

### ISSUE THREAD

**Issue by paxnil** [jumpserver/jumpserver#7588]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.18.1

**浏览器版本**
Microsoft Edge 98.0.1108.43 

**Bug 描述**
新建系统用户时，上传ed25519 SSH密钥失败，提示“密钥不合法或密钥密码错误”

**Bug 重现步骤(有截图更好)**
1.  新建系统用户
2. 上传一个ed25519的密钥
3. 保存

**日志**
```
2022-02-10 09:08:31 [exc_handlers ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework_bulk/drf3/mixins.py", line 29, in create
    return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'private_key': [ErrorDetail(string='密钥不合法或密钥密码错误', code='invalid')]}
```

看了一下代码，大概是这里没处理这个类型？
https://github.com/jumpserver/jumpserver/blob/67a49dc5e9b0089258459c60e8c9960f1b777579/apps/common/utils/encode.py#L72-L89

**Comment by jym503558564** [comment]
目前不支持

**Comment by ibuler** [comment]
paramiko 库不支持的，我们也暂不支持
