### ISSUE TITLE
添加用户，发送邮件错误

### ISSUE THREAD

**Issue by wocswang** [jumpserver/jumpserver#767]
[2017-10-18 16:00:53,289: ERROR/ForkPoolWorker-2] Task common.tasks.send_mail_async[e871555b-3e0e-4234-8b45-863b79038ab0] raised unexpected: gaierror(-2, 'Name or service not known')
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/common/tasks.py", line 29, in send_mail_async
    send_mail(*args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/opt/py3/lib/python3.6/site-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/py3/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "/opt/py3/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 64, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/smtplib.py", line 306, in _get_socket
    self.source_address)
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

在本地用命令mail发送邮件可以,在config.py文件中的配置是这样的

    EMAIL_HOST = 'stmp.sina.com'
    EMAIL_PORT = 25
    EMAIL_ENABLE = 1
    EMAIL_HOST_USER = 'wocswang@sina.com'
    EMAIL_HOST_PASSWORD = '**********'
    EMAIL_USE_SSL = False
    EMAIL_USE_TLS = False
    EMAIL_SUBJECT_PREFIX = '[Jumpserver] '
    SITE_URL = 'http://10.10.16.244:8080'

**Comment by hellorocky** [comment]
1. 是在阿里云上吗?
2. 从服务器上telnet smtp.sina.com 25看看能不能通
3. https://github.com/hellorocky/LearnByCoding/blob/master/python/mail/send_mail.py 使用这个脚本在服务器上发送邮件试试看看能不能
4. 你的日志中的问题明明是网络的问题

**Comment by wocswang** [comment]
@hellorocky 我用你这个脚本了但是No module named 'email.mime'; 'email' is not a package  安装这个也安装不上  对了还有一个问题就是我添加主机后再coco中可以显示已有的机器，但是在luna中不显示

**Comment by wocswang** [comment]
@hellorocky 我在命令行中用mail命令可以发送邮件

**Comment by hellorocky** [comment]
另外, 有时间可以多看看python, 感觉你的基础知识需要补充

**Comment by wocswang** [comment]
import smtplib;
from email.mime.text import MIMEText

def send_email(host,username,passwd,send_to,subject,content):
    msg = MIMEText( content.encode('utf8'), _subtype = 'html', _charset = 'utf8')
    msg['From'] = username
    msg['Subject'] = u'%s' % subject
    msg['To'] = ",".join(send_to)

    try:
        s = smtplib.SMTP_SSL(host,465)
        s.login(username, passwd )
        s.sendmail(username, send_to,msg.as_string())
        s.close()
    except Exception as e:
        print ('Exception: send email failed'), e

if __name__ == '__main__':
    host = 'smtp.sina.com'
    username = 'wocswang@sina.com'
   passwd = '******'
    to_list = ['salt_stack@126.com']
    subject = "邮件主题"
    content = '使用Python发送邮件'
    send_email(host,username,passwd,to_list,subject,content)
可以发送没有问题

**Comment by wocswang** [comment]
@hellorocky 
import smtplib;
from email.mime.text import MIMEText

def send_email(host,username,passwd,send_to,subject,content):
msg = MIMEText( content.encode('utf8'), _subtype = 'html', _charset = 'utf8')
msg['From'] = username
msg['Subject'] = u'%s' % subject
msg['To'] = ",".join(send_to)

try:
    s = smtplib.SMTP_SSL(host,465)
    s.login(username, passwd )
    s.sendmail(username, send_to,msg.as_string())
    s.close()
except Exception as e:
    print ('Exception: send email failed'), e
if name == 'main':
host = 'smtp.sina.com'
username = 'wocswang@sina.com'
passwd = '******'
to_list = ['salt_stack@126.com']
subject = "邮件主题"
content = '使用Python发送邮件'
send_email(host,username,passwd,to_list,subject,content)
可以发送没有问题
