### ISSUE TITLE
配置ldap，invalid literal for int() with base 10: '0.05'

### ISSUE THREAD

**Issue by htmz** [jumpserver/jumpserver#7680]
JumpServer 版本(v1.5.9以下不再支持)
Version v2.17.3-101 GPLv2.

浏览器版本
Google chrome 版本 97.0.4692.71（正式版本） (x86_64)

**Bug 描述**
配置ldap，页面报错

**Bug 重现步骤(有截图更好)**
1.  截图
![image](https://user-images.githubusercontent.com/27039243/155248039-2f7f68e8-3f8f-4f04-b520-21335783b479.png)

2. 日志报错
```python
2022-02-23 09:32:22 [log ERROR] Internal Server Error: /api/v1/settings/setting/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 252, in get
    return self.retrieve(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/fields.py", line 963, in to_representation
    return int(value)
ValueError: invalid literal for int() with base 10: '0.05'
```

**Comment by htmz** [comment]
jumpsever版本写错了 应该是2.19.1

**Comment by jym503558564** [comment]
社区版本吗？

**Comment by htmz** [comment]
> 
社区版本 升级后报的错

**Comment by lawrence191** [comment]
问题解决：
如果是按照官方文档：https://docs.jumpserver.org/zh/master/admin-guide/env/，其中参数：
AUTH_LDAP_SYNC_INTERVAL=None       # 同步间隔（单位：时）（优先）
AUTH_LDAP_SYNC_CRONTAB=None        # 同步 Crontab 表达式
且不改的话，会报这个错。对应到了这个错误：invalid literal for int() with base 10: 'None'。
建议：
官方针对这参数做个说明，应该是填写什么类型的。其他的参数，同样的指出应该填写什么样的参数。
