### ISSUE TITLE
[Question] SAML2疑问

### ISSUE THREAD

**Issue by LukeLiaoNote** [jumpserver/jumpserver#7686]
想咨询一下jumpserver是否兼容google saml.兼容的话jumpserver 的实体id跟acs的url是哪些呢？

**Comment by wojiushixiaobai** [comment]
[SAML2 认证](https://docs.jumpserver.org/zh/master/admin-guide/authentication/saml2/)
### 获取 SP metadata 信息
- 访问 http://your_jms_url/core/auth/saml2/metadata/ 保存 metadata 内容(可保存成文件，到 idp 中直接导入)

**Comment by LiaoXinNode** [comment]
但是google控制台需要手动输入acs url以及实体id url，不能导入，那么url应该在metadata中的哪行呢？

**Comment by LiaoXinNode** [comment]
目前情况是saml登陆时google验证通过跳转到jumpserver时一直死循环跳转到jumserver登陆页，是不是跟google的saml兼容性有问题呢

**Comment by wojiushixiaobai** [comment]
日志发出来看看

**Comment by LiaoXinNode** [comment]
CSRF验证失败. 请求被中断.

您看到此消息是由于该站点在提交表单时需要一个CSRF cookie。此项是出于安全考虑，以确保您的浏览器没有被第三方劫持。

如果您已将浏览器配置为禁用cookie，请重新启用它们，至少针对此站点或“同源”请求。

**Comment by LiaoXinNode** [comment]
2022-02-28 17:47:22 [ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

**Comment by LiaoXinNode** [comment]
ldp需要提供sp的acs地址以及实体id地址。我在官方文档没有看到有详细的记录。acs:/core/auth/saml2/callback/
实体ID:core/auth/saml2/login/ 不知道对不对

**Comment by wojiushixiaobai** [comment]
导出的 metadata 里面有此信息，请仔细看
