### ISSUE TITLE
[Bug] installer 安装报错：表结构变更失败

### ISSUE THREAD

**Issue by lf-zhang** [jumpserver/jumpserver#7692]
**JumpServer 版本(v1.5.9以下不再支持)**
版本是 v2.19.1，新建的外置数据库

**浏览器版本**
不涉及浏览器

**Bug 描述**
初始化数据库步骤出现 **表结构变更失败** 问题

**Bug 重现步骤(有截图更好)**

错误日志：
![image](https://user-images.githubusercontent.com/39855929/155466561-023bac4a-ca18-43b6-84a3-60c4399b9eb4.png)
![image](https://user-images.githubusercontent.com/39855929/155466618-2f39cd65-49e2-48c6-a3f3-62b12db144a2.png)

```
Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'secret_key_otp' in 'users_user'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./jms", line 84, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 338, in database_forwards
    schema_editor.alter_field(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 571, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 668, in _alter_field
    self.execute(self._rename_field_sql(model._meta.db_table, old_field, new_field, new_type))
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
# 以下设置如果为空系统会自动生成随机字符串填入
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'secret_key_otp' in 'users_user'")
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, sessions, settings, terminal, tickets, users
Running migrations:
  Applying users.0002_auto_20171225_1157_squashed_0019_auto_20190304_1459...[ERROR] 表结构变更失败!
```
查看创建出来的 `users_user` 表，没有报错信息中的 `secret_key_otp` 列
@wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
删库重新安装，常见于第一次初始化被异常结束导致

**Comment by lf-zhang** [comment]
> 删库重新安装，常见于第一次初始化被异常结束导致

错误原因变成新的了，还是需要删库重新安装么？
操作是：删除旧库，建新库，重新执行 install
![image](https://user-images.githubusercontent.com/39855929/155468876-545ce2cb-10f8-4f51-bdff-ccc0cd4f0d7d.png)

**Comment by wojiushixiaobai** [comment]
用默认自带的数据库看看是否同样有此问题

**Comment by lf-zhang** [comment]
> 用默认自带的数据库看看是否同样有此问题

默认的没有问题

**Comment by lf-zhang** [comment]
> 用默认自带的数据库看看是否同样有此问题

默认的可以连上，外置的不行

**Comment by lf-zhang** [comment]
> 用默认自带的数据库看看是否同样有此问题

默认的可以连上，外置的不行

**Comment by wojiushixiaobai** [comment]
创建数据库的字符集是啥

**Comment by lf-zhang** [comment]
> 创建数据库的字符集是啥

utf8mb4

**Comment by wojiushixiaobai** [comment]
去掉 mb4 试试
```mysql
mysql> show create database jumpserver;
+------------+---------------------------------------------------------------------+
| Database   | Create Database                                                     |
+------------+---------------------------------------------------------------------+
| jumpserver | CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8 */ |
+------------+---------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by lf-zhang** [comment]
> 去掉 mb4 试试
> 
> ```sql
> mysql> show create database jumpserver;
> +------------+---------------------------------------------------------------------+
> | Database   | Create Database                                                     |
> +------------+---------------------------------------------------------------------+
> | jumpserver | CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8 */ |
> +------------+---------------------------------------------------------------------+
> 1 row in set (0.00 sec)
> ```

我这边现在限制创建mb4格式，mb4包含utf8的呀，不可以使用这个格式吗

**Comment by lf-zhang** [comment]
> 去掉 mb4 试试
> 
> ```sql
> mysql> show create database jumpserver;
> +------------+---------------------------------------------------------------------+
> | Database   | Create Database                                                     |
> +------------+---------------------------------------------------------------------+
> | jumpserver | CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8 */ |
> +------------+---------------------------------------------------------------------+
> 1 row in set (0.00 sec)
> ```

为什么utf8是no migrations to apply，utf8mb4就需要迁移呢？

**Comment by lf-zhang** [comment]
> 去掉 mb4 试试
> 
> ```sql
> mysql> show create database jumpserver;
> +------------+---------------------------------------------------------------------+
> | Database   | Create Database                                                     |
> +------------+---------------------------------------------------------------------+
> | jumpserver | CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8 */ |
> +------------+---------------------------------------------------------------------+
> 1 row in set (0.00 sec)
> ```

目前是不是没有版本支持 utf8mb4 格式呢，新建数据库是 utf8mb4 字符集

**Comment by lf-zhang** [comment]
> django 默认不支持 utf8mb4，需要修改代码。我们看看后续是否可以优化判断

我这边可以增加配置支持吗，比如修改settings文件这些

**Comment by wojiushixiaobai** [comment]
可以自己修改源代码后打包

**Comment by lf-zhang** [comment]
> django 默认不支持 utf8mb4，需要修改代码。我们看看后续是否可以优化判断

我这边新建django项目测试了下，migrate是支持utf8mb4的呀，这是什么问题呢？

**Comment by wojiushixiaobai** [comment]
请注意版本，上面已经进行相关的回复，如果有需要请自行修改代码。
