### ISSUE TITLE
登录coco时候刷新资产卡住

### ISSUE THREAD

**Issue by zsjohny** [jumpserver/jumpserver#771]
登录coco时候刷新资产卡住

##### 使用版本
[0.4.0]

##### 问题复现步骤
登录coco时候刷新资产卡住

##### 具体表现

![image](https://user-images.githubusercontent.com/8543865/31757718-c5d1c0b8-b46f-11e7-8527-91e9089b4451.png)

DEBUG:/opt/coco/coco/interactive.py:End get my asset groups
2017-10-19 06:40:49 [interactive DEBUG] End get my asset groups
Exception in thread Thread-2069:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/app.py", line 135, in process_request
    InteractiveServer(self, ssh_interface.user_service, client_channel).run()
  File "/opt/coco/coco/interactive.py", line 293, in run
    self.dispatch()
  File "/opt/coco/coco/interactive.py", line 112, in dispatch
    option = self.get_input()
  File "/opt/coco/coco/interactive.py", line 69, in get_input
    r, w, x = select.select([self.client_channel], [], [])
ValueError: filedescriptor out of range in select()

##### 其他

[注:] 完成后请关闭 issue

**Comment by zsjohny** [comment]
@ibuler

**Comment by choldrim** [comment]
https://github.com/jumpserver/coco/issues/18 这个PR已经把select库替换掉了，@ibuler coco重构前要不要先把这个PR合并了？

**Comment by ibuler** [comment]
已merge了，Pull一下查看是否解决
