### ISSUE TITLE
[Question] 从v2.19.1升级至v2.20.2时表结构变更失败

### ISSUE THREAD

**Issue by yolylight** [jumpserver/jumpserver#8037]
从v2.19.1版本升级至v2.20.2时提示表结构变更失败，无法升级
升级记录如下
2022-04-10 16:52:28 Collect static files
2022-04-10 16:52:28 Collect static files done
2022-04-10 16:52:28 Check database structure change ...
2022-04-10 16:52:28 Migrate model change to database ...
2022-04-10 16:52:35 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./jms", line 84, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 121, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/jumpserver/apps/rbac/migrations/0004_auto_20211201_1901.py", line 33, in migrate_org_role_binding
    user_id=member.user.id,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 187, in __get__
    rel_obj = self.get_object(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 154, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
__fake__.User.DoesNotExist: User matching query does not exist.
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying acls.0003_auto_20211130_1037... OK
  Applying applications.0017_auto_20220217_2135... OK
  Applying applications.0018_auto_20220223_1539... OK
  Applying applications.0019_auto_20220310_1853... OK
  Applying applications.0020_auto_20220316_2028... OK
  Applying assets.0086_auto_20220217_2135... OK
  Applying assets.0087_auto_20220223_1539... OK
  Applying assets.0088_auto_20220303_1612... OK
  Applying assets.0089_auto_20220310_0616... OK
  Applying audits.0013_auto_20211130_1037... OK
  Applying authentication.0007_connectiontoken... OK
  Applying authentication.0008_superconnectiontoken... OK
  Applying authentication.0009_auto_20220310_0616... OK
  Applying django_celery_beat.0013_auto_20200609_0727... OK
  Applying django_celery_beat.0014_remove_clockedschedule_enabled... OK
  Applying django_celery_beat.0015_edit_solarschedule_events_choices... OK
  Applying ops.0021_auto_20211130_1037... OK
  Applying rbac.0001_initial... OK
  Applying rbac.0002_auto_20210929_1409... OK
  Applying rbac.0003_auto_20211130_1037...Update builtin Role: SystemAdmin - True
Update builtin Role: SystemAuditor - True
Update builtin Role: SystemComponent - True
Update builtin Role: User - True
Update builtin Role: OrgAdmin - True
Update builtin Role: OrgAuditor - True
Update builtin Role: OrgUser - True
 OK
  Applying rbac.0004_auto_20211201_1901...[ERROR] 表结构变更失败!

**Comment by luomoxu** [comment]
这类表变更失败的问题已经是影响升级最常见的问题了 感觉每几个小版本就要来一次

**Comment by yolylight** [comment]
官方是否能发个排查指南 有个排查方向就行

**Comment by ibuler** [comment]
没道理会失败啊

**Comment by ibuler** [comment]
表结构都经过测试的，这个报错应该是没查出用户来

**Comment by yolylight** [comment]
可以通过哪些日志排查？或者有保留资产重新部署的方法也行

**Comment by yolylight** [comment]
暴力解决了 删除所有用户只留admin 就可以成功升级了
