### ISSUE TITLE
Authentication credentials were not provided

### ISSUE THREAD

**Issue by artemus717** [jumpserver/jumpserver#8070]
Version:
2.20.2

Log:
```
127.0.0.1 [15/Apr/2022:17:31:07 +0800] 0.152461s "GET /core/auth/saml2/login/ HTTP/1.0" 302 0
127.0.0.1 [15/Apr/2022:17:31:09 +0800] 0.141655s "POST /core/auth/saml2/callback/ HTTP/1.0" 302 0
127.0.0.1 [15/Apr/2022:17:31:12 +0800] 0.008357s "GET /api/v1/settings/public/ HTTP/1.0" 200 1188
127.0.0.1 [15/Apr/2022:17:31:14 +0800] 0.008212s "GET /api/v1/settings/public/ HTTP/1.0" 200 1188
2022-04-15 17:31:14 [exc_handlers ERROR] 
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
127.0.0.1 [15/Apr/2022:17:31:14 +0800] 0.007014s "GET /api/v1/users/profile/ HTTP/1.0" 401 85
127.0.0.1 [15/Apr/2022:17:31:15 +0800] 0.007278s "GET /core/auth/login/ HTTP/1.0" 302 0
127.0.0.1 [15/Apr/2022:17:31:15 +0800] 0.007060s "GET /core/auth/login/ HTTP/1.0" 302 0
127.0.0.1 [15/Apr/2022:17:31:15 +0800] 0.009773s "GET /core/common/flash-message/?code=u52yUao6jkTQ HTTP/1.0" 200 3986
127.0.0.1 [15/Apr/2022:17:31:16 +0800] 0.011855s "GET /core/jsi18n/ HTTP/1.0" 200 3187
127.0.0.1 [15/Apr/2022:17:31:24 +0800] 0.198307s "GET /core/auth/saml2/login/?next=/&amp; HTTP/1.0" 302 0
127.0.0.1 [15/Apr/2022:17:31:25 +0800] 0.115931s "POST /core/auth/saml2/callback/ HTTP/1.0" 302 0
127.0.0.1 [15/Apr/2022:17:31:28 +0800] 0.007279s "GET /api/v1/settings/public/ HTTP/1.0" 200 1188
127.0.0.1 [15/Apr/2022:17:31:30 +0800] 0.016518s "POST /api/v1/terminal/terminals/status/ HTTP/1.1" 201 2
127.0.0.1 [15/Apr/2022:17:31:30 +0800] 0.014364s "GET /api/v1/terminal/terminals/config/ HTTP/1.1" 200 2308
127.0.0.1 [15/Apr/2022:17:31:30 +0800] 0.015118s "POST /api/v1/terminal/terminals/status/ HTTP/1.1" 201 2
127.0.0.1 [15/Apr/2022:17:31:32 +0800] 0.007069s "GET /api/v1/settings/public/ HTTP/1.0" 200 1188
/opt/py3/lib/python3.8/site-packages/azure/storage/blob/_upload_chunking.py:403: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if n is 0 or self._buffer.closed:
/opt/py3/lib/python3.8/site-packages/azure/storage/blob/baseblobservice.py:1008: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
/opt/py3/lib/python3.8/site-packages/azure/storage/blob/baseblobservice.py:2607: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lease_duration is not -1 and \
2022-04-15 17:31:32 [exc_handlers ERROR] 
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
127.0.0.1 [15/Apr/2022:17:31:32 +0800] 0.008145s "GET /api/v1/users/profile/ HTTP/1.0" 401 85
127.0.0.1 [15/Apr/2022:17:31:32 +0800] 0.006655s "GET /core/auth/login/ HTTP/1.0" 302 0
127.0.0.1 [15/Apr/2022:17:31:32 +0800] 0.007523s "GET /core/auth/login/ HTTP/1.0" 302 0
127.0.0.1 [15/Apr/2022:17:31:33 +0800] 0.024854s "GET /core/common/flash-message/?code=YRkGIWvG2Nkm HTTP/1.0" 200 3986
127.0.0.1 [15/Apr/2022:17:31:34 +0800] 0.008640s "GET /core/jsi18n/ HTTP/1.0" 200 3187
```

SAML Request:
```xml
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID="ONELOGIN_ef7efb0194a41a323368a807a8279e44ffe47c1a"
                    Version="2.0"
                    ProviderName="onlineopsjumpserver"
                    IssueInstant="2022-04-15T09:15:12Z"
                    Destination="https://stsus.xxxx.com/adfs/ls/"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    AssertionConsumerServiceURL="https://jumpserver.onlineops.xxxx.com/core/auth/saml2/callback/"
                    AttributeConsumingServiceIndex="1"
                    >
    <saml:Issuer>https://jumpserver.onlineops.xxxx.com/core/auth/saml2/login/</saml:Issuer>
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```
SAML Response:
```xml
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                ID="_19378c8f-7040-46ba-852d-e3f24d7d4d69"
                Version="2.0"
                IssueInstant="2022-04-15T09:15:12.725Z"
                Destination="https://jumpserver.onlineops.xxxx.com/core/auth/saml2/callback/"
                Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
                InResponseTo="ONELOGIN_ef7efb0194a41a323368a807a8279e44ffe47c1a"
                >
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://stsus.xxxx.com/adfs/services/trust</Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion"
               ID="_33b6713a-a3c6-448c-bea8-bec36bdf720f"
               IssueInstant="2022-04-15T09:15:12.725Z"
               Version="2.0"
               >
        <Issuer>http://stsus.xxxx.com/adfs/services/trust</Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
                <ds:Reference URI="#_33b6713a-a3c6-448c-bea8-bec36bdf720f">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                    <ds:DigestValue>HV48ZNN34bKvcem/pfbwdiHfWJ0Uaiqqea4O9jSFfks=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>Hi/JIFFjeEBINpPMZSL7CqRwwlosuZtwW+lBQxheEKbpxAgI9gW6gtKBbiqoMiBXNiM/zcWs8VyZaMVn+qmbOToVHqfz0dvp3+Hqyya7rHujGqgK53yadEalCiSoyjGPEcQgyx4A0Syg/MX9kcqcLz89zAQy4p3Fm81PP/a4d7KDv+MDhv3RfLaARqCtdfMUMO+2gXtJMgv2NHghzaEW85UiTffmjyrhfc94mJFhhylVeGxElWgN+pQVrS7lPsMSjDKxXi4zMqDrAnYN/obRX1rsnLJ+V6pgip1YMJBCY9h8FLBeDoUSBxO+VHIMwTREbOpoS5eYySZy49aRhH+X/g==</ds:SignatureValue>
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>MIIC3DCCAcSgAwIBAgIQRccunVQqvIFFChF7vsdI0jANBgkqhkiG9w0BAQsFADAqMSgwJgYDVQQDEx9BREZTIFNpZ25pbmcgLSBzdHN1cy5sZW5vdm8uY29tMB4XDTE4MDIxMzAzNDUzNVoXDTI4MDIxMTAzNDUzNVowKjEoMCYGA1UEAxMfQURGUyBTaWduaW5nIC0gc3RzdXMubGVub3ZvLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANVlDDYDOMITUVy/b0M4xgKMXAs9f+bG5x/RZLaVLiPIIq+Dxp4mflkuUPwF3Umx/ttUQbpMnWgJv2MqnRW8GERPFIJ6ePoSNStCVsteDEhgcJJWRyGbOjOyIdFLfGlbfAMPxHJAAMfqCLXBEIJsTFO6uAKX1EAocv/cUpod+ZKn70+IFLq4xfq1sp0TaWyU/be87lDaE0Oe+9+4hxOA3m+G3QB6JqMcDUZz/gpWueplEXv5JHDmR7gu13WT8eFVv6F8RsQzClO4ETrFyzgzCLW199uEQ+My50s+5Qs1zcas+xs3l3nBn66/fKNtsihu8bNabuN4780mTFJB8E9NbjcCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAWm/tZ/dEzXKrPWhSnasQpTgeqhQfzrKAonpmW+HkOCJlRejF15aa8aFLC2pI5t0z70YDsNcKMMmpWVdb+m3hOMU0jkPAZVra4hXztDXhm9R6gZWorQCLVrhvvMuaY0F9vouLD4oRXGNOGNIF3ocfMGd87JDZi0FlPxgweWj4Zn6qDw6ZqQNKWxwfVvGLi3C3ph/W8y6QqOriknWaskXhJuqORF0Bo1jQwbqrhsPcHqi4ukdRzZ0bELjxb6XCYRTeGGWYKHiJvtuw2e6zC1OCriMz99kCGoe/P0/amh8M916BPojU8cVFmEnEWNzNvImMtidcfcSbMbR25XUHGp62aA==</ds:X509Certificate>
                </ds:X509Data>
            </KeyInfo>
        </ds:Signature>
        <Subject>
            <NameID>lill25</NameID>
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData InResponseTo="ONELOGIN_ef7efb0194a41a323368a807a8279e44ffe47c1a"
                                         NotOnOrAfter="2022-04-15T09:20:12.725Z"
                                         Recipient="https://jumpserver.onlineops.xxxx.com/core/auth/saml2/callback/"
                                         />
            </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2022-04-15T09:15:12.725Z"
                    NotOnOrAfter="2022-04-15T10:15:12.725Z"
                    >
            <AudienceRestriction>
                <Audience>https://jumpserver.onlineops.xxxx.com/core/auth/saml2/login/</Audience>
            </AudienceRestriction>
        </Conditions>
        <AttributeStatement>
            <Attribute Name="itcode">
                <AttributeValue>lill25</AttributeValue>
            </Attribute>
            <Attribute Name="email">
                <AttributeValue>lill25@xxxx.com</AttributeValue>
            </Attribute>
            <Attribute Name="firstname">
                <AttributeValue>Linlin</AttributeValue>
            </Attribute>
            <Attribute Name="lastname">
                <AttributeValue>Li</AttributeValue>
            </Attribute>
            <Attribute Name="displayname">
                <AttributeValue>Linlin LL25 Li</AttributeValue>
            </Attribute>
        </AttributeStatement>
        <AuthnStatement AuthnInstant="2022-04-15T09:15:04.788Z"
                        SessionIndex="_33b6713a-a3c6-448c-bea8-bec36bdf720f"
                        >
            <AuthnContext>
                <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</AuthnContextClassRef>
            </AuthnContext>
        </AuthnStatement>
    </Assertion>
</samlp:Response>
```

**Comment by f2c-jiangweidong** [comment]
日志界别调成INFO，查看一下其他日志输出

**Comment by artemus717** [comment]
I changed to DEBUG ,and got 
`127.0.0.1 [18/Apr/2022:09:56:41 +0800] 0.009058s "GET /core/common/flash-message/?code=LOG4mGdz4IcN HTTP/1.0" 200 3986
127.0.0.1 [18/Apr/2022:09:56:41 +0800] 0.007955s "GET /core/jsi18n/ HTTP/1.0" 200 3187
2022-04-18 09:56:50 [views DEBUG] Process SAML GET requests: Start
2022-04-18 09:56:50 [views DEBUG] Start getting IDP configuration
2022-04-18 09:56:50 [views DEBUG] IDP settings obtained successfully
2022-04-18 09:56:50 [views DEBUG] Process SAML GET requests: Redirect login url
127.0.0.1 [18/Apr/2022:09:56:50 +0800] 0.103679s "GET /core/auth/saml2/login/?next=/&amp; HTTP/1.0" 302 0
2022-04-18 09:56:51 [views DEBUG] Start getting IDP configuration
2022-04-18 09:56:51 [views DEBUG] IDP settings obtained successfully
2022-04-18 09:56:51 [views DEBUG] Process SAML2 POST requests: Process saml response
2022-04-18 09:56:51 [views DEBUG] Process SAML2 POST requests: Process authenticate
2022-04-18 09:56:51 [backends DEBUG] Process authenticate [SAML2AuthCodeBackend]: Start
2022-04-18 09:56:51 [backends DEBUG] Process authenticate [SAML2AuthCodeBackend]: saml data, {'email': 'lill25@lenovo.com'}
2022-04-18 09:56:51 [backends DEBUG] Process authenticate [SAML2AuthCodeBackend]: username is missing
2022-04-18 09:56:51 [views DEBUG] Process SAML2 POST requests: Redirect
127.0.0.1 [18/Apr/2022:09:56:51 +0800] 0.115585s "POST /core/auth/saml2/callback/ HTTP/1.0" 302 0
127.0.0.1 [18/Apr/2022:09:56:52 +0800] 0.007722s "GET /api/v1/settings/public/ HTTP/1.0" 200 1188
127.0.0.1 [18/Apr/2022:09:56:52 +0800] 0.008323s "GET /api/v1/settings/public/ HTTP/1.0" 200 1188
2022-04-18 09:56:52 [exc_handlers ERROR] 
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(`


How can I map itcode in response to username ?

**Comment by f2c-jiangweidong** [comment]
右上角设置里 -> 认证设置 -> SAML2 -> 其他中 -> 用户属性设置 -> { "Saml2UsernameField":  "username"}

**Comment by artemus717** [comment]
Is this correct ? It still response username not found
`{
  "Saml2UsernameField": "itcode",
  "email": "email"
}
or
{
  "Saml2UsernameField": "username",
  "email": "email"
}
`

**Comment by f2c-jiangweidong** [comment]
You should replace itcode with username

**Comment by f2c-jiangweidong** [comment]
Let's optimize it later

**Comment by artemus717** [comment]
`{
  "Saml2UsernameField": "username",
  "email": "email"
}`

This also got username is missing error.

**Comment by f2c-jiangweidong** [comment]
At present, you can replace 
`<Attribute Name="itcode"><AttributeValue>lill25</AttributeValue></Attribute>`
 with 
`<Attribute Name="username"> <AttributeValue>lill25</AttributeValue></Attribute>`
 in the response, and we will optimize it later

**Comment by artemus717** [comment]
I will try to touch ADFS set itcode as username.

**Comment by artemus717** [comment]
This works. Thanks a lot!
<Attribute Name="username"> <AttributeValue>xxxx</AttributeValue></Attribute>

I edit  /opt/py3/lib/python3.8/site-packages/onelogin/saml2/auth.py config set_nameid_policy=False.
With set_nameid_policy=True , Jumpserver send nameid policy but got InvaildNameIDPolicy result.

**Comment by ibuler** [comment]
修复完成，那关闭了，另外可以关注这个 pr 
https://github.com/jumpserver/jumpserver/pull/8129
