### ISSUE TITLE
[Question] 创建资产提示“ Request failed with status code 500”

### ISSUE THREAD

**Issue by OldPeel** [jumpserver/jumpserver#8074]
**请描述您的问题.**
创建资产提示“ Request failed with status code 500”
![image](https://user-images.githubusercontent.com/86137842/163747864-7b153bdd-0a6d-43d3-8eda-210d1a2a4695.png)

**日志信息如下：**
jumpserver.log
2022-04-18 11:04:46 [log ERROR] Internal Server Error: /api/v1/assets/assets/
Traceback (most recent call last):
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/app/python3/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/app/python3/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/app/python3/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xE8\\x8A\\x82\\xE7\\x82\\xB9...' for column 'resource_type' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app/python3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/app/python3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app/python3/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/app/python3/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/app/python3/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/app/python3/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/app/python3/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/app/python3/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/app/python3/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/app/python3/lib/python3.8/site-packages/rest_framework_bulk/drf3/mixins.py", line 29, in create
    return super(BulkCreateModelMixin, self).create(request, *args, **kwargs)
  File "/opt/app/python3/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/opt/app/jumpserver/apps/assets/api/asset.py", line 74, in perform_create
    assets = serializer.save()
  File "/opt/app/python3/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/opt/app/jumpserver/apps/assets/serializers/asset.py", line 157, in create
    instance = super().create(validated_data)
  File "/opt/app/python3/lib/python3.8/site-packages/rest_framework/serializers.py", line 964, in create
    field.set(value)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1015, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 950, in add
    self._add_items(
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1159, in _add_items
    signals.m2m_changed.send(
  File "/opt/app/python3/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/opt/app/python3/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/app/jumpserver/apps/audits/signal_handlers.py", line 213, in on_m2m_changed
    OperateLog.objects.bulk_create(to_create)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/models/query.py", line 494, in bulk_create
    returned_columns = self._batched_insert(
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/models/query.py", line 1277, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/app/python3/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/app/python3/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/app/python3/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/app/python3/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xE8\\x8A\\x82\\xE7\\x82\\xB9...' for column 'resource_type' at row 1")
2022-04-18 11:04:48 [permissions DEBUG] View require perms: {'terminal.add_status'}, result: True
2022-04-18 11:04:57 [permissions DEBUG] View require perms: ['terminal.view_terminalconfig'], result: True
2022-04-18 11:05:08 [permissions DEBUG] View require perms: {'terminal.add_status'}, result: True
2022-04-18 11:05:18 [permissions DEBUG] View require perms: {'terminal.add_status'}, result: True

nginx访问日志：
172.17.0.1 - - [18/Apr/2022:11:04:46 +0800] "POST /api/v1/assets/assets/ HTTP/1.1" 500 329065 "http://192.168.116.200/ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"
172.17.0.1 - - [18/Apr/2022:11:06:43 +0800] "POST /api/v1/assets/assets/ HTTP/1.1" 500 329065 "http://192.168.116.200/ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" "-"

nginx错误日志：
2022/04/18 11:04:00 [warn] 2617#2617: *2530 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/8/05/0000000058 while reading upstream, client: 172.17.0.1, server: , request: "GET /ui/app.js HTTP/1.1", upstream: "http://127.0.0.1:9528/ui/app.js", host: "192.168.116.200", referrer: "http://192.168.116.200/sockjs-node/iframe.html"

**环境信息如下：**
OS：
CentOS Linux release 7.9.2009 (Core)

MySQL版本：
[root@BaseOS logs]# mysql --version
mysql  Ver 14.14 Distrib 5.7.36, for linux-glibc2.12 (x86_64) using  EditLine wrapper

Django版本：
[root@BaseOS logs]# python3 -m django --version
3.1.14

**安装方式：**
源码编译安装

**Comment by OldPeel** [comment]
**已解决**
问题原因：
jumpserver数据库的字符集存在问题；
解决方法：
1.删除原有数据库；
2.重新创建数据库； 
mysql> create database jumpserver default charset 'utf8' collate 'utf8_bin';

**Comment by seaurching** [comment]
> **已解决** 问题原因： jumpserver数据库的字符集存在问题； 解决方法： 1.删除原有数据库； 2.重新创建数据库； mysql> create database jumpserver default charset 'utf8' collate 'utf8_bin';

我的是在仪表盘界面提示这个错误码。数据库字符集为utf8
