### ISSUE TITLE
[Question] VSCode 连接失败，多个用户时需要交互选择系统用户ID

### ISSUE THREAD

**Issue by lic0914** [jumpserver/jumpserver#8102]
**请描述您的问题.**
VSCode 连接失败，多个用户时需要交互选择系统用户ID
``` bash 
 ssh jumpserverUsername@root@AssetIP@jumpserverHostIP -p2222
```
输入密码认证通过后

**必须选择系统用户**(AssertIP有多个系统用户(172.17.0.11-15root，50.118root))
是否可以通过 ssh 指定系统用户登录呢

当我使用 
``` bash 
 ssh jumpserverUsername@172.17.0.11-15root@AssetIP@jumpserverHostIP -p2222 
```
未发现匹配的用户名 172.17.0.11-15root

VSCode login log 
``` bash 
[09:31:15.859] Log Level: 2
[09:31:15.860] remote-ssh@0.78.0
[09:31:15.861] win32 x64
[09:31:15.864] SSH Resolver called for "ssh-remote+jumpserverHostIP", attempt 1
[09:31:15.864] "remote.SSH.useLocalServer": false
[09:31:15.865] "remote.SSH.showLoginTerminal": false
[09:31:15.865] "remote.SSH.remotePlatform": {"k8s-local":"linux","k8s-nfs":"linux"}
[09:31:15.865] "remote.SSH.path": undefined
[09:31:15.865] "remote.SSH.configFile": undefined
[09:31:15.865] "remote.SSH.useFlock": true
[09:31:15.865] "remote.SSH.lockfilesInTmp": false
[09:31:15.865] "remote.SSH.localServerDownload": auto
[09:31:15.865] "remote.SSH.remoteServerListenOnSocket": false
[09:31:15.865] "remote.SSH.showLoginTerminal": false
[09:31:15.866] "remote.SSH.defaultExtensions": []
[09:31:15.866] "remote.SSH.loglevel": 2
[09:31:15.866] "remote.SSH.enableDynamicForwarding": true
[09:31:15.866] "remote.SSH.enableRemoteCommand": false
[09:31:15.866] "remote.SSH.serverPickPortsFromRange": {}
[09:31:15.866] "remote.SSH.serverInstallPath": {}
[09:31:15.882] SSH Resolver called for host: jumpserverHostIP
[09:31:15.882] Setting up SSH remote "jumpserverHostIP"
[09:31:15.901] Using commit id "e18005f0f1b33c29e81d732535d8c0e47cafb0b5" and quality "stable" for server
[09:31:15.904] Install and start server if needed
[09:31:25.022] Checking ssh with "ssh -V"
[09:31:25.060] > OpenSSH_for_Windows_8.1p1
[09:31:25.061] > , LibreSSL 3.0.2

[09:31:25.065] Running script with connection command: ssh -T -D 54387 "jumpserverHostIP" bash
[09:31:25.068] Terminal shell path: C:\Windows\System32\cmd.exe
[09:31:25.299] > ]0;C:\Windows\System32\cmd.exe
[09:31:25.299] Got some output, clearing connection timeout
[09:31:25.627] > username@root@xx.xx.xx.xx@jumpserverHostIP's password: 
[09:31:25.630] Showing password prompt
[09:31:33.853] Got password response
[09:31:33.853] "install" wrote data to terminal: "**********"
[09:31:33.873] > 
[09:31:34.142] > No PTY requested.
[09:31:35.408] "install" terminal command done
[09:31:35.408] Install terminal quit with output: No PTY requested.
[09:31:35.409] Received install output: No PTY requested.
[09:31:35.409] Failed to parse remote port from server output
[09:31:35.410] Resolver error: Error: 
	at Function.Create (c:\Users\leechao\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:586041)
	at Object.t.handleInstallOutput (c:\Users\leechao\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:584693)
	at Object.t.tryInstall (c:\Users\leechao\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:681924)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\leechao\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:644564
	at async Object.t.withShowDetailsEvent (c:\Users\leechao\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:647909)
	at async Object.t.resolve (c:\Users\leechao\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:645643)
	at async c:\Users\leechao\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:722950
[09:31:35.414] ------





```

**Comment by ibuler** [comment]
使用id连接吧

**Comment by lic0914** [comment]
@ibuler 使用id 连接 可以直接 无需交互 使用命令行登录吗 是否有实例呢 谢谢！

**Comment by wojiushixiaobai** [comment]
@lic0914 当前可以试试 client，后续我们会优化此功能
