### ISSUE TITLE
[Bug] 打开接口文档页面报错

### ISSUE THREAD

**Issue by leim** [jumpserver/jumpserver#8104]
**JumpServer 版本(v1.5.9以下不再支持)**

v2.20.3

**浏览器版本**

google chrome 100.0.4896.127

**Bug 描述**

无法打开接口文档页面，报错内容如下截图：

![微信截图_20220420104318](https://user-images.githubusercontent.com/1665397/164137774-a8e59a43-8748-42dd-89b1-31af696586bf.png)

```
2022-04-20 10:31:11 [permissions DEBUG] View require perms: {'django_celery_beat.change_periodictask'}, result: True
2022-04-20 10:31:11 [exc_handlers ERROR]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/generators.py", line 401, in get_paths
    if not self.should_include_endpoint(path, method, view, public):
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/generators.py", line 370, in should_include_endpoint
    return public or self._gen.has_view_permissions(path, method, view)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/schemas/generators.py", line 236, in has_view_permissions
    view.check_permissions(view.request)
  File "/opt/jumpserver/apps/ops/api/command.py", line 62, in check_permissions
    if not settings.SECURITY_COMMAND_EXECUTION and request.user.is_common_user:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'is_common_user'
2022-04-20 10:31:11 [log ERROR] Internal Server Error: /api/docs/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/views.py", line 34, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/vary.py", line 20, in inner_func
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/generators.py", line 401, in get_paths
    if not self.should_include_endpoint(path, method, view, public):
  File "/usr/local/lib/python3.8/site-packages/drf_yasg/generators.py", line 370, in should_include_endpoint
    return public or self._gen.has_view_permissions(path, method, view)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/schemas/generators.py", line 236, in has_view_permissions
    view.check_permissions(view.request)
  File "/opt/jumpserver/apps/ops/api/command.py", line 62, in check_permissions
    if not settings.SECURITY_COMMAND_EXECUTION and request.user.is_common_user:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'is_common_user'
172.31.0.101 [20/Apr/2022:10:31:11 +0800] 2.811334s "GET /api/docs/?format=openapi HTTP/1.0" 500 180
2022-04-20 10:31:12 [permissions DEBUG] View require perms: {'terminal.add_status'}, result: True
172.31.0.106 [20/Apr/2022:10:31:12 +0800] 0.108018s "POST /api/v1/terminal/status/ HTTP/1.1" 201 2
```

**Bug 重现步骤(有截图更好)**
1.  直接打开接口文档页面即可：http://jumpserver/api/docs

**Comment by feng626** [comment]
2.21已修改
