### ISSUE TITLE
[Bug] oidc token endpoint token_endpoint_auth_method

### ISSUE THREAD

**Issue by xiaziheng98** [jumpserver/jumpserver#8165]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.21.0

**浏览器版本**
google chrome
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36

**Bug 描述**
OIDC 的 client 认证方式即 token_endpoint_auth_method 有 **client_secret_basic、client_secret_post** 或其他方式，这里只讨论 basic 和 post 两种。
client_secret_basic 即在请求头中添加 Authorization=Basic anVtcHNlcnZlcjpqdW1wc2VydmVy；
client_secret_post 即在请求体中添加参数 client_id=jumpserver 和 client_secret=jumpserver。

在 JumpServer 认证设置中使用标准OIDC配置，**在某些oidc的实现项目中**（例如go实现的hydra）**对这两种方式不同时兼容，即二者只能选其一**。

翻阅 JumpServer 源码发现在请求 OIDC token endpoint 时既在请求头里加了 Authorization=Basic anVtcHNlcnZlcjpqdW1wc2VydmVy 也在请求体里加了参数 client_id=jumpserver 和 client_secret=jumpserver，**由于OIDC对这两种方式不同时兼容，导致 OIDC 验证client失败。**

**Bug 重现步骤(有截图更好)**
1. 
![image](https://user-images.githubusercontent.com/57082055/165670422-575a7449-572b-41f9-b27b-ba4fe66a0ed0.png)

2.
![image](https://user-images.githubusercontent.com/57082055/165670489-71a0d2e5-4bd9-4e1f-ab10-3a8b661e0f8b.png)

**Comment by xiaziheng98** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication
During Client Registration, the RP (Client) MAY register a Client Authentication method. If no method is registered, the default method is client_secret_basic.
按照上面 OIDC 协议的内容来说，OIDC 对每个 client 只支持一种 token_endpoint_auth_method，默认是 client_secret_basic。

**Comment by ibuler** [comment]
欢迎提个 pr 解决一下吧，好久没看这里了

**Comment by gehengfeng** [comment]
什么时候能解决下呢？我测试与OKTA集成，SAML跑不通，Jumpserver不支持HTTP-POST Single Logout。转站OIDC，到这儿又跑不通。折腾几天，找代码才发现是这个问题。
2022-05-24 22:04:50 [backends DEBUG] Process authenticate [OIDCAuthCodeBackend]: Prepares token payload
2022-05-24 22:04:50 [backends DEBUG] Process authenticate [OIDCAuthCodeBackend]: Prepares token headers
2022-05-24 22:04:50 [backends DEBUG] Process authenticate [OIDCAuthCodeBackend]: Call the token endpoint
2022-05-24 22:04:52 [backends DEBUG] Process authenticate [OIDCAuthCodeBackend]: Json token response error, token response content is: b'{"error":"invalid_request","error_description":"Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body."}', error is: 401 Client Error: Unauthorized for url: https://dev-21313121.okta.com/oauth2/default/v1/token
2022-05-24 22:04:52 [log ERROR] Internal Server Error: /core/auth/openid/callback/
Traceback (most recent call last):
  File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 128, in authenticate
    token_response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://dev-21313121.okta.com/oauth2/default/v1/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/jumpserver/apps/authentication/backends/oidc/views.py", line 141, in get
    user = auth.authenticate(nonce=nonce, request=request)
  File "/opt/jumpserver/apps/authentication/mixins.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/opt/jumpserver/apps/authentication/backends/oidc/decorator.py", line 59, in wrapper
    return func(*args, **kwargs)
  File "/opt/jumpserver/apps/authentication/backends/oidc/backends.py", line 134, in authenticate
    raise ParseError(error)
rest_framework.exceptions.ParseError: Json token response error, token response content is: b'{"error":"invalid_request","error_description":"Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body."}', error is: 401 Client Error: Unauthorized for url: https://dev-21313121.okta.com/oauth2/default/v1/token
