### ISSUE TITLE
centos 7 上使用0.4.0 部署， 想通过 uwsgi 与 nginx 让 jumpserver 变得快一些，但是总是报错。具体如下

### ISSUE THREAD

**Issue by gitbeyond** [jumpserver/jumpserver#818]
[简述你的问题]

##### 使用版本
centos7 + jumpserver 0.4.0 + uwsgi-2.0.15 + nginx--1.10.2

##### 问题复现步骤
1. 单独使用 jumpserver 比较慢，所以想使用 nginx + uwsgi 进行 反代

##### 具体表现[截图可能会更好些,最好能截全]
uwsgi 配置如下
```bash
(py3) [root@docker-182 jumpserver]# cat /etc/uwsgi.ini
[uwsgi]
socket = 127.0.0.1:8090
chdir = /opt/jumpserver
uid = nginx
gid = nginx
daemonize = /run/uwsgi/uwsgi.log
virtualenv = /opt/py3
module = django_wsgi
wsgi-file = apps/jumpserver/wsgi.py
master = true
env = DJANGO_SETTINGS_MODULE=apps.jumpserver.settings
pidfile = /run/uwsgi/uwsgi.pid
emperor = /etc/uwsgi.d
stats = /run/uwsgi/stats.sock
chmod-socket = 664
emperor-tyrant = true
cap = setgid,setuid
```
nginx 配置如下:
```bash
(py3) [root@docker-182 jumpserver]# cat /etc/nginx/conf.d/jumpserver.conf 
server {
    listen 8091;
    server_name localhost;
    charset     utf-8;
    access_log      /var/log/nginx/nginx_access.log;
    error_log       /var/log/nginx/nginx_error.log;
    client_max_body_size 75M;

    location /static {
        alias /opt/jumpserver/apps/static;
    }

    location / {
        include     uwsgi_params;
        uwsgi_pass  127.0.0.1:8090;
        uwsgi_connect_timeout 120;
        uwsgi_param UWSGI_CHDIR /opt/jumpserver;
    }
}

```
报错如下：
```bash
Traceback (most recent call last):
  File "apps/jumpserver/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 3, in <module>
    from django.utils.version import get_version
  File "/opt/py3/lib/python3.6/site-packages/django/utils/version.py", line 5, in <module>
    import subprocess
  File "/usr/local/python3.6/lib/python3.6/subprocess.py", line 50, in <module>
    import signal
  File "/usr/local/python3.6/lib/python3.6/signal.py", line 3, in <module>
    from functools import wraps as _wraps
  File "/opt/py3/lib/python3.6/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/opt/py3/lib/python3.6/weakref.py", line 12, in <module>
    from _weakref import (getweakrefcount, 
ImportError: cannot import name '_remove_dead_weakref'
unable to load app 0 (mountpoint='') (callable not found or import error)


--- no python application found, check your startup logs for errors ---
[pid: 2349|app: -1|req: -1/4] 10.111.23.137 () {48 vars in 1048 bytes} [Mon Nov 20 20:48:20 2017] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)


```
##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
标准的django应用，可以多研究一下，这块还没有关注

**Comment by gitbeyond** [comment]
我用django 新建一个测试项目的话，是可以成功的，证明环境是没有问题，所以我就不理解jumpserver是哪里有配置不对。 而且如果我们把 jumpserver 部署到生产环境中的话，肯定是要用 uwsgi 来做的，否则的话，那岂不是太慢了一些？仅仅用 nginx 反代处理静态内容还是不行的。还希望作者能够给出这块的方法文档来，好让 jumpserver 被更广泛的使用

**Comment by hellorocky** [comment]
我在线上使用的gunicorn, 你可以搜搜这个软件, 配置大致如下:

```python
"""gunicorn WSGI server configuration."""
import sys

bind = "127.0.0.1:8000"
max_requests = 1000 # 当某个worker同时处理超过1000的时候会重启,防止内存泄漏
worker_class = 'gevent'
workers = 8
worker_connections = 1000 # 同时允许最大1000个连接
user = "jumpserver"
group = "jumpserver"
capture_output=True
errorlog = '/home/jumpserver/jumpserver/logs/gunicorn_error.log'
loglevel = 'info'
accesslog = '/home/jumpserver/jumpserver/logs/gunicorn.log'
timeout=60
```

**Comment by hellorocky** [comment]
这一块确实应该有一篇生产环境的部署文档, 不过因为0.4版本还没有release, 所以使用到生产环境的人并不多, 等release出来了, 有时间我可以出一个生产环境部署的文档, 作为抛砖引玉吧!😂

**Comment by hellorocky** [comment]
而且我感觉, 瓶颈不一定会出在jumpserver, 更多的应该是coco, 毕竟大部分场景是运维团队在使用jumpserver页面 @gitbeyond

**Comment by eli261** [comment]
@gitbeyond 你好，看到你发的这个问题，我好奇之下 也在我自己的环境（centos7+python3.4+virtualenv）中试验了一把你说的nginx+uwsgi，过程自然是曲折的，不过，最终在几经折腾，总算是跑起来了。我觉得这种变化 因素很多，很难有一个通用的适用全部人的环境的方法。

如果你愿意，可以联系我qq 284304241，我可以帮你看一下你环境具体是什么原因跑不起来。

**Comment by gitbeyond** [comment]
@hellorocky 你说的有些道理，但是我在测试环境里，6核心，9G的机器上部署了jumpserver 之后，点个页面都很慢，据我观察是慢在python 这块的处理上。 所以我想部署在 nginx+ uwsgi 的环境中。至于 gunicorn 我记得在弄 gitlab 的时候好像见过，刚搜了一下 ，感觉这个好像是 tomcat 于 jsp 的类似。可以独立工作起来。有空尝试下，我先把 nginx + uwsgi 的给解决掉，不解决，心里闷得慌。 @eli261 ，搜索你的 qq 号码了，搜不到啊，还麻烦给个其他的联系方式。thanks。 ```*** Operational MODE: single process ***
Traceback (most recent call last):
  File "jumpserver/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/opt/py3/lib/python3.6/site-packages/django/__init__.py", line 3, in <module>
    from django.utils.version import get_version
  File "/opt/py3/lib/python3.6/site-packages/django/utils/version.py", line 5, in <module>
    import subprocess
  File "/usr/local/python3.6/lib/python3.6/subprocess.py", line 50, in <module>
    import signal
  File "/usr/local/python3.6/lib/python3.6/signal.py", line 3, in <module>
    from functools import wraps as _wraps
  File "/opt/py3/lib/python3.6/functools.py", line 23, in <module>
    from weakref import WeakKeyDictionary
  File "/opt/py3/lib/python3.6/weakref.py", line 12, in <module>
    from _weakref import (getweakrefcount, 
ImportError: cannot import name '_remove_dead_weakref'
unable to load app 0 (mountpoint='') (callable not found or import error)
```  
目前是这个报错，我的 uwsgi 配置如下：
```bash
[uwsgi]
socket = 127.0.0.1:8090
chdir = /opt/jumpserver/apps
uid = nginx
gid = nginx
daemonize = /run/uwsgi/jumpserver_uwsgi.log
virtualenv = /opt/py3
wsgi-file = jumpserver/wsgi.py
master = true
env = DJANGO_SETTINGS_MODULE=jumpserver.settings
pidfile = /run/uwsgi/jumpserver_uwsgi.pid
vacuum = true
```
你把你配置给一下 ，我参考下也好。

**Comment by eli261** [comment]
@gitbeyond
我的qq，elichn@126.com

**Comment by gitbeyond** [comment]
@eli261 仍然搜索不到，你的qq 估计设置了什么权限了

**Comment by gitbeyond** [comment]
@hellorocky 我尝试了 gunicorn ，但是仍然是慢，
```bash
10.111.23.137 - - [23/Nov/2017:14:17:42 +0800] "GET /assets/asset/ HTTP/1.1" 200 20739 "http://10.111.32.182:8091/assets/asset-group/1/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
10.111.23.137 - - [23/Nov/2017:14:17:42 +0800] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 114011 "http://10.111.32.182:8091/assets/asset/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
10.111.23.137 - - [23/Nov/2017:14:17:42 +0800] "GET /static/css/font-awesome.css HTTP/1.1" 200 26651 "http://10.111.32.182:8091/assets/asset/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
```
这些是我在前端的 资产组页面点 资产链接时开始的日志，直到下面的日志，页面才返回了
```bash
10.111.23.137 - - [23/Nov/2017:14:18:04 +0800] "GET /static/js/plugins/metisMenu/jquery.metisMenu.js HTTP/1.1" 200 3984 "http://10.111.32.182:8091/assets/asset/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
10.111.23.137 - - [23/Nov/2017:14:18:04 +0800] "GET /static/js/plugins/toastr/toastr.min.js HTTP/1.1" 200 5216 "http://10.111.32.182:8091/assets/asset/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
10.111.23.137 - - [23/Nov/2017:14:18:04 +0800] "GET /static/js/inspinia.js HTTP/1.1" 200 4636 "http://10.111.32.182:8091/assets/asset/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
```
14:17:42 --> 14:18:04 足足等了 20秒， 哪里出了问题，我一时想不通

**Comment by eli261** [comment]
@gitbeyond 你给个联系方式，我联系你。

**Comment by gitbeyond** [comment]
qq:442838751

**Comment by hellorocky** [comment]
#782 是不是这个问题

**Comment by gitbeyond** [comment]
感谢各位的回答，感谢  eli261 的指导，因为在以下文件中存在了一些外网的链接，而这些链接无法访问，所以造成了加载变慢，文件如下：
```bash
[root@docker-182 apps]# grep -R "fonts\.css" ./*
./static/css/plugins/inputTags.css:@import url("https://fonts.css.network/css?family=Open+Sans:300,400,600,700");
./static/css/plugins/inputTags.css:@import url("https://fonts.css.network/css?family=Roboto:400,300,500,700");
./static/css/style.css:@import url("https://fonts.css.network/css?family=Open+Sans:300,400,600,700");
./static/css/style.css:@import url("https://fonts.css.network/css?family=Roboto:400,300,500,700");
./static/js/plugins/highcharts/themes/dark-unica.js:	href: 'https://fonts.css.network/css?family=Unica+One',
./static/js/plugins/highcharts/themes/grid-light.js:	href: 'https://fonts.css.network/css?family=Dosis:400,600',
./static/js/plugins/highcharts/themes/sand-signika.js:	href: 'https://fonts.css.network/css?family=Signika:400,700'
```
而使用 uwsgi 是因为我这里软件栈不匹配造成的，我用的是编译的 python3.6 ，并且是 pip 装的 uwsgi,可能是这个版本不匹配的问题，转而使用 yum 安装的 python34 及 uwsgi 时，即可以正常使用uwsgi 来访问 jumpserver了。

**Comment by gitbeyond** [comment]
@hellorocky  的确是 #782 的问题

**Comment by gitbeyond** [comment]
closes #818
