### ISSUE TITLE
源码部署方式安装Core组件报错

### ISSUE THREAD

**Issue by lixuan-git** [jumpserver/jumpserver#8182]
Core:
1.Step pip install -r requirements/requirements.txt
ERROR: Could not find a version that satisfies the requirement numpy==1.22.0
ERROR: No matching distribution found for numpy==1.22.0

Lina:
1.Step yarn serve
SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._compile (/opt/lina-v2.19.0/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/opt/lina-v2.19.0/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at registerRoutes (/opt/lina-v2.19.0/mock/mock-server.js:10:30)
    at Object.module.exports.app [as after] (/opt/lina-v2.19.0/mock/mock-server.js:41:22)
    at Server.setupAfterFeature (/opt/lina-v2.19.0/node_modules/webpack-dev-server/lib/Server.js:452:18)
    at Object.after (/opt/lina-v2.19.0/node_modules/webpack-dev-server/lib/Server.js:512:16)
    at forEach (/opt/lina-v2.19.0/node_modules/webpack-dev-server/lib/Server.js:571:24)
    at Array.forEach (<anonymous>)
    at Server.setupFeatures (/opt/lina-v2.19.0/node_modules/webpack-dev-server/lib/Server.js:570:49)

2.Step yarn build:prod
The new files are not in the path ./build

Luna:
1.Step ng serve
Command 'ng' not found

2.Step ng build -prod  
Command param is wrong, i think it should be
ng build --prod

KoKo:
1.Step make
fatal: Needed a single revision
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

……
pkg/srvconn/conn_k8s_container.go:11:2: k8s.io/api@v0.23.1: Get "https://proxy.golang.org/k8s.io/api/@v/v0.23.1.zip": dial tcp 172.217.163.49:443: connect: connection refused
pkg/srvconn/conn_k8s_container.go:12:2: k8s.io/client-go@v0.23.1: Get "https://proxy.golang.org/k8s.io/client-go/@v/v0.23.1.zip": dial tcp 142.251.42.241:443: connect: connection refused
pkg/srvconn/conn_k8s_container.go:13:2: k8s.io/client-go@v0.23.1: Get "https://proxy.golang.org/k8s.io/client-go/@v/v0.23.1.zip": dial tcp 142.251.42.241:443: connect: connection refused
pkg/srvconn/conn_k8s_container.go:14:2: k8s.io/client-go@v0.23.1: Get "https://proxy.golang.org/k8s.io/client-go/@v/v0.23.1.zip": dial tcp 142.251.42.241:443: connect: connection refused
pkg/srvconn/conn_k8s_container.go:15:2: k8s.io/client-go@v0.23.1: Get "https://proxy.golang.org/k8s.io/client-go/@v/v0.23.1.zip": dial tcp 142.251.42.241:443: connect: connection refused
make: *** [Makefile:41: darwin-amd64] Error 1

2.Step ./koko
The file named koko is not found

Lion:
1.Step ./lion
  <div id="explanation">
    <p>
      You're seeing this error because you have <code>DEBUG = True</code> in your
      Django settings file. Change that to <code>False</code>, and Django will
      display a standard page generated by the handler for this status code.
    </p>
  </div>

</body>
</html>

2022-04-12 16:38:42 main main.go [ERROR] 注册终端失败退出

2.Step ./lion
EnableRemoteAppUpDownLoad:false EnableRemoteAPPCopyPaste:false CleanDriveScheduleTime:1 ShareRoomType: RedisHost: RedisPort:0 RedisPassword: RedisDBIndex:0}
2022-04-12 18:35:12 main main.go [ERROR] POST http://127.0.0.1:8080/api/v1/terminal/terminal-registrations/ failed, get code: 500, {"error": "Server internal error"}

**Comment by wojiushixiaobai** [comment]
Receive your feedback.
Please deploy according to the dockerfile of the project, and the document will be updated later.

```bash
# ERROR: Could not find a version that satisfies the requirement xxx
pip install -r requirements/requirements.txt -i https://pypi.douban.com/simple
```

```bash
# Command 'ng' not found
npm run-script build
```

**Comment by lixuan-git** [comment]
您好，我们计划将jumpserver用于生产环境的管理，并且进行一些本地化的安全方面二次开发，所以选择源码方式部署验证，对于Issue提到的其它问题，是否没有更好的办法解决？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jumpserver/jumpserver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 上午7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jumpserver/jumpserver] 源码部署方式安装Core组件报错 (Issue #8182)





 
Receive your feedback.
 Please deploy according to the dockerfile of the project, and the document will be updated later.
 # ERROR: Could not find a version that satisfies the requirement xxx pip install -r requirements/requirements.txt -i https://pypi.douban.com/simple
 # Command 'ng' not found npm run-script build

**Comment by wojiushixiaobai** [comment]
@lixuan-git 其他的组件都可以下载编译好的 release 包使用，或者参考 Dockerfile 手动构建下即可。

**Comment by wojiushixiaobai** [comment]
@lixuan-git 文档已经更新，请检查下
