### ISSUE TITLE
docker jms_all 安装提示无法连接数据库

### ISSUE THREAD

**Issue by jimcat8** [jumpserver/jumpserver#8183]
OS：Rocky Linux 8.5

```bash
shell >  if [ ! "$SECRET_KEY" ]; then   SECRET_KEY=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 50`;   echo "SECRET_KEY=$SECRET_KEY" >> ~/.bashrc;   echo $SECRET_KEY; else   echo $SECRET_KEY; fi    
shell >  if [ ! "$BOOTSTRAP_TOKEN" ]; then   BOOTSTRAP_TOKEN=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 16`;   echo "BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN" >> ~/.bashrc;   echo $BOOTSTRAP_TOKEN; else   echo $BOOTSTRAP_TOKEN; fi
```

```bash
#!/bin/bash
echo "---1.安装基本的包、软件包以及存储库---"
yum -y install dnf 
dnf -y update  
dnf -y install vim wget  mlocate lrzsz tar gzip bzip2 zip unzip psmisc git epel-release gcc gcc-c++ make cmake automake yum-utils htop sshpass mariadb-devel openldap-devel libxml2-devel   xmlsec1-devel  xmlsec1-openssl-devel  libtool-ltdl-devel  python3

echo "---2.安装docker,配置存储库---"
dnf config-manager --enable  --add-repo  https://download.docker.com/linux/centos/docker-ce.repo 
sed -i "s/enabled=0/enabled=1/g"  /etc/yum.repos.d/Rocky-PowerTools.repo  

echo "---3.启动docker服务---"
dnf makecache 
dnf install docker-ce docker-ce-cli  containerd.io 
systemctl start docker.service 
systemctl enable docker.service 

echo "---4.拉取mysql镜像, 创建容器---"
docker pull mysql:latest 
mkdir -p /docker/mysql/data
mkdir -p /etc/my.conf.d  
touch /etc/my.cnf   
touch  /var/lib/mysql-files
echo  -e  "[mysqld]\nsecure-file-priv=/"  > /etc/my.cnf

docker run -d -p 3306:3306 --name=mysql8 \
-e MYSQL_ROOT_PASSWORD=google404notfound   \
-e MYSQL_DATABASE="jumpserver" \
-e MYSQL_USER="jumpserver"  \
-e MYSQL_PASSWORD="jumpserver" \
--privileged=true \
-v /docker/mysql/data:/var/lib/mysql:rw \
-v /etc/my.cnf:/etc/mysql/my.cnf:rw  \
-v /etc/my.conf.d:/etc/mysql/conf.d:rw \
-v  /var/lib/mysql-files:/var/lib/mysql-files:rw  \
mysql:latest --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 

echo "---5.拉取redis, 创建容器---"
docker pull redis:latest 
mkdir -p /docker/redis/data  
docker run -d --name=redis7 -p 6379:6379  --privileged=true  -v  /docker/redis/data:/data  redis:latest

echo "---6.拉取jms_all镜像---"
docker pull  jumpserver/jms_all:latest  

echo  "---6.1初始化数据库---"
mkdir  -p /opt/jumpserver/{core,koko,lion}/data

docker  run  --name="jms_all"  --rm \
-v /opt/jumpserver/core/data:/opt/jumpserver/data \
-v /opt/jumpserver/koko/data:/opt/koko/data  \
-v /opt/jumpserver/lion/data:/opt/lion/data  \
-e SECRET_KEY=$SECRET_KEY  \
-e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN  \
-e LOG_LEVEL=ERROR \
-e DB_ENGINE =mysql \
-e DB_HOST=10.1.1.5 \
-e DB_PORT=3306 \
-e DB_USER=jumpserver \
-e DB_PASSWORD=jumpserver \
-e DB_NAME=jumpserver \
-e REDIS_HOST=10.1.1.5 \
-e REDIS_PORT=6379 \
-e REDIS_PASSWORD=  \
jumpserver/jms_all:latest  init_db   &&

echo  "---6.2启动jumpserver---"
docker run  -d  --name="jms_all"   \
-v /opt/jumpserver/core/data:/opt/jumpserver/data \
-v /opt/jumpserver/koko/data:/opt/koko/data  \
-v /opt/jumpserver/lion/data:/opt/lion/data  \
-p 80:80 \
-p 2222:2222 \
-p 33060:33060 \
-p 33061:33061 \
-e SECRET_KEY=$SECRET_KEY \
-e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN \
-e LOG_LEVEL=ERROR \
-e DB_HOST=10.1.1.5 \
-e DB_PORT=3306 \
-e DB_USER=jumpserver \
-e DB_PASSWORD=jumpserver  \
-e DB_NAME=jumpserver  \
-e REDIS_HOST=10.1.1.5 \
-e REDIS_PORT=6379 \
-e REDIS_PASSWORD= \
--privileged=true \
jumpserver/jms_all:latest
```

当进行到6.1时，提示说以下错误

```text
---6.1初始化数据库---
Traceback (most recent call last):
  File "./jms", line 20, in <module>
    django.setup()
  File "/opt/py3/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/py3/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/py3/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/py3/lib/python3.8/site-packages/django/conf/__init__.py", line 189, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
 数据库处理失败, 请根据错误排查问题. 
```

我想请教下，安装的这个过程哪一步出现了问题。

**Comment by wsoyinka** [comment]
@jimcat8  :  In the bash script, try :

```
-e  "SECRET_KEY=$SECRET_KEY"  
```

**Comment by wsoyinka** [comment]
if that doesn't work try:

```
-e  SECRET_KEY="$SECRET_KEY" 

```

**Comment by jimcat8** [comment]
我重新尝试了下
`export  BOOTSTRAP_TOKEN;export SECRET_KEY`

```bash
env | grep -i -E "boot|key"
BOOTSTRAP_TOKEN=GF1wN1XsWnH1gi6A
SECRET_KEY=HW8pCn6doehFGC9dNkBxvrQN5FojvBgFNM0HZ7CRQqogAundRE
```

运行 bash 脚本:

```text
2022-05-01 10:43:59 Collect static files
2022-05-01 10:43:59 Collect static files done
2022-05-01 10:43:59 Check database structure change ...
2022-05-01 10:43:59 Migrate model change to database ...
2022-05-01 10:44:00 Perform migrate failed, exit
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/py3/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/py3/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/opt/py3/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2061, 'RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support')
```

**Comment by wojiushixiaobai** [comment]
不支持 utf8mb4
