### ISSUE TITLE
作业中心——任务监控Flower报错信息

### ISSUE THREAD

**Issue by diaoz** [jumpserver/jumpserver#8222]
遇到这个报错问题，请教下该如何处理：

**audits.tasks.clean_audits_log_period**

Exception:
`FieldError("Cannot resolve keyword 'datetime' into field. Choices are: asset, date_start, filename, id, is_success, operate, org_id, remote_addr, system_user, user") `

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/audits/tasks.py", line 40, in clean_audits_log_period
    clean_ftp_log_period()
  File "/opt/jumpserver/apps/audits/tasks.py", line 32, in clean_ftp_log_period
    FTPLog.objects.filter(datetime__lt=expired_day).delete()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1360, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1379, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1260, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1086, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1483, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'datetime' into field. Choices are: asset, date_start, filename, id, is_success, operate, org_id, remote_addr, system_user, user
```

Children:
`set() `

**Comment by wojiushixiaobai** [comment]
将你修改的代码还原

**Comment by enan820** [comment]
@wojiushixiaobai FTPLog`类中确实没有`datetime`，这个是fix: ftp日志清理bug时修改了task.py

**Comment by wojiushixiaobai** [comment]
将版本更新至最新看看问题是否解决，如果未解决的话请说明一下复现的过程。感谢
