### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Jerrywgl** [jumpserver/jumpserver#8242]
**请描述您的问题.**
出现问题的服务版本：v2.20.3

在koko已经配置了：
    - name: ENABLE_LOCAL_PORT_FORWARD
      value: "true"
    - name: ENABLE_VSCODE_SUPPORT
      value: "true"

远程连接报错日志如下：
[16:52:47.164] Received install output: local-server-1> Spawned ssh, pid=50253
OpenSSH_8.6p1, LibreSSL 3.3.5
debug1: Server host key: ssh-rsa SHA256:aBRElwzfX8hyaF+RUlSrWSFoRzo87wbiEZKbcCr9cI0
Authenticated to jump.hahaha.com ([192.168.1.1]:2222).
Transferred: sent 3248, received 1752 bytes, in 0.0 seconds
Bytes per second: sent 120609.0, received 65057.6
local-server-1> ssh child died, shutting down

[16:52:47.164] Stopped parsing output early. Remaining text: local-server-1> Spawned ssh, pid=50253OpenSSH_8.6p1, LibreSSL 3.3.5debug1: Server host key: ssh-rsa SHA256:aBRElwzfX8hyaF+RUlSrWSFoRzo87wbiEZKbcCr9cI0Authenticated to jump.hahaha.com ([192.168.1.1]:2222).Transferred: sent 3248, received 1752 bytes, in 0.0 secondsBytes per second: sent 120609.0, received 65057.6local-server-1> ssh child died, shutting down
[16:52:47.164] Failed to parse remote port from server output
[16:52:47.164] Resolver error: Error: 
	at Function.Create (/Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:585789)
	at Object.t.handleInstallOutput (/Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:584441)
	at Object.e [as tryInstallWithLocalServer] (/Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:624909)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:643946
	at async Object.t.withShowDetailsEvent (/Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:647693)
	at async /Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:623381
	at async b (/Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:619887)
	at async Object.t.resolveWithLocalServer (/Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:622996)
	at async Object.t.resolve (/Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:645303)
	at async /Users/guanlewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022051115/out/extension.js:1:722519
[16:52:47.166] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"UnparsableOutput","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":571,"timing.preSshTime":45}}
[16:52:47.166] ------

**Comment by Jerrywgl** [comment]
追踪发现，连接已经建立且完成了身份验证，但是突然连接就断掉了。local-server-1> ssh child died, shutting down
