### ISSUE TITLE
[Question] vscode remote ssh连接失败

### ISSUE THREAD

**Issue by Kurt-Shiwz** [jumpserver/jumpserver#8341]
**请描述您的问题.**
ssh jumpserverUsername@systemUsername@AssetIP@jumpserverHostIP -p2222
使用这个方式链接公司的主机失败，在提示输入MFA后就失败了， `too long for Unix domain socket`。是需要公司jumpserver后台打开什么配置吗？

```
[17:14:35.629] Log Level: 2
[17:14:35.632] remote-ssh@0.80.0
[17:14:35.632] darwin x64
[17:14:35.641] SSH Resolver called for "ssh-remote+jumpserver.company.com", attempt 1
[17:14:35.644] "remote.SSH.useLocalServer": true
[17:14:35.649] "remote.SSH.path": undefined
[17:14:35.650] "remote.SSH.configFile": undefined
[17:14:35.651] "remote.SSH.useFlock": true
[17:14:35.652] "remote.SSH.lockfilesInTmp": false
[17:14:35.653] "remote.SSH.localServerDownload": auto
[17:14:35.654] "remote.SSH.remoteServerListenOnSocket": false
[17:14:35.655] "remote.SSH.showLoginTerminal": false
[17:14:35.656] "remote.SSH.defaultExtensions": []
[17:14:35.657] "remote.SSH.loglevel": 2
[17:14:35.659] "remote.SSH.enableDynamicForwarding": true
[17:14:35.660] "remote.SSH.enableRemoteCommand": false
[17:14:35.661] "remote.SSH.serverPickPortsFromRange": {}
[17:14:35.662] "remote.SSH.serverInstallPath": {}
[17:14:35.697] SSH Resolver called for host: jumpserver.company.com
[17:14:35.697] Setting up SSH remote "jumpserver.company.com"
[17:14:35.703] Acquiring local install lock: /var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-remote-ssh-137029cb-install.lock
[17:14:35.710] Looking for existing server data file at /Users/username/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-137029cb-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.80.0/data.json
[17:14:35.712] Using commit id "c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5" and quality "stable" for server
[17:14:35.717] Install and start server if needed
[17:14:35.724] PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/username/go/bin:/Users/username/Library/Python/3.9/bin
[17:14:35.724] Checking ssh with "ssh -V"
[17:14:35.745] > OpenSSH_8.6p1, LibreSSL 3.3.6

[17:14:35.750] askpass server listening on /var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-cf2efe7f356c91a73db4cf937234db216423145f.sock
[17:14:35.750] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-71a06aefa5c23b6b4194b5401f1f9a7d565efcbb.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","64225","-o","ConnectTimeout=15","jumpserver.company.com"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/username/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-137029cb-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.80.0/data.json"}
[17:14:35.750] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.3U8Xmu3AVc/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-cf2efe7f356c91a73db4cf937234db216423145f.sock"}
[17:14:35.752] Spawned 16537
[17:14:36.004] > local-server-1> Spawned ssh, pid=16539
[17:14:36.010] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[17:14:36.109] stderr> debug1: Server host key: ssh-rsa SHA256:EbARR/yDioG3UULFKK3FRAzCB99tIPL5FWytWp5t6FM
[17:14:36.287] stderr> Authenticated with partial success.
[17:14:36.338] stderr> Please Enter MFA Code.
[17:14:36.514] Got askpass request: {"request":"(username@username@ip1@jumpserver.company.com) [OTP Code]:"}
[17:14:36.517] Listening for interwindow password on /var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-afc4cf071f9de520c5332e4e46c3a3cd123f20c5.sock
[17:14:36.517] Writing password prompt to globalState
[17:14:40.598] Interactor gave response: ******
[17:14:40.599] Cleaning up other-window auth server
[17:14:40.785] stderr> Authenticated to jumpserver.company.com ([ip2]:2222).
[17:14:40.787] stderr> unix_listener: path "/Users/username/.ssh/master-username@username@ip1@jumpserver.company.com:2222.EG0Z4316MKlh4R4E" too long for Unix domain socket
[17:14:40.788] > local-server-1> ssh child died, shutting down
[17:14:40.795] Local server exit: 0
[17:14:40.796] Received install output: local-server-1> Spawned ssh, pid=16539
OpenSSH_8.6p1, LibreSSL 3.3.6
debug1: Server host key: ssh-rsa SHA256:EbARR/yDioG3UULFKK3FRAzCB99tIPL5FWytWp5t6FM
Authenticated with partial success.
Please Enter MFA Code.
Authenticated to jumpserver.company.com ([ip2]:2222).
unix_listener: path "/Users/username/.ssh/master-username@username@ip1@jumpserver.company.com:2222.EG0Z4316MKlh4R4E" too long for Unix domain socket
local-server-1> ssh child died, shutting down

[17:14:40.798] Failed to parse remote port from server output
[17:14:40.799] Resolver error: Error: 
	at Function.Create (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:585789)
	at Object.t.handleInstallOutput (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:584441)
	at Object.e [as tryInstallWithLocalServer] (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:624908)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:643945
	at async Object.t.withShowDetailsEvent (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:647692)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:623380
	at async b (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:619886)
	at async Object.t.resolveWithLocalServer (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:622995)
	at async Object.t.resolve (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:645302)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:722509
[17:14:40.809] ------
```

**Comment by wojiushixiaobai** [comment]
- cat /opt/jumpserver/config/config.txt
```bash
ENABLE_LOCAL_PORT_FORWARD=True   # 是否开启本地转发 (目前仅对 vscode remote ssh 有效果) v2.11 新增
ENABLE_VSCODE_SUPPORT=True       # 是否开启 针对 vscode 的 remote-ssh 远程开发支持 ( 前置条件: 必须开启 ENABLE_LOCAL_PORT_FORWARD ) v2.11 新增。( 注意: vscode 的连接操作，无审计功能 )
```

**Comment by Kurt-Shiwz** [comment]
> * cat /opt/jumpserver/config/config.txt
> 
> ```shell
> ENABLE_LOCAL_PORT_FORWARD=True   # 是否开启本地转发 (目前仅对 vscode remote ssh 有效果) v2.11 新增
> ENABLE_VSCODE_SUPPORT=True       # 是否开启 针对 vscode 的 remote-ssh 远程开发支持
>                                  #  ( 前置条件: 必须开启 ENABLE_LOCAL_PORT_FORWARD ) v2.11 新增。
>                                  # ( 注意: vscode 的连接操作，无审计功能 )
> ```

打开了，还是不行。这个主机上有多个帐号，我用的是授权的ops帐号。
在终端使用命令也不行`ssh username@ops@ip1@openjumpserver.company.com -p2222`
`unix_listener: path "/Users/username/.ssh/master-username@ops@ip1@openjumpserver.company.com:2222.xdsqfq" too long for Unix domain socket`

电脑是mac 12.4，zsh （切到bash也试了）
jumpserver是v2.19.2
ops主机是bash，redhat 7.7

```
[15:12:52.731] Log Level: 2
[15:12:52.732] remote-ssh@0.80.0
[15:12:52.732] darwin x64
[15:12:52.737] SSH Resolver called for "ssh-remote+openjumpserver.company.com", attempt 1
[15:12:52.738] "remote.SSH.useLocalServer": true
[15:12:52.741] "remote.SSH.path": undefined
[15:12:52.742] "remote.SSH.configFile": undefined
[15:12:52.742] "remote.SSH.useFlock": true
[15:12:52.743] "remote.SSH.lockfilesInTmp": false
[15:12:52.743] "remote.SSH.localServerDownload": auto
[15:12:52.744] "remote.SSH.remoteServerListenOnSocket": false
[15:12:52.744] "remote.SSH.showLoginTerminal": false
[15:12:52.745] "remote.SSH.defaultExtensions": []
[15:12:52.745] "remote.SSH.loglevel": 2
[15:12:52.745] "remote.SSH.enableDynamicForwarding": true
[15:12:52.746] "remote.SSH.enableRemoteCommand": false
[15:12:52.746] "remote.SSH.serverPickPortsFromRange": {}
[15:12:52.747] "remote.SSH.serverInstallPath": {}
[15:12:52.766] SSH Resolver called for host: openjumpserver.company.com
[15:12:52.766] Setting up SSH remote "openjumpserver.company.com"
[15:12:52.773] Acquiring local install lock: /var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-remote-ssh-6ed8337f-install.lock
[15:12:52.777] Looking for existing server data file at /Users/username/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6ed8337f-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.80.0/data.json
[15:12:52.778] Using commit id "c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5" and quality "stable" for server
[15:12:52.784] Install and start server if needed
[15:12:52.792] PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/username/go/bin:/Users/username/Library/Python/3.9/bin
[15:12:52.792] Checking ssh with "ssh -V"
[15:12:52.800] > OpenSSH_8.6p1, LibreSSL 3.3.6

[15:12:52.806] askpass server listening on /var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-5fd0697aac0c6d768200b1311dfccf717ff82745.sock
[15:12:52.807] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-6f1799a3a8b55c02c23bd3dbc4e9d17467a273da.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51966","-o","ConnectTimeout=15","openjumpserver.company.com"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/username/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6ed8337f-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.80.0/data.json"}
[15:12:52.807] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.3U8Xmu3AVc/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-5fd0697aac0c6d768200b1311dfccf717ff82745.sock"}
[15:12:52.808] Spawned 51781
[15:12:52.955] > local-server-1> Spawned ssh, pid=51789
[15:12:52.958] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[15:12:53.066] stderr> debug1: Server host key: ssh-rsa SHA256:EbARR/yDioG3UULFKK3FRAzCB99tIPL5FWytWp5t6FM
[15:12:53.317] stderr> Authenticated with partial success.
[15:12:53.374] stderr> Please Enter MFA Code.
[15:12:53.535] Got askpass request: {"request":"(username@ops@ip1@openjumpserver.company.com) [OTP Code]:"}
[15:12:53.537] Listening for interwindow password on /var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-faa2d8b9d806c2a72890da3d7a832e157ca9dcde.sock
[15:12:53.537] Writing password prompt to globalState
[15:13:13.748] Interactor gave response: ******
[15:13:13.749] Cleaning up other-window auth server
[15:13:13.934] stderr> Authenticated to openjumpserver.company.com ([ip2]:2222).
[15:13:13.935] stderr> unix_listener: path "/Users/username/.ssh/master-username@ops@ip1@openjumpserver.company.com:2222.IZVTBg8gJhUYe9Yb" too long for Unix domain socket
[15:13:13.936] > local-server-1> ssh child died, shutting down
[15:13:13.940] Local server exit: 0
[15:13:13.941] Received install output: local-server-1> Spawned ssh, pid=51789
OpenSSH_8.6p1, LibreSSL 3.3.6
debug1: Server host key: ssh-rsa SHA256:EbARR/yDioG3UULFKK3FRAzCB99tIPL5FWytWp5t6FM
Authenticated with partial success.
Please Enter MFA Code.
Authenticated to openjumpserver.company.com ([ip2]:2222).
unix_listener: path "/Users/username/.ssh/master-username@ops@ip1@openjumpserver.company.com:2222.IZVTBg8gJhUYe9Yb" too long for Unix domain socket
local-server-1> ssh child died, shutting down

[15:13:13.942] Failed to parse remote port from server output
[15:13:13.943] Resolver error: Error: 
	at Function.Create (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:585789)
	at Object.t.handleInstallOutput (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:584441)
	at Object.e [as tryInstallWithLocalServer] (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:624908)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:643945
	at async Object.t.withShowDetailsEvent (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:647692)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:623380
	at async b (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:619886)
	at async Object.t.resolveWithLocalServer (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:622995)
	at async Object.t.resolve (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:645302)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:722509
[15:13:13.951] ------
```

**Comment by Kurt-Shiwz** [comment]
> * cat /opt/jumpserver/config/config.txt
> 
> ```shell
> ENABLE_LOCAL_PORT_FORWARD=True   # 是否开启本地转发 (目前仅对 vscode remote ssh 有效果) v2.11 新增
> ENABLE_VSCODE_SUPPORT=True       # 是否开启 针对 vscode 的 remote-ssh 远程开发支持
>                                  #  ( 前置条件: 必须开启 ENABLE_LOCAL_PORT_FORWARD ) v2.11 新增。
>                                  # ( 注意: vscode 的连接操作，无审计功能 )
> ```

打开了，还是不行。这个主机上有多个帐号，我用的是授权的ops帐号。
在终端使用命令也不行`ssh username@ops@ip1@openjumpserver.company.com -p2222`
`unix_listener: path "/Users/username/.ssh/master-username@ops@ip1@openjumpserver.company.com:2222.xdsqfq" too long for Unix domain socket`

电脑是mac 12.4，zsh （切到bash也试了）
jumpserver是v2.19.2
ops主机是bash，redhat 7.7

```
[15:12:52.731] Log Level: 2
[15:12:52.732] remote-ssh@0.80.0
[15:12:52.732] darwin x64
[15:12:52.737] SSH Resolver called for "ssh-remote+openjumpserver.company.com", attempt 1
[15:12:52.738] "remote.SSH.useLocalServer": true
[15:12:52.741] "remote.SSH.path": undefined
[15:12:52.742] "remote.SSH.configFile": undefined
[15:12:52.742] "remote.SSH.useFlock": true
[15:12:52.743] "remote.SSH.lockfilesInTmp": false
[15:12:52.743] "remote.SSH.localServerDownload": auto
[15:12:52.744] "remote.SSH.remoteServerListenOnSocket": false
[15:12:52.744] "remote.SSH.showLoginTerminal": false
[15:12:52.745] "remote.SSH.defaultExtensions": []
[15:12:52.745] "remote.SSH.loglevel": 2
[15:12:52.745] "remote.SSH.enableDynamicForwarding": true
[15:12:52.746] "remote.SSH.enableRemoteCommand": false
[15:12:52.746] "remote.SSH.serverPickPortsFromRange": {}
[15:12:52.747] "remote.SSH.serverInstallPath": {}
[15:12:52.766] SSH Resolver called for host: openjumpserver.company.com
[15:12:52.766] Setting up SSH remote "openjumpserver.company.com"
[15:12:52.773] Acquiring local install lock: /var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-remote-ssh-6ed8337f-install.lock
[15:12:52.777] Looking for existing server data file at /Users/username/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6ed8337f-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.80.0/data.json
[15:12:52.778] Using commit id "c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5" and quality "stable" for server
[15:12:52.784] Install and start server if needed
[15:12:52.792] PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/username/go/bin:/Users/username/Library/Python/3.9/bin
[15:12:52.792] Checking ssh with "ssh -V"
[15:12:52.800] > OpenSSH_8.6p1, LibreSSL 3.3.6

[15:12:52.806] askpass server listening on /var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-5fd0697aac0c6d768200b1311dfccf717ff82745.sock
[15:12:52.807] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-6f1799a3a8b55c02c23bd3dbc4e9d17467a273da.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51966","-o","ConnectTimeout=15","openjumpserver.company.com"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/username/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6ed8337f-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.80.0/data.json"}
[15:12:52.807] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.3U8Xmu3AVc/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-5fd0697aac0c6d768200b1311dfccf717ff82745.sock"}
[15:12:52.808] Spawned 51781
[15:12:52.955] > local-server-1> Spawned ssh, pid=51789
[15:12:52.958] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[15:12:53.066] stderr> debug1: Server host key: ssh-rsa SHA256:EbARR/yDioG3UULFKK3FRAzCB99tIPL5FWytWp5t6FM
[15:12:53.317] stderr> Authenticated with partial success.
[15:12:53.374] stderr> Please Enter MFA Code.
[15:12:53.535] Got askpass request: {"request":"(username@ops@ip1@openjumpserver.company.com) [OTP Code]:"}
[15:12:53.537] Listening for interwindow password on /var/folders/rb/0sg28hyn7tl_rvj402r3my5w0000gp/T/vscode-ssh-askpass-faa2d8b9d806c2a72890da3d7a832e157ca9dcde.sock
[15:12:53.537] Writing password prompt to globalState
[15:13:13.748] Interactor gave response: ******
[15:13:13.749] Cleaning up other-window auth server
[15:13:13.934] stderr> Authenticated to openjumpserver.company.com ([ip2]:2222).
[15:13:13.935] stderr> unix_listener: path "/Users/username/.ssh/master-username@ops@ip1@openjumpserver.company.com:2222.IZVTBg8gJhUYe9Yb" too long for Unix domain socket
[15:13:13.936] > local-server-1> ssh child died, shutting down
[15:13:13.940] Local server exit: 0
[15:13:13.941] Received install output: local-server-1> Spawned ssh, pid=51789
OpenSSH_8.6p1, LibreSSL 3.3.6
debug1: Server host key: ssh-rsa SHA256:EbARR/yDioG3UULFKK3FRAzCB99tIPL5FWytWp5t6FM
Authenticated with partial success.
Please Enter MFA Code.
Authenticated to openjumpserver.company.com ([ip2]:2222).
unix_listener: path "/Users/username/.ssh/master-username@ops@ip1@openjumpserver.company.com:2222.IZVTBg8gJhUYe9Yb" too long for Unix domain socket
local-server-1> ssh child died, shutting down

[15:13:13.942] Failed to parse remote port from server output
[15:13:13.943] Resolver error: Error: 
	at Function.Create (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:585789)
	at Object.t.handleInstallOutput (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:584441)
	at Object.e [as tryInstallWithLocalServer] (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:624908)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:643945
	at async Object.t.withShowDetailsEvent (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:647692)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:623380
	at async b (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:619886)
	at async Object.t.resolveWithLocalServer (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:622995)
	at async Object.t.resolve (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:645302)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/extension.js:1:722509
[15:13:13.951] ------
```

**Comment by Kurt-Shiwz** [comment]
> * cat /opt/jumpserver/config/config.txt
> 
> ```shell
> ENABLE_LOCAL_PORT_FORWARD=True   # 是否开启本地转发 (目前仅对 vscode remote ssh 有效果) v2.11 新增
> ENABLE_VSCODE_SUPPORT=True       # 是否开启 针对 vscode 的 remote-ssh 远程开发支持
>                                  #  ( 前置条件: 必须开启 ENABLE_LOCAL_PORT_FORWARD ) v2.11 新增。
>                                  # ( 注意: vscode 的连接操作，无审计功能 )
> ```

我们有什么命令能拉取jumpserver的配置吗？比如`curl jumpserver.company.com`，因为是公司别的同事配置的，我想再check一下配置是否打开

**Comment by wojiushixiaobai** [comment]
配置后重启 jumpserver，系统用户必须要为自动登录

**Comment by Kurt-Shiwz** [comment]
> 配置后重启 jumpserver，系统用户必须要为自动登录

已经重启过了。
ops是自动登录的账户，并且还配置了authorized_keys自动登录。试了用id也不行。

**Comment by wojiushixiaobai** [comment]
先试试 手动 ssh 是否可以免密进入到资产
ssh master-username@ops@ip1@openjumpserver.company.com -p2222

**Comment by Kurt-Shiwz** [comment]
> 先试试 手动 ssh 是否可以免密进入到资产 ssh master-username@ops@[ip1@openjumpserver.company.com](mailto:ip1@openjumpserver.company.com) -p2222

`ssh master-username@ops@ip1@openjumpserver.company.com -p2222`
不能登录，提示需要输入密码。

`ssh master-username@username@ip1@openjumpserver.company.com -p2222`
另一个知道密码的账户，输入密码也不能登入

所以问题出在从“堡垒机”到“资产”的登陆上？
需要打开什么配置或者什么操作吗，这块不是很了解
（我本机(mac)账户是username）

**Comment by wojiushixiaobai** [comment]
![image](https://user-images.githubusercontent.com/24326988/172730559-aa130802-717f-4461-94cc-70696afde22e.png)

```bash
ssh demo@test@test_ssh@demo.jumpserver.org -p2222
```
如图所示：
```
# demo.jumpserver.org 为堡垒机域名
# 2222 为 ssh 访问端口
# demo 是堡垒机登录的账号，demo 账号的密码是 jumpserver
# test 是资产的登录账号
# test_ssh 是资产的 ip 或者 域名（内部改写了 hosts）
```

**Comment by Kurt-Shiwz** [comment]
> ![image](https://user-images.githubusercontent.com/24326988/172730559-aa130802-717f-4461-94cc-70696afde22e.png)
> 
> ```shell
> ssh demo@test@test_ssh@demo.jumpserver.org -p2222
> ```
> 
> 如图所示：
> 
> ```
> # demo.jumpserver.org 为堡垒机域名
> # 2222 为 ssh 访问端口
> # demo 是堡垒机登录的账号，demo 账号的密码是 jumpserver
> # test 是资产的登录账号
> # test_ssh 是资产的 ip 或者 域名（内部改写了 hosts）
> ```

搞定了，可以登上ops帐户了。把`ControlPath ~/.ssh/master-%r@%h:%p`改成`ControlPath ~/.ssh/%r@%h:%p`

但另一个知道密码的登不上，可能系统有些别的限制，我再研究一下。

**Comment by ibuler** [comment]
好的

**Comment by weibochang** [comment]
jumpserver开启了mfa验证，然后vscode就一直连接不上服务器了，也不报错
