### ISSUE TITLE
迁移手动部署版本至k8s

### ISSUE THREAD

**Issue by smallhorsegg** [jumpserver/jumpserver#8408]
helm部署2.22.2   外部mariadb10.4.25   redis5.0.9，部署完成后正常。

迁移之前通过手动部署2.11.3时，报以下错误(内置msyql5/reids6):
kp logs jms-k8s-jumpserver-jms-celery-8db856999-s2xvd
2022-06-15 15:56:09 Wed Jun 15 15:56:09 2022
2022-06-15 15:56:09 JumpServer version v2.22.2, more see https://www.jumpserver.org
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'jumpserver.terminal' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/jumpserver/apps/terminal/startup.py", line 57, in start_heartbeat
    terminal = self.get_or_register_terminal()
  File "/opt/jumpserver/apps/terminal/startup.py", line 67, in get_or_register_terminal
    terminal = Terminal.objects.filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 678, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all

迁移步骤: 
1 .导出源库
2. 改字符集
3. drop目的库，创建新库并导入

**Comment by wojiushixiaobai** [comment]
部署完成后：
- 将 pod 副本设置为 0，然后将数据库导入（外置数据库可以直接使用原数据库地址，跳过此步骤）
- 将原来使用的 core 参数添加到 values 正常启动即可

**Comment by smallhorsegg** [comment]
> 数据库变更有问题？terminal 表不存在

原来2.11.3中只有79张表    新版的2.22.2中有122张表（新版中确实没有terminal表）

**Comment by smallhorsegg** [comment]
> 部署完成后：
> 
> * 将 pod 副本设置为 0，然后将数据库导入（外置数据库可以直接使用原数据库地址，跳过此步骤）
> * 将原来使用的 core 参数添加到 values 正常启动即可

按照您说的将pod副本数设置为0  然后导数据就行了  请问这是什么问题呢？ 
还有点这个报错jms-k8s-jumpserver-jms-celery：
xception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'users_user.is_service_account' in 'field list'")

**Comment by wojiushixiaobai** [comment]
@smallhorsegg 其实就是导入的过程中不能有 jumpserver pod 在运行。保证这个条件，数据无问题的情况下升级就没啥问题
