### ISSUE TITLE
[Question] docker重新run的jms_all服务 502错误

### ISSUE THREAD

**Issue by yangyang122** [jumpserver/jumpserver#8496]
原始服务启动成功，删除掉docker进程，重新docker run操作；
数据库保持不变。
结果: ssh连接失败
查看日志： jumpserver/logs/gunicorn.log
  rest_framework.exceptions.ValidationError: {'name': [ErrorDetail(string='名称重复', code='unique')]}
2022-06-27 16:25:56 [exc_handlers ERROR] 
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/opt/jumpserver/apps/terminal/api/terminal.py", line 105, in create
    return super().create(request, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/opt/jumpserver/apps/terminal/serializers/terminal.py", line 127, in is_valid
    valid = self.service_account.is_valid(raise_exception=True)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)

**Comment by wojiushixiaobai** [comment]
到 web 页面的 终端管理 里面删除不在线的组件，稍等一会就好了。

**Comment by yangyang122** [comment]
感谢大佬
