### ISSUE TITLE
使用mysql数据库 无法连接

### ISSUE THREAD

**Issue by riseast** [jumpserver/jumpserver#874]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.4.0beta1
##### 问题复现步骤
1. [步骤1]
DockerConfig 配置如下
class DockerConfig(Config):
    #DB_ENGINE = 'sqlite'
    #DB_NAME = os.path.join(BASE_DIR, 'data', 'db.sqlite3')
    DB_ENGINE = 'mysql'
    DB_HOST = '172.23.143.232'
    DB_PORT = 3306
    DB_USER = 'jumpserver'
    DB_PASSWORD = 'jumpserver'
    DB_NAME = 'jumpserver'
    REDIS_HOST = os.environ.get('REDIS_HOST') or 'redis'
    EMAIL_HOST = os.environ.get('EMAIL_HOST') or 'smtp.qq.com'
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 465))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER') or 'admin'
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') or 'somepasswrd'
    EMAIL_USE_SSL = True if EMAIL_PORT == 465 else False
    EMAIL_USE_TLS = True if EMAIL_PORT == 587 else False
    EMAIL_SUBJECT_PREFIX = os.environ.get('EMAIL_SUBJECT_PREFIX') or '[Jumpserver] '
    SITE_URL = os.environ.get('SITE_URL') or 'http://localhost:8080'
2. [步骤2]
重新build镜像后，修改docker-compose.yml 使用新的镜像 然后docker-compose up -d 
jumpserver 服务无法启动，查看容器日志如下
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 57, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.6/site-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 236, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '172.23.143.232' (113)")
##### 具体表现[截图可能会更好些,最好能截全]

单独 执行 run_docker.sh  jumpserver 服务可以正常启动
#!/bin/bash
#

# Run redis
docker run --name redis -d redis

# Run jumpserver
docker run -d --name jumpserver -p 8080:8080 --link redis:redis jumpserver/重新build后的镜像

# Finished
echo -e "Please visit http://ServerIP:8080\n Username: admin\nPassword: admin\n"riseast utils # 

##### 其他

[注:] 完成后请关闭 issue

**Comment by riseast** [comment]
jumpserver，coco，luna 三个镜像单独运行，问题已解决
