### ISSUE TITLE
[Bug] ValueError: Invalid IPv6 URL异常错误

### ISSUE THREAD

**Issue by SnailProbe** [jumpserver/jumpserver#8817]
离线版本：jumpserver-offline-installer-v2.25.2-amd64-67.tar.gz
执行命令：./jmsctl.sh init_db
Creating jms_core ... done
Traceback (most recent call last):
  File "./jms", line 21, in <module>
    django.setup()
......
 File "/usr/local/lib/python3.8/site-packages/django_redis/pool.py", line 72, in connect
    connection = self.get_connection(params)
  File "/usr/local/lib/python3.8/site-packages/django_redis/pool.py", line 91, in get_connection
    pool = self.get_or_create_connection_pool(params)
  File "/usr/local/lib/python3.8/site-packages/django_redis/pool.py", line 112, in get_or_create_connection_pool
    self._pools[key] = self.get_connection_pool(params)
  File "/usr/local/lib/python3.8/site-packages/django_redis/pool.py", line 125, in get_connection_pool
    pool = self.pool_cls.from_url(**cp_params)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1271, in from_url
    url_options = parse_url(url)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1165, in parse_url
    url = urlparse(url)
  File "/usr/local/lib/python3.8/urllib/parse.py", line 376, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/lib/python3.8/urllib/parse.py", line 474, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
[ERROR] 表结构变更失败!
看错误应该是redis连接失败了
ping了以下redis，做了映射的（通的）
PING redis (10.10.122.182) 56(84) bytes of data.
64 bytes from redis (10.10.122.182): icmp_seq=1 ttl=64 time=0.724 ms
64 bytes from redis (10.10.122.182): icmp_seq=2 ttl=64 time=0.289 ms
配置文件
##  MySQL 配置, USE_EXTERNAL_MYSQL=1 表示使用外置 MySQL, 请输入正确的 MySQL 信息
USE_EXTERNAL_MYSQL=1
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD='QbQv.(^#128>&51'
DB_NAME=jumpserver
##  Redis 配置, USE_EXTERNAL_REDIS=1 表示使用外置 Redis, 请输入正确的 Redis 信息
USE_EXTERNAL_REDIS=1
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD='QbQv.A[xq9156@f'

**Comment by ibuler** [comment]
账号密码不要贴出来

**Comment by ibuler** [comment]
从上面来看，应该是密码特殊字符导致的

**Comment by SnailProbe** [comment]
> 账号密码不要贴出来

密码不是真实的，做了修改才发布的，但是复杂度是一样的

**Comment by SnailProbe** [comment]
> 从上面来看，应该是密码特殊字符导致的

因为找不到原因，被迫无奈目前使用了docker容器的mysql和redis镜像，以此来解决该问题

**Comment by wojiushixiaobai** [comment]
容器里面也要做 DNS 解析，或者指向公共 DNS
