### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by aborover** [jumpserver/jumpserver#8887]
2.26安装包离线安装的时候到数据库那报错过不去，哪位有时间请帮忙指导一下看看啥原因？
系统是debian 11
安装选择了外置数据库，没有选择redis
```
Recreating jms_redis ... done
Creating jms_core    ... done
2022-09-22 17:04:32 Collect static files
2022-09-22 17:04:33 Collect static files done
2022-09-22 17:04:33 Check database structure change ...
2022-09-22 17:04:33 Migrate model change to database ...
2022-09-22 17:04:34 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on '10.10.10.200' (115)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./jms", line 86, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on '10.10.10.200' (115)")
[ERROR] Failed to change the table structure!

```

**Comment by wojiushixiaobai** [comment]
错误已经明确告知 `Can't connect to MySQL server on '10.10.10.200' (115)`
请自行确定你的容器是否可以连接到你的 mysql
```sh
docker exec -it jms_core bash
mysql -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD $DB_NAME
```
![image](https://user-images.githubusercontent.com/24326988/191897772-1f181c44-80ac-4729-bbb3-cedf780c4858.png)

**Comment by aborover** [comment]
> 错误已经明确告知 `Can't connect to MySQL server on '10.10.10.200' (115)` 请自行确定你的容器是否可以连接到你的 mysql
> 
> ```shell
> docker exec -it jms_core bash
> mysql -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD $DB_NAME
> ```
> 
> ![image](https://user-images.githubusercontent.com/24326988/191897772-1f181c44-80ac-4729-bbb3-cedf780c4858.png)

我是全新安装的，安装脚本没有让容器运行起来，我看文档里也没有配置jumpserver/mariadb的参数 ，运行docker ps -a没有一个一个创建成功的。镜像倒是都拉取到了
```
root@debian:/home/fort# docker images
REPOSITORY           TAG       IMAGE ID       CREATED         SIZE
jumpserver/koko      v2.26.0   e470cfd25d88   7 days ago      770MB
jumpserver/lion      v2.26.0   6ffe7ce10d52   7 days ago      344MB
jumpserver/magnus    v2.26.0   db4882f1d2b6   7 days ago      159MB
jumpserver/web       v2.26.0   014f34bbfa94   7 days ago      418MB
jumpserver/core      v2.26.0   cae9ec3e0404   8 days ago      1.84GB
jumpserver/redis     6.2       d63965480619   9 months ago    113MB
jumpserver/mariadb   10.6      254214175aa9   10 months ago   410MB
root@debian:/home/fort# docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@debian:/home/fort# 

```

**Comment by wojiushixiaobai** [comment]
你使用的是外置数据库，请在出现 `Can't connect to MySQL server on '10.10.10.200' (115)` 的时候执行我上面发送的命令
