### ISSUE TITLE
[Bug] 2.26.1 安装初始化失败

### ISSUE THREAD

**Issue by liangsuilong** [jumpserver/jumpserver#8909]
**JumpServer 版本(v1.5.9以下不再支持)**
2.26.1

**浏览器版本**

**Bug 描述**
执行安装命令初始化报错。
<img width="1041" alt="Screen Shot 2022-09-27 at 15 00 50" src="https://user-images.githubusercontent.com/152888/192456634-fafc18e1-8f3e-4fbc-8dfb-b9840b6a5c55.png">

**Bug 重现步骤(有截图更好)**
1.  下载 jumpserver-installer-v2.26.1.tar.gz
2.  解压压缩包
3. 执行 ./jmsctl.sh install
4. 到初始化系统的步骤时出现以下报错。

5. Configure External Port
Do you need to customize the JumpServer external port? (y/n)  (default n): 
complete

6. Init JumpServer Database
jms_redis is up-to-date
jms_mysql is up-to-date
Creating jms_core ... 
Creating jms_core ... done
Traceback (most recent call last):
  File "./jms", line 21, in <module>
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 124, in create
    mod = import_module(mod_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/channels/apps.py", line 4, in <module>
    import daphne.server
  File "/usr/local/lib/python3.8/site-packages/daphne/server.py", line 5, in <module>
    from twisted.internet import asyncioreactor  # isort:skip
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py", line 19, in <module>
    from twisted.internet.posixbase import (
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 19, in <module>
    from twisted.internet import error, tcp, udp
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 38, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/_newtls.py", line 18, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 42, in <module>
    from OpenSSL.SSL import Connection, Error, SysCallError, WantReadError, ZeroReturnError
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3224, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'
[ERROR] Failed to change the table structure!

**Comment by liangsuilong** [comment]
操作系统是 CentOS 7.9，Kernel 是 5.4.206-200.el7.x86_64。

**Comment by jym503558564** [comment]
正在修复

**Comment by wojiushixiaobai** [comment]
已修复，请重新更新镜像即可。
```sh
docker pull jumpserver/core:v2.26.1
```
然后重新安装 
```sh
./jmsctl.sh install
``
