### ISSUE TITLE
0.5.0 最新git pull后资产列表显示问题

### ISSUE THREAD

**Issue by qiushaohu** [jumpserver/jumpserver#905]
[简述你的问题]
2018-01-09 17:03 更新后 资产列表显示异常
##### 使用版本
[Jumpserver版本 0.5.0]

##### 问题复现步骤
![image](https://user-images.githubusercontent.com/34025457/34715019-34288e3e-f566-11e7-8f53-5b495563c592.png)
![image](https://user-images.githubusercontent.com/34025457/34715028-3c0481f8-f566-11e7-82c7-3e38b634b1c8.png)
![image](https://user-images.githubusercontent.com/34025457/34715040-44d55b54-f566-11e7-9978-d69cb5956268.png)
![image](https://user-images.githubusercontent.com/34025457/34715047-493ab5c2-f566-11e7-9159-0bac1de5f3bf.png)

后台日志如下：
127.0.0.1 [09/Jan/2018:17:36:31 +0800] "POST /api/terminal/v1/terminal/status/ HTTP/1.1" 201 2
127.0.0.1 [09/Jan/2018:17:36:32 +0800] "GET /assets/asset/ HTTP/1.0" 200 21126
2018-01-09 17:36:32 [exception ERROR] Internal Server Error: /api/assets/v1/assets/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/py3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/serializers.py", line 738, in data
    ret = super(ListSerializer, self).data
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/serializers.py", line 656, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/serializers.py", line 656, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/serializers.py", line 500, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/opt/py3/lib/python3.6/site-packages/rest_framework/fields.py", line 1816, in to_representation
    return method(value)
  File "/opt/jumpserver/apps/assets/serializers.py", line 181, in get_cluster_name
    return obj.cluster.name
AttributeError: 'NoneType' object has no attribute 'name'
127.0.0.1 [09/Jan/2018:17:36:33 +0800] "GET /api/assets/v1/assets/?_=1515490558770 HTTP/1.0" 500 18389
  
================================================================
2018-01-09 21:09

问题复现，批量导入资产，模板csv文件中不填集群即会出现以上现象。
结果是  页面显示导入失败，实际数据库assets_asset表中已添加了数据
![1](https://user-images.githubusercontent.com/34025457/34722642-a49327c6-f582-11e7-8926-1a5c2db9580b.png)
![2](https://user-images.githubusercontent.com/34025457/34722657-b009dcb2-f582-11e7-8fc4-b12ea154f722.png)

mysql> select count(*) from assets_asset;
+----------+
| count(*) |
+----------+
|       20 |
+----------+
1 row in set (0.00 sec)

后续再点资产列表  就会出现上面描述的现象及日志。

**Comment by ibuler** [comment]
没有设置cluster导致的，已fix, cluster为必选
