### ISSUE TITLE
[Bug] helm部署2.28.1版本，部分组件启动失败

### ISSUE THREAD

**Issue by build-z** [jumpserver/jumpserver#9116]
**Bug 描述**

helm部署jumpserver2.28.1后，core组件有报错，celery组件健康检查不通过
**Bug 重现步骤(有截图更好)**
1.celery组件不停健康检查失败，一直重启
![celery异常](https://user-images.githubusercontent.com/57315512/203563051-2ec80b79-cf4b-4771-b129-c45409ef438f.png)

2. core组件日志一直打印错误
![core异常](https://user-images.githubusercontent.com/57315512/203563195-efd1fa94-7577-4520-ad90-961a13aff163.png)

**Comment by build-z** [comment]
`Traceback (most recent call last):
  File "start_celery_beat.py", line 81, in <module>
    main()
  File "start_celery_beat.py", line 73, in main
    with redis_lock.Lock(redis_client, name="beat-distribute-start-lock", expire=60, auto_renewal=True):
  File "/usr/local/lib/python3.8/site-packages/redis_lock/__init__.py", line 341, in __enter__
    acquired = self.acquire(blocking=True)
  File "/usr/local/lib/python3.8/site-packages/redis_lock/__init__.py", line 249, in acquire
    timed_out = not self._client.blpop(self._signal, blpop_timeout) and timeout
  File "/usr/local/lib/python3.8/site-packages/redis/commands/core.py", line 2467, in blpop
    return self.execute_command("BLPOP", *keys)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1235, in execute_command
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1239, in <lambda>
    lambda error: self._disconnect_raise(conn, error),
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1225, in _disconnect_raise
    raise error
  File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1236, in <lambda>
    lambda: self._send_command_parse_response(
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1212, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1251, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 822, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.`

这是beat.log的内容，redis需要配置什么吗，使用外部redis，没有密码

**Comment by wojiushixiaobai** [comment]
可以设置 redis 密码后验证下，redis 版本需要大于等于 5.0

**Comment by build-z** [comment]
redis设置密码后程序启动正常
