### ISSUE TITLE
[Bug] v2.25.3升级v2.28.1报错

### ISSUE THREAD

**Issue by vinkdong** [jumpserver/jumpserver#9131]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.25.3 升级 v2.28.1

**浏览器版本**
无

**Bug 描述**
```
5. Apply database changes
Changing database schema may take a while, please wait patiently
WARNING: Found orphan containers (jms_lb) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
jms_mysql is up-to-date
jms_redis is up-to-date
Creating jms_core ... done
2022-11-30 11:22:39 Collect static files
2022-11-30 11:22:40 Collect static files done
2022-11-30 11:22:40 Check database structure change ...
2022-11-30 11:22:40 Migrate model change to database ...
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying applications.0024_alter_application_type... OK
  Applying assets.0092_commandfilter_nodes...2022-11-30 11:22:40 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1822, "Failed to add the foreign key constaint. Missing index for constraint 'assets_commandfilter_commandfilter_id_78504779_fk_assets_co' in the referenced table 'assets_commandfilter'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./jms", line 87, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 230, in apply_migration
    migration_recorded = True
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 118, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1822, "Failed to add the foreign key constaint. Missing index for constraint 'assets_commandfilter_commandfilter_id_78504779_fk_assets_co' in the referenced table 'assets_commandfilter'")
[ERROR] Failed to change the table structure!
```

**Bug 重现步骤(有截图更好)**
1.  执行 `./jmsctl.sh upgrade`
2.  开始提示外键报错 `Foreign key constraint is incorrectly formed`
3.  禁用外键约束 重新升级，提示如上

**Comment by wojiushixiaobai** [comment]
如果数据库里面包含多种不一样的排序规则依旧会报错
- [Cannot add foreign key constraint](https://github.com/jumpserver/jumpserver/issues/9131)
```bash
# 通过 grep 检查 sql 文件
mysqldump -uroot -p jumpserver > jumpserver.sql

# 检查字符集, 如果都返回 utf8 则无问题
grep -r "DEFAULT CHARSET=" jumpserver.sql

# 检查排序规则，正常情况下返回都是空或者唯一
grep -r "COLLATE=" jumpserver.sql
grep -r "COLLATE " jumpserver.sql

# 如果上述结果不一致，请手动修正数据库。
```

**Comment by vinkdong** [comment]
通过排查发现，新创建的表 `assets_commandfilter_nodes` 和原来的表COLLATE 不一致导致的，把新表改成utf8mb3_bin后正常升级了
<img width="990" alt="WeChatWorkScreenshot_bbdfba1f-c965-4a50-beb0-0e809a2001bb" src="https://user-images.githubusercontent.com/10599904/204756249-7a245567-dec4-4ffc-9561-b61ffd8b97bb.png">

**Comment by aishang1993** [comment]
> 



> 通过排查发现，新创建的表 `assets_commandfilter_nodes` 和原来的表COLLATE 不一致导致的，把新表改成utf8mb3_bin后正常升级了 <img alt="WeChatWorkScreenshot_bbdfba1f-c965-4a50-beb0-0e809a2001bb" width="990" src="https://user-images.githubusercontent.com/10599904/204756249-7a245567-dec4-4ffc-9561-b61ffd8b97bb.png">

我也遇到了这个问题，我修改assets_commandfilter_nodes表后，启动还是会报错：
```
django.db.utils.OperationalError: (1050, "Table 'assets_commandfilter_nodes' already exists")
```
@wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
@aishang1993 `utf8mb3_bin` 是根据你的实际排序规则修改的，不一定是  `utf8mb3_bin`

**Comment by aishang1993** [comment]
> 

我把数据库默认的字符集由utf8mb4 变更为utf8mb3，再把assets_commandfilter_nodes 表删除后，再启动就好了，因为之前的表都是 utf8mb3的。😄
