### ISSUE TITLE
[Bug] 使用helm部署jumpserver，jumpserver-jms-celery一直不断重启，但是能正常使用

### ISSUE THREAD

**Issue by PayneRose** [jumpserver/jumpserver#9186]
容器日志：
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.8/logging/config.py", line 744, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/opt/jumpserver/logs/ansible.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "jms", line 21, in <module>
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.8/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/local/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'ansible_logs'

**Comment by PayneRose** [comment]
版本是：v2.28.1

**Comment by wojiushixiaobai** [comment]
`Read-only file system: '/opt/jumpserver/logs/ansible.log'`
存储需要支持共同读写，`RWX`

**Comment by wojiushixiaobai** [comment]
当前版本需要这样，我们将在后续的版本优化此问题
