### ISSUE TITLE
[Bug] 升级到 2.28.4 系统用户相关 报500错误

### ISSUE THREAD

**Issue by 502647092** [jumpserver/jumpserver#9211]
**JumpServer 版本(v1.5.9以下不再支持)**
2.28.4

**浏览器版本**

**Bug 描述**
升级到 2.28.4 无法连接终端
日志提示 获取系统用户 500错误
![F`7F$7U( _A`E 08I`(%A)T](https://user-images.githubusercontent.com/10203793/207765114-924c6662-542f-4958-8d32-91316a2ba2d9.png)
直接打开系统用户页面 也提示500错误

**Bug 重现步骤(有截图更好)**
1. 升级到 2.28.4
2. 打开系统用户页面
3. 
![image](https://user-images.githubusercontent.com/10203793/207765227-b6fdafa6-a6c4-45f4-83ae-68aaa6cc6c95.png)

**Comment by LeeEirc** [comment]
到 core 的目录看下日志。

**Comment by 502647092** [comment]
报错相关日志

```
2022-12-15 13:40:41 [log ERROR] Internal Server Error: /api/v1/assets/system-users/05a9e0d8-d6f3-4420-acaf-42ff70b1b5b6/
Traceback (most recent call last):
  File "/opt/py3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/py3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/py3/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/serializers.py", line 509, in to_representation
    attribute = field.get_attribute(instance)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/opt/py3/lib/python3.8/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
  File "/opt/jumpserver/apps/assets/models/base.py", line 77, in ssh_key_fingerprint
    fingerprint = public_key_obj.hash_md5()
  File "/opt/py3/lib/python3.8/site-packages/sshpubkeys/keys.py", line 160, in hash_md5
    fp_plain = hashlib.md5(self._decoded_key).hexdigest()
TypeError: object supporting the buffer API required

```

**Comment by 502647092** [comment]
清空数据库系统用户表后 重新添加 问题解决 应该是历史的数据没办法解析 报错导致的

**Comment by wojiushixiaobai** [comment]
非 ssh 协议的系统用户 **assets_systemuser**，**public_key** 和 **private_key** 应该为空
