### ISSUE TITLE
0.3.2版本 迁移问题

### ISSUE THREAD

**Issue by EverCurse** [jumpserver/jumpserver#922]
[简述你的问题]

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2]

##### 问题复现步骤
请问现在跳板机迁移机器的话有没有具体的迁移步骤呢？或者说需要注意的地方。
谢谢。感谢jumpserver团队的贡献

**Comment by wojiushixiaobai** [comment]
环境撘好，然后覆盖数据库不就完了吗老哥？？？虚拟环境的话可以尝试复制镜像，或者使用 docker 

自己可以先测试一下看下遇到什么问题再来问的话会更好一点。

**Comment by EverCurse** [comment]
@wojiushixiaobai  代码目录直接拷贝的 python的依赖也解决了。现在就是测试 重新下发了key 登录选择机器




Only match Host:  xxxx
Connecting xxxxx ...
Traceback (most recent call last):
  File "/data/Highso_jumpserver/connect.py", line 817, in <module>
    main()
  File "/data/Highso_jumpserver/connect.py", line 808, in main
    nav.try_connect()
  File "/data/Highso_jumpserver/connect.py", line 560, in try_connect
    ssh_tty.connect()
  File "/data/Highso_jumpserver/connect.py", line 397, in connect
    ssh = self.get_connection()
  File "/data/Highso_jumpserver/connect.py", line 239, in get_connection
    look_for_keys=False)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 367, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 505, in _auth
    key = pkey_class.from_private_key_file(key_filename, password)
  File "/usr/lib/python2.7/site-packages/paramiko/pkey.py", line 184, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/lib/python2.7/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/lib/python2.7/site-packages/paramiko/rsakey.py", line 165, in _from_private_key_file
    data = self._read_private_key_file('RSA', filename, password)
  File "/usr/lib/python2.7/site-packages/paramiko/pkey.py", line 255, in _read_private_key_file
    with open(filename, 'r') as f:
IOError: [Errno 13] Permission denied: u'/data/Highso_jumpserver/keys/user/xxxx_ops.pem'
Connection to xxxxclosed.

**Comment by wojiushixiaobai** [comment]
@EverCurse 老哥，推送已经成功了吗？

**Comment by EverCurse** [comment]
@wojiushixiaobai  老铁 成功了，每个用户重新生成密钥就好了。非常感谢
