### ISSUE TITLE
0.5版本发邮件报错

### ISSUE THREAD

**Issue by testueu** [jumpserver/jumpserver#923]
[简述你的问题]

##### 使用版本
0.5

##### 问题复现步骤
发送邮件的时候日子报错

Task accepted: common.tasks.send_mail_async[fcbd65c9-76c6-461a-8d6d-30bc56d65b00] pid:23281
Task common.tasks.send_mail_async[fcbd65c9-76c6-461a-8d6d-30bc56d65b00] raised unexpected: TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'",)
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/jumpserver/jumpserver/apps/common/tasks.py", line 26, in send_mail_async
    args[0] = settings.EMAIL_SUBJECT_PREFIX + args[0]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
172.16.11.195 [16/Jan/2018:16:55:35 +0800] "PATCH /api/users/v1/users/4ac99e58-babf-4d9d-b9f2-fa896e09c3f9/password/reset/ HTTP/1.1" 200 548

[注:] 完成后请关闭 issue

**Comment by testueu** [comment]
请问在哪里可以下再0.3版本的jumpserver

**Comment by ibuler** [comment]
查看tag

**Comment by ibuler** [comment]
CONFIG中设置 EMAIL_SUBJECT_PREFIX="[Jumpserver] "
