### ISSUE TITLE
[Bug] redis密码中带有特殊字符，执行初始化命令后报错`WRONGPASS invalid username-password pair`

### ISSUE THREAD

**Issue by wang-xiaowu** [jumpserver/jumpserver#9266]
**JumpServer 版本(v1.5.9以下不再支持)**
latest

**浏览器版本**

**Bug 描述**
redis密码中带有特殊字符，执行初始化命令后报错`WRONGPASS invalid username-password pair`

**Bug 重现步骤(有截图更好)**
Docker方式, redis密码带有#和@还有*
```
[root@VM-30-197-centos jumpserver]# docker exec -i jms_core bash -c './jms upgrade_db'
Traceback (most recent call last):
  File "./jms", line 21, in <module>
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 15, in ready
    django_ready.send(CommonConfig)
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/jumpserver/apps/orgs/signal_handlers/common.py", line 48, in subscribe_orgs_mapping_expire
    orgs_mapping_for_memory_pub_sub.subscribe(
  File "/opt/jumpserver/apps/common/utils/connection.py", line 29, in subscribe
    ps.subscribe(self.ch)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1589, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1430, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1383, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 621, in connect
    self.on_connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 711, in on_connect
    auth_response = self.read_response()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 837, in read_response
    raise response
redis.exceptions.ResponseError: WRONGPASS invalid username-password pair
```

**Comment by wojiushixiaobai** [comment]
`#` 应该不行，`@` 和 `*` 应该可以

**Comment by wang-xiaowu** [comment]
> `#` 应该不行，`@` 和 `*` 应该可以

有解决办法么

**Comment by wojiushixiaobai** [comment]
先修改你的密码或者使用内置 redis，后续我们看看能否优化

**Comment by wang-xiaowu** [comment]
> 用内置 redis，后续我们看看能否优化

请问redis仅是用作缓存么？如果现在使用内置redis，后续迁移的话需要考虑迁移redis数据么

**Comment by wojiushixiaobai** [comment]
仅缓存，无需要持久化数据。

**Comment by wang-xiaowu** [comment]
最新版目前对于该问题还是没解决：
版本：3.10.0
错误：`REDIS_PASSWORD='J*#36@us.tin'` => `ValueError: Port could not be cast to integer value as 'J*'`
