### ISSUE TITLE
[Question] koko假死，ssh连不上资产

### ISSUE THREAD

**Issue by 7cristiano** [jumpserver/jumpserver#9277]
**请描述您的问题.**
之前一直正常使用中，突然ssh连不上资产。期间发现日志有这些打印。重启koko后恢复

2023-01-05 07:29:08 [manager DEBUG] Distinct asset user queryset
2023-01-05 07:29:08 [base ERROR] No record found(org is DEFAULT)
Traceback (most recent call last):
  File "/opt/jumpserver/apps/assets/models/base.py", line 176, in get_asset_user
    prefer_id=self.id, prefer=self._prefer,
  File "/opt/jumpserver/apps/assets/backends/manager.py", line 98, in get_latest
    return self.get(latest=True, **kwargs)
  File "/opt/jumpserver/apps/assets/backends/manager.py", line 95, in get
    raise ObjectDoesNotExist(msg)
django.core.exceptions.ObjectDoesNotExist: No record found(org is DEFAULT)

**Comment by LeeEirc** [comment]
使用的版本？koko 是否有日志？ 如果是 web 方式，nginx 是否有 proxy 到 koko日志？

**Comment by 7cristiano** [comment]
版本1.5.4
koko只有这些日志
![image](https://user-images.githubusercontent.com/33511216/210739276-cdb213dd-ddf7-4215-8e14-af739846ea82.png)
通过 secureCRT登录的

![image](https://user-images.githubusercontent.com/33511216/210741385-d71e4fff-a0f5-4731-ae8f-03cbe3449ef9.png)
输入资产ID后一直没有反应

**Comment by LeeEirc** [comment]
早期 v1.5 版本可能存在一些 bug，可以升级到相对稳定的 v1.5.9。现在最新的版本是 v2.28了，增加了很多功能，欢迎体验。
