### ISSUE TITLE
数据库编码转化问题

### ISSUE THREAD

**Issue by npcomet** [jumpserver/jumpserver#9289]
**请描述您的问题.**
操作系统为 Ubuntu 22.04.1 LTS
MYSQL 版本为 mysql-server-8.0.31

系统从2.21.4更新到2.28.6 报错如下：
```
2023-01-07 15:42:46 Collect static files
2023-01-07 15:42:47 Collect static files done
2023-01-07 15:42:47 Check database structure change ...
2023-01-07 15:42:47 Migrate model change to database ...
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying applications.0021_auto_20220629_1826... OK
  Applying applications.0022_auto_20220714_1046... OK
  Applying applications.0023_auto_20220715_1556... OK
  Applying applications.0024_alter_application_type... OK
  Applying assets.0091_auto_20220629_1826... OK
  Applying assets.0092_commandfilter_nodes... OK
  Applying assets.0093_alter_systemuser_protocol... OK
  Applying audits.0014_auto_20220505_1902... OK
  Applying audits.0015_auto_20221011_1745... OK
  Applying authentication.0011_auto_20220705_1940...2023-01-07 15:42:48 Perform migrate failed, exit
Traceback (most recent call last):
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3new/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/py3new/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/py3new/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (3780, "Referencing column 'application_id' and referenced column 'id' in foreign key constraint 'authentication_conne_application_id_8a292d07_fk_applicati' are incompatible.")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./jms", line 87, in perform_db_migrate
    management.call_command('migrate')
  File "/opt/py3new/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/opt/py3new/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/py3new/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/py3new/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/py3new/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/mysql/schema.py", line 98, in add_field
    super().add_field(model, field)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 522, in add_field
    self.execute(sql, params)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/py3new/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/py3new/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/py3new/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/py3new/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (3780, "Referencing column 'application_id' and referenced column 'id' in foreign key constraint 'authentication_conne_application_id_8a292d07_fk_applicati' are incompatible.")
```
根据大家反馈问题，找到下面链接，大概确定是编码问题。

https://github.com/jumpserver/jumpserver/issues/6918

执行 “还原为 utf8_general_ci 校对集”
最后发现无效，字符集并未修改，经过对比修改前后数据库发现是 ubuntu 22的新情况。

此版本的默认uft8字符集为 utf8mb3
```
+------------+-----------------------------------------------------------------------------------------------------------+
| Database   | Create Database                                                                                           |
+------------+-----------------------------------------------------------------------------------------------------------+
| jumpserver | CREATE DATABASE `jumpserver` /*!40100 DEFAULT CHARACTER SET utf8mb3 */ /*!80016 DEFAULT ENCRYPTION='N' */ |
+------------+-----------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

所以修改字符集的步骤应该为
```
$ sed -i 's@COLLATE=utf8mb3_bin@@g' jumpserver.sql
$ sed -i 's@COLLATE utf8mb3_bin@@g' jumpserver.sql
```
按照此思路替换后数据库导入失败，提示
```
ERROR 3780 (HY000) at line 25: Referencing column 'loginacl_id' and referenced column 'id' in foreign key constraint 'acls_loginacl_reviewers_loginacl_id_79f293a0_fk_acls_loginacl_id' are incompatible.
```
升级陷入僵局，请帮忙看一下。

**Comment by wojiushixiaobai** [comment]
新建一个一样系统的测试环境
正常部署 jumpserver 后，导出 sql 表结构
然后对比异常的旧环境表结构，手动更新下表结构即可

**Comment by npcomet** [comment]
好的 我尽快测试一下
