### ISSUE TITLE
使用docker compose部署，core和celery始终无法启动

### ISSUE THREAD

**Issue by jumping008** [jumpserver/jumpserver#9342]
我使用docker compose部署 v2.28.0，jms_core和jms_celery 反复重启。查看docker logs jms_core显示如下：

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jms", line 21, in <module>
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 15, in ready
    django_ready.send(CommonConfig)
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/jumpserver/apps/orgs/signal_handlers/common.py", line 48, in subscribe_orgs_mapping_expire
    orgs_mapping_for_memory_pub_sub.subscribe(
  File "/opt/jumpserver/apps/common/utils/connection.py", line 29, in subscribe
    ps.subscribe(self.ch)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1589, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1430, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1383, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 615, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 609, in connect
    sock = self.retry.call_with_retry(
  File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 610, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 675, in _connect
    raise err
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 663, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jms", line 21, in <module>
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 15, in ready
    django_ready.send(CommonConfig)
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/jumpserver/apps/orgs/signal_handlers/common.py", line 48, in subscribe_orgs_mapping_expire
    orgs_mapping_for_memory_pub_sub.subscribe(
  File "/opt/jumpserver/apps/common/utils/connection.py", line 29, in subscribe
    ps.subscribe(self.ch)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1589, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1430, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1383, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 615, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 609, in connect
    sock = self.retry.call_with_retry(
  File "/usr/local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 610, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 675, in _connect
    raise err
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 663, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jms", line 21, in <module>
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/jumpserver/apps/common/apps.py", line 15, in ready
    django_ready.send(CommonConfig)
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/jumpserver/apps/orgs/signal_handlers/common.py", line 48, in subscribe_orgs_mapping_expire
    orgs_mapping_for_memory_pub_sub.subscribe(
  File "/opt/jumpserver/apps/common/utils/connection.py", line 29, in subscribe
    ps.subscribe(self.ch)
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1589, in subscribe
    ret_val = self.execute_command("SUBSCRIBE", *new_channels.keys())
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1430, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1383, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 615, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.

其他组件都正常运行中：

root@NUC:/container/docker-compose/jumpserver# docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS                                  PORTS                NAMES
aff031db3454   jumpserver/magnus:v2.28.0   "./entrypoint.sh"        25 seconds ago   Up 21 seconds                           0-65535/tcp          jms_magnus
369abdf4a34a   jumpserver/lion:v2.28.0     "./entrypoint.sh"        25 seconds ago   Up 22 seconds (health: starting)        4822/tcp, 8081/tcp   jms_lion
75cc97d3352a   redis:6                     "docker-entrypoint.s…"   25 seconds ago   Up 23 seconds                           6379/tcp             jms_redis
32e5f1ea9a38   mariadb:10.5                "docker-entrypoint.s…"   25 seconds ago   Up 22 seconds                           3306/tcp             jms_mysql
c71b966248f8   jumpserver/core:v2.28.0     "./entrypoint.sh sta…"   25 seconds ago   Restarting (1) Less than a second ago                        jms_celery
7d3fdd095a63   jumpserver/core:v2.28.0     "./entrypoint.sh sta…"   25 seconds ago   Restarting (1) Less than a second ago                        jms_core
02be319ee958   jumpserver/web:v2.28.0      "/docker-entrypoint.…"   25 seconds ago   Up 23 seconds                           80/tcp               jms_web
dfdb026ec03b   jumpserver/koko:v2.28.0     "./entrypoint.sh"        25 seconds ago   Up 22 seconds                           2222/tcp, 5000/tcp   jms_koko
8b1f1bac9c12   wiznote/wizserver           "bash /wiz/app/entry…"   12 hours ago     Up 12 hours                                                  wiz

我的系统是root@NUC:/container/docker-compose/jumpserver# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

docker-compose版本
root@NUC:/container/docker-compose/jumpserver# docker-compose version
Docker Compose version v2.15.1

**Comment by wojiushixiaobai** [comment]
redis 未正确配置，请仔细检查部署步骤
