### ISSUE TITLE
jumpserver04 启动问题

### ISSUE THREAD

**Issue by zhangshuaiming** [jumpserver/jumpserver#939]
[简述你的问题]
run_server.py: error: the following arguments are required: services
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.4.0]
0.4.0

##### 问题复现步骤
1. [步骤1]
2. [步骤2]

##### 其他

[注:] 完成后请关闭 issue

**Comment by wojiushixiaobai** [comment]
run_server.py all

**Comment by zhangshuaiming** [comment]
Thu Jan 18 14:24:52 2018
Jumpserver version 0.5.0, more see https://www.jumpserver.org
Quit the server with CONTROL-C.
- Start Gunicorn WSGI HTTP Server
Check database change, make migrations
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'jumpserver.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named django_auth_ldap.config
Collect static files
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'jumpserver.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named django_auth_ldap.config
- Start Celery as Distributed Task Queue
- Start Beat as Periodic Task Scheduler
/bin/sh: gunicorn: 未找到命令


########################################  ERROR OCCUR  ########################################
Start service gunicorn [FAILED]
Exited

**Comment by zhangshuaiming** [comment]
我已经pip安装了requirements.txt

**Comment by wojiushixiaobai** [comment]
@zhangshuaiming 

Python 环境换 3.6

**Comment by zhangshuaiming** [comment]
@wojiushixiaobai   我是用换车3.6 也是这样的

**Comment by wojiushixiaobai** [comment]
@zhangshuaiming  发图和 log

**Comment by zhangshuaiming** [comment]
<img width="1334" alt="qq20180118-144355 2x" src="https://user-images.githubusercontent.com/19390230/35084274-2966e30c-fc5e-11e7-880c-8a3b697bbedc.png">

**Comment by zhangshuaiming** [comment]
https://github.com/jumpserver/jumpserver/blob/dev/docs/install.md是这个，还有能不能从0.3升级到0.4，或者docker镜像有没有

**Comment by wojiushixiaobai** [comment]
@zhangshuaiming  docker 镜像有，但是版本可能不是最新（没有测试，你可以尝试一下）
0.3和0.4的数据库结构不一样，需要自己修改导入，所以不能直接升级。

**Comment by zhangshuaiming** [comment]
@wojiushixiaobai  0.3版本的数据库和0.4版本是通用吗

**Comment by zhangshuaiming** [comment]
那之前的数据就没有了

**Comment by wojiushixiaobai** [comment]
@zhangshuaiming 自己写个脚本处理一下（对比新旧数据库结构，导入旧数据应该可以，建议先测试）

**Comment by zhangshuaiming** [comment]
@wojiushixiaobai  好的
