### ISSUE TITLE
jumpserver V2.28.6  got problems during install requirements file

### ISSUE THREAD

**Issue by typesky** [jumpserver/jumpserver#9391]
**请描述您的问题.**
During I installed jumpserver  2.28.6 , I met some problems when I use "pip3 install -r requirements/requirements.txt" command ,  does anyone can fix it  please ? 

**here is the error info :**
Collecting python-ldap==3.4.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/41/e2/6b12190c171b78d1cd8c9d0d3380d18b85959aecb2b1267f7bdd5b66cd8f/python-ldap-3.4.0.tar.gz (376 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-y6rde613/python_ldap.egg-info
      writing /tmp/pip-modern-metadata-y6rde613/python_ldap.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-y6rde613/python_ldap.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-y6rde613/python_ldap.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-y6rde613/python_ldap.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-y6rde613/python_ldap.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-y6rde613/python_ldap.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      /tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      no previously-included directories found matching 'Doc/.build'
      adding license file 'LICENCE'
      writing manifest file '/tmp/pip-modern-metadata-y6rde613/python_ldap.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-y6rde613/python_ldap-3.4.0.dist-info'
      Traceback (most recent call last):
        File "/apps/python3/jumpserver_env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/apps/python3/jumpserver_env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/apps/python3/jumpserver_env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 60, in <module>
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/command/dist_info.py", line 101, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 958, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
          module = import_module(match.group('module'))
        File "/apps/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 843, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-69ay4hav/overlay/lib/python3.8/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/apps/python3/lib/python3.8/ctypes/__init__.py", line 7, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

============================================================
**another error  hapened when  I commented python-ldap ,here is the error**

Collecting xmlsec>=1.0.5
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/37/9f/342d4562eac99178d0d515c780285e107c6828cefad37d02f05b7b7d8751/xmlsec-1.3.13.tar.gz (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.6/64.6 kB 134.8 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-l6l4icl6/xmlsec.egg-info
      writing /tmp/pip-modern-metadata-l6l4icl6/xmlsec.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-l6l4icl6/xmlsec.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-l6l4icl6/xmlsec.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-l6l4icl6/xmlsec.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-l6l4icl6/xmlsec.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-l6l4icl6/xmlsec.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching '*/__pycache__'
      no previously-included directories found matching '.github'
      no previously-included directories found matching 'doc'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.travis.yml'
      warning: no previously-included files found matching '.gitattributes'
      warning: no previously-included files found matching '.gitignore'
      warning: no previously-included files found matching 'requirements-test.txt'
      warning: no previously-included files found matching 'requirements.txt'
      warning: no previously-included files found matching 'xmlsec_extra.py'
      warning: no previously-included files found matching 'xmlsec_setupinfo.py'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-l6l4icl6/xmlsec.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-l6l4icl6/xmlsec-1.3.13.dist-info'
      Traceback (most recent call last):
        File "/apps/python3/jumpserver_env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/apps/python3/jumpserver_env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/apps/python3/jumpserver_env/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 501, in <module>
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/command/dist_info.py", line 101, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 958, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
          module = import_module(match.group('module'))
        File "/apps/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 843, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-qj0wgn4y/overlay/lib/python3.8/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/apps/python3/lib/python3.8/ctypes/__init__.py", line 7, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**I have tried many ways to fix that  but still problems remain**

**Comment by typesky** [comment]
env: 
os: almalinux8
python: 3.8.12
mysql 8.0
redis 6.2

**Comment by wojiushixiaobai** [comment]
`ModuleNotFoundError: No module named '_ctypes'`



```sh
# debian
apt-get install libffi-dev

# redhat
yum install libffi-devel
```
