### ISSUE TITLE
关于web terminal 的问题。

### ISSUE THREAD

**Issue by airforce-captain** [jumpserver/jumpserver#956]
[简述你的问题]

使用web terminal ，如果不使用退出命令直接关闭浏览器的话，terminal会话就无法操作了，始终显示是在线状态，点击terminal 也没有动作。

##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]

0.5.0

##### 问题复现步骤
1. [步骤1]
 登陆操作完了后，不执行exit , 直接关闭断开。

2. [步骤2]
重新打开一个web terminal .

##### 具体表现[截图可能会更好些,最好能截全]

服务器日志会报错：

```
Exception in thread Thread-515:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/app.py", line 130, in heartbeat
    self.handle_task(tasks)
  File "/opt/coco/coco/app.py", line 142, in handle_task
    self.task_handler.handle(task)
  File "/opt/coco/coco/tasks.py", line 35, in handle
    self.handle_kill_session(task)
  File "/opt/coco/coco/tasks.py", line 30, in handle_kill_session
    session.terminate()
  File "/opt/coco/coco/session.py", line 109, in terminate
    self.client.send(msg)
  File "/opt/coco/coco/models.py", line 46, in send
    return self.chan.send(b)
OSError: [Errno 9] Bad file descriptor
```

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
该bug再修复中
