### ISSUE TITLE
ssh登陆后输入错误命令会卡死

### ISSUE THREAD

**Issue by yaoluoye** [jumpserver/jumpserver#958]
[简述你的问题]
在终端(非web)通过ssh登陆，输入错误命令会卡死，比如退出时没有输入“q”，而是输入一个exit
后台报错
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/sshd.py", line 96, in handle_chan
    self.dispatch(client)
  File "/opt/coco/coco/sshd.py", line 102, in dispatch
    InteractiveServer(self.app, client).interact()
  File "/opt/coco/coco/interactive.py", line 296, in interact
    rv = self.dispatch(opt)
  File "/opt/coco/coco/interactive.py", line 138, in dispatch
    self.search_and_proxy(opt)
  File "/opt/coco/coco/interactive.py", line 275, in search_and_proxy
    if len(self.search_result) == 1:
TypeError: object of type 'NoneType' has no len()

##### 使用版本
0.5.0 master

**Comment by yaoluoye** [comment]
1.0版本已修正
