### ISSUE TITLE
远程主机FreeBSD 8无法获取资产信息.

### ISSUE THREAD

**Issue by airforce-captain** [jumpserver/jumpserver#965]
[简述你的问题]

FreeBSD 8机器无法获取资产信息.

远程freebsd 的python版本:
```
Python 2.7.10 (default, Jul 31 2015, 03:37:44) 
[GCC 4.2.1 20070831 patched [FreeBSD]] on freebsd8
```
##### 使用版本
[请提供你使用的Jumpserver版本 0.3.2 或 0.5.0]
0.5.0

##### 问题复现步骤
1. [步骤1]
添加资产机器.
2. [步骤2]
更新硬件信息.

##### 具体表现[截图可能会更好些,最好能截全]
```
2018-01-26 15:26:37 [exception ERROR] Internal Server Error: /api/assets/v1/assets/8eb3d51e-516c-44d0-8644-74ee325fb29f/refresh/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/rest_framework/generics.py", line 210, in get
    return self.retrieve(request, *args, **kwargs)
  File "/opt/jumpserver/apps/assets/api.py", line 236, in retrieve
    summary = update_asset_hardware_info_manual(asset)[1]
  File "/usr/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python3.6/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/assets/tasks.py", line 108, in update_asset_hardware_info_manual
    return update_assets_hardware_info_util([asset], task_name=task_name)
  File "/usr/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python3.6/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/assets/tasks.py", line 101, in update_assets_hardware_info_util
    assets_updated = set_assets_hardware_info(result)
  File "/usr/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python3.6/site-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/assets/tasks.py", line 58, in set_assets_hardware_info
    ___cpu_cores = info['ansible_processor_cores']
KeyError: 'ansible_processor_cores'
```

**Comment by airforce-captain** [comment]
kvm 虚拟机也获取不到cpu和硬盘.
![jms_vm](https://user-images.githubusercontent.com/16110498/35429901-0085203a-02b1-11e8-91a4-6103ddb3e22c.png)

**Comment by ibuler** [comment]
fixed
