### ISSUE TITLE
[Question] 按照文档操作，出现如下错误，求解

### ISSUE THREAD

**Issue by Oliver-yangyang** [jumpserver/jumpserver#9685]
**请描述您的问题.**
Traceback (most recent call last):
  File "/jumpserver/jumpserver/apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/jumpserver/jmp_venv1/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/jumpserver/jmp_venv1/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/jumpserver/jmp_venv1/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/jumpserver/jmp_venv1/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/jumpserver/jmp_venv1/lib/python3.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/jumpserver/python_rpm/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/jumpserver/jumpserver-v2.1.0/apps/ops/__init__.py", line 1, in <module>
    from .celery import app as celery_app
  File "/jumpserver/jumpserver-v2.1.0/apps/ops/celery/__init__.py", line 5, in <module>
    from kombu import Exchange, Queue
ImportError: cannot import name 'Exchange' from 'kombu' (/jumpserver/jmp_venv1/lib/python3.7/site-packages/kombu/__init__.py)

**Comment by wojiushixiaobai** [comment]
python 版本不符合要求

**Comment by Oliver-yangyang** [comment]
你的意思是要装python3.8吗

**Comment by Oliver-yangyang** [comment]
我装的jumpserver版本是v2.1.0

**Comment by BaiJiangJie** [comment]
使用最新版本安装一下，有一些依赖没有安装成功。

**Comment by xibolun** [comment]
若依赖配置了ansible==7.x 需要使用python 3.9以上的版本；
https://groups.google.com/g/ansible-project/c/y6eFBK3f0HE
