### ISSUE TITLE
启动coco时报错，没有jms的module（ModuleNotFoundError: No module named 'jms'）。

### ISSUE THREAD

**Issue by buguoqiang** [jumpserver/jumpserver#972]
启动coco时报错，没有jms的module。

##### 使用版本
0.5.0

##### 问题复现步骤
1. 安装完jumpserver，可以正常运行。
2. 安装coco的过程中，无法启动coco。

##### 具体表现[截图可能会更好些,最好能截全]
(py3) [root@localhost coco]# python run_server.py 
Traceback (most recent call last):
  File "run_server.py", line 8, in <module>
    from coco import Coco
  File "/opt/coco/coco/__init__.py", line 5, in <module>
    from .app import Coco
  File "/opt/coco/coco/app.py", line 12, in <module>
    from jms.service import AppService
ModuleNotFoundError: No module named 'jms'

##### 其他

[注:] 完成后请关闭 issue

**Comment by ibuler** [comment]
没有安装 jumpserver-python-sdk库  https://pypi.org/project/jumpserver-python-sdk/，它在requirements中

**Comment by buguoqiang** [comment]
谢谢，pip显示确实未安装此sdk。可是还是无法安装这个sdk。

(py3) [root@localhost requirements]# pip install jumpserver-python-sdk
Collecting jumpserver-python-sdk
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0a/fe/348265e560bcc7fe2be677c45a54315e208bb826a25e0c7b8212fc1a759c/jumpserver-python-sdk-0.0.27.tar.gz
Collecting paramiko==2.4.0s (from jumpserver-python-sdk)
  Could not find a version that satisfies the requirement paramiko==2.4.0s (from jumpserver-python-sdk) (from versions: 0.1-bulbasaur, 0.1-charmander, 0.9-doduo, 0.9-eevee, 0.9-fearow, 0.9-gyarados, 0.9-horsea, 0.9-ivysaur, 1.0, 1.1, 1.2, 1.3, 1.3.1, 1.4, 1.5.1, 1.5.2, 1.5.4, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.7, 1.7.1, 1.7.2, 1.7.4, 1.7.5, 1.7.6, 1.7.7.1, 1.7.7.2, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.12.0, 1.12.1, 1.12.2, 1.12.3, 1.12.4, 1.13.0, 1.13.1, 1.13.2, 1.13.3, 1.13.4, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0)
No matching distribution found for paramiko==2.4.0s (from jumpserver-python-sdk)
(py3) [root@localhost requirements]# pip install paramiko
Requirement already satisfied: paramiko in /opt/py3/lib/python3.6/site-packages
Requirement already satisfied: pynacl>=1.0.1 in /opt/py3/lib/python3.6/site-packages (from paramiko)
Requirement already satisfied: pyasn1>=0.1.7 in /opt/py3/lib/python3.6/site-packages (from paramiko)
Requirement already satisfied: bcrypt>=3.1.3 in /opt/py3/lib/python3.6/site-packages (from paramiko)
Requirement already satisfied: cryptography>=1.5 in /opt/py3/lib/python3.6/site-packages (from paramiko)
Requirement already satisfied: six in /opt/py3/lib/python3.6/site-packages (from pynacl>=1.0.1->paramiko)
Requirement already satisfied: cffi>=1.4.1 in /opt/py3/lib/python3.6/site-packages (from pynacl>=1.0.1->paramiko)
Requirement already satisfied: asn1crypto>=0.21.0 in /opt/py3/lib/python3.6/site-packages (from cryptography>=1.5->paramiko)
Requirement already satisfied: idna>=2.1 in /opt/py3/lib/python3.6/site-packages (from cryptography>=1.5->paramiko)
Requirement already satisfied: pycparser in /opt/py3/lib/python3.6/site-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko)

**Comment by buguoqiang** [comment]
(py3) [root@localhost requirements]# pip show paramiko
Name: paramiko
Version: 2.4.0
Summary: SSH2 protocol library
Home-page: https://github.com/paramiko/paramiko/
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: LGPL
Location: /opt/py3/lib/python3.6/site-packages
Requires: bcrypt, cryptography, pyasn1, pynacl

**Comment by ibuler** [comment]
升级你的pip 再重新安装试试

`pip install --upgrade pip`

**Comment by buguoqiang** [comment]
之前就升级过了，问题依旧。


(py3) [root@localhost requirements]# pip -V
pip 9.0.1 from /opt/py3/lib/python3.6/site-packages (python 3.6)
(py3) [root@localhost requirements]# pip install --upgrade pip
Requirement already up-to-date: pip in /opt/py3/lib/python3.6/site-packages
(py3) [root@localhost requirements]# pip install jumpserver-python-sdk
Collecting jumpserver-python-sdk
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0a/fe/348265e560bcc7fe2be677c45a54315e208bb826a25e0c7b8212fc1a759c/jumpserver-python-sdk-0.0.27.tar.gz
Collecting paramiko==2.4.0s (from jumpserver-python-sdk)
  Could not find a version that satisfies the requirement paramiko==2.4.0s (from jumpserver-python-sdk) (from versions: 0.1-bulbasaur, 0.1-charmander, 0.9-doduo, 0.9-eevee, 0.9-fearow, 0.9-gyarados, 0.9-horsea, 0.9-ivysaur, 1.0, 1.1, 1.2, 1.3, 1.3.1, 1.4, 1.5.1, 1.5.2, 1.5.4, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.7, 1.7.1, 1.7.2, 1.7.4, 1.7.5, 1.7.6, 1.7.7.1, 1.7.7.2, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.12.0, 1.12.1, 1.12.2, 1.12.3, 1.12.4, 1.13.0, 1.13.1, 1.13.2, 1.13.3, 1.13.4, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0)
No matching distribution found for paramiko==2.4.0s (from jumpserver-python-sdk)
(py3) [root@localhost requirements]#

**Comment by buguoqiang** [comment]
谢谢老广，重装一次，OK了。问题不知道在哪里，哈哈
