### ISSUE TITLE
[Question] v3.0.2版本资产连通性测试失败

### ISSUE THREAD

**Issue by csh0101** [jumpserver/jumpserver#9825]
**请描述您的问题.**
机器配置：Ubuntu 1C/1G
操作步骤： 
1.sshkey-gen ed25519 生成一对密钥对
2.公钥加入到资产的authorize_keys文件中
3.私钥贴在账号上，用户名为root，设置成特权账号。
4.点击连通性测试，执行ansible，连通性任务，发生报错。
报错信息如下：

Task assets.tasks.ping.test_assets_connectivity_task[f7f3e5d3-ac29-4c28-bbe0-bda0896084cd] raised unexpected: Exception('Not implemented in PKey')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/jumpserver/apps/assets/tasks/ping.py", line 31, in test_assets_connectivity_task
    quickstart_automation(task_name, AutomationTypes.ping, task_snapshot)
  File "/opt/jumpserver/apps/assets/tasks/common.py", line 47, in quickstart_automation
    execution.start()
  File "/opt/jumpserver/apps/assets/models/automations/base.py", line 158, in start
    return manager.run()
  File "/opt/jumpserver/apps/assets/automations/endpoint.py", line 19, in run
    return self._runner.run(*args, **kwargs)
  File "/opt/jumpserver/apps/assets/automations/base/manager.py", line 280, in run
    runners = self.get_runners()
  File "/opt/jumpserver/apps/assets/automations/base/manager.py", line 175, in get_runners
    self.generate_inventory(_assets, inventory_path)
  File "/opt/jumpserver/apps/assets/automations/base/manager.py", line 141, in generate_inventory
    inventory.write_to_file(inventory_path)
  File "/opt/jumpserver/apps/ops/ansible/inventory.py", line 219, in write_to_file
    data = self.generate(path_dir)
  File "/opt/jumpserver/apps/ops/ansible/inventory.py", line 183, in generate
    host = self.asset_to_host(asset, account, automation, protocols, platform)
  File "/opt/jumpserver/apps/ops/ansible/inventory.py", line 139, in asset_to_host
    self.make_ssh_account_vars(host, asset, account, automation, protocols, platform, gateway)
  File "/opt/jumpserver/apps/ops/ansible/inventory.py", line 97, in make_ssh_account_vars
    host.update(self.make_account_ansible_vars(account))
  File "/opt/jumpserver/apps/ops/ansible/inventory.py", line 72, in make_account_ansible_vars
    var['ansible_ssh_private_key_file'] = account.private_key_path
  File "/opt/jumpserver/apps/accounts/models/base.py", line 121, in private_key_path
    self.private_key_obj.write_private_key_file(key_path)
  File "/usr/local/lib/python3.9/site-packages/paramiko/pkey.py", line 285, in write_private_key_file
    raise Exception("Not implemented in PKey")
Exception: Not implemented in PKey

疑惑：
1. 在完成账号授权后 Web Terminal登录端可以顺利登录那台不连通的机器，对此感到奇怪。

**Comment by csh0101** [comment]
<img width="595" alt="Screen Shot 2023-03-01 at 16 33 01" src="https://user-images.githubusercontent.com/44041710/222086280-452a3b54-cc5c-4e5b-bfea-76bcaf0618df.png">
怀疑是不是这里SSH密钥写的有问题？不应该写私钥么

**Comment by csh0101** [comment]
看了下代码，感觉是提示我账户信息的密钥就不是一个私钥 我对此感到困惑。因为就如截图上所见，它确实是一个私钥，因为我可以通过Web Termnial登录到该资产上

**Comment by csh0101** [comment]
追加：
刚才使用的是ED25519、OPENSSH格式的私钥，导致了连通性检测失败。
现在换成了RSA SHA256 PEM的私钥，连通性检测就可以成功了。
结论：ED25519的支持度存疑

**Comment by csh0101** [comment]
结论: paramiko的private_key_write_file方法支持的是PEM的序列化协议，所以怀疑这一点导致的ETD25519的Key(bytes)在序列化时发生失败，建议在private_key_write_file前加上 私钥的格式check。 @wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
收到反馈，我们验证下
