### ISSUE TITLE
[Bug] 编译安装后无法启动

### ISSUE THREAD

**Issue by PikuZheng** [jumpserver/jumpserver#9981]
**JumpServer 版本( v2.28 之前的版本不再支持 )**
3.0.4

**浏览器版本**
不涉及

**Bug 描述**
严格按照 https://docs.jumpserver.org/zh/v3/installation/source_install/core_install/#14-python 操作，编译成功，启动时报错
```
localhost:/opt/jumpserver-v3.0.4# ./jms start -d
Traceback (most recent call last):
  File "/opt/jumpserver-v3.0.4/./jms", line 21, in <module>
    django.setup()
  File "/opt/py3/lib/python3.10/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/opt/py3/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/py3/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/py3/lib/python3.10/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/jumpserver-v3.0.4/apps/jumpserver/settings/__init__.py", line 3, in <module>
    from .base import *
  File "/opt/jumpserver-v3.0.4/apps/jumpserver/settings/base.py", line 14, in <module>
    from .. import const
  File "/opt/jumpserver-v3.0.4/apps/jumpserver/const.py", line 12, in <module>
    CONFIG = ConfigManager.load_user_config()
  File "/opt/jumpserver-v3.0.4/apps/jumpserver/conf.py", line 865, in load_user_config
    elif manager.load_from_yml():
  File "/opt/jumpserver-v3.0.4/apps/jumpserver/conf.py", line 850, in load_from_yml
    loaded = self.from_yaml(i)
  File "/opt/jumpserver-v3.0.4/apps/jumpserver/conf.py", line 801, in from_yaml
    obj = yaml.safe_load(f)
  File "/opt/py3/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/opt/py3/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/opt/py3/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/opt/py3/lib/python3.10/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/opt/py3/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/opt/py3/lib/python3.10/site-packages/yaml/parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "/opt/jumpserver-v3.0.4/config.yml", line 8, column 1
```

**Bug 重现步骤(有截图更好)**
1. 严格按照 https://docs.jumpserver.org/zh/v3/installation/source_install/core_install/#14-python 操作编译
2. 启动
3.

**Comment by LeeEirc** [comment]
配置文件问题，不符合 yaml 格式

**Comment by PikuZheng** [comment]
配置文件除了填了两个key，没做其他改动
```
(py3) localhost:/opt/jumpserver-v3.0.4# diff config_example.yml config.yml
--- config_example.yml
+++ config.yml
@@ -1,11 +1,11 @@
 # SECURITY WARNING: keep the secret key used in production secret!
 # 加密密钥 生产环境中请修改为随机字符串，请勿外泄, 可使用命令生成
 # $ cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 49;echo
-SECRET_KEY:
+SECRET_KEY:UgJFdr3SK5aUXoPl2ieF01RF6xdQ7qRZbftez6Rx4UESPwynIU

 # SECURITY WARNING: keep the bootstrap token used in production secret!
 # 预共享Token coco和guacamole用来注册服务账号，不在使用原来的注册接受机制
-BOOTSTRAP_TOKEN:
+BOOTSTRAP_TOKEN:CCAGGqPyMOpQwEd3RdDE

 # Development env open this, when error occur display the full process track, Production disable it
 # DEBUG 模式 开启DEBUG后遇到错误时可以看到更多日志
(py3) localhost:/opt/jumpserver-v3.0.4#
```

**Comment by PikuZheng** [comment]
解决了。。。yaml需要在冒号后加空格
