### ISSUE TITLE
tail -n 300 catalina.out 输出日志过多后web终端卡死

### ISSUE THREAD

**Issue by zhaofei91** [jumpserver/jumpserver#999]
[简述你的问题]

##### 使用版本
[Version 0.5.0-2 GPLv2.]

##### 问题复现步骤
1. web终端 tail -n 300 catalina.out
2. web终端卡死
3. web终端退出，在线会话中依然显示在线
4. 在线会话-点击终断后依然在线
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/coco/coco/app.py", line 147, in func
    self.heartbeat()
  File "/opt/coco/coco/app.py", line 130, in heartbeat
    self.handle_task(tasks)
  File "/opt/coco/coco/app.py", line 142, in handle_task
    self.task_handler.handle(task)
  File "/opt/coco/coco/tasks.py", line 35, in handle
    self.handle_kill_session(task)
  File "/opt/coco/coco/tasks.py", line 30, in handle_kill_session
    session.terminate()
  File "/opt/coco/coco/session.py", line 109, in terminate
    self.client.send(msg)
  File "/opt/coco/coco/models.py", line 46, in send
    return self.chan.send(b)
BrokenPipeError: [Errno 32] Broken pipe
5. 历史会话-回放提示无法下载 

##### 具体表现[截图可能会更好些,最好能截全]
必须重启coco，之前退出的会话才会kill
2018-02-06 11:27:22 [app DEBUG] Loading config from server: {"COMMAND_STORAGE": {"TYPE": "server"}}
Tue Feb  6 11:27:22 2018
Coco version 0.5.0, more see https://www.jumpserver.org
Quit the server with CONTROL-C.
Starting ssh server at 0.0.0.0:2222
Starting websocket server at 0.0.0.0:5000
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2018-02-06 11:27:23 [tasks INFO] Handle kill session task: 76920108-a4f2-4df5-8796-11dc5a5eb4cc
2018-02-06 11:27:23 [tasks INFO] Handle kill session task: 76920108-a4f2-4df5-8796-11dc5a5eb4cc

##### 其他

[注:] 完成后请关闭 issue

**Comment by hacker0001** [comment]
我也出现了这个问题，我的版本是0.50，重启一下coco后正常

**Comment by hacker0001** [comment]
我在web端直接开5个链接之后，再服务器全部断开，在线回话里面还是有5个链接，coco显示在线，我重启一下coco后，在线会话才会清空

**Comment by ibuler** [comment]
fixed ，有问题请打开
